import test,{after} from 'node:test';import assert from 'node:assert/strict';import express from 'express';import sql from 'mssql';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64)});
const {platformRouter}=await import('../dist/routes/platform.js');const id='12345678-1234-4234-8234-123456789abc';let selected,eligible=true,started=true,writes=0;const originalQuery=sql.Request.prototype.query,originalConnect=sql.ConnectionPool.prototype.connect;sql.ConnectionPool.prototype.connect=async()=>({connected:true,config:{},request:()=>new sql.Request()});sql.Request.prototype.query=async function(text){if(text.includes('SELECT TOP 1 Id FROM CommunityMembers'))return{recordset:[{Id:'member'}]};if(text.includes('SELECT TOP 1 s.MeetingId')){assert.match(text,/m.StartDateTime<=SYSUTCDATETIME/);selected=this.parameters.meeting?.value;assert.match(text,/@meeting IS NULL OR m.Id=@meeting/);return{recordset:selected===id&&started?[{MeetingId:id,StartDateTime:new Date(),EndDateTime:new Date(Date.now()+3600000)}]:[]}}if(text.includes('SELECT * FROM Meetings'))return{recordset:[{Id:id,CommunityId:'c',SettingsJson:'{}'}]};if(text.includes('SELECT dbo.CanAttendMeeting'))return{recordset:[{Allowed:eligible}]};if(text.includes('MERGE MeetingAttendance'))writes++;return{recordset:[]}};
const app=express();app.use(express.json(),(req,res,next)=>{req.user={id:'user'};next()});const route=platformRouter.stack.find(s=>s.route?.path==='/communities/:communityId/attendance/mark');app.post('/communities/:communityId/attendance/mark',route.route.stack.at(-1).handle);app.use((e,req,res,next)=>res.status(e.status||400).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const send=body=>fetch('http://127.0.0.1:'+server.address().port+'/communities/c/attendance/mark',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});after(()=>{sql.Request.prototype.query=originalQuery;sql.ConnectionPool.prototype.connect=originalConnect;server.closeAllConnections();server.close()});
test('check-in validates six digits and the selected meeting ID',async()=>{assert.equal((await send({code:'123',meetingId:id})).status,400);assert.equal((await send({code:'123456',meetingId:'bad'})).status,400);assert.equal(writes,0)});
test('code must match the selected meeting and attendance eligibility',async()=>{assert.equal((await send({code:'123456',meetingId:'22345678-1234-4234-8234-123456789abc'})).status,400);eligible=false;assert.equal((await send({code:'123456',meetingId:id})).status,403);assert.equal(writes,0);eligible=true});
test('valid selected meeting check-in records attendance',async()=>{assert.equal((await send({code:'123456',meetingId:id})).status,200);assert.equal(selected,id);assert.equal(writes,1)});

test('meeting codes reject check-in before the scheduled start',async()=>{started=false;const before=writes;assert.equal((await send({code:'123456',meetingId:id})).status,400);assert.equal(writes,before);started=true});
