import test,{after} from 'node:test';import assert from 'node:assert/strict';import express from 'express';import sql from 'mssql';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64)});
const{chatRouter}=await import('../dist/routes/chat.js');const u='11111111-1111-4111-8111-111111111111',c='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333';let mode='',writes=[],rollbacks=0;
const old={connect:sql.ConnectionPool.prototype.connect,query:sql.Request.prototype.query,begin:sql.Transaction.prototype.begin,commit:sql.Transaction.prototype.commit,rollback:sql.Transaction.prototype.rollback};sql.ConnectionPool.prototype.connect=async()=>({connected:true,request:()=>new sql.Request()});sql.Transaction.prototype.begin=async()=>{};sql.Transaction.prototype.commit=async()=>{};sql.Transaction.prototype.rollback=async()=>{rollbacks++};sql.Request.prototype.query=async function(q){writes.push(q);if(q.includes('FROM Communities c WHERE c.Id=@c AND'))return{recordset:mode==='member'?[]:[{ok:1}]};if(q.includes("AccountStatus='ACTIVE' AND EmailVerified=1"))return{recordset:mode==='unverified'?[]:[{Id:u}]};if(q.includes('SELECT COUNT(*) Count'))return{recordset:[{Count:mode==='quota'?5:0}]};if(q.includes('SELECT cm.UserId'))return{recordset:mode==='outsider'?[{UserId:u}]:[{UserId:u},{UserId:other}]};if(q.includes('LOWER(LTRIM(RTRIM(Name)))'))return{recordset:mode==='duplicate'?[{Id:c}]:[]};return{recordset:[{Id:c}]}};
const app=express();app.use(express.json(),(req,res,next)=>{req.user={id:u};next()});const layer=chatRouter.stack.find(x=>x.route?.path==='/communities/:communityId/conversations'&&x.route.methods.post);app.post('/communities/:communityId/conversations',...layer.route.stack.map(x=>x.handle));app.use((e,req,res,next)=>res.status(e.status??(e.name==='ZodError'?400:500)).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));after(()=>{sql.ConnectionPool.prototype.connect=old.connect;sql.Request.prototype.query=old.query;sql.Transaction.prototype.begin=old.begin;sql.Transaction.prototype.commit=old.commit;sql.Transaction.prototype.rollback=old.rollback;server.closeAllConnections();server.close()});
const call=body=>fetch('http://127.0.0.1:'+server.address().port+'/communities/'+c+'/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Test group',memberUserIds:[other],...body})});
test('ordinary members cannot create groups even when member discussions are allowed',async()=>{mode='member';writes=[];assert.equal((await call({})).status,403);assert.ok(!writes.some(q=>q.includes('INSERT INTO Conversations')));assert.doesNotMatch(writes.at(-1),/AllowMemberDiscussions/)});
test('unverified creators, daily bursts, outsiders and duplicate groups fail before group insertion',async()=>{for(const[value,status]of[['unverified',403],['quota',429],['outsider',400],['duplicate',409]]){mode=value;writes=[];const before=rollbacks;assert.equal((await call({})).status,status);assert.ok(!writes.some(q=>q.includes('INSERT INTO Conversations')));assert.equal(rollbacks,before+1)}mode=''});
test('self-only selection and oversized membership requests are refused',async()=>{mode='';assert.equal((await call({memberUserIds:[u]})).status,400);assert.equal((await call({memberUserIds:Array(201).fill(other)})).status,400)});
