import test,{after} from 'node:test';import assert from 'node:assert/strict';import express from 'express';import sql from 'mssql';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64)});
const {discoveryRouter}=await import('../dist/routes/discovery.js');const {privacyRouter}=await import('../dist/routes/privacy.js');const uid='a9b1c630-0be5-426c-b145-578eb4da9181',cid='bd6c205a-8085-4236-a5ac-d476f0b03cec';let enabled=false,manager=false,queries=[];const originalConnect=sql.ConnectionPool.prototype.connect,originalQuery=sql.Request.prototype.query;const pool={connected:true,config:{},request(){return new sql.Request()}};sql.ConnectionPool.prototype.connect=async()=>pool;sql.Request.prototype.query=async function(query){const params=Object.fromEntries(Object.entries(this.parameters).map(([k,v])=>[k,v.value]));queries.push({query,params});if(query.startsWith('SELECT ShareLocation'))return{recordset:[{ShareLocation:enabled}]};if(query.includes('JOIN Communities community'))return{recordset:manager?[{ok:1}]:[]};return{recordset:[]}};
const app=express();app.use(express.json());app.use((req,res,next)=>{req.user={id:uid};next()});app.use(discoveryRouter);app.use(privacyRouter);app.use((e,req,res,next)=>res.status(e.status??400).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));after(()=>{sql.ConnectionPool.prototype.connect=originalConnect;sql.Request.prototype.query=originalQuery;server.closeAllConnections();server.close()});const call=(path,body,method='POST')=>fetch(`http://127.0.0.1:${server.address().port}${path}`,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
test('nearby search requires opt-in and never queries directory when disabled',async()=>{queries=[];const r=await call('/discover/search',{latitude:6.6,longitude:3.3});assert.equal(r.status,403);assert.equal(queries.length,1);assert.equal(queries[0].params.u,uid)});
test('coordinate pair and ranges are validated before SQL',async()=>{for(const body of [{latitude:6},{latitude:91,longitude:3},{latitude:6,longitude:181},{latitude:6,longitude:3,radius:300}]){queries=[];assert.equal((await call('/discover/search',body)).status,400);assert.equal(queries.length,0)}});
test('nearby query applies server radius, excludes unmapped groups, and does not store user location',async()=>{enabled=true;queries=[];const r=await call('/discover/search',{latitude:6.6,longitude:3.3,radius:25});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');const q=queries[1];assert.equal(q.params.lat,6.6);assert.equal(q.params.lng,3.3);assert.equal(q.params.radius,25);assert.match(q.query,/distance.DistanceKm<=@radius/);assert.match(q.query,/c.Latitude BETWEEN -90 AND 90/);assert.doesNotMatch(q.query,/INSERT|UPDATE/)});
test('name search supports category and pagination without device coordinates',async()=>{queries=[];assert.equal((await call('/discover/search?q=Sports%20club&area=Ikeja&category=Sports&offset=60',null,'GET')).status,200);assert.equal(queries.length,1);assert.equal(queries[0].params.area,'Ikeja');assert.equal(queries[0].params.category,'Sports');assert.equal(queries[0].params.offset,60);assert.equal(queries[0].params.lat,null)});
test('saved community is scoped to authenticated user',async()=>{queries=[];assert.equal((await call('/'+cid+'/saved',{saved:true},'PUT')).status,200);assert.equal(queries[0].params.u,uid);assert.equal(queries[0].params.c,cid);assert.match(queries[0].query,/WITH\(HOLDLOCK\)/)});
test('privacy toggle is persisted and accepts boolean only',async()=>{queries=[];assert.equal((await call('/privacy',{key:'shareLocation',value:true},'PATCH')).status,200);assert.equal(queries[0].params.u,uid);assert.equal(queries[0].params.v,true);assert.match(queries[0].query,/ShareLocation=@v/);assert.equal((await call('/privacy',{key:'shareLocation',value:'true'},'PATCH')).status,400)});
test('only community managers may update map position',async()=>{queries=[];assert.equal((await call('/'+cid+'/location',{latitude:6.6,longitude:3.3},'PATCH')).status,403);assert.ok(!queries.some(q=>q.query.includes('UPDATE Communities')));manager=true;queries=[];assert.equal((await call('/'+cid+'/location',{latitude:6.6,longitude:3.3},'PATCH')).status,200);assert.equal(queries.at(-1).params.c,cid)});

test('empty discovery never returns a global directory',async()=>{queries=[];const r=await call('/discover/search',null,'GET');assert.deepEqual(await r.json(),[]);assert.equal(queries.length,0)});
test('name search bypasses distance and matches only names',async()=>{queries=[];await call('/discover/search',{q:'Royal View',latitude:6.6,longitude:3.3});assert.equal(queries.length,1);assert.equal(queries[0].params.lat,null);assert.match(queries[0].query,/LOWER\(c.Name\)/)});
