import test,{after} from 'node:test';import assert from 'node:assert/strict';import express from 'express';import sql from 'mssql';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64)});const {communitiesRouter}=await import('../dist/routes/communities.js');const {requirePermission}=await import('../dist/services/permissions.js');const uid='a9b1c630-0be5-426c-b145-578eb4da9181',cid='bd6c205a-8085-4236-a5ac-d476f0b03cec';let queries=[],mode='',accountCountry='Nigeria',commits=0,rollbacks=0;const pool={connected:true,config:{},request(){return new sql.Request()}};
const originals={connect:sql.ConnectionPool.prototype.connect,begin:sql.Transaction.prototype.begin,commit:sql.Transaction.prototype.commit,rollback:sql.Transaction.prototype.rollback,query:sql.Request.prototype.query};sql.ConnectionPool.prototype.connect=async()=>pool;sql.Transaction.prototype.begin=async()=>{};sql.Transaction.prototype.commit=async()=>{commits++};sql.Transaction.prototype.rollback=async()=>{rollbacks++};sql.Request.prototype.query=async function(query){const params=Object.fromEntries(Object.entries(this.parameters).map(([k,v])=>[k,v.value]));queries.push({query,params});if(query.includes("AccountStatus='ACTIVE' AND EmailVerified=1"))return{recordset:mode==='unverified'?[]:[{Id:uid}]};if(query.includes('RecentCount'))return{recordset:[{RecentCount:mode==='daily-limit'?1:0,UnverifiedCount:mode==='pending-limit'?3:0}]};if(query.includes('FROM Communities WITH(UPDLOCK,HOLDLOCK) WHERE LOWER'))return{recordset:mode==='existing-community'?[{Id:cid}]:[]};if(query.includes('SELECT Country FROM Users'))return{recordset:[{Country:accountCountry}]};if(query.includes('FROM Communities c WHERE c.Id=@c AND'))return{recordset:mode==='member-denied'?[]:[{ok:1}]};if(query.includes('FROM StoredObjects'))return{recordset:mode==='invalid-image'?[]:[{PublicUrl:'https://cdaconnect.org/uploads/logo.png'}]};if(query.startsWith('INSERT INTO Communities')){if(mode==='duplicate')throw{number:2627};return{recordset:[{Id:cid,JoinCode:params.code,LogoUrl:params.logo}]}}return{recordset:[{Id:cid}]}};
const handler=communitiesRouter.stack.find(x=>x.route?.path==='/'&&x.route.methods.post).route.stack.at(-1).handle;const app=express();app.use(express.json());app.post('/',(req,res,next)=>{req.user={id:uid};next()},handler);app.use((e,req,res,next)=>res.status(e.status??(e.name==='ZodError'?400:500)).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));after(()=>{sql.ConnectionPool.prototype.connect=originals.connect;sql.Transaction.prototype.begin=originals.begin;sql.Transaction.prototype.commit=originals.commit;sql.Transaction.prototype.rollback=originals.rollback;sql.Request.prototype.query=originals.query;server.closeAllConnections();server.close()});const send=body=>fetch('http://127.0.0.1:'+server.address().port,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'My Community',stateId:'NG025',localArea:'Ikeja',guidelines:'Be respectful',...body})});
test('creation generates its own invite code instead of trusting client input',async()=>{queries=[];const response=await send({joinCode:'a b!'});assert.equal(response.status,201);assert.match((await response.json()).JoinCode,/^[A-F0-9]{16}$/)});
test('creation persists image, code, category and rules with owner membership and approval defaults',async()=>{queries=[];mode='';const r=await send({joinCode:' riverside1 ',logoUploadId:uid,category:'Sports',guidelines:'Be respectful'});assert.equal(r.status,201);const insertion=queries.find(x=>x.query.startsWith('INSERT INTO Communities'));assert.match(insertion.params.code,/^[A-F0-9]{16}$/);assert.notEqual(insertion.params.code,'RIVERSIDE1');assert.equal(insertion.params.logo,'https://cdaconnect.org/uploads/logo.png');assert.equal(insertion.params.category,'Sports');assert.equal(insertion.params.guidelines,'Be respectful');assert.equal(insertion.params.owner,uid);assert.equal(insertion.params.priv,true);assert.equal(insertion.params.approval,true);const image=queries.find(x=>x.query.includes('FROM StoredObjects'));assert.equal(image.params.u,uid);assert.match(image.query,/IsPrivate=0/);assert.match(image.query,/SizeBytes<=5242880/);assert.ok(queries.some(x=>x.query.includes('CommunityMemberRoles')));assert.ok(commits>0)});
test('creation refuses unavailable uploads and rolls back duplicate codes',async()=>{mode='invalid-image';queries=[];assert.equal((await send({logoUploadId:uid})).status,400);assert.ok(!queries.some(x=>x.query.startsWith('INSERT')));mode='duplicate';const before=rollbacks;assert.equal((await send({joinCode:'RIVERSIDE1'})).status,409);assert.equal(rollbacks,before+1);mode=''});

test('rules and location selections are mandatory and validated',async()=>{assert.equal((await send({guidelines:'  '})).status,400);assert.equal((await send({stateId:'not-a-state'})).status,400);assert.equal((await send({localArea:'not-an-area'})).status,400)});
test('creation ignores a forged country and uses the authenticated account country',async()=>{queries=[];assert.equal((await send({countryCode:'GB',country:'United Kingdom'})).status,201);const insertion=queries.find(x=>x.query.startsWith('INSERT INTO Communities'));assert.equal(insertion.params.country,'Nigeria');assert.equal(insertion.params.currency,'NGN')});
test('creation requires a supported account country',async()=>{accountCountry='Unknown';assert.equal((await send({})).status,400);accountCountry='Nigeria'});

test('events obey community preferences while chat creation is restricted to administrators',async()=>{mode='member-denied';await assert.rejects(requirePermission(uid,cid,'EVENT_CREATE'),e=>e.status===403);await assert.rejects(requirePermission(uid,cid,'CHAT_CREATE'),e=>e.status===403);mode='';await requirePermission(uid,cid,'EVENT_CREATE');await requirePermission(uid,cid,'CHAT_CREATE');const checks=queries.filter(x=>x.query.includes('FROM Communities c WHERE c.Id=@c AND'));assert.ok(checks.every(x=>x.params.c===cid&&x.params.u===uid));assert.match(checks[0].query,/AllowMemberEvents=1/);const group=checks.find(x=>!x.query.includes('AllowMemberEvents'));assert.doesNotMatch(group.query,/AllowMemberDiscussions=1/);assert.match(group.query,/role.Name IN \('Owner','Admin'\)/)});

test('public visibility and participation options are persisted',async()=>{mode='';queries=[];assert.equal((await send({isPrivate:false,allowMemberEvents:false,allowMemberDiscussions:false})).status,201);const p=queries.find(x=>x.query.startsWith('INSERT INTO Communities')).params;assert.equal(p.priv,false);assert.equal(p.events,false);assert.equal(p.discussions,false)});


test('community creation rejects unverified accounts, daily bursts, excess pending communities and duplicates before insert',async()=>{for(const [value,status] of [['unverified',403],['daily-limit',429],['pending-limit',403],['existing-community',409]]){mode=value;queries=[];assert.equal((await send({})).status,status);assert.ok(!queries.some(q=>q.query.startsWith('INSERT INTO Communities')))}mode=''});
