import test,{after} from 'node:test';import assert from 'node:assert/strict';import sql from 'mssql';import nodemailer from 'nodemailer';import {readFile} from 'node:fs/promises';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64),EMAIL_PROVIDER:'smtp',SMTP_USER:'test@example.com',SMTP_PASSWORD:'test'});
const {planDelivery,claimDelivery,finishDelivery,completeOutbox}=await import('../dist/services/deliveryLedger.js');const {sendEmailRecipient}=await import('../dist/services/notifications.js');
const orig={connect:sql.ConnectionPool.prototype.connect,query:sql.Request.prototype.query,transport:nodemailer.createTransport};const deliveries=new Map();let sealed=false,complete=false,expected=0,terminal=0;
sql.ConnectionPool.prototype.connect=async()=>({connected:true,config:{},request:()=>new sql.Request()});sql.Request.prototype.query=async function(text){const p=Object.fromEntries(Object.entries(this.parameters).map(([k,v])=>[k,v.value])),key=[p.n,p.u,p.ch,p.hash].join(':');
 if(text.includes('INSERT INTO NotificationDeliveries')){if(!deliveries.has(key))deliveries.set(key,p.s)}
 else if(text.includes('OUTPUT INSERTED.UserId')){if(deliveries.get(key)==='QUEUED'){deliveries.set(key,'PROCESSING');return {recordset:[{UserId:p.u}]}}}
 else if(text.includes('UPDATE NotificationDeliveries SET Status=@s')){assert.match(text,/UserId=@u AND Channel=@ch AND DestinationHash=@hash/);if(['QUEUED','PROCESSING'].includes(deliveries.get(key)))deliveries.set(key,p.s)}
 else if(text.includes('UPDATE o SET')){sealed ||= !!p.seal;expected=deliveries.size;terminal=[...deliveries.values()].filter(s=>!['QUEUED','PROCESSING'].includes(s)).length;complete=sealed&&expected===terminal;assert.match(text,/DispatchComplete=1 OR @seal=1/)}
 else throw Error('Unexpected SQL');return {recordset:[]};};
after(()=>{sql.ConnectionPool.prototype.connect=orig.connect;sql.Request.prototype.query=orig.query;nodemailer.createTransport=orig.transport});
const target=(user,channel='PUSH',destination=user)=>({notificationId:'notification',userId:user,channel,destination});
test('one successful device cannot mark another user or device sent',async()=>{await planDelivery(target('one'));await planDelivery(target('two'));await planDelivery(target('one','PUSH','second'));assert.equal(await claimDelivery(target('one')),true);assert.equal(await claimDelivery(target('one')),false);await finishDelivery(target('one'),'SENT');await completeOutbox('notification',true);assert.equal(expected,3);assert.equal(terminal,1);assert.equal(complete,false);assert.equal(await claimDelivery(target('one')),false)});
test('muted, no-device, skipped, rejected and unknown outcomes terminate without receipts',async()=>{await finishDelivery(target('two'),'MUTED');await finishDelivery(target('one','PUSH','second'),'FAILED');for(const [user,status]of [['three','NO_DEVICE'],['four','SKIPPED'],['five','UNKNOWN']])await planDelivery(target(user),status);await completeOutbox('notification',true);assert.equal(complete,true);assert.equal(expected,6);assert.equal(terminal,6)});
test('no recipient outbox completes only after discovery is sealed',async()=>{deliveries.clear();sealed=false;await completeOutbox('notification');assert.equal(complete,false);await completeOutbox('notification',true);assert.equal(complete,true);assert.equal(expected,0)});
test('in-app availability is independent from pending email',async()=>{deliveries.clear();sealed=false;await planDelivery(target('one','IN_APP'),'SENT');await planDelivery(target('one','EMAIL'));await completeOutbox('notification',true);assert.equal(complete,false);await finishDelivery(target('one','EMAIL'),'SKIPPED');assert.equal(complete,true)});
test('each accepted emergency email returns its provider ID before the next send',async()=>{let count=0;nodemailer.createTransport=()=>({close(){},async sendMail(){count++;if(count===2)throw Object.assign(Error('rejected'),{responseCode:550});return {accepted:['one@example.com'],rejected:[],messageId:'provider-1'}}});const mail={to:'one@example.com',subject:'Emergency',text:'Message'};assert.deepEqual(await sendEmailRecipient(mail,'one'),{status:'SENT',providerId:'provider-1'});assert.equal((await sendEmailRecipient(mail,'two')).status,'FAILED');nodemailer.createTransport=()=>({close(){},async sendMail(){throw Error('socket lost')}});assert.equal((await sendEmailRecipient(mail,'three')).status,'UNKNOWN')});
test('worker never blanket-marks push sent and recovery covers stalled outbox states',async()=>{const worker=await readFile(new URL('../src/workers/worker.ts',import.meta.url),'utf8');assert.doesNotMatch(worker,/UPDATE UserNotifications SET DeliveryStatus='SENT' WHERE NotificationId/);assert.match(worker,/Status IN\('QUEUED','PROCESSING','DISPATCHED'\)/);assert.match(worker,/Status='UNKNOWN'/);assert.match(worker,/completeOutbox\(d.notificationId,true\)/);assert.match(worker,/notificationId:d.notificationId,userId,communityId/);assert.doesNotMatch(worker,/sendEmailBatch/)});
