import test,{after} from 'node:test';import assert from 'node:assert/strict';import sql from 'mssql';import {readFile} from 'node:fs/promises';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64)});
const {documentVisibility,requireDocumentView}=await import('../dist/services/documentAccess.js');
const original={connect:sql.ConnectionPool.prototype.connect,query:sql.Request.prototype.query};let permitted=true;
sql.ConnectionPool.prototype.connect=async()=>({connected:true,config:{},request:()=>new sql.Request()});sql.Request.prototype.query=async function(text){assert.ok(text.includes(documentVisibility));assert.equal(this.parameters.u.value,'viewer');return {recordset:permitted?[{Id:'document'}]:[]}};
after(()=>{sql.ConnectionPool.prototype.connect=original.connect;sql.Request.prototype.query=original.query});
test('MEMBERS and authorized ADMINS use the shared predicate',async()=>{permitted=true;assert.equal((await requireDocumentView('viewer','document')).Id,'document');assert.match(documentVisibility,/d.Visibility='MEMBERS'/);assert.match(documentVisibility,/d.Visibility='ADMINS'/);assert.match(documentVisibility,/DOCUMENT_MANAGE/)});
for(const [name,rule]of [['wrong role',/accessRole.RoleId=accessRule.RoleId/],['removed member',/viewerMember.Status='ACTIVE'/],['suspended account',/viewer.AccountStatus='ACTIVE'/],['denied role',/accessRule.CanView=1/]])test(name+' is denied by the authoritative query',async()=>{assert.match(documentVisibility,rule);permitted=false;await assert.rejects(()=>requireDocumentView('viewer','document'),{status:404})});
test('list and both AI paths embed the complete predicate; download and history call the shared guard',async()=>{const source=await readFile(new URL('../src/routes/advanced.ts',import.meta.url),'utf8');assert.equal(source.split('${documentVisibility}').length-1,3);assert.doesNotMatch(source,/d.Visibility='MEMBERS'/);for(const path of ["'/documents/:documentId/history'","'/documents/:documentId/download-url'"]){const route=source.split(path)[1].split('\n')[0];assert.match(route,/requireDocumentView/)}assert.match(await readFile(new URL('../src/routes/media.ts',import.meta.url),'utf8'),/\$\{documentVisibility\}/)});
