import test,{after} from 'node:test';import assert from 'node:assert/strict';import express from 'express';import sql from 'mssql';import {Redis} from 'ioredis';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',STORAGE_DRIVER:'local',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64)});
const tokens=new Map(),oldRedis={};for(const k of ['connect','get','set','incr','expire'])oldRedis[k]=Redis.prototype[k];Redis.prototype.connect=async()=>{};Redis.prototype.get=async k=>tokens.get(k);Redis.prototype.set=async(k,v)=>{tokens.set(k,v);return 'OK'};Redis.prototype.incr=async()=>1;Redis.prototype.expire=async()=>1;
const {mediaRouter}=await import('../dist/routes/media.js'),{deleteObject}=await import('../dist/services/storage.js'),{reportDetailsSchema,validateReportDetails}=await import('../dist/services/issueReports.js');
const originalConnect=sql.ConnectionPool.prototype.connect,originalQuery=sql.Request.prototype.query;let member=true,allowed=true,owned=true,record,queries=[];
sql.ConnectionPool.prototype.connect=async()=>({connected:true,config:{},request:()=>new sql.Request()});
sql.Request.prototype.query=async function(text){const p=Object.fromEntries(Object.entries(this.parameters).map(([k,v])=>[k,v.value]));queries.push({text,p});if(text.includes('SELECT TOP 1 Id FROM CommunityMembers'))return{recordset:member?[{Id:'member'}]:[]};if(text.includes('INSERT INTO StoredObjects')){record={StorageKey:p.k,MimeType:p.mime,OriginalName:p.name};return{recordset:[{Id:'22222222-2222-4222-8222-222222222222'}]}}if(text.includes('SELECT stored.StorageKey'))return{recordset:allowed&&record?[record]:[]};if(text.includes('SELECT OriginalName FROM StoredObjects'))return{recordset:owned?[{OriginalName:'proof.txt'}]:[]};if(text.includes('SELECT Id FROM CommunityMembers'))return{recordset:member?[{Id:'member'}]:[]};return{recordset:[]}};
const app=express();app.use(express.json(),(req,res,next)=>{req.user={id:'11111111-1111-4111-8111-111111111111'};next()});for(const layer of mediaRouter.stack){const route=layer.route;if(route&&['/media/upload','/communities/:communityId/issues/:issueId/evidence/:objectId','/media/issue-download/:token'].includes(route.path))app[Object.keys(route.methods)[0]](route.path,...route.stack.map(x=>x.handle))}app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port,c='33333333-3333-4333-8333-333333333333';
const {app:fullApp}=await import('../dist/app.js');const fullServer=fullApp.listen(0,'127.0.0.1');await new Promise(r=>fullServer.once('listening',r));const fullBase='http://127.0.0.1:'+fullServer.address().port+'/api/v1';
after(async()=>{fullServer.closeAllConnections();fullServer.close();if(record)await deleteObject(record.StorageKey);sql.ConnectionPool.prototype.connect=originalConnect;sql.Request.prototype.query=originalQuery;Object.assign(Redis.prototype,oldRedis);server.closeAllConnections();server.close()});
async function upload(){const f=new FormData();f.append('file',new Blob(['confidential evidence']),'proof.txt');return fetch(base+'/media/upload?purpose=issue&communityId='+c,{method:'POST',body:f})}
test('evidence upload requires community membership',async()=>{member=false;assert.equal((await upload()).status,403);member=true});
test('evidence stays private and download checks report access again',async()=>{const r=await upload();assert.equal(r.status,201);const data=await r.json();assert.equal(data.url,undefined);assert.match(record.StorageKey,/^private-issues\//);assert.equal(queries.find(q=>q.text.includes('INSERT INTO StoredObjects')).p.private,true);const response=await fetch(base+'/communities/'+c+'/issues/44444444-4444-4444-8444-444444444444/evidence/'+data.storedObjectId,{method:'POST'});assert.equal(response.status,200);const link=await response.json();const download=await fetch(fullBase+link.path);assert.equal(await download.text(),'confidential evidence');assert.equal(download.headers.get('cache-control'),'private, no-store');const query=queries.find(q=>q.text.includes('SELECT stored.StorageKey')).text;assert.match(query,/issue.ReportedBy=@u OR @manager=1/);assert.match(query,/evidence.id=stored.Id/);allowed=false;assert.equal((await fetch(fullBase+link.path)).status,404);allowed=true});
test('report evidence must belong to reporter and correct community',async()=>{const d=reportDetailsSchema.parse({evidence:[{id:'22222222-2222-4222-8222-222222222222',name:'untrusted.txt'}]});await validateReportDetails('u',c,d);assert.equal(d.evidence[0].name,'proof.txt');owned=false;await assert.rejects(validateReportDetails('u',c,d),/unavailable/);owned=true;assert.equal(reportDetailsSchema.safeParse({evidence:Array(5).fill(d.evidence[0])}).success,false);assert.equal(reportDetailsSchema.safeParse({additionalDetails:'x'.repeat(501)}).success,false)});

test('full API rejects expired links and keeps normal API endpoints authenticated',async()=>{assert.equal((await fetch(fullBase+'/media/issue-download/expired')).status,404);assert.equal((await fetch(fullBase+'/users/me')).status,401);assert.equal((await fetch(fullBase+'/communities/'+c+'/issues')).status,401)});
