import test,{after} from 'node:test';import assert from 'node:assert/strict';import express from 'express';import sql from 'mssql';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64)});
const {levyRouter,levySchema}=await import('../dist/routes/levies.js');const c='11111111-1111-4111-a111-111111111111',l='22222222-2222-4222-a222-222222222222',u='33333333-3333-4333-a333-333333333333',f='44444444-4444-4444-a444-444444444444';let manager=false,ledger,pending=false,validFile=true,writes=[];
const old={connect:sql.ConnectionPool.prototype.connect,query:sql.Request.prototype.query,begin:sql.Transaction.prototype.begin,commit:sql.Transaction.prototype.commit,rollback:sql.Transaction.prototype.rollback};sql.ConnectionPool.prototype.connect=async function(){return this};for(const k of ['begin','commit','rollback'])sql.Transaction.prototype[k]=async()=>{};sql.Request.prototype.query=async function(text){if(text.includes('SELECT TOP 1 Id FROM CommunityMembers'))return{recordset:[{Id:'member'}]};if(text.includes('1 Allowed FROM'))return{recordset:manager?[{Allowed:1}]:[]};if(text.startsWith('SELECT l.*')){assert.match(text,/l.UserId=@u/);assert.match(text,/UPDLOCK,HOLDLOCK/);return{recordset:ledger?[ledger]:[]}}if(text.startsWith('SELECT Id FROM LevyPaymentSubmissions') || text.startsWith('SELECT TOP 1 Id FROM LevyPaymentSubmissions'))return{recordset:pending?[{Id:'existing'}]:[]};if(text.startsWith('SELECT Id FROM StoredObjects')){assert.match(text,/UploadedBy=@u AND CommunityId=@c AND IsPrivate=1/);return{recordset:validFile?[{Id:f}]:[]}}writes.push({text,parameters:this.parameters});return{recordset:[{Id:'saved'}]}};
const app=express();app.use(express.json(),(req,_res,next)=>{req.user={id:u};next()},levyRouter);app.use((e,_req,res,_next)=>res.status(e.status??(e.name==='ZodError'?400:500)).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));after(()=>{sql.ConnectionPool.prototype.connect=old.connect;sql.Request.prototype.query=old.query;for(const k of ['begin','commit','rollback'])sql.Transaction.prototype[k]=old[k];server.closeAllConnections();server.close()});
const send=(path,body)=>fetch('http://127.0.0.1:'+server.address().port+'/communities/'+c+'/finance/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const payload={amount:100,paymentMethod:'BANK_TRANSFER',reference:'BANK-001',evidenceId:f};
test('ordinary members cannot create levies',async()=>{writes=[];const r=await send('dues-plans',{});assert.equal(r.status,403);assert.equal(writes.length,0)});
test('payment evidence rejects other members, overpayment, partial restrictions, duplicate pending and unrelated files',async()=>{writes=[];ledger=null;assert.equal((await send('ledger/'+l+'/payment-submissions',payload)).status,404);ledger={Id:l,AmountDue:100,AmountPaid:0,AllowPartial:false,IsActive:true};assert.equal((await send('ledger/'+l+'/payment-submissions',{...payload,amount:101})).status,400);assert.equal((await send('ledger/'+l+'/payment-submissions',{...payload,amount:50})).status,400);pending=true;assert.equal((await send('ledger/'+l+'/payment-submissions',payload)).status,409);pending=false;validFile=false;assert.equal((await send('ledger/'+l+'/payment-submissions',payload)).status,400);assert.equal(writes.length,0);validFile=true;assert.equal((await send('ledger/'+l+'/payment-submissions',payload)).status,201);assert.equal(writes.length,1);assert.ok(writes[0].text.startsWith('INSERT LevyPaymentSubmissions'));assert.ok(!writes.some(x=>x.text.includes('UPDATE MemberDuesLedger')))});
test('levy creation validates real dates and precise positive amounts',()=>{const d={name:'Levy',description:'Services',amount:100,frequency:'MONTHLY',dueDate:'2028-02-29'};assert.equal(levySchema.safeParse(d).success,true);assert.equal(levySchema.safeParse({...d,dueDate:'2027-02-29'}).success,false);assert.equal(levySchema.safeParse({...d,amount:0}).success,false);assert.equal(levySchema.safeParse({...d,amount:1.001}).success,false)});

test('payment reviews are leader-only and scoped to the community',async()=>{writes=[];const url='http://127.0.0.1:'+server.address().port+'/communities/'+c+'/finance/payment-submissions';assert.equal((await fetch(url)).status,403);assert.equal(writes.length,0);manager=true;try{const r=await fetch(url);assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.match(writes[0].text,/WHERE s.CommunityId=@c/);assert.match(writes[0].text,/u.ProfileImage/);assert.equal(writes[0].parameters.c.value,c)}finally{manager=false}});

test('unpaid member balances require leadership and exclude pending transfers',async()=>{writes=[];const url='http://127.0.0.1:'+server.address().port+'/communities/'+c+'/finance/unpaid-members';assert.equal((await fetch(url)).status,403);assert.equal(writes.length,0);manager=true;try{const r=await fetch(url);assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.match(writes[0].text,/WHERE l.CommunityId=@c AND l.AmountPaid<l.AmountDue/);assert.match(writes[0].text,/NOT EXISTS/);assert.match(writes[0].text,/pending.Status='PENDING'/);assert.equal(writes[0].parameters.c.value,c)}finally{manager=false}});
