import test,{after} from 'node:test';import assert from 'node:assert/strict';import express from 'express';import sql from 'mssql';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64)});
const {contentRouter}=await import('../dist/routes/content.js');const {meetingSettingsSchema}=await import('../dist/services/meetingSettings.js');const {emergencyQueue,notificationQueue,backgroundQueue}=await import('../dist/queues/index.js');for(const q of [emergencyQueue,notificationQueue,backgroundQueue]){q.on('error',()=>{});q.opts.connection.disconnect();}let visible=true,eligible=true,retry=false,queries=[];
const originals={connect:sql.ConnectionPool.prototype.connect,query:sql.Request.prototype.query,begin:sql.Transaction.prototype.begin,commit:sql.Transaction.prototype.commit,rollback:sql.Transaction.prototype.rollback};sql.ConnectionPool.prototype.connect=async()=>({connected:true,config:{},request(){return new sql.Request()}});sql.Transaction.prototype.begin=async()=>{};sql.Transaction.prototype.commit=async()=>{};sql.Transaction.prototype.rollback=async()=>{};
const settings={allowQuestions:false,allowNotes:true,enableVoting:false,attendance:'ORGANISERS',visibility:'ORGANISERS',sendInvitations:false,smsReminders:false,reminderMinutes:1440};
sql.Request.prototype.query=async function(text){const params=Object.fromEntries(Object.entries(this.parameters).map(([k,v])=>[k,v.value]));queries.push({text,params});if(text.includes('SELECT TOP 1 Id FROM CommunityMembers')||text.includes('SELECT TOP 1 1'))return{recordset:[{Id:'member',ok:1}]};if(text.includes('SELECT DISTINCT p.Code')||text.includes('p.Code=@p'))return{recordset:[{Code:'MEETING_CREATE',ok:1}]};if(text.includes('dbo.CanAttendMeeting'))return{recordset:[{Allowed:eligible}]};if(text.includes('CreateRequestId=@request'))return{recordset:retry?[{Id:'existing'}]:[]};if(text.includes('SELECT * FROM Meetings'))return{recordset:visible?[{Id:'m',CommunityId:'c',SettingsJson:JSON.stringify(settings),EndDateTime:new Date(Date.now()+86400000)}]:[]};if(text.includes('INSERT INTO Meetings'))return{recordset:[{Id:'m',CreatedAt:new Date()}]};return{recordset:[]}};
const app=express();app.use(express.json(),(req,res,next)=>{req.user={id:'viewer'};next()});for(const path of ['/communities/:communityId/meetings','/meetings/:meetingId/activity','/meetings/:meetingId/vote']){const route=contentRouter.stack.find(x=>x.route?.path===path&&x.route.methods.post);app.post(path,route.route.stack.at(-1).handle)}app.use((e,req,res,next)=>res.status(e.status||400).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const send=(path,body)=>fetch('http://127.0.0.1:'+server.address().port+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});after(async()=>{Object.assign(sql.ConnectionPool.prototype,{connect:originals.connect});sql.Request.prototype.query=originals.query;sql.Transaction.prototype.begin=originals.begin;sql.Transaction.prototype.commit=originals.commit;sql.Transaction.prototype.rollback=originals.rollback;server.closeAllConnections();server.close();});
test('settings reject unsupported audiences and reminder schedules',()=>{assert.equal(meetingSettingsSchema.safeParse({visibility:'PUBLIC'}).success,false);assert.equal(meetingSettingsSchema.safeParse({reminderMinutes:-1}).success,false);assert.equal(meetingSettingsSchema.parse({}).smsReminders,false)});
test('restricted meetings reject invisible users before accepting questions',async()=>{visible=false;assert.equal((await send('/meetings/m/activity',{kind:'QUESTION',body:'Hello'})).status,404);visible=true});
test('attendee restrictions are checked for contributions',async()=>{eligible=false;assert.equal((await send('/meetings/m/activity',{kind:'NOTE',body:'Hello'})).status,403);eligible=true});
test('disabled questions and votes reject submissions, enabled notes persist',async()=>{assert.equal((await send('/meetings/m/activity',{kind:'QUESTION',body:'Hello'})).status,403);assert.equal((await send('/meetings/m/vote',{agendaId:'12345678-1234-4234-8234-123456789abc',choice:'YES'})).status,403);assert.equal((await send('/meetings/m/activity',{kind:'NOTE',body:'Agreed action'})).status,201);assert.ok(queries.some(q=>q.text.includes('INSERT INTO MeetingContributions')&&q.params.body==='Agreed action'))});
test('publishing saves the agenda duration and notification preferences',async()=>{queries=[];const response=await send('/communities/c/meetings',{title:'General meeting',description:'A real discussion',startDateTime:'2030-10-10T09:00:00Z',endDateTime:'2030-10-10T11:00:00Z',settings:{...settings,timeZone:'Europe/London'},agenda:[{title:'Updates',position:1,durationMinutes:25}]});assert.equal(response.status,201,await response.text());const insert=queries.find(q=>q.text.includes('INSERT INTO Meetings'));assert.ok(insert);assert.equal(JSON.parse(insert.params.settings).sendInvitations,false);assert.equal(JSON.parse(insert.params.settings).visibility,'ORGANISERS');assert.ok(queries.some(q=>q.text.includes('INSERT INTO MeetingAgendaItems')&&q.params.duration===25));assert.ok(!queries.some(q=>q.text.includes('NotificationOutbox')))});
test('server rejects an agenda longer than its meeting',async()=>{const r=await send('/communities/c/meetings',{title:'General meeting',startDateTime:'2030-10-10T09:00:00Z',endDateTime:'2030-10-10T10:00:00Z',settings:{sendInvitations:false},agenda:[{title:'Updates',position:1,durationMinutes:90}]});assert.equal(r.status,400)});

test('retrying the same publish request returns the original meeting without duplicates',async()=>{retry=true;queries=[];const r=await send('/communities/c/meetings',{requestId:'12345678-1234-4234-8234-123456789abc',title:'General meeting',startDateTime:'2030-10-10T09:00:00Z',endDateTime:'2030-10-10T11:00:00Z',settings:{sendInvitations:false}});assert.equal(r.status,200);assert.equal((await r.json()).Id,'existing');assert.ok(!queries.some(q=>q.text.includes('INSERT INTO Meetings')||q.text.includes('NotificationOutbox')));retry=false});
