import test from 'node:test';
import assert from 'node:assert/strict';
import sql from 'mssql';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64)});
const {ensureMeetingSchema}=await import('../dist/migrateMeetings.js');
test('an administrator-installed schema is verified without DDL or loading the migration',async()=>{let queries=0;const pool={request:()=>({query:async text=>{queries++;if(text.includes('END Ready'))return{recordset:[{Ready:1}]};assert.match(text,/CanViewMeeting\(NULL,NULL\)/);return{recordset:[]}}})};assert.equal(await ensureMeetingSchema(pool,()=>{throw Error('Must not load DDL')}),'verified');assert.equal(queries,2)});
test('runtime permission errors fail verification without trying to alter existing functions',async()=>{const denied=Error('Function permission denied');const pool={request:()=>({query:async text=>{if(text.includes('END Ready'))return{recordset:[{Ready:1}]};throw denied}})};await assert.rejects(ensureMeetingSchema(pool,()=>{throw Error('Must not load DDL')}),e=>e===denied)});
test('an incomplete schema runs migration batches and rolls back on permission failure',async t=>{let rolledBack=false;const denied=Error('ALTER permission denied');t.mock.method(sql.Transaction.prototype,'begin',async()=>{});t.mock.method(sql.Transaction.prototype,'rollback',async()=>{rolledBack=true});t.mock.method(sql.Request.prototype,'batch',async()=>{throw denied});const pool={config:{},request:()=>({query:async text=>({recordset:[text.includes('END Ready')?{Ready:0}:{CanMigrate:1}]})})};await assert.rejects(ensureMeetingSchema(pool,async()=> 'ALTER TABLE dbo.Meetings ADD Example int;\nGO\n'),e=>e===denied);assert.equal(rolledBack,true)});

test('hidden metadata on a restricted account never triggers ALTER',async()=>{const pool={request:()=>({query:async text=>({recordset:[text.includes('END Ready')?{Ready:0}:{DatabaseName:'CDAConnect',DatabaseUser:'app',CanMigrate:0,ViewFunction:null}]})})};await assert.rejects(ensureMeetingSchema(pool,()=>{throw Error('Must not load DDL')}),/No ALTER was attempted.*CDAConnect/)});
