import test,{after} from 'node:test';import assert from 'node:assert/strict';import express from 'express';import sql from 'mssql';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64)});
const {pollRouter}=await import('../dist/routes/polls.js');const {pollSettingsSchema}=await import('../dist/services/pollSettings.js');
const pid='11111111-1111-4111-a111-111111111111',oid='22222222-2222-4222-a222-222222222222',user='33333333-3333-4333-a333-333333333333';let row,existing=[],writes=[];
const originals={connect:sql.ConnectionPool.prototype.connect,query:sql.Request.prototype.query,begin:sql.Transaction.prototype.begin,commit:sql.Transaction.prototype.commit,rollback:sql.Transaction.prototype.rollback};sql.ConnectionPool.prototype.connect=async function(){return this};sql.Transaction.prototype.begin=async()=>{};sql.Transaction.prototype.commit=async()=>{};sql.Transaction.prototype.rollback=async()=>{};sql.Request.prototype.query=async function(q){if(q.startsWith('SELECT p.*')){assert.ok(q.includes("cm.Status='ACTIVE'"));assert.ok(q.includes('SettingsJson'));return{recordset:row?[row]:[]}}if(q.startsWith('SELECT Id,OptionText'))return{recordset:[{Id:oid,OptionText:'Other'}]};if(q.startsWith('SELECT Id FROM PollVotes'))return{recordset:existing};writes.push({q,other:this.parameters.other?.value});return{recordset:[]}};
const app=express();app.use(express.json(),(req,_res,next)=>{req.user={id:user};next()},pollRouter);app.use((e,_req,res,_next)=>res.status(e.status??(e.name==='ZodError'?400:500)).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));after(()=>{sql.ConnectionPool.prototype.connect=originals.connect;sql.Request.prototype.query=originals.query;for(const k of ['begin','commit','rollback'])sql.Transaction.prototype[k]=originals[k];server.closeAllConnections();server.close()});
const reset=()=>{row={Id:pid,StartAt:'2020-01-01',EndAt:'2099-01-01',AllowMultiple:false,AllowChangeVote:false,SettingsJson:JSON.stringify({other:true})};existing=[];writes=[]};const vote=data=>fetch('http://127.0.0.1:'+server.address().port+'/polls/'+pid+'/vote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
test('poll voting validates audience, dates, duplicates and write-in before mutation',async()=>{reset();row=null;assert.equal((await vote({optionIds:[oid]})).status,403);reset();row.EndAt='2020-01-02';assert.equal((await vote({optionIds:[oid]})).status,400);reset();row.StartAt='2098-01-01';assert.equal((await vote({optionIds:[oid]})).status,400);reset();assert.equal((await vote({optionIds:[oid,oid]})).status,400);assert.equal((await vote({optionIds:[pid]})).status,400);assert.equal((await vote({optionIds:[oid]})).status,400);assert.equal(writes.length,0);assert.equal((await vote({optionIds:[oid],otherText:'Repair the water supply'})).status,200);assert.equal(writes.at(-1).other,'Repair the water supply');});
test('repeat voting requires explicit allow-change setting',async()=>{reset();existing=[{Id:'vote'}];assert.equal((await vote({optionIds:[oid],otherText:'A'})).status,409);assert.equal(writes.length,0);row.AllowChangeVote=true;assert.equal((await vote({optionIds:[oid],otherText:'B'})).status,200);assert.ok(writes[0].q.startsWith('DELETE'));});
test('poll settings reject unknown audiences and invalid reminder delays',()=>{assert.equal(pollSettingsSchema.safeParse({audience:'PUBLIC'}).success,false);assert.equal(pollSettingsSchema.safeParse({reminderMinutes:-1}).success,false);assert.equal(pollSettingsSchema.parse({audience:'ROLE',role:'Excos',notify:false}).notify,false)});

test('poll comments reject empty content and nonexistent polls before writing',async()=>{writes=[];const url='http://127.0.0.1:'+server.address().port+'/polls/'+pid+'/comments';let r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:'   '})});assert.equal(r.status,400);assert.equal(writes.length,0);r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:'Feedback'})});assert.equal(r.status,404);assert.ok(!writes.some(x=>x.q.startsWith('INSERT')))});
