// Dedicated Redis integration suite. No FLUSHDB; only a unique test queue is removed.
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {Queue,Worker} from 'bullmq';import {Redis} from 'ioredis';import {ensureRunnable} from '../dist/queues/recovery.js';
if(!process.env.REDIS_TEST_URL)throw Error('Set REDIS_TEST_URL to a test Redis instance');
async function until(check){const end=Date.now()+10000;while(Date.now()<end){if(await check())return;await new Promise(r=>setTimeout(r,25))}throw Error('Timed out waiting for Redis worker')}
test('retained failed and completed jobs restart on real Redis for every notification job class',{timeout:60000},async()=>{const connection=new Redis(process.env.REDIS_TEST_URL,{maxRetriesPerRequest:1,connectTimeout:5000,commandTimeout:5000,retryStrategy:()=>null}),workerConnection=new Redis(process.env.REDIS_TEST_URL,{maxRetriesPerRequest:null,connectTimeout:5000,retryStrategy:()=>null}),name='integrity-test-'+randomUUID(),queue=new Queue(name,{connection});let fail=true,calls=0;const worker=new Worker(name,async()=>{calls++;if(fail)throw Error('Injected provider failure');return 'accepted'},{connection:workerConnection});worker.on('error',()=>{});connection.on('error',()=>{});workerConnection.on('error',()=>{});
 try{await connection.ping();for(const kind of ['notification-dispatch','notification-delivery','account-email','account-sms','broadcast']){fail=true;const id=kind;await queue.add(kind,{}, {jobId:id,attempts:1,removeOnFail:1000,removeOnComplete:1000});await until(async()=>(await queue.getJob(id))?.getState().then(s=>s==='failed'));fail=false;const previous=calls;await ensureRunnable(queue,kind,{}, {jobId:id});await until(async()=>(await queue.getJob(id))?.getState().then(s=>s==='completed'));assert.equal(calls,previous+1);await ensureRunnable(queue,kind,{}, {jobId:id});await until(()=>calls===previous+2);await until(async()=>(await queue.getJob(id))?.getState().then(s=>s==='completed'));}
 const delayed=await ensureRunnable(queue,'delayed',{}, {jobId:'integration-delayed-job',delay:60000});assert.equal(delayed.state,'delayed');assert.equal((await ensureRunnable(queue,'delayed',{}, {jobId:'integration-delayed-job'})).state,'delayed');
 }finally{try{await Promise.race([(async()=>{await worker.close(true);await queue.obliterate({force:true});await queue.close()})(),new Promise((_,reject)=>{const t=setTimeout(()=>reject(Error('Redis cleanup timed out')),5000);t.unref()})])}finally{connection.disconnect();workerConnection.disconnect();await worker.disconnect().catch(()=>{})}}
});
