import test,{after} from 'node:test';import assert from 'node:assert/strict';import express from 'express';import sql from 'mssql';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
Object.assign(process.env,{NODE_ENV:'test',DB_SERVER:'localhost',DB_NAME:'test',DB_USER:'test',DB_PASSWORD:'test',JWT_ACCESS_SECRET:'a'.repeat(64),JWT_REFRESH_SECRET:'b'.repeat(64)});
const {Redis}=await import('ioredis');const originalRedisConnect=Redis.prototype.connect;Redis.prototype.connect=async()=>{};
const {advancedRouter}=await import('../dist/routes/advanced.js'),{safetyRouter}=await import('../dist/routes/safety.js'),{contentRouter}=await import('../dist/routes/content.js');
let active=true,ack=true,manager=true,version=1,archived=false,failAudit=false,updates=0,audits=0,responses=0,tail=Promise.resolve();const levels=[];
const old={connect:sql.ConnectionPool.prototype.connect,query:sql.Request.prototype.query,begin:sql.Transaction.prototype.begin,commit:sql.Transaction.prototype.commit,rollback:sql.Transaction.prototype.rollback};
sql.ConnectionPool.prototype.connect=async function(){return this};sql.Transaction.prototype.begin=async function(level){levels.push(level);const before=tail;tail=new Promise(r=>this.release=r);await before;this.snapshot={version,archived,updates,audits,responses}};sql.Transaction.prototype.commit=async function(){this.release()};sql.Transaction.prototype.rollback=async function(){({version,archived,updates,audits,responses}=this.snapshot);this.release()};
sql.Request.prototype.query=async function(text){
 if(text.includes('CommunityShardMap'))return{recordset:[]};if(text.includes('SELECT TOP 1 Id FROM CommunityMembers'))return{recordset:[{Id:'member'}]};if(text.includes('SELECT TOP 1 1 ok'))return{recordset:manager?[{ok:1}]:[]};
 if(text.includes('FROM EmergencyAlerts WITH')){assert.match(text,/UPDLOCK,HOLDLOCK/);return{recordset:[{CommunityId:'community',Active:active,RequiresAcknowledgement:ack}]}}
 if(text.includes('INSERT INTO EmergencyIncidentUpdates')){updates++;return{recordset:[{Id:'update'}]}}if(text.includes('INSERT AuditLogs')){if(failAudit)throw Error('Audit unavailable');audits++}if(text.includes('MERGE EmergencyResponses'))responses++;
 if(text.includes('FROM KnowledgeDocuments'))return{recordset:archived?[]:[{Id:'document',CommunityId:'community',CurrentVersion:version,Title:'Policy'}]};
 if(text.includes('FROM StoredObjects WITH'))return{recordset:[{Id:'file'}]};if(text.includes('UPDATE KnowledgeDocuments SET CurrentVersion'))version=this.parameters.v.value;
 if(text.includes('UPDATE KnowledgeDocuments SET Title'))archived=!!this.parameters.archived.value;
 return{recordset:[]};
};
const app=express();app.use(express.json(),(req,res,next)=>{req.user={id:'reviewer'};next()});for(const router of [advancedRouter,safetyRouter,contentRouter])for(const layer of router.stack){if(layer.route&&['/documents/:documentId','/documents/:documentId/versions','/alerts/:alertId/updates','/alerts/:alertId/respond'].includes(layer.route.path))for(const method of Object.keys(layer.route.methods))app[method](layer.route.path,layer.route.stack.at(-1).handle)}app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));after(()=>{Redis.prototype.connect=originalRedisConnect;sql.ConnectionPool.prototype.connect=old.connect;sql.Request.prototype.query=old.query;for(const k of ['begin','commit','rollback'])sql.Transaction.prototype[k]=old[k];server.closeAllConnections();server.close()});const call=(path,body,method=body?'POST':'GET')=>fetch(`http://127.0.0.1:${server.address().port}${path}`,{method,headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
test('resolved alerts reject incident updates and safety responses',async()=>{active=false;assert.equal((await call('/alerts/alert/updates',{message:'Update'})).status,409);assert.equal((await call('/alerts/alert/respond',{response:'SAFE'})).status,409);assert.equal(updates,0);assert.equal(responses,0);active=true});
test('acknowledgement-disabled alert rejects responses but remains updateable',async()=>{ack=false;assert.equal((await call('/alerts/alert/respond',{response:'SAFE'})).status,409);assert.equal((await call('/alerts/alert/updates',{message:'Informational update'})).status,201);assert.equal(updates,1);assert.equal(audits,1);ack=true;assert.equal((await call('/alerts/alert/respond',{response:'SAFE'})).status,200)});
test('incident update rolls back when its audit cannot be saved',async()=>{failAudit=true;assert.equal((await call('/alerts/alert/updates',{message:'Must roll back'})).status,500);assert.equal(updates,1);assert.equal(audits,1);failAudit=false});
test('exactly one GET document detail route exists and sends no-store',async()=>{assert.equal(advancedRouter.stack.filter(x=>x.route?.path==='/documents/:documentId'&&x.route.methods.get).length,1);const r=await call('/documents/document');assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store')});
test('simultaneous document replacements allocate distinct versions inside serialized transactions',async()=>{const payload={storedObjectId:'44444444-4444-4444-8444-444444444444',changeNotes:'Updated policy'};const results=await Promise.all([call('/documents/document/versions',payload),call('/documents/document/versions',{...payload,storedObjectId:'55555555-5555-4555-8555-555555555555'})]);assert.deepEqual(results.map(r=>r.status),[201,201]);const numbers=await Promise.all(results.map(r=>r.json().then(d=>d.version)));assert.deepEqual(numbers.sort(),[2,3]);assert.ok(levels.slice(-2).every(l=>l===sql.ISOLATION_LEVEL.SERIALIZABLE))});
test('metadata and archive require document management, and archive removes reader access',async()=>{manager=false;assert.equal((await call('/documents/document',{title:'Updated'},'PATCH')).status,403);manager=true;assert.equal((await call('/documents/document',{archived:true},'PATCH')).status,200);assert.equal((await call('/documents/document')).status,404)});
test('workflow migration checksums match canonical LF file bytes',()=>{const root=new URL('../sql/',import.meta.url),manifest=JSON.parse(readFileSync(new URL('migrations.json',root),'utf8'));for(const file of ['review-workflows.sql','finance-permissions.sql','workflow-integrity.sql']){const bytes=readFileSync(new URL(file,root));assert.equal(bytes.includes(13),false);assert.equal(createHash('sha256').update(bytes).digest('hex'),manifest.find(m=>m.file===file).sha256)}});
