import {useMemo,useState} from 'react';
import {Alert,Linking,Platform,Pressable,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Button,Card,Input,Muted,Screen,useAppTheme} from '@/components/UI';

const menu=[['person-outline','Account Settings','/account-settings'],['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;
const categories=[['Getting Started','Learn the basics and set up your account','book-outline'],['Account & Profile','Manage your profile, privacy and security','person-outline'],['Communities','Create, join and manage communities','people-outline'],['Communication','Chat, posts and notifications','chatbubble-ellipses-outline'],['Payments & Finance','Dues, donations and transactions','wallet-outline'],['Safety & Privacy','Learn how we protect your data','shield-checkmark-outline']] as const;
const articles=[['How to create a new community','Getting Started','Open Communities and select Create. Complete the basic details, location, settings and review steps.'],['How to reset your password','Account & Profile','Open Settings, Account Settings, then Change Password. Use a unique password and enable two-factor authentication.'],['Understanding community roles','Communities','Owners manage the workspace, admins manage members, moderators oversee content, and members participate.'],['How notifications work','Communication','Notification preferences control in-app, email, SMS and push delivery for each activity category.'],['Manage community payments','Payments & Finance','Open the community Finance section to review dues, payments, receipts and financial reports.'],['Report unsafe content','Safety & Privacy','Use the three-dot menu on a post, member or listing and select Report. Use Emergency for immediate danger.']] as const;

export default function Help(){const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;const[q,setQ]=useState('');const[selected,setSelected]=useState<string|null>(null);const filtered=useMemo(()=>articles.filter(a=>(a.join(' ').toLowerCase()).includes(q.trim().toLowerCase())),[q]);
 const openArticle=(title:string)=>setSelected(title);const contact=()=>Linking.openURL('mailto:support@cdaconnect.local?subject=CDA%20Connect%20Support');
 if(selected){const article=articles.find(a=>a[0]===selected);return <Screen scroll contentStyle={s.detail}><Pressable onPress={()=>setSelected(null)} style={s.back}><Ionicons name="chevron-back" size={27} color={palette.text}/><Text style={[s.detailTitle,{color:palette.text}]}>Help & Support</Text></Pressable><Card><View style={[s.largeIcon,{backgroundColor:palette.successSoft}]}><Ionicons name="book-outline" size={34} color={palette.success}/></View><Text style={[s.articleTitle,{color:palette.text}]}>{article?.[0]}</Text><Muted>{article?.[1]}</Muted><Text style={[s.articleBody,{color:palette.text}]}>{article?.[2]}</Text><Text style={[s.articleBody,{color:palette.text}]}>If you still need help, contact the CDA Connect support team and include any relevant community name, page and error message.</Text><Button title="Contact Support" variant="success" onPress={contact}/></Card></Screen>}
 return <Screen scroll contentStyle={s.page}><View style={s.heading}><Text style={[s.title,{color:palette.text}]}>Help & Support</Text><Muted>We’re here to help! Find answers, connect with support, or share your feedback.</Muted></View><View style={[s.layout,!desktop&&s.stack]}>{desktop?<SettingsMenu/>:null}<View style={s.main}>
  <View style={[s.top,!desktop&&s.stack]}><Card style={s.hero}><View style={[s.agent,{backgroundColor:palette.successSoft}]}><Ionicons name="headset-outline" size={72} color={palette.success}/></View><Text style={[s.heroTitle,{color:palette.text}]}>How can we help you today?</Text><Muted style={{textAlign:'center'}}>Search our Help Center or choose a topic below.</Muted><Input placeholder="Search for help articles..." value={q} onChangeText={setQ}/>{q?<View style={s.results}>{filtered.length?filtered.map(a=><Action key={a[0]} icon="document-text-outline" label={a[0]} body={a[1]} onPress={()=>openArticle(a[0])}/>):<Muted>No matching help articles.</Muted>}</View>:null}</Card>
   {desktop?<><Card style={s.flex}><SectionTitle title="Popular Topics"/>{articles.slice(0,5).map(a=><Action key={a[0]} icon={(categories.find(c=>c[0]===a[1])?.[2]||'book-outline') as any} label={a[0]} body={a[1]} onPress={()=>openArticle(a[0])}/>)}</Card><Card style={s.support}><SectionTitle title="Need more help?"/><Muted>Our support team is ready to assist you.</Muted><Action icon="headset-outline" label="Contact Support" body="Get help from our team" onPress={contact}/><Action icon="chatbubble-outline" label="Live Chat" body="Chat with us in real time" value="Online" onPress={()=>router.push('/(tabs)/communities')}/><Action icon="warning-outline" label="Report an Issue" body="Tell us what is not working" onPress={()=>router.push('/(tabs)/communities')}/><Action icon="people-outline" label="Community Forum" body="Ask questions and get help" onPress={()=>router.push('/(tabs)/communities')}/><View style={[s.response,{backgroundColor:palette.successSoft}]}><Ionicons name="time-outline" size={22} color={palette.success}/><Muted>Average response time: under 2 hours</Muted></View></Card></>:null}</View>
  <Text style={[s.blockTitle,{color:palette.text}]}>Help Categories</Text><View style={s.categoryGrid}>{categories.map(([name,body,icon])=><Pressable key={name} onPress={()=>{const first=articles.find(a=>a[1]===name);first&&openArticle(first[0])}} style={[s.category,{backgroundColor:palette.surface,borderColor:palette.border}]}><View style={[s.categoryIcon,{backgroundColor:name==='Safety & Privacy'?palette.dangerSoft:palette.successSoft}]}><Ionicons name={icon} size={31} color={name==='Safety & Privacy'?palette.danger:palette.success}/></View><Text style={[s.categoryTitle,{color:palette.text}]}>{name}</Text><Muted style={{textAlign:'center'}}>{body}</Muted><Text style={{color:palette.success,fontWeight:'900'}}>Explore →</Text></Pressable>)}</View>
  {!desktop?<><Card><SectionTitle title="Popular Topics"/>{articles.slice(0,5).map(a=><Action key={a[0]} icon="document-text-outline" label={a[0]} body={a[1]} onPress={()=>openArticle(a[0])}/>)}</Card><Card><SectionTitle title="Need more help?"/><View style={s.quick}><Quick icon="headset-outline" label="Contact" press={contact}/><Quick icon="chatbubble-outline" label="Live Chat" press={()=>router.push('/(tabs)/communities')}/><Quick icon="warning-outline" label="Report Issue" press={()=>router.push('/(tabs)/communities')}/><Quick icon="people-outline" label="Community" press={()=>router.push('/(tabs)/communities')}/></View></Card></>:null}
  <View style={[s.bottom,!desktop&&s.stack]}><Card style={s.flex}><SectionTitle title="Support Resources"/><Action icon="help-buoy-outline" label="Help Center" body="Browse detailed help articles" onPress={()=>openArticle(articles[0][0])}/><Action icon="play-circle-outline" label="Video Tutorials" body="Watch step-by-step guides" onPress={()=>Alert.alert('Video tutorials','Tutorial videos will open here as they are published.')}/><Action icon="download-outline" label="Guides & Downloads" body="User guides and useful resources" onPress={()=>Alert.alert('Guides','The current help guide is available inside each Help category.')}/><Action icon="checkmark-circle-outline" label="System Status" body="All CDA Connect services operational" value="All Good" onPress={()=>Alert.alert('System status','API, database and messaging services are operational.')}/></Card><Card style={s.flex}><SectionTitle title="Recent Help Articles"/>{articles.slice(0,4).map(a=><Action key={a[0]} icon="document-text-outline" label={a[0]} body={a[1]} onPress={()=>openArticle(a[0])}/>)}</Card><Card style={s.contact}><Ionicons name="mail-open-outline" size={48} color={palette.success}/><SectionTitle title="Still need help?"/><Muted style={{textAlign:'center'}}>Can’t find what you’re looking for? Contact our support team.</Muted><Button title="Contact Support" variant="success" onPress={contact}/></Card></View>
  <Card style={[s.banner,{backgroundColor:palette.successSoft}]}><Ionicons name="shield-checkmark-outline" size={34} color={palette.success}/><View style={{flex:1}}><Text style={[s.categoryTitle,{color:palette.success}]}>We’re here to help</Text><Muted>Our goal is to make your CDA Connect experience smooth and successful.</Muted></View></Card>
 </View></View></Screen>}

function SettingsMenu(){const{palette}=useAppTheme();return <Card style={s.menu}><Text style={[s.menuTitle,{color:palette.text}]}>Settings Menu</Text>{menu.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[s.menuRow,label==='Help & Support'&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={label==='Help & Support'?palette.success:palette.navy}/><Text style={{fontWeight:'800',color:label==='Help & Support'?palette.success:palette.text}}>{label}</Text></Pressable>)}</Card>}
function SectionTitle({title}:{title:string}){const{palette}=useAppTheme();return <Text style={[s.sectionTitle,{color:palette.text}]}>{title}</Text>}
function Action({icon,label,body,value,onPress}:{icon:keyof typeof Ionicons.glyphMap;label:string;body:string;value?:string;onPress:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={onPress} style={[s.action,{borderBottomColor:palette.border}]}><View style={[s.actionIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={palette.success}/></View><View style={{flex:1}}><Text style={[s.actionTitle,{color:palette.text}]}>{label}</Text><Muted>{body}</Muted></View>{value?<Text style={{color:palette.success,fontWeight:'900'}}>{value}</Text>:null}<Ionicons name="chevron-forward" size={18} color={palette.muted}/></Pressable>}
function Quick({icon,label,press}:{icon:keyof typeof Ionicons.glyphMap;label:string;press:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={press} style={s.quickItem}><View style={[s.quickIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={25} color={palette.success}/></View><Text style={[s.quickText,{color:palette.text}]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1380,alignSelf:'center'},heading:{marginBottom:22},title:{fontSize:30,fontWeight:'900',marginBottom:5},layout:{flexDirection:'row',alignItems:'flex-start',gap:16},stack:{flexDirection:'column'},menu:{width:245,padding:12},menuTitle:{fontWeight:'900',margin:8},menuRow:{minHeight:48,borderRadius:10,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:11},main:{flex:1,width:'100%',minWidth:0,gap:15},top:{flexDirection:'row',gap:14,alignItems:'stretch'},hero:{flex:1,alignItems:'center'},agent:{width:150,height:120,borderRadius:38,alignItems:'center',justifyContent:'center'},heroTitle:{fontSize:20,fontWeight:'900',marginTop:9,marginBottom:4},flex:{flex:1,minWidth:0},support:{flex:1,minWidth:0},sectionTitle:{fontSize:19,fontWeight:'900',marginBottom:10},results:{width:'100%'},action:{minHeight:65,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:10},actionIcon:{width:39,height:39,borderRadius:12,alignItems:'center',justifyContent:'center'},actionTitle:{fontWeight:'900',marginBottom:2},response:{padding:12,borderRadius:12,flexDirection:'row',gap:9,alignItems:'center',marginTop:12},blockTitle:{fontSize:20,fontWeight:'900',marginTop:4},categoryGrid:{flexDirection:'row',flexWrap:'wrap',gap:12},category:{flexGrow:1,flexBasis:145,minHeight:220,borderWidth:1,borderRadius:14,padding:14,alignItems:'center',justifyContent:'space-between'},categoryIcon:{width:64,height:64,borderRadius:32,alignItems:'center',justifyContent:'center'},categoryTitle:{fontSize:15,fontWeight:'900',textAlign:'center'},quick:{flexDirection:'row',justifyContent:'space-around',gap:8},quickItem:{flex:1,alignItems:'center',gap:6},quickIcon:{width:48,height:48,borderRadius:14,alignItems:'center',justifyContent:'center'},quickText:{fontSize:11,fontWeight:'800',textAlign:'center'},bottom:{flexDirection:'row',gap:14},contact:{width:270,alignItems:'center',justifyContent:'center'},banner:{flexDirection:'row',alignItems:'center',gap:14},detail:{width:'100%',maxWidth:720,alignSelf:'center'},back:{minHeight:54,flexDirection:'row',alignItems:'center',gap:8},detailTitle:{fontSize:23,fontWeight:'900'},largeIcon:{width:72,height:72,borderRadius:22,alignItems:'center',justifyContent:'center'},articleTitle:{fontSize:25,fontWeight:'900',marginTop:14,marginBottom:5},articleBody:{fontSize:16,lineHeight:25,marginTop:18}});
