import { useMemo, useState } from 'react';
import { FlatList, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { City, Country, type ICountry, type IState, State } from 'country-state-city';
import { getLGAsByState, getStateByName } from '@some19ice/nigeria-geo-core';
import { api } from '@/lib/api';
import { useAuth } from '@/store/auth';
import { Button, Input, Muted, Screen } from '@/components/UI';
import { colors } from '@/theme';

type Option={label:string;value:string};
const NO_POSTCODE_COUNTRIES=new Set(['AO','AG','AW','BS','BZ','BJ','BW','BF','BI','CM','CF','KM','CG','CD','CK','CI','DJ','DM','GQ','ER','FJ','GM','GH','GD','GY','HK','JM','KI','MO','MW','ML','MR','MU','MS','NR','NU','QA','RW','KN','LC','ST','SC','SL','SB','SO','SR','SY','TL','TG','TK','TO','TT','TV','UG','AE','VU','YE','ZW']);

function Selector({label,value,placeholder,options,disabled,onSelect}:{label:string;value:string;placeholder:string;options:Option[];disabled?:boolean;onSelect:(option:Option)=>void}){
 const[open,setOpen]=useState(false);const[search,setSearch]=useState('');
 const shown=useMemo(()=>{const q=search.trim().toLowerCase();return q?options.filter(x=>x.label.toLowerCase().includes(q)):options},[options,search]);
 return <><Text style={styles.label}>{label}</Text><Pressable accessibilityRole="button" disabled={disabled} onPress={()=>setOpen(true)} style={[styles.selector,disabled&&styles.disabled]}><Text style={[styles.selectorText,!value&&styles.placeholder]}>{value||placeholder}</Text><Ionicons name="chevron-down" size={20} color={colors.muted}/></Pressable><Modal visible={open} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setOpen(false)}><View style={styles.modal}><View style={styles.modalHeader}><Text style={styles.modalTitle}>Select {label}</Text><Pressable onPress={()=>setOpen(false)}><Ionicons name="close" size={28} color={colors.text}/></Pressable></View><Input placeholder={`Search ${label.toLowerCase()}`} value={search} onChangeText={setSearch}/><FlatList data={shown} keyExtractor={x=>x.value} keyboardShouldPersistTaps="handled" renderItem={({item})=><Pressable style={styles.option} onPress={()=>{onSelect(item);setSearch('');setOpen(false)}}><Text style={styles.optionText}>{item.label}</Text>{item.label===value?<Ionicons name="checkmark" size={22} color={colors.green}/>:null}</Pressable>}/></View></Modal></>;
}

export default function Register(){
 const countries=useMemo(()=>Country.getAllCountries(),[]);const nigeria=useMemo(()=>countries.find(x=>x.isoCode==='NG')!,[countries]);
 const[f,setF]=useState('');const[l,setL]=useState('');const[email,setEmail]=useState('');const[selectedCountry,setSelectedCountry]=useState<ICountry>(nigeria);const[phone,setPhone]=useState(`+${nigeria.phonecode} `);const[selectedState,setSelectedState]=useState<IState|null>(null);const[localArea,setLocalArea]=useState('');const[postcode,setPostcode]=useState('');const[address,setAddress]=useState('');const[dateOfBirth,setDateOfBirth]=useState('');const[p,setP]=useState('');const[confirm,setConfirm]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const setSession=useAuth(s=>s.setSession);
 const countryOptions=useMemo(()=>countries.map(x=>({label:`${x.flag} ${x.name} (+${x.phonecode})`,value:x.isoCode})),[countries]);
 const states=useMemo(()=>State.getStatesOfCountry(selectedCountry.isoCode),[selectedCountry]);const stateOptions=useMemo(()=>states.map(x=>({label:x.name,value:x.isoCode})),[states]);
 const localOptions=useMemo(()=>{if(!selectedState)return [];if(selectedCountry.isoCode==='NG'){const ngState=getStateByName(selectedState.name);return ngState?getLGAsByState(ngState.id).map(x=>({label:x.name,value:x.id})):[]}return City.getCitiesOfState(selectedCountry.isoCode,selectedState.isoCode).map(x=>({label:x.name,value:x.name}))},[selectedCountry,selectedState]);
 const usesPostcode=selectedCountry.isoCode!=='NG'&&!NO_POSTCODE_COUNTRIES.has(selectedCountry.isoCode);
 function chooseCountry(option:Option){const next=countries.find(x=>x.isoCode===option.value);if(!next)return;setSelectedCountry(next);setSelectedState(null);setLocalArea('');setPostcode('');setPhone(`+${next.phonecode} `)}
 async function submit(){if(loading)return;setError('');const firstName=f.trim(),lastName=l.trim(),cleanEmail=email.trim().toLowerCase(),cleanPhone=phone.trim();if(firstName.length<2||lastName.length<2){setError('First name and last name must contain at least 2 characters.');return}if(!/^\S+@\S+\.\S+$/.test(cleanEmail)){setError('Enter a valid email address.');return}if(!selectedState){setError('Select your state or region.');return}if(usesPostcode&&!postcode.trim()){setError('Enter your postcode.');return}if(!usesPostcode&&!localArea){setError('Select your local area.');return}if(address.trim().length<5){setError('Enter your residential address.');return}if(!/^\d{4}-\d{2}-\d{2}$/.test(dateOfBirth)||Number.isNaN(Date.parse(`${dateOfBirth}T00:00:00Z`))){setError('Enter your date of birth as YYYY-MM-DD.');return}if(p.length<8){setError('Password must contain at least 8 characters.');return}if(p!==confirm){setError('Passwords do not match.');return}try{setLoading(true);const r=await api.post('/auth/register',{firstName,lastName,email:cleanEmail,phone:cleanPhone||undefined,country:selectedCountry.name,state:selectedState.name,lga:localArea||undefined,postcode:postcode.trim()||undefined,address:address.trim(),dateOfBirth,password:p});await setSession(r.data.user,r.data.accessToken,r.data.refreshToken);router.replace('/(tabs)/home')}catch(e:any){const message=e.response?.data?.error??(e.code==='ERR_NETWORK'?'Cannot connect to the CDA Connect server. Check that the API service is running.':e.message);setError(message||'Registration failed. Please try again.')}finally{setLoading(false)}}
 return <Screen scroll contentStyle={{maxWidth:560,width:'100%',alignSelf:'center'}}><Pressable onPress={()=>(router.canGoBack()?router.back():router.replace('/'))} style={styles.back}><Ionicons name="chevron-back" size={24} color={colors.text}/></Pressable><Text style={styles.title}>Create Account</Text><Muted>Join your community today.</Muted><Text style={styles.label}>First Name</Text><Input placeholder="Enter your first name" value={f} onChangeText={setF}/><Text style={styles.label}>Last Name</Text><Input placeholder="Enter your last name" value={l} onChangeText={setL}/><Text style={styles.label}>Email</Text><Input placeholder="Enter your email address" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail}/><Selector label="Country" value={selectedCountry.name} placeholder="Select country" options={countryOptions} onSelect={chooseCountry}/><Text style={styles.label}>Phone Number</Text><Input placeholder="Enter your phone number" keyboardType="phone-pad" value={phone} onChangeText={setPhone}/><Selector label="State / Region" value={selectedState?.name||''} placeholder="Select state or region" options={stateOptions} disabled={!stateOptions.length} onSelect={x=>{setSelectedState(states.find(s=>s.isoCode===x.value)||null);setLocalArea('')}}/>{usesPostcode?<><Text style={styles.label}>Postcode</Text><Input placeholder="Enter your postcode" autoCapitalize="characters" value={postcode} onChangeText={setPostcode}/></>:<Selector label={selectedCountry.isoCode==='NG'?'Local Government Area (LGA)':'City / Local Area'} value={localArea} placeholder={selectedCountry.isoCode==='NG'?'Select LGA':'Select city or local area'} options={localOptions} disabled={!selectedState} onSelect={x=>setLocalArea(x.label)}/>} <Text style={styles.label}>Address</Text><Input placeholder="Enter your residential address" multiline value={address} onChangeText={setAddress}/><Text style={styles.label}>Date of Birth</Text><Input placeholder="YYYY-MM-DD" value={dateOfBirth} onChangeText={setDateOfBirth} keyboardType="numbers-and-punctuation"/><Text style={styles.label}>Password</Text><Input placeholder="Minimum 8 characters" secureTextEntry value={p} onChangeText={setP}/><Text style={styles.label}>Confirm Password</Text><Input placeholder="Repeat password" secureTextEntry value={confirm} onChangeText={setConfirm}/>{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}<Button title="Sign Up" loading={loading} disabled={loading} onPress={submit}/><Pressable onPress={()=>router.push('/(auth)/login')}><Text style={styles.login}>Already have an account? <Text style={{color:colors.primary,fontWeight:'800'}}>Login</Text></Text></Pressable></Screen>;
}
const styles=StyleSheet.create({back:{marginTop:8,marginBottom:18,width:40},title:{fontSize:30,fontWeight:'900',color:colors.text},label:{fontSize:13,fontWeight:'700',color:colors.text,marginBottom:7,marginTop:10},selector:{minHeight:52,borderWidth:1,borderColor:colors.border,borderRadius:14,backgroundColor:colors.surface,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},selectorText:{fontSize:16,color:colors.text,flex:1},placeholder:{color:colors.muted},disabled:{opacity:.5},modal:{flex:1,backgroundColor:colors.background,padding:20},modalHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:14},modalTitle:{fontSize:22,fontWeight:'900',color:colors.text},option:{minHeight:52,borderBottomWidth:1,borderBottomColor:colors.border,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:4},optionText:{fontSize:15,color:colors.text,flex:1},error:{color:colors.danger,fontWeight:'700',marginVertical:8},login:{textAlign:'center',marginVertical:20,color:colors.muted,fontSize:13}});
