import {useEffect,useMemo,useState} from 'react';
import {Alert,Image,Pressable,StyleSheet,Text,View} from '@/platform/react-native';
import {router,useLocalSearchParams} from '@/router';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Ionicons} from '@/platform/icons';
import {api} from '@/lib/api';
import {Avatar,Button,Card,EmptyState,Input,Modal,Muted,Screen,TabBar,useAppTheme} from '@/components/UI';
import {useAuth} from '@/store/auth';

type Conversation={Id:string;Name:string;Type:'COMMUNITY'|'GROUP'|'DIRECT';CreatedAt:string;LastMessage?:string;CommunityImage?:string;DirectImage?:string;DirectUserId?:string;Virtual?:boolean};
type Member={UserId:string;FirstName:string;LastName:string;Email:string;ProfileImage?:string;Roles?:string};
type Filter='all'|'groups'|'private'; type People='all'|'leaders'|'members';
export default function CommunityChat(){
 const{id,createGroup}=useLocalSearchParams<{id:string;createGroup?:string}>();const{palette}=useAppTheme();const{user}=useAuth();const qc=useQueryClient();const[search,setSearch]=useState(''),[filter,setFilter]=useState<Filter>('all'),[createOpen,setCreateOpen]=useState(false),[name,setName]=useState(''),[selected,setSelected]=useState<string[]>([]),[people,setPeople]=useState<People>('all');
 const community=useQuery<any>({queryKey:['community',id],queryFn:async()=>(await api.get(`/communities/${id}`)).data});
 const conversations=useQuery<Conversation[]>({queryKey:['conversations',id],queryFn:async()=>(await api.get(`/communities/${id}/conversations`)).data});
 const members=useQuery<Member[]>({queryKey:['members',id],queryFn:async()=>(await api.get(`/communities/${id}/members`)).data});
 const capabilities=useQuery<any>({queryKey:['capabilities',id],queryFn:async()=>(await api.get(`/communities/${id}/capabilities`)).data});
 const canCreate=!capabilities.isLoading;
 const rows=useMemo(()=>{const existing=conversations.data||[],directIds=new Set(existing.filter(x=>x.Type==='DIRECT').map(x=>x.DirectUserId).filter(Boolean));const memberChats:Conversation[]=(members.data||[]).filter(m=>m.UserId!==user?.Id&&!directIds.has(m.UserId)).map(m=>({Id:`member-${m.UserId}`,DirectUserId:m.UserId,Name:`${m.FirstName} ${m.LastName}`.trim()||m.Email,Type:'DIRECT',CreatedAt:'',DirectImage:m.ProfileImage,Virtual:true}));const q=search.trim().toLowerCase();const ok=(x:Conversation)=>filter==='all'||(filter==='groups'?x.Type==='GROUP':x.Type==='DIRECT');return [...existing,...memberChats].filter(x=>ok(x)&&`${x.Name} ${x.LastMessage||''}`.toLowerCase().includes(q)).sort((a,b)=>({COMMUNITY:0,GROUP:1,DIRECT:2}[a.Type]-{COMMUNITY:0,GROUP:1,DIRECT:2}[b.Type])||+new Date(b.CreatedAt||0)-+new Date(a.CreatedAt||0))},[conversations.data,members.data,user?.Id,filter,search]);
 const choices=useMemo(()=>(members.data||[]).filter(m=>people==='all'||(people==='leaders'?/Admin|Owner|Moderator/i.test(String(m.Roles||'')):!/Admin|Owner|Moderator/i.test(String(m.Roles||'')))),[members.data,people]);
 const create=useMutation({mutationFn:async()=>(await api.post(`/communities/${id}/conversations`,{name:name.trim(),type:'GROUP',memberUserIds:selected})).data,onSuccess:(cv)=>{setCreateOpen(false);setName('');setSelected([]);qc.invalidateQueries({queryKey:['conversations',id]});router.push(`/chat/${cv.Id}` as any)},onError:(e:any)=>Alert.alert('Unable to create chat group',e.response?.data?.message||e.message)});
 const openDirect=useMutation({mutationFn:async(userId:string)=>(await api.post(`/communities/${id}/direct-conversations/${userId}`)).data,onSuccess:(cv)=>{qc.invalidateQueries({queryKey:['conversations',id]});router.push(`/chat/${cv.Id}` as any)},onError:(e:any)=>Alert.alert('Unable to open private chat',e.response?.data?.message||e.message)});
 useEffect(()=>{if(createGroup==='1'&&canCreate){setCreateOpen(true);router.setParams({createGroup:undefined} as any)}},[createGroup,canCreate]);
 function toggle(uid:string){setSelected(x=>x.includes(uid)?x.filter(v=>v!==uid):[...x,uid])}
 return <Screen scroll contentStyle={s.page}>
  <TabBar value={filter} onChange={setFilter} items={[{key:'all',label:'All Chats',icon:'chatbubbles-outline'},{key:'groups',label:'Groups',icon:'people-outline'},{key:'private',label:'Private',icon:'lock-closed-outline'}]}/>
  <View style={[s.search,{backgroundColor:palette.surface,borderColor:palette.border}]}><Ionicons name="search-outline" size={23} color={palette.muted}/><Input value={search} onChangeText={setSearch} placeholder="Search chats…" style={s.searchInput}/></View>
  {conversations.isLoading||members.isLoading?<Muted>Loading conversations…</Muted>:rows.length?<Card style={s.list}>{rows.map((x,i)=><Pressable key={x.Id} onPress={()=>x.Virtual&&x.DirectUserId?openDirect.mutate(x.DirectUserId):router.push(`/chat/${x.Id}` as any)} style={[s.row,{borderBottomColor:palette.border}]}>{x.Type==='COMMUNITY'&&x.CommunityImage?<Image source={{uri:x.CommunityImage}} style={s.avatar}/>:<Avatar name={x.Type==='COMMUNITY'?(community.data?.Name||'General'):x.Name} uri={x.Type==='DIRECT'?x.DirectImage:undefined} size={58} backgroundColor={x.Type==='COMMUNITY'?palette.success:[palette.primary,palette.navy,palette.success][i%3]}/>}<View style={{flex:1}}><View style={s.rowTop}><Text style={[s.name,{color:palette.text}]}>{x.Type==='COMMUNITY'?'General Chat':x.Name}</Text>{x.Type==='COMMUNITY'?<Ionicons name="pin" size={16} color={palette.success}/>:null}</View><Muted numberOfLines={2}>{x.LastMessage||'No messages yet. Start the conversation.'}</Muted></View><Ionicons name="chevron-forward" size={20} color={palette.muted}/></Pressable>)}</Card>:<EmptyState icon="chatbubbles-outline" title={search?'No matching chats':'No conversations yet'} body={filter==='private'?'No other community members match your search.':canCreate?'Create a group and select its members.':'Your community conversations will appear here.'}/>} 
  <Modal visible={createOpen} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setCreateOpen(false)}><Screen scroll contentStyle={s.modal}><View style={s.modalHead}><View><Text style={[s.modalTitle,{color:palette.text}]}>Create Group Chat</Text><Muted>Select the members who can access this conversation.</Muted></View><Pressable onPress={()=>setCreateOpen(false)} style={s.touch}><Ionicons name="close" size={27} color={palette.text}/></Pressable></View><Text style={[s.inputLabel,{color:palette.text}]}>Group name</Text><Input value={name} onChangeText={setName} placeholder="e.g. Volunteers Group"/><TabBar value={people} onChange={setPeople} items={[{key:'all',label:'All',icon:'people-outline'},{key:'leaders',label:'Admins & Mods',icon:'shield-outline'},{key:'members',label:'Members',icon:'person-outline'}]}/>{choices.map(m=>{const checked=selected.includes(m.UserId);return <Pressable key={m.UserId} onPress={()=>toggle(m.UserId)} style={[s.person,{borderBottomColor:palette.border}]}><Avatar name={`${m.FirstName} ${m.LastName}`} uri={m.ProfileImage} size={44}/><View style={{flex:1}}><Text style={{color:palette.text,fontWeight:'900'}}>{m.FirstName} {m.LastName}</Text><Muted>{m.Roles||'Member'} · {m.Email}</Muted></View><Ionicons name={checked?'checkbox':'square-outline'} size={25} color={checked?palette.primary:palette.muted}/></Pressable>})}<Button title={`Create Group (${selected.length})`} icon="chatbubbles-outline" loading={create.isPending} disabled={name.trim().length<2||selected.length===0} onPress={()=>create.mutate()}/></Screen></Modal>
 </Screen>
}
const s=StyleSheet.create({page:{width:'100%',maxWidth:900,alignSelf:'center',paddingBottom:125},actions:{flexDirection:'row',justifyContent:'flex-end'},create:{minWidth:118,marginBottom:12},tabs:{flexDirection:'row',borderWidth:1,borderRadius:16,overflow:'hidden',marginBottom:12},tab:{flex:1,minHeight:48,alignItems:'center',justifyContent:'center'},search:{minHeight:56,borderWidth:1,borderRadius:15,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:13,marginBottom:14},searchInput:{flex:1,borderWidth:0,marginBottom:0,backgroundColor:'transparent'},list:{paddingVertical:0,overflow:'hidden'},row:{minHeight:90,flexDirection:'row',gap:12,alignItems:'center',borderBottomWidth:1,paddingVertical:12},avatar:{width:58,height:58,borderRadius:29},rowTop:{flexDirection:'row',alignItems:'center',gap:7},name:{fontSize:16,fontWeight:'900'},modal:{width:'100%',maxWidth:760,alignSelf:'center'},modalHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:12},modalTitle:{fontSize:23,fontWeight:'900'},touch:{minWidth:44,minHeight:44,alignItems:'center',justifyContent:'center'},inputLabel:{fontSize:13,fontWeight:'900',marginBottom:7},peopleTabs:{flexDirection:'row',gap:7,marginVertical:12},peopleTab:{flex:1,minHeight:44,borderWidth:1,borderRadius:11,alignItems:'center',justifyContent:'center'},person:{minHeight:68,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1}});
