import {useEffect,useState,type ComponentProps} from 'react';
import {Alert,Pressable,Share,StyleSheet,Switch,Text,View} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Location from 'expo-location';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {Button,Card,Input as BaseInput,Muted,Screen,useAppTheme} from '@/components/UI';
import {DateField} from '@/components/DateField';
import {displayTime,TimeField} from '@/components/TimeField';

type AgendaDraft={title:string;description:string};
type Draft={title:string;description:string;meetingType:string;date:string;startTime:string;endTime:string;location:string;format:'IN_PERSON'|'ONLINE';onlineMeetingUrl:string;agenda:AgendaDraft[];allowRegistration:boolean;allowCalendar:boolean};
function Input(props:ComponentProps<typeof BaseInput>){if(props.placeholder==='YYYY-MM-DD')return <DateField value={String(props.value||'')} onChange={props.onChangeText||(()=>{})} minimumDate={new Date()} showIcon={false}/>;if(props.placeholder==='HH:MM')return <TimeField value={String(props.value||'')} onChange={props.onChangeText||(()=>{})} showIcon={false}/>;return <BaseInput {...props}/>}
const initial:Draft={title:'',description:'',meetingType:'General Meeting',date:'',startTime:'',endTime:'',location:'',format:'IN_PERSON',onlineMeetingUrl:'',agenda:[],allowRegistration:true,allowCalendar:true};

export default function CreateMeeting(){
 const{id}=useLocalSearchParams<{id:string}>();const{palette}=useAppTheme();const qc=useQueryClient();const[step,setStep]=useState(1),[draft,setDraft]=useState<Draft>(initial),[published,setPublished]=useState<any>();const key=`cda-meeting-draft-${id}`;
 const community=useQuery<any>({queryKey:['community',id],queryFn:async()=>(await api.get(`/communities/${id}`)).data});
 useEffect(()=>{AsyncStorage.getItem(key).then(saved=>{if(saved)try{setDraft({...initial,...JSON.parse(saved)})}catch{}})},[key]);
 const create=useMutation({mutationFn:async()=>{const start=localDate(draft.date,draft.startTime),end=localDate(draft.date,draft.endTime);return(await api.post(`/communities/${id}/meetings`,{title:draft.title.trim(),description:draft.description.trim()||undefined,meetingType:draft.meetingType,location:draft.format==='IN_PERSON'?draft.location.trim()||undefined:undefined,onlineMeetingUrl:draft.format==='ONLINE'?draft.onlineMeetingUrl.trim()||undefined:undefined,startDateTime:start.toISOString(),endDateTime:end.toISOString(),allowRegistration:draft.allowRegistration,allowCalendar:draft.allowCalendar,agenda:draft.agenda.filter(x=>x.title.trim()).map((x,index)=>({title:x.title.trim(),description:x.description.trim()||undefined,position:index+1}))})).data},onSuccess:async data=>{await AsyncStorage.removeItem(key);setPublished(data);qc.invalidateQueries({queryKey:['meetings',id]})},onError:(e:any)=>Alert.alert('Unable to publish meeting',e.response?.data?.message||'Check the required fields and try again.')});
 const set=<K extends keyof Draft>(field:K,value:Draft[K])=>setDraft(current=>({...current,[field]:value}));
 async function currentLocation(){try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted')return Alert.alert('Location permission required','Allow location access to use your current location.');const position=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});const places=await Location.reverseGeocodeAsync(position.coords);const p=places[0];const address=p?[p.name,p.street,p.city,p.district,p.region,p.postalCode,p.country].filter((v,i,a)=>v&&a.indexOf(v)===i).join(', '):`${position.coords.latitude.toFixed(6)}, ${position.coords.longitude.toFixed(6)}`;set('location',address)}catch{Alert.alert('Location unavailable','Enter the meeting location manually.')}}
 function next(){if(step===1){if(!draft.title.trim()||!draft.date||!draft.startTime||!draft.endTime)return Alert.alert('Meeting details required','Enter a title, date, start time and end time.');const start=localDate(draft.date,draft.startTime),end=localDate(draft.date,draft.endTime);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<=start)return Alert.alert('Check meeting time','End time must be later than the start time.');if(start.getTime()<=Date.now())return Alert.alert('Choose an upcoming time','A new meeting must start in the future.');if(draft.format==='IN_PERSON'&&!draft.location.trim())return Alert.alert('Location required','Enter a meeting location or use your current location.');if(draft.format==='ONLINE'&&!/^https?:\/\//i.test(draft.onlineMeetingUrl))return Alert.alert('Online link required','Enter a valid http or https meeting link.')}setStep(value=>Math.min(4,value+1))}
 if(published)return <Published meeting={published} community={community.data} id={id!} reset={()=>{setDraft(initial);setPublished(undefined);setStep(1)}} palette={palette}/>;
 return <Screen scroll contentStyle={s.page}><Progress step={step} palette={palette}/>{step===1?<Details draft={draft} set={set} location={currentLocation} palette={palette}/>:step===2?<Agenda draft={draft} set={set} palette={palette}/>:step===3?<Settings draft={draft} set={set} palette={palette}/>:<Review draft={draft} edit={setStep} palette={palette}/>}<View style={s.navigation}>{step>1?<Button title="Back" icon="chevron-back" variant="secondary" onPress={()=>setStep(value=>value-1)}/>:null}<Button title={step===4?'Publish Meeting':step===1?'Next: Add Agenda':step===2?'Next: Settings':'Next: Review & Publish'} icon={step===4?'send':'chevron-forward'} loading={create.isPending} onPress={()=>step===4?create.mutate():next()}/></View></Screen>
}

function Progress({step,palette}:{step:number;palette:any}){return <View style={s.progress}>{['Meeting Details','Agenda','Settings','Review & Publish'].map((label,index)=>{const n=index+1,active=n<=step;return <View key={label} style={s.progressItem}><View style={[s.stepCircle,{backgroundColor:active?palette.primary:palette.backgroundSoft}]}><Text style={{color:active?'#fff':palette.muted,fontWeight:'900'}}>{n}</Text></View><Text style={{color:active?palette.primary:palette.muted,fontSize:11,fontWeight:'800',textAlign:'center'}}>{label}</Text></View>})}</View>}
function Details({draft,set,location,palette}:{draft:Draft;set:any;location:()=>void;palette:any}){return <View><Title title="Meeting Details" subtitle="Provide the information members need to attend." palette={palette}/><Card><Label text="Meeting Title *" palette={palette}/><Input value={draft.title} onChangeText={v=>set('title',v)} placeholder="Meeting title" maxLength={100}/><Label text="Description" palette={palette}/><Input value={draft.description} onChangeText={v=>set('description',v)} placeholder="What will be discussed?" multiline maxLength={1000}/><Label text="Meeting Type" palette={palette}/><View style={s.choiceRow}>{['General Meeting','Members Only','Committee Meeting'].map(type=><Choice key={type} label={type} selected={draft.meetingType===type} press={()=>set('meetingType',type)} palette={palette}/>)}</View><View><Label text="Date *" palette={palette}/><Input value={draft.date} onChangeText={v=>set('date',v)} placeholder="YYYY-MM-DD" keyboardType="numbers-and-punctuation"/></View><View style={s.timeRow}><View style={s.timeField}><Label text="Start Time *" palette={palette}/><Input value={draft.startTime} onChangeText={v=>set('startTime',v)} placeholder="HH:MM" keyboardType="numbers-and-punctuation"/></View><View style={s.timeField}><Label text="End Time *" palette={palette}/><Input value={draft.endTime} onChangeText={v=>set('endTime',v)} placeholder="HH:MM" keyboardType="numbers-and-punctuation"/></View></View><Muted>Times use this phone’s current time zone automatically.</Muted><Label text="Meeting Format" palette={palette}/><View style={s.choiceRow}><Choice label="In-person" selected={draft.format==='IN_PERSON'} press={()=>set('format','IN_PERSON')} palette={palette}/><Choice label="Online" selected={draft.format==='ONLINE'} press={()=>set('format','ONLINE')} palette={palette}/></View>{draft.format==='IN_PERSON'?<><Label text="Location *" palette={palette}/><View style={s.location}><Input value={draft.location} onChangeText={v=>set('location',v)} placeholder="Venue or address" style={{flex:1,marginBottom:0}}/><Pressable accessibilityLabel="Use current location" onPress={location} style={[s.locationButton,{backgroundColor:palette.primarySoft}]}><Ionicons name="locate" size={23} color={palette.primary}/></Pressable></View><Muted>The detected address remains editable.</Muted></>:<><Label text="Online Meeting Link *" palette={palette}/><Input value={draft.onlineMeetingUrl} onChangeText={v=>set('onlineMeetingUrl',v)} placeholder="https://…" autoCapitalize="none" keyboardType="url"/></>}</Card></View>}
function Agenda({draft,set,palette}:{draft:Draft;set:any;palette:any}){function change(i:number,k:keyof AgendaDraft,v:string){set('agenda',draft.agenda.map((x,n)=>n===i?{...x,[k]:v}:x))}return <View><Title title="Agenda" subtitle="Add the real topics that will be discussed. Empty items are not published." palette={palette}/><Card><View style={s.sectionHead}><Text style={[s.sectionTitle,{color:palette.text}]}>Agenda Items</Text><Button title="Add Item" icon="add" variant="secondary" onPress={()=>set('agenda',[...draft.agenda,{title:'',description:''}])}/></View>{draft.agenda.length?draft.agenda.map((item,i)=><View key={i} style={[s.agendaItem,{borderColor:palette.border}]}><View style={[s.agendaNumber,{backgroundColor:palette.primarySoft}]}><Text style={{color:palette.primary,fontWeight:'900'}}>{i+1}</Text></View><View style={{flex:1}}><Input value={item.title} onChangeText={v=>change(i,'title',v)} placeholder="Agenda item title"/><Input value={item.description} onChangeText={v=>change(i,'description',v)} placeholder="Details (optional)" multiline/></View><Pressable accessibilityLabel="Remove agenda item" onPress={()=>set('agenda',draft.agenda.filter((_,n)=>n!==i))} style={s.touch}><Ionicons name="trash-outline" size={21} color={palette.danger}/></Pressable></View>):<Muted>No agenda items yet. You can publish without an agenda or add items now.</Muted>}</Card></View>}
function Settings({draft,set,palette}:{draft:Draft;set:any;palette:any}){return <View><Title title="Meeting Settings" subtitle="Configure options supported by CDA General Meetings." palette={palette}/><Card><Setting icon="people-outline" title="Allow Member Registration" body="Members can respond Going, Maybe or Can’t Attend." value={draft.allowRegistration} change={(v)=>set('allowRegistration',v)} palette={palette}/><Setting icon="calendar-outline" title="Add to Calendar" body="Members can use their phone calendar." value={draft.allowCalendar} change={(v)=>set('allowCalendar',v)} palette={palette}/><View style={[s.infoBox,{backgroundColor:palette.primarySoft}]}><Ionicons name="shield-checkmark-outline" size={25} color={palette.primary}/><Muted style={{flex:1}}>Meeting access follows the selected meeting type. Publishing permissions are enforced by the community backend.</Muted></View></Card></View>}
function Review({draft,edit,palette}:{draft:Draft;edit:(n:number)=>void;palette:any}){return <View><Title title="Review & Publish" subtitle="Confirm the live meeting data before publishing." palette={palette}/><Card><ReviewHead title="Meeting Details" edit={()=>edit(1)} palette={palette}/><ReviewRow label="Title" value={draft.title} palette={palette}/><ReviewRow label="Description" value={draft.description||'Not provided'} palette={palette}/><ReviewRow label="Meeting Type" value={draft.meetingType} palette={palette}/><ReviewRow label="Date & Time" value={`${draft.date} · ${displayTime(draft.startTime)} – ${displayTime(draft.endTime)}`} palette={palette}/><ReviewRow label="Format" value={draft.format==='ONLINE'?'Online':'In-person'} palette={palette}/><ReviewRow label="Location" value={draft.format==='ONLINE'?draft.onlineMeetingUrl:draft.location} palette={palette}/></Card><Card><ReviewHead title={`Agenda (${draft.agenda.filter(x=>x.title.trim()).length} items)`} edit={()=>edit(2)} palette={palette}/>{draft.agenda.filter(x=>x.title.trim()).map((x,i)=><ReviewRow key={i} label={`${i+1}`} value={x.title} palette={palette}/>)}</Card><Card><ReviewHead title="Settings Summary" edit={()=>edit(3)} palette={palette}/><ReviewRow label="Member registration" value={draft.allowRegistration?'Enabled':'Disabled'} palette={palette}/><ReviewRow label="Add to calendar" value={draft.allowCalendar?'Enabled':'Disabled'} palette={palette}/></Card></View>}
function Published({meeting,community,id,reset,palette}:{meeting:any;community:any;id:string;reset:()=>void;palette:any}){const share=()=>Share.share({title:meeting.Title,message:`${meeting.Title}\n${new Date(meeting.StartDateTime).toLocaleString()}\n${meeting.Location||meeting.OnlineMeetingUrl||''}`});return <Screen scroll contentStyle={s.success}><View style={[s.successIcon,{backgroundColor:palette.primarySoft}]}><Ionicons name="calendar" size={63} color={palette.primary}/><Ionicons name="checkmark-circle" size={35} color={palette.success} style={s.check}/></View><Text style={[s.successTitle,{color:palette.primaryDark}]}>Meeting Published Successfully!</Text><Muted style={{textAlign:'center'}}>The meeting is now available in Upcoming Meetings.</Muted><Card><Text style={[s.sectionTitle,{color:palette.text}]}>{meeting.Title}</Text><ReviewRow label="Date & Time" value={new Date(meeting.StartDateTime).toLocaleString()} palette={palette}/><ReviewRow label="Location" value={meeting.Location||meeting.OnlineMeetingUrl||'To be confirmed'} palette={palette}/><ReviewRow label="Community" value={community?.Name||'Community'} palette={palette}/></Card><Button title="View Meeting" icon="eye-outline" onPress={()=>router.replace(`/community/${id}/meeting/${meeting.Id}` as any)}/><Button title="Share Meeting" icon="share-social-outline" variant="secondary" onPress={share}/><Button title="Go to Community Home" icon="home" onPress={()=>router.replace(`/community/${id}` as any)}/><Button title="Create Another Meeting" icon="add" variant="ghost" onPress={reset}/></Screen>}
function localDate(date:string,time:string){return new Date(`${date}T${time.length===5?`${time}:00`:time}`)}
function Title({title,subtitle,palette}:{title:string;subtitle:string;palette:any}){return <View style={s.titleBlock}><Text style={[s.pageTitle,{color:palette.text}]}>{title}</Text><Muted>{subtitle}</Muted></View>}
function Label({text,palette}:{text:string;palette:any}){return <Text style={[s.label,{color:palette.text}]}>{text}</Text>}
function Choice({label,selected,press,palette}:{label:string;selected:boolean;press:()=>void;palette:any}){return <Pressable onPress={press} style={[s.choice,{borderColor:selected?palette.primary:palette.border,backgroundColor:selected?palette.primarySoft:palette.surface}]}><Ionicons name={selected?'checkmark-circle':'ellipse-outline'} size={22} color={selected?palette.primary:palette.muted}/><Text style={{color:palette.text,fontWeight:'800',textAlign:'center'}}>{label}</Text></Pressable>}
function Setting({icon,title,body,value,change,palette}:{icon:keyof typeof Ionicons.glyphMap;title:string;body:string;value:boolean;change:(v:boolean)=>void;palette:any}){return <View style={s.setting}><View style={[s.settingIcon,{backgroundColor:palette.primarySoft}]}><Ionicons name={icon} size={22} color={palette.primary}/></View><View style={{flex:1}}><Text style={{color:palette.text,fontWeight:'900'}}>{title}</Text><Muted>{body}</Muted></View><Switch value={value} onValueChange={change} trackColor={{false:palette.border,true:palette.primary}}/></View>}
function ReviewHead({title,edit,palette}:{title:string;edit:()=>void;palette:any}){return <View style={s.sectionHead}><Text style={[s.sectionTitle,{color:palette.text}]}>{title}</Text><Pressable onPress={edit} style={s.edit}><Ionicons name="pencil" size={17} color={palette.primary}/><Text style={{color:palette.primary,fontWeight:'900'}}>Edit</Text></Pressable></View>}
function ReviewRow({label,value,palette}:{label:string;value:string;palette:any}){return <View style={s.reviewRow}><Muted style={{width:120}}>{label}</Muted><Text style={{color:palette.text,flex:1}}>{value}</Text></View>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:920,alignSelf:'center',paddingBottom:110},touch:{width:44,height:44,alignItems:'center',justifyContent:'center'},progress:{flexDirection:'row',justifyContent:'space-around',marginVertical:12},progressItem:{flex:1,alignItems:'center',gap:7},stepCircle:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center'},titleBlock:{marginVertical:14},pageTitle:{fontSize:21,fontWeight:'900',marginBottom:5},label:{fontSize:13,fontWeight:'900',marginBottom:7,marginTop:10},choiceRow:{flexDirection:'row',gap:8,flexWrap:'wrap'},choice:{flex:1,minWidth:135,minHeight:78,borderWidth:1,borderRadius:13,alignItems:'center',justifyContent:'center',gap:7,padding:10},two:{flexDirection:'row',gap:10,flexWrap:'wrap'},timeRow:{flexDirection:'row',gap:10},timeField:{flex:1,minWidth:0},location:{flexDirection:'row',gap:8,alignItems:'center'},locationButton:{width:48,height:48,borderRadius:12,alignItems:'center',justifyContent:'center'},navigation:{flexDirection:'row',justifyContent:'flex-end',gap:10,marginTop:16},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:12},sectionTitle:{fontSize:17,fontWeight:'900'},agendaItem:{flexDirection:'row',alignItems:'flex-start',gap:8,borderWidth:1,borderRadius:13,padding:10,marginBottom:9},agendaNumber:{width:32,height:32,borderRadius:16,alignItems:'center',justifyContent:'center',marginTop:6},setting:{minHeight:75,flexDirection:'row',alignItems:'center',gap:12},settingIcon:{width:46,height:46,borderRadius:12,alignItems:'center',justifyContent:'center'},infoBox:{flexDirection:'row',alignItems:'center',gap:10,borderRadius:13,padding:13,marginTop:10},edit:{flexDirection:'row',alignItems:'center',gap:5},reviewRow:{flexDirection:'row',gap:10,paddingVertical:8},success:{width:'100%',maxWidth:760,alignSelf:'center',paddingBottom:110,alignItems:'stretch'},successIcon:{width:170,height:170,borderRadius:85,alignItems:'center',justifyContent:'center',alignSelf:'center',marginTop:25},check:{position:'absolute',right:25,bottom:24},successTitle:{fontSize:32,fontWeight:'900',textAlign:'center',marginTop:16,marginBottom:6}});
