import {useEffect,useState} from 'react';
import {Alert,Image,Platform,Pressable,StyleSheet,Text,View} from '@/platform/react-native';
import {router,useLocalSearchParams} from '@/router';
import {useMutation,useQueryClient} from '@tanstack/react-query';
import {Ionicons} from '@/platform/icons';
import * as ImagePicker from '@/platform/image-picker';
import * as DocumentPicker from '@/platform/document-picker';
import {AudioModule,RecordingPresets,setAudioModeAsync,useAudioPlayer,useAudioRecorder,useAudioRecorderState} from '@/platform/audio';
import {useVideoPlayer,VideoView} from '@/platform/video';
import {api} from '@/lib/api';
import {Button,Card,Input,Muted,Screen,useAppTheme} from '@/components/UI';
import {useAccessibility} from '@/store/accessibility';

const MORE_TYPES=[['TEXT','Text'],['POLL','Poll'],['EVENT','Event'],['LOST_FOUND','Lost & found'],['RECOMMENDATION','Recommendation'],['QUESTION','Question'],['ALERT','Alert'],['LOCAL_NEWS','Local news']] as const;
type PostType='TEXT'|'PHOTO'|'VIDEO'|'DOCUMENT'|'VOICE'|'POLL'|'EVENT'|'LOST_FOUND'|'RECOMMENDATION'|'QUESTION'|'ALERT'|'LOCAL_NEWS';
type Media={uri:string;name:string;type:string};

export default function CreatePost(){
 const{id}=useLocalSearchParams<{id:string}>(),{palette}=useAppTheme(),a=useAccessibility(),qc=useQueryClient();
 const[body,setBody]=useState(''),[postType,setPostType]=useState<PostType>('TEXT'),[media,setMedia]=useState<Media|null>(null),[caption,setCaption]=useState(''),[transcript,setTranscript]=useState('');
 const recorder=useAudioRecorder(RecordingPresets.HIGH_QUALITY),recording=useAudioRecorderState(recorder);
 useEffect(()=>{AudioModule.requestRecordingPermissionsAsync().then(x=>{if(x.granted)setAudioModeAsync({playsInSilentMode:true,allowsRecording:true})})},[]);
 async function upload(file:Media){const fd=new FormData();if(Platform.OS==='web'){const blob=await(await fetch(file.uri)).blob();fd.append('file',blob,file.name)}else fd.append('file',{uri:file.uri,name:file.name,type:file.type} as any);return(await api.post('/media/upload',fd,{headers:{'Content-Type':'multipart/form-data'}})).data}
 const create=useMutation({mutationFn:async()=>{const uploaded=media?await upload(media):null;return api.post(`/communities/${id}/feed`,{body:body.trim(),postType,mediaUrl:uploaded?.url,mediaType:uploaded?.mimeType||media?.type,documentName:postType==='DOCUMENT'?media?.name:undefined,caption:caption.trim()||undefined,transcript:transcript.trim()||undefined,originalLanguage:a.language,isAnnouncement:false})},onSuccess:()=>{qc.invalidateQueries({queryKey:['feed',id]});router.replace(`/community/${id}/feed` as never)},onError:(e:any)=>Alert.alert('Unable to post',e.response?.data?.message||'Please try again.')});
 async function pick(kind:'PHOTO'|'VIDEO'|'DOCUMENT'){if(kind==='DOCUMENT'){const r=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true,multiple:false});if(!r.canceled){const x=r.assets[0];setPostType(kind);setMedia({uri:x.uri,name:x.name,type:x.mimeType||'application/octet-stream'})}return}const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:[kind==='PHOTO'?'images':'videos'],quality:.85});if(!r.canceled){const x=r.assets[0];setPostType(kind);setMedia({uri:x.uri,name:x.fileName||`${kind.toLowerCase()}-${Date.now()}`,type:x.mimeType||(kind==='PHOTO'?'image/jpeg':'video/mp4')})}}
 async function voice(){if(recording.isRecording){await recorder.stop();if(recorder.uri){setPostType('VOICE');setMedia({uri:recorder.uri,name:`voice-${Date.now()}.m4a`,type:'audio/m4a'})}}else{await recorder.prepareToRecordAsync();recorder.record()}}
 function more(){Alert.alert('Post type','Choose a post type',[...MORE_TYPES.map(([value,label])=>({text:label,onPress:()=>setPostType(value)})),{text:'Cancel',style:'cancel'}] as any)}
 return <Screen scroll contentStyle={s.page}><Card style={s.composer}><Input autoFocus value={body} onChangeText={setBody} placeholder="Share an update, ask a question, mention @someone or add #topic…" multiline style={s.input}/><View style={[s.quickRow,{borderTopColor:palette.border}]}><Quick icon="image-outline" label="Photo" color="#65B816" press={()=>void pick('PHOTO')}/><Quick icon="videocam-outline" label="Video" color="#8B3DFF" press={()=>void pick('VIDEO')}/><Quick icon={recording.isRecording?'stop-circle':'mic-outline'} label={recording.isRecording?'Stop':'Voice'} color={palette.primary} press={()=>void voice()}/><Quick icon="document-text-outline" label="File" color="#F58413" press={()=>void pick('DOCUMENT')}/><Quick icon="ellipsis-horizontal" label="More" color={palette.text} press={more}/></View>{postType!=='TEXT'?<Muted style={s.type}>Post type: {postType.replace('_',' ').toLowerCase()}</Muted>:null}{media?<Card style={[s.attachment,{backgroundColor:palette.primarySoft}]}><MediaPreview media={media} postType={postType} palette={palette}/><View style={s.mediaRow}><Ionicons name={postType==='PHOTO'?'image':postType==='VIDEO'?'videocam':postType==='VOICE'?'mic':'document'} size={24} color={palette.primary}/><View style={{flex:1}}><Text numberOfLines={1} style={{color:palette.text,fontWeight:'800'}}>{media.name}</Text><Muted>{media.type}</Muted></View><Pressable accessibilityLabel="Remove attachment" onPress={()=>{setMedia(null);setPostType('TEXT')}} style={s.touch}><Ionicons name="close" size={22} color={palette.text}/></Pressable></View><Input value={caption} onChangeText={setCaption} placeholder="Add a caption or media description…"/>{postType==='VOICE'?<Input value={transcript} onChangeText={setTranscript} placeholder="Add a voice transcript…" multiline/>:null}</Card>:null}<Button title="Post to community" icon="send" loading={create.isPending} disabled={!body.trim()&&!media} onPress={()=>create.mutate()}/></Card></Screen>
}
function MediaPreview({media,postType,palette}:{media:Media;postType:PostType;palette:any}){if(postType==='PHOTO')return <Image source={{uri:media.uri}} style={s.previewImage} resizeMode="cover" accessibilityLabel="Selected photo preview"/>;if(postType==='VIDEO')return <VideoPreview uri={media.uri}/>;if(postType==='VOICE')return <VoicePreview uri={media.uri} palette={palette}/>;return <View style={[s.documentPreview,{backgroundColor:palette.surface,borderColor:palette.border}]}><View style={[s.documentIcon,{backgroundColor:palette.warningLight}]}><Ionicons name="document-text" size={44} color="#F58413"/></View><Text numberOfLines={2} style={[s.documentName,{color:palette.text}]}>{media.name}</Text><Muted>{media.type||'Document'} · Ready to upload</Muted></View>}
function VideoPreview({uri}:{uri:string}){const player=useVideoPlayer(uri,p=>{p.loop=false});return <VideoView player={player} style={s.previewVideo} nativeControls contentFit="contain" accessibilityLabel="Selected video preview"/>}
function VoicePreview({uri,palette}:{uri:string;palette:any}){const player=useAudioPlayer(uri);return <View style={[s.voicePreview,{backgroundColor:palette.surface,borderColor:palette.border}]}><Pressable accessibilityRole="button" accessibilityLabel={player.playing?'Pause voice preview':'Play voice preview'} onPress={()=>player.playing?player.pause():player.play()} style={[s.playButton,{backgroundColor:palette.primary}]}><Ionicons name={player.playing?'pause':'play'} size={27} color="#fff"/></Pressable><View style={{flex:1}}><Text style={[s.voiceTitle,{color:palette.text}]}>Voice recording</Text><Muted>Tap to {player.playing?'pause':'play'} your recording</Muted></View><Ionicons name="musical-notes-outline" size={30} color={palette.primary}/></View>}
function Quick({icon,label,color,press}:{icon:keyof typeof Ionicons.glyphMap;label:string;color:string;press:()=>void}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={press} style={s.quick}><Ionicons name={icon} size={27} color={color}/><Text style={s.quickText}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:820,alignSelf:'center',paddingBottom:125},composer:{paddingVertical:12},input:{minHeight:130,textAlignVertical:'top'},quickRow:{flexDirection:'row',borderTopWidth:1,paddingVertical:12},quick:{flex:1,minWidth:0,alignItems:'center',justifyContent:'center',gap:5,minHeight:58},quickText:{fontSize:11,fontWeight:'800',color:'#11243F'},type:{textTransform:'capitalize',marginVertical:8},attachment:{marginTop:10,overflow:'hidden'},previewImage:{width:'100%',height:280,borderRadius:14,marginBottom:12,backgroundColor:'#E2E8F0'},previewVideo:{width:'100%',height:280,borderRadius:14,marginBottom:12,backgroundColor:'#07142F'},voicePreview:{minHeight:92,borderWidth:1,borderRadius:14,padding:14,flexDirection:'row',alignItems:'center',gap:13,marginBottom:12},playButton:{width:54,height:54,borderRadius:27,alignItems:'center',justifyContent:'center'},voiceTitle:{fontSize:16,fontWeight:'900'},documentPreview:{minHeight:180,borderWidth:1,borderRadius:14,alignItems:'center',justifyContent:'center',padding:18,marginBottom:12},documentIcon:{width:76,height:76,borderRadius:20,alignItems:'center',justifyContent:'center',marginBottom:10},documentName:{fontSize:15,fontWeight:'900',textAlign:'center',marginBottom:4},mediaRow:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:8},touch:{width:44,height:44,alignItems:'center',justifyContent:'center'}})
