import { useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { api } from '@/lib/api';
import { Button, Card, Input, Muted, Screen, useAppTheme } from '@/components/UI';

export default function CreateAnnouncementScreen(){
 const {id}=useLocalSearchParams<{id:string}>();const {palette}=useAppTheme();const qc=useQueryClient();
 const [title,setTitle]=useState('');const [message,setMessage]=useState('');
 const publish=useMutation({mutationFn:async()=>api.post(`/communities/${id}/feed`,{body:[title.trim(),message.trim()].filter(Boolean).join('\n\n'),postType:'TEXT',isAnnouncement:true}),onSuccess:()=>{qc.invalidateQueries({queryKey:['feed',id]});Alert.alert('Announcement published','Community members can now see this announcement.',[{text:'View announcements',onPress:()=>router.replace(`/community/${id}/feed?tab=announcements` as never)}])},onError:(e:any)=>Alert.alert('Unable to publish',e.response?.data?.message||'Only authorised community administrators can publish announcements.')});
 return <Screen scroll contentStyle={s.page}><View style={[s.hero,{backgroundColor:palette.primarySoft}]}><View style={[s.icon,{backgroundColor:palette.surface}]}><Ionicons name="megaphone-outline" size={38} color={palette.primary}/></View><View style={{flex:1}}><Text style={[s.heroTitle,{color:palette.primaryDark}]}>Post an announcement</Text><Muted>Publish an official update to your community feed.</Muted></View></View><Card><Text style={[s.label,{color:palette.text}]}>Announcement title</Text><Input value={title} onChangeText={x=>setTitle(x.slice(0,120))} placeholder="Enter a clear title"/><Muted style={s.count}>{title.length}/120</Muted><Text style={[s.label,{color:palette.text}]}>Announcement message</Text><Input value={message} onChangeText={x=>setMessage(x.slice(0,2000))} placeholder="Write the announcement details…" multiline style={s.message}/><Muted style={s.count}>{message.length}/2000</Muted></Card><View style={[s.notice,{backgroundColor:palette.primarySoft}]}><Ionicons name="notifications-outline" size={25} color={palette.primary}/><Muted style={{flex:1}}>This will be marked as an administrator announcement and shown in the Announcements tab.</Muted></View><Button title="Publish announcement" icon="send" loading={publish.isPending} disabled={!title.trim()||!message.trim()} onPress={()=>publish.mutate()}/></Screen>
}
const s=StyleSheet.create({page:{width:'100%',maxWidth:820,alignSelf:'center',paddingBottom:125},hero:{borderRadius:18,padding:18,flexDirection:'row',alignItems:'center',gap:14,marginBottom:12},icon:{width:70,height:70,borderRadius:35,alignItems:'center',justifyContent:'center'},heroTitle:{fontSize:20,fontWeight:'900',marginBottom:5},label:{fontSize:15,fontWeight:'900',marginTop:8,marginBottom:7},message:{minHeight:180,textAlignVertical:'top'},count:{textAlign:'right',marginTop:-7},notice:{borderRadius:15,padding:15,flexDirection:'row',alignItems:'center',gap:11}})
