import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { api } from '@/lib/api';
import { Badge, Card, EmptyState, Header, Input, Muted, Screen, useAppTheme } from '@/components/UI';
import { AttachmentPreview, type Attachment } from '@/components/AttachmentPreview';

export default function Documents() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { palette } = useAppTheme(); const [query, setQuery] = useState(''); const [preview, setPreview] = useState<Attachment>(null);
  const documents = useQuery<any[]>({ queryKey: ['documents', id, query], queryFn: async () => (await api.get(`/communities/${id}/documents`, { params: { q: query } })).data });
  return <Screen scroll contentStyle={styles.page}><Header page title="Document Centre" subtitle="Searchable community knowledge with version history" /><Input value={query} onChangeText={setQuery} placeholder="Search constitution, policies, minutes, reports…" />{!documents.data?.length ? <EmptyState title="No documents found" body="Community constitutions, policies, minutes, reports, forms and procedures will live here." /> : documents.data.map(document => <Pressable key={document.Id} disabled={!document.FileUrl} accessibilityRole="button" accessibilityLabel={`Preview ${document.Title}`} onPress={() => setPreview({ url: document.FileUrl, title: document.Title })}><Card><View style={styles.top}><View style={[styles.icon, { backgroundColor: palette.primarySoft }]}><Ionicons name="document-text-outline" size={23} color={palette.primary} /></View><View style={styles.flex}><Text style={[styles.title, { color: palette.text }]}>{document.Title}</Text><Muted>{document.Category} · version {document.CurrentVersion}</Muted></View><Badge text={document.Visibility} /></View>{document.Summary ? <Muted style={styles.summary}>{document.Summary}</Muted> : null}{document.ChangeNotes ? <Muted style={styles.change}>Latest: {document.ChangeNotes}</Muted> : null}{document.FileUrl ? <View style={styles.open}><Ionicons name="eye-outline" size={18} color={palette.primary} /><Text style={{ color: palette.primary, fontWeight: '800' }}>Preview file</Text></View> : <Muted style={styles.change}>No file attached</Muted>}</Card></Pressable>)}<AttachmentPreview attachment={preview} onClose={() => setPreview(null)} /></Screen>;
}
const styles = StyleSheet.create({ page: { width: '100%', maxWidth: 900, alignSelf: 'center', paddingBottom: 120 }, flex: { flex: 1, minWidth: 0 }, top: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, alignItems: 'center' }, icon: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 16, fontWeight: '900' }, summary: { marginTop: 10 }, change: { marginTop: 6 }, open: { minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 6 } });
