import {useEffect,useMemo,useState} from 'react';
import {Alert,Modal,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {Avatar,Badge,Button,Card,EmptyState,Header,Input,Muted,Screen,useAppTheme} from '@/components/UI';
import {DateField} from '@/components/DateField';

type Exco={Id:string;UserId:string;Position:string;Department?:string;AppointedDate:string;TenureEndDate?:string;Notes?:string;Status:'ACTIVE'|'INACTIVE';FirstName:string;LastName:string;Email:string;Phone?:string;ProfileImage?:string};
type Member={UserId:string;FirstName:string;LastName:string;Email:string;Phone?:string;ProfileImage?:string};
const positions=['Chairperson','Vice Chairperson','Secretary','Assistant Secretary','Treasurer','Financial Secretary','Public Relations Officer','Welfare Officer','Organising Secretary','Provost','Ex-Officio','Member'];
const today=()=>new Date().toISOString().slice(0,10);

export default function Excos(){
 const{id,addExco}=useLocalSearchParams<{id:string;addExco?:string}>();const{palette}=useAppTheme();const qc=useQueryClient();
 const[search,setSearch]=useState('');const[status,setStatus]=useState<'ALL'|'ACTIVE'|'INACTIVE'>('ALL');const[addOpen,setAddOpen]=useState(false);const[picker,setPicker]=useState<'member'|'position'|null>(null);const[action,setAction]=useState<Exco|null>(null);
 const[selected,setSelected]=useState<Member|null>(null);const[position,setPosition]=useState('');const[department,setDepartment]=useState('');const[appointed,setAppointed]=useState(today());const[tenureEnd,setTenureEnd]=useState('');const[notes,setNotes]=useState('');
 const query=useQuery<{items:Exco[];canManage:boolean}>({queryKey:['excos',id],queryFn:async()=>(await api.get(`/communities/${id}/excos`)).data});
 useEffect(()=>{if(addExco==='1'){setAddOpen(true);router.setParams({addExco:undefined})}},[addExco]);
 const members=useQuery<Member[]>({queryKey:['members',id],queryFn:async()=>(await api.get(`/communities/${id}/members`)).data,enabled:addOpen});
 const create=useMutation({mutationFn:()=>api.post(`/communities/${id}/excos`,{userId:selected?.UserId,position,department:department.trim()||undefined,appointedDate:appointed,tenureEndDate:tenureEnd||undefined,notes:notes.trim()||undefined}),onSuccess:()=>{qc.invalidateQueries({queryKey:['excos',id]});closeAdd();Alert.alert('Exco added','The appointment is now listed for this community.')},onError:(e:any)=>Alert.alert('Could not add Exco',e.response?.data?.error||e.response?.data?.message||'Please try again.')});
 const update=useMutation({mutationFn:(v:{item:Exco;status:'ACTIVE'|'INACTIVE'})=>api.patch(`/communities/${id}/excos/${v.item.Id}`,{status:v.status}),onSuccess:()=>{qc.invalidateQueries({queryKey:['excos',id]});setAction(null)},onError:(e:any)=>Alert.alert('Update failed',e.response?.data?.error||'Please try again.')});
 const remove=useMutation({mutationFn:(item:Exco)=>api.delete(`/communities/${id}/excos/${item.Id}`),onSuccess:()=>{qc.invalidateQueries({queryKey:['excos',id]});setAction(null)},onError:(e:any)=>Alert.alert('Remove failed',e.response?.data?.error||'Please try again.')});
 const items=query.data?.items||[];const visible=useMemo(()=>items.filter(x=>(status==='ALL'||x.Status===status)&&`${x.FirstName} ${x.LastName} ${x.Email} ${x.Position} ${x.Department||''}`.toLowerCase().includes(search.trim().toLowerCase())),[items,status,search]);
 const active=items.filter(x=>x.Status==='ACTIVE');const roles=new Set(active.map(x=>x.Position)).size;const years=active.map(x=>new Date(x.AppointedDate).getFullYear()).filter(Boolean);const tenure=years.length?`${Math.min(...years)} – ${Math.max(new Date().getFullYear(),...years)}`:'Not set';
 function closeAdd(){setAddOpen(false);setSelected(null);setPosition('');setDepartment('');setAppointed(today());setTenureEnd('');setNotes('');setPicker(null)}
 function confirmRemove(item:Exco){Alert.alert('Remove Exco',`Remove ${item.FirstName} ${item.LastName} from the executive committee?`,[{text:'Cancel',style:'cancel'},{text:'Remove',style:'destructive',onPress:()=>remove.mutate(item)}])}
 if(addOpen&&picker){const available=(members.data||[]).filter(m=>!items.some(e=>e.UserId===m.UserId));return <Screen scroll contentStyle={s.form}><Header title={picker==='member'?'Select community member':'Select position'} right={<Pressable accessibilityRole="button" accessibilityLabel="Back to appointment form" onPress={()=>setPicker(null)} style={s.more}><Ionicons name="close" size={25} color={palette.text}/></Pressable>}/><Card style={s.list}>{picker==='member'?(members.isLoading?<Muted>Loading active members…</Muted>:available.length?available.map(m=><Choice key={m.UserId} label={`${m.FirstName} ${m.LastName}`} detail={m.Email} onPress={()=>{setSelected(m);setPicker(null)}} palette={palette}/>):<Muted>No eligible active members are available.</Muted>):positions.map(p=><Choice key={p} label={p} selected={position===p} onPress={()=>{setPosition(p);setPicker(null)}} palette={palette}/>)}</Card></Screen>}
 if(addOpen)return <><Screen scroll contentStyle={s.form}><Header title="Add Exco Member" subtitle="Appoint an existing community member" right={<Pressable accessibilityLabel="Close Add Exco" onPress={closeAdd} style={s.more}><Ionicons name="close" size={25} color={palette.text}/></Pressable>}/><Card style={[s.about,{backgroundColor:palette.primarySoft}]}><Ionicons name="shield-checkmark-outline" size={34} color={palette.primary}/><View style={s.person}><Text style={[s.aboutTitle,{color:palette.primary}]}>About Exco Members</Text><Muted>Appointments are linked to verified community membership and saved to the official directory.</Muted></View></Card><Text style={[s.section,{color:palette.text}]}>Member</Text><SelectField label="Community member" value={selected?`${selected.FirstName} ${selected.LastName}`:''} placeholder="Select an active member" icon="person-outline" onPress={()=>setPicker('member')} palette={palette}/><Text style={[s.section,{color:palette.text}]}>Exco Information</Text><SelectField label="Position / Role" value={position} placeholder="Select position" icon="briefcase-outline" onPress={()=>setPicker('position')} palette={palette}/><Input placeholder="Department / committee (optional)" value={department} onChangeText={setDepartment}/><DateField value={appointed} onChange={setAppointed} placeholder="Date appointed" maximumDate={new Date()}/><DateField value={tenureEnd} onChange={setTenureEnd} placeholder="Tenure end date (optional)" minimumDate={appointed?new Date(`${appointed}T00:00:00`):undefined}/><Text style={[s.section,{color:palette.text}]}>Additional Information</Text><Input placeholder="Notes (optional)" value={notes} onChangeText={v=>setNotes(v.slice(0,500))} multiline/><Muted style={s.count}>{notes.length}/500</Muted><Button title="Add Exco Member" icon="person-add-outline" loading={create.isPending} disabled={!selected||!position||!appointed||create.isPending} onPress={()=>create.mutate()}/><Button title="Cancel" variant="secondary" onPress={closeAdd}/></Screen><ChoiceModal visible={picker==='member'} title="Select community member" close={()=>setPicker(null)}>{members.isLoading?<Muted>Loading active members…</Muted>:(members.data||[]).filter(m=>!items.some(e=>e.UserId===m.UserId)).map(m=><Choice key={m.UserId} label={`${m.FirstName} ${m.LastName}`} detail={m.Email} onPress={()=>{setSelected(m);setPicker(null)}} palette={palette}/>)}</ChoiceModal><ChoiceModal visible={picker==='position'} title="Select position" close={()=>setPicker(null)}>{positions.map(p=><Choice key={p} label={p} selected={position===p} onPress={()=>{setPosition(p);setPicker(null)}} palette={palette}/>)}</ChoiceModal></>;
 return <Screen scroll contentStyle={s.page}><Header page title="Excos" subtitle="Executive committee members"/>
  <View style={[s.hero,{backgroundColor:palette.primaryDark}]}><View style={s.heroTop}><View style={s.heroIcon}><Ionicons name="people" size={31} color={palette.primary}/></View><View style={s.heroCopy}><View style={s.inline}><Text style={s.heroTitle}>Community leadership</Text><Badge text={active.length?'Active':'No Excos Yet'} tone={active.length?'green':'gray'}/></View><Text style={s.heroBody}>Official executive appointments for this community.</Text></View></View>
   <View style={s.stats}><Stat icon="people-outline" label="Total Excos" value={String(items.length)} palette={palette}/><Stat icon="shield-checkmark-outline" label="Roles" value={String(roles)} palette={palette}/><Stat icon="calendar-outline" label="Tenure" value={tenure} palette={palette}/><Stat icon="checkmark-circle-outline" label="Status" value={active.length?'Active':'None'} palette={palette}/></View>
  </View>
  <View style={s.tools}><View style={[s.search,{borderColor:palette.border,backgroundColor:palette.surface}]}><Ionicons name="search-outline" size={20} color={palette.muted}/><Input placeholder="Search Exco members" value={search} onChangeText={setSearch} style={s.searchInput}/></View><Pressable onPress={()=>setStatus(status==='ALL'?'ACTIVE':status==='ACTIVE'?'INACTIVE':'ALL')} style={[s.filter,{borderColor:palette.border,backgroundColor:palette.surface}]}><Ionicons name="options-outline" size={19} color={palette.primary}/><Text style={{color:palette.text,fontWeight:'800'}}>{status==='ALL'?'Filter':status==='ACTIVE'?'Active':'Inactive'}</Text></Pressable></View>
  <Text style={[s.listTitle,{color:palette.text}]}>Exco Members ({visible.length})</Text>
  {query.isLoading?<Muted>Loading executive committee…</Muted>:query.isError?<EmptyState icon="cloud-offline-outline" title="Could not load Excos" body="Check that the Exco database update has been installed, then try again."/>:visible.length?<Card style={s.list}>{visible.map((item,i)=><View key={item.Id} style={[s.row,i<visible.length-1&&{borderBottomColor:palette.border,borderBottomWidth:1}]}><Avatar name={`${item.FirstName} ${item.LastName}`} uri={item.ProfileImage} size={50}/><View style={s.person}><View style={s.inline}><Text numberOfLines={1} style={[s.name,{color:palette.text}]}>{item.FirstName} {item.LastName}</Text>{item.Status==='ACTIVE'?<Ionicons name="shield-checkmark" size={17} color={palette.success}/>:null}</View><Muted numberOfLines={1}>{item.Email}</Muted>{item.Department?<Muted numberOfLines={1}>{item.Department}</Muted>:null}</View><View style={[s.role,{backgroundColor:item.Status==='ACTIVE'?palette.primarySoft:palette.backgroundSoft}]}><Text numberOfLines={2} style={{color:item.Status==='ACTIVE'?palette.primary:palette.muted,fontSize:11,fontWeight:'900',textAlign:'center'}}>{item.Position}</Text></View>{query.data?.canManage?<Pressable accessibilityLabel={`Actions for ${item.FirstName}`} onPress={()=>setAction(item)} style={s.more}><Ionicons name="ellipsis-vertical" size={21} color={palette.text}/></Pressable>:null}</View>)}</Card>:<EmptyState icon="people-outline" title={search||status!=='ALL'?'No matching Excos':'No Excos added'} body={query.data?.canManage?'Use Add Exco to appoint an active community member.':'Executive committee appointments will appear here.'}/>} 
  <Modal visible={addOpen} animationType="slide" presentationStyle="pageSheet" onRequestClose={closeAdd}><Screen scroll contentStyle={s.form}><Header title="Add Exco Member" subtitle="Appoint an existing community member" right={<Pressable accessibilityLabel="Close" onPress={closeAdd} style={s.more}><Ionicons name="close" size={25} color={palette.text}/></Pressable>}/><Card style={[s.about,{backgroundColor:palette.primarySoft}]}><Ionicons name="shield-checkmark-outline" size={34} color={palette.primary}/><View style={s.person}><Text style={[s.aboutTitle,{color:palette.primary}]}>About Exco Members</Text><Muted>Appointments are linked to verified community membership and saved to the official directory.</Muted></View></Card>
   <Text style={[s.section,{color:palette.text}]}>Member</Text><SelectField label="Community member" value={selected?`${selected.FirstName} ${selected.LastName}`:''} placeholder="Select an active member" icon="person-outline" onPress={()=>setPicker('member')} palette={palette}/>
   <Text style={[s.section,{color:palette.text}]}>Exco Information</Text><SelectField label="Position / Role" value={position} placeholder="Select position" icon="briefcase-outline" onPress={()=>setPicker('position')} palette={palette}/><Input placeholder="Department / committee (optional)" value={department} onChangeText={setDepartment}/><DateField value={appointed} onChange={setAppointed} placeholder="Date appointed" maximumDate={new Date()}/><DateField value={tenureEnd} onChange={setTenureEnd} placeholder="Tenure end date (optional)" minimumDate={appointed?new Date(`${appointed}T00:00:00`):undefined}/>
   <Text style={[s.section,{color:palette.text}]}>Additional Information</Text><Input placeholder="Notes (optional)" value={notes} onChangeText={v=>setNotes(v.slice(0,500))} multiline/><Muted style={s.count}>{notes.length}/500</Muted><Button title="Add Exco Member" icon="person-add-outline" loading={create.isPending} disabled={!selected||!position||!appointed} onPress={()=>create.mutate()}/><Button title="Cancel" variant="secondary" onPress={closeAdd}/>
  </Screen></Modal>
  <ChoiceModal visible={picker==='member'} title="Select community member" close={()=>setPicker(null)}>{(members.data||[]).filter(m=>!items.some(e=>e.UserId===m.UserId)).map(m=><Choice key={m.UserId} label={`${m.FirstName} ${m.LastName}`} detail={m.Email} onPress={()=>{setSelected(m);setPicker(null)}} palette={palette}/>)}</ChoiceModal>
  <ChoiceModal visible={picker==='position'} title="Select position" close={()=>setPicker(null)}>{positions.map(p=><Choice key={p} label={p} selected={position===p} onPress={()=>{setPosition(p);setPicker(null)}} palette={palette}/>)}</ChoiceModal>
  <Modal visible={!!action} transparent animationType="fade" onRequestClose={()=>setAction(null)}><Pressable style={s.backdrop} onPress={()=>setAction(null)}><View style={[s.actionModal,{backgroundColor:palette.surface}]}><Text style={[s.actionTitle,{color:palette.text}]}>{action?.FirstName} {action?.LastName}</Text><Muted>{action?.Position}</Muted><Button title={action?.Status==='ACTIVE'?'Mark Inactive':'Restore as Active'} variant="secondary" loading={update.isPending} onPress={()=>action&&update.mutate({item:action,status:action.Status==='ACTIVE'?'INACTIVE':'ACTIVE'})}/><Button title="Remove Exco" variant="danger" loading={remove.isPending} onPress={()=>action&&confirmRemove(action)}/><Button title="Cancel" variant="ghost" onPress={()=>setAction(null)}/></View></Pressable></Modal>
 </Screen>
}
function Stat({icon,label,value,palette}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:string;palette:any}){return <View style={s.stat}><Ionicons name={icon} size={20} color={palette.primary}/><Text numberOfLines={1} adjustsFontSizeToFit style={s.statValue}>{value}</Text><Text numberOfLines={1} style={s.statLabel}>{label}</Text></View>}
function SelectField({label,value,placeholder,icon,onPress,palette}:{label:string;value:string;placeholder:string;icon:keyof typeof Ionicons.glyphMap;onPress:()=>void;palette:any}){return <View><Text style={[s.fieldLabel,{color:palette.text}]}>{label}</Text><Pressable accessibilityRole="button" accessibilityLabel={`${label}: ${value||placeholder}`} hitSlop={4} onPress={onPress} style={({pressed})=>[s.select,{borderColor:palette.border,backgroundColor:palette.surface},pressed&&{opacity:.72}]}><Ionicons name={icon} size={21} color={palette.primary}/><Text numberOfLines={1} style={{flex:1,color:value?palette.text:palette.muted,fontSize:15,fontWeight:'600'}}>{value||placeholder}</Text><Ionicons name="chevron-forward" size={19} color={palette.muted}/></Pressable></View>}
function ChoiceModal({visible,title,close,children}:{visible:boolean;title:string;close:()=>void;children:any}){const{palette}=useAppTheme();return <Modal visible={visible} transparent animationType="fade" onRequestClose={close}><View style={s.backdrop}><View style={[s.choiceModal,{backgroundColor:palette.surface}]}><View style={s.choiceHead}><Text style={[s.actionTitle,{color:palette.text}]}>{title}</Text><Pressable onPress={close} style={s.more}><Ionicons name="close" size={24} color={palette.text}/></Pressable></View><ScrollView showsVerticalScrollIndicator={false}>{children}</ScrollView></View></View></Modal>}
function Choice({label,detail,selected,onPress,palette}:{label:string;detail?:string;selected?:boolean;onPress:()=>void;palette:any}){return <Pressable onPress={onPress} style={[s.choice,{borderBottomColor:palette.border}]}><View style={s.person}><Text style={{color:palette.text,fontWeight:'800'}}>{label}</Text>{detail?<Muted numberOfLines={1}>{detail}</Muted>:null}</View>{selected?<Ionicons name="checkmark-circle" size={21} color={palette.primary}/>:null}</Pressable>}
const s=StyleSheet.create({page:{paddingBottom:95},hero:{borderRadius:18,padding:14,marginBottom:15},heroTop:{flexDirection:'row',alignItems:'center',gap:10},heroIcon:{width:54,height:54,borderRadius:27,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},heroCopy:{flex:1,minWidth:0},heroTitle:{color:'#fff',fontSize:16,fontWeight:'900'},heroBody:{color:'#D9FBE7',fontSize:12,lineHeight:17,marginTop:4},inline:{flexDirection:'row',alignItems:'center',gap:6,minWidth:0},add:{minHeight:44,borderRadius:13,paddingHorizontal:13,backgroundColor:'rgba(255,255,255,.15)',borderWidth:1,borderColor:'rgba(255,255,255,.22)',flexDirection:'row',alignItems:'center',gap:6},addText:{color:'#fff',fontWeight:'900'},stats:{marginTop:14,backgroundColor:'#fff',borderRadius:14,flexDirection:'row',paddingVertical:12},stat:{width:'25%',alignItems:'center',paddingHorizontal:4,borderRightWidth:1,borderRightColor:'#E7ECF3'},statValue:{color:'#0F1F44',fontSize:16,fontWeight:'900',marginTop:4},statLabel:{color:'#64748B',fontSize:9,fontWeight:'700',marginTop:2},tools:{flexDirection:'row',gap:8,marginBottom:14},search:{flex:1,minWidth:0,height:52,borderWidth:1,borderRadius:13,flexDirection:'row',alignItems:'center',paddingLeft:12},searchInput:{flex:1,marginBottom:0,borderWidth:0,backgroundColor:'transparent'},filter:{height:52,borderWidth:1,borderRadius:13,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:6},listTitle:{fontSize:16,fontWeight:'900',marginBottom:9},list:{padding:0,overflow:'hidden'},row:{minHeight:78,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:11,paddingVertical:9},person:{flex:1,minWidth:0},name:{fontSize:14,fontWeight:'900',flexShrink:1},role:{maxWidth:105,minWidth:70,minHeight:34,borderRadius:9,paddingHorizontal:7,alignItems:'center',justifyContent:'center'},more:{width:42,height:42,alignItems:'center',justifyContent:'center'},form:{paddingBottom:30,maxWidth:720},about:{flexDirection:'row',alignItems:'center',gap:13},aboutTitle:{fontSize:16,fontWeight:'900',marginBottom:3},section:{fontSize:17,fontWeight:'900',marginTop:14,marginBottom:10},fieldLabel:{fontSize:13,fontWeight:'900',marginBottom:7},select:{minHeight:54,borderWidth:1.5,borderRadius:13,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:9,marginBottom:12},count:{textAlign:'right',marginTop:-9,marginBottom:9},backdrop:{flex:1,backgroundColor:'rgba(15,31,68,.4)',alignItems:'center',justifyContent:'center',padding:18},choiceModal:{width:'100%',maxWidth:440,maxHeight:'84%',borderRadius:20,padding:16},choiceHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:8},choice:{minHeight:58,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:4},actionModal:{width:'100%',maxWidth:390,borderRadius:20,padding:18},actionTitle:{fontSize:19,fontWeight:'900',marginBottom:3}});
