import { useEffect, useMemo, useState } from 'react';
import { Alert, Image, Linking, Modal, Pressable, Share, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import * as DocumentPicker from 'expo-document-picker';
import * as Speech from 'expo-speech';
import { AudioModule, RecordingPresets, setAudioModeAsync, useAudioPlayer, useAudioRecorder, useAudioRecorderState } from 'expo-audio';
import { useVideoPlayer, VideoView } from 'expo-video';
import { api } from '@/lib/api';
import { Avatar, Badge, Button, Card, EmptyState, Input, Muted, Screen, useAppTheme } from '@/components/UI';
import { colors } from '@/theme';
import { useAccessibility } from '@/store/accessibility';

const POST_TYPES=[['TEXT','Text','create-outline'],['PHOTO','Photo','image-outline'],['VIDEO','Video','videocam-outline'],['DOCUMENT','Document','document-outline'],['VOICE','Voice','mic-outline'],['POLL','Poll','stats-chart-outline'],['EVENT','Event','calendar-outline'],['LOST_FOUND','Lost & found','search-outline'],['RECOMMENDATION','Recommend','thumbs-up-outline'],['QUESTION','Question','help-circle-outline'],['ALERT','Alert','warning-outline'],['LOCAL_NEWS','Local news','newspaper-outline']] as const;
type PostType=typeof POST_TYPES[number][0]; type Reaction='LIKE'|'CELEBRATE'|'SUPPORT';
interface Post {Id:string;CreatedBy:string;Body:string;PostType:PostType;MediaUrl?:string;MediaType?:string;DocumentName?:string;Caption?:string;Transcript?:string;OriginalLanguage?:string;IsPinned:boolean;IsAnnouncement:boolean;CreatedAt:string;FirstName:string;LastName:string;ReactionCount:number;LikeCount:number;CelebrateCount:number;SupportCount:number;CommentCount:number;ShareCount:number;MyReaction?:Reaction;MySaved:boolean;Hashtags:string[]}
interface Comment {Id:string;Body:string;ParentCommentId?:string;CreatedAt:string;FirstName:string;LastName:string;ProfileImage?:string}

async function uploadFile(uri:string,name:string,type:string){const fd=new FormData();fd.append('file',{uri,name,type} as any);return (await api.post('/media/upload',fd,{headers:{'Content-Type':'multipart/form-data'}})).data as {url:string;name:string;mimeType:string};}
function VideoMedia({uri,caption}:{uri:string;caption?:string}){const player=useVideoPlayer(uri,p=>{p.loop=false});return <View><VideoView player={player} style={st.video} nativeControls contentFit="cover" accessibilityLabel={caption||'Community video'}/>{caption?<Muted style={st.caption}>{caption}</Muted>:null}</View>}
function AudioMedia({uri,transcript}:{uri:string;transcript?:string}){const player=useAudioPlayer(uri);return <View style={st.audio}><Pressable accessibilityRole="button" accessibilityLabel="Play voice note" onPress={()=>player.play()} style={st.audioButton}><Ionicons name="play" size={20} color="#fff"/></Pressable><View style={{flex:1}}><Text style={st.audioTitle}>Voice note</Text>{transcript?<Muted>{transcript}</Muted>:<Muted>Transcript not available</Muted>}</View></View>}
function AccessibleBody({post}:{post:Post}){const a=useAccessibility();const [shown,setShown]=useState(post.Body);const [working,setWorking]=useState(false);const canTransform=(a.autoTranslate&&a.language!=='en')||(a.simpleLanguage&&post.IsAnnouncement);useEffect(()=>{let active=true;if(!canTransform){setShown(post.Body);return;}setWorking(true);const mode=a.simpleLanguage&&post.IsAnnouncement?'simple':'translate';api.post(`/content/post/${post.Id}/transform`,{mode,language:a.language}).then(r=>{if(active)setShown(r.data.text||post.Body)}).catch(()=>{if(active)setShown(post.Body)}).finally(()=>active&&setWorking(false));return()=>{active=false}},[post.Id,post.Body,post.IsAnnouncement,a.autoTranslate,a.simpleLanguage,a.language]);return <View><Text allowFontScaling style={st.body}>{shown}</Text>{working?<Muted>Preparing accessible version…</Muted>:null}</View>}

export default function FeedScreen(){
 const {id}=useLocalSearchParams<{id:string}>();const qc=useQueryClient();const {palette,prefs}=useAppTheme();const a=useAccessibility();
 const [body,setBody]=useState('');const [postType,setPostType]=useState<PostType>('TEXT');const [media,setMedia]=useState<{uri:string;url?:string;name:string;type:string}|null>(null);const [caption,setCaption]=useState('');const [transcript,setTranscript]=useState('');const [announcement,setAnnouncement]=useState(false);const [selected,setSelected]=useState<Post|null>(null);const [comment,setComment]=useState('');const [replyTo,setReplyTo]=useState<Comment|null>(null);
 const recorder=useAudioRecorder(RecordingPresets.HIGH_QUALITY);const recorderState=useAudioRecorderState(recorder);
 const posts=useQuery<Post[]>({queryKey:['feed',id],queryFn:async()=>(await api.get(`/communities/${id}/feed`)).data});const comments=useQuery<Comment[]>({queryKey:['post-comments',selected?.Id],enabled:!!selected,queryFn:async()=>(await api.get(`/posts/${selected!.Id}/comments`)).data});
 useEffect(()=>{AudioModule.requestRecordingPermissionsAsync().then(x=>{if(x.granted)setAudioModeAsync({playsInSilentMode:true,allowsRecording:true})})},[]);
 const create=useMutation({mutationFn:async()=>{let uploaded=media;if(media&&!media.url){const u=await uploadFile(media.uri,media.name,media.type);uploaded={...media,url:u.url,type:u.mimeType};}return api.post(`/communities/${id}/feed`,{body,postType,mediaUrl:uploaded?.url,mediaType:uploaded?.type,documentName:postType==='DOCUMENT'?uploaded?.name:undefined,caption:caption||undefined,transcript:transcript||undefined,originalLanguage:a.language,isAnnouncement:announcement});},onSuccess:()=>{setBody('');setMedia(null);setCaption('');setTranscript('');setPostType('TEXT');setAnnouncement(false);qc.invalidateQueries({queryKey:['feed',id]});},onError:(e:any)=>Alert.alert('Unable to post',e.response?.data?.message||'Please try again.')});
 const react=useMutation({mutationFn:async({postId,reaction}:{postId:string;reaction:Reaction|null})=>api.post(`/posts/${postId}/reaction`,{reaction}),onSuccess:()=>qc.invalidateQueries({queryKey:['feed',id]})});const save=useMutation({mutationFn:async(postId:string)=>api.post(`/posts/${postId}/save`),onSuccess:()=>qc.invalidateQueries({queryKey:['feed',id]})});
 const addComment=useMutation({mutationFn:async()=>api.post(`/posts/${selected!.Id}/comments`,{body:comment,parentCommentId:replyTo?.Id}),onSuccess:()=>{setComment('');setReplyTo(null);qc.invalidateQueries({queryKey:['post-comments',selected?.Id]});qc.invalidateQueries({queryKey:['feed',id]});}});
 const remove=useMutation({mutationFn:async(postId:string)=>api.delete(`/communities/${id}/posts/${postId}`),onSuccess:()=>qc.invalidateQueries({queryKey:['feed',id]}),onError:(e:any)=>Alert.alert('Unable to delete',e.response?.data?.message||'Admin or moderator permission is required.')});
 const moderate=useMutation({mutationFn:async({postId,isPinned}:{postId:string;isPinned:boolean})=>api.patch(`/communities/${id}/posts/${postId}/moderation`,{isPinned}),onSuccess:()=>qc.invalidateQueries({queryKey:['feed',id]}),onError:(e:any)=>Alert.alert('Admin action',e.response?.data?.message||'Admin or moderator permission is required.')});
 const feed=useMemo(()=>posts.data||[],[posts.data]);
 const pickMedia=async(kind:'PHOTO'|'VIDEO'|'DOCUMENT')=>{if(kind==='DOCUMENT'){const r=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true,multiple:false});if(!r.canceled){const x=r.assets[0];setPostType('DOCUMENT');setMedia({uri:x.uri,name:x.name,type:x.mimeType||'application/octet-stream'});}return;}const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:[kind==='PHOTO'?'images':'videos'],quality:.85});if(!r.canceled){const x=r.assets[0];setPostType(kind);setMedia({uri:x.uri,name:x.fileName||`${kind.toLowerCase()}-${Date.now()}`,type:x.mimeType||(kind==='PHOTO'?'image/jpeg':'video/mp4')});}};
 const toggleRecording=async()=>{if(recorderState.isRecording){await recorder.stop();const uri=recorder.uri;if(uri){setPostType('VOICE');setMedia({uri,name:`voice-${Date.now()}.m4a`,type:'audio/m4a'});if(a.autoTranscripts){try{const fd=new FormData();fd.append('file',{uri,name:'voice.m4a',type:'audio/m4a'} as any);const r=await api.post('/media/transcribe',fd,{headers:{'Content-Type':'multipart/form-data'}});setTranscript(r.data.transcript||'');}catch{Alert.alert('Transcript unavailable','The voice note is saved, but automatic transcription needs a configured transcription provider.')}}}}else{await recorder.prepareToRecordAsync();recorder.record();}};
 const sharePost=async(p:Post)=>{await api.post(`/posts/${p.Id}/share`);await Share.share({message:`${p.FirstName} ${p.LastName} on CDA Connect:\n\n${p.Body}`});qc.invalidateQueries({queryKey:['feed',id]});};
 const reportPost=(p:Post)=>Alert.alert('Report post','Why are you reporting this?',[{text:'Spam',onPress:()=>api.post(`/posts/${p.Id}/report`,{reason:'Spam'})},{text:'Harassment',onPress:()=>api.post(`/posts/${p.Id}/report`,{reason:'Harassment'})},{text:'False or harmful information',onPress:()=>api.post(`/posts/${p.Id}/report`,{reason:'False or harmful information'})},{text:'Cancel',style:'cancel'}]);
 const options=(p:Post)=>Alert.alert('Post options','Choose an action',[{text:p.MySaved?'Remove from saved':'Save post',onPress:()=>save.mutate(p.Id)},{text:p.IsPinned?'Unpin post':'Pin post',onPress:()=>moderate.mutate({postId:p.Id,isPinned:!p.IsPinned})},{text:'Report post',onPress:()=>reportPost(p)},{text:'Delete post',style:'destructive',onPress:()=>remove.mutate(p.Id)},{text:'Cancel',style:'cancel'}]);
 return <Screen scroll><View style={st.header}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>(router.canGoBack()?router.back():router.replace('/'))} style={st.touch}><Ionicons name="chevron-back" size={24} color={palette.text}/></Pressable><View style={{flex:1}}><Text accessibilityRole="header" style={[st.title,{color:palette.text}]}>News Feed</Text><Muted>Useful updates from your CDA</Muted></View><Ionicons name="newspaper-outline" size={24} color={palette.primary}/></View>
 <Card><View style={st.composerRow}><Avatar name="You" size={42}/><Input value={body} onChangeText={setBody} placeholder="Share an update, ask a question, mention @someone or add #topic…" multiline style={st.postInput}/></View><View style={st.typeWrap}>{POST_TYPES.map(([value,label,icon])=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:postType===value}} onPress={()=>{setPostType(value);if(value==='PHOTO'||value==='VIDEO')pickMedia(value);if(value==='DOCUMENT')pickMedia('DOCUMENT')}} style={[st.typeChip,{borderColor:palette.border,backgroundColor:postType===value?palette.primarySoft:palette.surface,minHeight:prefs.largeTouchTargets?44:36}]}><Ionicons name={icon as any} size={16} color={postType===value?palette.primary:palette.muted}/><Text style={{color:postType===value?palette.primary:palette.text,fontSize:12,fontWeight:'700'}}>{label}</Text></Pressable>)}</View>
 <View style={st.utilityRow}><Pressable accessibilityRole="button" accessibilityLabel={recorderState.isRecording?'Stop voice recording':'Record voice note'} onPress={toggleRecording} style={st.smallAction}><Ionicons name={recorderState.isRecording?'stop-circle':'mic-outline'} size={20} color={recorderState.isRecording?palette.danger:palette.primary}/><Text style={{color:palette.text,fontSize:12}}>{recorderState.isRecording?'Stop recording':'Voice note'}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Mark as admin announcement" onPress={()=>setAnnouncement(v=>!v)} style={st.smallAction}><Ionicons name={announcement?'megaphone':'megaphone-outline'} size={20} color={announcement?palette.primary:palette.muted}/><Text style={{color:palette.text,fontSize:12}}>Admin announcement</Text></Pressable></View>
 {media?<Card style={{backgroundColor:palette.primarySoft}}><View style={st.mediaSelected}><Ionicons name={postType==='PHOTO'?'image':postType==='VIDEO'?'videocam':postType==='VOICE'?'mic':'document'} size={22} color={palette.primary}/><View style={{flex:1}}><Text numberOfLines={1} style={{color:palette.text,fontWeight:'800'}}>{media.name}</Text><Muted>{media.type}</Muted></View><Pressable accessibilityRole="button" accessibilityLabel="Remove attachment" onPress={()=>setMedia(null)} style={st.touch}><Ionicons name="close" size={20} color={palette.text}/></Pressable></View><Input value={caption} onChangeText={setCaption} placeholder="Add a caption or media description…"/>{postType==='VOICE'?<Input value={transcript} onChangeText={setTranscript} placeholder="Voice transcript (automatic when configured)…" multiline/>:null}</Card>:null}
 <Button title="Post to community" loading={create.isPending} disabled={!body.trim()&&!media} onPress={()=>create.mutate()} icon="send"/></Card>
 {posts.isLoading?<Muted>Loading feed…</Muted>:feed.length===0?<EmptyState icon="newspaper-outline" title="No posts yet" body="Be the first member to share something useful with this community."/>:feed.map(p=><Card key={p.Id}>{(p.IsPinned||p.IsAnnouncement)&&<View style={st.badges}>{p.IsPinned?<Badge text="Pinned"/>:null}{p.IsAnnouncement?<Badge text="Admin announcement" tone="orange"/>:null}</View>}<View style={st.postHeader}><Avatar name={`${p.FirstName} ${p.LastName}`} size={44}/><View style={{flex:1}}><Text style={[st.author,{color:palette.text}]}>{p.FirstName} {p.LastName}</Text><View style={st.meta}><Muted>{new Date(p.CreatedAt).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}</Muted><Badge text={POST_TYPES.find(x=>x[0]===p.PostType)?.[1]||p.PostType} tone="gray"/></View></View><Pressable accessibilityRole="button" accessibilityLabel="Post options" onPress={()=>options(p)} style={st.touch}><Ionicons name="ellipsis-horizontal" size={22} color={palette.muted}/></Pressable></View>
 <AccessibleBody post={p}/>{p.Hashtags?.length?<View style={st.hashes}>{p.Hashtags.map(h=><Text key={h} style={{color:palette.primary,fontWeight:'700'}}>#{h}</Text>)}</View>:null}
 {p.MediaUrl&&p.PostType==='PHOTO'?<><Image source={{uri:p.MediaUrl}} style={st.media} accessibilityLabel={p.Caption||'Community photo'}/>{a.captionsEnabled&&p.Caption?<Muted style={st.caption}>{p.Caption}</Muted>:null}</>:null}{p.MediaUrl&&p.PostType==='VIDEO'?<VideoMedia uri={p.MediaUrl} caption={a.captionsEnabled?p.Caption:undefined}/>:null}{p.MediaUrl&&p.PostType==='VOICE'?<AudioMedia uri={p.MediaUrl} transcript={a.autoTranscripts?p.Transcript:undefined}/>:null}{p.MediaUrl&&p.PostType==='DOCUMENT'?<Pressable accessibilityRole="link" accessibilityLabel={`Open document ${p.DocumentName||''}`} onPress={()=>Linking.openURL(p.MediaUrl!)} style={[st.document,{borderColor:palette.border}]}><Ionicons name="document-text-outline" size={26} color={palette.primary}/><View style={{flex:1}}><Text style={{fontWeight:'800',color:palette.text}}>{p.DocumentName||'Community document'}</Text><Muted>{p.Caption||'Tap to open'}</Muted></View></Pressable>:null}
 {(p.IsAnnouncement||p.PostType==='ALERT')?<Pressable accessibilityRole="button" accessibilityLabel="Listen to this notice" onPress={()=>Speech.speak(p.Body,{language:a.language})} style={st.listen}><Ionicons name="volume-high-outline" size={18} color={palette.primary}/><Text style={{color:palette.primary,fontWeight:'800'}}>Listen</Text></Pressable>:null}
 <View style={[st.stats,{borderBottomColor:palette.border}]}><Text style={[st.stat,{color:palette.muted}]}>{p.ReactionCount} reactions · {p.CommentCount} comments · {p.ShareCount} shares</Text>{p.MySaved?<Ionicons name="bookmark" size={16} color={palette.primary}/>:null}</View>
 <View style={st.actions}><Pressable accessibilityRole="button" accessibilityLabel="React to post" style={st.action} onPress={()=>Alert.alert('React',undefined,[{text:'Like',onPress:()=>react.mutate({postId:p.Id,reaction:p.MyReaction==='LIKE'?null:'LIKE'})},{text:'Celebrate',onPress:()=>react.mutate({postId:p.Id,reaction:p.MyReaction==='CELEBRATE'?null:'CELEBRATE'})},{text:'Support',onPress:()=>react.mutate({postId:p.Id,reaction:p.MyReaction==='SUPPORT'?null:'SUPPORT'})},{text:'Cancel',style:'cancel'}])}><Ionicons name={p.MyReaction==='LIKE'?'heart':p.MyReaction==='CELEBRATE'?'sparkles':p.MyReaction==='SUPPORT'?'hand-left':'heart-outline'} size={21} color={p.MyReaction?palette.primary:palette.muted}/><Text style={{color:p.MyReaction?palette.primary:palette.muted,fontWeight:'700'}}>{p.MyReaction?({LIKE:'Like',CELEBRATE:'Celebrate',SUPPORT:'Support'} as any)[p.MyReaction]:'React'}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Comment" style={st.action} onPress={()=>setSelected(p)}><Ionicons name="chatbubble-outline" size={20} color={palette.muted}/><Text style={{color:palette.muted,fontWeight:'700'}}>Comment</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Share post" style={st.action} onPress={()=>sharePost(p)}><Ionicons name="share-social-outline" size={20} color={palette.muted}/><Text style={{color:palette.muted,fontWeight:'700'}}>Share</Text></Pressable></View></Card>)}
 <Modal visible={!!selected} animationType={a.reducedMotion?'none':'slide'} presentationStyle="pageSheet" onRequestClose={()=>setSelected(null)}><Screen scroll><View style={st.header}><Pressable accessibilityRole="button" accessibilityLabel="Close comments" onPress={()=>setSelected(null)} style={st.touch}><Ionicons name="close" size={26} color={palette.text}/></Pressable><Text style={[st.title,{color:palette.text}]}>Comments</Text><View style={{width:44}}/></View>{selected?<Card><Text style={[st.author,{color:palette.text}]}>{selected.FirstName} {selected.LastName}</Text><AccessibleBody post={selected}/></Card>:null}{replyTo?<View style={[st.replying,{backgroundColor:palette.primarySoft}]}><Text style={{color:palette.text,flex:1}}>Replying to {replyTo.FirstName}</Text><Pressable onPress={()=>setReplyTo(null)}><Ionicons name="close" size={18} color={palette.text}/></Pressable></View>:null}<Input value={comment} onChangeText={setComment} placeholder="Write a comment or @mention someone…" multiline/><Button title={replyTo?'Reply':'Comment'} disabled={!comment.trim()} loading={addComment.isPending} onPress={()=>addComment.mutate()}/>{comments.data?.map(c=><View key={c.Id} style={[st.comment,c.ParentCommentId&&{marginLeft:42}]}><Avatar name={`${c.FirstName} ${c.LastName}`} size={36}/><Pressable accessibilityRole="button" accessibilityLabel={`Reply to ${c.FirstName}`} onPress={()=>setReplyTo(c)} style={[st.commentBubble,{backgroundColor:palette.primarySoft}]}><Text style={[st.commentAuthor,{color:palette.text}]}>{c.FirstName} {c.LastName}</Text><Text style={[st.commentBody,{color:palette.text}]}>{c.Body}</Text><Muted>{new Date(c.CreatedAt).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})} · Reply</Muted></Pressable></View>)}</Screen></Modal>
 </Screen>
}
const st=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:16},touch:{minWidth:44,minHeight:44,alignItems:'center',justifyContent:'center'},title:{fontSize:22,fontWeight:'900'},composerRow:{flexDirection:'row',gap:10,alignItems:'flex-start'},postInput:{flex:1,minHeight:82,marginBottom:0},typeWrap:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:12},typeChip:{flexDirection:'row',alignItems:'center',gap:5,borderWidth:1,borderRadius:999,paddingHorizontal:10,justifyContent:'center'},utilityRow:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:12},smallAction:{flexDirection:'row',alignItems:'center',gap:6,minHeight:44},mediaSelected:{flexDirection:'row',alignItems:'center',gap:10},postHeader:{flexDirection:'row',alignItems:'center',gap:10},author:{fontSize:14,fontWeight:'900'},meta:{flexDirection:'row',gap:7,alignItems:'center',flexWrap:'wrap'},body:{fontSize:15,lineHeight:23,marginTop:14},media:{width:'100%',height:240,borderRadius:14,marginTop:12},video:{width:'100%',height:240,borderRadius:14,marginTop:12},caption:{marginTop:6},audio:{flexDirection:'row',gap:10,alignItems:'center',paddingVertical:12},audioButton:{width:44,height:44,borderRadius:22,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},audioTitle:{fontWeight:'900'},document:{marginTop:12,borderWidth:1,borderRadius:14,padding:12,flexDirection:'row',alignItems:'center',gap:10},listen:{flexDirection:'row',alignItems:'center',gap:6,minHeight:44,marginTop:6},stats:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingVertical:12,borderBottomWidth:1},stat:{fontSize:12},actions:{flexDirection:'row',paddingTop:8},action:{flex:1,minHeight:48,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:6},badges:{flexDirection:'row',gap:6,marginBottom:10},hashes:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:8},comment:{flexDirection:'row',gap:9,marginBottom:14},commentBubble:{flex:1,borderRadius:15,padding:11},commentAuthor:{fontSize:13,fontWeight:'900'},commentBody:{fontSize:14,marginVertical:4},replying:{flexDirection:'row',alignItems:'center',padding:10,borderRadius:12,marginBottom:8}})
