import { useState } from 'react';
import { Alert,Image,Platform,Pressable,StyleSheet,Text,View } from '@/platform/react-native';
import { useLocalSearchParams } from '@/router';
import { useMutation,useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@/platform/icons';
import * as ImagePicker from '@/platform/image-picker';import * as DocumentPicker from '@/platform/document-picker';
import { api } from '@/lib/api';import { Button,Card,Input,Muted,Screen,useAppTheme } from '@/components/UI';
const categories=[['Inappropriate Content','chatbubbles-outline','#0F8A43'],['Harassment or Bullying','person-remove-outline','#F58413'],['Spam or Scams','mail-outline','#7C3AED'],['Fake Profile','person-circle-outline','#1683E8'],['Violence or Threats','shield-outline','#E31B23'],['Hate Speech','megaphone-outline','#1683E8'],['Privacy Violation','lock-closed-outline','#0F8A43'],['Other','ellipsis-horizontal-circle-outline','#64748B']] as const;
type Attachment={uri:string;name:string;type:string;kind:string};
async function upload(a:Attachment){const fd=new FormData();if(Platform.OS==='web'){const blob=await(await fetch(a.uri)).blob();fd.append('file',blob,a.name)}else fd.append('file',{uri:a.uri,name:a.name,type:a.type} as any);return (await api.post('/media/upload',fd,{headers:{'Content-Type':'multipart/form-data'}})).data.url as string}
export default function ReportIssue(){const{id}=useLocalSearchParams<{id:string}>();const{palette}=useAppTheme();const qc=useQueryClient();const[category,setCategory]=useState<string>('Inappropriate Content'),[otherCategory,setOtherCategory]=useState(''),[place,setPlace]=useState(''),[description,setDescription]=useState(''),[involved,setInvolved]=useState(''),[extra,setExtra]=useState(''),[attachment,setAttachment]=useState<Attachment|null>(null);
 const submit=useMutation({mutationFn:async()=>{const evidence=attachment?await upload(attachment):undefined;const submittedCategory=category==='Other'?otherCategory.trim():category;const detail=[description.trim(),involved.trim()?`Person involved: ${involved.trim()}`:'',extra.trim()?`Additional details: ${extra.trim()}`:''].filter(Boolean).join('\n\n');return api.post(`/communities/${id}/issues`,{category:submittedCategory,title:`${submittedCategory} report`,description:detail,photoUrl:evidence,approximateLocation:place})},onSuccess:()=>{qc.invalidateQueries({queryKey:['issues',id]});setOtherCategory('');setPlace('');setDescription('');setInvolved('');setExtra('');setAttachment(null);Alert.alert('Report submitted','Your confidential report has been sent to authorised community administrators for action.')},onError:(e:any)=>Alert.alert('Unable to submit report',e.response?.data?.message||e.message)});
 async function pick(kind:'photo'|'video'|'document'){if(kind==='document'){const r=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true,multiple:false});if(!r.canceled){const x=r.assets[0];setAttachment({uri:x.uri,name:x.name,type:x.mimeType||'application/octet-stream',kind})}return}const mediaTypes=kind==='video'?['videos'] as ImagePicker.MediaType[]:['images'] as ImagePicker.MediaType[];const r=await ImagePicker.launchImageLibraryAsync({mediaTypes,quality:.82});if(!r.canceled){const x=r.assets[0];setAttachment({uri:x.uri,name:x.fileName||`issue-${kind}-${Date.now()}`,type:x.mimeType||(kind==='video'?'video/mp4':'image/jpeg'),kind})}}
 return <Screen scroll contentStyle={s.page}>
 <View style={[s.hero,{backgroundColor:palette.primarySoft,borderColor:palette.primaryLight}]}><View style={[s.heroIcon,{backgroundColor:palette.successSoft}]}><Ionicons name="shield-checkmark-outline" size={48} color={palette.primary}/></View><View style={{flex:1}}><Text style={[s.heroTitle,{color:palette.primaryDark}]}>Help us keep our community safe</Text><Muted>Report issues, inappropriate behaviour or problems so authorised administrators can take action.</Muted></View></View>
 <Text style={[s.sectionTitle,{color:palette.text}]}>What’s the issue about?</Text><View style={s.categoryGrid}>{categories.map(([label,icon,color])=><Pressable key={label} onPress={()=>setCategory(label)} style={[s.category,{borderColor:category===label?palette.primary:palette.border,backgroundColor:category===label?palette.primarySoft:palette.surface}]}><Ionicons name={icon} size={27} color={color}/><Text style={[s.categoryText,{color:palette.text}]}>{label}</Text>{category===label?<View style={[s.check,{backgroundColor:palette.primary}]}><Ionicons name="checkmark" size={14} color="#fff"/></View>:null}</Pressable>)}</View>{category==='Other'?<Input value={otherCategory} onChangeText={setOtherCategory} placeholder="Enter the type of issue" autoFocus style={s.otherInput}/>:null}
 <Text style={[s.sectionTitle,{color:palette.text}]}>Where did this happen?</Text><Input value={place} onChangeText={setPlace} placeholder="Enter the location where the issue occurred"/><Text style={[s.sectionTitle,{color:palette.text}]}>Describe the issue</Text><Input multiline value={description} onChangeText={x=>setDescription(x.slice(0,1000))} placeholder="Please provide as much detail as possible…" style={s.largeInput}/><Muted style={s.count}>{description.length}/1000</Muted>
 <Text style={[s.sectionTitle,{color:palette.text}]}>Add evidence <Muted>(optional)</Muted></Text><Muted>Photos, videos or documents can help administrators investigate.</Muted><View style={s.evidence}>{([['photo','image-outline','Photo'],['video','videocam-outline','Video'],['document','document-text-outline','Document']] as const).map(([kind,icon,label])=><Pressable key={kind} onPress={()=>pick(kind)} style={[s.evidenceButton,{borderColor:attachment?.kind===kind?palette.primary:palette.border,backgroundColor:palette.surface}]}><Ionicons name={icon} size={27} color={palette.primary}/><Text style={[s.evidenceText,{color:palette.text}]}>{label}</Text></Pressable>)}</View>{attachment?<Card style={s.attachment}>{attachment.type.startsWith('image/')?<Image source={{uri:attachment.uri}} style={s.preview}/>:<Ionicons name={attachment.kind==='video'?'videocam':'document-text'} size={34} color={palette.primary}/>}<View style={{flex:1}}><Text numberOfLines={1} style={{color:palette.text,fontWeight:'800'}}>{attachment.name}</Text><Muted>Ready to upload securely</Muted></View><Pressable onPress={()=>setAttachment(null)} style={s.touch}><Ionicons name="close" size={22} color={palette.text}/></Pressable></Card>:null}
 <Text style={[s.sectionTitle,{color:palette.text}]}>Who is involved? <Muted>(optional)</Muted></Text><Input value={involved} onChangeText={setInvolved} placeholder="Enter a member name or identifying information"/><Text style={[s.sectionTitle,{color:palette.text}]}>Additional details <Muted>(optional)</Muted></Text><Input multiline value={extra} onChangeText={x=>setExtra(x.slice(0,500))} placeholder="Anything else you’d like to add?" style={s.mediumInput}/><Muted style={s.count}>{extra.length}/500</Muted><View style={[s.confidential,{backgroundColor:palette.primarySoft}]}><Ionicons name="lock-closed" size={36} color={palette.primary}/><View style={{flex:1}}><Text style={{fontWeight:'900',color:palette.primaryDark}}>Your report is confidential</Text><Muted>Only authorised community administrators and you can view this report.</Muted></View></View><Button title="Submit Report" icon="send" loading={submit.isPending} disabled={!place.trim()||description.trim().length<3||(category==='Other'&&!otherCategory.trim())} onPress={()=>submit.mutate()}/></Screen>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:820,alignSelf:'center',paddingTop:10,paddingHorizontal:14,paddingBottom:125},touch:{width:44,height:44,alignItems:'center',justifyContent:'center'},hero:{borderWidth:1,borderRadius:18,padding:16,flexDirection:'row',gap:14,alignItems:'center',marginBottom:10},heroIcon:{width:72,height:72,borderRadius:36,alignItems:'center',justifyContent:'center'},heroTitle:{fontSize:18,fontWeight:'900',marginBottom:5},sectionTitle:{fontSize:17,fontWeight:'900',marginTop:18,marginBottom:9},categoryGrid:{flexDirection:'row',flexWrap:'wrap',gap:6},category:{width:'23.5%',minHeight:92,borderWidth:1,borderRadius:13,alignItems:'center',justifyContent:'center',gap:5,paddingHorizontal:4,paddingVertical:7,position:'relative'},categoryText:{fontSize:9.5,fontWeight:'800',textAlign:'center'},check:{position:'absolute',right:4,top:4,width:19,height:19,borderRadius:10,alignItems:'center',justifyContent:'center'},otherInput:{marginTop:10,marginBottom:0},largeInput:{minHeight:120},mediumInput:{minHeight:96},count:{textAlign:'right',marginTop:-9},evidence:{flexDirection:'row',gap:8,marginTop:11},evidenceButton:{flex:1,minWidth:0,minHeight:82,borderWidth:1,borderRadius:14,alignItems:'center',justifyContent:'center',gap:6},evidenceText:{fontSize:11,fontWeight:'800'},attachment:{flexDirection:'row',alignItems:'center',gap:12},preview:{width:62,height:52,borderRadius:8},confidential:{flexDirection:'row',alignItems:'center',gap:13,borderRadius:16,padding:15,marginTop:16}})
