import {useMemo,useState} from 'react';
import {Alert,Image,Pressable,StyleSheet,Text,TextInput,View,useWindowDimensions} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {Badge,Button,EmptyState,Header,Muted,Screen,useAppTheme} from '@/components/UI';
import {formatAmount} from '@/lib/money';
type Listing={Id:string;SellerUserId:string;ListingType:string;Title:string;Description?:string;Price?:number;Currency:string;Area?:string;ImageUrl?:string;IsSaved?:boolean;SellerVerified?:boolean;FirstName:string;LastName:string;CreatedAt:string};
const categories=[['ALL','grid-outline','All'],['FOR_SALE','pricetag-outline','For Sale'],['FREE','gift-outline','Free'],['WANTED','search-outline','Wanted'],['SERVICES','construct-outline','Services'],['RENTALS','key-outline','Rentals'],['JOBS','briefcase-outline','Jobs']] as const;
export default function Marketplace(){
 const{id}=useLocalSearchParams<{id:string}>();const{palette}=useAppTheme();const{width}=useWindowDimensions();const qc=useQueryClient();const[category,setCategory]=useState('ALL');const[search,setSearch]=useState('');const[latest,setLatest]=useState(true);
 const capabilities=useQuery<any>({queryKey:['capabilities',id],queryFn:async()=>(await api.get(`/communities/${id}/capabilities`)).data});const canModerate=capabilities.data?.permissions?.includes('MARKETPLACE_MODERATE');
 const query=useQuery<Listing[]>({queryKey:['marketplace',id,category],queryFn:async()=>(await api.get(`/communities/${id}/marketplace`,{params:{type:category==='ALL'?'':category}})).data});
 const items=useMemo(()=>{const q=search.trim().toLowerCase();const filtered=(query.data||[]).filter(x=>!q||`${x.Title} ${x.Description||''} ${x.Area||''} ${x.ListingType}`.toLowerCase().includes(q));return [...filtered].sort((a,b)=>(latest?-1:1)*(new Date(b.CreatedAt).getTime()-new Date(a.CreatedAt).getTime()))},[query.data,search,latest]);
 const save=useMutation({mutationFn:(listingId:string)=>api.post(`/marketplace/${listingId}/save`),onSuccess:()=>qc.invalidateQueries({queryKey:['marketplace',id]}),onError:(e:any)=>Alert.alert('Unable to save',e.response?.data?.message||'Please try again.')});
 const remove=useMutation({mutationFn:(listingId:string)=>api.delete(`/communities/${id}/marketplace/${listingId}`),onSuccess:()=>qc.invalidateQueries({queryKey:['marketplace',id]})});const report=useMutation({mutationFn:(listingId:string)=>api.post(`/marketplace/${listingId}/report`,{reason:'Member report',details:'Reported from the CDA Connect marketplace.'}),onSuccess:()=>Alert.alert('Report submitted','Community moderators can review this listing.')});
 async function messageSeller(item:Listing){try{const r=await api.post(`/communities/${id}/direct-conversations/${item.SellerUserId}`);router.push(`/chat/${r.data.Id}` as never)}catch(e:any){Alert.alert('Unable to message',e.response?.data?.message||e.message)}}
 function options(item:Listing){Alert.alert(item.Title,'Choose an action',[{text:'Message seller',onPress:()=>void messageSeller(item)},{text:item.IsSaved?'Remove saved item':'Save item',onPress:()=>save.mutate(item.Id)},{text:'Report listing',onPress:()=>report.mutate(item.Id)},...(canModerate?[{text:'Remove listing',style:'destructive' as const,onPress:()=>remove.mutate(item.Id)}]:[]),{text:'Cancel',style:'cancel'}])}
 return <Screen scroll contentStyle={s.page}><Header page title="Marketplace" subtitle="Buy, sell and connect with verified members in your community." right={<Button title={width<380?'Post':'Post Item'} icon="bag-add-outline" variant="success" onPress={()=>router.push(`/community/${id}/post-marketplace-item` as never)}/>}/><View style={[s.search,{borderColor:palette.border,backgroundColor:palette.surface}]}><Ionicons name="search-outline" size={23} color={palette.muted}/><TextInput accessibilityLabel="Search marketplace" value={search} onChangeText={setSearch} placeholder="Search items, services or keywords" placeholderTextColor={palette.muted} style={[s.searchInput,{color:palette.text}]}/>{search?<Pressable accessibilityLabel="Clear search" onPress={()=>setSearch('')} style={s.iconButton}><Ionicons name="close-circle" size={21} color={palette.muted}/></Pressable>:null}</View><View style={s.categories}>{categories.map(([value,icon,label])=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:category===value}} onPress={()=>setCategory(value)} style={[s.category,{borderColor:category===value?palette.primary:palette.border,backgroundColor:category===value?palette.primarySoft:palette.surface}]}><Ionicons name={icon} size={24} color={palette.primary}/><Text numberOfLines={2} style={[s.categoryText,{color:palette.text}]}>{label}</Text></Pressable>)}</View><View style={s.sectionHead}><Text style={[s.sectionTitle,{color:palette.text}]}>Community Listings</Text><Pressable accessibilityRole="button" onPress={()=>setLatest(v=>!v)} style={[s.sort,{borderColor:palette.border,backgroundColor:palette.surface}]}><Text style={{color:palette.text,fontWeight:'800'}}>{latest?'Latest':'Oldest'}</Text><Ionicons name="swap-vertical" size={18} color={palette.primary}/></Pressable></View>
 {query.isLoading?<Muted>Loading marketplace…</Muted>:query.isError?<EmptyState icon="cloud-offline-outline" title="Marketplace unavailable" body="Check your connection and try again."/>:items.length?<View style={s.grid}>{items.map(item=><Pressable key={item.Id} accessibilityRole="button" accessibilityLabel={`Open ${item.Title}`} onPress={()=>options(item)} style={[s.listing,{width:width<430?'100%':'48.8%',borderColor:palette.border,backgroundColor:palette.surface}]}>{item.ImageUrl?<Image source={{uri:item.ImageUrl}} style={s.image}/>:<View style={[s.placeholder,{backgroundColor:palette.primarySoft}]}><Ionicons name="bag-handle-outline" size={40} color={palette.primary}/></View>}<Pressable accessibilityLabel={item.IsSaved?'Remove saved item':'Save item'} onPress={()=>save.mutate(item.Id)} style={[s.save,{backgroundColor:palette.surface}]}><Ionicons name={item.IsSaved?'heart':'heart-outline'} size={22} color={item.IsSaved?palette.danger:palette.primary}/></Pressable><View style={s.listingBody}><View style={s.badges}><Badge text={item.ListingType.replace('_',' ')}/>{item.SellerVerified?<Badge text="Verified" tone="green"/>:null}</View><Text numberOfLines={2} style={[s.itemTitle,{color:palette.text}]}>{item.Title}</Text><Text style={[s.price,{color:palette.primary}]}>{item.Price!=null?`${item.Currency==='NGN'?'₦':item.Currency} ${formatAmount(item.Price)}`:item.ListingType==='FREE'?'Free':'Contact seller'}</Text><View style={s.meta}><Ionicons name="location-outline" size={16} color={palette.muted}/><Muted numberOfLines={1}>{item.Area||'Community'}</Muted></View><Muted numberOfLines={1}>{item.FirstName} {item.LastName} · {new Date(item.CreatedAt).toLocaleDateString()}</Muted></View></Pressable>)}</View>:<EmptyState icon="bag-handle-outline" title={search?'No matching listings':'No marketplace listings'} body={search?'Try another keyword or category.':'Use Post Item to publish the first community listing.'}/>}</Screen>
}
const s=StyleSheet.create({page:{width:'100%',maxWidth:960,alignSelf:'center',paddingBottom:135},search:{minHeight:56,borderWidth:1,borderRadius:15,flexDirection:'row',alignItems:'center',paddingLeft:15,gap:9,marginBottom:14},searchInput:{flex:1,minWidth:0,fontSize:15,paddingVertical:13},iconButton:{width:44,height:44,alignItems:'center',justifyContent:'center'},categories:{width:'100%',flexDirection:'row',gap:5,marginBottom:20,flexWrap:'nowrap'},category:{flex:1,minWidth:0,minHeight:72,borderWidth:1,borderRadius:13,alignItems:'center',justifyContent:'center',gap:5,paddingHorizontal:2,paddingVertical:6},categoryText:{fontSize:9,fontWeight:'800',textAlign:'center'},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:12},sectionTitle:{fontSize:19,fontWeight:'900',flex:1},sort:{minHeight:44,borderWidth:1,borderRadius:12,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:7},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},listing:{minWidth:0,borderWidth:1,borderRadius:16,overflow:'hidden',position:'relative'},image:{width:'100%',height:170,backgroundColor:'#E8ECE9'},placeholder:{width:'100%',height:150,alignItems:'center',justifyContent:'center'},save:{position:'absolute',right:9,top:9,width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',elevation:3},listingBody:{padding:13},badges:{flexDirection:'row',flexWrap:'wrap',gap:5},itemTitle:{fontSize:17,fontWeight:'900',marginTop:9},price:{fontSize:17,fontWeight:'900',marginVertical:6},meta:{flexDirection:'row',alignItems:'center',gap:3,minWidth:0}});
