import {useMemo,useState} from 'react';
import {Alert,Modal,Platform,Pressable,Share,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {useLocalSearchParams,router} from 'expo-router';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {Avatar,Badge,Button,Card,EmptyState,Input,Muted,Screen,useAppTheme} from '@/components/UI';
import {useAuth} from '@/store/auth';

type Member={MembershipId:string;UserId:string;FirstName:string;LastName:string;Email:string;Roles?:string;JoinedAt?:string;Status?:string};
type Role='Admin'|'Moderator'|'Member';

export default function Members(){
 const{id}=useLocalSearchParams<{id:string}>();const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;const qc=useQueryClient();const user=useAuth(s=>s.user);
 const[search,setSearch]=useState('');const[roleFilter,setRoleFilter]=useState<'All'|Role>('All');const[selected,setSelected]=useState<Member|null>(null);
 const members=useQuery<Member[]>({queryKey:['members',id],queryFn:async()=>(await api.get(`/communities/${id}/members`)).data});const community=useQuery<any>({queryKey:['community',id],queryFn:async()=>(await api.get(`/communities/${id}`)).data});const data=members.data||[];
 const canManage=['Admin','Owner'].includes(community.data?.UserRole);const filtered=useMemo(()=>data.filter(m=>{const matches=`${m.FirstName} ${m.LastName} ${m.Email}`.toLowerCase().includes(search.trim().toLowerCase());return matches&&(roleFilter==='All'||String(m.Roles||'Member').includes(roleFilter))}),[data,search,roleFilter]);
 const roleMutation=useMutation({mutationFn:async(v:{member:Member;role:Role})=>api.patch(`/communities/${id}/members/${v.member.MembershipId}/roles`,{roles:[v.role]}),onSuccess:(_,v)=>{setSelected(null);qc.invalidateQueries({queryKey:['members',id]});Alert.alert('Role updated',`${v.member.FirstName} is now ${v.role}.`)},onError:(e:any)=>Alert.alert('Unable to update role',e.response?.data?.message||'Admin permission is required.')});
 const removeMutation=useMutation({mutationFn:async(member:Member)=>api.delete(`/communities/${id}/members/${member.MembershipId}`),onSuccess:(_,member)=>{setSelected(null);qc.invalidateQueries({queryKey:['members',id]});Alert.alert('Member removed',`${member.FirstName} has been removed from the community.`)},onError:(e:any)=>Alert.alert('Unable to remove member',e.response?.data?.message||'Admin permission is required.')});
 const invite=()=>Share.share({title:`Join ${community.data?.Name||'my community'}`,message:`Join ${community.data?.Name||'my community'} on CDA Connect using code: ${community.data?.JoinCode||''}`});
 function openMenu(member:Member){if(!canManage)return Alert.alert('Member details',`${member.FirstName} ${member.LastName}\n${member.Roles||'Member'}\n${member.Email}`);if(String(member.Roles||'').includes('Owner'))return Alert.alert('Community owner','The community owner’s role cannot be changed or removed.');setSelected(member)}
 function confirmRemove(){if(!selected)return;Alert.alert('Remove member?',`${selected.FirstName} ${selected.LastName} will lose access to this community and its conversations.`,[{text:'Cancel',style:'cancel'},{text:'Remove from community',style:'destructive',onPress:()=>removeMutation.mutate(selected)}])}
 const counts={admins:data.filter(x=>String(x.Roles).includes('Admin')||String(x.Roles).includes('Owner')).length,moderators:data.filter(x=>String(x.Roles).includes('Moderator')).length,members:data.filter(x=>!String(x.Roles).includes('Admin')&&!String(x.Roles).includes('Owner')&&!String(x.Roles).includes('Moderator')).length};
 return <Screen scroll contentStyle={desktop?s.desktop:undefined}>
  <View style={s.nav}><Pressable accessibilityLabel="Back to community" onPress={()=>(router.canGoBack()?router.back():router.replace('/'))} style={s.touch}><Ionicons name="chevron-back" size={24} color={palette.text}/></Pressable><View style={{flex:1}}><Text style={[s.navTitle,{color:palette.text}]}>Members ({data.length.toLocaleString()})</Text><Muted>Manage and connect with members of {community.data?.Name||'this community'}.</Muted></View><Pressable accessibilityLabel="Invite members" onPress={invite} style={[s.inviteTop,{backgroundColor:palette.success}]}><Ionicons name="person-add-outline" size={18} color="#fff"/><Text style={s.inviteText}>Invite</Text></Pressable></View>
  <View style={desktop?s.columns:undefined}><View style={{flex:1,minWidth:0}}><Card><View style={[s.tools,!desktop&&{flexDirection:'column',alignItems:'stretch'}]}><View style={[s.search,{borderColor:palette.border,backgroundColor:palette.surface}]}><Ionicons name="search" size={19} color={palette.muted}/><Input placeholder="Search members…" value={search} onChangeText={setSearch} style={s.searchInput}/></View><View style={s.filters}>{(['All','Admin','Moderator','Member'] as const).map(role=><Pressable key={role} onPress={()=>setRoleFilter(role)} style={[s.filter,{borderColor:roleFilter===role?palette.success:palette.border,backgroundColor:roleFilter===role?palette.successSoft:palette.surface}]}><Text style={{color:roleFilter===role?palette.success:palette.text,fontWeight:'800'}}>{role}</Text></Pressable>)}</View></View></Card>
  {members.isLoading?<Muted>Loading members…</Muted>:filtered.length?filtered.map((m,i)=><View key={m.MembershipId} style={[s.row,{borderBottomColor:palette.border}]}><Avatar name={`${m.FirstName} ${m.LastName}`} backgroundColor={[palette.primary,palette.navy,palette.success,'#334155'][i%4]}/><View style={{flex:1}}><View style={s.memberName}><Text style={[s.name,{color:palette.text}]}>{m.FirstName} {m.LastName}</Text>{m.UserId===user?.Id?<Badge text="You" tone="green"/>:null}</View><Muted>{m.Email}</Muted><View style={s.memberMeta}><Badge text={String(m.Roles||'Member').split(',')[0]} tone={String(m.Roles).includes('Admin')||String(m.Roles).includes('Owner')?'green':String(m.Roles).includes('Moderator')?'blue':'gray'}/><View style={[s.statusDot,{backgroundColor:palette.success}]}/><Muted>Active</Muted>{m.JoinedAt?<Muted>· Joined {new Date(m.JoinedAt).toLocaleDateString()}</Muted>:null}</View></View><Pressable accessibilityLabel={`Actions for ${m.FirstName} ${m.LastName}`} onPress={()=>openMenu(m)} style={s.touch}><Ionicons name="ellipsis-vertical" size={20} color={palette.muted}/></Pressable></View>):<EmptyState icon="people-outline" title="No members found" body="Try another search or invite members to this community."/>}</View>
  {desktop?<View style={s.aside}><Card><Text style={[s.cardTitle,{color:palette.text}]}>Member Summary</Text><Summary icon="people" label="Total members" value={data.length} color={palette.primary} palette={palette}/><Summary icon="shield-checkmark" label="Admins" value={counts.admins} color={palette.success} palette={palette}/><Summary icon="ribbon" label="Moderators" value={counts.moderators} color={palette.primary} palette={palette}/><Summary icon="person" label="Members" value={counts.members} color={palette.muted} palette={palette}/></Card><Card><Text style={[s.cardTitle,{color:palette.text}]}>Roles & Permissions</Text><Muted><Text style={{fontWeight:'900'}}>Admin:</Text> manage settings, members and activities.</Muted><Muted style={s.permission}><Text style={{fontWeight:'900'}}>Moderator:</Text> manage posts, discussions and member guidance.</Muted><Muted style={s.permission}><Text style={{fontWeight:'900'}}>Member:</Text> standard community access.</Muted></Card><Button title="Invite Members" icon="person-add-outline" variant="success" onPress={invite}/></View>:null}</View>
  {!desktop?<Button title="Invite Members" icon="person-add-outline" variant="success" onPress={invite}/>:null}
  <Modal visible={!!selected} transparent animationType="fade" onRequestClose={()=>setSelected(null)}><Pressable style={s.overlay} onPress={()=>setSelected(null)}><Pressable style={[s.menu,{backgroundColor:palette.surface,borderColor:palette.border}]} onPress={()=>{}}><View style={s.menuHeader}><Avatar name={`${selected?.FirstName||''} ${selected?.LastName||''}`} size={42}/><View style={{flex:1}}><Text style={[s.name,{color:palette.text}]}>{selected?.FirstName} {selected?.LastName}</Text><Muted>{selected?.Email}</Muted></View><Pressable onPress={()=>setSelected(null)} style={s.touch}><Ionicons name="close" size={22} color={palette.text}/></Pressable></View><MenuItem icon="shield-checkmark-outline" label="Set as Admin" detail="Full community management access" color={palette.success} onPress={()=>selected&&roleMutation.mutate({member:selected,role:'Admin'})} palette={palette}/><MenuItem icon="ribbon-outline" label="Set as Moderator" detail="Manage content and discussions" color={palette.primary} onPress={()=>selected&&roleMutation.mutate({member:selected,role:'Moderator'})} palette={palette}/><MenuItem icon="person-outline" label="Set as Member" detail="Standard community access" color={palette.muted} onPress={()=>selected&&roleMutation.mutate({member:selected,role:'Member'})} palette={palette}/><MenuItem icon="person-remove-outline" label="Remove from Community" detail="Revoke community access" color={palette.danger} onPress={confirmRemove} palette={palette}/></Pressable></Pressable></Modal>
 </Screen>
}

function MenuItem({icon,label,detail,color,onPress,palette}:{icon:keyof typeof Ionicons.glyphMap;label:string;detail:string;color:string;onPress:()=>void;palette:any}){return <Pressable disabled={false} onPress={onPress} style={[s.menuItem,{borderTopColor:palette.border}]}><View style={[s.menuIcon,{backgroundColor:`${color}18`}]}><Ionicons name={icon} size={21} color={color}/></View><View style={{flex:1}}><Text style={{color:label.startsWith('Remove')?palette.danger:palette.text,fontWeight:'900'}}>{label}</Text><Muted>{detail}</Muted></View><Ionicons name="chevron-forward" size={18} color={palette.muted}/></Pressable>}
function Summary({icon,label,value,color,palette}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:number;color:string;palette:any}){return <View style={s.summary}><View style={[s.summaryIcon,{backgroundColor:`${color}18`}]}><Ionicons name={icon} size={18} color={color}/></View><Text style={{color:palette.text,flex:1}}>{label}</Text><Text style={{color:palette.text,fontWeight:'900'}}>{value.toLocaleString()}</Text></View>}
const s=StyleSheet.create({desktop:{maxWidth:1180},nav:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:18},navTitle:{fontSize:22,fontWeight:'900'},touch:{minWidth:44,minHeight:44,alignItems:'center',justifyContent:'center'},inviteTop:{minHeight:42,borderRadius:10,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:7},inviteText:{color:'#fff',fontWeight:'900'},columns:{flexDirection:'row',alignItems:'flex-start',gap:14},aside:{width:300},tools:{flexDirection:'row',gap:12,alignItems:'center'},search:{flex:1,flexDirection:'row',alignItems:'center',borderWidth:1,borderRadius:12,paddingHorizontal:12},searchInput:{flex:1,borderWidth:0,marginBottom:0,paddingHorizontal:8,backgroundColor:'transparent'},filters:{flexDirection:'row',gap:7,flexWrap:'wrap'},filter:{minHeight:42,borderWidth:1,borderRadius:10,paddingHorizontal:12,alignItems:'center',justifyContent:'center'},row:{flexDirection:'row',gap:12,alignItems:'center',paddingVertical:13,borderBottomWidth:1},memberName:{flexDirection:'row',gap:8,alignItems:'center'},name:{fontSize:14,fontWeight:'900'},memberMeta:{flexDirection:'row',alignItems:'center',gap:7,flexWrap:'wrap',marginTop:6},statusDot:{width:7,height:7,borderRadius:4},cardTitle:{fontSize:17,fontWeight:'900',marginBottom:10},summary:{minHeight:48,flexDirection:'row',alignItems:'center',gap:10},summaryIcon:{width:34,height:34,borderRadius:10,alignItems:'center',justifyContent:'center'},permission:{marginTop:12},overlay:{flex:1,backgroundColor:'rgba(15,23,42,.42)',alignItems:'center',justifyContent:'center',padding:20},menu:{width:'100%',maxWidth:440,borderWidth:1,borderRadius:18,padding:14,shadowColor:'#000',shadowOpacity:.2,shadowRadius:20,elevation:12},menuHeader:{flexDirection:'row',alignItems:'center',gap:10,paddingBottom:10},menuItem:{minHeight:68,borderTopWidth:1,flexDirection:'row',alignItems:'center',gap:11},menuIcon:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'}});
