import {useMemo,useState} from 'react';
import {Alert,Modal,Pressable,StyleSheet,Text,View} from 'react-native';
import {useLocalSearchParams} from 'expo-router';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {Avatar,Badge,Button,Card,EmptyState,Header,Input,Muted,Screen,useAppTheme} from '@/components/UI';

type Exco={Id:string;UserId:string;Position:string;Department?:string;AppointedDate:string;TenureEndDate?:string;Notes?:string;Status:'ACTIVE'|'INACTIVE';FirstName:string;LastName:string;Email:string;Phone?:string;ProfileImage?:string};
const months=(start:string,end?:string)=>Math.max(0,Math.round((new Date(end||Date.now()).getTime()-new Date(start).getTime())/2629800000));
const term=(item:Exco)=>{const value=months(item.AppointedDate,item.TenureEndDate);const years=Math.floor(value/12),rest=value%12;return [years?`${years} year${years===1?'':'s'}`:'',rest?`${rest} month${rest===1?'':'s'}`:''].filter(Boolean).join(' ')||'Less than a month'};
const date=(value?:string)=>value?new Date(value).toLocaleDateString(undefined,{month:'short',year:'numeric'}):'Not recorded';

export default function PastExcos(){
 const{id}=useLocalSearchParams<{id:string}>();const{palette}=useAppTheme();const qc=useQueryClient();const[search,setSearch]=useState('');const[position,setPosition]=useState('All Positions');const[year,setYear]=useState('All Time');const[detail,setDetail]=useState<Exco|null>(null);
 const query=useQuery<{items:Exco[];canManage:boolean}>({queryKey:['excos',id],queryFn:async()=>(await api.get(`/communities/${id}/excos`)).data});
 const restore=useMutation({mutationFn:(item:Exco)=>api.patch(`/communities/${id}/excos/${item.Id}`,{status:'ACTIVE'}),onSuccess:()=>{qc.invalidateQueries({queryKey:['excos',id]});setDetail(null);Alert.alert('Exco restored','The appointment is active again.')},onError:(e:any)=>Alert.alert('Restore failed',e.response?.data?.error||'Please try again.')});
 const items=(query.data?.items||[]).filter(x=>x.Status==='INACTIVE');const positions=useMemo(()=>['All Positions',...Array.from(new Set(items.map(x=>x.Position))).sort()],[items]);const years=useMemo(()=>['All Time',...Array.from(new Set(items.map(x=>String(new Date(x.TenureEndDate||x.AppointedDate).getFullYear())))).sort((a,b)=>Number(b)-Number(a))],[items]);
 const visible=useMemo(()=>items.filter(x=>(position==='All Positions'||x.Position===position)&&(year==='All Time'||String(new Date(x.TenureEndDate||x.AppointedDate).getFullYear())===year)&&`${x.FirstName} ${x.LastName} ${x.Position} ${x.Department||''}`.toLowerCase().includes(search.trim().toLowerCase())),[items,position,year,search]);
 const totalMonths=items.reduce((sum,item)=>sum+months(item.AppointedDate,item.TenureEndDate),0),average=items.length?totalMonths/items.length/12:0;
 function cycle(current:string,values:string[],set:(value:string)=>void){const index=values.indexOf(current);set(values[(index+1)%values.length])}
 return <Screen scroll contentStyle={s.page}><Header page title="Past Excos" subtitle="Completed executive committee terms"/>
  <View style={[s.hero,{backgroundColor:palette.primarySoft}]}><View style={[s.heroIcon,{backgroundColor:palette.surface}]}><Ionicons name="shield-checkmark" size={42} color={palette.primary}/></View><Text style={[s.heroTitle,{color:palette.primary}]}>Past Exco Members</Text><Muted style={s.heroBody}>Official history of completed executive committee appointments.</Muted></View>
  <Card style={s.stats}><Stat icon="people" label="Total Past Excos" value={String(items.length)} palette={palette}/><Stat icon="calendar" label="Completed Terms" value={String(items.filter(x=>x.TenureEndDate).length)} palette={palette}/><Stat icon="ribbon" label="Average Term" value={items.length?`${average.toFixed(1)} years`:'0 years'} palette={palette}/><Stat icon="time" label="Total Served" value={`${(totalMonths/12).toFixed(1)} years`} palette={palette}/></Card>
  <View style={[s.search,{borderColor:palette.border,backgroundColor:palette.surface}]}><Ionicons name="search-outline" size={22} color={palette.muted}/><Input placeholder="Search by name or position" value={search} onChangeText={setSearch} style={s.input}/></View>
  <View style={s.filters}><Pressable onPress={()=>cycle(position,positions,setPosition)} style={[s.filter,{borderColor:palette.border,backgroundColor:palette.surface}]}><Text numberOfLines={1} style={[s.filterText,{color:palette.text}]}>{position}</Text><Ionicons name="chevron-down" size={17} color={palette.primary}/></Pressable><Pressable onPress={()=>cycle(year,years,setYear)} style={[s.filter,{borderColor:palette.border,backgroundColor:palette.surface}]}><Ionicons name="calendar-outline" size={17} color={palette.primary}/><Text numberOfLines={1} style={[s.filterText,{color:palette.text}]}>{year}</Text><Ionicons name="chevron-down" size={17} color={palette.primary}/></Pressable></View>
  {query.isLoading?<Muted>Loading past appointments…</Muted>:query.isError?<EmptyState icon="cloud-offline-outline" title="Could not load Past Excos" body="Check your connection and try again."/>:visible.length?<Card style={s.list}>{visible.map((item,index)=><Pressable key={item.Id} accessibilityRole="button" accessibilityLabel={`View ${item.FirstName} ${item.LastName} term`} onPress={()=>setDetail(item)} style={[s.row,index<visible.length-1&&{borderBottomWidth:1,borderBottomColor:palette.border}]}><Avatar name={`${item.FirstName} ${item.LastName}`} uri={item.ProfileImage} size={50}/><View style={s.person}><Text numberOfLines={1} style={[s.name,{color:palette.text}]}>{item.FirstName} {item.LastName}</Text><Muted numberOfLines={1}>{item.Position}</Muted><Text style={{color:palette.primary,fontSize:12,fontWeight:'800'}}>{date(item.AppointedDate)} – {date(item.TenureEndDate)}</Text></View><View style={s.term}><Badge text="Completed" tone="green"/><Muted numberOfLines={2}>{term(item)}</Muted></View><Ionicons name="chevron-forward" size={21} color={palette.text}/></Pressable>)}</Card>:<EmptyState icon="time-outline" title={search||position!=='All Positions'||year!=='All Time'?'No matching records':'No past Excos'} body="Completed Exco appointments will appear here when an active appointment is marked inactive."/>}
  <Modal visible={!!detail} transparent animationType="fade" onRequestClose={()=>setDetail(null)}><Pressable style={s.backdrop} onPress={()=>setDetail(null)}><Pressable style={[s.detail,{backgroundColor:palette.surface}]} onPress={()=>{}}><View style={s.detailHead}><View style={s.person}><Text style={[s.detailTitle,{color:palette.text}]}>{detail?.FirstName} {detail?.LastName}</Text><Muted>{detail?.Email}</Muted></View><Pressable accessibilityLabel="Close details" onPress={()=>setDetail(null)} style={s.close}><Ionicons name="close" size={25} color={palette.text}/></Pressable></View><Detail label="Position" value={detail?.Position} palette={palette}/><Detail label="Department" value={detail?.Department||'Not specified'} palette={palette}/><Detail label="Term" value={detail?`${date(detail.AppointedDate)} – ${date(detail.TenureEndDate)} (${term(detail)})`:''} palette={palette}/>{detail?.Notes?<Detail label="Notes" value={detail.Notes} palette={palette}/>:null}{query.data?.canManage?<Button title="Restore as Active Exco" variant="success" icon="refresh-outline" loading={restore.isPending} onPress={()=>detail&&restore.mutate(detail)}/>:null}<Button title="Close" variant="secondary" onPress={()=>setDetail(null)}/></Pressable></Pressable></Modal>
 </Screen>
}
function Stat({icon,label,value,palette}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:string;palette:any}){return <View style={[s.stat,{borderColor:palette.border}]}><View style={[s.statIcon,{backgroundColor:palette.primarySoft}]}><Ionicons name={icon} size={22} color={palette.primary}/></View><View style={s.person}><Muted>{label}</Muted><Text numberOfLines={1} adjustsFontSizeToFit style={[s.statValue,{color:palette.primary}]}>{value}</Text></View></View>}
function Detail({label,value,palette}:{label:string;value?:string;palette:any}){return <View style={[s.detailRow,{borderBottomColor:palette.border}]}><Muted>{label}</Muted><Text style={{color:palette.text,fontWeight:'800',textAlign:'right',flex:1}}>{value}</Text></View>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:850,alignSelf:'center',paddingBottom:140},hero:{borderRadius:20,alignItems:'center',padding:22,marginBottom:12},heroIcon:{width:78,height:78,borderRadius:39,alignItems:'center',justifyContent:'center'},heroTitle:{fontSize:21,fontWeight:'900',marginTop:11},heroBody:{textAlign:'center',marginTop:5},stats:{flexDirection:'row',flexWrap:'wrap',padding:8},stat:{width:'50%',minHeight:78,borderBottomWidth:1,padding:9,flexDirection:'row',alignItems:'center',gap:9},statIcon:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center'},statValue:{fontSize:18,fontWeight:'900',marginTop:2},person:{flex:1,minWidth:0},search:{height:56,borderWidth:1,borderRadius:14,flexDirection:'row',alignItems:'center',paddingLeft:13,marginBottom:10},input:{flex:1,borderWidth:0,marginBottom:0,backgroundColor:'transparent'},filters:{flexDirection:'row',gap:9,marginBottom:12},filter:{flex:1,minWidth:0,minHeight:48,borderWidth:1,borderRadius:12,paddingHorizontal:11,flexDirection:'row',alignItems:'center',gap:6},filterText:{flex:1,minWidth:0,fontSize:12,fontWeight:'800'},list:{padding:0,overflow:'hidden'},row:{minHeight:86,paddingHorizontal:11,paddingVertical:9,flexDirection:'row',alignItems:'center',gap:9},name:{fontSize:14,fontWeight:'900'},term:{width:88,alignItems:'flex-start',gap:4},backdrop:{flex:1,backgroundColor:'rgba(15,31,68,.4)',alignItems:'center',justifyContent:'center',padding:18},detail:{width:'100%',maxWidth:430,borderRadius:20,padding:18},detailHead:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:10},detailTitle:{fontSize:20,fontWeight:'900'},close:{width:42,height:42,alignItems:'center',justifyContent:'center'},detailRow:{minHeight:54,borderBottomWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12}});
