import {useMemo,useState} from 'react';
import {Alert,Modal,Pressable,StyleSheet,Text,View,useWindowDimensions} from '@/platform/react-native';
import {router,useLocalSearchParams} from '@/router';
import {Ionicons} from '@/platform/icons';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api} from '@/lib/api';
import {Badge,Button,Card,EmptyState,Input,Muted,Screen,TabBar,useAppTheme} from '@/components/UI';
import {DateField} from '@/components/DateField';

type Option={Id:string;OptionText:string;VoteCount:number;MyVote:boolean};
type Poll={Id:string;Question:string;Description?:string;IsAnonymous:boolean;AllowMultiple:boolean;AllowChangeVote:boolean;StartAt:string;EndAt?:string;CreatedAt:string;VoterCount:number;MemberCount:number;options:Option[]};
type Tab='all'|'active'|'completed';
type Filter='ALL'|'SINGLE'|'MULTIPLE';
type AdminAction='edit'|'stop'|'delete';

export default function Polls(){
 const{id}=useLocalSearchParams<{id:string}>(),{palette}=useAppTheme(),{width}=useWindowDimensions(),queryClient=useQueryClient();
 const[tab,setTab]=useState<Tab>('all'),[search,setSearch]=useState(''),[filter,setFilter]=useState<Filter>('ALL'),[openMenu,setOpenMenu]=useState<string|null>(null);
 const[action,setAction]=useState<{kind:AdminAction;poll:Poll}|null>(null),[createdDate,setCreatedDate]=useState(''),[editMode,setEditMode]=useState(false),[question,setQuestion]=useState(''),[description,setDescription]=useState('');
 const polls=useQuery<Poll[]>({queryKey:['polls',id],queryFn:async()=>(await api.get(`/communities/${id}/polls`)).data});
 const capabilities=useQuery<any>({queryKey:['capabilities',id],queryFn:async()=>(await api.get(`/communities/${id}/capabilities`)).data});
 const permissions:string[]=capabilities.data?.permissions||[],roles:string[]=capabilities.data?.roles||[];
 const isAdmin=!!capabilities.data?.isOwner||!!capabilities.data?.canManageCommunity||permissions.includes('POLL_CLOSE')||roles.some(role=>['OWNER','ADMIN'].includes(String(role).trim().toUpperCase()));
 const shown=useMemo(()=>{const term=search.trim().toLowerCase(),now=Date.now();return(polls.data||[]).filter(p=>{const ended=!!p.EndAt&&new Date(p.EndAt).getTime()<=now;if(tab==='active'&&ended)return false;if(tab==='completed'&&!ended)return false;if(filter==='SINGLE'&&p.AllowMultiple)return false;if(filter==='MULTIPLE'&&!p.AllowMultiple)return false;return !term||`${p.Question} ${p.Description||''}`.toLowerCase().includes(term)})},[polls.data,tab,filter,search]);
 const perform=useMutation({mutationFn:async()=>{if(!action)return;if(action.kind==='edit'&&!editMode){await api.post(`/polls/${action.poll.Id}/verify-created-date`,{createdDate});return'edit'}if(action.kind==='edit'){await api.patch(`/polls/${action.poll.Id}`,{createdDate,question:question.trim(),description:description.trim()||undefined});return'done'}if(action.kind==='stop'){await api.post(`/polls/${action.poll.Id}/stop`,{createdDate});return'done'}await api.delete(`/polls/${action.poll.Id}`,{data:{createdDate}});return'done'},onSuccess:async result=>{if(result==='edit'){setEditMode(true);return}await queryClient.invalidateQueries({queryKey:['polls',id]});closeAction();Alert.alert('Poll updated',action?.kind==='delete'?'The poll was deleted.':action?.kind==='stop'?'The poll was stopped.':'The poll details were saved.')},onError:(error:any)=>Alert.alert('Action not completed',error?.response?.data?.message||error?.message||'Please check the created date and try again.')});
 function chooseFilter(){Alert.alert('Filter polls','Choose which voting format to display.',[{text:'All poll types',onPress:()=>setFilter('ALL')},{text:'Single choice',onPress:()=>setFilter('SINGLE')},{text:'Multiple choice',onPress:()=>setFilter('MULTIPLE')},{text:'Cancel',style:'cancel'}])}
 function beginAction(kind:AdminAction,poll:Poll){setAction({kind,poll});setCreatedDate('');setEditMode(false);setQuestion(poll.Question);setDescription(poll.Description||'')}
 function closeAction(){setAction(null);setCreatedDate('');setEditMode(false)}
 const validDate=/^\d{4}-\d{2}-\d{2}$/.test(createdDate),canContinue=validDate&&(!editMode||question.trim().length>=2);
 return <Screen scroll contentStyle={s.page}><Pressable onPress={()=>setOpenMenu(null)}>
  <TabBar value={tab} onChange={setTab} items={[{key:'all',label:'All Polls'},{key:'active',label:'Active'},{key:'completed',label:'Completed'}]}/>
  <View style={s.searchRow}><View style={[s.search,{borderColor:palette.border,backgroundColor:palette.surface}]}><Ionicons name="search-outline" size={22} color={palette.muted}/><Input value={search} onChangeText={setSearch} placeholder={`Search ${tab==='all'?'polls':`${tab} polls`}…`} style={s.searchInput}/></View><Pressable accessibilityRole="button" accessibilityLabel="Filter polls" onPress={chooseFilter} style={[s.filter,{borderColor:filter==='ALL'?palette.border:palette.success,backgroundColor:palette.surface}]}><Ionicons name="filter-outline" size={21} color={filter==='ALL'?palette.text:palette.success}/>{width>=430?<Text style={{color:palette.text,fontWeight:'800'}}>Filter</Text>:null}</Pressable></View>
  {polls.isLoading?<Muted>Loading community polls…</Muted>:polls.isError?<EmptyState icon="cloud-offline-outline" title="Polls unavailable" body="The community polls could not be loaded."/>:shown.length?shown.map(p=><PollCard key={p.Id} poll={p} mode={tab} open={()=>router.push(`/community/${id}/poll/${p.Id}` as any)} palette={palette} isAdmin={isAdmin} menuOpen={openMenu===p.Id} toggleMenu={()=>setOpenMenu(current=>current===p.Id?null:p.Id)} onAdminAction={beginAction}/>):<EmptyState icon="stats-chart-outline" title="No polls found" body={search||filter!=='ALL'?'Change the search or filter to see more polls.':tab==='active'?'There are no active polls accepting votes.':tab==='completed'?'No community polls have ended yet.':'Create a poll to collect responses from community members.'}/>} 
  <Modal transparent animationType="fade" visible={!!action} onRequestClose={closeAction}><Pressable style={s.overlay} onPress={closeAction}><Pressable onPress={()=>{}} style={[s.modal,{backgroundColor:palette.surface,borderColor:palette.border}]}><View style={s.modalTitleRow}><Text style={[s.modalTitle,{color:palette.text}]}>{editMode?'Edit poll':`${action?.kind==='stop'?'Stop':action?.kind==='delete'?'Delete':'Edit'} poll`}</Text><Pressable accessibilityLabel="Close" onPress={closeAction} hitSlop={10}><Ionicons name="close" size={24} color={palette.text}/></Pressable></View>{editMode?<><Text style={[s.label,{color:palette.text}]}>Poll question</Text><Input value={question} onChangeText={setQuestion} maxLength={500}/><Text style={[s.label,{color:palette.text}]}>Description</Text><Input value={description} onChangeText={setDescription} multiline maxLength={5000} style={s.description}/><Muted>Existing poll options and votes will be preserved.</Muted></>:<><Muted>Select the date this poll was created to continue. This protects administrative actions from accidental changes.</Muted><Text style={[s.label,{color:palette.text}]}>Poll created date</Text><DateField value={createdDate} onChange={setCreatedDate} placeholder="Select created date" maximumDate={new Date()}/></>}<View style={s.modalButtons}><Button title="Cancel" variant="secondary" onPress={closeAction}/><View style={s.continue}><Button title={editMode?'Save changes':'Continue'} variant={action?.kind==='delete'?'danger':'primary'} loading={perform.isPending} disabled={!canContinue||perform.isPending} onPress={()=>perform.mutate()}/></View></View></Pressable></Pressable></Modal>
 </Pressable></Screen>
}

function PollCard({poll,mode,open,palette,isAdmin,menuOpen,toggleMenu,onAdminAction}:{poll:Poll;mode:Tab;open:()=>void;palette:any;isAdmin:boolean;menuOpen:boolean;toggleMenu:()=>void;onAdminAction:(kind:AdminAction,poll:Poll)=>void}){
 const ended=!!poll.EndAt&&new Date(poll.EndAt).getTime()<=Date.now(),total=poll.options.reduce((n,o)=>n+Number(o.VoteCount||0),0),voters=Number(poll.VoterCount||total),members=Number(poll.MemberCount||0),participation=members?Math.min(100,Math.round(voters/members*100)):0,days=poll.EndAt?Math.max(0,Math.ceil((new Date(poll.EndAt).getTime()-Date.now())/86400000)):null;
 function select(kind:AdminAction){toggleMenu();onAdminAction(kind,poll)}
 const endText=poll.EndAt?new Date(poll.EndAt).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'';
 return <Card style={[s.card,menuOpen&&s.raised]}><Pressable accessibilityRole="link" accessibilityLabel={`Open ${poll.Question}`} onPress={open} style={[s.cardMain,isAdmin&&s.adminPadding]}><View style={s.cardTop}><View style={s.body}><View style={s.badgeLine}><Badge text={ended?'Completed':days===null?'Active':`Ends in ${days} day${days===1?'':'s'}`} tone="green"/></View><Text style={[s.question,{color:palette.text}]}>{poll.Question}</Text><Muted>Created on {new Date(poll.CreatedAt).toLocaleDateString()}</Muted></View>{!ended?<View style={s.rate}><Text style={[s.rateValue,{color:palette.success}]}>{participation}%</Text><Muted>participation</Muted></View>:null}</View><View style={s.meta}><View style={s.metaItem}><Ionicons name="people-outline" size={17} color={palette.text}/><Muted numberOfLines={1}>{voters} voter{voters===1?'':'s'}</Muted></View>{poll.EndAt?<View style={[s.metaItem,s.endMeta]}><Ionicons name="time-outline" size={17} color={palette.text}/><Muted numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.72}>{ended?'Ended':'Ends'} {endText}</Muted></View>:null}</View></Pressable>{isAdmin?<><Pressable accessibilityRole="button" accessibilityLabel="Manage poll" onPress={event=>{event.stopPropagation();toggleMenu()}} style={s.more}><Ionicons name="ellipsis-vertical" size={22} color={palette.success}/></Pressable>{menuOpen?<View onStartShouldSetResponder={()=>true} style={[s.menu,{backgroundColor:palette.surface,borderColor:palette.border}]}><MenuItem icon="create-outline" label="Edit" color={palette.text} onPress={()=>select('edit')}/>{!ended?<MenuItem icon="stop-circle-outline" label="Stop" color={palette.text} onPress={()=>select('stop')}/>:null}<MenuItem icon="trash-outline" label="Delete" color={palette.danger} onPress={()=>select('delete')}/></View>:null}</>:null}
  {mode==='active'&&!ended?<View style={s.participationBlock}><View style={[s.track,{backgroundColor:palette.backgroundSoft}]}><View style={[s.fill,{backgroundColor:palette.success,width:`${participation}%`}]}/></View><Muted>{participation}% participation ({voters} / {members||'—'} members)</Muted></View>:null}
  {mode==='completed'&&ended?<View style={s.results}>{poll.options.map(option=>{const count=Number(option.VoteCount||0),pct=total?Math.round(count/total*100):0;return <View key={option.Id} style={s.result}><Text numberOfLines={1} style={[s.resultLabel,{color:palette.text}]}>{option.OptionText}</Text><View style={[s.resultTrack,{backgroundColor:palette.backgroundSoft}]}><View style={[s.fill,{backgroundColor:palette.success,width:`${pct}%`}]}/></View><Text style={[s.resultValue,{color:palette.text}]}>{pct}% ({count})</Text></View>})}<Pressable onPress={open} style={s.details}><Text style={{color:palette.success,fontWeight:'900'}}>View Details</Text><Ionicons name="chevron-forward" size={18} color={palette.success}/></Pressable></View>:null}
 </Card>
}

function MenuItem({icon,label,color,onPress}:{icon:keyof typeof Ionicons.glyphMap;label:string;color:string;onPress:()=>void}){return <Pressable accessibilityRole="menuitem" onPress={onPress} style={s.menuItem}><Ionicons name={icon} size={19} color={color}/><Text style={{color,fontWeight:'800'}}>{label}</Text></Pressable>}

const s=StyleSheet.create({page:{width:'100%',maxWidth:900,alignSelf:'center',paddingBottom:125},searchRow:{flexDirection:'row',gap:9,marginBottom:12},search:{flex:1,minWidth:0,minHeight:52,borderWidth:1,borderRadius:12,flexDirection:'row',alignItems:'center',paddingLeft:12},searchInput:{flex:1,borderWidth:0,marginBottom:0,backgroundColor:'transparent'},filter:{minWidth:52,minHeight:52,borderWidth:1,borderRadius:12,paddingHorizontal:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},card:{padding:13,position:'relative',overflow:'visible'},raised:{zIndex:20,elevation:8},cardMain:{width:'100%'},cardTop:{flexDirection:'row',alignItems:'center'},adminPadding:{paddingRight:28},body:{flex:1,minWidth:0},badgeLine:{flexDirection:'row',alignItems:'center',minHeight:27},question:{fontSize:16,fontWeight:'900',lineHeight:21,marginVertical:4},meta:{flexDirection:'row',alignItems:'center',flexWrap:'nowrap',columnGap:18,marginTop:9,minWidth:0},metaItem:{flexDirection:'row',alignItems:'center',gap:6,flexShrink:0},endMeta:{flex:1,minWidth:0},rate:{width:74,alignItems:'center',flexShrink:0},rateValue:{fontSize:17,fontWeight:'900'},more:{position:'absolute',right:3,top:5,width:42,height:42,alignItems:'center',justifyContent:'center',zIndex:22},menu:{position:'absolute',right:9,top:43,width:142,borderWidth:1,borderRadius:12,paddingVertical:5,zIndex:30,elevation:12,shadowColor:'#000',shadowOpacity:.15,shadowRadius:8,shadowOffset:{width:0,height:4}},menuItem:{minHeight:43,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:10},participationBlock:{marginTop:11,gap:5},track:{height:7,borderRadius:5,overflow:'hidden'},fill:{height:'100%',borderRadius:5},results:{marginTop:12,gap:8},result:{flexDirection:'row',alignItems:'center',gap:8},resultLabel:{width:'32%',fontSize:13},resultTrack:{flex:1,height:7,borderRadius:5,overflow:'hidden'},resultValue:{width:68,textAlign:'right',fontSize:12,fontWeight:'800'},details:{minHeight:38,alignSelf:'flex-end',flexDirection:'row',alignItems:'center',gap:3},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.42)',alignItems:'center',justifyContent:'center',padding:20},modal:{width:'100%',maxWidth:480,borderWidth:1,borderRadius:18,padding:18,gap:10},modalTitleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},modalTitle:{fontSize:20,fontWeight:'900',textTransform:'capitalize'},label:{fontSize:14,fontWeight:'800',marginTop:4},description:{minHeight:90,textAlignVertical:'top'},modalButtons:{flexDirection:'row',alignItems:'center',gap:10,marginTop:6},continue:{flex:1}});
