import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, router } from 'expo-router';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { api } from '@/lib/api';
import { Badge, Button, Card, EmptyState, Muted, Screen } from '@/components/UI';
import { colors } from '@/theme';
import type { Poll } from '@/types';

export default function Polls(){const{id}=useLocalSearchParams<{id:string}>();const qc=useQueryClient();const{data=[]}=useQuery<Poll[]>({queryKey:['polls',id],queryFn:async()=>(await api.get(`/communities/${id}/polls`)).data});const vote=useMutation({mutationFn:async(v:{pollId:string,optionId:string})=>api.post(`/polls/${v.pollId}/vote`,{optionIds:[v.optionId]}),onSuccess:()=>qc.invalidateQueries({queryKey:['polls',id]}),onError:(e:any)=>Alert.alert('Unable to vote',e.response?.data?.error??e.message)});return <Screen scroll><View style={styles.nav}><Pressable onPress={()=>(router.canGoBack()?router.back():router.replace('/'))}><Ionicons name="chevron-back" size={24}/></Pressable><Text style={styles.navTitle}>Poll Details</Text><Pressable onPress={()=>router.push(`/community/${id}/manage`)}><Ionicons name="add" size={25} color={colors.primary}/></Pressable></View>{data.length?data.map(p=>{const total=p.options.reduce((n,o)=>n+o.VoteCount,0);return <Card key={p.Id}><View style={styles.status}><Badge text="Active" tone="green"/>{p.EndAt?<Muted>Closes {new Date(p.EndAt).toLocaleDateString()}</Muted>:null}</View><Text style={styles.question}>{p.Question}</Text>{p.Description?<Muted style={{marginTop:6}}>{p.Description}</Muted>:null}<View style={{marginTop:18}}>{p.options.map(o=>{const pct=total?Math.round(o.VoteCount/total*100):0;return <Pressable key={o.Id} onPress={()=>vote.mutate({pollId:p.Id,optionId:o.Id})} style={[styles.option,o.MyVote&&styles.optionSelected]}><View style={styles.optionTop}><Text style={styles.optionText}>{o.MyVote?'✓ ':''}{o.OptionText}</Text><Text style={styles.pct}>{pct}% <Text style={styles.votes}>({o.VoteCount} votes)</Text></Text></View><View style={styles.track}><View style={[styles.fill,{width:`${pct}%`}]}/></View></Pressable>})}</View><Text style={styles.total}>Total votes: {total}</Text>{p.options.some(o=>o.MyVote)&&p.AllowChangeVote?<Muted>Tap another option to change your vote.</Muted>:null}</Card>}):<EmptyState icon="stats-chart-outline" title="No polls yet" body="Community polls and votes will appear here."/>}</Screen>}
const styles=StyleSheet.create({nav:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',height:52,marginBottom:10},navTitle:{fontSize:18,fontWeight:'900',color:colors.text},status:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12},question:{fontSize:20,fontWeight:'900',color:colors.text,lineHeight:27},option:{borderWidth:1,borderColor:colors.border,borderRadius:14,padding:13,marginBottom:10},optionSelected:{borderColor:colors.primary,backgroundColor:colors.primarySoft},optionTop:{flexDirection:'row',justifyContent:'space-between',gap:10},optionText:{fontSize:13,fontWeight:'800',color:colors.text,flex:1},pct:{fontSize:12,fontWeight:'900',color:colors.text},votes:{fontWeight:'500',color:colors.muted},track:{height:7,borderRadius:5,backgroundColor:'#EEF0F4',overflow:'hidden',marginTop:10},fill:{height:'100%',backgroundColor:colors.primary,borderRadius:5},total:{fontSize:12,fontWeight:'800',color:colors.muted,marginTop:4,marginBottom:8}})
