import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, router } from 'expo-router';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { api } from '@/lib/api';
import { Avatar, Button, Card, EmptyState, Muted, Screen } from '@/components/UI';
import { colors } from '@/theme';
type JoinRequest={Id:string;UserId:string;FirstName:string;LastName:string;Email:string;ProfileImage?:string;Message?:string;CreatedAt:string};
export default function JoinRequests(){const{id}=useLocalSearchParams<{id:string}>();const qc=useQueryClient();const{data=[]}=useQuery<JoinRequest[]>({queryKey:['join-requests',id],queryFn:async()=>(await api.get(`/communities/${id}/join-requests`)).data});const review=useMutation({mutationFn:async(v:{requestId:string;decision:'APPROVE'|'REJECT'})=>(await api.post(`/communities/${id}/join-requests/${v.requestId}/review`,{decision:v.decision})).data,onSuccess:()=>{qc.invalidateQueries({queryKey:['join-requests',id]});qc.invalidateQueries({queryKey:['members',id]});},onError:(e:any)=>Alert.alert('Unable to review',e.response?.data?.error??e.message)});return <Screen scroll><View style={styles.header}><Pressable onPress={()=>(router.canGoBack()?router.back():router.replace('/'))}><Ionicons name="chevron-back" size={25}/></Pressable><Text style={styles.title}>Join Requests</Text><View style={{width:25}}/></View><Muted>Review people who have requested to join this community.</Muted>{data.length?data.map(r=><Card key={r.Id} style={styles.card}><Avatar name={`${r.FirstName} ${r.LastName}`} uri={r.ProfileImage}/><View style={{flex:1}}><Text style={styles.name}>{r.FirstName} {r.LastName}</Text><Muted>{r.Email}</Muted>{r.Message?<Text style={styles.message}>{r.Message}</Text>:null}<View style={styles.actions}><View style={{flex:1}}><Button title="Approve" onPress={()=>review.mutate({requestId:r.Id,decision:'APPROVE'})}/></View><Pressable style={styles.reject} onPress={()=>review.mutate({requestId:r.Id,decision:'REJECT'})}><Text style={styles.rejectText}>Reject</Text></Pressable></View></View></Card>):<EmptyState icon="person-add-outline" title="No pending requests" body="New requests to join this community will appear here."/>}</Screen>}
const styles=StyleSheet.create({header:{height:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:18,fontWeight:'900',color:colors.text},card:{flexDirection:'row',gap:12,alignItems:'flex-start'},name:{fontSize:16,fontWeight:'900',color:colors.text},message:{marginTop:8,color:colors.text},actions:{flexDirection:'row',gap:9,alignItems:'center',marginTop:10},reject:{paddingHorizontal:16,paddingVertical:12,borderWidth:1,borderColor:colors.danger,borderRadius:12},rejectText:{color:colors.danger,fontWeight:'800'}})
