import React,{useState} from 'react';
import {Alert,Image,Linking,Modal,Platform,Pressable,Share,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {useVideoPlayer,VideoView} from 'expo-video';
import {Muted,useAppTheme} from './UI';

export type Attachment={url:string;title?:string;mimeType?:string;posterName?:string;posterImage?:string;caption?:string;reactionCount?:number;commentCount?:number;shareCount?:number;liked?:boolean;saved?:boolean;onLike?:()=>void;onComment?:()=>void;onShare?:()=>void;onSave?:()=>void}|null;
function extension(url:string){try{return new URL(url).pathname.split('.').pop()?.toLowerCase()||''}catch{return url.split('?')[0].split('.').pop()?.toLowerCase()||''}}
function isImage(file:NonNullable<Attachment>){return file.mimeType?.startsWith('image/')||['jpg','jpeg','png','gif','webp','bmp','svg'].includes(extension(file.url))}
function isVideo(file:NonNullable<Attachment>){return file.mimeType?.startsWith('video/')||['mp4','webm','mov'].includes(extension(file.url))}

export function AttachmentPreview({attachment,onClose}:{attachment:Attachment;onClose:()=>void}){
 const{palette}=useAppTheme();const{width,height}=useWindowDimensions();
 if(!attachment)return null;
 const title=attachment.title||decodeURIComponent(attachment.url.split('/').pop()?.split('?')[0]||'Attachment');
 if(isImage(attachment)||isVideo(attachment))return <MediaViewer attachment={attachment} title={title} video={isVideo(attachment)} onClose={onClose}/>;
 const maxWidth=Math.min(Math.max(280,width-28),860),maxHeight=Math.min(Math.max(420,height-50),760);
 const save=()=>saveAttachment(attachment,title);
 const share=()=>shareAttachment(attachment,title);
 const preview=Platform.OS==='web'?React.createElement('iframe',{src:attachment.url,title,style:{width:'100%',height:'100%',border:'0',backgroundColor:'#fff'}}):<View style={styles.fallback}><Ionicons name="document-text-outline" size={64} color={palette.primary}/><Text numberOfLines={3} style={[styles.fallbackTitle,{color:palette.text}]}>{title}</Text><Muted style={styles.center}>Use Save to download or open this file with a compatible app.</Muted></View>;
 return <Modal visible transparent animationType="fade" statusBarTranslucent onRequestClose={onClose}><View style={styles.backdrop}><View accessibilityViewIsModal style={[styles.dialog,{width:maxWidth,height:maxHeight,backgroundColor:palette.surface,borderColor:palette.border}]}><View style={[styles.header,{borderBottomColor:palette.border}]}><Text numberOfLines={1} style={[styles.title,{color:palette.text}]}>{title}</Text><View style={styles.headerActions}><HeaderAction icon="share-social-outline" label="Share attachment" onPress={()=>void share()} color={palette.text}/><HeaderAction icon="download-outline" label="Save attachment" onPress={()=>void save()} color={palette.primary}/><HeaderAction icon="close" label="Close preview" onPress={onClose} color={palette.text}/></View></View><View style={[styles.viewer,{backgroundColor:palette.backgroundSoft}]}>{preview}</View></View></View></Modal>;
}

function MediaViewer({attachment,title,video,onClose}:{attachment:NonNullable<Attachment>;title:string;video:boolean;onClose:()=>void}){
 const[menu,setMenu]=useState(false);const{width,height}=useWindowDimensions();
 const share=()=>attachment.onShare?.()||shareAttachment(attachment,title),save=()=>saveAttachment(attachment,title);
 const comment=()=>{onClose();attachment.onComment?.()};
 return <Modal visible animationType="fade" presentationStyle="fullScreen" statusBarTranslucent onRequestClose={onClose}><View style={media.black}><View style={media.top}><HeaderAction icon="close" label="Close media" onPress={onClose} color="#fff"/><Text numberOfLines={1} style={media.mediaTitle}>{title}</Text><HeaderAction icon="share-social-outline" label="Share media" onPress={()=>void share()} color="#fff"/><HeaderAction icon="ellipsis-horizontal" label="Media options" onPress={()=>setMenu(true)} color="#fff"/></View><View style={media.stage}>{video?<FullscreenVideo uri={attachment.url} title={title}/>:<Image source={{uri:attachment.url}} resizeMode="contain" style={[media.image,{width,height:Math.max(260,height-150)}]} accessibilityLabel={title}/>}</View><View pointerEvents="box-none" style={media.social}><SocialAction icon={attachment.liked?'thumbs-up':'thumbs-up-outline'} count={attachment.reactionCount} label="Like" onPress={attachment.onLike}/><SocialAction icon="chatbubble-outline" count={attachment.commentCount} label="Comments" onPress={comment}/><SocialAction icon="share-social-outline" count={attachment.shareCount} label="Share" onPress={()=>void share()}/><SocialAction icon={attachment.saved?'bookmark':'bookmark-outline'} label="Save post" onPress={attachment.onSave}/></View><View style={media.postInfo}><View style={media.posterRow}>{attachment.posterImage?<Image source={{uri:attachment.posterImage}} style={media.avatar}/>:<View style={media.avatarFallback}><Ionicons name="person" size={18} color="#fff"/></View>}<Text numberOfLines={1} style={media.posterName}>{attachment.posterName||'Community member'}</Text></View>{attachment.caption?<Text numberOfLines={2} style={media.caption}>{attachment.caption}</Text>:null}<Pressable accessibilityRole="button" accessibilityLabel="Add a comment" onPress={comment} style={media.commentBox}><Text style={media.commentText}>Add a comment</Text><Ionicons name="send-outline" size={20} color="#fff"/></Pressable></View>{menu?<><Pressable accessibilityLabel="Close media options" onPress={()=>setMenu(false)} style={media.menuBackdrop}/><View style={media.sheet}><SheetAction label={video?'Save video':'Save photo'} onPress={()=>{setMenu(false);void save()}}/><SheetAction label="Copy link" onPress={()=>{setMenu(false);void copyLink(attachment.url)}}/><SheetAction label="Share" onPress={()=>{setMenu(false);void share()}}/><SheetAction label="Cancel" onPress={()=>setMenu(false)} separate/></View></>:null}</View></Modal>;
}

function SocialAction({icon,count,label,onPress}:{icon:keyof typeof Ionicons.glyphMap;count?:number;label:string;onPress?:()=>void}){return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={!onPress} onPress={onPress} style={media.socialAction}><Ionicons name={icon} size={29} color="#fff"/><Text style={media.socialCount}>{count??''}</Text></Pressable>}

function FullscreenVideo({uri,title}:{uri:string;title:string}){
 const[playing,setPlaying]=useState(false);const player=useVideoPlayer(uri,p=>{p.loop=false;p.muted=false});
 const toggle=()=>{if(playing)player.pause();else player.play();setPlaying(!playing)};
 const skip=(seconds:number)=>{player.currentTime=Math.max(0,player.currentTime+seconds)};
 return <View style={media.videoStage}><VideoView player={player} style={media.video} nativeControls={false} contentFit="contain" accessibilityLabel={title}/><View style={media.videoControls}><RoundAction icon="play-back-outline" label="Back 10 seconds" onPress={()=>skip(-10)}/><Pressable accessibilityRole="button" accessibilityLabel={playing?'Pause video':'Play video'} onPress={toggle} style={media.play}><Ionicons name={playing?'pause':'play'} size={34} color="#fff"/></Pressable><RoundAction icon="play-forward-outline" label="Forward 10 seconds" onPress={()=>skip(10)}/></View></View>;
}

function HeaderAction({icon,label,onPress,color}:{icon:keyof typeof Ionicons.glyphMap;label:string;onPress:()=>void;color:string}){return <Pressable accessibilityRole="button" accessibilityLabel={label} hitSlop={8} onPress={onPress} style={styles.headerAction}><Ionicons name={icon} size={23} color={color}/></Pressable>}
function RoundAction({icon,label,onPress}:{icon:keyof typeof Ionicons.glyphMap;label:string;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={media.round}><Ionicons name={icon} size={23} color="#fff"/></Pressable>}
function SheetAction({label,onPress,separate=false}:{label:string;onPress:()=>void;separate?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={[media.sheetAction,separate&&media.separate]}><Text style={media.sheetText}>{label}</Text></Pressable>}

async function saveAttachment(attachment:NonNullable<Attachment>,title:string){try{if(Platform.OS==='web'&&typeof document!=='undefined'){const link=document.createElement('a');link.href=attachment.url;link.download=title;link.target='_blank';link.rel='noopener';document.body.appendChild(link);link.click();link.remove();return}await Linking.openURL(attachment.url)}catch{Alert.alert('Unable to save file','The media could not be saved. Please try again.')}}
async function shareAttachment(attachment:NonNullable<Attachment>,title:string){try{if(Platform.OS==='web'&&typeof navigator!=='undefined'&&navigator.share){await navigator.share({title,url:attachment.url});return}await Share.share({title,message:attachment.url,url:attachment.url})}catch(error:any){if(error?.name!=='AbortError')Alert.alert('Unable to share','The media could not be shared. Please try again.')}}
async function copyLink(url:string){try{if(typeof navigator!=='undefined'&&navigator.clipboard){await navigator.clipboard.writeText(url);Alert.alert('Copied','Media link copied to clipboard.');return}await Share.share({message:url})}catch{Alert.alert('Unable to copy','The media link could not be copied.')}}

const styles=StyleSheet.create({backdrop:{flex:1,width:'100%',alignItems:'center',justifyContent:'center',padding:14,backgroundColor:'rgba(5,14,32,.72)'},dialog:{maxWidth:'100%',maxHeight:'94%',minHeight:360,borderWidth:1,borderRadius:20,overflow:'hidden',shadowColor:'#000',shadowOpacity:.3,shadowRadius:28,shadowOffset:{width:0,height:12},elevation:30},header:{minHeight:58,flexDirection:'row',alignItems:'center',gap:8,borderBottomWidth:1,paddingLeft:16,paddingRight:8},title:{flex:1,minWidth:0,fontSize:17,fontWeight:'900'},headerActions:{flexDirection:'row',alignItems:'center'},headerAction:{width:42,height:42,alignItems:'center',justifyContent:'center',borderRadius:21},viewer:{flex:1,minHeight:0,alignItems:'center',justifyContent:'center'},fallback:{alignItems:'center',justifyContent:'center',gap:14,padding:24},fallbackTitle:{maxWidth:'100%',fontSize:18,fontWeight:'900',textAlign:'center'},center:{textAlign:'center'}});
const media=StyleSheet.create({black:{flex:1,width:'100%',backgroundColor:'#000'},top:{position:'absolute',zIndex:5,top:0,left:0,right:0,minHeight:92,paddingTop:Platform.OS==='web'?36:48,paddingHorizontal:10,paddingBottom:8,flexDirection:'row',alignItems:'center',gap:2,backgroundColor:'rgba(0,0,0,.48)'},mediaTitle:{flex:1,minWidth:0,color:'#fff',fontSize:15,fontWeight:'900'},stage:{flex:1,alignItems:'center',justifyContent:'center'},image:{maxWidth:'100%'},videoStage:{width:'100%',height:'100%',alignItems:'center',justifyContent:'center'},video:{width:'100%',height:'100%'},videoControls:{position:'absolute',left:0,right:0,top:'45%',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:20},round:{width:46,height:46,borderRadius:23,backgroundColor:'rgba(0,0,0,.58)',alignItems:'center',justifyContent:'center'},play:{width:68,height:68,borderRadius:34,backgroundColor:'rgba(0,0,0,.68)',alignItems:'center',justifyContent:'center'},social:{position:'absolute',zIndex:5,right:10,bottom:112,alignItems:'center',gap:13},socialAction:{minWidth:48,minHeight:50,alignItems:'center',justifyContent:'center'},socialCount:{color:'#fff',fontSize:11,fontWeight:'700',marginTop:2,textShadowColor:'#000',textShadowRadius:3},postInfo:{position:'absolute',zIndex:4,left:14,right:66,bottom:14},posterRow:{flexDirection:'row',alignItems:'center',gap:9,marginBottom:6},avatar:{width:34,height:34,borderRadius:17,borderWidth:1,borderColor:'#fff'},avatarFallback:{width:34,height:34,borderRadius:17,backgroundColor:'#455',alignItems:'center',justifyContent:'center'},posterName:{flex:1,color:'#fff',fontSize:14,fontWeight:'900'},caption:{color:'#fff',fontSize:13,lineHeight:18,marginBottom:9,textShadowColor:'#000',textShadowRadius:4},commentBox:{height:44,borderRadius:22,borderWidth:1,borderColor:'rgba(255,255,255,.45)',backgroundColor:'rgba(12,12,12,.68)',paddingHorizontal:15,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},commentText:{color:'rgba(255,255,255,.82)',fontSize:13},menuBackdrop:{...StyleSheet.absoluteFillObject,zIndex:8,backgroundColor:'rgba(0,0,0,.25)'},sheet:{position:'absolute',zIndex:9,left:8,right:8,bottom:18,borderRadius:16,overflow:'hidden'},sheetAction:{minHeight:58,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(250,250,252,.96)',borderBottomWidth:1,borderBottomColor:'rgba(120,120,130,.25)'},separate:{marginTop:8,borderRadius:13,borderBottomWidth:0},sheetText:{color:'#087CFF',fontSize:17,fontWeight:'600'}});
