import {useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Modal,NativeModules,Pressable,StyleSheet,Text,View} from '@/platform/react-native';
import {Ionicons} from '@/platform/icons';
import {connectSocket,socket} from '../lib/socket';
import {useAppTheme} from './UI';

type Props={visible:boolean;conversationId:string;title:string;onEnd:()=>void};
const turnUrl=import.meta.env.EXPO_PUBLIC_TURN_URL;const rtcConfig={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'},...(turnUrl?[{urls:turnUrl,username:import.meta.env.EXPO_PUBLIC_TURN_USERNAME,credential:import.meta.env.EXPO_PUBLIC_TURN_CREDENTIAL}]:[])]};
let mediaDevices:any,RTCIceCandidate:any,RTCPeerConnection:any,RTCSessionDescription:any;let RTCView:any=()=>null;

export function InAppAudioCall({visible,conversationId,title,onEnd}:Props){
 const{palette}=useAppTheme();const[status,setStatus]=useState('Connecting…');const[muted,setMuted]=useState(false);const[remoteStreams,setRemoteStreams]=useState<Record<string,any>>({});const localRef=useRef<any>(null);const peersRef=useRef(new Map<string,any>());
 useEffect(()=>{if(!visible)return;let active=true;if(!(NativeModules as any).WebRTCModule){setStatus('Audio calls require the installed CDA Connect app. Chat remains available in Expo Go.');return()=>{active=false}}const rtc=require('react-native-webrtc');mediaDevices=rtc.mediaDevices;RTCIceCandidate=rtc.RTCIceCandidate;RTCPeerConnection=rtc.RTCPeerConnection;RTCSessionDescription=rtc.RTCSessionDescription;RTCView=rtc.RTCView;
  const closePeer=(id:string)=>{peersRef.current.get(id)?.close();peersRef.current.delete(id);setRemoteStreams(value=>{const next={...value};delete next[id];return next})};
  const peer=(id:string)=>{const existing=peersRef.current.get(id);if(existing)return existing;const pc=new RTCPeerConnection(rtcConfig);localRef.current?.getTracks().forEach((track:any)=>pc.addTrack(track,localRef.current!));pc.onicecandidate=(event:any)=>{if(event.candidate)socket.emit('call:signal',{conversationId,targetSocketId:id,signal:{candidate:event.candidate.toJSON()}})};pc.ontrack=(event:any)=>{const stream=event.streams?.[0];if(stream){setRemoteStreams(value=>({...value,[id]:stream}));setStatus('Connected')}};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))closePeer(id);else if(pc.connectionState==='connected')setStatus('Connected')};peersRef.current.set(id,pc);return pc};
  const offer=async(id:string)=>{const pc=peer(id);const description=await pc.createOffer();await pc.setLocalDescription(description);socket.emit('call:signal',{conversationId,targetSocketId:id,signal:{type:description.type,sdp:description.sdp}})};
  const onSignal=async({conversationId:cv,fromSocketId,signal}:{conversationId:string;fromSocketId:string;signal:any})=>{if(cv!==conversationId)return;try{const pc=peer(fromSocketId);if(signal.sdp&&signal.type){await pc.setRemoteDescription(new RTCSessionDescription(signal));if(signal.type==='offer'){const answer=await pc.createAnswer();await pc.setLocalDescription(answer);socket.emit('call:signal',{conversationId,targetSocketId:fromSocketId,signal:{type:answer.type,sdp:answer.sdp}})}}else if(signal.candidate)await pc.addIceCandidate(new RTCIceCandidate(signal.candidate))}catch{setStatus('Reconnecting…')}};
  const onJoined=({conversationId:cv,socketId}:{conversationId:string;socketId:string})=>{if(cv===conversationId)peer(socketId)};const onLeft=({conversationId:cv,socketId}:{conversationId:string;socketId:string})=>{if(cv===conversationId)closePeer(socketId)};
  void mediaDevices.getUserMedia({audio:true,video:false}).then((stream:any)=>{if(!active){stream.getTracks().forEach((track:any)=>track.stop());return}localRef.current=stream;connectSocket();socket.on('call:signal',onSignal);socket.on('call:participant-joined',onJoined);socket.on('call:participant-left',onLeft);socket.emit('call:join',{conversationId},(result:any)=>{if(!result?.ok){setStatus(result?.error||'Unable to connect');return}setStatus(result.peers?.length?'Connecting participants…':'Waiting for others…');for(const id of result.peers||[])void offer(id)})}).catch(()=>setStatus('Microphone permission is required'));
  return()=>{active=false;socket.emit('call:leave',{conversationId});socket.off('call:signal',onSignal);socket.off('call:participant-joined',onJoined);socket.off('call:participant-left',onLeft);peersRef.current.forEach(pc=>pc.close());peersRef.current.clear();localRef.current?.getTracks().forEach((track:any)=>track.stop());localRef.current=null;setRemoteStreams({})}
 },[visible,conversationId]);
 const toggleMute=()=>{const next=!muted;localRef.current?.getAudioTracks().forEach((track:any)=>{track.enabled=!next});setMuted(next)};const count=1+Object.keys(remoteStreams).length;
 return <Modal visible={visible} animationType="slide" presentationStyle="fullScreen" onRequestClose={onEnd} statusBarTranslucent><View style={[s.screen,{backgroundColor:palette.background}]}>{Object.entries(remoteStreams).map(([id,stream])=><RTCView key={id} streamURL={stream.toURL()} style={s.hiddenStream}/>) }<View style={s.center}><View style={[s.avatar,{backgroundColor:palette.primarySoft}]}><Ionicons name="people" size={54} color={palette.primary}/></View><Text style={[s.title,{color:palette.text}]}>{title}</Text><Text style={[s.status,{color:palette.muted}]}>{status}</Text><Text style={[s.participants,{color:palette.primary}]}>{count} participant{count===1?'':'s'}</Text>{status.includes('Connecting')?<ActivityIndicator color={palette.primary} style={{marginTop:18}}/>:null}</View><View style={s.controls}><Pressable accessibilityLabel={muted?'Unmute microphone':'Mute microphone'} onPress={toggleMute} style={[s.control,{backgroundColor:muted?palette.danger:palette.surface,borderColor:palette.border}]}><Ionicons name={muted?'mic-off':'mic'} size={25} color={muted?'#fff':palette.text}/></Pressable><Pressable accessibilityLabel="End call" onPress={onEnd} style={[s.control,s.end]}><Ionicons name="call" size={27} color="#fff"/></Pressable></View></View></Modal>
}
const s=StyleSheet.create({screen:{flex:1,justifyContent:'space-between',paddingVertical:60},hiddenStream:{width:1,height:1,position:'absolute',opacity:0},center:{flex:1,alignItems:'center',justifyContent:'center'},avatar:{width:116,height:116,borderRadius:58,alignItems:'center',justifyContent:'center'},title:{fontSize:25,fontWeight:'900',marginTop:22},status:{fontSize:14,marginTop:8},participants:{fontWeight:'800',marginTop:10},controls:{flexDirection:'row',justifyContent:'center',gap:26},control:{width:62,height:62,borderRadius:31,borderWidth:1,alignItems:'center',justifyContent:'center'},end:{backgroundColor:'#DC2626',borderWidth:0,transform:[{rotate:'135deg'}]}});
