import React,{useCallback,useRef,useState} from 'react';
import {ActivityIndicator,Image,Pressable,RefreshControl,ScrollView,StyleSheet,Switch,Text,TextInput,View,useColorScheme,useWindowDimensions,Platform,type NativeScrollEvent,type NativeSyntheticEvent,type PressableProps,type SwitchProps,type TextInputProps,type TextProps,type ViewStyle,type TextStyle,type StyleProp} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import {useQueryClient} from '@tanstack/react-query';
import { colors,darkColors,highContrastColors,typography } from '../theme';
import { textScaleValue,useAccessibility } from '../store/accessibility';
import {formatAmountInput,parseAmountInput} from '../lib/money';

export function useAppTheme(){const scheme=useColorScheme();const a=useAccessibility();const dark=a.themeMode==='dark'||(a.themeMode==='system'&&scheme==='dark');const base=a.highContrast||a.colorBlindFriendly?highContrastColors:dark?darkColors:colors;const palette={...base,primary:a.accentColor};return {palette,dark,scale:textScaleValue(a.textScale),prefs:a};}
const tx=(base:any,scale:number):TextStyle=>({...(base||{}),fontSize:typeof base?.fontSize==='number'?base.fontSize*scale:base?.fontSize,lineHeight:typeof base?.lineHeight==='number'?base.lineHeight*scale:base?.lineHeight});
export function AText({children,style,role='text',label}:{children:React.ReactNode;style?:any;role?:any;label?:string}){const{palette,scale,prefs}=useAppTheme();const flat=StyleSheet.flatten(style)||{};return <Text accessibilityRole={role} accessibilityLabel={label} allowFontScaling maxFontSizeMultiplier={1.8} style={[{color:palette.text,fontSize:typography.body*scale,lineHeight:Math.round(typography.body*typography.lineHeight*scale),fontWeight:prefs.boldText?'700':undefined},tx(flat,scale),style&&{...flat,color:flat.color??palette.text}]}>{children}</Text>}
export function useAppRefresh(onRefresh?:()=>Promise<void>|void){const qc=useQueryClient();const[refreshing,setRefreshing]=useState(false);const run=useCallback(async()=>{if(refreshing)return;setRefreshing(true);try{await onRefresh?.();await qc.refetchQueries({type:'active'});}finally{setRefreshing(false)}},[onRefresh,qc,refreshing]);return{refreshing,refresh:run}}
export function Screen({children,scroll=false,contentStyle,refreshable=true,onRefresh,onScroll}:{children:React.ReactNode;scroll?:boolean;contentStyle?:ViewStyle;refreshable?:boolean;onRefresh?:()=>Promise<void>|void;onScroll?:(event:NativeSyntheticEvent<NativeScrollEvent>)=>void}){const{palette,prefs}=useAppTheme();const{width}=useWindowDimensions();const{refreshing,refresh}=useAppRefresh(onRefresh);const web=Platform.OS==='web';const compact=width<480;const atTop=useRef(true),touchY=useRef<number|null>(null),pull=useRef(0);const content=<View style={[s.content,{paddingHorizontal:prefs.compactMode?8:compact?12:18,paddingTop:prefs.compactMode?4:8},web&&{width:'100%',maxWidth:1440,alignSelf:'center',paddingHorizontal:prefs.compactMode?12:compact?12:24},contentStyle]}>{children}</View>;return <SafeAreaView style={[s.safe,{backgroundColor:palette.background}]}>{scroll?<ScrollView showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" scrollEventThrottle={16} onScroll={e=>{atTop.current=e.nativeEvent.contentOffset.y<=1;onScroll?.(e)}} onTouchStart={e=>{if(web&&atTop.current)touchY.current=e.nativeEvent.pageY}} onTouchMove={e=>{if(web&&touchY.current!==null)pull.current=Math.max(0,e.nativeEvent.pageY-touchY.current)}} onTouchEnd={()=>{if(web&&refreshable&&atTop.current&&pull.current>=72)void refresh();touchY.current=null;pull.current=0}} refreshControl={refreshable?<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={palette.primary} colors={[palette.primary]} progressBackgroundColor={palette.surface}/>:undefined} contentContainerStyle={[s.scrollContent,web&&{width:'100%'}]}>{content}</ScrollView>:content}</SafeAreaView>}
export function Card({children,style}:{children:React.ReactNode;style?:StyleProp<ViewStyle>}){const{palette,prefs}=useAppTheme();const{width}=useWindowDimensions();return <View style={[s.card,{backgroundColor:palette.surface,borderColor:palette.border,borderRadius:prefs.roundCorners?16:4,padding:prefs.compactMode?10:width<480?13:16},style]}>{children}</View>}
export function Title({children}:{children:React.ReactNode}){const{palette,scale}=useAppTheme();return <Text accessibilityRole="header" allowFontScaling maxFontSizeMultiplier={1.6} style={[s.title,{color:palette.text,fontSize:typography.display*scale}]}>{children}</Text>}
export function SectionTitle({children,action}:{children:React.ReactNode;action?:React.ReactNode}){const{palette,scale}=useAppTheme();return <View style={s.sectionRow}><Text accessibilityRole="header" allowFontScaling maxFontSizeMultiplier={1.7} style={[s.sectionTitle,{color:palette.text,fontSize:typography.sectionTitle*scale}]}>{children}</Text>{action}</View>}
export function Muted({children,style,...props}:{children:React.ReactNode;style?:any}&TextProps){const{palette,scale,prefs}=useAppTheme();return <Text {...props} allowFontScaling maxFontSizeMultiplier={1.8} style={[s.muted,{color:palette.muted,fontSize:typography.body*scale,lineHeight:20*scale,fontWeight:prefs.boldText?'700':undefined},style]}>{children}</Text>}
export function Input(p:TextInputProps){const{palette,scale,prefs}=useAppTheme();return <TextInput allowFontScaling maxFontSizeMultiplier={1.6} placeholderTextColor={palette.muted} accessibilityLabel={p.accessibilityLabel??p.placeholder} {...p} style={[s.input,{backgroundColor:palette.surface,borderColor:palette.border,color:palette.text,fontSize:typography.body*scale,minHeight:prefs.largeTouchTargets?50:44},p.multiline&&s.multiline,p.style]}/>}
export function AmountInput({value,onChangeText,...props}:Omit<TextInputProps,'value'|'onChangeText'> & {value:string;onChangeText:(value:string)=>void}){return <Input {...props} value={formatAmountInput(value)} onChangeText={text=>onChangeText(parseAmountInput(text))} keyboardType="decimal-pad" inputMode="decimal"/>}
export function Button({title,loading,variant='primary',icon,...p}:{title:string;loading?:boolean;variant?:'primary'|'secondary'|'danger'|'success'|'ghost';icon?:keyof typeof Ionicons.glyphMap}&PressableProps){const{palette,scale,prefs}=useAppTheme();const outlined=variant==='secondary'||variant==='ghost',fg=outlined?palette.primary:'#fff',background=variant==='danger'?palette.danger:palette.primary,disabled=Boolean(p.disabled||loading);return <Pressable accessibilityRole="button" accessibilityLabel={p.accessibilityLabel??title} accessibilityState={{disabled,busy:Boolean(loading)}} {...p} disabled={disabled} style={({pressed})=>[s.button,{backgroundColor:background,minHeight:prefs.largeTouchTargets?48:44},outlined&&{backgroundColor:palette.surface,borderWidth:1,borderColor:palette.primary},pressed&&!disabled&&{opacity:.84,transform:[{scale:.985}]},disabled&&{backgroundColor:outlined?palette.surface:palette.disabled,borderColor:palette.muted,opacity:1}]}>{loading?<ActivityIndicator color={outlined?palette.primary:'#fff'}/>:<View style={s.buttonInner}>{icon&&<Ionicons name={icon} size={18} color={disabled?palette.muted:fg}/>}<Text allowFontScaling maxFontSizeMultiplier={1.5} style={[s.buttonText,{color:disabled?palette.muted:fg,fontSize:typography.body*scale}]}>{title}</Text></View>}</Pressable>}
export function ToggleSwitch({style,trackColor,...props}:SwitchProps){const{palette}=useAppTheme();return <View style={s.switchSlot}><Switch accessibilityRole="switch" {...props} trackColor={trackColor??{false:palette.border,true:palette.primary}} thumbColor="#fff" style={[s.compactSwitch,style]}/></View>}
export function IconTile({icon,label,onPress,tone='blue',bubbleSize=38}:{icon:keyof typeof Ionicons.glyphMap;label:string;onPress?:()=>void;tone?:'blue'|'red'|'green'|'orange'|'purple';bubbleSize?:number}){const{palette,scale,prefs}=useAppTheme();const fg={blue:palette.info,red:palette.danger,green:palette.success,orange:palette.orange,purple:palette.purple}[tone];const bg={blue:palette.infoLight,red:palette.dangerLight,green:palette.primaryLight,orange:palette.warningLight,purple:palette.purpleLight}[tone];return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={!onPress} onPress={onPress} style={({pressed})=>[s.iconTile,{minHeight:prefs.largeTouchTargets?70:60},pressed&&{opacity:.72,transform:[{scale:.98}]},!onPress&&{opacity:.55}]}><View style={[s.iconBubble,{backgroundColor:bg,width:bubbleSize,height:bubbleSize,borderRadius:Math.round(bubbleSize*.3)}]}><Ionicons name={icon} size={Math.round(bubbleSize*.52)} color={fg}/></View><Text allowFontScaling maxFontSizeMultiplier={1.5} numberOfLines={2} style={[s.iconLabel,{color:palette.text,fontSize:12*scale}]}>{label}</Text></Pressable>}
export function Avatar({name,size=44,backgroundColor,textColor='#fff',uri,borderWidth=0}:{name:string;size?:number;backgroundColor?:string;textColor?:string;uri?:string;borderWidth?:number}){const{palette}=useAppTheme();const initials=name.split(' ').filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'CDA',safeSize=Math.max(1,size),safeBorder=Math.max(0,Math.min(borderWidth,safeSize/2)),innerSize=Math.max(1,safeSize-safeBorder*2);return <View accessible accessibilityRole="image" accessibilityLabel={`${name} profile`} style={{width:safeSize,height:safeSize,borderRadius:safeSize/2,padding:safeBorder,overflow:'hidden',backgroundColor:'transparent',alignItems:'center',justifyContent:'center'}}><View style={{width:innerSize,height:innerSize,borderRadius:innerSize/2,overflow:'hidden',backgroundColor:backgroundColor??palette.primary,alignItems:'center',justifyContent:'center'}}>{uri?<Image source={{uri}} style={{width:innerSize,height:innerSize,borderRadius:innerSize/2}}/>:<Text style={{color:textColor,fontWeight:'800',fontSize:innerSize*.32}}>{initials}</Text>}</View></View>}
export function Badge({text,tone='blue'}:{text:string;tone?:'blue'|'green'|'red'|'orange'|'gray'}){const{palette,scale}=useAppTheme();const fg={blue:palette.infoText,green:palette.successText,red:palette.dangerText,orange:palette.warningText,gray:palette.muted}[tone];return <View style={[s.badge,{backgroundColor:palette.surface,borderColor:fg}]}><Text allowFontScaling style={[s.badgeText,{color:fg,fontSize:11*scale}]}>{text}</Text></View>}
export function MembershipStatusBadge({status='ACTIVE',compact=false}:{status?:string;compact?:boolean}){const active=String(status).trim().toUpperCase()==='ACTIVE';return <Badge text={compact?(active?'Active':'Inactive'):(active?'Active Member':'Inactive Member')} tone={active?'green':'gray'}/>}
export type TabBarItem<T extends string>={key:T;label:string;icon?:keyof typeof Ionicons.glyphMap;count?:number};
export function TabBar<T extends string>({items,value,onChange}:{items:readonly TabBarItem<T>[];value:T;onChange:(value:T)=>void}){const{palette,scale}=useAppTheme();return <View accessibilityRole="tablist" style={[s.tabBar,{borderBottomColor:palette.border}]}>{items.map(item=>{const active=item.key===value;const color=active?palette.primary:palette.muted;return <Pressable key={item.key} accessibilityRole="tab" accessibilityState={{selected:active}} accessibilityLabel={item.label} onPress={()=>onChange(item.key)} style={[s.tabBarItem,active&&{borderBottomColor:palette.primary}]}><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.72} style={[s.tabBarLabel,{color,fontSize:13*scale}]}>{item.label}</Text>{typeof item.count==='number'?<View style={[s.tabBarCount,{backgroundColor:active?palette.primary:palette.backgroundSoft}]}><Text style={[s.tabBarCountText,{color:active?'#fff':palette.muted}]}>{item.count}</Text></View>:null}</Pressable>})}</View>}
export function Header({title,subtitle,right,page=false}:{title:string;subtitle?:string;right?:React.ReactNode;page?:boolean}){const{palette,scale}=useAppTheme();const{width}=useWindowDimensions();const mobilePage=page&&width<980;return <View style={s.header}><View style={{flex:1,minWidth:mobilePage?0:180}}>{!mobilePage?<Text accessibilityRole="header" allowFontScaling maxFontSizeMultiplier={1.6} style={[s.headerTitle,{color:palette.text,fontSize:typography.pageTitle*scale}]}>{title}</Text>:null}{subtitle?<Text allowFontScaling maxFontSizeMultiplier={1.7} style={[s.headerSubtitle,mobilePage&&{marginTop:0},{color:palette.muted,fontSize:typography.body*scale}]}>{subtitle}</Text>:null}</View>{right}</View>}
export function EmptyState({icon='albums-outline',title,body}:{icon?:keyof typeof Ionicons.glyphMap;title:string;body:string}){const{palette}=useAppTheme();return <Card style={{alignItems:'center',paddingVertical:28}}><Ionicons name={icon} size={34} color={palette.primary}/><SectionTitle>{title}</SectionTitle><Muted style={{textAlign:'center',marginTop:6}}>{body}</Muted></Card>}
export const s=StyleSheet.create({safe:{flex:1,width:'100%',minWidth:0},content:{flex:1,width:'100%',maxWidth:'100%',minWidth:0,paddingTop:6},scrollContent:{flexGrow:1,width:'100%',maxWidth:'100%',paddingBottom:100},card:{width:'100%',maxWidth:'100%',minWidth:0,borderRadius:12,padding:12,borderWidth:1,marginBottom:8},title:{fontWeight:'800',letterSpacing:-.4,flexShrink:1},muted:{flexShrink:1},input:{width:'100%',maxWidth:'100%',minWidth:0,borderWidth:1,borderRadius:9,paddingHorizontal:12,paddingVertical:8,marginBottom:8},multiline:{minHeight:82,textAlignVertical:'top'},button:{maxWidth:'100%',minWidth:0,borderRadius:9,paddingVertical:6,paddingHorizontal:12,alignItems:'center',justifyContent:'center',marginVertical:4,overflow:'hidden'},buttonText:{fontWeight:'800',flexShrink:1,textAlign:'center'},buttonInner:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6,minWidth:0,maxWidth:'100%'},switchSlot:{width:52,minWidth:52,height:36,alignItems:'flex-end',justifyContent:'center',flexShrink:0,overflow:'visible'},compactSwitch:{transform:[{scale:Platform.OS==='ios'?.82:Platform.OS==='android'?.88:.86}]},sectionRow:{minWidth:0,flexDirection:'row',flexWrap:'wrap',gap:7,alignItems:'center',justifyContent:'space-between',marginTop:7,marginBottom:9},sectionTitle:{fontWeight:'800',flexShrink:1},iconTile:{flex:1,minWidth:56,maxWidth:'100%',alignItems:'center',justifyContent:'center',gap:5,paddingVertical:2,paddingHorizontal:2},iconBubble:{width:36,height:36,borderRadius:10,alignItems:'center',justifyContent:'center'},iconLabel:{fontWeight:'700',textAlign:'center',flexShrink:1},badge:{maxWidth:'100%',paddingHorizontal:8,paddingVertical:3,borderRadius:999,alignSelf:'flex-start',borderWidth:1},badgeText:{fontWeight:'800',flexShrink:1},tabBar:{width:'100%',minWidth:0,flexDirection:'row',borderBottomWidth:1,marginBottom:10},tabBarItem:{flex:1,minWidth:0,minHeight:42,borderBottomWidth:3,borderBottomColor:'transparent',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:4,paddingHorizontal:3},tabBarLabel:{fontWeight:'900',textAlign:'center',flexShrink:1},tabBarCount:{minWidth:18,height:18,borderRadius:9,alignItems:'center',justifyContent:'center',paddingHorizontal:4},tabBarCountText:{fontSize:9,fontWeight:'900'},header:{minWidth:0,maxWidth:'100%',flexDirection:'row',flexWrap:'wrap',gap:8,alignItems:'center',justifyContent:'space-between',marginBottom:12},headerTitle:{fontWeight:'800',letterSpacing:-.3,flexShrink:1},headerSubtitle:{marginTop:2,flexShrink:1}});
