import {useState} from 'react';
import {Alert,Image,ImageBackground,KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View,useWindowDimensions} from '@/platform/react-native';
import {router} from '@/router';
import {Ionicons} from '@/platform/icons';
import {SafeAreaView} from '@/platform/safe-area';
import {StatusBar} from '@/platform/status-bar';
import {api} from '@/lib/api';
import {useAuth} from '@/store/auth';
import {colors} from '@/theme';
import {completePendingCommunityInvite} from '@/lib/communityInvite';
import backgroundUrl from '../../assets/branding/login-community.png';
import logoUrl from '../../assets/branding/cda-connect-logo.png';
const background:any=backgroundUrl;
const logo:any=logoUrl;

function ImageDissolve(){return <View pointerEvents="none" style={(s as any).dissolve}>{[.08,.18,.32,.5,.7,.86,.96,1].map((opacity,i)=><View key={i} style={{flex:1,backgroundColor:colors.background,opacity}}/>)}</View>}

export default function Login(){
 const{width}=useWindowDimensions();const desktop=width>=768;const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[showPassword,setShowPassword]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[challenge,setChallenge]=useState('');const[method,setMethod]=useState('');const[code,setCode]=useState('');const setSession=useAuth(s=>s.setSession);
 async function finishLogin(data:any){await setSession(data.user,data.accessToken,data.refreshToken);const joined=await completePendingCommunityInvite().catch(()=>null);router.replace(joined?`/community/${joined.Id}` as any:'/(tabs)/home')}
 async function submit(){const cleanEmail=email.trim().toLowerCase();setError('');if(!/^\S+@\S+\.\S+$/.test(cleanEmail)){setError('Enter a valid email address.');return}if(!password){setError('Enter your password.');return}try{setLoading(true);const r=await api.post('/auth/login',{email:cleanEmail,password});if(r.data.requiresTwoFactor){setChallenge(r.data.challengeToken);setMethod(r.data.method);setCode('');return}await finishLogin(r.data)}catch(e:any){setError(e.response?.data?.error??(e.code==='ERR_NETWORK'?'Cannot connect to the CDA Connect server.':'Login failed. Please try again.'))}finally{setLoading(false)}}
 async function verifyTwoFactor(){if(!/^\d{6}$/.test(code)){setError('Enter the six-digit verification code.');return}try{setLoading(true);setError('');const r=await api.post('/auth/login/two-factor',{challengeToken:challenge,code});await finishLogin(r.data)}catch(e:any){setError(e.response?.data?.error??'Verification failed.')}finally{setLoading(false)}}
 const forgot=()=>router.push('/(auth)/forgot-password' as any);
 if(Platform.OS==='web')return <main className="auth-web-page">
  <section className="auth-web-hero" style={{backgroundImage:`url(${backgroundUrl})`}} aria-label="A connected residential community">
   <button className="auth-web-back" aria-label="Back" onClick={()=>router.canGoBack()?router.back():router.replace('/')}><Ionicons name="chevron-back" size={27} color={colors.textPrimary}/></button>
   <div className="auth-web-hero-copy"><h2>Your community,<br/>connected.</h2><p>Updates, conversations, events and decisions—all together in one secure place.</p></div>
  </section>
  <section className="auth-web-panel"><div className="auth-web-form">
   <h1>{challenge?'Verify it’s you':'Welcome back!'}</h1>
   <p className="auth-web-subtitle">{challenge?(method==='sms'?'Enter the code sent to your verified phone.':'Enter the current code from your authenticator app.'):'Sign in to your CDA Connect account and continue building stronger communities.'}</p>
   {challenge?<>
    <label htmlFor="login-code">Verification code</label><input id="login-code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} onKeyDown={e=>e.key==='Enter'&&void verifyTwoFactor()} placeholder="000000"/>
    {error?<p className="auth-web-error" role="alert">{error}</p>:null}
    <button className="auth-web-primary" disabled={loading} onClick={()=>void verifyTwoFactor()}>{loading?'Verifying…':'Verify & Log in'}</button>
    <button className="auth-web-link" onClick={()=>{setChallenge('');setCode('');setError('')}}>Use a different account</button>
   </>:<>
    <label htmlFor="login-email">Email address</label><input id="login-email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void submit()} placeholder="you@example.com"/>
    <label htmlFor="login-password">Password</label><div className="auth-web-password"><input id="login-password" type={showPassword?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void submit()} placeholder="Enter your password"/><button aria-label={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(v=>!v)}><Ionicons name={showPassword?'eye-off-outline':'eye-outline'} size={23} color={colors.textSecondary}/></button></div>
    <button className="auth-web-forgot" onClick={forgot}>Forgot password?</button>{error?<p className="auth-web-error" role="alert">{error}</p>:null}
    <button className="auth-web-primary" disabled={loading} onClick={()=>void submit()}>{loading?'Signing in…':'Log in'}</button>
    <p className="auth-web-alt">Don’t have an account? <a href="/onboarding">Sign up</a></p>
   </>}
  </div></section>
 </main>;
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView style={s.scroll} contentContainerStyle={[s.shell,desktop&&s.webShell]} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
  <ImageBackground source={background} resizeMode="cover" style={[s.hero,desktop&&(s as any).desktopHero]} imageStyle={s.heroImage}><View style={s.heroWash}/>{!desktop?<ImageDissolve/>:null}<Pressable accessibilityLabel="Back" onPress={()=>(router.canGoBack()?router.back():router.replace('/'))} style={s.back}><Ionicons name="chevron-back" size={27} color={colors.textPrimary}/></Pressable><View style={[s.logoFrame,desktop&&(s as any).desktopLogo]}><Image source={logo} resizeMode="contain" style={s.logo}/></View>{desktop?<View style={(s as any).desktopHeroCopy}><Text style={(s as any).desktopHeroTitle}>Your community,{`\n`}connected.</Text><Text style={(s as any).desktopHeroText}>Updates, conversations, events and decisions—all together in one secure place.</Text></View>:null}</ImageBackground>
  <View style={[s.content,desktop&&(s as any).desktopContent]}>
   <Text accessibilityRole="header" style={s.title}>{challenge?'Verify it’s you':'Welcome back!'}</Text><Text style={s.subtitle}>{challenge?(method==='sms'?'Enter the code sent to your verified phone.':'Enter the current code from your authenticator app.'):`Sign in to your CDA Connect account\nand continue building stronger communities.`}</Text>
   {challenge?<><Text style={s.label}>Verification code</Text><View style={s.inputWrap}><Ionicons name="shield-checkmark-outline" size={22} color={colors.textSecondary}/><TextInput accessibilityLabel="Verification code" value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} placeholder="000000" placeholderTextColor={colors.textMuted} keyboardType="number-pad" maxLength={6} returnKeyType="done" onSubmitEditing={verifyTwoFactor} style={[s.input,{fontSize:23,fontWeight:'900',letterSpacing:7,textAlign:'center'}]}/></View>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}<Pressable accessibilityRole="button" disabled={loading} onPress={verifyTwoFactor} style={({pressed})=>[s.loginButton,pressed&&s.loginPressed,loading&&s.loginDisabled]}><Text style={s.loginText}>{loading?'Verifying…':'Verify & Log in'}</Text></Pressable><Pressable onPress={()=>{setChallenge('');setCode('');setError('')}} style={s.signup}><Text style={s.signupLink}>Use a different account</Text></Pressable></>:
   <>
   <Text style={s.label}>Email address</Text><View style={[s.inputWrap,error&&email&&!/^\S+@\S+\.\S+$/.test(email)&&s.inputError]}><Ionicons name="mail-outline" size={22} color={colors.textSecondary}/><TextInput accessibilityLabel="Email address" value={email} onChangeText={setEmail} placeholder="you@example.com" placeholderTextColor={colors.textMuted} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" returnKeyType="next" style={s.input}/></View>
   <Text style={s.label}>Password</Text><View style={s.inputWrap}><Ionicons name="lock-closed-outline" size={22} color={colors.textSecondary}/><TextInput accessibilityLabel="Password" value={password} onChangeText={setPassword} placeholder="Enter your password" placeholderTextColor={colors.textMuted} secureTextEntry={!showPassword} returnKeyType="done" onSubmitEditing={submit} style={s.input}/><Pressable accessibilityLabel={showPassword?'Hide password':'Show password'} onPress={()=>setShowPassword(v=>!v)} style={s.eye}><Ionicons name={showPassword?'eye-off-outline':'eye-outline'} size={24} color={colors.textSecondary}/></Pressable></View>
   <Pressable onPress={forgot} style={s.forgot}><Text style={s.forgotText}>Forgot password?</Text></Pressable>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}
   <Pressable accessibilityRole="button" disabled={loading} onPress={submit} style={({pressed})=>[s.loginButton,pressed&&s.loginPressed,loading&&s.loginDisabled]}><Text style={s.loginText}>{loading?'Signing in…':'Log in'}</Text></Pressable>
   <Pressable accessibilityRole="button" onPress={()=>router.push('/(auth)/onboarding' as any)} style={s.signup}><Text style={s.signupText}>Don’t have an account? <Text style={s.signupLink}>Sign up</Text></Text></Pressable></>}
  </View>
 </ScrollView></KeyboardAvoidingView></SafeAreaView>
}

const s=StyleSheet.create({safe:{flex:1,width:'100%',backgroundColor:colors.backgroundSoft},flex:{flex:1,width:'100%'},scroll:{flex:1,width:'100%'},shell:{flexGrow:1,width:'100%',backgroundColor:colors.white},webShell:{maxWidth:520,alignSelf:'center',marginVertical:18,borderRadius:32,overflow:'hidden',borderWidth:1,borderColor:colors.border},hero:{height:330,width:'100%'},heroImage:{width:'100%',height:'100%'},heroWash:{...StyleSheet.absoluteFill,backgroundColor:'rgba(255,255,255,.16)'},back:{position:'absolute',top:18,left:20,width:44,height:44,borderRadius:22,backgroundColor:'rgba(255,255,255,.84)',alignItems:'center',justifyContent:'center'},logoFrame:{position:'absolute',left:'50%',marginLeft:-73,bottom:42,width:146,height:146,borderRadius:73,backgroundColor:'#fff',overflow:'hidden',alignItems:'center',justifyContent:'center',shadowColor:colors.textPrimary,shadowOpacity:.18,shadowRadius:20,shadowOffset:{width:0,height:8},elevation:8},logo:{width:'100%',height:'100%',transform:[{scale:1.48}]},content:{flex:1,marginTop:-32,borderTopLeftRadius:38,borderTopRightRadius:38,backgroundColor:colors.white,paddingHorizontal:30,paddingTop:35,paddingBottom:30},title:{fontSize:35,lineHeight:43,fontWeight:'900',textAlign:'center',color:colors.primaryDark},subtitle:{fontSize:16,lineHeight:25,textAlign:'center',color:colors.textSecondary,marginTop:8,marginBottom:24},label:{fontSize:14,fontWeight:'800',color:colors.textPrimary,marginBottom:8,marginTop:13},inputWrap:{minHeight:58,borderWidth:1.5,borderColor:colors.border,borderRadius:14,backgroundColor:colors.white,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:12},inputError:{borderColor:colors.danger},input:{flex:1,minWidth:0,fontSize:16,color:colors.textPrimary,paddingVertical:15,outlineStyle:'none' as any},eye:{width:42,height:50,alignItems:'center',justifyContent:'center'},forgot:{alignSelf:'flex-end',paddingVertical:14},forgotText:{fontSize:14,fontWeight:'800',color:colors.primary},error:{fontSize:13,fontWeight:'700',color:colors.danger,marginBottom:10},loginButton:{minHeight:58,borderRadius:14,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',marginTop:5,shadowColor:colors.primaryDark,shadowOpacity:.15,shadowRadius:9,shadowOffset:{width:0,height:4},elevation:3},loginPressed:{backgroundColor:colors.primaryDark,transform:[{scale:.99}]},loginDisabled:{backgroundColor:colors.disabled},loginText:{fontSize:18,fontWeight:'800',color:'#fff'},signup:{minHeight:58,alignItems:'center',justifyContent:'center',marginTop:17},signupText:{fontSize:15,fontWeight:'600',color:colors.textSecondary},signupLink:{fontWeight:'900',color:colors.primary}});
Object.assign(s,{shell:{flexGrow:1,width:'100%',backgroundColor:colors.background},heroWash:{...StyleSheet.absoluteFill,backgroundColor:'rgba(255,255,255,.1)'},dissolve:{position:'absolute',left:0,right:0,bottom:0,height:112},back:{position:'absolute',top:18,left:20,width:44,height:44,borderRadius:22,backgroundColor:'rgba(247,245,240,.84)',alignItems:'center',justifyContent:'center'},logoFrame:{position:'absolute',left:'50%',marginLeft:-60,bottom:40,width:120,height:120,alignItems:'center',justifyContent:'center'},logo:{width:'100%',height:'100%'},content:{flex:1,marginTop:-58,borderTopLeftRadius:38,borderTopRightRadius:38,backgroundColor:colors.background,paddingHorizontal:30,paddingTop:58,paddingBottom:30}});
Object.assign(s,{webShell:{flexGrow:0,width:'100%',maxWidth:1240,height:'100vh',alignSelf:'center',flexDirection:'row',overflow:'hidden',borderLeftWidth:1,borderRightWidth:1,borderColor:colors.border},desktopHero:{flex:0,width:'54%',height:'100vh',minHeight:0,justifyContent:'flex-end'},desktopLogo:{left:46,top:38,bottom:'auto',marginLeft:0,width:76,height:76,backgroundColor:'rgba(255,255,255,.92)',borderRadius:22},desktopHeroCopy:{zIndex:4,padding:54,maxWidth:600},desktopHeroTitle:{fontSize:48,lineHeight:56,fontWeight:'900',color:'#fff',textShadowColor:'rgba(0,0,0,.3)',textShadowRadius:10},desktopHeroText:{fontSize:17,lineHeight:27,fontWeight:'700',color:'#F2FFF6',marginTop:15},desktopContent:{flex:0,width:'46%',height:'100vh',minHeight:0,marginTop:0,borderTopLeftRadius:0,borderTopRightRadius:0,paddingHorizontal:64,paddingTop:48,paddingBottom:48,justifyContent:'center',overflow:'auto'}} as any);
