import {Image,Platform,Pressable,ScrollView,StyleSheet,Text,View,useWindowDimensions} from '@/platform/react-native';
import {router} from '@/router';
import {StatusBar} from '@/platform/status-bar';
import {SafeAreaView} from '@/platform/safe-area';
import {Ionicons} from '@/platform/icons';
import {colors} from '@/theme';
import illustrationUrl from '../../assets/branding/onboarding-community-transparent.png';
const illustration:any=illustrationUrl;

const features=[
  ['people-outline','Stay informed','Get the latest updates and announcements.'],
  ['documents-outline','Work together','Join meetings, make decisions and take action.'],
  ['git-network-outline','Build stronger communities','Connect, support and grow together.'],
];

export default function Onboarding(){
 const{width}=useWindowDimensions();const desktop=width>=768;const proceed=()=>router.push('/(auth)/register');
 if(Platform.OS==='web')return <main className="onboarding-web-page"><section className="onboarding-web-intro"><div><p className="onboarding-web-eyebrow">Welcome to</p><h1>CDA Connect</h1><p className="onboarding-web-lead">The all-in-one platform for communities to connect, collaborate and grow together.</p></div><Image source={illustration} resizeMode="contain" style={{width:'100%',height:390}}/><a className="onboarding-web-home" href="/">Back Home</a></section><section className="onboarding-web-card"><div><p className="onboarding-web-label">WHY CDA CONNECT</p><h2>One place for everything that matters.</h2><p className="onboarding-web-body">Designed around the way real communities communicate, organise and grow.</p>{features.map(([icon,title,body])=><div className="onboarding-web-feature" key={title}><span><Ionicons name={icon as any} size={25} color={colors.primary}/></span><div><h3>{title}</h3><p>{body}</p></div></div>)}<a className="onboarding-web-primary" href="/register">Create your account <Ionicons name="arrow-forward" size={20} color="#fff"/></a></div></section></main>;
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><ScrollView style={s.scroll} contentContainerStyle={[s.page,desktop&&s.desktopPage]} showsVerticalScrollIndicator={false}>
  <View style={[s.main,desktop&&s.desktopMain]}><View style={[s.introColumn,desktop&&s.desktopIntroColumn]}><View><Text style={[s.eyebrow,desktop&&s.desktopEyebrow]}>Welcome to</Text><Text style={[s.title,desktop&&s.desktopTitle]}>CDA Connect</Text><Text style={[s.intro,desktop&&s.desktopIntro]}>The all-in-one platform for communities to connect, collaborate and grow together.</Text></View><Image source={illustration} resizeMode="contain" style={[s.image,desktop&&s.desktopImage]}/></View>
  <View style={[s.featurePanel,desktop&&s.desktopFeaturePanel]}>{desktop?<><Text style={s.panelEyebrow}>WHY CDA CONNECT</Text><Text style={s.panelTitle}>One place for everything that matters.</Text><Text style={s.panelBody}>Designed around the way real communities communicate, organise and grow.</Text></>:null}{features.map(([icon,title,body])=><View key={title} style={[s.feature,desktop&&s.desktopFeature]}><View style={[s.icon,desktop&&s.desktopIcon]}><Ionicons name={icon as any} size={26} color={colors.primary}/></View><View style={{flex:1}}><Text style={[s.featureTitle,desktop&&s.desktopFeatureTitle]}>{title}</Text><Text style={s.featureBody}>{body}</Text></View></View>)}{desktop?<Pressable onPress={proceed} accessibilityRole="button" style={s.desktopPrimary}><Text style={s.desktopPrimaryText}>Create your account</Text><Ionicons name="arrow-forward" size={20} color="#fff"/></Pressable>:null}</View></View>
  <View style={s.footer}><Pressable onPress={()=>router.replace('/')} accessibilityRole="button" accessibilityLabel="Back home"><Text style={s.link}>Back Home</Text></Pressable>{!desktop?<Pressable onPress={proceed} accessibilityRole="button"><Text style={s.link}>Next</Text></Pressable>:null}</View>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,width:'100%',backgroundColor:colors.background},scroll:{flex:1,width:'100%',backgroundColor:colors.background},page:{flexGrow:1,width:'100%',backgroundColor:colors.background,paddingHorizontal:30,paddingTop:58,paddingBottom:24,isolation:'isolate' as any},desktopPage:{paddingHorizontal:64,paddingTop:44,paddingBottom:32,maxWidth:1500,alignSelf:'center'},main:{width:'100%'},desktopMain:{flex:1,flexDirection:'row',alignItems:'stretch',gap:42,maxWidth:1320,alignSelf:'center'},introColumn:{width:'100%'},desktopIntroColumn:{width:'52%',justifyContent:'center'},eyebrow:{fontSize:27,fontWeight:'800',color:colors.primary},desktopEyebrow:{fontSize:31},title:{fontSize:40,lineHeight:48,fontWeight:'900',color:colors.textPrimary},desktopTitle:{fontSize:62,lineHeight:70,letterSpacing:-1.5},intro:{fontSize:17,lineHeight:28,fontWeight:'600',color:colors.textSecondary,marginTop:20,maxWidth:430},desktopIntro:{fontSize:20,lineHeight:32,maxWidth:620},image:{width:'100%',height:210,marginTop:12},desktopImage:{height:390,marginTop:30},featurePanel:{borderTopWidth:2,borderTopColor:colors.primaryLight,borderTopLeftRadius:28,borderTopRightRadius:28,paddingTop:22,gap:19},desktopFeaturePanel:{width:'39%',marginRight:32,borderTopWidth:0,borderRadius:30,backgroundColor:colors.surface,padding:40,justifyContent:'center',shadowColor:colors.textPrimary,shadowOpacity:.08,shadowRadius:30,shadowOffset:{width:0,height:12}},panelEyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.4,color:colors.primary},panelTitle:{fontSize:30,lineHeight:38,fontWeight:'900',color:colors.textPrimary,marginTop:10},panelBody:{fontSize:15,lineHeight:24,color:colors.textSecondary,marginBottom:14},feature:{flexDirection:'row',alignItems:'center',gap:16},desktopFeature:{paddingVertical:7},icon:{width:54,height:54,borderRadius:16,backgroundColor:'#FFFFFF',alignItems:'center',justifyContent:'center'},desktopIcon:{backgroundColor:colors.primaryLight},featureTitle:{fontSize:16,fontWeight:'800',color:colors.textPrimary},desktopFeatureTitle:{fontSize:17},featureBody:{fontSize:14,lineHeight:21,color:colors.textSecondary,marginTop:3},desktopPrimary:{height:58,borderRadius:14,backgroundColor:colors.primary,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10,marginTop:18},desktopPrimaryText:{fontSize:16,fontWeight:'900',color:'#fff'},footer:{marginTop:'auto',paddingTop:28,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},link:{fontSize:17,fontWeight:'800',color:colors.primary}});
