import React from 'react';
import {ActivityIndicator,Image,Linking,Platform,StyleSheet,Text,View} from 'react-native';
import {useLocalSearchParams} from 'expo-router';
import {useQuery} from '@tanstack/react-query';
import {Ionicons} from '@expo/vector-icons';
import {VideoView,useVideoPlayer} from 'expo-video';
import {WebView} from 'react-native-webview';
import {api} from '@/lib/api';
import {useAuth} from '@/store/auth';
import {Button,EmptyState,Header,Muted,Screen,useAppTheme} from '@/components/UI';

type DocumentData={Id:string;Title:string;FileName?:string;MimeType?:string;SizeBytes?:number;Visibility:string};
type SecureSource={uri:string;headers:Record<string,string>};
const fileExtension=(name?:string)=>String(name||'').split('?')[0].split('.').pop()?.toLowerCase()||'';
export default function DocumentViewer(){const{documentId,title}=useLocalSearchParams<{id:string;documentId:string;title?:string}>(),{palette}=useAppTheme(),accessToken=useAuth(s=>s.accessToken);const document=useQuery<DocumentData>({queryKey:['document',documentId],queryFn:async()=>(await api.get(`/documents/${documentId}`)).data});const download=useQuery<{url:string}>({queryKey:['document-download',documentId],queryFn:async()=>(await api.post(`/documents/${documentId}/download-url`)).data,enabled:!!document.data,retry:1});const data=document.data,url=download.data?.url,name=data?.FileName||data?.Title||String(title||'Document'),mime=data?.MimeType||'',extension=fileExtension(name),image=mime.startsWith('image/')||['jpg','jpeg','png','gif','webp'].includes(extension),video=mime.startsWith('video/')||['mp4','mov','webm'].includes(extension),pdf=mime==='application/pdf'||extension==='pdf',office=['doc','docx','xls','xlsx','ppt','pptx'].includes(extension),headers:Record<string,string>=accessToken?{Authorization:`Bearer ${accessToken}`}: {},source:SecureSource|undefined=url?{uri:url,headers}:undefined;return <Screen contentStyle={s.page}><Header page title={data?.Title||String(title||'Document')} subtitle={data?.FileName||'Community document'}/>{document.isLoading||download.isLoading?<View style={s.center}><ActivityIndicator size="large" color={palette.primary}/><Muted>Opening document…</Muted></View>:document.isError||download.isError||!url||!source?<EmptyState icon="document-outline" title="Document unavailable" body="This file may have been removed, or your access may have changed."/>:<View style={[s.viewer,{backgroundColor:palette.surface,borderColor:palette.border}]}>{image?<Image source={source} resizeMode="contain" style={s.media}/>:video?<DocumentVideo uri={url}/>:pdf?<DocumentWeb source={source} title={name}/>:office?<OpenDocument name={name} url={url} palette={palette}/>:<OpenDocument name={name} url={url} palette={palette}/>}</View>}</Screen>}
function DocumentWeb({source,title}:{source:SecureSource;title:string}){if(Platform.OS==='web')return React.createElement('iframe',{src:source.uri,title,style:{width:'100%',height:'100%',border:'0',backgroundColor:'#fff'}});return <WebView source={source} originWhitelist={['*']} startInLoadingState style={s.media} renderLoading={()=><View style={s.center}><ActivityIndicator size="large"/></View>}/>}
function OpenDocument({name,url,palette}:{name:string;url:string;palette:any}){return <View style={s.center}><Ionicons name="document-text-outline" size={72} color={palette.primary}/><Text style={[s.fileName,{color:palette.text}]}>{name}</Text><Muted>Open this document with an application installed on your device.</Muted><Button title="Open file" icon="open-outline" onPress={()=>void Linking.openURL(url)}/></View>}
function DocumentVideo({uri}:{uri:string}){const player=useVideoPlayer(uri,instance=>{instance.loop=false});return <VideoView player={player} nativeControls contentFit="contain" style={s.media}/>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1100,alignSelf:'center',paddingBottom:90},viewer:{flex:1,minHeight:420,borderWidth:1,borderRadius:16,overflow:'hidden'},media:{width:'100%',height:'100%',flex:1,backgroundColor:'#fff'},center:{flex:1,minHeight:320,alignItems:'center',justifyContent:'center',gap:14,padding:24},fileName:{fontSize:18,fontWeight:'900',textAlign:'center'}});
