import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from '@/platform/react-native';
import { useLocalSearchParams } from '@/router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@/platform/icons';
import { api } from '@/lib/api';
import { Avatar, Badge, Button, Card, EmptyState, Header, Muted, Screen, TabBar, useAppTheme } from '@/components/UI';
import { AttachmentPreview, type Attachment } from '@/components/AttachmentPreview';
import { formatAmount } from '@/lib/money';

type Tab = 'paid' | 'pending' | 'unpaid';
export default function LevyDetail() {
  const { id, planId } = useLocalSearchParams<{ id: string; planId: string }>(); const { palette } = useAppTheme(); const qc = useQueryClient(); const [tab, setTab] = useState<Tab>('pending'); const [preview, setPreview] = useState<Attachment>(null);
  const query = useQuery<any>({ queryKey: ['levy-detail', id, planId], queryFn: async () => (await api.get(`/communities/${id}/finance/levies/${planId}`)).data });
  const review = useMutation({ mutationFn: (value: { sid: string; action: 'APPROVE' | 'REJECT' }) => api.patch(`/communities/${id}/finance/payment-submissions/${value.sid}`, { action: value.action }), onSuccess: () => qc.invalidateQueries({ queryKey: ['levy-detail', id, planId] }), onError: (error: any) => Alert.alert('Review failed', error.response?.data?.message || error.message) });
  const rows = (query.data?.members || []).filter((member: any) => tab === 'paid' ? member.Status === 'PAID' : tab === 'pending' ? member.SubmissionStatus === 'PENDING' : member.Status !== 'PAID' && member.SubmissionStatus !== 'PENDING');
  return <Screen scroll contentStyle={styles.page}><Header page title={query.data?.plan?.Name || 'Levy details'} subtitle="Review member payment status and evidence" /><Card><Text adjustsFontSizeToFit numberOfLines={1} style={[styles.amount, { color: palette.success }]}>{query.data?.plan?.CurrencyCode} {formatAmount(query.data?.plan?.Amount)}</Text><Muted>{query.data?.plan?.Description}</Muted></Card><TabBar value={tab} onChange={setTab} items={[{key:'paid',label:'All Paid Members',icon:'checkmark-circle-outline'},{key:'pending',label:'Pending',icon:'time-outline'},{key:'unpaid',label:'Not Yet Paid',icon:'alert-circle-outline'}]}/>{!rows.length ? <EmptyState icon="people-outline" title="No members in this status" body="Member payment activity will appear here." /> : rows.map((member: any) => <Card key={member.Id}><View style={styles.row}><Avatar name={`${member.FirstName} ${member.LastName}`} uri={member.ProfileImage} size={48} /><View style={styles.flex}><Text style={{ color: palette.text, fontWeight: '900' }}>{member.FirstName} {member.LastName}</Text><View style={styles.statusRow}><Badge text={member.SubmissionStatus || member.Status} tone={member.Status === 'PAID' ? 'green' : member.SubmissionStatus === 'PENDING' ? 'orange' : 'gray'} />{member.EvidenceUrl&&member.SubmissionStatus!=='PENDING'?<Pressable accessibilityRole="button" accessibilityLabel={`View ${member.FirstName} ${member.LastName} payment evidence`} onPress={()=>setPreview({url:member.EvidenceUrl,title:`${member.FirstName} ${member.LastName} payment evidence`})} style={[styles.evidenceButton,{borderColor:palette.primary}]}><Ionicons name="eye-outline" size={16} color={palette.primary}/><Text style={[styles.evidenceText,{color:palette.primary}]}>View evidence</Text></Pressable>:null}</View></View></View>{member.SubmissionStatus === 'PENDING' ? <View style={styles.actions}>{member.EvidenceUrl ? <Button title="View Evidence" variant="secondary" icon="eye-outline" onPress={() => setPreview({ url: member.EvidenceUrl, title: `${member.FirstName} ${member.LastName} payment evidence` })} /> : null}<Button title="Reject" variant="danger" onPress={() => review.mutate({ sid: member.SubmissionId, action: 'REJECT' })} /><Button title="Approve" variant="success" onPress={() => review.mutate({ sid: member.SubmissionId, action: 'APPROVE' })} /></View> : null}</Card>)}<AttachmentPreview attachment={preview} onClose={() => setPreview(null)} /></Screen>;
}
const styles = StyleSheet.create({ page: { width: '100%', maxWidth: 900, alignSelf: 'center', paddingBottom: 120 }, flex: { flex: 1, minWidth: 0 }, amount: { maxWidth: '100%', fontSize: 26, fontWeight: '900' }, tabs: { width: '100%', flexDirection: 'row', borderBottomWidth: 1, marginBottom: 15 }, tab: { flex: 1, minHeight: 55, borderBottomWidth: 3, borderBottomColor: 'transparent', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3 }, row: { flexDirection: 'row', alignItems: 'center', gap: 11 }, statusRow:{flexDirection:'row',alignItems:'center',gap:14,flexWrap:'nowrap',marginTop:8},evidenceButton:{minHeight:30,borderWidth:1,borderRadius:15,paddingHorizontal:10,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:5,flexShrink:1},evidenceText:{fontSize:11,fontWeight:'900'}, actions: { width: '100%', flexDirection: 'row', justifyContent: 'flex-end', gap: 8, flexWrap: 'wrap', marginTop: 12 } });
