IF COL_LENGTH('Users','TwoFactorEnabled') IS NULL ALTER TABLE Users ADD TwoFactorEnabled BIT NOT NULL CONSTRAINT DF_Users_TwoFactorEnabled DEFAULT 0;
IF COL_LENGTH('Users','TwoFactorMethod') IS NULL ALTER TABLE Users ADD TwoFactorMethod NVARCHAR(20) NULL;
IF COL_LENGTH('Users','TwoFactorSecret') IS NULL ALTER TABLE Users ADD TwoFactorSecret NVARCHAR(1000) NULL;

IF OBJECT_ID('TwoFactorChallenges','U') IS NULL
BEGIN
  CREATE TABLE TwoFactorChallenges(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Purpose NVARCHAR(30) NOT NULL,CodeHash NVARCHAR(64) NOT NULL,Attempts TINYINT NOT NULL DEFAULT 0,ExpiresAt DATETIME2 NOT NULL,ConsumedAt DATETIME2 NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
  CREATE INDEX IX_TwoFactorChallenges_User ON TwoFactorChallenges(UserId,Purpose,ExpiresAt) INCLUDE(ConsumedAt,Attempts);
END;
