IF OBJECT_ID('SupportTickets','U') IS NULL
CREATE TABLE SupportTickets(
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
  Category NVARCHAR(40) NOT NULL,
  Subject NVARCHAR(200) NOT NULL,
  Message NVARCHAR(4000) NOT NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'OPEN',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
