SET NOCOUNT ON;

IF OBJECT_ID('CommentReactions','U') IS NULL
BEGIN
  CREATE TABLE CommentReactions(
    CommentId UNIQUEIDENTIFIER NOT NULL REFERENCES PostComments(Id),
    UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
    ReactionType NVARCHAR(10) NOT NULL CHECK(ReactionType IN('LIKE','DISLIKE')),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    PRIMARY KEY(CommentId,UserId)
  );
END;
