-- Run in the configured application database as a database administrator.
-- Existing reports are preserved.
IF OBJECT_ID('dbo.CommunityIssues','U') IS NULL
CREATE TABLE dbo.CommunityIssues(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.Communities(Id),
 ReportedBy UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.Users(Id), Category NVARCHAR(80) NOT NULL, Title NVARCHAR(250) NOT NULL,
 Description NVARCHAR(4000) NOT NULL, PhotoUrl NVARCHAR(1000) NULL, ApproximateLocation NVARCHAR(250) NULL,
 Status NVARCHAR(30) NOT NULL DEFAULT 'SUBMITTED', AssignedTo UNIQUEIDENTIFIER NULL REFERENCES dbo.Users(Id),
 ResolutionNote NVARCHAR(3000) NULL, ResolvedAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), ReportDetails NVARCHAR(MAX) NULL
);
GO
IF COL_LENGTH('dbo.CommunityIssues','ReportDetails') IS NULL
 EXEC(N'ALTER TABLE dbo.CommunityIssues ADD ReportDetails NVARCHAR(MAX) NULL');
GO
IF OBJECT_ID('dbo.CommunityIssueUpdates','U') IS NULL
CREATE TABLE dbo.CommunityIssueUpdates(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), IssueId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.CommunityIssues(Id),
 CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.Users(Id), Status NVARCHAR(30) NULL, Note NVARCHAR(2000) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
