USE [CDAConnect];
GO
IF OBJECT_ID('AccountSettings','U') IS NULL THROW 50001, 'Apply account-settings.sql first.', 1;
GO
IF OBJECT_ID('PrivacySafetySettings','U') IS NULL
CREATE TABLE PrivacySafetySettings(UserId UNIQUEIDENTIFIER PRIMARY KEY REFERENCES Users(Id),CommentAudience NVARCHAR(20) NOT NULL DEFAULT 'EVERYONE',MentionAudience NVARCHAR(20) NOT NULL DEFAULT 'EVERYONE',TagApproval BIT NOT NULL DEFAULT 1,AllowDownloads BIT NOT NULL DEFAULT 0,UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CHECK(CommentAudience IN ('EVERYONE','COMMUNITIES','NOBODY')),CHECK(MentionAudience IN ('EVERYONE','COMMUNITIES','NOBODY')));
IF OBJECT_ID('HiddenUsers','U') IS NULL CREATE TABLE HiddenUsers(UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),HiddenUserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),PRIMARY KEY(UserId,HiddenUserId),CHECK(UserId<>HiddenUserId));
IF OBJECT_ID('RestrictedWords','U') IS NULL CREATE TABLE RestrictedWords(UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Phrase NVARCHAR(100) NOT NULL,PRIMARY KEY(UserId,Phrase));
IF OBJECT_ID('ProfileTags','U') IS NULL CREATE TABLE ProfileTags(PostId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityPosts(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Status NVARCHAR(20) NOT NULL DEFAULT 'PENDING',CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),PRIMARY KEY(PostId,UserId),CHECK(Status IN ('PENDING','APPROVED','REJECTED')));
IF COL_LENGTH('UserSessions','TrustedName') IS NULL ALTER TABLE UserSessions ADD TrustedName NVARCHAR(80) NULL;
GO
