SET NOCOUNT ON;

CREATE TABLE Users(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),FirstName NVARCHAR(100) NOT NULL,LastName NVARCHAR(100) NOT NULL,Email NVARCHAR(255) NOT NULL UNIQUE,Phone NVARCHAR(30),Country NVARCHAR(100),State NVARCHAR(100),LGA NVARCHAR(150),Postcode NVARCHAR(30),Address NVARCHAR(500),DateOfBirth DATE,PasswordHash NVARCHAR(500) NOT NULL,ProfileImage NVARCHAR(500),CoverImage NVARCHAR(1000),AccountStatus NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE',EmailVerified BIT NOT NULL DEFAULT 0,PhoneVerified BIT NOT NULL DEFAULT 0,TwoFactorEnabled BIT NOT NULL DEFAULT 0,TwoFactorMethod NVARCHAR(20),TwoFactorSecret NVARCHAR(1000),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE UserSessions(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),RefreshTokenHash NVARCHAR(64) NOT NULL UNIQUE,ExpiresAt DATETIME2 NOT NULL,RevokedAt DATETIME2,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE PhoneVerificationCodes(Phone NVARCHAR(30) NOT NULL PRIMARY KEY,CodeHash NVARCHAR(64) NOT NULL,Attempts TINYINT NOT NULL DEFAULT 0,SentAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),ExpiresAt DATETIME2 NOT NULL,ConsumedAt DATETIME2 NULL);
CREATE INDEX IX_PhoneVerificationCodes_Expiry ON PhoneVerificationCodes(ExpiresAt) INCLUDE(ConsumedAt);
CREATE TABLE TwoFactorChallenges(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Purpose NVARCHAR(30) NOT NULL,CodeHash NVARCHAR(64) NOT NULL,Attempts TINYINT NOT NULL DEFAULT 0,ExpiresAt DATETIME2 NOT NULL,ConsumedAt DATETIME2 NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE INDEX IX_TwoFactorChallenges_User ON TwoFactorChallenges(UserId,Purpose,ExpiresAt) INCLUDE(ConsumedAt,Attempts);
CREATE TABLE UserDevices(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),DeviceToken NVARCHAR(500) NOT NULL,Platform NVARCHAR(20) NOT NULL,DeviceName NVARCHAR(200),LastActiveAt DATETIME2,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_UserDevice UNIQUE(UserId,DeviceToken));
CREATE TABLE Communities(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),Name NVARCHAR(200) NOT NULL,Description NVARCHAR(MAX),LogoUrl NVARCHAR(500),BannerUrl NVARCHAR(500),CommunityType NVARCHAR(100),Country NVARCHAR(100),City NVARCHAR(100),IsPrivate BIT NOT NULL DEFAULT 1,OwnerUserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),JoinCode NVARCHAR(20) NOT NULL UNIQUE,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE CommunityMembers(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Status NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE',JoinedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_CommunityMember UNIQUE(CommunityId,UserId));
CREATE TABLE CommunityExecutiveMembers(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Position NVARCHAR(100) NOT NULL,Department NVARCHAR(150) NULL,AppointedDate DATE NOT NULL,TenureEndDate DATE NULL,Notes NVARCHAR(500) NULL,Status NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_CommunityExecutiveMembers_Community_User UNIQUE(CommunityId,UserId));
CREATE TABLE Roles(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),Name NVARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE Permissions(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),Code NVARCHAR(100) NOT NULL UNIQUE,Description NVARCHAR(300));
CREATE TABLE CommunityMemberRoles(CommunityMemberId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityMembers(Id),RoleId UNIQUEIDENTIFIER NOT NULL REFERENCES Roles(Id),PRIMARY KEY(CommunityMemberId,RoleId));
CREATE TABLE RolePermissions(RoleId UNIQUEIDENTIFIER NOT NULL REFERENCES Roles(Id),PermissionId UNIQUEIDENTIFIER NOT NULL REFERENCES Permissions(Id),PRIMARY KEY(RoleId,PermissionId));
CREATE TABLE Announcements(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Title NVARCHAR(250) NOT NULL,Body NVARCHAR(MAX) NOT NULL,IsPinned BIT NOT NULL DEFAULT 0,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE Meetings(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Title NVARCHAR(250) NOT NULL,Description NVARCHAR(MAX),Location NVARCHAR(500),OnlineMeetingUrl NVARCHAR(500),StartDateTime DATETIME2 NOT NULL,EndDateTime DATETIME2 NOT NULL,MeetingType NVARCHAR(100),AllowRegistration BIT NOT NULL DEFAULT 1,AllowCalendar BIT NOT NULL DEFAULT 1,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE MeetingAgendaItems(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),MeetingId UNIQUEIDENTIFIER NOT NULL REFERENCES Meetings(Id),Title NVARCHAR(250) NOT NULL,Description NVARCHAR(MAX),Position INT NOT NULL,AssignedTo UNIQUEIDENTIFIER NULL REFERENCES Users(Id),DurationMinutes INT,Status NVARCHAR(30));
CREATE TABLE MeetingAttendees(MeetingId UNIQUEIDENTIFIER NOT NULL REFERENCES Meetings(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Response NVARCHAR(20) NOT NULL,RespondedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),PRIMARY KEY(MeetingId,UserId));
CREATE TABLE MeetingAttendanceSessions(MeetingId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY REFERENCES Meetings(Id),AttendanceCode CHAR(6) NOT NULL,CodeExpiresAt DATETIME2 NOT NULL,IsActive BIT NOT NULL DEFAULT 1,CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE MeetingAttendance(MeetingId UNIQUEIDENTIFIER NOT NULL REFERENCES Meetings(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Status NVARCHAR(20) NOT NULL DEFAULT 'PRESENT',CheckInMethod NVARCHAR(20) NOT NULL,CheckedInAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),MarkedBy UNIQUEIDENTIFIER NULL REFERENCES Users(Id),PRIMARY KEY(MeetingId,UserId));
CREATE INDEX IX_MeetingAttendance_CheckedInAt ON MeetingAttendance(MeetingId,CheckedInAt);
CREATE TABLE Polls(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Question NVARCHAR(500) NOT NULL,Description NVARCHAR(MAX),IsAnonymous BIT NOT NULL DEFAULT 0,AllowMultiple BIT NOT NULL DEFAULT 0,AllowChangeVote BIT NOT NULL DEFAULT 0,StartAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),EndAt DATETIME2,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE PollOptions(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),PollId UNIQUEIDENTIFIER NOT NULL REFERENCES Polls(Id),OptionText NVARCHAR(500) NOT NULL,ImageUrl NVARCHAR(1500) NULL,SortOrder INT NOT NULL DEFAULT 0);
CREATE TABLE PollVotes(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),PollId UNIQUEIDENTIFIER NOT NULL REFERENCES Polls(Id),OptionId UNIQUEIDENTIFIER NOT NULL REFERENCES PollOptions(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_PollOptionUser UNIQUE(PollId,OptionId,UserId));
CREATE TABLE EmergencyAlerts(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Title NVARCHAR(250) NOT NULL,Message NVARCHAR(MAX) NOT NULL,AlertType NVARCHAR(100),Severity NVARCHAR(30) NOT NULL,Latitude DECIMAL(10,7),Longitude DECIMAL(10,7),RequiresAcknowledgement BIT NOT NULL DEFAULT 0,Active BIT NOT NULL DEFAULT 1,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE EmergencyResponses(AlertId UNIQUEIDENTIFIER NOT NULL REFERENCES EmergencyAlerts(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Response NVARCHAR(30) NOT NULL,RespondedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),PRIMARY KEY(AlertId,UserId));
CREATE TABLE Conversations(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),Name NVARCHAR(200) NOT NULL,Type NVARCHAR(30) NOT NULL,CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE ConversationMembers(ConversationId UNIQUEIDENTIFIER NOT NULL REFERENCES Conversations(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),JoinedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),PRIMARY KEY(ConversationId,UserId));
CREATE TABLE Messages(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),ConversationId UNIQUEIDENTIFIER NOT NULL REFERENCES Conversations(Id),SenderUserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),MessageType NVARCHAR(30) NOT NULL DEFAULT 'TEXT',MessageText NVARCHAR(MAX),MediaUrl NVARCHAR(500),ReplyToMessageId UNIQUEIDENTIFIER NULL,IsEdited BIT NOT NULL DEFAULT 0,IsDeleted BIT NOT NULL DEFAULT 0,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE AuditLogs(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NULL,UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Action NVARCHAR(200) NOT NULL,EntityType NVARCHAR(100) NOT NULL,EntityId UNIQUEIDENTIFIER NULL,Details NVARCHAR(MAX),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

INSERT INTO Roles(Name) VALUES('Owner'),('Admin'),('Moderator'),('Secretary'),('Treasurer'),('Emergency Coordinator'),('Member');
INSERT INTO Permissions(Code,Description) VALUES
('COMMUNITY_EDIT','Edit community'),('MEMBER_INVITE','Invite members'),('MEMBER_REMOVE','Remove members'),('MEMBER_ROLE_CHANGE','Change member roles'),('CHAT_CREATE','Create group chats'),('CHAT_MODERATE','Moderate chat'),('MEETING_CREATE','Create meetings'),('MEETING_EDIT','Edit meetings'),('ATTENDANCE_MANAGE','Manage meeting attendance'),('POLL_CREATE','Create polls'),('POLL_CLOSE','Close polls'),('EMERGENCY_SEND','Send emergency alerts'),('ANNOUNCEMENT_CREATE','Create announcements'),('DOCUMENT_UPLOAD','Upload documents'),('DOCUMENT_DELETE','Delete documents');
INSERT INTO RolePermissions(RoleId,PermissionId) SELECT r.Id,p.Id FROM Roles r CROSS JOIN Permissions p WHERE r.Name IN('Owner','Admin');
INSERT INTO RolePermissions(RoleId,PermissionId) SELECT r.Id,p.Id FROM Roles r JOIN Permissions p ON p.Code IN('CHAT_MODERATE') WHERE r.Name='Moderator';
INSERT INTO RolePermissions(RoleId,PermissionId) SELECT r.Id,p.Id FROM Roles r JOIN Permissions p ON p.Code='ATTENDANCE_MANAGE' WHERE r.Name='Moderator';
INSERT INTO RolePermissions(RoleId,PermissionId) SELECT r.Id,p.Id FROM Roles r JOIN Permissions p ON p.Code IN('MEETING_CREATE','MEETING_EDIT','ANNOUNCEMENT_CREATE') WHERE r.Name='Secretary';
INSERT INTO RolePermissions(RoleId,PermissionId) SELECT r.Id,p.Id FROM Roles r JOIN Permissions p ON p.Code='EMERGENCY_SEND' WHERE r.Name='Emergency Coordinator';
CREATE INDEX IX_CommunityMembers_User ON CommunityMembers(UserId,Status);
CREATE INDEX IX_Messages_Conversation_Created ON Messages(ConversationId,CreatedAt);
CREATE INDEX IX_Announcements_Community_Created ON Announcements(CommunityId,CreatedAt DESC);
CREATE INDEX IX_Meetings_Community_Start ON Meetings(CommunityId,StartDateTime);
CREATE TABLE CommunityJoinRequests(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Status NVARCHAR(30) NOT NULL DEFAULT 'PENDING',Message NVARCHAR(500),ReviewedBy UNIQUEIDENTIFIER NULL REFERENCES Users(Id),ReviewedAt DATETIME2 NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_CommunityJoinRequest UNIQUE(CommunityId,UserId));
CREATE INDEX IX_JoinRequests_Community_Status ON CommunityJoinRequests(CommunityId,Status,CreatedAt DESC);

-- Community news feed
CREATE TABLE CommunityPosts(
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),
  CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
  Body NVARCHAR(MAX) NOT NULL,
  MediaUrl NVARCHAR(1000),
  IsDeleted BIT NOT NULL DEFAULT 0,
  DeletedBy UNIQUEIDENTIFIER NULL REFERENCES Users(Id),
  DeletedAt DATETIME2 NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE TABLE PostLikes(
  PostId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityPosts(Id),
  UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  PRIMARY KEY(PostId,UserId)
);
CREATE TABLE PostComments(
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  PostId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityPosts(Id),
  UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
  Body NVARCHAR(1500) NOT NULL,
  IsDeleted BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE INDEX IX_CommunityPosts_Community_Created ON CommunityPosts(CommunityId,CreatedAt DESC);
CREATE INDEX IX_PostComments_Post_Created ON PostComments(PostId,CreatedAt);
SET NOCOUNT ON;

IF COL_LENGTH('CommunityPosts','PostType') IS NULL ALTER TABLE CommunityPosts ADD PostType NVARCHAR(40) NOT NULL CONSTRAINT DF_CommunityPosts_PostType DEFAULT 'TEXT';
IF COL_LENGTH('CommunityPosts','MediaType') IS NULL ALTER TABLE CommunityPosts ADD MediaType NVARCHAR(100) NULL;
IF COL_LENGTH('CommunityPosts','DocumentName') IS NULL ALTER TABLE CommunityPosts ADD DocumentName NVARCHAR(500) NULL;
IF COL_LENGTH('CommunityPosts','Caption') IS NULL ALTER TABLE CommunityPosts ADD Caption NVARCHAR(1500) NULL;
IF COL_LENGTH('CommunityPosts','Transcript') IS NULL ALTER TABLE CommunityPosts ADD Transcript NVARCHAR(MAX) NULL;
IF COL_LENGTH('CommunityPosts','OriginalLanguage') IS NULL ALTER TABLE CommunityPosts ADD OriginalLanguage NVARCHAR(20) NULL;
IF COL_LENGTH('CommunityPosts','IsPinned') IS NULL ALTER TABLE CommunityPosts ADD IsPinned BIT NOT NULL CONSTRAINT DF_CommunityPosts_IsPinned DEFAULT 0;
IF COL_LENGTH('CommunityPosts','IsAnnouncement') IS NULL ALTER TABLE CommunityPosts ADD IsAnnouncement BIT NOT NULL CONSTRAINT DF_CommunityPosts_IsAnnouncement DEFAULT 0;
IF COL_LENGTH('PostComments','ParentCommentId') IS NULL ALTER TABLE PostComments ADD ParentCommentId UNIQUEIDENTIFIER NULL;
IF COL_LENGTH('PostComments','DeletedBy') IS NULL ALTER TABLE PostComments ADD DeletedBy UNIQUEIDENTIFIER NULL REFERENCES Users(Id);
IF COL_LENGTH('PostComments','DeletedAt') IS NULL ALTER TABLE PostComments ADD DeletedAt DATETIME2 NULL;

IF OBJECT_ID('PostReactions','U') IS NULL CREATE TABLE PostReactions(PostId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityPosts(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),ReactionType NVARCHAR(20) NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),PRIMARY KEY(PostId,UserId));
IF OBJECT_ID('CommentReactions','U') IS NULL CREATE TABLE CommentReactions(CommentId UNIQUEIDENTIFIER NOT NULL REFERENCES PostComments(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),ReactionType NVARCHAR(10) NOT NULL CHECK(ReactionType IN('LIKE','DISLIKE')),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),PRIMARY KEY(CommentId,UserId));
IF OBJECT_ID('PostSaves','U') IS NULL CREATE TABLE PostSaves(PostId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityPosts(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),PRIMARY KEY(PostId,UserId));
IF OBJECT_ID('PostShares','U') IS NULL CREATE TABLE PostShares(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),PostId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityPosts(Id),UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('PostReports','U') IS NULL CREATE TABLE PostReports(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),PostId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityPosts(Id),ReportedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),Reason NVARCHAR(100) NOT NULL,Details NVARCHAR(1000),Status NVARCHAR(30) NOT NULL DEFAULT 'OPEN',ReviewedBy UNIQUEIDENTIFIER NULL REFERENCES Users(Id),ReviewedAt DATETIME2 NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('PostHashtags','U') IS NULL CREATE TABLE PostHashtags(PostId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityPosts(Id),Tag NVARCHAR(80) NOT NULL,PRIMARY KEY(PostId,Tag));
IF OBJECT_ID('PostMentionLabels','U') IS NULL CREATE TABLE PostMentionLabels(PostId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityPosts(Id),MentionLabel NVARCHAR(120) NOT NULL,PRIMARY KEY(PostId,MentionLabel));
IF OBJECT_ID('ContentTranslations','U') IS NULL CREATE TABLE ContentTranslations(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),EntityType NVARCHAR(30) NOT NULL,EntityId UNIQUEIDENTIFIER NOT NULL,LanguageCode NVARCHAR(20) NOT NULL,Mode NVARCHAR(20) NOT NULL,Text NVARCHAR(MAX) NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_ContentTranslation UNIQUE(EntityType,EntityId,LanguageCode,Mode));

IF OBJECT_ID('PostLikes','U') IS NOT NULL INSERT INTO PostReactions(PostId,UserId,ReactionType) SELECT l.PostId,l.UserId,'LIKE' FROM PostLikes l WHERE NOT EXISTS(SELECT 1 FROM PostReactions r WHERE r.PostId=l.PostId AND r.UserId=l.UserId);
CREATE INDEX IX_PostReactions_Post ON PostReactions(PostId,ReactionType);
CREATE INDEX IX_PostReports_Status ON PostReports(Status,CreatedAt DESC);
CREATE INDEX IX_PostHashtags_Tag ON PostHashtags(Tag);


-- Community discovery, services, events and civic modules
SET NOCOUNT ON;

-- Discovery / verification
IF COL_LENGTH('Communities','Postcode') IS NULL ALTER TABLE Communities ADD Postcode NVARCHAR(20) NULL;
IF COL_LENGTH('Communities','Category') IS NULL ALTER TABLE Communities ADD Category NVARCHAR(80) NULL;
IF COL_LENGTH('Communities','IsVerified') IS NULL ALTER TABLE Communities ADD IsVerified BIT NOT NULL CONSTRAINT DF_Communities_IsVerified DEFAULT 0;
IF COL_LENGTH('Communities','VerifiedAt') IS NULL ALTER TABLE Communities ADD VerifiedAt DATETIME2 NULL;
IF COL_LENGTH('Communities','State') IS NULL ALTER TABLE Communities ADD State NVARCHAR(100) NULL;
IF COL_LENGTH('Communities','LGA') IS NULL ALTER TABLE Communities ADD LGA NVARCHAR(150) NULL;
IF COL_LENGTH('Communities','SpecificArea') IS NULL ALTER TABLE Communities ADD SpecificArea NVARCHAR(250) NULL;
IF COL_LENGTH('Communities','Latitude') IS NULL ALTER TABLE Communities ADD Latitude DECIMAL(10,7) NULL;
IF COL_LENGTH('Communities','Longitude') IS NULL ALTER TABLE Communities ADD Longitude DECIMAL(10,7) NULL;
IF COL_LENGTH('Communities','RequireMemberApproval') IS NULL ALTER TABLE Communities ADD RequireMemberApproval BIT NOT NULL CONSTRAINT DF_Communities_RequireMemberApproval DEFAULT 1;
IF COL_LENGTH('Communities','AllowMemberEvents') IS NULL ALTER TABLE Communities ADD AllowMemberEvents BIT NOT NULL CONSTRAINT DF_Communities_AllowMemberEvents DEFAULT 1;
IF COL_LENGTH('Communities','AllowMemberDiscussions') IS NULL ALTER TABLE Communities ADD AllowMemberDiscussions BIT NOT NULL CONSTRAINT DF_Communities_AllowMemberDiscussions DEFAULT 1;
IF COL_LENGTH('Communities','Guidelines') IS NULL ALTER TABLE Communities ADD Guidelines NVARCHAR(2000) NULL;
IF COL_LENGTH('Communities','Tags') IS NULL ALTER TABLE Communities ADD Tags NVARCHAR(1000) NULL;

IF OBJECT_ID('UserDiscoveryPreferences','U') IS NULL
CREATE TABLE UserDiscoveryPreferences(
 UserId UNIQUEIDENTIFIER PRIMARY KEY REFERENCES Users(Id),
 DiscoveryEnabled BIT NOT NULL DEFAULT 0,
 Town NVARCHAR(120) NULL,
 Postcode NVARCHAR(20) NULL,
 PreferredRadiusKm INT NOT NULL DEFAULT 25,
 UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('CommunityVerificationRequests','U') IS NULL
CREATE TABLE CommunityVerificationRequests(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
 CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),
 SubmittedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
 OrganisationName NVARCHAR(200) NOT NULL,
 RegistrationNumber NVARCHAR(120) NULL,
 EvidenceUrl NVARCHAR(1000) NOT NULL,
 Notes NVARCHAR(2000) NULL,
 Status NVARCHAR(30) NOT NULL DEFAULT 'PENDING',
 ReviewNotes NVARCHAR(2000) NULL,
 ReviewedBy UNIQUEIDENTIFIER NULL REFERENCES Users(Id),
 ReviewedAt DATETIME2 NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- Emergency command centre
IF COL_LENGTH('EmergencyAlerts','AffectedArea') IS NULL ALTER TABLE EmergencyAlerts ADD AffectedArea NVARCHAR(250) NULL;
IF COL_LENGTH('EmergencyAlerts','ResolvedAt') IS NULL ALTER TABLE EmergencyAlerts ADD ResolvedAt DATETIME2 NULL;
IF COL_LENGTH('EmergencyAlerts','ResolvedBy') IS NULL ALTER TABLE EmergencyAlerts ADD ResolvedBy UNIQUEIDENTIFIER NULL REFERENCES Users(Id);
IF COL_LENGTH('EmergencyAlerts','ResolutionNote') IS NULL ALTER TABLE EmergencyAlerts ADD ResolutionNote NVARCHAR(2000) NULL;

IF OBJECT_ID('EmergencyIncidentUpdates','U') IS NULL
CREATE TABLE EmergencyIncidentUpdates(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
 AlertId UNIQUEIDENTIFIER NOT NULL REFERENCES EmergencyAlerts(Id),
 CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
 Message NVARCHAR(3000) NOT NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
IF OBJECT_ID('CommunityEmergencyContacts','U') IS NULL
CREATE TABLE CommunityEmergencyContacts(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),
 Name NVARCHAR(160) NOT NULL, Phone NVARCHAR(40) NOT NULL, ContactType NVARCHAR(80) NULL, IsOfficial BIT NOT NULL DEFAULT 0,
 CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id), CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
IF OBJECT_ID('TrustedContacts','U') IS NULL
CREATE TABLE TrustedContacts(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
 Name NVARCHAR(160) NOT NULL, Phone NVARCHAR(40) NOT NULL, Relationship NVARCHAR(100) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
IF OBJECT_ID('SOSRequests','U') IS NULL
CREATE TABLE SOSRequests(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),
 UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id), Message NVARCHAR(1000) NULL, ApproximateArea NVARCHAR(250) NULL,
 Status NVARCHAR(30) NOT NULL DEFAULT 'OPEN', ResolvedAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- Issue reporting
IF OBJECT_ID('CommunityIssues','U') IS NULL
CREATE TABLE CommunityIssues(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),
 ReportedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id), Category NVARCHAR(80) NOT NULL, Title NVARCHAR(250) NOT NULL,
 Description NVARCHAR(4000) NOT NULL, PhotoUrl NVARCHAR(1000) NULL, ApproximateLocation NVARCHAR(250) NULL,
 Status NVARCHAR(30) NOT NULL DEFAULT 'SUBMITTED', AssignedTo UNIQUEIDENTIFIER NULL REFERENCES Users(Id),
 ResolutionNote NVARCHAR(3000) NULL, ResolvedAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
IF OBJECT_ID('CommunityIssueUpdates','U') IS NULL
CREATE TABLE CommunityIssueUpdates(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), IssueId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityIssues(Id),
 CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id), Status NVARCHAR(30) NULL, Note NVARCHAR(2000) NOT NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- Service directory
IF OBJECT_ID('ServiceProviders','U') IS NULL
CREATE TABLE ServiceProviders(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),
 CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id), Name NVARCHAR(200) NOT NULL, Category NVARCHAR(100) NOT NULL,
 Description NVARCHAR(3000) NULL, Phone NVARCHAR(40) NULL, Email NVARCHAR(255) NULL, Website NVARCHAR(500) NULL,
 Area NVARCHAR(200) NULL, LogoUrl NVARCHAR(1000) NULL, IsVerified BIT NOT NULL DEFAULT 0, Status NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
IF OBJECT_ID('ServiceReviews','U') IS NULL
CREATE TABLE ServiceReviews(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), ProviderId UNIQUEIDENTIFIER NOT NULL REFERENCES ServiceProviders(Id),
 UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id), Rating TINYINT NOT NULL CHECK(Rating BETWEEN 1 AND 5), Comment NVARCHAR(2000) NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_ServiceReview UNIQUE(ProviderId,UserId)
);

-- Marketplace
IF OBJECT_ID('MarketplaceListings','U') IS NULL
CREATE TABLE MarketplaceListings(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),
 SellerUserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id), ListingType NVARCHAR(30) NOT NULL, Title NVARCHAR(220) NOT NULL,
 Description NVARCHAR(4000) NULL, Price DECIMAL(18,2) NULL, Currency NVARCHAR(10) NOT NULL DEFAULT 'GBP', Area NVARCHAR(200) NULL,
 ImageUrl NVARCHAR(1000) NULL, Status NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE', ModerationStatus NVARCHAR(30) NOT NULL DEFAULT 'APPROVED',
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
IF OBJECT_ID('MarketplaceReports','U') IS NULL
CREATE TABLE MarketplaceReports(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), ListingId UNIQUEIDENTIFIER NOT NULL REFERENCES MarketplaceListings(Id),
 ReportedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id), Reason NVARCHAR(120) NOT NULL, Details NVARCHAR(1000) NULL,
 Status NVARCHAR(30) NOT NULL DEFAULT 'OPEN', CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- Opportunities
IF OBJECT_ID('CommunityOpportunities','U') IS NULL
CREATE TABLE CommunityOpportunities(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),
 CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id), OpportunityType NVARCHAR(40) NOT NULL, Title NVARCHAR(250) NOT NULL,
 Description NVARCHAR(MAX) NOT NULL, Organisation NVARCHAR(200) NULL, Location NVARCHAR(200) NULL, ApplyUrl NVARCHAR(1000) NULL,
 Deadline DATETIME2 NULL, Status NVARCHAR(30) NOT NULL DEFAULT 'OPEN', CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
IF OBJECT_ID('SavedOpportunities','U') IS NULL
CREATE TABLE SavedOpportunities(
 OpportunityId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityOpportunities(Id), UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), PRIMARY KEY(OpportunityId,UserId)
);

-- Events / membership cards / attendance
IF OBJECT_ID('CommunityEvents','U') IS NULL
CREATE TABLE CommunityEvents(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), CommunityId UNIQUEIDENTIFIER NOT NULL REFERENCES Communities(Id),
 CreatedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id), Title NVARCHAR(250) NOT NULL, Description NVARCHAR(MAX) NULL,
 EventType NVARCHAR(80) NULL, Location NVARCHAR(500) NULL, StartDateTime DATETIME2 NOT NULL, EndDateTime DATETIME2 NOT NULL,
 Capacity INT NULL, AllowWaitlist BIT NOT NULL DEFAULT 1, ReminderMinutes INT NULL, CoverImageUrl NVARCHAR(1000) NULL,
 ConversationId UNIQUEIDENTIFIER NULL REFERENCES Conversations(Id), CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
IF OBJECT_ID('EventAttendees','U') IS NULL
CREATE TABLE EventAttendees(
 EventId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityEvents(Id), UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
 Status NVARCHAR(30) NOT NULL DEFAULT 'GOING', CheckedInAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 PRIMARY KEY(EventId,UserId)
);
IF OBJECT_ID('EventPhotos','U') IS NULL
CREATE TABLE EventPhotos(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), EventId UNIQUEIDENTIFIER NOT NULL REFERENCES CommunityEvents(Id),
 UploadedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id), PhotoUrl NVARCHAR(1000) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
IF OBJECT_ID('MembershipCards','U') IS NULL
CREATE TABLE MembershipCards(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), MembershipId UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES CommunityMembers(Id),
 CardNumber NVARCHAR(50) NOT NULL UNIQUE, QrToken NVARCHAR(120) NOT NULL UNIQUE, IsActive BIT NOT NULL DEFAULT 1,
 IssuedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), ExpiresAt DATETIME2 NULL
);

-- New permissions
MERGE Permissions AS t USING (VALUES
 ('VERIFICATION_SUBMIT','Submit community verification'),('ISSUE_MANAGE','Manage community issues'),('DIRECTORY_MANAGE','Manage service directory'),
 ('MARKETPLACE_MODERATE','Moderate marketplace'),('OPPORTUNITY_MANAGE','Manage opportunities'),('EVENT_CREATE','Create community events'),
 ('EVENT_MANAGE','Manage community events'),('MEMBERSHIP_SCAN','Scan membership cards'),('EMERGENCY_MANAGE','Manage emergency command centre')
) AS s(Code,Description) ON t.Code=s.Code WHEN NOT MATCHED THEN INSERT(Code,Description) VALUES(s.Code,s.Description);
INSERT INTO RolePermissions(RoleId,PermissionId)
SELECT r.Id,p.Id FROM Roles r CROSS JOIN Permissions p
WHERE r.Name IN('Owner','Admin') AND p.Code IN('VERIFICATION_SUBMIT','ISSUE_MANAGE','DIRECTORY_MANAGE','MARKETPLACE_MODERATE','OPPORTUNITY_MANAGE','EVENT_CREATE','EVENT_MANAGE','MEMBERSHIP_SCAN','EMERGENCY_MANAGE')
AND NOT EXISTS(SELECT 1 FROM RolePermissions rp WHERE rp.RoleId=r.Id AND rp.PermissionId=p.Id);

INSERT INTO RolePermissions(RoleId,PermissionId)
SELECT r.Id,p.Id FROM Roles r CROSS JOIN Permissions p WHERE r.Name='Moderator' AND p.Code='FINANCE_MANAGE'
AND NOT EXISTS(SELECT 1 FROM RolePermissions rp WHERE rp.RoleId=r.Id AND rp.PermissionId=p.Id);

CREATE INDEX IX_Communities_Discovery ON Communities(Category,City,Postcode,IsVerified);
CREATE INDEX IX_Issues_Community_Status ON CommunityIssues(CommunityId,Status,CreatedAt DESC);
CREATE INDEX IX_Events_Community_Start ON CommunityEvents(CommunityId,StartDateTime);
CREATE INDEX IX_Marketplace_Community_Status ON MarketplaceListings(CommunityId,Status,CreatedAt DESC);
CREATE INDEX IX_Opportunities_Community_Deadline ON CommunityOpportunities(CommunityId,Deadline);

-- ============================================================
-- GOVERNANCE, FORMAL VOTING, FINANCE, KNOWLEDGE, AI & INSIGHTS
-- Included directly in the fresh-install schema.
-- ============================================================

/* Governance, formal voting, finance, knowledge centre, AI, summaries, preferences and analytics */

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='GovernanceProposals')
CREATE TABLE GovernanceProposals(
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), CommunityId UNIQUEIDENTIFIER NOT NULL, CreatedBy UNIQUEIDENTIFIER NOT NULL,
 Title NVARCHAR(250) NOT NULL, Summary NVARCHAR(2000) NULL, Body NVARCHAR(MAX) NOT NULL,
 Status NVARCHAR(30) NOT NULL DEFAULT 'DISCUSSION', DiscussionClosesAt DATETIME2 NULL, VotingOpensAt DATETIME2 NULL, VotingClosesAt DATETIME2 NULL,
 DecisionText NVARCHAR(MAX) NULL, DecidedAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 CONSTRAINT FK_GovernanceProposals_Community FOREIGN KEY(CommunityId) REFERENCES Communities(Id),
 CONSTRAINT FK_GovernanceProposals_User FOREIGN KEY(CreatedBy) REFERENCES Users(Id)
);
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='ProposalDiscussions')
CREATE TABLE ProposalDiscussions(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),ProposalId UNIQUEIDENTIFIER NOT NULL,UserId UNIQUEIDENTIFIER NOT NULL,Body NVARCHAR(4000) NOT NULL,ParentId UNIQUEIDENTIFIER NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(ProposalId) REFERENCES GovernanceProposals(Id),FOREIGN KEY(UserId) REFERENCES Users(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='ProposalAmendments')
CREATE TABLE ProposalAmendments(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),ProposalId UNIQUEIDENTIFIER NOT NULL,ProposedBy UNIQUEIDENTIFIER NOT NULL,Title NVARCHAR(250) NOT NULL,Body NVARCHAR(MAX) NOT NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'PROPOSED',ReviewedBy UNIQUEIDENTIFIER NULL,ReviewedAt DATETIME2 NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(ProposalId) REFERENCES GovernanceProposals(Id),FOREIGN KEY(ProposedBy) REFERENCES Users(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='FormalBallots')
CREATE TABLE FormalBallots(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,ProposalId UNIQUEIDENTIFIER NULL,CreatedBy UNIQUEIDENTIFIER NOT NULL,Title NVARCHAR(250) NOT NULL,Description NVARCHAR(MAX) NULL,BallotType NVARCHAR(30) NOT NULL DEFAULT 'FORMAL',IsAnonymous BIT NOT NULL DEFAULT 1,QuorumPercent DECIMAL(5,2) NOT NULL DEFAULT 50,OpensAt DATETIME2 NOT NULL,ClosesAt DATETIME2 NOT NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',FinalResult NVARCHAR(MAX) NULL,FinalizedAt DATETIME2 NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(CommunityId) REFERENCES Communities(Id),FOREIGN KEY(ProposalId) REFERENCES GovernanceProposals(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='FormalBallotOptions')
CREATE TABLE FormalBallotOptions(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),BallotId UNIQUEIDENTIFIER NOT NULL,Label NVARCHAR(500) NOT NULL,SortOrder INT NOT NULL DEFAULT 0,FOREIGN KEY(BallotId) REFERENCES FormalBallots(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='FormalBallotEligibility')
CREATE TABLE FormalBallotEligibility(BallotId UNIQUEIDENTIFIER NOT NULL,UserId UNIQUEIDENTIFIER NOT NULL,Eligible BIT NOT NULL DEFAULT 1,Reason NVARCHAR(500) NULL,SnapshotAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),PRIMARY KEY(BallotId,UserId),FOREIGN KEY(BallotId) REFERENCES FormalBallots(Id),FOREIGN KEY(UserId) REFERENCES Users(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='FormalBallotReceipts')
CREATE TABLE FormalBallotReceipts(BallotId UNIQUEIDENTIFIER NOT NULL,UserId UNIQUEIDENTIFIER NOT NULL,ReceiptHash NVARCHAR(128) NOT NULL,CastAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),PRIMARY KEY(BallotId,UserId),FOREIGN KEY(BallotId) REFERENCES FormalBallots(Id),FOREIGN KEY(UserId) REFERENCES Users(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='FormalBallotVotes')
CREATE TABLE FormalBallotVotes(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),BallotId UNIQUEIDENTIFIER NOT NULL,OptionId UNIQUEIDENTIFIER NOT NULL,VoterUserId UNIQUEIDENTIFIER NULL,VoterTokenHash NVARCHAR(128) NULL,CastAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(BallotId) REFERENCES FormalBallots(Id),FOREIGN KEY(OptionId) REFERENCES FormalBallotOptions(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='GovernanceActions')
CREATE TABLE GovernanceActions(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,ProposalId UNIQUEIDENTIFIER NULL,DecisionId UNIQUEIDENTIFIER NULL,Title NVARCHAR(250) NOT NULL,Description NVARCHAR(MAX) NULL,AssignedTo UNIQUEIDENTIFIER NULL,DueAt DATETIME2 NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'OPEN',ProgressPercent INT NOT NULL DEFAULT 0,CreatedBy UNIQUEIDENTIFIER NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='DecisionRegister')
CREATE TABLE DecisionRegister(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,ProposalId UNIQUEIDENTIFIER NULL,BallotId UNIQUEIDENTIFIER NULL,Title NVARCHAR(250) NOT NULL,DecisionText NVARCHAR(MAX) NOT NULL,DecisionDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),Tags NVARCHAR(1000) NULL,SearchText NVARCHAR(MAX) NULL,RecordedBy UNIQUEIDENTIFIER NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='FinanceAccounts')
CREATE TABLE FinanceAccounts(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,Name NVARCHAR(200) NOT NULL,CurrencyCode CHAR(3) NOT NULL DEFAULT 'GBP',AccountType NVARCHAR(40) NOT NULL DEFAULT 'GENERAL',IsActive BIT NOT NULL DEFAULT 1,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='MemberDuesPlans')
CREATE TABLE MemberDuesPlans(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,Name NVARCHAR(200) NOT NULL,Description NVARCHAR(2000) NULL,Year INT NOT NULL,Amount DECIMAL(18,2) NOT NULL,CurrencyCode CHAR(3) NOT NULL DEFAULT 'NGN',DueDate DATE NULL,Frequency NVARCHAR(30) NOT NULL DEFAULT 'ONE_TIME',AudienceType NVARCHAR(20) NOT NULL DEFAULT 'ALL',IsActive BIT NOT NULL DEFAULT 1,CreatedBy UNIQUEIDENTIFIER NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='MemberDuesLedger')
CREATE TABLE MemberDuesLedger(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),PlanId UNIQUEIDENTIFIER NOT NULL,CommunityId UNIQUEIDENTIFIER NOT NULL,UserId UNIQUEIDENTIFIER NOT NULL,AmountDue DECIMAL(18,2) NOT NULL,AmountPaid DECIMAL(18,2) NOT NULL DEFAULT 0,Status NVARCHAR(30) NOT NULL DEFAULT 'OUTSTANDING',UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_Dues_UserPlan UNIQUE(PlanId,UserId),FOREIGN KEY(PlanId) REFERENCES MemberDuesPlans(Id),FOREIGN KEY(UserId) REFERENCES Users(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='LevyPaymentSubmissions')
CREATE TABLE LevyPaymentSubmissions(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),LedgerId UNIQUEIDENTIFIER NOT NULL,CommunityId UNIQUEIDENTIFIER NOT NULL,UserId UNIQUEIDENTIFIER NOT NULL,Amount DECIMAL(18,2) NOT NULL,PaymentMethod NVARCHAR(30) NOT NULL DEFAULT 'BANK_TRANSFER',Reference NVARCHAR(120) NOT NULL,EvidenceUrl NVARCHAR(1000) NOT NULL,Note NVARCHAR(2000) NULL,Status NVARCHAR(20) NOT NULL DEFAULT 'PENDING',ReviewedBy UNIQUEIDENTIFIER NULL,ReviewedAt DATETIME2 NULL,ReviewNote NVARCHAR(2000) NULL,SubmittedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(LedgerId) REFERENCES MemberDuesLedger(Id),FOREIGN KEY(CommunityId) REFERENCES Communities(Id),FOREIGN KEY(UserId) REFERENCES Users(Id),FOREIGN KEY(ReviewedBy) REFERENCES Users(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='FinanceTransactions')
CREATE TABLE FinanceTransactions(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,AccountId UNIQUEIDENTIFIER NULL,UserId UNIQUEIDENTIFIER NULL,TransactionType NVARCHAR(40) NOT NULL,Category NVARCHAR(120) NULL,Description NVARCHAR(500) NOT NULL,Amount DECIMAL(18,2) NOT NULL,CurrencyCode CHAR(3) NOT NULL DEFAULT 'GBP',Reference NVARCHAR(120) NULL,Provider NVARCHAR(50) NULL,ProviderReference NVARCHAR(200) NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'COMPLETED',TransactionDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CreatedBy UNIQUEIDENTIFIER NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Fundraisers')
CREATE TABLE Fundraisers(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,Title NVARCHAR(250) NOT NULL,Description NVARCHAR(MAX) NULL,TargetAmount DECIMAL(18,2) NULL,CurrencyCode CHAR(3) NOT NULL DEFAULT 'GBP',StartsAt DATETIME2 NULL,EndsAt DATETIME2 NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE',CreatedBy UNIQUEIDENTIFIER NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='FinanceBudgets')
CREATE TABLE FinanceBudgets(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,Name NVARCHAR(200) NOT NULL,PeriodStart DATE NOT NULL,PeriodEnd DATE NOT NULL,CurrencyCode CHAR(3) NOT NULL DEFAULT 'GBP',Status NVARCHAR(30) NOT NULL DEFAULT 'DRAFT',CreatedBy UNIQUEIDENTIFIER NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='FinanceBudgetLines')
CREATE TABLE FinanceBudgetLines(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),BudgetId UNIQUEIDENTIFIER NOT NULL,Category NVARCHAR(120) NOT NULL,PlannedAmount DECIMAL(18,2) NOT NULL,Notes NVARCHAR(500) NULL,FOREIGN KEY(BudgetId) REFERENCES FinanceBudgets(Id));

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='KnowledgeDocuments')
CREATE TABLE KnowledgeDocuments(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,Category NVARCHAR(80) NOT NULL,Title NVARCHAR(250) NOT NULL,Summary NVARCHAR(2000) NULL,Visibility NVARCHAR(30) NOT NULL DEFAULT 'MEMBERS',CurrentVersion INT NOT NULL DEFAULT 1,CreatedBy UNIQUEIDENTIFIER NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='KnowledgeDocumentVersions')
CREATE TABLE KnowledgeDocumentVersions(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),DocumentId UNIQUEIDENTIFIER NOT NULL,VersionNumber INT NOT NULL,FileUrl NVARCHAR(1000) NULL,Body NVARCHAR(MAX) NULL,ChangeNotes NVARCHAR(1000) NULL,UploadedBy UNIQUEIDENTIFIER NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_DocumentVersion UNIQUE(DocumentId,VersionNumber),FOREIGN KEY(DocumentId) REFERENCES KnowledgeDocuments(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='KnowledgeDocumentAccess')
CREATE TABLE KnowledgeDocumentAccess(DocumentId UNIQUEIDENTIFIER NOT NULL,RoleId UNIQUEIDENTIFIER NOT NULL,CanView BIT NOT NULL DEFAULT 1,CanEdit BIT NOT NULL DEFAULT 0,PRIMARY KEY(DocumentId,RoleId),FOREIGN KEY(DocumentId) REFERENCES KnowledgeDocuments(Id),FOREIGN KEY(RoleId) REFERENCES Roles(Id));

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='AiAssistantSessions')
CREATE TABLE AiAssistantSessions(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NULL,UserId UNIQUEIDENTIFIER NOT NULL,Title NVARCHAR(250) NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(UserId) REFERENCES Users(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='AiAssistantMessages')
CREATE TABLE AiAssistantMessages(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),SessionId UNIQUEIDENTIFIER NOT NULL,Role NVARCHAR(20) NOT NULL,Content NVARCHAR(MAX) NOT NULL,SourceRefs NVARCHAR(MAX) NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(SessionId) REFERENCES AiAssistantSessions(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='ModerationQueue')
CREATE TABLE ModerationQueue(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,EntityType NVARCHAR(40) NOT NULL,EntityId UNIQUEIDENTIFIER NOT NULL,ReasonCode NVARCHAR(80) NOT NULL,Confidence DECIMAL(5,4) NULL,Explanation NVARCHAR(2000) NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',ReviewedBy UNIQUEIDENTIFIER NULL,ReviewedAt DATETIME2 NULL,ResolutionNotes NVARCHAR(2000) NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='SmartSummaries')
CREATE TABLE SmartSummaries(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,UserId UNIQUEIDENTIFIER NULL,SummaryType NVARCHAR(40) NOT NULL,PeriodStart DATETIME2 NOT NULL,PeriodEnd DATETIME2 NOT NULL,Content NVARCHAR(MAX) NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='NotificationPreferences')
CREATE TABLE NotificationPreferences(UserId UNIQUEIDENTIFIER PRIMARY KEY,EmergencyAlerts NVARCHAR(20) NOT NULL DEFAULT 'ALWAYS',DirectMessages NVARCHAR(20) NOT NULL DEFAULT 'ON',Mentions NVARCHAR(20) NOT NULL DEFAULT 'ON',CommunityPosts NVARCHAR(20) NOT NULL DEFAULT 'DAILY',Polls NVARCHAR(20) NOT NULL DEFAULT 'ON',Events NVARCHAR(20) NOT NULL DEFAULT 'ON',Marketplace NVARCHAR(20) NOT NULL DEFAULT 'OFF',BusinessPromotions NVARCHAR(20) NOT NULL DEFAULT 'OFF',QuietHoursEnabled BIT NOT NULL DEFAULT 0,QuietStart TIME NULL,QuietEnd TIME NULL,UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(UserId) REFERENCES Users(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='PrivacyPreferences')
CREATE TABLE PrivacyPreferences(UserId UNIQUEIDENTIFIER PRIMARY KEY,PhoneVisibility NVARCHAR(20) NOT NULL DEFAULT 'ADMINS',EmailVisibility NVARCHAR(20) NOT NULL DEFAULT 'ADMINS',WhoCanMessage NVARCHAR(20) NOT NULL DEFAULT 'MEMBERS',WhoCanAddToGroups NVARCHAR(20) NOT NULL DEFAULT 'ADMINS',ShowOnlineStatus BIT NOT NULL DEFAULT 1,ShowProfilePhoto BIT NOT NULL DEFAULT 1,AllowCommunityDiscovery BIT NOT NULL DEFAULT 1,UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(UserId) REFERENCES Users(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='BlockedUsers')
CREATE TABLE BlockedUsers(UserId UNIQUEIDENTIFIER NOT NULL,BlockedUserId UNIQUEIDENTIFIER NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),PRIMARY KEY(UserId,BlockedUserId),FOREIGN KEY(UserId) REFERENCES Users(Id),FOREIGN KEY(BlockedUserId) REFERENCES Users(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='DataExportRequests')
CREATE TABLE DataExportRequests(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),UserId UNIQUEIDENTIFIER NOT NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'QUEUED',DownloadUrl NVARCHAR(1000) NULL,ExpiresAt DATETIME2 NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CompletedAt DATETIME2 NULL,FOREIGN KEY(UserId) REFERENCES Users(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='UserAppPreferences')
CREATE TABLE UserAppPreferences(UserId UNIQUEIDENTIFIER PRIMARY KEY,DataSaverEnabled BIT NOT NULL DEFAULT 0,OfflineCacheEnabled BIT NOT NULL DEFAULT 1,AutoDownloadImages BIT NOT NULL DEFAULT 1,AutoDownloadVideos BIT NOT NULL DEFAULT 0,UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(UserId) REFERENCES Users(Id));

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='CommunityAnalyticsSnapshots')
CREATE TABLE CommunityAnalyticsSnapshots(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,SnapshotDate DATE NOT NULL,MemberCount INT NOT NULL,NewMembers30d INT NOT NULL,MonthlyActivePercent DECIMAL(5,2) NOT NULL,MeetingRsvpPercent DECIMAL(5,2) NOT NULL,PollParticipationPercent DECIMAL(5,2) NOT NULL,OpenIssues INT NOT NULL,ResolvedIssues30d INT NOT NULL,PostMessageCount30d INT NOT NULL,AdminMedianResponseHours DECIMAL(10,2) NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_AnalyticsSnapshot UNIQUE(CommunityId,SnapshotDate),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='CommunityHealthScores')
CREATE TABLE CommunityHealthScores(Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),CommunityId UNIQUEIDENTIFIER NOT NULL,SnapshotDate DATE NOT NULL,EngagementScore DECIMAL(5,2) NOT NULL,MeetingActivityScore DECIMAL(5,2) NOT NULL,IssueResolutionScore DECIMAL(5,2) NOT NULL,ParticipationScore DECIMAL(5,2) NOT NULL,AdminResponseScore DECIMAL(5,2) NOT NULL,OverallScore DECIMAL(5,2) NOT NULL,FormulaVersion NVARCHAR(30) NOT NULL DEFAULT 'v1',Explanation NVARCHAR(2000) NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_HealthScore UNIQUE(CommunityId,SnapshotDate),FOREIGN KEY(CommunityId) REFERENCES Communities(Id));

IF NOT EXISTS(SELECT 1 FROM Permissions WHERE Code='GOVERNANCE_MANAGE') INSERT INTO Permissions(Id,Code,Description) VALUES(NEWID(),'GOVERNANCE_MANAGE','Manage governance proposals and decisions');
IF NOT EXISTS(SELECT 1 FROM Permissions WHERE Code='FORMAL_VOTE_MANAGE') INSERT INTO Permissions(Id,Code,Description) VALUES(NEWID(),'FORMAL_VOTE_MANAGE','Manage formal ballots');
IF NOT EXISTS(SELECT 1 FROM Permissions WHERE Code='FINANCE_MANAGE') INSERT INTO Permissions(Id,Code,Description) VALUES(NEWID(),'FINANCE_MANAGE','Manage community finances');
IF NOT EXISTS(SELECT 1 FROM Permissions WHERE Code='DOCUMENT_MANAGE') INSERT INTO Permissions(Id,Code,Description) VALUES(NEWID(),'DOCUMENT_MANAGE','Manage knowledge documents');
IF NOT EXISTS(SELECT 1 FROM Permissions WHERE Code='MODERATION_REVIEW') INSERT INTO Permissions(Id,Code,Description) VALUES(NEWID(),'MODERATION_REVIEW','Review AI moderation queue');
IF NOT EXISTS(SELECT 1 FROM Permissions WHERE Code='ANALYTICS_VIEW') INSERT INTO Permissions(Id,Code,Description) VALUES(NEWID(),'ANALYTICS_VIEW','View community analytics');

;WITH adminRoles AS (SELECT Id FROM Roles WHERE Name IN ('Owner','Admin'))
INSERT INTO RolePermissions(RoleId,PermissionId)
SELECT r.Id,p.Id FROM adminRoles r CROSS JOIN Permissions p WHERE p.Code IN ('GOVERNANCE_MANAGE','FORMAL_VOTE_MANAGE','FINANCE_MANAGE','DOCUMENT_MANAGE','MODERATION_REVIEW','ANALYTICS_VIEW')
AND NOT EXISTS(SELECT 1 FROM RolePermissions rp WHERE rp.RoleId=r.Id AND rp.PermissionId=p.Id);

CREATE INDEX IX_DecisionRegister_Search ON DecisionRegister(CommunityId,DecisionDate DESC);
CREATE INDEX IX_Proposal_CommunityStatus ON GovernanceProposals(CommunityId,Status,CreatedAt DESC);
CREATE INDEX IX_FinanceTransactions_CommunityDate ON FinanceTransactions(CommunityId,TransactionDate DESC);
CREATE INDEX IX_KnowledgeDocuments_CommunityCategory ON KnowledgeDocuments(CommunityId,Category,UpdatedAt DESC);
CREATE INDEX IX_ModerationQueue_CommunityStatus ON ModerationQueue(CommunityId,Status,CreatedAt DESC);


-- ============================================================
-- SCALABLE PRODUCTION FOUNDATION
-- Redis/BullMQ/object storage are external services; MSSQL stores durable metadata.
-- CommunityShardMap keeps the schema shard-ready without enabling physical shards yet.
-- ============================================================

IF COL_LENGTH('EmergencyAlerts','NotificationQueuedAt') IS NULL ALTER TABLE EmergencyAlerts ADD NotificationQueuedAt DATETIME2 NULL;
IF COL_LENGTH('EmergencyAlerts','NotificationTargetCount') IS NULL ALTER TABLE EmergencyAlerts ADD NotificationTargetCount INT NULL;

IF OBJECT_ID('StoredObjects','U') IS NULL
CREATE TABLE StoredObjects(
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  UploadedBy UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
  CommunityId UNIQUEIDENTIFIER NULL REFERENCES Communities(Id),
  StorageKey NVARCHAR(1000) NOT NULL UNIQUE,
  PublicUrl NVARCHAR(1500) NOT NULL,
  OriginalName NVARCHAR(500) NOT NULL,
  MimeType NVARCHAR(150) NOT NULL,
  SizeBytes BIGINT NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('CommunityShardMap','U') IS NULL
CREATE TABLE CommunityShardMap(
  CommunityId UNIQUEIDENTIFIER PRIMARY KEY REFERENCES Communities(Id),
  ShardId NVARCHAR(100) NOT NULL DEFAULT 'primary',
  AssignedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('AsyncJobAudit','U') IS NULL
CREATE TABLE AsyncJobAudit(
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  QueueName NVARCHAR(100) NOT NULL,
  JobKey NVARCHAR(200) NOT NULL,
  CommunityId UNIQUEIDENTIFIER NULL,
  EntityId UNIQUEIDENTIFIER NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'QUEUED',
  Attempts INT NOT NULL DEFAULT 0,
  LastError NVARCHAR(2000) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  StartedAt DATETIME2 NULL,
  CompletedAt DATETIME2 NULL
);

IF OBJECT_ID('SupportTickets','U') IS NULL
CREATE TABLE SupportTickets(
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  UserId UNIQUEIDENTIFIER NOT NULL REFERENCES Users(Id),
  Category NVARCHAR(40) NOT NULL,
  Subject NVARCHAR(200) NOT NULL,
  Message NVARCHAR(4000) NOT NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'OPEN',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- Query-pattern indexes. These are deliberately composite because CDA Connect is community-centric.
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_CommunityMembers_Community_Status_User' AND object_id=OBJECT_ID('CommunityMembers'))
  CREATE INDEX IX_CommunityMembers_Community_Status_User ON CommunityMembers(CommunityId,Status,UserId) INCLUDE(JoinedAt);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_Messages_Conversation_Created_Desc' AND object_id=OBJECT_ID('Messages'))
  CREATE INDEX IX_Messages_Conversation_Created_Desc ON Messages(ConversationId,CreatedAt DESC) INCLUDE(SenderUserId,MessageType,IsDeleted);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_CommunityPosts_Community_Deleted_Pinned_Created' AND object_id=OBJECT_ID('CommunityPosts'))
  CREATE INDEX IX_CommunityPosts_Community_Deleted_Pinned_Created ON CommunityPosts(CommunityId,IsDeleted,IsPinned,CreatedAt DESC) INCLUDE(CreatedBy,PostType);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_EmergencyAlerts_Community_Active_Created' AND object_id=OBJECT_ID('EmergencyAlerts'))
  CREATE INDEX IX_EmergencyAlerts_Community_Active_Created ON EmergencyAlerts(CommunityId,Active,CreatedAt DESC) INCLUDE(Severity,AlertType,NotificationTargetCount);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_AuditLogs_Community_Created' AND object_id=OBJECT_ID('AuditLogs'))
  CREATE INDEX IX_AuditLogs_Community_Created ON AuditLogs(CommunityId,CreatedAt DESC) INCLUDE(UserId,Action,EntityType,EntityId);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_UserSessions_User_Expiry' AND object_id=OBJECT_ID('UserSessions'))
  CREATE INDEX IX_UserSessions_User_Expiry ON UserSessions(UserId,ExpiresAt) INCLUDE(RevokedAt);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_UserDevices_User_LastActive' AND object_id=OBJECT_ID('UserDevices'))
  CREATE INDEX IX_UserDevices_User_LastActive ON UserDevices(UserId,LastActiveAt DESC) INCLUDE(DeviceToken,Platform);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_StoredObjects_User_Created' AND object_id=OBJECT_ID('StoredObjects'))
  CREATE INDEX IX_StoredObjects_User_Created ON StoredObjects(UploadedBy,CreatedAt DESC);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_AsyncJobAudit_Queue_Status_Created' AND object_id=OBJECT_ID('AsyncJobAudit'))
  CREATE INDEX IX_AsyncJobAudit_Queue_Status_Created ON AsyncJobAudit(QueueName,Status,CreatedAt DESC);
