import React from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View,useColorScheme,useWindowDimensions,Platform,type PressableProps,type TextInputProps,type TextProps,type ViewStyle,type TextStyle,type StyleProp} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { colors,darkColors,highContrastColors } from '../theme';
import { textScaleValue,useAccessibility } from '../store/accessibility';

export function useAppTheme(){const scheme=useColorScheme();const a=useAccessibility();const dark=a.themeMode==='dark'||(a.themeMode==='system'&&scheme==='dark');const palette=a.highContrast?highContrastColors:dark?darkColors:colors;return {palette,scale:textScaleValue(a.textScale),prefs:a};}
const tx=(base:any,scale:number):TextStyle=>({...(base||{}),fontSize:typeof base?.fontSize==='number'?base.fontSize*scale:base?.fontSize,lineHeight:typeof base?.lineHeight==='number'?base.lineHeight*scale:base?.lineHeight});
export function AText({children,style,role='text',label}:{children:React.ReactNode;style?:any;role?:any;label?:string}){const{palette,scale}=useAppTheme();const flat=StyleSheet.flatten(style)||{};return <Text accessibilityRole={role} accessibilityLabel={label} allowFontScaling maxFontSizeMultiplier={2} style={[{color:palette.text,fontSize:15*scale},tx(flat,scale),style&&{...flat,color:flat.color??palette.text}]}>{children}</Text>}
export function Screen({children,scroll=false,contentStyle}:{children:React.ReactNode;scroll?:boolean;contentStyle?:ViewStyle}){const{palette}=useAppTheme();const{width}=useWindowDimensions();const web=Platform.OS==='web';const compact=width<480;const content=<View style={[s.content,{paddingHorizontal:compact?12:18},web&&{width:'100%',alignSelf:'stretch',paddingHorizontal:compact?12:24},contentStyle]}>{children}</View>;return <SafeAreaView style={[s.safe,{backgroundColor:palette.background}]}>{scroll?<ScrollView showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" contentContainerStyle={[s.scrollContent,web&&{width:'100%'}]}>{content}</ScrollView>:content}</SafeAreaView>}
export function Card({children,style}:{children:React.ReactNode;style?:StyleProp<ViewStyle>}){const{palette}=useAppTheme();return <View style={[s.card,{backgroundColor:palette.surface,borderColor:palette.border},style]}>{children}</View>}
export function Title({children}:{children:React.ReactNode}){const{palette,scale}=useAppTheme();return <Text accessibilityRole="header" allowFontScaling style={[s.title,{color:palette.text,fontSize:28*scale}]}>{children}</Text>}
export function SectionTitle({children,action}:{children:React.ReactNode;action?:React.ReactNode}){const{palette,scale}=useAppTheme();return <View style={s.sectionRow}><Text accessibilityRole="header" allowFontScaling style={[s.sectionTitle,{color:palette.text,fontSize:18*scale}]}>{children}</Text>{action}</View>}
export function Muted({children,style,...props}:{children:React.ReactNode;style?:any}&TextProps){const{palette,scale}=useAppTheme();return <Text {...props} allowFontScaling style={[s.muted,{color:palette.muted,fontSize:14*scale,lineHeight:20*scale},style]}>{children}</Text>}
export function Input(p:TextInputProps){const{palette,scale,prefs}=useAppTheme();return <TextInput allowFontScaling placeholderTextColor={palette.muted} accessibilityLabel={p.accessibilityLabel??p.placeholder} {...p} style={[s.input,{backgroundColor:palette.surface,borderColor:palette.border,color:palette.text,fontSize:15*scale,minHeight:prefs.largeTouchTargets?50:44},p.multiline&&s.multiline,p.style]}/>}
export function Button({title,loading,variant='primary',icon,...p}:{title:string;loading?:boolean;variant?:'primary'|'secondary'|'danger'|'success'|'ghost';icon?:keyof typeof Ionicons.glyphMap}&PressableProps){const{palette,scale,prefs}=useAppTheme();const fg=variant==='primary'?palette.navy:variant==='secondary'||variant==='ghost'?palette.primary:'#fff';return <Pressable accessibilityRole="button" accessibilityLabel={p.accessibilityLabel??title} {...p} style={({pressed})=>[s.button,{backgroundColor:palette.accent,minHeight:prefs.largeTouchTargets?52:46},variant==='secondary'&&{backgroundColor:'transparent',borderWidth:1.5,borderColor:palette.primary},variant==='danger'&&{backgroundColor:palette.danger},variant==='success'&&{backgroundColor:palette.success},variant==='ghost'&&{backgroundColor:'transparent'},pressed&&{opacity:.82,transform:[{scale:.99}]},p.disabled&&{opacity:.5}]}>{loading?<ActivityIndicator color={fg}/>:<View style={s.buttonInner}>{icon&&<Ionicons name={icon} size={20} color={fg}/>}<Text allowFontScaling style={[s.buttonText,{color:fg,fontSize:15*scale}]}>{title}</Text></View>}</Pressable>}
export function IconTile({icon,label,onPress,tone='blue'}:{icon:keyof typeof Ionicons.glyphMap;label:string;onPress?:()=>void;tone?:'blue'|'red'|'green'|'orange'|'purple'}){const{palette,scale,prefs}=useAppTheme();const fg={blue:palette.primary,red:palette.danger,green:palette.success,orange:palette.warning,purple:palette.purple}[tone];const bg={blue:palette.primarySoft,red:palette.dangerSoft,green:palette.successSoft,orange:palette.warningSoft,purple:palette.primarySoft}[tone];return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={!onPress} onPress={onPress} style={({pressed})=>[s.iconTile,{minHeight:prefs.largeTouchTargets?76:64},pressed&&{opacity:.72,transform:[{scale:.98}]},!onPress&&{opacity:.55}]}><View style={[s.iconBubble,{backgroundColor:bg}]}><Ionicons name={icon} size={22} color={fg}/></View><Text allowFontScaling style={[s.iconLabel,{color:palette.text,fontSize:12*scale}]}>{label}</Text></Pressable>}
export function Avatar({name,size=44,backgroundColor,textColor='#fff'}:{name:string;size?:number;backgroundColor?:string;textColor?:string}){const{palette}=useAppTheme();const initials=name.split(' ').filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'CDA';return <View accessible accessibilityRole="image" accessibilityLabel={`${name} profile`} style={{width:size,height:size,borderRadius:size/2,backgroundColor:backgroundColor??palette.primary,alignItems:'center',justifyContent:'center'}}><Text style={{color:textColor,fontWeight:'800',fontSize:size*.32}}>{initials}</Text></View>}
export function Badge({text,tone='blue'}:{text:string;tone?:'blue'|'green'|'red'|'orange'|'gray'}){const{palette,scale}=useAppTheme();const fg={blue:palette.primary,green:palette.success,red:palette.danger,orange:palette.warning,gray:palette.muted}[tone];const bg={blue:palette.primarySoft,green:palette.successSoft,red:palette.dangerSoft,orange:palette.warningSoft,gray:palette.background}[tone];return <View style={[s.badge,{backgroundColor:bg}]}><Text allowFontScaling style={[s.badgeText,{color:fg,fontSize:11*scale}]}>{text}</Text></View>}
export function Header({title,subtitle,right}:{title:string;subtitle?:string;right?:React.ReactNode}){const{palette,scale}=useAppTheme();return <View style={s.header}><View style={{flex:1}}><Text accessibilityRole="header" allowFontScaling style={[s.headerTitle,{color:palette.text,fontSize:24*scale}]}>{title}</Text>{subtitle?<Text allowFontScaling style={[s.headerSubtitle,{color:palette.muted,fontSize:14*scale}]}>{subtitle}</Text>:null}</View>{right}</View>}
export function EmptyState({icon='albums-outline',title,body}:{icon?:keyof typeof Ionicons.glyphMap;title:string;body:string}){const{palette}=useAppTheme();return <Card style={{alignItems:'center',paddingVertical:28}}><Ionicons name={icon} size={34} color={palette.primary}/><SectionTitle>{title}</SectionTitle><Muted style={{textAlign:'center',marginTop:6}}>{body}</Muted></Card>}
export const s=StyleSheet.create({safe:{flex:1,width:'100%'},content:{flex:1,width:'100%',minWidth:0,paddingTop:8},scrollContent:{flexGrow:1,width:'100%',paddingBottom:24},card:{width:'100%',minWidth:0,borderRadius:16,padding:16,borderWidth:1,marginBottom:12,shadowColor:'#0F2C59',shadowOpacity:.06,shadowRadius:12,shadowOffset:{width:0,height:4},elevation:2},title:{fontWeight:'800',letterSpacing:-.5,flexShrink:1},muted:{flexShrink:1},input:{width:'100%',minWidth:0,borderWidth:1,borderRadius:12,paddingHorizontal:14,paddingVertical:12,marginBottom:12},multiline:{minHeight:96,textAlignVertical:'top'},button:{maxWidth:'100%',minWidth:0,borderRadius:10,paddingVertical:12,paddingHorizontal:16,alignItems:'center',justifyContent:'center',marginVertical:6},buttonText:{fontWeight:'800',flexShrink:1,textAlign:'center'},buttonInner:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,minWidth:0},sectionRow:{flexDirection:'row',flexWrap:'wrap',gap:8,alignItems:'center',justifyContent:'space-between',marginTop:8,marginBottom:12},sectionTitle:{fontWeight:'800',flexShrink:1},iconTile:{flex:1,minWidth:64,alignItems:'center',justifyContent:'center',gap:7,paddingVertical:4},iconBubble:{width:46,height:46,borderRadius:14,alignItems:'center',justifyContent:'center'},iconLabel:{fontWeight:'700',textAlign:'center',flexShrink:1},badge:{maxWidth:'100%',paddingHorizontal:9,paddingVertical:4,borderRadius:999,alignSelf:'flex-start'},badgeText:{fontWeight:'800',flexShrink:1},header:{minWidth:0,flexDirection:'row',flexWrap:'wrap',gap:10,alignItems:'center',justifyContent:'space-between',marginBottom:18},headerTitle:{fontWeight:'800',letterSpacing:-.3,flexShrink:1},headerSubtitle:{marginTop:3,flexShrink:1}});
