import {test,expect,type Page} from '@playwright/test';
const user={Id:'11111111-1111-4111-8111-111111111111',FirstName:'Adekola',LastName:'Ayannuga',Email:'member@example.test',CreatedAt:'2026-01-01T12:00:00Z',Username:'member'};
const community={Id:'22222222-2222-4222-8222-222222222222',Name:'Royal View CDA',Description:'Moving forward for progress',MemberCount:2,Role:'Owner'};
async function setup(page:Page,long=false){
 await page.clock.setFixedTime(new Date('2026-09-17T12:00:00Z'));
 await page.route('https://fonts.**',r=>r.abort());
 await page.route('**/socket.io/**',r=>r.abort());
 await page.route('**/api/v1/**',async r=>{const path=new URL(r.request().url()).pathname;let json:any=[];const u=long?{...user,FirstName:'Alexandria-Margaret',LastName:'A very long family name with several words'}:user;
 if(path.endsWith('/auth/refresh'))json={accessToken:'fixture-access',user:u};
 else if(path.endsWith('/users/me')||path.endsWith('/users/account'))json=u;
 else if(path.endsWith('/communities'))json=[community];
 else if(path.endsWith('/communities/'+community.Id))json=long?{...community,Name:'A community with an unusually long descriptive name'}:community;
 else if(path.endsWith('/capabilities'))json={permissions:['MEMBER_ROLE_CHANGE']};
 else if(path.endsWith('/personal-activity'))json={stats:{},items:[],nextCursor:null};
 else if(path.endsWith('/recent-activity'))json={items:[],nextCursor:null};
 else if(path.includes('/weather'))json={available:false};
 else if(path.includes('/settings'))json={};
 return r.fulfill({json,headers:{'access-control-allow-origin':'http://127.0.0.1:4173','access-control-allow-credentials':'true'}});});
}
const pages=[['profile','/profile','.profile-compact-banner'],['account','/profile/account','.account-dashboard'],['community','/community/'+community.Id+'/menu','.community-hero'],['settings','/settings','.settings-list'],['home','/home','.home-activities']] as const;
for(const width of [390,768,1440])for(const [name,path,selector] of pages)test(`${name} at ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await setup(page);await page.goto(path);await expect(page.locator(selector).first()).toBeVisible();await page.evaluate(()=>document.fonts.ready);await expect(page).toHaveScreenshot(`${name}-${width}.png`,{animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)});
for(const size of [{width:320,height:800},{width:844,height:390}])test(`long names, enlarged text and missing images ${size.width}`,async({page})=>{await page.setViewportSize(size);await setup(page,true);for(const path of ['/profile','/community/'+community.Id+'/menu']){await page.goto(path);await expect(page.locator('.profile-compact-banner,.community-hero').first()).toBeVisible();await page.addStyleTag({content:':root{font-size:125%;--safe-area-inset-top:24px;--safe-area-inset-bottom:20px}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}});
test('profile statistics toggle, account navigation and no browser token storage',async({page})=>{await setup(page);await page.goto('/profile');await expect(page.locator('#profile-statistics')).toBeHidden();await page.getByRole('button',{name:'Show profile statistics'}).click();await expect(page.locator('#profile-statistics')).toBeVisible();await page.getByRole('button',{name:'Hide profile statistics'}).click();await expect(page.locator('#profile-statistics')).toBeHidden();await page.getByRole('link',{name:'Account settings',exact:true}).click();await page.getByRole('link',{name:/Email address/}).click();await expect(page.getByLabel('Current password')).toBeVisible();expect(await page.evaluate(()=>[localStorage.getItem('cda-connect-session'),sessionStorage.getItem('cda-connect-session')])).toEqual([null,null])});
test('cover images extend behind mobile headers with iOS and Android safe areas',async({page})=>{await setup(page);const cover='http://127.0.0.1:4173/test-cover.svg';await page.route('**/test-cover.svg',r=>r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400"><rect width="800" height="400" fill="#073B78"/><circle cx="400" cy="200" r="100" fill="#078A3A"/></svg>'}));await page.route('**/api/v1/users/me',r=>r.fulfill({json:{...user,CoverImage:cover,ProfileImage:cover},headers:{'access-control-allow-origin':'http://127.0.0.1:4173','access-control-allow-credentials':'true'}}));for(const [width,inset] of [[390,47],[412,24]]){await page.setViewportSize({width,height:850});await page.goto('/profile');await expect(page.locator('.profile-compact-banner')).toBeVisible();await page.addStyleTag({content:`:root{--safe-area-inset-top:${inset}px}`});await expect(page.locator('.profile-avatar img')).toHaveJSProperty('complete',true);expect(await page.locator('.profile-cover-workspace').evaluate(el=>getComputedStyle(el,'::before').backgroundImage)).toContain('test-cover.svg');expect(await page.locator('.topbar').evaluate(el=>parseFloat(getComputedStyle(el).paddingTop))).toBeGreaterThanOrEqual(inset);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}});
