import {useState} from 'react';
import {Alert,Linking,Platform,Pressable,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import Constants from 'expo-constants';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Button,Card,Muted,Screen,useAppTheme} from '@/components/UI';

const menu=[['person-outline','Account Settings','/account-settings'],['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;
const principles=[['Our Mission','Empower communities by connecting people, resources, and opportunities to create a better tomorrow together.','locate-outline'],['Our Vision','A world where every community thrives through connection, collaboration and shared purpose.','eye-outline'],['Our Values','Community First · Trust & Transparency · Inclusion & Respect · Innovation & Impact','heart-outline'],['Built for communities','Designed for residents, leaders, organisations and businesses.','people-outline'],['Your data, your control','We take privacy and security seriously. You are in control of your data.','shield-checkmark-outline'],['Made with care','Simple, accessible and inclusive for everyone.','heart-circle-outline']] as const;
type Panel='mission'|'vision'|'values'|'communities'|'data'|'care'|'info'|'team'|'terms'|'policy'|'guidelines'|null;

export default function About(){const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;const[panel,setPanel]=useState<Panel>(null);const version=Constants.expoConfig?.version||'1.0.0';
 if(panel)return <Detail panel={panel} version={version} back={()=>setPanel(null)}/>;
 return <Screen scroll contentStyle={s.page}><View style={s.heading}><Text style={[s.title,{color:palette.text}]}>About CDA Connect</Text><Muted>Learn more about our mission, values, and the app you can trust.</Muted></View><View style={[s.layout,!desktop&&s.stack]}>{desktop?<SettingsMenu/>:null}<View style={s.main}>
  <Card style={[s.brand,!desktop&&s.brandMobile]}><View style={s.brandCopy}><View style={[s.logo,{borderColor:palette.success}]}><Ionicons name="home-outline" size={54} color={palette.success}/><Ionicons name="people" size={29} color={palette.success}/></View><Text style={[s.brandName,{color:palette.success}]}>CDA CONNECT</Text><Text style={[s.tagline,{color:palette.navy}]}>Stronger Communities, Better Lives</Text><View style={[s.versionChip,{backgroundColor:palette.successSoft}]}><Text style={{color:palette.success,fontWeight:'900'}}>v{version}</Text></View><Text style={[s.intro,{color:palette.text}]}>CDA Connect is a community platform that brings people together. Share updates, join discussions, access local services, and work together to build stronger communities.</Text></View><View style={[s.illustration,{backgroundColor:palette.successSoft}]}><Ionicons name="earth-outline" size={96} color={palette.success}/><View style={s.people}><Ionicons name="people-circle-outline" size={72} color={palette.navy}/></View></View></Card>
  <View style={s.grid}>{principles.slice(0,3).map(([name,body,icon],i)=><InfoCard key={name} name={name} body={body} icon={icon} onPress={()=>setPanel((['mission','vision','values'] as Panel[])[i])}/>)}</View><View style={s.grid}>{principles.slice(3).map(([name,body,icon],i)=><InfoCard key={name} name={name} body={body} icon={icon} onPress={()=>setPanel((['communities','data','care'] as Panel[])[i])}/>)}</View>
  <Card><View style={s.infoHeader}><View style={[s.smallIcon,{backgroundColor:palette.successSoft}]}><Ionicons name="information-circle-outline" size={27} color={palette.success}/></View><Text style={[s.sectionTitle,{color:palette.text}]}>App Information</Text></View><View style={s.infoGrid}>{[['Version',version],['Build','100'],['Release Date','20 August 2026'],['Developed by','CDA Connect Team']].map(([a,b])=><Pressable key={a} onPress={()=>setPanel('info')} style={s.infoItem}><Muted>{a}</Muted><Text style={[s.infoValue,{color:palette.text}]}>{b}</Text></Pressable>)}</View></Card>
  {!desktop?<Card><SectionTitle title="Quick Links"/><Action icon="compass-outline" label="Explore Features" onPress={()=>router.push('/(tabs)/home')}/><Action icon="lock-closed-outline" label="Privacy & Safety" onPress={()=>router.push('/privacy')}/><Action icon="people-outline" label="Meet the Team" onPress={()=>setPanel('team')}/><Action icon="document-text-outline" label="Terms of Service" onPress={()=>setPanel('terms')}/><Action icon="document-lock-outline" label="Privacy Policy" onPress={()=>setPanel('policy')}/><Action icon="person-outline" label="Community Guidelines" onPress={()=>setPanel('guidelines')}/></Card>:null}
  <View style={[s.bottom,!desktop&&s.stack]}><Card style={s.flex}><View style={s.contactRow}><View style={[s.smallIcon,{backgroundColor:palette.successSoft}]}><Ionicons name="help-circle-outline" size={27} color={palette.success}/></View><View style={{flex:1}}><Text style={[s.sectionTitle,{color:palette.text}]}>Need help?</Text><Muted>Visit our Help Center for articles, guides and support.</Muted></View></View><Button title="Go to Help Center" variant="secondary" onPress={()=>router.push('/help')}/></Card><Card style={s.flex}><View style={s.contactRow}><View style={[s.smallIcon,{backgroundColor:palette.successSoft}]}><Ionicons name="mail-outline" size={27} color={palette.success}/></View><View style={{flex:1}}><Text style={[s.sectionTitle,{color:palette.text}]}>Get in touch</Text><Muted>We’d love to hear from you.</Muted><Text style={{color:palette.success,fontWeight:'900'}}>support@cdaconnect.local</Text></View></View><Button title="Email Support" variant="success" onPress={()=>Linking.openURL('mailto:support@cdaconnect.local?subject=CDA%20Connect')}/></Card></View>
  {desktop?<View style={s.footer}><Muted>© 2026 CDA Connect. All rights reserved.</Muted><Pressable onPress={()=>setPanel('terms')}><Text style={s.footerLink}>Terms of Service</Text></Pressable><Pressable onPress={()=>setPanel('policy')}><Text style={s.footerLink}>Privacy Policy</Text></Pressable><Pressable onPress={()=>setPanel('guidelines')}><Text style={s.footerLink}>Community Guidelines</Text></Pressable></View>:null}
 </View></View></Screen>}

function SettingsMenu(){const{palette}=useAppTheme();return <Card style={s.menu}><Text style={[s.menuTitle,{color:palette.text}]}>Settings Menu</Text>{menu.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[s.menuRow,label==='About CDA Connect'&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={label==='About CDA Connect'?palette.success:palette.navy}/><Text style={{fontWeight:'800',color:label==='About CDA Connect'?palette.success:palette.text}}>{label}</Text></Pressable>)}</Card>}
function InfoCard({name,body,icon,onPress}:{name:string;body:string;icon:keyof typeof Ionicons.glyphMap;onPress:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={onPress} style={[s.infoCard,{backgroundColor:palette.surface,borderColor:palette.border}]}><View style={[s.bigIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={40} color={palette.success}/></View><Text style={[s.cardTitle,{color:palette.navy}]}>{name}</Text><Muted style={{textAlign:'center'}}>{body}</Muted><Text style={{color:palette.success,fontWeight:'900'}}>Learn more →</Text></Pressable>}
function SectionTitle({title}:{title:string}){const{palette}=useAppTheme();return <Text style={[s.sectionTitle,{color:palette.text}]}>{title}</Text>}
function Action({icon,label,onPress}:{icon:keyof typeof Ionicons.glyphMap;label:string;onPress:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={onPress} style={[s.action,{borderBottomColor:palette.border}]}><View style={[s.actionIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={20} color={palette.success}/></View><Text style={[s.actionText,{color:palette.text}]}>{label}</Text><Ionicons name="chevron-forward" size={19} color={palette.muted}/></Pressable>}
function Detail({panel,version,back}:{panel:Exclude<Panel,null>;version:string;back:()=>void}){const{palette}=useAppTheme();const item=principles.find((_,i)=>(['mission','vision','values','communities','data','care'] as string[])[i]===panel);const legal:Record<string,[string,string]>= {team:['Meet the CDA Connect Team','CDA Connect is built by people committed to safer, stronger and better-connected communities. Product, engineering, support and community partners work together to improve the platform.'],terms:['Terms of Service','Use CDA Connect respectfully and lawfully. Community owners remain responsible for their local governance, while every member must protect privacy, avoid abuse and follow applicable community rules.'],policy:['Privacy Policy','CDA Connect collects only the information needed to operate community features. Privacy settings control visibility, and personal data is never sold. Contact support for access, correction or deletion requests.'],guidelines:['Community Guidelines','Be respectful, share accurate information, protect private details, avoid harassment and report unsafe content. Emergency situations should be directed to the appropriate local authorities.'],info:['App Information',`Version ${version}\nBuild 100\nReleased 20 August 2026\nDeveloped by the CDA Connect Team.`]};const title=item?.[0]||legal[panel]?.[0]||'About CDA Connect';const body=item?.[1]||legal[panel]?.[1]||'';const icon=(item?.[2]||'information-circle-outline') as keyof typeof Ionicons.glyphMap;return <Screen scroll contentStyle={s.detail}><Pressable onPress={back} style={s.back}><Ionicons name="chevron-back" size={27} color={palette.text}/><Text style={[s.detailTitle,{color:palette.text}]}>About CDA Connect</Text></Pressable><Card style={s.detailCard}><View style={[s.detailIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={50} color={palette.success}/></View><Text style={[s.detailHeading,{color:palette.navy}]}>{title}</Text><Text style={[s.detailBody,{color:palette.text}]}>{body}</Text>{panel==='data'?<Button title="Open Privacy & Safety" variant="success" onPress={()=>router.push('/privacy')}/>:panel==='communities'?<Button title="Explore Communities" variant="success" onPress={()=>router.push('/(tabs)/communities')}/>:panel==='team'?<Button title="Contact the Team" variant="success" onPress={()=>Linking.openURL('mailto:support@cdaconnect.local')}/>:null}</Card></Screen>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1380,alignSelf:'center'},heading:{marginBottom:22},title:{fontSize:30,fontWeight:'900',marginBottom:5},layout:{flexDirection:'row',alignItems:'flex-start',gap:16},stack:{flexDirection:'column'},menu:{width:245,padding:12},menuTitle:{fontWeight:'900',margin:8},menuRow:{minHeight:48,borderRadius:10,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:11},main:{flex:1,width:'100%',minWidth:0,gap:14},brand:{flexDirection:'row',alignItems:'center',padding:28,gap:30},brandMobile:{flexDirection:'column'},brandCopy:{flex:1,alignItems:'center'},logo:{width:92,height:92,borderRadius:24,borderWidth:3,alignItems:'center',justifyContent:'center'},brandName:{fontSize:29,fontWeight:'900',marginTop:10},tagline:{fontWeight:'900',marginTop:3},versionChip:{paddingHorizontal:12,paddingVertical:6,borderRadius:15,marginVertical:12},intro:{fontSize:15,lineHeight:23,textAlign:'center',maxWidth:540},illustration:{flex:1,minWidth:240,minHeight:200,borderRadius:30,alignItems:'center',justifyContent:'center'},people:{position:'absolute',bottom:15},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},infoCard:{flex:1,minWidth:210,minHeight:245,borderWidth:1,borderRadius:15,padding:18,alignItems:'center',justifyContent:'space-between'},bigIcon:{width:76,height:76,borderRadius:38,alignItems:'center',justifyContent:'center'},cardTitle:{fontSize:17,fontWeight:'900',textAlign:'center'},infoHeader:{flexDirection:'row',alignItems:'center',gap:11,marginBottom:10},smallIcon:{width:46,height:46,borderRadius:23,alignItems:'center',justifyContent:'center'},sectionTitle:{fontSize:18,fontWeight:'900'},infoGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},infoItem:{flex:1,minWidth:135,padding:10},infoValue:{fontWeight:'900',marginTop:4},action:{minHeight:64,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:11},actionIcon:{width:39,height:39,borderRadius:12,alignItems:'center',justifyContent:'center'},actionText:{flex:1,fontWeight:'900'},bottom:{flexDirection:'row',gap:14},flex:{flex:1,minWidth:0},contactRow:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:12},footer:{flexDirection:'row',justifyContent:'center',gap:25,padding:14,flexWrap:'wrap'},footerLink:{color:'#15803D',fontWeight:'800'},detail:{width:'100%',maxWidth:720,alignSelf:'center'},back:{minHeight:54,flexDirection:'row',alignItems:'center',gap:8},detailTitle:{fontSize:23,fontWeight:'900'},detailCard:{alignItems:'center'},detailIcon:{width:92,height:92,borderRadius:30,alignItems:'center',justifyContent:'center'},detailHeading:{fontSize:27,fontWeight:'900',marginTop:17,textAlign:'center'},detailBody:{fontSize:16,lineHeight:26,marginTop:15,textAlign:'center'}});
