import {Image,Linking,Platform,Pressable,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import Constants from 'expo-constants';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Card,Muted,Screen,useAppTheme} from '@/components/UI';

const menu=[['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;
const aboutItems=[['Our Mission','Connect people, resources and opportunities.','/our-mission'],['Our Vision','Stronger communities built through trusted collaboration.','/our-vision'],['Our Values','Community, trust, inclusion, safety and meaningful impact.','/our-values'],['Built for Communities','A practical platform for residents, leaders and organisations.','/built-for-communities']] as const;
const legalItems=[['Terms of Service','Rules governing access to and use of CDA Connect.','/terms-of-service'],['Privacy Policy','How account and community information is handled.','/privacy-policy'],['Community Guidelines','Standards for safe, respectful community participation.','/community-guidelines']] as const;

export default function About(){const{palette}=useAppTheme(),{width}=useWindowDimensions(),desktop=Platform.OS==='web'&&width>=900,version=Constants.expoConfig?.version||Constants.nativeAppVersion||'1.0.0';
 return <Screen scroll contentStyle={s.page}><View style={s.heading}><Muted>Learn about our purpose, principles and the app communities can trust.</Muted></View><View style={[s.layout,!desktop&&s.stack]}>{desktop?<SettingsMenu/>:null}<View style={s.main}>
  <Card style={s.brand}><Image source={require('../assets/branding/cda-connect-logo.png')} resizeMode="contain" style={s.logo}/><View style={s.brandCopy}><Text style={[s.brandName,{color:palette.success}]}>CDA CONNECT</Text><Text style={[s.tagline,{color:palette.text}]}>Stronger Communities, Better Lives</Text><Muted style={{textAlign:'center'}}>CDA Connect brings residents, leaders and organisations together to share updates, participate in community decisions, organise activities and access local resources.</Muted></View></Card>
  <Text style={[s.sectionTitle,{color:palette.text}]}>Who We Are</Text><Card style={s.list}>{aboutItems.map(([title,summary,path])=><PolicyLink key={title} title={title} summary={summary} press={()=>router.push(path as any)}/>)}</Card>
  <Text style={[s.sectionTitle,{color:palette.text}]}>Policies & Guidelines</Text><Card style={s.list}>{legalItems.map(([title,summary,path])=><PolicyLink key={title} title={title} summary={summary} press={()=>router.push(path as any)}/>)}</Card>
  <View style={s.actions}><Pressable accessibilityRole="link" onPress={()=>Linking.openURL('https://www.cdaconnect.org')} style={[s.action,{borderColor:palette.primary}]}><Ionicons name="globe-outline" size={21} color={palette.primary}/><Text style={[s.actionText,{color:palette.primary}]}>Visit Website</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>router.push('/help')} style={[s.action,{borderColor:palette.primary}]}><Ionicons name="headset-outline" size={21} color={palette.primary}/><Text style={[s.actionText,{color:palette.primary}]}>Help & Support</Text></Pressable></View>
  <Text accessibilityLabel={`CDA Connect version ${version}`} style={[s.version,{color:palette.muted}]}>CDA Connect · Version {version}</Text>
 </View></View></Screen>}

function PolicyLink({title,summary,press}:{title:string;summary:string;press:()=>void}){const{palette}=useAppTheme();return <Pressable accessibilityRole="link" onPress={press} style={[s.itemHead,{borderBottomColor:palette.border,borderBottomWidth:1}]}><View style={s.grow}><Text style={[s.itemTitle,{color:palette.text}]}>{title}</Text><Muted>{summary}</Muted></View><Ionicons name="chevron-forward" size={21} color={palette.muted}/></Pressable>}
function SettingsMenu(){const{palette}=useAppTheme();return <Card style={s.menu}><Text style={[s.menuTitle,{color:palette.text}]}>Settings Menu</Text>{menu.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[s.menuRow,label==='About CDA Connect'&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={label==='About CDA Connect'?palette.success:palette.navy}/><Text style={{fontWeight:'800',color:label==='About CDA Connect'?palette.success:palette.text}}>{label}</Text></Pressable>)}</Card>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1380,alignSelf:'center',paddingBottom:120},heading:{marginBottom:14},layout:{flexDirection:'row',alignItems:'flex-start',gap:16},stack:{flexDirection:'column'},menu:{width:245,padding:12},menuTitle:{fontWeight:'900',margin:8},menuRow:{minHeight:48,borderRadius:10,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:11},main:{flex:1,width:'100%',minWidth:0,gap:14},brand:{alignItems:'center',gap:10,padding:18},logo:{width:92,height:92},brandCopy:{width:'100%',maxWidth:620,alignItems:'center',gap:4},brandName:{fontSize:22,fontWeight:'900',textAlign:'center'},tagline:{fontSize:15,fontWeight:'900',textAlign:'center',marginBottom:4},sectionTitle:{fontSize:20,fontWeight:'900',marginTop:3},list:{paddingVertical:0,overflow:'hidden'},item:{borderBottomWidth:1},itemHead:{minHeight:76,paddingVertical:12,flexDirection:'row',alignItems:'center',gap:10},grow:{flex:1,minWidth:0},itemTitle:{fontSize:17,fontWeight:'900',marginBottom:3},itemBody:{borderTopWidth:1,padding:14,gap:11},detail:{flexDirection:'row',alignItems:'flex-start',gap:9},bullet:{width:7,height:7,borderRadius:4,marginTop:7,flexShrink:0},detailText:{flex:1,minWidth:0,fontSize:15,lineHeight:22},actions:{flexDirection:'row',gap:10},action:{flex:1,minHeight:52,borderWidth:1.5,borderRadius:12,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},actionText:{fontWeight:'900',textAlign:'center'},version:{textAlign:'center',fontSize:13,fontWeight:'700',paddingTop:8,paddingBottom:4}});
