import {Platform,Pressable,StyleSheet,Switch,Text,View,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Button,Card,Muted,Screen,useAppTheme} from '@/components/UI';
import {AccentColor,TextScale,ThemeMode,useAccessibility} from '@/store/accessibility';

const themes:[ThemeMode,string,string,keyof typeof Ionicons.glyphMap][]=[['light','Light','Clean and bright','sunny-outline'],['dark','Dark','Easy on the eyes','moon-outline'],['system','System','Follow device settings','desktop-outline']];
const scales:[TextScale,string,string][]=[['normal','A','Small'],['large','A','Medium'],['xlarge','A','Large']];
const accents:AccentColor[]=['#15803D','#2563EB','#7C3AED','#0891B2','#F59E0B','#DC2626','#DB2777'];
const menu=[['person-outline','Account Settings','/account-settings'],['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;

export default function Appearance(){
 const a=useAccessibility();const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;
 return <Screen scroll contentStyle={st.page}><View style={st.heading}><Text style={[st.title,{color:palette.text}]}>Appearance</Text><Muted>Customize how CDA Connect looks and feels for you.</Muted></View>
  <View style={[st.layout,!desktop&&st.stack]}>
   {desktop?<Card style={st.menu}><Text style={[st.menuTitle,{color:palette.text}]}>Settings Menu</Text>{menu.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[st.menuRow,label==='Appearance'&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={label==='Appearance'?palette.success:palette.navy}/><Text style={{fontWeight:'800',color:label==='Appearance'?palette.success:palette.text}}>{label}</Text></Pressable>)}</Card>:null}
   <View style={st.main}>
    <Text style={[st.groupTitle,{color:palette.text}]}>Theme</Text><View style={st.themeGrid}>{themes.map(([value,label,body,icon])=><Pressable accessibilityState={{selected:a.themeMode===value}} key={value} onPress={()=>a.update({themeMode:value})} style={[st.theme,{borderColor:a.themeMode===value?palette.success:palette.border,backgroundColor:a.themeMode===value?palette.successSoft:palette.surface}]}><Ionicons name={icon} size={29} color={a.themeMode===value?palette.success:palette.navy}/><Text style={[st.optionTitle,{color:palette.text}]}>{label}</Text><Muted style={{textAlign:'center'}}>{body}</Muted>{a.themeMode===value?<Ionicons name="checkmark-circle" size={20} color={palette.success}/>:null}</Pressable>)}</View>
    <Card><Text style={[st.groupTitle,{color:palette.text}]}>Accent Color</Text><Muted>Choose the primary colour used across CDA Connect.</Muted><View style={st.accents}>{accents.map(color=><Pressable accessibilityLabel={`Use accent colour ${color}`} key={color} onPress={()=>a.update({accentColor:color})} style={[st.accent,{backgroundColor:color},a.accentColor===color&&{borderColor:palette.text,borderWidth:3}]}>{a.accentColor===color?<Ionicons name="checkmark" size={20} color="#fff"/>:null}</Pressable>)}</View></Card>
    <Card><Text style={[st.groupTitle,{color:palette.text}]}>Font Size</Text><Muted>Adjust text size for better readability.</Muted><View style={st.scaleGrid}>{scales.map(([value,letter,label])=><Pressable key={value} onPress={()=>a.update({textScale:value})} style={[st.scaleOption,{borderColor:a.textScale===value?palette.success:palette.border,backgroundColor:a.textScale===value?palette.successSoft:palette.surface}]}><Text style={{fontSize:value==='normal'?16:value==='large'?21:26,color:palette.text,fontWeight:'800'}}>{letter}</Text><Muted>{label}</Muted></Pressable>)}</View></Card>
    <Card style={st.options}><Text style={[st.groupTitle,{color:palette.text}]}>Display Options</Text><Toggle icon="reorder-three-outline" title="Compact Mode" body="Show more content in less space" value={a.compactMode} onChange={v=>a.update({compactMode:v})}/><Toggle icon="eye-off-outline" title="Reduce Motion" body="Minimize animations throughout the app" value={a.reducedMotion} onChange={v=>a.update({reducedMotion:v})}/><Toggle icon="contrast-outline" title="High Contrast" body="Increase contrast for better visibility" value={a.highContrast} onChange={v=>a.update({highContrast:v})}/><Toggle icon="scan-outline" title="Round Corners" body="Use rounded corners on cards and buttons" value={a.roundCorners} onChange={v=>a.update({roundCorners:v})}/><Toggle icon="image-outline" title="Show Community Covers" body="Display cover photos in community cards" value={a.showCommunityCovers} onChange={v=>a.update({showCommunityCovers:v})}/><Toggle icon="color-palette-outline" title="Color Blind Friendly" body="Use stronger contrast and clearer status colours" value={a.colorBlindFriendly} onChange={v=>a.update({colorBlindFriendly:v})}/></Card>
    {!desktop?<Preview/>:null}<Card style={[st.saved,{backgroundColor:palette.successSoft}]}><Ionicons name="shield-checkmark-outline" size={23} color={palette.success}/><View style={{flex:1}}><Text style={{fontWeight:'900',color:palette.success}}>Changes are saved automatically</Text><Muted>Your preferences are applied on this device.</Muted></View></Card>
    <Button title="Reset Appearance" variant="secondary" onPress={()=>a.reset()}/>
   </View>
   {desktop?<View style={st.previewColumn}><Preview/><Card><Text style={[st.groupTitle,{color:palette.text}]}>More Options</Text><More icon="apps-outline" title="App Icon" body="Uses the CDA Connect app icon"/><More icon="phone-portrait-outline" title="Background" body="Follows your selected theme"/><Toggle icon="color-filter-outline" title="Color Blind Friendly" body="Improve accessibility" value={a.colorBlindFriendly} onChange={v=>a.update({colorBlindFriendly:v})}/><Button title="View Help Center" variant="secondary" onPress={()=>router.push('/help')}/></Card></View>:null}
  </View>
 </Screen>
}

function Toggle({icon,title,body,value,onChange}:{icon:keyof typeof Ionicons.glyphMap;title:string;body:string;value:boolean;onChange:(v:boolean)=>void}){const{palette}=useAppTheme();return <View style={[st.toggle,{borderBottomColor:palette.border}]}><View style={[st.rowIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={20} color={palette.success}/></View><View style={{flex:1}}><Text style={[st.rowTitle,{color:palette.text}]}>{title}</Text><Muted>{body}</Muted></View><Switch value={value} onValueChange={onChange} trackColor={{false:palette.border,true:palette.success}}/></View>}
function Preview(){const{palette,prefs}=useAppTheme();return <Card><Text style={[st.groupTitle,{color:palette.text}]}>Preview</Text><View style={st.previewHead}><View style={[st.previewAvatar,{backgroundColor:palette.success}]}><Text style={{color:'#fff',fontWeight:'900'}}>YC</Text></View><View style={{flex:1}}><Text style={[st.rowTitle,{color:palette.text}]}>Your community</Text><Muted>Recent update</Muted></View><Ionicons name="ellipsis-horizontal" size={20} color={palette.muted}/></View><Text style={[st.previewText,{color:palette.text}]}>Community announcements and updates will use your selected appearance settings.</Text>{prefs.showCommunityCovers?<View style={[st.cover,{backgroundColor:palette.successSoft}]}><Ionicons name="people" size={42} color={palette.success}/><Text style={{color:palette.success,fontWeight:'900'}}>Community update</Text></View>:null}<View style={st.reactions}><Ionicons name="heart-outline" size={20} color={palette.danger}/><Text style={{color:palette.muted}}>0</Text><Ionicons name="chatbubble-outline" size={19} color={palette.navy}/><Text style={{color:palette.muted}}>0</Text></View></Card>}
function More({icon,title,body}:{icon:keyof typeof Ionicons.glyphMap;title:string;body:string}){const{palette}=useAppTheme();return <View style={[st.toggle,{borderBottomColor:palette.border}]}><View style={[st.rowIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={20} color={palette.success}/></View><View style={{flex:1}}><Text style={[st.rowTitle,{color:palette.text}]}>{title}</Text><Muted>{body}</Muted></View></View>}

const st=StyleSheet.create({page:{width:'100%',maxWidth:1380,alignSelf:'center'},heading:{marginBottom:22},title:{fontSize:29,fontWeight:'900',marginBottom:5},layout:{flexDirection:'row',alignItems:'flex-start',gap:16},stack:{flexDirection:'column'},menu:{width:245,padding:12},menuTitle:{fontWeight:'900',margin:8},menuRow:{minHeight:48,borderRadius:10,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:11},main:{flex:1,width:'100%',minWidth:0},previewColumn:{width:280},groupTitle:{fontSize:18,fontWeight:'900',marginBottom:7},themeGrid:{flexDirection:'row',gap:10,marginBottom:12},theme:{flex:1,minHeight:150,borderWidth:1.5,borderRadius:14,alignItems:'center',justifyContent:'center',gap:7,padding:10},optionTitle:{fontWeight:'900'},accents:{flexDirection:'row',flexWrap:'wrap',gap:14,marginTop:18},accent:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center'},scaleGrid:{flexDirection:'row',gap:10,marginTop:16},scaleOption:{flex:1,minHeight:100,borderWidth:1.5,borderRadius:12,alignItems:'center',justifyContent:'center',gap:6},options:{paddingBottom:4},toggle:{minHeight:68,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,paddingVertical:8},rowIcon:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'},rowTitle:{fontWeight:'900',marginBottom:2},saved:{flexDirection:'row',alignItems:'center',gap:12},previewHead:{flexDirection:'row',alignItems:'center',gap:10},previewAvatar:{width:46,height:46,borderRadius:11,alignItems:'center',justifyContent:'center'},previewText:{lineHeight:21,marginVertical:14},cover:{height:150,borderRadius:13,alignItems:'center',justifyContent:'center',gap:10},reactions:{flexDirection:'row',alignItems:'center',gap:8,marginTop:13}});
