import {useState} from 'react';
import {Alert,Platform,Pressable,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {useAuth} from '@/store/auth';
import {Avatar,Button,Card,Muted,Screen,useAppTheme} from '@/components/UI';

const menu=[['person-outline','Account Settings','/account-settings'],['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;

export default function AccountSettings(){
 const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;const{user,logout}=useAuth();const[deleting,setDeleting]=useState(false);
 const name=`${user?.FirstName||''} ${user?.LastName||''}`.trim()||'Community Member';const location=[(user as any)?.City,(user as any)?.State,(user as any)?.Country].filter(Boolean).join(', ')||'Not added';
 const open=(path:string)=>router.push(path as any);const back=()=>router.canGoBack()?router.back():router.replace('/(tabs)/settings' as any);
 const requestDeletion=()=>Alert.alert('Delete account?','This submits an account deletion request and signs you out. Administrative and legal retention requirements may apply.',[{text:'Cancel',style:'cancel'},{text:'Request deletion',style:'destructive',onPress:async()=>{try{setDeleting(true);await api.post('/me/delete-account-request');await logout();Alert.alert('Request submitted','Your account deletion request has been recorded.');router.replace('/(auth)/welcome')}catch(e:any){Alert.alert('Unable to submit request',e.response?.data?.error||e.message)}finally{setDeleting(false)}}}]);
 const rows=[['Full Name',name],['Username',(user as any)?.Username||String(user?.Email||'').split('@')[0]||'Not added'],['Email',user?.Email||'Not added'],['Phone Number',user?.Phone||'Not added'],['Location',location],['Occupation',(user as any)?.Occupation||'Not added'],['Bio',(user as any)?.Bio||'Tell your community about yourself']] as const;
 return <Screen scroll contentStyle={s.page}>
  <View style={s.top}><Pressable accessibilityLabel="Back to settings" onPress={back} style={s.back}><Ionicons name="chevron-back" size={27} color={palette.text}/></Pressable><View><Text style={[s.title,{color:palette.text}]}>{desktop?'Settings':'Account Settings'}</Text>{desktop?<Muted>Manage your account, preferences and community experience.</Muted>:null}</View></View>
  <View style={[s.layout,!desktop&&s.stack]}>
   {desktop?<Card style={s.menu}><Text style={[s.menuTitle,{color:palette.text}]}>Settings Menu</Text>{menu.map(([icon,label,path],i)=><Pressable key={label} onPress={()=>open(path)} style={[s.menuRow,i===0&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={20} color={i===0?palette.success:palette.navy}/><Text style={{color:i===0?palette.success:palette.text,fontWeight:'800'}}>{label}</Text></Pressable>)}</Card>:null}
   <View style={s.main}>
    <Card style={s.account}>
     <View style={s.accountHead}><View><Text style={[s.sectionTitle,{color:palette.text}]}>Account Settings</Text><Muted>Manage your personal information and account preferences.</Muted></View>{desktop?<Button title="Edit Profile" icon="create-outline" variant="secondary" onPress={()=>open('/profile-edit')}/>:null}</View>
     <View style={[s.identity,!desktop&&s.identityMobile]}><Avatar name={name} size={desktop?80:70}/><View style={s.grow}><Text style={[s.name,{color:palette.text}]}>{name} <Ionicons name="checkmark-circle" size={17} color={palette.success}/></Text><Muted>{user?.Email}</Muted><Muted>{user?.Phone||'Phone number not added'}</Muted></View>{!desktop?<Button title="Edit Profile" variant="secondary" onPress={()=>open('/profile-edit')}/>:null}</View>
     <Text style={[s.subheading,{color:palette.text}]}>Profile Information</Text>
     {rows.map(([label,value],i)=><Pressable accessibilityLabel={`Edit ${label}`} key={label} onPress={()=>open('/profile-edit')} style={[s.row,{borderTopColor:palette.border}]}>{i===0&&!desktop?<Ionicons name="person-circle-outline" size={25} color={palette.success}/>:null}<Text style={[s.label,{color:palette.text}]}>{label}</Text><Muted style={s.value} numberOfLines={label==='Bio'?3:1}>{value}</Muted><Ionicons name="chevron-forward" size={18} color={palette.muted}/></Pressable>)}
    </Card>
    <Card><Text style={[s.sectionTitle,{color:palette.text}]}>Quick Actions</Text><Action icon="key-outline" tone="#7C3AED" label="Change Password" help="Update your password" onPress={()=>open('/security')}/><Action icon="shield-checkmark-outline" tone={palette.success} label="Two-Factor Authentication" help="Add extra security to your account" onPress={()=>open('/security')}/><Action icon="desktop-outline" tone={palette.warning} label="Active Sessions" help="Manage your active sessions and trusted devices" onPress={()=>open('/security')}/></Card>
    <Pressable accessibilityRole="button" accessibilityLabel="Delete account" disabled={deleting} onPress={requestDeletion} style={[s.delete,{backgroundColor:palette.danger}]}><Ionicons name="trash-outline" size={20} color="#FFF"/><Text style={s.deleteText}>{deleting?'Submitting request…':'Delete Account'}</Text></Pressable>
   </View>
  </View>
 </Screen>
}

function Action({icon,tone,label,help,onPress}:{icon:keyof typeof Ionicons.glyphMap;tone:string;label:string;help:string;onPress:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={onPress} style={[s.action,{borderTopColor:palette.border}]}><View style={[s.actionIcon,{backgroundColor:`${tone}18`}]}><Ionicons name={icon} size={22} color={tone}/></View><View style={s.grow}><Text style={[s.actionLabel,{color:palette.text}]}>{label}</Text><Muted>{help}</Muted></View><Ionicons name="chevron-forward" size={19} color={palette.muted}/></Pressable>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1240,alignSelf:'center'},top:{minHeight:75,flexDirection:'row',alignItems:'center',gap:10,marginBottom:15},back:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontSize:28,fontWeight:'900'},layout:{flexDirection:'row',gap:18,alignItems:'flex-start'},stack:{flexDirection:'column'},menu:{width:270,padding:13},menuTitle:{fontWeight:'900',margin:9},menuRow:{minHeight:50,borderRadius:11,flexDirection:'row',alignItems:'center',gap:11,paddingHorizontal:12},main:{flex:1,width:'100%',gap:15},account:{padding:22},accountHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,marginBottom:18},sectionTitle:{fontSize:20,fontWeight:'900',marginBottom:5},identity:{flexDirection:'row',alignItems:'center',gap:16,marginBottom:18},identityMobile:{flexWrap:'wrap'},grow:{flex:1,minWidth:150},name:{fontSize:19,fontWeight:'900',marginBottom:4},subheading:{fontSize:15,fontWeight:'900',marginTop:6,marginBottom:4},row:{minHeight:61,borderTopWidth:1,flexDirection:'row',alignItems:'center',gap:12},label:{fontWeight:'800',width:125},value:{flex:1,textAlign:'right'},action:{minHeight:72,borderTopWidth:1,flexDirection:'row',alignItems:'center',gap:12},actionIcon:{width:42,height:42,borderRadius:12,alignItems:'center',justifyContent:'center'},actionLabel:{fontWeight:'900',marginBottom:2},delete:{minHeight:55,borderRadius:12,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},deleteText:{color:'#FFF',fontWeight:'900'}});
