import {PolicyPage,PolicySection} from '@/components/PolicyPage';
const sections:PolicySection[]=[
 {heading:'Who the Platform Serves',paragraphs:['CDA Connect supports residents, community associations, leaders, administrators, moderators, local organisations and businesses.','Each user receives features according to membership, role and community configuration. A platform role does not itself create a government office or regulated professional status.']},
 {heading:'Community Workspaces',paragraphs:['Workspaces may include feeds, chat, members, executives, events, meetings, attendance, documents, polls, governance, local services, marketplaces and financial records.','Communities decide how to use enabled tools and remain responsible for lawful rules, authorisations, records and decisions.']},
 {heading:'Administrator Responsibilities',paragraphs:['Owners and administrators must protect access, appoint suitable role holders, maintain accurate information and use member data only for authorised purposes.','Where a community determines why and how personal data is used, it may have independent controller obligations under the Nigeria Data Protection Act 2023 and GAID 2025.','Administrative powers must not be used for retaliation, unlawful discrimination, fraud, surveillance or personal enrichment.']},
 {heading:'Finance and Payments',paragraphs:['Community levies and records must accurately identify purpose, amount, beneficiary and status. CDA Connect is not a bank or licensed payment institution unless expressly stated.','Actual payment processing should be handled by appropriate providers operating within the Central Bank of Nigeria’s regulatory framework. Communities and providers remain responsible for their respective legal duties.']},
 {heading:'Marketplace and Services',paragraphs:['Community businesses and service providers must describe offerings accurately and comply with licensing, safety, tax, advertising and consumer rules applicable to them.','CDA Connect provides discovery and communication tools but does not guarantee a provider’s identity, qualification, quality or fitness. Mandatory FCCPA rights remain unaffected.']},
 {heading:'Governance and Elections',paragraphs:['Voting, proposals and decision records are support tools. Communities must follow their constitutions, association rules and applicable Nigerian law.','Authorised officials should publish clear eligibility, quorum, voting, conflict and result procedures and maintain an appropriate audit trail.']},
 {heading:'Privacy, Records and Retention',paragraphs:['Member information, attendance, documents and financial records should be limited to legitimate purposes and accessible only to appropriate roles.','Communities should establish retention and deletion practices that reflect legal duties, disputes, accounting needs and data-subject rights.']},
 {heading:'Moderation and Safety',paragraphs:['Communities should publish local rules, train moderators, handle reports fairly and escalate immediate danger to competent authorities.','Local rules may be stricter than platform minimums where lawful but cannot authorise conduct prohibited by the Terms or Community Guidelines.']},
 {heading:'Legal Boundaries',paragraphs:['CDA Connect does not provide legal, financial, medical or emergency advice through ordinary platform features. Users should consult qualified professionals or public authorities for regulated decisions.','The Terms of Service, Privacy Policy and Community Guidelines contain the binding platform rules and should be read with this explanatory page.']},
];
export default function BuiltForCommunities(){return <PolicyPage intro="CDA Connect combines practical community tools with clear responsibilities for members, administrators and third-party providers." sections={sections}/>}
