import {useMemo,useState} from 'react';
import {Alert,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Button,Card,Muted,Screen,useAppTheme} from '@/components/UI';
import {api} from '@/lib/api';
import {useAuth} from '@/store/auth';

export default function ChangePassword(){const{palette}=useAppTheme();const refreshToken=useAuth(x=>x.refreshToken);const[current,setCurrent]=useState('');const[next,setNext]=useState('');const[confirm,setConfirm]=useState('');const[show,setShow]=useState({current:false,next:false,confirm:false});const[saving,setSaving]=useState(false);
 const rules=useMemo(()=>[{label:'At least 8 characters long',ok:next.length>=8},{label:'At least one uppercase letter (A–Z)',ok:/[A-Z]/.test(next)},{label:'At least one lowercase letter (a–z)',ok:/[a-z]/.test(next)},{label:'At least one number (0–9)',ok:/\d/.test(next)},{label:'At least one special character',ok:/[^A-Za-z0-9]/.test(next)}],[next]);
 const passed=rules.filter(x=>x.ok).length;const strength=passed<=1?'Weak':passed<=3?'Fair':passed===4?'Strong':'Very strong';const valid=Boolean(current)&&passed===rules.length&&next===confirm&&next!==current;
 const submit=async()=>{if(next!==confirm)return Alert.alert('Passwords do not match','Enter the same new password in both fields.');if(next===current)return Alert.alert('Choose a different password','Your new password must be different from your current password.');if(passed!==rules.length)return Alert.alert('Password requirements','Complete every password requirement before continuing.');try{setSaving(true);await api.put('/auth/password',{currentPassword:current,newPassword:next,refreshToken});setCurrent('');setNext('');setConfirm('');Alert.alert('Password updated','Your password was changed and all other sessions were signed out.',[{text:'Done',onPress:()=>router.replace('/security')}])}catch(e:any){Alert.alert('Unable to change password',e.response?.data?.error||e.message)}finally{setSaving(false)}};
 return <Screen scroll contentStyle={s.page}><Pressable accessibilityRole="button" accessibilityLabel="Back to security" onPress={()=>router.canGoBack()?router.back():router.replace('/security')} style={s.back}><Ionicons name="chevron-back" size={27} color={palette.text}/><Text style={[s.backText,{color:palette.text}]}>Security</Text></Pressable><Text style={[s.title,{color:palette.text}]}>Change Password</Text><Muted style={s.subtitle}>Create a new password to keep your account secure.</Muted>
  <Card style={[s.hero,{backgroundColor:palette.successSoft}]}><View style={[s.heroIcon,{backgroundColor:palette.success}]}><Ionicons name="lock-closed" size={38} color="#fff"/></View><View style={s.grow}><Text style={[s.heroTitle,{color:palette.success}]}>Keep your account secure</Text><Muted>Use a strong, unique password that you do not use on other websites or apps.</Muted></View></Card>
  <PasswordField label="Current Password" placeholder="Enter your current password" value={current} change={setCurrent} visible={show.current} toggle={()=>setShow(x=>({...x,current:!x.current}))}/><PasswordField label="New Password" placeholder="Enter your new password" value={next} change={setNext} visible={show.next} toggle={()=>setShow(x=>({...x,next:!x.next}))}/>
  <View style={s.strengthHead}><Text style={[s.strengthLabel,{color:palette.text}]}>Password strength</Text><Text style={{fontWeight:'900',color:passed>=4?palette.success:passed>=2?palette.accent:palette.danger}}>{strength}</Text></View><View style={s.strengthBar}>{[0,1,2,3,4].map(i=><View key={i} style={[s.segment,{backgroundColor:i<passed?(passed>=4?palette.success:passed>=2?palette.accent:palette.danger):palette.border}]}/>)}</View>
  <PasswordField label="Confirm New Password" placeholder="Confirm your new password" value={confirm} change={setConfirm} visible={show.confirm} toggle={()=>setShow(x=>({...x,confirm:!x.confirm}))}/>{confirm&&next!==confirm?<Text accessibilityRole="alert" style={{color:palette.danger,fontWeight:'800'}}>Passwords do not match.</Text>:null}
  <Card><View style={s.ruleHead}><Ionicons name="shield-checkmark-outline" size={26} color={palette.success}/><Text style={[s.ruleTitle,{color:palette.success}]}>Password must contain</Text></View>{rules.map(rule=><View key={rule.label} style={s.rule}><Ionicons name={rule.ok?'checkmark-circle':'ellipse-outline'} size={22} color={rule.ok?palette.success:palette.muted}/><Text style={{color:palette.text,fontWeight:rule.ok?'800':'600',flex:1}}>{rule.label}</Text></View>)}</Card>
  <Card style={[s.tip,{backgroundColor:palette.infoLight}]}><Ionicons name="information-circle-outline" size={30} color={palette.info}/><View style={s.grow}><Text style={[s.ruleTitle,{color:palette.infoText}]}>Password tip</Text><Muted>Avoid names, dates, common words and repeated characters. A password manager can create and store a unique password.</Muted></View></Card>
  <Button title="Update Password" variant="success" loading={saving} disabled={!valid||saving} onPress={submit}/>
 </Screen>}

function PasswordField({label,placeholder,value,change,visible,toggle}:{label:string;placeholder:string;value:string;change:(v:string)=>void;visible:boolean;toggle:()=>void}){const{palette}=useAppTheme();return <View style={s.fieldGroup}><Text style={[s.label,{color:palette.text}]}>{label}</Text><View style={[s.field,{borderColor:palette.border,backgroundColor:palette.surface}]}><Ionicons name="lock-closed-outline" size={21} color={palette.muted}/><TextInput accessibilityLabel={label} value={value} onChangeText={change} placeholder={placeholder} placeholderTextColor={palette.muted} secureTextEntry={!visible} autoCapitalize="none" autoCorrect={false} style={[s.input,{color:palette.text}]}/><Pressable accessibilityRole="button" accessibilityLabel={visible?'Hide password':'Show password'} onPress={toggle} style={s.eye}><Ionicons name={visible?'eye-off-outline':'eye-outline'} size={23} color={palette.muted}/></Pressable></View></View>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:780,alignSelf:'center',paddingBottom:115},back:{minHeight:52,alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:5},backText:{fontWeight:'800'},title:{fontSize:32,fontWeight:'900',marginTop:10},subtitle:{fontSize:16,marginTop:7,marginBottom:22},hero:{flexDirection:'row',alignItems:'center',gap:18,paddingVertical:25},heroIcon:{width:76,height:86,borderRadius:25,alignItems:'center',justifyContent:'center'},grow:{flex:1,minWidth:0},heroTitle:{fontSize:19,fontWeight:'900',marginBottom:7},fieldGroup:{marginTop:15,marginBottom:8},label:{fontSize:16,fontWeight:'900',marginBottom:9},field:{minHeight:62,borderWidth:1.5,borderRadius:14,flexDirection:'row',alignItems:'center',paddingLeft:17},input:{flex:1,fontSize:16,paddingHorizontal:13,paddingVertical:15},eye:{width:54,height:54,alignItems:'center',justifyContent:'center'},strengthHead:{flexDirection:'row',gap:8,alignItems:'center',marginTop:7},strengthLabel:{fontWeight:'800'},strengthBar:{flexDirection:'row',gap:6,marginTop:10,marginBottom:14},segment:{height:6,flex:1,borderRadius:3},ruleHead:{flexDirection:'row',alignItems:'center',gap:9,marginBottom:12},ruleTitle:{fontSize:16,fontWeight:'900'},rule:{minHeight:37,flexDirection:'row',alignItems:'center',gap:10},tip:{flexDirection:'row',alignItems:'flex-start',gap:13}});
