import {useMemo,useState} from 'react';
import {Alert,Pressable,StyleSheet,Text,TextInput,View} from '@/platform/react-native';
import {router} from '@/router';
import {Ionicons} from '@/platform/icons';
import {Button,Card,Muted,Screen,useAppTheme} from '@/components/UI';
import {api} from '@/lib/api';
import {useAuth} from '@/store/auth';

export default function ChangePassword(){const{palette}=useAppTheme();const refreshToken=useAuth(x=>x.refreshToken);const[current,setCurrent]=useState('');const[next,setNext]=useState('');const[confirm,setConfirm]=useState('');const[show,setShow]=useState({current:false,next:false,confirm:false});const[saving,setSaving]=useState(false);
 const rules=useMemo(()=>[{label:'At least 8 characters long',ok:next.length>=8},{label:'At least one uppercase letter (A–Z)',ok:/[A-Z]/.test(next)},{label:'At least one lowercase letter (a–z)',ok:/[a-z]/.test(next)},{label:'At least one number (0–9)',ok:/\d/.test(next)},{label:'At least one special character',ok:/[^A-Za-z0-9]/.test(next)}],[next]);
 const passed=rules.filter(x=>x.ok).length;const strength=passed<=1?'Weak':passed<=3?'Fair':passed===4?'Strong':'Very strong';const valid=Boolean(current)&&passed===rules.length&&next===confirm&&next!==current;
 const submit=async()=>{if(next!==confirm)return Alert.alert('Passwords do not match','Enter the same new password in both fields.');if(next===current)return Alert.alert('Choose a different password','Your new password must be different from your current password.');if(passed!==rules.length)return Alert.alert('Password requirements','Complete every password requirement before continuing.');try{setSaving(true);await api.put('/auth/password',{currentPassword:current,newPassword:next,refreshToken});setCurrent('');setNext('');setConfirm('');Alert.alert('Password updated','Your password was changed and all other sessions were signed out.',[{text:'Done',onPress:()=>router.replace('/security')}])}catch(e:any){Alert.alert('Unable to change password',e.response?.data?.error||e.message)}finally{setSaving(false)}};
 return <Screen scroll contentStyle={s.page}><Muted style={s.subtitle}>Create a new password to keep your account secure.</Muted>
  <PasswordField label="Current Password" placeholder="Enter your current password" value={current} change={setCurrent} visible={show.current} toggle={()=>setShow(x=>({...x,current:!x.current}))}/><PasswordField label="New Password" placeholder="Enter your new password" value={next} change={setNext} visible={show.next} toggle={()=>setShow(x=>({...x,next:!x.next}))}/>
  <View style={s.strengthHead}><Text style={[s.strengthLabel,{color:palette.text}]}>Password strength</Text><Text style={{fontWeight:'900',color:passed>=4?palette.success:passed>=2?palette.accent:palette.danger}}>{strength}</Text></View><View style={s.strengthBar}>{[0,1,2,3,4].map(i=><View key={i} style={[s.segment,{backgroundColor:i<passed?(passed>=4?palette.success:passed>=2?palette.accent:palette.danger):palette.border}]}/>)}</View>
  <PasswordField label="Confirm New Password" placeholder="Confirm your new password" value={confirm} change={setConfirm} visible={show.confirm} toggle={()=>setShow(x=>({...x,confirm:!x.confirm}))}/>{confirm&&next!==confirm?<Text accessibilityRole="alert" style={{color:palette.danger,fontWeight:'800'}}>Passwords do not match.</Text>:null}
  <Card><View style={s.ruleHead}><Ionicons name="shield-checkmark-outline" size={26} color={palette.success}/><Text style={[s.ruleTitle,{color:palette.success}]}>Password must contain</Text></View>{rules.map(rule=><View key={rule.label} style={s.rule}><Ionicons name={rule.ok?'checkmark-circle':'ellipse-outline'} size={22} color={rule.ok?palette.success:palette.muted}/><Text style={{color:palette.text,fontWeight:rule.ok?'800':'600',flex:1}}>{rule.label}</Text></View>)}</Card>
  <Card style={[s.tip,{backgroundColor:palette.infoLight}]}><Ionicons name="information-circle-outline" size={30} color={palette.info}/><View style={s.grow}><Text style={[s.ruleTitle,{color:palette.infoText}]}>Password tip</Text><Muted>Avoid names, dates, common words and repeated characters. A password manager can create and store a unique password.</Muted></View></Card>
  <Button title="Update Password" variant="success" loading={saving} disabled={!valid||saving} onPress={submit}/>
 </Screen>}

function PasswordField({label,placeholder,value,change,visible,toggle}:{label:string;placeholder:string;value:string;change:(v:string)=>void;visible:boolean;toggle:()=>void}){const{palette}=useAppTheme();return <View style={s.fieldGroup}><Text style={[s.label,{color:palette.text}]}>{label}</Text><View style={[s.field,{borderColor:palette.border,backgroundColor:palette.surface}]}><Ionicons name="lock-closed-outline" size={21} color={palette.muted}/><TextInput accessibilityLabel={label} value={value} onChangeText={change} placeholder={placeholder} placeholderTextColor={palette.muted} secureTextEntry={!visible} autoCapitalize="none" autoCorrect={false} style={[s.input,{color:palette.text}]}/><Pressable accessibilityRole="button" accessibilityLabel={visible?'Hide password':'Show password'} onPress={toggle} style={s.eye}><Ionicons name={visible?'eye-off-outline':'eye-outline'} size={23} color={palette.muted}/></Pressable></View></View>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:780,alignSelf:'center',paddingBottom:120},subtitle:{fontSize:16,marginBottom:14},grow:{flex:1,minWidth:0},fieldGroup:{marginTop:14,marginBottom:8},label:{fontSize:16,fontWeight:'900',marginBottom:9},field:{width:'100%',minHeight:60,borderWidth:1.5,borderRadius:14,flexDirection:'row',alignItems:'center',paddingLeft:14},input:{flex:1,minWidth:0,fontSize:16,paddingHorizontal:11,paddingVertical:14},eye:{width:50,height:54,alignItems:'center',justifyContent:'center',flexShrink:0},strengthHead:{flexDirection:'row',justifyContent:'space-between',gap:8,alignItems:'center',marginTop:7},strengthLabel:{fontWeight:'800'},strengthBar:{flexDirection:'row',gap:5,marginTop:10,marginBottom:14},segment:{height:6,flex:1,borderRadius:3},ruleHead:{flexDirection:'row',alignItems:'center',gap:9,marginBottom:12},ruleTitle:{fontSize:16,fontWeight:'900'},rule:{minHeight:37,flexDirection:'row',alignItems:'center',gap:10},tip:{flexDirection:'row',alignItems:'flex-start',gap:11}});
