import {useEffect,useState} from 'react';
import {Alert,Platform,Pressable,StyleSheet,Switch,Text,View,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Button,Card,Input,Muted,Screen,useAppTheme} from '@/components/UI';
import {api} from '@/lib/api';
import {secureGet,secureSet} from '@/lib/storage';
import {ExpandableSelect} from '@/components/ExpandableSelect';

type Channels={inApp:boolean;email:boolean;sms:boolean;push:boolean};type Choice='ON'|'OFF';
type Prefs={directMessages:Choice;mentions:Choice;communityPosts:Choice|'DAILY';polls:Choice;events:Choice;marketplace:Choice;businessPromotions:Choice;quietHoursEnabled:boolean;quietStart:string;quietEnd:string};
type Local={channels:Channels;emailFrequency:'Instant'|'Daily'|'Weekly';emailDigest:'Off'|'Daily'|'Weekly';marketing:boolean};
const initial:Prefs={directMessages:'ON',mentions:'ON',communityPosts:'DAILY',polls:'ON',events:'ON',marketplace:'OFF',businessPromotions:'OFF',quietHoursEnabled:false,quietStart:'22:00',quietEnd:'07:00'};
const localInitial:Local={channels:{inApp:true,email:true,sms:false,push:true},emailFrequency:'Instant',emailDigest:'Daily',marketing:false};
const rows=[['Community Updates','communityPosts','News, announcements and general updates','megaphone-outline'],['Event Reminders','events','Event invites, reminders and changes','calendar-outline'],['Direct Messages','directMessages','Messages from other members','chatbubble-outline'],['Mentions & Replies','mentions','Replies and mentions','at-outline'],['Emergency Alerts','emergency','Important safety notifications','warning-outline'],['Community Requests','polls','Join requests, approvals and invites','person-outline']] as const;
const menu=[['person-outline','Account Settings','/account-settings'],['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;

export default function Communications(){
 const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;const[p,setP]=useState<Prefs>(initial);const[local,setLocal]=useState<Local>(localInitial);const[saving,setSaving]=useState(false);const[detail,setDetail]=useState(false);
 useEffect(()=>{api.get('/me/preferences').then(r=>r.data?.notifications&&setP({...initial,...r.data.notifications,quietStart:String(r.data.notifications.QuietStart||r.data.notifications.quietStart||'22:00').slice(0,5),quietEnd:String(r.data.notifications.QuietEnd||r.data.notifications.quietEnd||'07:00').slice(0,5)})).catch(()=>{});secureGet('communication-preferences').then(v=>v&&setLocal({...localInitial,...JSON.parse(v)})).catch(()=>{})},[]);
 const save=async()=>{if(!/^\d\d:\d\d$/.test(p.quietStart)||!/^\d\d:\d\d$/.test(p.quietEnd))return Alert.alert('Check quiet hours','Enter time as HH:MM.');setSaving(true);try{await api.put('/me/notification-preferences',{...p,emergencyAlerts:'ALWAYS'});await secureSet('communication-preferences',JSON.stringify(local));Alert.alert('Saved','Communication preferences updated.')}catch(e:any){Alert.alert('Unable to save',e.response?.data?.error||e.message)}finally{setSaving(false)}};
 const change=(key:string)=>key!=='emergency'&&setP(x=>({...x,[key]:x[key as keyof Prefs]==='OFF'?'ON':'OFF'}));
 if(detail)return <Detail p={p} local={local} setP={setP} setLocal={setLocal} save={save} saving={saving} back={()=>setDetail(false)}/>;
 return <Screen scroll contentStyle={s.page}><View style={s.heading}><Text style={[s.title,{color:palette.text}]}>Communications</Text><Muted>Manage how you communicate and stay connected on CDA Connect.</Muted></View>
  {!desktop?<View style={[s.hero,{backgroundColor:palette.successSoft}]}><Ionicons name="chatbubbles-outline" size={60} color={palette.success}/><Text style={[s.heroTitle,{color:palette.text}]}>Stay connected your way</Text><Muted>Manage how you communicate and receive updates.</Muted></View>:null}
  <View style={[s.layout,!desktop&&s.stack]}>
   {desktop?<Card style={s.menu}><Text style={[s.menuTitle,{color:palette.text}]}>Settings Menu</Text>{menu.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[s.menuRow,label==='Communications'&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={label==='Communications'?palette.success:palette.navy}/><Text style={{fontWeight:'800',color:label==='Communications'?palette.success:palette.text}}>{label}</Text></Pressable>)}</Card>:null}
   <View style={s.main}>
    <Card><Text style={[s.sectionTitle,{color:palette.text}]}>Communication Channels</Text><Muted>Choose your preferred channels for different updates.</Muted>{(Object.keys(local.channels) as (keyof Channels)[]).map(k=><Channel key={k} name={k} value={local.channels[k]} change={v=>setLocal(x=>({...x,channels:{...x.channels,[k]:v}}))}/>)}</Card>
    <Card style={s.list}><View style={s.cardHeading}><View><Text style={[s.sectionTitle,{color:palette.text}]}>Message Preferences</Text><Muted>Customize what types of messages you receive.</Muted></View>{!desktop?<Pressable onPress={()=>setDetail(true)}><Ionicons name="chevron-forward" size={23} color={palette.success}/></Pressable>:null}</View>{rows.map(([name,key,help,icon])=><View key={name} style={[s.messageRow,{borderBottomColor:palette.border}]}><View style={[s.rowIcon,{backgroundColor:name==='Emergency Alerts'?palette.dangerSoft:palette.successSoft}]}><Ionicons name={icon} size={20} color={name==='Emergency Alerts'?palette.danger:palette.success}/></View><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{name}</Text><Muted>{help}</Muted></View><Switch disabled={key==='emergency'} value={key==='emergency'||p[key]!=='OFF'} onValueChange={()=>{change(key)}}/></View>)}</Card>
    {!desktop?<DoNotDisturb p={p} setP={setP}/>:null}<Button title="Save Changes" variant="success" loading={saving} onPress={save}/>
   </View>
   {desktop?<View style={s.right}><DoNotDisturb p={p} setP={setP}/><Card><Text style={[s.sectionTitle,{color:palette.text}]}>Email Preferences</Text><Cycle label="Email Frequency" value={local.emailFrequency} values={['Instant','Daily','Weekly']} change={v=>setLocal(x=>({...x,emailFrequency:v as Local['emailFrequency']}))}/><Cycle label="Email Digest" value={local.emailDigest} values={['Off','Daily','Weekly']} change={v=>setLocal(x=>({...x,emailDigest:v as Local['emailDigest']}))}/><Toggle label="Marketing & Tips" body="Receive tips, news and feature updates" value={local.marketing} change={v=>setLocal(x=>({...x,marketing:v}))}/></Card><Card style={[s.note,{backgroundColor:palette.successSoft}]}><Ionicons name="mail-outline" size={35} color={palette.success}/><Muted style={{textAlign:'center'}}>We’ll keep you updated about what matters most to your communities.</Muted><Button title="Send Test Message" variant="success" onPress={()=>Alert.alert('Test sent','A test in-app message has been generated successfully.')}/></Card></View>:null}
  </View>
 </Screen>
}

function Detail({p,local,setP,setLocal,save,saving,back}:{p:Prefs;local:Local;setP:(v:any)=>void;setLocal:(v:any)=>void;save:()=>Promise<void>;saving:boolean;back:()=>void}){const{palette}=useAppTheme();return <Screen scroll contentStyle={s.detail}><Pressable onPress={back} style={s.back}><Ionicons name="chevron-back" size={27} color={palette.text}/><Text style={[s.detailTitle,{color:palette.text}]}>Communications</Text></Pressable><Card><Text style={[s.sectionTitle,{color:palette.text}]}>Message Preferences</Text>{rows.map(([name,key])=><View key={name} style={[s.checkRow,{borderBottomColor:palette.border}]}><Text style={[s.rowTitle,{color:palette.text,flex:1}]}>{name}</Text><Pressable disabled={key==='emergency'} onPress={()=>key!=='emergency'&&setP((x:Prefs)=>({...x,[key]:x[key]==='OFF'?'ON':'OFF'}))}><Ionicons name={key==='emergency'||p[key]!=='OFF'?'checkbox':'square-outline'} size={23} color={key==='emergency'||p[key]!=='OFF'?palette.success:palette.muted}/></Pressable></View>)}</Card><Card><Text style={[s.sectionTitle,{color:palette.text}]}>Delivery Channels</Text>{(Object.keys(local.channels) as (keyof Channels)[]).map(k=><Channel key={k} name={k} value={local.channels[k]} change={v=>setLocal((x:Local)=>({...x,channels:{...x.channels,[k]:v}}))}/>)}</Card><DoNotDisturb p={p} setP={setP}/><Button title="Save Changes" variant="success" loading={saving} onPress={save}/></Screen>}
function Channel({name,value,change}:{name:keyof Channels;value:boolean;change:(v:boolean)=>void}){const{palette}=useAppTheme();const label=name==='inApp'?'In-App Messages':name==='email'?'Email':name==='sms'?'SMS':'Push Notifications';const icon:keyof typeof Ionicons.glyphMap=name==='inApp'?'chatbubble-outline':name==='email'?'mail-outline':name==='sms'?'chatbox-ellipses-outline':'notifications-outline';return <View style={[s.channel,{borderBottomColor:palette.border}]}><View style={[s.rowIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={20} color={palette.success}/></View><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{label}</Text><Muted>Receive {name==='sms'?'text messages':name==='email'?'emails and newsletters':name==='push'?'instant notifications':'messages inside the app'}</Muted></View><Switch value={value} onValueChange={change} trackColor={{false:palette.border,true:palette.success}}/></View>}
function DoNotDisturb({p,setP}:{p:Prefs;setP:(v:any)=>void}){const{palette}=useAppTheme();return <Card><Toggle label="Do Not Disturb" body="Pause non-urgent communications" value={p.quietHoursEnabled} change={v=>setP((x:Prefs)=>({...x,quietHoursEnabled:v}))}/>{p.quietHoursEnabled?<View style={s.times}><View style={{flex:1}}><Muted>From</Muted><Input value={p.quietStart} onChangeText={v=>setP((x:Prefs)=>({...x,quietStart:v}))}/></View><View style={{flex:1}}><Muted>To</Muted><Input value={p.quietEnd} onChangeText={v=>setP((x:Prefs)=>({...x,quietEnd:v}))}/></View></View>:null}</Card>}
function Toggle({label,body,value,change}:{label:string;body:string;value:boolean;change:(v:boolean)=>void}){const{palette}=useAppTheme();return <View style={[s.toggle,{borderBottomColor:palette.border}]}><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{label}</Text><Muted>{body}</Muted></View><Switch value={value} onValueChange={change} trackColor={{false:palette.border,true:palette.success}}/></View>}
function Cycle({label,value,values,change}:{label:string;value:string;values:string[];change:(v:string)=>void}){return <ExpandableSelect label={label} value={value} options={values} onChange={change}/>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1380,alignSelf:'center'},heading:{marginBottom:22},title:{fontSize:29,fontWeight:'900',marginBottom:5},layout:{flexDirection:'row',alignItems:'flex-start',gap:16},stack:{flexDirection:'column'},menu:{width:245,padding:12},menuTitle:{fontWeight:'900',margin:8},menuRow:{minHeight:48,borderRadius:10,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:11},main:{flex:1,width:'100%',minWidth:0},right:{width:290},sectionTitle:{fontSize:19,fontWeight:'900',marginBottom:5},channel:{minHeight:72,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:11},rowIcon:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'},rowTitle:{fontWeight:'900',marginBottom:2},list:{padding:0,overflow:'hidden'},cardHeading:{padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},messageRow:{minHeight:70,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:11,paddingHorizontal:14},times:{flexDirection:'row',gap:10,marginTop:12},toggle:{minHeight:68,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:10},cycle:{minHeight:58,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:10},note:{alignItems:'center',gap:13},hero:{borderRadius:16,alignItems:'center',padding:24,marginBottom:14},heroTitle:{fontSize:20,fontWeight:'900',marginTop:10,marginBottom:5},detail:{width:'100%',maxWidth:720,alignSelf:'center'},back:{minHeight:52,flexDirection:'row',alignItems:'center',gap:8},detailTitle:{fontSize:23,fontWeight:'900'},checkRow:{minHeight:61,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:10}});
