import {PolicyPage,PolicySection} from '@/components/PolicyPage';

const sections:PolicySection[]=[
 {heading:'1. Purpose and Scope',paragraphs:['These Guidelines apply to posts, comments, chat, profiles, events, meetings, documents, marketplace listings, service directories, voting, payments-related records and other activity on CDA Connect.','They supplement the Terms of Service and community-specific rules. Nigerian law and mandatory platform safety requirements always prevail.']},
 {heading:'2. Respect and Inclusion',paragraphs:['Treat people with dignity. Do not harass, bully, threaten, stalk, shame or coordinate abuse against another person.','Do not attack people based on ethnicity, nationality, sex, gender, religion, disability, age or another protected or vulnerable characteristic.','Criticism of ideas and leadership is allowed when expressed lawfully and without threats, defamation or targeted abuse.']},
 {heading:'3. Violence and Dangerous Conduct',paragraphs:['Do not praise, organise, instruct or credibly threaten violence, terrorism, kidnapping, trafficking, cult violence or serious physical harm.','Do not use CDA Connect to buy, sell or distribute unlawful weapons, controlled substances or dangerous materials.','For immediate danger, contact Nigerian emergency or law-enforcement services. Platform reports are not a substitute for emergency assistance.']},
 {heading:'4. Child Safety',paragraphs:['Any sexual exploitation, grooming, trafficking or sexualised content involving a child is prohibited. Never request, create, possess or share child sexual abuse material.','Do not expose a child’s private location, school, contact information or identity where doing so creates risk. Obtain appropriate guardian permission before sharing children’s images or records.','CDA Connect may remove content, preserve evidence and report suspected offences to appropriate authorities in line with Nigerian child-protection and cybercrime obligations.']},
 {heading:'5. Privacy, Confidentiality and Personal Data',paragraphs:['Do not publish another person’s private contact, identity, financial, health, biometric, location or family information without a lawful reason and required permission.','Information available to administrators, executives, moderators or finance officers must only be used for authorised community purposes.','Do not record or distribute private meetings, chats, votes or documents when prohibited by law, confidentiality duties or community rules.']},
 {heading:'6. Truthfulness, Defamation and Impersonation',paragraphs:['Do not knowingly spread false information, fabricate evidence, impersonate another person or organisation, or misrepresent official community instructions.','Correct significant errors promptly. Clearly distinguish personal opinion, satire and unverified claims from established fact.','Allegations of crime or misconduct should be made responsibly through appropriate reporting channels and must comply with applicable defamation and due-process requirements.']},
 {heading:'7. Fraud, Cybercrime and Platform Security',paragraphs:['Phishing, scams, identity theft, account trading, unauthorised access, malware, credential theft and circumvention of security controls are prohibited.','Never ask another user for a password, one-time verification code, card PIN or full payment credentials.','Do not scrape member data, probe systems, overload services or exploit a vulnerability. Report suspected vulnerabilities privately to support@cdaconnect.org.']},
 {heading:'8. Intellectual Property',paragraphs:['Share only content you created or have permission to use. Respect copyright, trademarks, confidential material and personality rights under applicable Nigerian law.','Do not distribute pirated media, copied documents, counterfeit branding or unauthorised commercial materials.','Rights holders may submit a detailed infringement notice to support@cdaconnect.org. Misleading or abusive notices may lead to action.']},
 {heading:'9. Spam and Manipulation',paragraphs:['Do not send repetitive unsolicited messages, create fake engagement, manipulate polls or votes, coordinate inauthentic accounts, or use deceptive links.','Promotional content must be relevant, accurate, permitted by community rules and compliant with consumer-protection and advertising requirements.']},
 {heading:'10. Marketplace and Local Services',paragraphs:['Listings must accurately describe the item, service, condition, price and material restrictions. Do not list unlawful, stolen, counterfeit, unsafe or recalled goods.','Service providers must not fabricate qualifications, licences, reviews or availability. Users should conduct appropriate checks before engaging a provider.','Do not use misleading pricing, hidden charges or unfair commercial practices. Statutory consumer rights under the FCCPA remain applicable.']},
 {heading:'11. Payments, Levies and Financial Records',paragraphs:['Only authorised officers may create levies or financial records for legitimate community purposes. Amounts, beneficiaries, deadlines and descriptions must be accurate and transparent.','Do not divert funds, falsify receipts, conceal material charges, solicit payment to an unauthorised account or misuse member financial information.','Suspected fraud should be reported to the community, relevant payment provider and competent authorities where appropriate.']},
 {heading:'12. Events, Meetings and Attendance',paragraphs:['Event and meeting information must be accurate and should disclose material safety, access, payment and cancellation conditions.','Do not falsify attendance, misuse attendance codes, scan membership credentials without authority or expose private attendee information.']},
 {heading:'13. Governance, Elections and Administration',paragraphs:['Administrators and election officers must apply published rules consistently, avoid conflicts of interest and preserve accurate records.','Do not intimidate voters, buy votes, manipulate results, suppress eligible participation or falsely claim an official result.','Platform tools support governance but do not replace a community constitution, applicable association rules, electoral law or lawful dispute procedures.']},
 {heading:'14. Reporting',paragraphs:['Use the closest available report option and provide the relevant content, account, community, dates and context. Do not submit knowingly false, retaliatory or duplicate reports.','For privacy, legal or security concerns, email support@cdaconnect.org. Preserve evidence safely but do not redistribute harmful material.']},
 {heading:'15. Moderation and Enforcement',paragraphs:['CDA Connect and authorised community moderators may warn users, limit distribution, remove content, change permissions, freeze features, suspend access or refer matters to authorities.','Decisions consider severity, intent, context, harm, repetition and cooperation. Serious safety, child-protection, fraud or security risks may require immediate action without advance notice.','Where appropriate, affected users may request review through support. A review does not guarantee reversal and may be limited where disclosure would endanger someone or compromise an investigation.']},
 {heading:'16. Community Responsibilities',paragraphs:['Communities should publish clear local rules, appoint trustworthy moderators, protect role access and provide fair internal complaint channels.','Local rules may be stricter where lawful, but may not authorise abuse, discrimination, fraud, privacy violations or conduct prohibited by these Guidelines.']},
 {heading:'17. Updates',paragraphs:['These Guidelines may change to reflect Nigerian law, regulator guidance, emerging harms and platform features. Material changes will be communicated appropriately.','Continued participation is subject to the current Guidelines and rights that cannot lawfully be waived.']},
];
export default function Guidelines(){return <PolicyPage intro="These Guidelines establish standards for lawful, safe and respectful participation across CDA Connect communities." sections={sections}/>}
