import {useEffect,useState} from 'react';
import {Alert,Platform,Pressable,StyleSheet,Switch,Text,View,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Button,Card,Muted,Screen,useAppTheme} from '@/components/UI';
import {api} from '@/lib/api';
import {secureGet,secureSet} from '@/lib/storage';
import {ExpandableSelect} from '@/components/ExpandableSelect';

type Access='NOBODY'|'ADMINS'|'MEMBERS';type Local={memberPosts:boolean;recommended:boolean;eventUpdates:boolean;announcements:boolean;polls:boolean;autoJoin:boolean;showMemberCount:boolean;activityStatus:boolean;adminMessages:boolean;comments:boolean;likes:boolean;sharing:boolean;mentions:boolean;tagging:boolean;emailDigest:'Off'|'Daily'|'Weekly';newCommunityAlerts:boolean;weeklyHighlights:boolean;defaultAudience:Access;saveAcrossDevices:boolean};
type Privacy={phoneVisibility:Access;emailVisibility:Access;whoCanMessage:Access;whoCanAddToGroups:Access;showOnlineStatus:boolean;showProfilePhoto:boolean;allowCommunityDiscovery:boolean};
type Notifications={directMessages:'ON'|'OFF';mentions:'ON'|'OFF';communityPosts:'ON'|'OFF'|'DAILY';polls:'ON'|'OFF';events:'ON'|'OFF';marketplace:'ON'|'OFF';businessPromotions:'ON'|'OFF';quietHoursEnabled:boolean;quietStart?:string;quietEnd?:string};
const localInitial:Local={memberPosts:true,recommended:true,eventUpdates:true,announcements:true,polls:false,autoJoin:false,showMemberCount:true,activityStatus:true,adminMessages:true,comments:true,likes:true,sharing:true,mentions:true,tagging:true,emailDigest:'Daily',newCommunityAlerts:true,weeklyHighlights:true,defaultAudience:'MEMBERS',saveAcrossDevices:true};
const privacyInitial:Privacy={phoneVisibility:'ADMINS',emailVisibility:'ADMINS',whoCanMessage:'MEMBERS',whoCanAddToGroups:'MEMBERS',showOnlineStatus:true,showProfilePhoto:true,allowCommunityDiscovery:true};
const notificationInitial:Notifications={directMessages:'ON',mentions:'ON',communityPosts:'DAILY',polls:'ON',events:'ON',marketplace:'OFF',businessPromotions:'OFF',quietHoursEnabled:false};
const labels:Record<Access,string>={NOBODY:'Only Me',ADMINS:'Admins',MEMBERS:'Members'};
const menu=[['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;
const top=StyleSheet.create({bar:{minHeight:68,flexDirection:'row',alignItems:'center',gap:8},back:{width:44,height:44,borderRadius:22,borderWidth:1,alignItems:'center',justifyContent:'center'},logo:{width:48,height:48,resizeMode:'contain'},brand:{fontSize:17,fontWeight:'900'},tagline:{fontSize:9},action:{width:44,height:44,alignItems:'center',justifyContent:'center'}});

export default function CommunityPreferences(){
 const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;const[local,setLocal]=useState<Local>(localInitial);const[privacy,setPrivacy]=useState<Privacy>(privacyInitial);const[notifications,setNotifications]=useState<Notifications>(notificationInitial);const[saving,setSaving]=useState(false);
 useEffect(()=>{secureGet('community-preferences').then(v=>v&&setLocal({...localInitial,...JSON.parse(v)})).catch(()=>{});api.get('/me/preferences').then(r=>{const p=r.data?.privacy;if(p)setPrivacy({phoneVisibility:p.PhoneVisibility??p.phoneVisibility??privacyInitial.phoneVisibility,emailVisibility:p.EmailVisibility??p.emailVisibility??privacyInitial.emailVisibility,whoCanMessage:p.WhoCanMessage??p.whoCanMessage??privacyInitial.whoCanMessage,whoCanAddToGroups:p.WhoCanAddToGroups??p.whoCanAddToGroups??privacyInitial.whoCanAddToGroups,showOnlineStatus:Boolean(p.ShowOnlineStatus??p.showOnlineStatus),showProfilePhoto:Boolean(p.ShowProfilePhoto??p.showProfilePhoto),allowCommunityDiscovery:Boolean(p.AllowCommunityDiscovery??p.allowCommunityDiscovery)});const n=r.data?.notifications;if(n)setNotifications({directMessages:n.DirectMessages??n.directMessages??'ON',mentions:n.Mentions??n.mentions??'ON',communityPosts:n.CommunityPosts??n.communityPosts??'DAILY',polls:n.Polls??n.polls??'ON',events:n.Events??n.events??'ON',marketplace:n.Marketplace??n.marketplace??'OFF',businessPromotions:n.BusinessPromotions??n.businessPromotions??'OFF',quietHoursEnabled:Boolean(n.QuietHoursEnabled??n.quietHoursEnabled),quietStart:n.QuietStart?String(n.QuietStart).slice(0,5):undefined,quietEnd:n.QuietEnd?String(n.QuietEnd).slice(0,5):undefined})}).catch(()=>Alert.alert('Community preferences','Your saved preferences could not be loaded.'))},[]);
 const set=(key:keyof Local,value:boolean)=>setLocal(x=>({...x,[key]:value}));const cycle=(value:Access):Access=>value==='MEMBERS'?'ADMINS':value==='ADMINS'?'NOBODY':'MEMBERS';
 const save=async()=>{setSaving(true);try{await secureSet('community-preferences',JSON.stringify(local));await Promise.all([api.put('/me/privacy-preferences',privacy),api.put('/me/notification-preferences',{...notifications,emergencyAlerts:'ALWAYS'})]);Alert.alert('Saved','Your community preferences have been updated.')}catch(e:any){Alert.alert('Unable to save',e.response?.data?.error||e.message)}finally{setSaving(false)}};
 return <Screen scroll contentStyle={s.page}><View style={s.heading}><Muted>Customize your community experience and content.</Muted></View>
  {!desktop?<View style={s.hero}><View style={[s.heroIcon,{backgroundColor:palette.successSoft}]}><Ionicons name="people-outline" size={54} color={palette.success}/></View><Text style={[s.heroTitle,{color:palette.text}]}>Customize your experience</Text><Muted style={{textAlign:'center'}}>Manage how you see and interact with communities.</Muted></View>:null}
  <View style={[s.layout,!desktop&&s.stack]}>
   {desktop?<Card style={s.menu}><Text style={[s.menuTitle,{color:palette.text}]}>Settings Menu</Text>{menu.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[s.menuRow,label==='Community Preferences'&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={label==='Community Preferences'?palette.success:palette.navy}/><Text style={{fontWeight:'800',color:label==='Community Preferences'?palette.success:palette.text}}>{label}</Text></Pressable>)}</Card>:null}
   <View style={s.main}>
    <View style={[s.grid,!desktop&&s.stack]}><PreferenceCard title="Community Content" help="Choose the updates you want to receive from your communities"><Toggle icon="newspaper-outline" title="Community posts" body="Posts and updates from communities you belong to" value={notifications.communityPosts!=='OFF'} change={v=>setNotifications(x=>({...x,communityPosts:v?'ON':'OFF'}))}/><Toggle icon="sparkles-outline" title="Recommended communities" body="See relevant community suggestions" value={privacy.allowCommunityDiscovery} change={v=>setPrivacy(x=>({...x,allowCommunityDiscovery:v}))}/><Toggle icon="calendar-outline" title="Event updates" body="Updates about events and activities" value={notifications.events==='ON'} change={v=>setNotifications(x=>({...x,events:v?'ON':'OFF'}))}/><Toggle icon="megaphone-outline" title="Community announcements" body="Important updates from community administrators" value={notifications.communityPosts!=='OFF'} change={v=>setNotifications(x=>({...x,communityPosts:v?'DAILY':'OFF'}))}/><Toggle icon="stats-chart-outline" title="Polls & surveys" body="New polls and voting reminders" value={notifications.polls==='ON'} change={v=>setNotifications(x=>({...x,polls:v?'ON':'OFF'}))}/></PreferenceCard>
     <PreferenceCard title="Membership Preferences" help="Manage how you join, approve and participate"><Toggle icon="enter-outline" title="Auto-join requests" body="Join communities without admin approval where allowed" value={local.autoJoin} change={v=>set('autoJoin',v)}/><Toggle icon="people-outline" title="Show my member count" body="Display your community count" value={local.showMemberCount} change={v=>set('showMemberCount',v)}/><Toggle icon="pulse-outline" title="Activity status" body="Show when you are active" value={local.activityStatus} change={v=>{set('activityStatus',v);setPrivacy(x=>({...x,showOnlineStatus:v}))}}/><Toggle icon="mail-outline" title="Admin messages" body="Receive messages from community admins" value={local.adminMessages} change={v=>set('adminMessages',v)}/><Action icon="shield-outline" title="Manage blocked communities" body="Review hidden or blocked communities" press={()=>router.push('/search')}/></PreferenceCard>
     <PreferenceCard title="Content & Interaction Preferences" help="Control how you interact and what content you see"><Toggle icon="chatbubble-outline" title="Enable comments by default" body="Allow comments on your posts" value={local.comments} change={v=>set('comments',v)}/><Toggle icon="heart-outline" title="Likes & reactions" body="Show reaction counts" value={local.likes} change={v=>set('likes',v)}/><Toggle icon="share-social-outline" title="Share posts" body="Allow others to share your posts" value={local.sharing} change={v=>set('sharing',v)}/><Toggle icon="at-outline" title="Mentions" body="Allow others to mention you" value={local.mentions} change={v=>set('mentions',v)}/><Toggle icon="pricetag-outline" title="Tagging" body="Allow others to tag you" value={local.tagging} change={v=>set('tagging',v)}/></PreferenceCard>
     <PreferenceCard title="Privacy in Communities" help="Control your visibility and privacy"><Cycle title="Profile visibility" value={labels[privacy.emailVisibility]} values={Object.values(labels)} change={v=>{const access=(Object.keys(labels) as Access[]).find(k=>labels[k]===v)||'MEMBERS';setPrivacy(x=>({...x,emailVisibility:access,phoneVisibility:access}))}}/><Cycle title="Who can invite you" value={labels[privacy.whoCanAddToGroups]} values={Object.values(labels)} change={v=>{const access=(Object.keys(labels) as Access[]).find(k=>labels[k]===v)||'MEMBERS';setPrivacy(x=>({...x,whoCanAddToGroups:access}))}}/><Toggle icon="mail-outline" title="Show my email" body="Allow permitted members to see email" value={privacy.emailVisibility!=='NOBODY'} change={v=>setPrivacy(x=>({...x,emailVisibility:v?'MEMBERS':'NOBODY'}))}/><Toggle icon="call-outline" title="Show my phone number" body="Allow permitted members to see phone" value={privacy.phoneVisibility!=='NOBODY'} change={v=>setPrivacy(x=>({...x,phoneVisibility:v?'MEMBERS':'NOBODY'}))}/></PreferenceCard></View>
    <PreferenceCard title="Email & Digest Preferences" help="Choose how often you receive community updates"><Cycle title="Email digest" value={local.emailDigest} values={['Off','Daily','Weekly']} change={v=>setLocal(x=>({...x,emailDigest:v as Local['emailDigest']}))}/><Toggle icon="notifications-outline" title="New community alerts" body="Get notified about new communities" value={local.newCommunityAlerts} change={v=>set('newCommunityAlerts',v)}/><Toggle icon="calendar-outline" title="Weekly highlights" body="Receive a weekly summary" value={local.weeklyHighlights} change={v=>set('weeklyHighlights',v)}/><Cycle title="Default post audience" value={labels[local.defaultAudience]} values={Object.values(labels)} change={v=>{const access=(Object.keys(labels) as Access[]).find(k=>labels[k]===v)||'MEMBERS';setLocal(x=>({...x,defaultAudience:access}))}}/></PreferenceCard>
    <Card style={[s.note,{backgroundColor:palette.successSoft}]}><Ionicons name="shield-checkmark-outline" size={24} color={palette.success}/><View style={{flex:1}}><Text style={{color:palette.success,fontWeight:'900'}}>Your preferences, your community experience</Text><Muted>These settings personalize your experience across communities.</Muted></View></Card><Button title="Save Preferences" variant="success" loading={saving} onPress={save}/>
   </View>
  </View>
 </Screen>
}

function PreferenceCard({title,help,children}:{title:string;help:string;children:React.ReactNode}){const{palette}=useAppTheme();return <Card style={s.prefCard}><Text style={[s.sectionTitle,{color:palette.text}]}>{title}</Text><Muted>{help}</Muted><View style={{marginTop:8}}>{children}</View></Card>}
function Toggle({icon,title,body,value,change}:{icon:keyof typeof Ionicons.glyphMap;title:string;body:string;value:boolean;change:(v:boolean)=>void}){const{palette}=useAppTheme();return <View style={[s.row,{borderBottomColor:palette.border}]}><View style={[s.rowIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={palette.success}/></View><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{title}</Text><Muted>{body}</Muted></View><Switch value={value} onValueChange={change} trackColor={{false:palette.border,true:palette.success}}/></View>}
function Cycle({title,value,values,change}:{title:string;value:string;values:string[];change:(v:string)=>void}){return <ExpandableSelect label={title} value={value} options={values} onChange={change}/>}
function Action({icon,title,body,press}:{icon:keyof typeof Ionicons.glyphMap;title:string;body:string;press:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={press} style={[s.row,{borderBottomColor:palette.border}]}><View style={[s.rowIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={palette.success}/></View><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{title}</Text><Muted>{body}</Muted></View><Ionicons name="chevron-forward" size={19} color={palette.muted}/></Pressable>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1420,alignSelf:'center'},heading:{marginBottom:22},title:{fontSize:29,fontWeight:'900',marginBottom:5},layout:{flexDirection:'row',alignItems:'flex-start',gap:16},stack:{flexDirection:'column'},menu:{width:245,padding:12},menuTitle:{fontWeight:'900',margin:8},menuRow:{minHeight:48,borderRadius:10,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:11},main:{flex:1,width:'100%',minWidth:0},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},prefCard:{flexGrow:1,flexBasis:'46%'},sectionTitle:{fontSize:18,fontWeight:'900',marginBottom:4},row:{minHeight:68,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:11},rowIcon:{width:39,height:39,borderRadius:12,alignItems:'center',justifyContent:'center'},rowTitle:{fontWeight:'900',marginBottom:2},note:{flexDirection:'row',alignItems:'center',gap:12},hero:{alignItems:'center',paddingVertical:8,marginBottom:13},heroIcon:{width:96,height:96,borderRadius:48,alignItems:'center',justifyContent:'center'},heroTitle:{fontSize:20,fontWeight:'900',marginTop:11,marginBottom:5}});
