import {useMemo,useState} from 'react';
import {Alert,FlatList,Image,Linking,Modal,Platform,Pressable,ScrollView,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {useMutation,useQueryClient} from '@tanstack/react-query';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {City,Country,type ICountry,type IState,State} from 'country-state-city';
import {getLGAsByState,getStateByName} from '@some19ice/nigeria-geo-core';
import {api} from '@/lib/api';
import {Button,Card,Input,Muted,Screen,useAppTheme} from '@/components/UI';

const steps=['Basic Details','Location','Settings','Review & Create'];
const categories=['Residents','Sports','Business','Environment','Faith','Education','Health & Wellness','Technology','Other'];
type Option={label:string;value:string};

export default function CreateCommunity(){
 const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;const qc=useQueryClient();
 const countries=useMemo(()=>Country.getAllCountries(),[]);const initialCountry=useMemo(()=>countries.find(x=>x.isoCode==='NG')??countries[0],[countries]);
 const[step,setStep]=useState(0);const[name,setName]=useState('');const[description,setDescription]=useState('');const[category,setCategory]=useState('Residents');const[selectedCountry,setSelectedCountry]=useState<ICountry>(initialCountry);const[selectedState,setSelectedState]=useState<IState|null>(null);const[lga,setLga]=useState('');const[area,setArea]=useState('');const[isPrivate,setPrivate]=useState(true);const[approval,setApproval]=useState(true);const[events,setEvents]=useState(true);const[discussions,setDiscussions]=useState(true);const[guidelines,setGuidelines]=useState('');const[tags,setTags]=useState('');
 const countryOptions=useMemo(()=>countries.map(x=>({label:`${x.flag} ${x.name}`,value:x.isoCode})),[countries]);const states=useMemo(()=>State.getStatesOfCountry(selectedCountry.isoCode),[selectedCountry]);const stateOptions=useMemo(()=>states.map(x=>({label:x.name,value:x.isoCode})),[states]);
 const lgaOptions=useMemo(()=>{if(!selectedState)return[];if(selectedCountry.isoCode==='NG'){const ngState=getStateByName(selectedState.name);return ngState?getLGAsByState(ngState.id).map(x=>({label:x.name,value:x.id})):[]}return City.getCitiesOfState(selectedCountry.isoCode,selectedState.isoCode).map(x=>({label:x.name,value:x.name}))},[selectedCountry,selectedState]);
 const latitude=Number(selectedState?.latitude||selectedCountry.latitude||9.082);const longitude=Number(selectedState?.longitude||selectedCountry.longitude||8.6753);const mapUrl=`https://staticmap.openstreetmap.de/staticmap.php?center=${latitude},${longitude}&zoom=${selectedState?8:5}&size=900x360&maptype=mapnik&markers=${latitude},${longitude},red-pushpin`;
 const country=selectedCountry.name,state=selectedState?.name||'',city=lga;
 function chooseCountry(option:Option){const next=countries.find(x=>x.isoCode===option.value);if(!next)return;setSelectedCountry(next);setSelectedState(null);setLga('')}
 const create=useMutation({mutationFn:async()=>(await api.post('/communities',{name,description,category,communityType:category,country,state,lga,city,specificArea:area,latitude,longitude,isPrivate})).data,onSuccess:(community)=>{qc.invalidateQueries({queryKey:['communities']});router.replace(`/community/${community.Id}`)},onError:(e:any)=>Alert.alert('Unable to create community',e.response?.data?.message||e.message)});
 const next=()=>{if(step===0&&(!name.trim()||!description.trim()))return Alert.alert('Complete the details','Community name and description are required.');if(step===1&&(!selectedState||!lga))return Alert.alert('Complete the location','Select a state/region and LGA/local area.');setStep(x=>Math.min(3,x+1))};
 return <Screen scroll contentStyle={desktop?s.desktop:undefined}>
  <View style={s.header}><Pressable onPress={()=>step?setStep(step-1):(router.canGoBack()?router.back():router.replace('/'))} style={s.back}><Ionicons name="arrow-back" size={25} color={palette.navy}/></Pressable><View><Text style={[s.title,{color:palette.text}]}>Create Community</Text><Muted>Create a community and become its owner and administrator.</Muted></View></View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.steps}>{steps.map((label,i)=><Pressable key={label} onPress={()=>i<step&&setStep(i)} style={s.step}><View style={[s.stepCircle,{borderColor:i<=step?palette.cyan:palette.border,backgroundColor:i<=step?palette.navy:palette.surface}]}>{i<step?<Ionicons name="checkmark" size={18} color="#fff"/>:<Text style={{color:i===step?'#fff':palette.text,fontWeight:'900'}}>{i+1}</Text>}</View><Text style={[s.stepLabel,{color:i===step?palette.navy:palette.muted}]}>{label}</Text>{i<3?<View style={[s.stepLine,{backgroundColor:i<step?palette.cyan:palette.border}]}/>:null}</Pressable>)}</ScrollView>
  {step===0?<><Section icon="people" title="Community Information" subtitle="Tell us about your community." palette={palette}><Label text="Community name *" palette={palette}/><Input value={name} onChangeText={setName} placeholder="e.g. Doncaster Community"/><Label text="Community description *" palette={palette}/><Input value={description} onChangeText={setDescription} placeholder="Describe its purpose and what members can expect…" multiline maxLength={500}/><Label text="Community category *" palette={palette}/><View style={s.optionGrid}>{categories.map(x=><Pressable key={x} onPress={()=>setCategory(x)} style={[s.option,{borderColor:category===x?'#007A5E':palette.border,backgroundColor:category===x?palette.successSoft:palette.surface}]}><Text style={{color:palette.text,fontWeight:'700'}}>{x}</Text></Pressable>)}</View></Section><Section icon="lock-closed" title="Community Privacy" subtitle="Choose who can find and join your community." palette={palette}><View style={desktop?s.two:undefined}><Choice selected={isPrivate} title="Private" body="Only invited members can see and join." onPress={()=>setPrivate(true)} palette={palette}/><Choice selected={!isPrivate} title="Public" body="Anyone can find and request to join." onPress={()=>setPrivate(false)} palette={palette}/></View></Section></>:null}
  {step===1?<Section icon="location" title="Community Location" subtitle="Help members find your community in their area." palette={palette}><Selector label="Country *" value={country} placeholder="Select country" options={countryOptions} onSelect={chooseCountry} palette={palette}/><View style={desktop?s.two:undefined}><View style={{flex:1}}><Selector label="State / Region *" value={state} placeholder="Select state or region" options={stateOptions} disabled={!stateOptions.length} onSelect={x=>{setSelectedState(states.find(item=>item.isoCode===x.value)||null);setLga('')}} palette={palette}/></View><View style={{flex:1}}><Selector label={selectedCountry.isoCode==='NG'?'Local Government Area (LGA) *':'City / Local Area *'} value={lga} placeholder={selectedCountry.isoCode==='NG'?'Select LGA':'Select city or local area'} options={lgaOptions} disabled={!selectedState} onSelect={x=>setLga(x.label)} palette={palette}/></View></View><Label text="Specific area" palette={palette}/><Input value={area} onChangeText={setArea} placeholder="e.g. Central Estate, Block A, Riverside"/><Pressable accessibilityRole="link" onPress={()=>Linking.openURL(`https://www.openstreetmap.org/?mlat=${latitude}&mlon=${longitude}#map=${selectedState?10:6}/${latitude}/${longitude}`)} style={s.mapWrap}><Image source={{uri:mapUrl}} style={s.mapImage}/><View style={s.mapCaption}><Ionicons name="location" size={24} color="#007A5E"/><View style={{flex:1}}><Text style={[s.mapTitle,{color:palette.text}]}>{[area,lga,state,country].filter(Boolean).join(', ')}</Text><Muted>Tap the map to open this location in OpenStreetMap.</Muted></View></View></Pressable></Section>:null}
  {step===2?<Section icon="settings" title="Community Settings" subtitle="Configure privacy, membership and participation." palette={palette}><View style={desktop?s.two:undefined}><Choice selected={isPrivate} title="Private community" body="Only invited members can discover it." onPress={()=>setPrivate(true)} palette={palette}/><Choice selected={!isPrivate} title="Public community" body="People can discover and request to join." onPress={()=>setPrivate(false)} palette={palette}/></View><Toggle label="Admin approval required" value={approval} onPress={()=>setApproval(!approval)} palette={palette}/><Toggle label="Allow members to create events" value={events} onPress={()=>setEvents(!events)} palette={palette}/><Toggle label="Allow members to start discussions" value={discussions} onPress={()=>setDiscussions(!discussions)} palette={palette}/><Label text="Community guidelines" palette={palette}/><Input value={guidelines} onChangeText={setGuidelines} placeholder="Be respectful, no spam, keep discussions relevant…" multiline maxLength={500}/><Label text="Community tags" palette={palette}/><Input value={tags} onChangeText={setTags} placeholder="residents, neighbourhood, safety"/></Section>:null}
  {step===3?<Section icon="clipboard" title="Review Your Community" subtitle="Review all details before creating your community." palette={palette}><View style={desktop?s.reviewGrid:undefined}><Review title="Basic Details" rows={[['Community Name',name],['Description',description],['Category',category]]} onEdit={()=>setStep(0)} palette={palette}/><Review title="Location" rows={[['Country',country],['State / Region',state],[selectedCountry.isoCode==='NG'?'LGA':'City / Local Area',lga],['Specific Area',area||'Not provided']]} onEdit={()=>setStep(1)} palette={palette}/><Review title="Settings" rows={[['Privacy',isPrivate?'Private':'Public'],['Member approval',approval?'Admin approval':'Automatic'],['Create events',events?'Allowed':'Admins only'],['Start discussions',discussions?'Allowed':'Admins only'],['Guidelines',guidelines||'Not added'],['Tags',tags||'Not added']]} onEdit={()=>setStep(2)} palette={palette}/></View></Section>:null}
  <View style={[s.footer,!desktop&&{flexDirection:'column-reverse',alignItems:'stretch'}]}>{step>0?<Button title={`Back: ${steps[step-1]}`} variant="secondary" onPress={()=>setStep(step-1)}/>:desktop?<View/>:null}<View style={[s.footerRight,!desktop&&{flexDirection:'column',alignItems:'stretch'}]}><Button title="Cancel" variant="ghost" onPress={()=>(router.canGoBack()?router.back():router.replace('/'))}/>{step<3?<Button title={`Next: ${steps[step+1]}`} onPress={next}/>:<Button title="Create Community" icon="sparkles" loading={create.isPending} onPress={()=>create.mutate()}/>}</View></View>
 </Screen>
}

function Selector({label,value,placeholder,options,disabled,onSelect,palette}:{label:string;value:string;placeholder:string;options:Option[];disabled?:boolean;onSelect:(option:Option)=>void;palette:any}){const[open,setOpen]=useState(false);const[search,setSearch]=useState('');const shown=useMemo(()=>{const q=search.trim().toLowerCase();return q?options.filter(x=>x.label.toLowerCase().includes(q)):options},[options,search]);return <><Label text={label} palette={palette}/><Pressable accessibilityRole="button" disabled={disabled} onPress={()=>setOpen(true)} style={[s.selector,{borderColor:palette.border,backgroundColor:palette.surface},disabled&&s.disabled]}><Text style={[s.selectorText,{color:value?palette.text:palette.muted}]}>{value||placeholder}</Text><Ionicons name="chevron-down" size={20} color={palette.muted}/></Pressable><Modal visible={open} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setOpen(false)}><View style={[s.modal,{backgroundColor:palette.background}]}><View style={s.modalHeader}><Text style={[s.modalTitle,{color:palette.text}]}>Select {label.replace(' *','')}</Text><Pressable onPress={()=>setOpen(false)}><Ionicons name="close" size={28} color={palette.text}/></Pressable></View><Input placeholder={`Search ${label.replace(' *','').toLowerCase()}`} value={search} onChangeText={setSearch}/><FlatList data={shown} keyExtractor={x=>x.value} keyboardShouldPersistTaps="handled" renderItem={({item})=><Pressable style={[s.selectorOption,{borderBottomColor:palette.border}]} onPress={()=>{onSelect(item);setSearch('');setOpen(false)}}><Text style={[s.selectorOptionText,{color:palette.text}]}>{item.label}</Text>{item.label===value?<Ionicons name="checkmark" size={22} color="#007A5E"/>:null}</Pressable>}/></View></Modal></>}
function Section({icon,title,subtitle,palette,children}:{icon:keyof typeof Ionicons.glyphMap;title:string;subtitle:string;palette:any;children:React.ReactNode}){return <Card style={s.section}><View style={s.sectionHead}><View style={[s.sectionIcon,{backgroundColor:palette.primarySoft}]}><Ionicons name={icon} size={23} color={palette.navy}/></View><View><Text style={[s.sectionTitle,{color:palette.text}]}>{title}</Text><Muted>{subtitle}</Muted></View></View>{children}</Card>}
function Label({text,palette}:{text:string;palette:any}){return <Text style={[s.label,{color:palette.text}]}>{text}</Text>}
function Choice({selected,title,body,onPress,palette}:{selected:boolean;title:string;body:string;onPress:()=>void;palette:any}){return <Pressable onPress={onPress} style={[s.choice,{borderColor:selected?palette.cyan:palette.border,backgroundColor:selected?palette.primarySoft:palette.surface}]}><Ionicons name={selected?'radio-button-on':'radio-button-off'} size={22} color={selected?palette.navy:palette.muted}/><View style={{flex:1}}><Text style={{color:palette.text,fontWeight:'900'}}>{title}</Text><Muted>{body}</Muted></View></Pressable>}
function Toggle({label,value,onPress,palette}:{label:string;value:boolean;onPress:()=>void;palette:any}){return <Pressable onPress={onPress} style={s.toggleRow}><View style={[s.switch,{backgroundColor:value?palette.navy:palette.border}]}><View style={[s.knob,{left:value?22:3}]}/></View><Text style={{color:palette.text,fontWeight:'700',flex:1}}>{label}</Text></Pressable>}
function Review({title,rows,onEdit,palette}:{title:string;rows:string[][];onEdit:()=>void;palette:any}){return <Card style={s.review}><View style={s.reviewHead}><Text style={[s.sectionTitle,{color:palette.text}]}>{title}</Text><Pressable onPress={onEdit}><Text style={s.edit}>Edit</Text></Pressable></View>{rows.map(([key,value])=><View key={key} style={s.reviewRow}><Text style={[s.reviewKey,{color:palette.text}]}>{key}</Text><Muted style={{flex:1}}>{value}</Muted></View>)}</Card>}
const s=StyleSheet.create({desktop:{maxWidth:1180},header:{flexDirection:'row',gap:16,alignItems:'center',marginBottom:20},back:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:28,fontWeight:'900'},steps:{minWidth:'100%',alignItems:'flex-start',paddingVertical:16,marginBottom:12},step:{minWidth:170,flex:1,alignItems:'center'},stepCircle:{width:38,height:38,borderRadius:19,borderWidth:2,alignItems:'center',justifyContent:'center'},stepLabel:{fontSize:12,fontWeight:'800',marginTop:7},stepLine:{position:'absolute',height:2,left:'62%',right:'-38%',top:18},section:{padding:22},sectionHead:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:20},sectionIcon:{width:46,height:46,borderRadius:23,alignItems:'center',justifyContent:'center'},sectionTitle:{fontSize:17,fontWeight:'900'},label:{fontSize:13,fontWeight:'800',marginTop:12,marginBottom:7},selector:{minHeight:52,borderWidth:1,borderRadius:14,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},selectorText:{fontSize:16,flex:1},disabled:{opacity:.5},modal:{flex:1,padding:20},modalHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:14},modalTitle:{fontSize:22,fontWeight:'900'},selectorOption:{minHeight:52,borderBottomWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:4},selectorOptionText:{fontSize:15,flex:1},optionGrid:{flexDirection:'row',flexWrap:'wrap',gap:9},option:{borderWidth:1,borderRadius:10,paddingHorizontal:14,paddingVertical:11},two:{flexDirection:'row',gap:14},choice:{flex:1,minHeight:92,borderWidth:1,borderRadius:12,padding:16,flexDirection:'row',gap:11,alignItems:'center'},mapWrap:{marginTop:18,borderRadius:16,overflow:'hidden',backgroundColor:'#E6F6FA'},mapImage:{width:'100%',height:240,backgroundColor:'#DCEEF2'},mapCaption:{padding:14,flexDirection:'row',alignItems:'center',gap:10},mapTitle:{fontWeight:'900'},toggleRow:{minHeight:55,flexDirection:'row',alignItems:'center',gap:12},switch:{width:46,height:27,borderRadius:14,padding:3},knob:{position:'absolute',top:3,width:21,height:21,borderRadius:11,backgroundColor:'#fff'},reviewGrid:{flexDirection:'row',flexWrap:'wrap',gap:14},review:{flexBasis:'47%',flexGrow:1},reviewHead:{flexDirection:'row',justifyContent:'space-between',marginBottom:12},edit:{color:'#007A5E',fontWeight:'900'},reviewRow:{flexDirection:'row',gap:12,marginBottom:8},reviewKey:{width:125,fontSize:12,fontWeight:'800'},footer:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12,marginVertical:10},footerRight:{flexDirection:'row',alignItems:'center',gap:10}});
