import {useEffect,useState} from 'react';
import {Alert,Platform,Pressable,StyleSheet,Switch,Text,View,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Button,Card,Muted,Screen,useAppTheme} from '@/components/UI';
import {api} from '@/lib/api';
import {flushQueue} from '@/lib/offline';
import {secureDelete,secureGet,secureSet} from '@/lib/storage';
import {ExpandableSelect} from '@/components/ExpandableSelect';

type Prefs={autoBackup:boolean;compressImages:boolean;streamVideos:boolean;autoDeleteTemp:boolean;lessMobileData:boolean;wifiQuality:boolean;showStats:boolean;autoClean:boolean;downloadQuality:string;autoDownload:string;fileLocation:string;maxFileSize:string;retention:string};
const initial:Prefs={autoBackup:true,compressImages:true,streamVideos:true,autoDeleteTemp:true,lessMobileData:true,wifiQuality:true,showStats:true,autoClean:true,downloadQuality:'Standard (720p)',autoDownload:'Only on Wi-Fi',fileLocation:'App storage',maxFileSize:'500 MB',retention:'30 days'};
const menu=[['person-outline','Account Settings','/account-settings'],['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;

export default function DataStorage(){
 const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;const[p,setP]=useState(initial);const[saving,setSaving]=useState(false);const[detail,setDetail]=useState(false);
 useEffect(()=>{Promise.all([secureGet('data-storage-preferences'),api.get('/me/preferences').catch(()=>null)]).then(([saved,res])=>{const local=saved?JSON.parse(saved):{};const app=res?.data?.app||{};setP(x=>({...x,...local,lessMobileData:app.dataSaverEnabled??local.lessMobileData??x.lessMobileData,autoBackup:app.offlineCacheEnabled??local.autoBackup??x.autoBackup,compressImages:app.autoDownloadImages??local.compressImages??x.compressImages,streamVideos:app.autoDownloadVideos??local.streamVideos??x.streamVideos}))}).catch(()=>{})},[]);
 const save=async()=>{setSaving(true);try{await secureSet('data-storage-preferences',JSON.stringify(p));await api.put('/me/app-preferences',{dataSaverEnabled:p.lessMobileData,offlineCacheEnabled:p.autoBackup,autoDownloadImages:p.compressImages,autoDownloadVideos:p.streamVideos});Alert.alert('Saved','Data and storage preferences updated.')}catch(e:any){Alert.alert('Unable to save',e.response?.data?.error||e.message)}finally{setSaving(false)}};
 const toggle=(key:keyof Prefs,value:boolean)=>setP(x=>({...x,[key]:value}));
 const clearCache=async()=>{await secureDelete('community-cache');await secureDelete('media-cache');Alert.alert('Cache cleared','Temporary files were removed. Your account and preferences were not affected.')};
 const exportData=async()=>{try{const response=await api.get('/me/preferences');const payload=JSON.stringify({exportedAt:new Date().toISOString(),preferences:response.data,storage:p},null,2);if(Platform.OS==='web'&&typeof document!=='undefined'){const blob=new Blob([payload],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='cda-connect-data.json';a.click();URL.revokeObjectURL(url)}else Alert.alert('Export prepared','Your data export is ready for the device download workflow.')}catch(e:any){Alert.alert('Export failed',e.response?.data?.error||e.message)}};
 if(detail)return <MobileDetail p={p} setP={setP} save={save} saving={saving} back={()=>setDetail(false)}/>;
 return <Screen scroll contentStyle={s.page}><View style={s.heading}><Text style={[s.title,{color:palette.text}]}>Data & Storage</Text><Muted>Manage your data, storage and downloads on CDA Connect.</Muted></View>
  {!desktop?<View style={[s.hero,{backgroundColor:palette.successSoft}]}><Ionicons name="cloud-upload-outline" size={68} color={palette.success}/><Text style={[s.heroTitle,{color:palette.text}]}>Manage your data</Text><Muted>Control your storage, downloads and data usage.</Muted></View>:null}
  <View style={[s.layout,!desktop&&s.stack]}>{desktop?<SettingsMenu/>:null}<View style={s.main}><StorageOverview/>
   {!desktop?<Card><Action icon="settings-outline" label="Storage Management" body="Auto backup, compression and cache" onPress={()=>setDetail(true)}/><Action icon="download-outline" label="Download Preferences" body="Quality, location and file size" onPress={()=>setDetail(true)}/><Action icon="wifi-outline" label="Data Usage" body="Mobile data and Wi-Fi options" onPress={()=>setDetail(true)}/><Action icon="folder-outline" label="Your Data" body="Export, delete and manage files" onPress={()=>setDetail(true)}/><Action icon="calendar-outline" label="Retention & Cleanup" body="Control how long data is kept" onPress={()=>setDetail(true)}/></Card>:null}
   {desktop?<><View style={s.two}><Card style={s.flex}><SectionTitle title="Storage Management" body="Manage how files and media are stored and used."/><Toggle icon="cloud-upload-outline" label="Auto backup my media" body="Automatically back up photos and videos" value={p.autoBackup} change={v=>toggle('autoBackup',v)}/><Toggle icon="image-outline" label="Compress images" body="Optimize images to save space" value={p.compressImages} change={v=>toggle('compressImages',v)}/><Toggle icon="videocam-outline" label="Stream videos" body="Play videos without full download" value={p.streamVideos} change={v=>toggle('streamVideos',v)}/><Toggle icon="trash-outline" label="Auto-delete temporary files" body="Remove cache after 30 days" value={p.autoDeleteTemp} change={v=>toggle('autoDeleteTemp',v)}/></Card><Card style={s.flex}><SectionTitle title="Download Preferences" body="Choose how files are downloaded."/><Cycle label="Download quality" value={p.downloadQuality} values={['Data saver (480p)','Standard (720p)','High (1080p)']} change={v=>setP(x=>({...x,downloadQuality:v}))}/><Cycle label="Auto-download media" value={p.autoDownload} values={['Never','Only on Wi-Fi','Wi-Fi and mobile']} change={v=>setP(x=>({...x,autoDownload:v}))}/><Cycle label="File download location" value={p.fileLocation} values={['App storage','Downloads folder']} change={v=>setP(x=>({...x,fileLocation:v}))}/><Cycle label="Maximum download size" value={p.maxFileSize} values={['100 MB','500 MB','1 GB']} change={v=>setP(x=>({...x,maxFileSize:v}))}/></Card></View>
    <View style={s.two}><Card style={s.flex}><SectionTitle title="Data Usage" body="Control how the app uses mobile data."/><Toggle icon="wifi-outline" label="Use less data on mobile networks" body="Optimize content for lower data usage" value={p.lessMobileData} change={v=>toggle('lessMobileData',v)}/><Toggle icon="wifi-outline" label="High-quality on Wi-Fi only" body="Save mobile data" value={p.wifiQuality} change={v=>toggle('wifiQuality',v)}/><Toggle icon="stats-chart-outline" label="Show data usage statistics" body="Track app data consumption" value={p.showStats} change={v=>toggle('showStats',v)}/></Card><Card style={s.flex}><SectionTitle title="Your Data" body="View, export or delete your personal data."/><Action icon="download-outline" label="Download your data" body="Get a copy of your personal data" onPress={exportData}/><Action icon="folder-open-outline" label="Manage stored files" body="View your uploaded files" onPress={()=>router.push('/documents' as any)}/><Action icon="trash-outline" label="Clear app cache" body="Free temporary storage" onPress={clearCache}/><Button title="Send queued changes now" variant="secondary" onPress={async()=>{const r=await flushQueue();Alert.alert('Offline queue',`${r.flushed} item(s) sent.`)}}/></Card></View>
    <Card><SectionTitle title="Retention & Cleanup" body="Set how long your data is kept."/><Cycle label="Keep deleted items for" value={p.retention} values={['7 days','30 days','90 days']} change={v=>setP(x=>({...x,retention:v}))}/><Toggle icon="trash-bin-outline" label="Auto-clean old cache" body="Remove unused temporary files" value={p.autoClean} change={v=>toggle('autoClean',v)}/></Card><Button title="Save Changes" variant="success" loading={saving} onPress={save}/></>:null}
   {!desktop?<Card style={[s.safe,{backgroundColor:palette.successSoft}]}><Ionicons name="shield-checkmark-outline" size={27} color={palette.success}/><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.success}]}>Your data is safe</Text><Muted>Encrypted and stored securely.</Muted></View></Card>:null}
  </View></View></Screen>
}

function SettingsMenu(){const{palette}=useAppTheme();return <Card style={s.menu}><Text style={[s.menuTitle,{color:palette.text}]}>Settings Menu</Text>{menu.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[s.menuRow,label==='Data & Storage'&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={label==='Data & Storage'?palette.success:palette.navy}/><Text style={{fontWeight:'800',color:label==='Data & Storage'?palette.success:palette.text}}>{label}</Text></Pressable>)}</Card>}
function StorageOverview(){const{palette}=useAppTheme();return <Card><SectionTitle title="Storage Overview" body="Track and manage your storage usage across CDA Connect."/><View style={s.overview}><View style={[s.ring,{borderColor:palette.border,borderTopColor:palette.success}]}><Text style={[s.used,{color:palette.text}]}>2.4 GB</Text><Muted>of 10 GB used</Muted><Text style={{color:palette.success,fontWeight:'900'}}>24%</Text></View><View style={s.storageList}>{[['Photos','1.2 GB','image-outline'],['Videos','640 MB','videocam-outline'],['Documents','320 MB','document-outline'],['Other','240 MB','albums-outline']].map(([name,size,icon])=><View key={name} style={s.storageRow}><Ionicons name={icon as any} size={18} color={palette.success}/><Text style={[s.rowTitle,{color:palette.text,flex:1}]}>{name}</Text><Text style={{color:palette.text,fontWeight:'800'}}>{size}</Text></View>)}</View><View style={[s.upgrade,{backgroundColor:palette.successSoft}]}><Ionicons name="cloud-upload-outline" size={43} color={palette.success}/><Text style={[s.rowTitle,{color:palette.text}]}>Need more space?</Text><Muted style={{textAlign:'center'}}>Upgrade for larger storage and extra features.</Muted><Button title="Upgrade Storage" variant="success" onPress={()=>Alert.alert('Storage plans','You have 7.6 GB available, so no upgrade is required yet.')}/></View></View></Card>}
function MobileDetail({p,setP,save,saving,back}:{p:Prefs;setP:(v:any)=>void;save:()=>Promise<void>;saving:boolean;back:()=>void}){const{palette}=useAppTheme();const toggle=(k:keyof Prefs,v:boolean)=>setP((x:Prefs)=>({...x,[k]:v}));return <Screen scroll contentStyle={s.detail}><Pressable onPress={back} style={s.back}><Ionicons name="chevron-back" size={27} color={palette.text}/><Text style={[s.detailTitle,{color:palette.text}]}>Data & Storage</Text></Pressable><Card><SectionTitle title="Storage Management"/><Toggle icon="cloud-upload-outline" label="Auto backup my media" body="Back up photos and videos" value={p.autoBackup} change={v=>toggle('autoBackup',v)}/><Toggle icon="image-outline" label="Compress images" body="Optimize to save space" value={p.compressImages} change={v=>toggle('compressImages',v)}/><Toggle icon="videocam-outline" label="Stream videos" body="Play without full download" value={p.streamVideos} change={v=>toggle('streamVideos',v)}/><Toggle icon="trash-outline" label="Auto-delete temp files" body="Remove cache after 30 days" value={p.autoDeleteTemp} change={v=>toggle('autoDeleteTemp',v)}/></Card><Card><SectionTitle title="Download Preferences"/><Cycle label="Download quality" value={p.downloadQuality} values={['Data saver (480p)','Standard (720p)','High (1080p)']} change={v=>setP((x:Prefs)=>({...x,downloadQuality:v}))}/><Cycle label="Auto-download" value={p.autoDownload} values={['Never','Only on Wi-Fi','Wi-Fi and mobile']} change={v=>setP((x:Prefs)=>({...x,autoDownload:v}))}/><Cycle label="File location" value={p.fileLocation} values={['App storage','Downloads folder']} change={v=>setP((x:Prefs)=>({...x,fileLocation:v}))}/><Cycle label="Max file size" value={p.maxFileSize} values={['100 MB','500 MB','1 GB']} change={v=>setP((x:Prefs)=>({...x,maxFileSize:v}))}/></Card><Card><SectionTitle title="Data Usage"/><Toggle icon="wifi-outline" label="Use less data on mobile" body="Optimize content" value={p.lessMobileData} change={v=>toggle('lessMobileData',v)}/><Toggle icon="wifi-outline" label="High-quality on Wi-Fi only" body="Save mobile data" value={p.wifiQuality} change={v=>toggle('wifiQuality',v)}/><Toggle icon="stats-chart-outline" label="Show data usage stats" body="Track consumption" value={p.showStats} change={v=>toggle('showStats',v)}/></Card><Button title="Save Changes" variant="success" loading={saving} onPress={save}/></Screen>}
function SectionTitle({title,body}:{title:string;body?:string}){const{palette}=useAppTheme();return <View style={{marginBottom:10}}><Text style={[s.sectionTitle,{color:palette.text}]}>{title}</Text>{body?<Muted>{body}</Muted>:null}</View>}
function Toggle({icon,label,body,value,change}:{icon:keyof typeof Ionicons.glyphMap;label:string;body:string;value:boolean;change:(v:boolean)=>void}){const{palette}=useAppTheme();return <View style={[s.toggle,{borderBottomColor:palette.border}]}><View style={[s.icon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={20} color={palette.success}/></View><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{label}</Text><Muted>{body}</Muted></View><Switch value={value} onValueChange={change} trackColor={{false:palette.border,true:palette.success}}/></View>}
function Cycle({label,value,values,change}:{label:string;value:string;values:string[];change:(v:string)=>void}){return <ExpandableSelect label={label} value={value} options={values} onChange={change}/>}
function Action({icon,label,body,onPress}:{icon:keyof typeof Ionicons.glyphMap;label:string;body:string;onPress:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={onPress} style={[s.action,{borderBottomColor:palette.border}]}><View style={[s.icon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={20} color={palette.success}/></View><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{label}</Text><Muted>{body}</Muted></View><Ionicons name="chevron-forward" size={19} color={palette.muted}/></Pressable>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1380,alignSelf:'center'},heading:{marginBottom:22},title:{fontSize:30,fontWeight:'900',marginBottom:5},layout:{flexDirection:'row',alignItems:'flex-start',gap:16},stack:{flexDirection:'column'},menu:{width:245,padding:12},menuTitle:{fontWeight:'900',margin:8},menuRow:{minHeight:48,borderRadius:10,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:11},main:{flex:1,width:'100%',minWidth:0,gap:14},two:{flexDirection:'row',gap:14},flex:{flex:1,minWidth:0},sectionTitle:{fontSize:19,fontWeight:'900',marginBottom:4},overview:{flexDirection:'row',alignItems:'center',gap:24,flexWrap:'wrap'},ring:{width:150,height:150,borderRadius:75,borderWidth:13,alignItems:'center',justifyContent:'center'},used:{fontSize:25,fontWeight:'900'},storageList:{flex:1,minWidth:230},storageRow:{minHeight:39,flexDirection:'row',alignItems:'center',gap:9},upgrade:{width:230,borderRadius:14,padding:16,alignItems:'center',gap:8},toggle:{minHeight:70,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:11},cycle:{minHeight:60,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:10},action:{minHeight:67,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:11},icon:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'},rowTitle:{fontWeight:'900',marginBottom:2},hero:{borderRadius:16,alignItems:'center',padding:24,marginBottom:14},heroTitle:{fontSize:21,fontWeight:'900',marginTop:8,marginBottom:4},safe:{flexDirection:'row',alignItems:'center',gap:12},detail:{width:'100%',maxWidth:720,alignSelf:'center'},back:{minHeight:54,flexDirection:'row',alignItems:'center',gap:8},detailTitle:{fontSize:23,fontWeight:'900'}});
