import {useState} from 'react';
import {Alert,Pressable,StyleSheet,Text,TextInput,View} from '@/platform/react-native';
import {router} from '@/router';
import {Ionicons} from '@/platform/icons';
import {Button,Card,Muted,Screen,useAppTheme} from '@/components/UI';
import {api} from '@/lib/api';
import {useAuth} from '@/store/auth';

const consequences=[['person-outline','Your profile will be deleted','Your photos, contact details and personal information will be permanently removed.'],['people-outline','You will lose access to communities','Your active community memberships and roles will be removed.'],['chatbubble-ellipses-outline','Messages will be deleted','Your message text and uploaded message media will be permanently redacted.'],['calendar-outline','Events and activities','Your registrations, RSVPs and personal participation data will be removed.'],['document-text-outline','Data cannot be recovered','Your credentials are destroyed and the deleted account cannot be restored.']] as const;
export default function DeleteAccount(){const{palette}=useAppTheme(),logout=useAuth(x=>x.logout);const[password,setPassword]=useState(''),[show,setShow]=useState(false),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false);const valid=Boolean(password)&&confirmed;
 const deactivate=()=>{if(!password)return Alert.alert('Password required','Enter your current password before deactivating your account.');Alert.alert('Deactivate account?','You will be signed out. Your profile and data will remain available if support reactivates your account.',[{text:'Cancel',style:'cancel'},{text:'Deactivate',style:'destructive',onPress:async()=>{try{setBusy(true);await api.post('/me/deactivate-secure',{password});await logout();router.replace('/(auth)/welcome')}catch(e:any){Alert.alert('Unable to deactivate account',e.response?.data?.error||e.message)}finally{setBusy(false)}}}])};
 const remove=()=>Alert.alert('Permanently delete your account?','This is the final confirmation. Your personal data cannot be recovered.',[{text:'Cancel',style:'cancel'},{text:'Delete permanently',style:'destructive',onPress:async()=>{try{setBusy(true);await api.post('/me/delete-account',{password,confirmation:'DELETE'});await logout();router.replace('/(auth)/welcome');Alert.alert('Account deleted','Your account and personal data have been deleted.')}catch(e:any){Alert.alert('Unable to delete account',e.response?.data?.error||e.message)}finally{setBusy(false)}}}]);
 return <Screen scroll contentStyle={s.page}><Muted style={s.subtitle}>We’re sorry to see you go. Please read the information below before deleting your account.</Muted>
  <Card style={[s.warning,{backgroundColor:palette.dangerSoft,borderColor:palette.danger}]}><View style={[s.warningIcon,{backgroundColor:'#FDE2E2'}]}><Ionicons name="trash-outline" size={27} color={palette.danger}/></View><View style={s.grow}><Text style={[s.warningTitle,{color:palette.danger}]}>This action cannot be undone</Text><Text style={[s.warningBody,{color:palette.text}]}>Deleting your account is permanent and your personal data will be lost forever.</Text></View></Card>
  <Text style={[s.sectionTitle,{color:palette.text}]}>What happens when you delete your account?</Text><View style={[s.list,{backgroundColor:palette.surface,borderColor:palette.border}]}>{consequences.map(([icon,title,body],index)=><View key={title} style={[s.row,index<consequences.length-1&&{borderBottomColor:palette.border,borderBottomWidth:1}]}><View style={[s.rowIcon,{backgroundColor:palette.dangerSoft}]}><Ionicons name={icon} size={23} color={palette.danger}/></View><View style={s.grow}><Text style={[s.rowTitle,{color:palette.text}]}>{title}</Text><Muted>{body}</Muted></View></View>)}</View>
  <Text style={[s.sectionTitle,{color:palette.text}]}>Before you go</Text><Card style={[s.option,{backgroundColor:palette.warningSoft,borderColor:palette.warning}]}><View style={s.optionCopy}><View style={[s.optionIcon,{backgroundColor:'#FFF1C7'}]}><Ionicons name="bulb-outline" size={22} color={palette.warning}/></View><View style={s.grow}><Text style={[s.rowTitle,{color:palette.text}]}>Consider deactivating instead</Text><Muted>Your data remains safe while your account is unavailable.</Muted></View></View><View style={s.optionButton}><Button title="Deactivate Account" variant="secondary" loading={busy} onPress={deactivate}/></View></Card>
  <Text style={[s.sectionTitle,{color:palette.text}]}>To continue, confirm your identity</Text><View style={[s.inputWrap,{borderColor:palette.border,backgroundColor:palette.surface}]}><Ionicons name="lock-closed-outline" size={22} color={palette.muted}/><TextInput accessibilityLabel="Current password" secureTextEntry={!show} autoCapitalize="none" autoCorrect={false} value={password} onChangeText={setPassword} placeholder="Enter your password" placeholderTextColor={palette.muted} style={[s.input,{color:palette.text}]}/><Pressable accessibilityLabel={show?'Hide password':'Show password'} onPress={()=>setShow(x=>!x)} style={s.eye}><Ionicons name={show?'eye-off-outline':'eye-outline'} size={24} color={palette.muted}/></Pressable></View>
  <Pressable accessibilityRole="checkbox" accessibilityState={{checked:confirmed}} onPress={()=>setConfirmed(x=>!x)} style={[s.confirm,{backgroundColor:palette.dangerSoft,borderColor:palette.danger}]}><View style={[s.checkbox,{borderColor:palette.danger,backgroundColor:confirmed?palette.danger:'transparent'}]}>{confirmed?<Ionicons name="checkmark" size={20} color="#fff"/>:null}</View><View style={s.grow}><Text style={[s.confirmTitle,{color:palette.danger}]}>I understand this action is permanent</Text><Text style={[s.confirmBody,{color:palette.text}]}>I confirm that I want to permanently delete my account and personal data from CDA Connect.</Text></View></Pressable>
  <Button title="Delete My Account" variant="danger" loading={busy} disabled={!valid||busy} onPress={remove}/>
 </Screen>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:800,alignSelf:'center',paddingBottom:120},subtitle:{fontSize:16,lineHeight:23,marginBottom:16},warning:{borderWidth:1,flexDirection:'row',alignItems:'center',gap:12,padding:16},warningIcon:{width:52,height:52,borderRadius:16,alignItems:'center',justifyContent:'center',flexShrink:0},grow:{flex:1,minWidth:0},warningTitle:{fontSize:18,fontWeight:'900',marginBottom:5},warningBody:{fontSize:15,lineHeight:22,fontWeight:'600'},sectionTitle:{fontSize:18,fontWeight:'900',marginTop:22,marginBottom:10},list:{borderWidth:1,borderRadius:15,overflow:'hidden'},row:{minHeight:92,flexDirection:'row',alignItems:'center',gap:11,paddingHorizontal:14},rowIcon:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center',flexShrink:0},rowTitle:{fontSize:16,fontWeight:'900',marginBottom:4},option:{borderWidth:1,gap:14},optionCopy:{width:'100%',flexDirection:'row',alignItems:'center',gap:11},optionIcon:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center',flexShrink:0},optionButton:{width:'100%'},inputWrap:{width:'100%',minHeight:60,borderWidth:1.5,borderRadius:14,flexDirection:'row',alignItems:'center',paddingLeft:14},input:{flex:1,minWidth:0,fontSize:16,paddingHorizontal:11,paddingVertical:14},eye:{width:50,height:54,alignItems:'center',justifyContent:'center',flexShrink:0},confirm:{borderWidth:1,borderRadius:14,padding:15,marginVertical:18,flexDirection:'row',alignItems:'flex-start',gap:11},checkbox:{width:26,height:26,borderRadius:6,borderWidth:2,alignItems:'center',justifyContent:'center',flexShrink:0},confirmTitle:{fontSize:16,fontWeight:'900',marginBottom:5},confirmBody:{fontSize:15,lineHeight:22}});
