import {useMemo,useState} from 'react';
import {Alert,Linking,Platform,Pressable,StyleSheet,Text,TextInput,View,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Card,Muted,Screen,useAppTheme} from '@/components/UI';

type Category={name:string;summary:string;icon:keyof typeof Ionicons.glyphMap;details:string[]};
const menu=[['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;
const categories:Category[]=[
 {name:'Getting Started',summary:'Create your account and learn the main navigation.',icon:'rocket-outline',details:['Complete your profile so communities can recognise you.','Use Home for updates, Communities for groups, Calendar for events, Profile for your account and Settings for preferences.','Join a community with an invite code or create one when you have the required permissions.']},
 {name:'Account & Profile',summary:'Manage your identity, profile details and account.',icon:'person-outline',details:['Edit your name, contact details, profile image and personal information from Profile.','Use Security to change your password, verify your email or phone and enable two-factor authentication.','Download or delete account data from the relevant profile and settings controls.']},
 {name:'Communities & Membership',summary:'Create, join and participate in communities.',icon:'people-outline',details:['Community owners and admins can manage membership, roles, rules and approval settings.','Members can read posts, join discussions, attend meetings and access enabled community services.','Use the community menu to find members, executives, documents, services and other workspace tools.']},
 {name:'Posts, Chat & Communication',summary:'Use feeds, comments, messages and communication preferences.',icon:'chatbubbles-outline',details:['Create posts from a community feed and use the available audience and content controls.','Community chat supports direct participation and group conversations where enabled.','Communication settings control in-app messages, email delivery and quiet-hour preferences.']},
 {name:'Events, Meetings & Calendar',summary:'Schedule activities and manage attendance.',icon:'calendar-outline',details:['Calendar combines your community events and meetings in one place.','Authorised organisers can create events, schedule meetings and manage attendance.','Use attendance codes or authorised membership-card scanning when those options are enabled.']},
 {name:'Payments & Finance',summary:'Understand dues, levies, donations and records.',icon:'wallet-outline',details:['Community finance pages show levies, payments, receipts and financial records available to your role.','Always confirm the community, amount and payment instructions before completing a transaction.','Contact a community administrator if a payment is missing or has an incorrect status.']},
 {name:'Documents, Data & Storage',summary:'Manage files, downloads, cache and data usage.',icon:'folder-open-outline',details:['Community documents are available according to membership and role permissions.','Data & Storage controls downloads, quality, mobile-data usage, retention and temporary cache.','Clearing cache removes temporary files without deleting your account or saved preferences.']},
 {name:'Privacy, Safety & Security',summary:'Control privacy, verification and secure access.',icon:'shield-checkmark-outline',details:['Privacy settings control visibility, messaging permissions and blocked accounts.','Security provides password changes, two-factor authentication, contact verification and active-session sign-out.','Report unsafe content through the available report control and contact emergency services for immediate danger.']},
 {name:'Notifications & Preferences',summary:'Choose which updates you receive and how.',icon:'notifications-outline',details:['Notification settings control activity categories and delivery channels.','Opening a notification marks it as read; notifications expire automatically after their retention period.','Community preferences customise recommendations, posts, events, polls and other community updates.']},
 {name:'Appearance, Accessibility & Language',summary:'Personalise display, accessibility and app language.',icon:'accessibility-outline',details:['Choose light, dark or device-system appearance from Settings.','Accessibility options improve readability and interaction preferences.','Language selection changes supported app text, while regional settings affect dates, times and numbers.']},
 {name:'Troubleshooting & Support',summary:'Resolve common problems or contact the support team.',icon:'construct-outline',details:['Refresh the page and confirm your internet connection before retrying a failed action.','Install the latest app version and ensure required notification, camera or biometric permissions are enabled.','Include the page name, time, device type and exact error when emailing support@cdaconnect.org.']},
];

export default function Help(){const{palette}=useAppTheme(),{width}=useWindowDimensions(),desktop=Platform.OS==='web'&&width>=900;const[q,setQ]=useState(''),[expanded,setExpanded]=useState<string|null>(null);const filtered=useMemo(()=>{const term=q.trim().toLowerCase();return term?categories.filter(c=>`${c.name} ${c.summary} ${c.details.join(' ')}`.toLowerCase().includes(term)):categories},[q]);
 const emailSupport=async(problem=false)=>{const subject=encodeURIComponent(problem?'CDA Connect app problem':'CDA Connect support request'),body=encodeURIComponent(problem?'Please describe the problem, page, device and any error message:\n\n':'Please describe how we can help:\n\n');try{await Linking.openURL(`mailto:support@cdaconnect.org?subject=${subject}&body=${body}`)}catch{Alert.alert('Email support','Send your request to support@cdaconnect.org.')}};
 return <Screen scroll contentStyle={s.page}><View style={s.heading}><Muted>We’re here to help. Search the guide, explore a category, or email support.</Muted></View><View style={[s.layout,!desktop&&s.stack]}>{desktop?<SettingsMenu/>:null}<View style={s.main}>
  <Card style={s.hero}><View style={s.heroRow}><View style={[s.agent,{backgroundColor:palette.successSoft}]}><Ionicons name="headset-outline" size={40} color={palette.success}/></View><View style={s.heroCopy}><Text style={[s.heroTitle,{color:palette.text}]}>How can we help you today?</Text><Muted>Search the CDA Connect help guide or expand a category below.</Muted></View></View><View style={[s.search,{borderColor:palette.border,backgroundColor:palette.surface}]}><Ionicons name="search-outline" size={22} color={palette.muted}/><TextInput accessibilityLabel="Search help" value={q} onChangeText={setQ} placeholder="Search help topics..." placeholderTextColor={palette.muted} style={[s.searchInput,{color:palette.text}]}/>{q?<Pressable accessibilityLabel="Clear search" onPress={()=>setQ('')} style={s.clear}><Ionicons name="close-circle" size={22} color={palette.muted}/></Pressable>:null}</View></Card>
  <Text style={[s.blockTitle,{color:palette.text}]}>Help Categories</Text><Card style={s.categories}>{filtered.length?filtered.map(category=><CategoryRow key={category.name} category={category} open={expanded===category.name} press={()=>setExpanded(value=>value===category.name?null:category.name)}/>):<View style={s.noResults}><Ionicons name="search-outline" size={30} color={palette.muted}/><Muted>No help categories match “{q}”.</Muted></View>}</Card>
  <Card style={s.support}><View style={[s.supportIcon,{backgroundColor:palette.successSoft}]}><Ionicons name="mail-outline" size={28} color={palette.success}/></View><View style={s.supportCopy}><Text style={[s.supportTitle,{color:palette.text}]}>Still need help?</Text><Muted>Email support@cdaconnect.org and our support team will assist you.</Muted></View><View style={s.supportActions}><Pressable accessibilityRole="button" onPress={()=>emailSupport(false)} style={[s.supportButton,{backgroundColor:palette.success}]}><Ionicons name="headset-outline" size={20} color="#fff"/><Text style={s.supportButtonText}>Contact Support</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>emailSupport(true)} style={[s.reportButton,{borderColor:palette.danger}]}><Ionicons name="warning-outline" size={20} color={palette.danger}/><Text style={[s.reportText,{color:palette.danger}]}>Report Problem</Text></Pressable></View><Pressable accessibilityRole="button" accessibilityLabel="Delete Account" onPress={()=>router.push('/delete-account')} style={[s.deleteButton,{borderColor:palette.danger,backgroundColor:palette.dangerSoft}]}><Ionicons name="trash-outline" size={21} color={palette.danger}/><Text style={[s.deleteText,{color:palette.danger}]}>Delete Account</Text></Pressable></Card>
 </View></View></Screen>}

function CategoryRow({category,open,press}:{category:Category;open:boolean;press:()=>void}){const{palette}=useAppTheme();return <View style={[s.categoryWrap,{borderBottomColor:palette.border}]}><Pressable accessibilityRole="button" accessibilityState={{expanded:open}} onPress={press} style={s.categoryHead}><View style={[s.categoryIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={category.icon} size={25} color={palette.success}/></View><View style={s.grow}><Text style={[s.categoryTitle,{color:palette.text}]}>{category.name}</Text><Muted>{category.summary}</Muted></View><Ionicons name={open?'chevron-up':'chevron-down'} size={21} color={palette.muted}/></Pressable>{open?<View style={[s.categoryBody,{backgroundColor:palette.background,borderTopColor:palette.border}]}>{category.details.map((detail,index)=><View key={detail} style={s.detailRow}><View style={[s.bullet,{backgroundColor:palette.success}]}/><Text style={[s.detailText,{color:palette.text}]}>{detail}</Text></View>)}</View>:null}</View>}
function SettingsMenu(){const{palette}=useAppTheme();return <Card style={s.menu}><Text style={[s.menuTitle,{color:palette.text}]}>Settings Menu</Text>{menu.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[s.menuRow,label==='Help & Support'&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={label==='Help & Support'?palette.success:palette.navy}/><Text style={{fontWeight:'800',color:label==='Help & Support'?palette.success:palette.text}}>{label}</Text></Pressable>)}</Card>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1380,alignSelf:'center',paddingBottom:120},heading:{marginBottom:14},layout:{flexDirection:'row',alignItems:'flex-start',gap:16},stack:{flexDirection:'column'},menu:{width:245,padding:12},menuTitle:{fontWeight:'900',margin:8},menuRow:{minHeight:48,borderRadius:10,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:11},main:{flex:1,width:'100%',minWidth:0,gap:15},hero:{padding:16},heroRow:{width:'100%',flexDirection:'row',alignItems:'center',gap:12,marginBottom:14},agent:{width:72,height:68,borderRadius:22,alignItems:'center',justifyContent:'center',flexShrink:0},heroCopy:{flex:1,minWidth:0},heroTitle:{fontSize:20,fontWeight:'900',marginBottom:4},search:{width:'100%',minHeight:56,borderWidth:1.5,borderRadius:14,flexDirection:'row',alignItems:'center',paddingLeft:14},searchInput:{flex:1,minWidth:0,fontSize:16,paddingHorizontal:10,paddingVertical:13},clear:{width:46,height:50,alignItems:'center',justifyContent:'center'},blockTitle:{fontSize:20,fontWeight:'900',marginTop:3},categories:{paddingVertical:0,overflow:'hidden'},categoryWrap:{borderBottomWidth:1},categoryHead:{minHeight:78,paddingVertical:10,flexDirection:'row',alignItems:'center',gap:11},categoryIcon:{width:46,height:46,borderRadius:14,alignItems:'center',justifyContent:'center',flexShrink:0},grow:{flex:1,minWidth:0},categoryTitle:{fontSize:16,fontWeight:'900',marginBottom:3},categoryBody:{borderTopWidth:1,padding:14,gap:11},detailRow:{flexDirection:'row',alignItems:'flex-start',gap:9},bullet:{width:7,height:7,borderRadius:4,marginTop:7,flexShrink:0},detailText:{flex:1,minWidth:0,fontSize:15,lineHeight:22},noResults:{minHeight:110,alignItems:'center',justifyContent:'center',gap:8,padding:16},support:{flexDirection:'row',alignItems:'center',gap:12,flexWrap:'wrap'},supportIcon:{width:52,height:52,borderRadius:16,alignItems:'center',justifyContent:'center',flexShrink:0},supportCopy:{flex:1,minWidth:190},supportTitle:{fontSize:18,fontWeight:'900',marginBottom:3},supportActions:{width:'100%',flexDirection:'row',gap:9},supportButton:{flex:1,minHeight:50,borderRadius:12,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},supportButtonText:{color:'#fff',fontWeight:'900',textAlign:'center'},reportButton:{flex:1,minHeight:50,borderWidth:1.5,borderRadius:12,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},reportText:{fontWeight:'900',textAlign:'center'},deleteButton:{width:'100%',minHeight:52,borderWidth:1.5,borderRadius:12,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},deleteText:{fontWeight:'900'}});
