import {useState} from 'react';
import {Platform,Pressable,StyleSheet,Switch,Text,View,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Button,Card,Muted,Screen,useAppTheme} from '@/components/UI';
import {AppLanguage,useAccessibility} from '@/store/accessibility';
import {languageNames,useI18n} from '@/i18n';
import {ExpandableSelect} from '@/components/ExpandableSelect';

const flags:Record<AppLanguage,string>={en:'🇬🇧',fr:'🇫🇷',es:'🇪🇸',pt:'🇵🇹',ar:'🇸🇦',yo:'🇳🇬',ig:'🇳🇬',ha:'🇳🇬'};
const english:Record<AppLanguage,string>={en:'English (UK)',fr:'French',es:'Spanish',pt:'Portuguese',ar:'Arabic',yo:'Yoruba',ig:'Igbo',ha:'Hausa'};
const languages=Object.keys(languageNames) as AppLanguage[];
const menu=[['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;
const top=StyleSheet.create({bar:{minHeight:68,flexDirection:'row',alignItems:'center',gap:8},back:{width:44,height:44,borderRadius:22,borderWidth:1,alignItems:'center',justifyContent:'center'},logo:{width:48,height:48,resizeMode:'contain'},brand:{fontSize:17,fontWeight:'900'},tagline:{fontSize:9},action:{width:44,height:44,alignItems:'center',justifyContent:'center'}});

export default function Language(){
 const a=useAccessibility();const{t}=useI18n();const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;const[languagesOpen,setLanguagesOpen]=useState(false);
 const cycle=<T extends string>(value:T,values:T[])=>values[(values.indexOf(value)+1)%values.length];
 return <Screen scroll contentStyle={s.page}><View style={s.heading}><Muted>{t('languageSubtitle')}</Muted></View>
  {!desktop?<View style={s.hero}><View style={[s.globe,{backgroundColor:palette.successSoft}]}><Ionicons name="globe-outline" size={52} color={palette.success}/></View><Text style={[s.heroTitle,{color:palette.text}]}>Choose your language</Text><Muted style={{textAlign:'center'}}>Select your preferred language for CDA Connect.</Muted></View>:null}
  <View style={[s.layout,!desktop&&s.stack]}>
   {desktop?<Card style={s.menu}><Text style={[s.menuTitle,{color:palette.text}]}>Settings Menu</Text>{menu.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[s.menuRow,label==='Language'&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={label==='Language'?palette.success:palette.navy}/><Text style={{fontWeight:'800',color:label==='Language'?palette.success:palette.text}}>{label}</Text></Pressable>)}</Card>:null}
   <View style={s.main}>
    <Card><Text style={[s.sectionTitle,{color:palette.text}]}>{t('appLanguage')}</Text><Muted>{t('appLanguageHelp')}</Muted><Pressable accessibilityRole="button" accessibilityLabel={t('supportedLanguages')} accessibilityState={{expanded:languagesOpen}} onPress={()=>setLanguagesOpen(v=>!v)} style={[s.current,{borderColor:palette.border}]}><Text style={s.flag}>{flags[a.language]}</Text><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{languageNames[a.language]}</Text><Muted>{english[a.language]}</Muted></View><Ionicons name={languagesOpen?'chevron-up':'chevron-down'} size={20} color={palette.muted}/></Pressable></Card>
    {languagesOpen?<Card style={s.list}><Text style={[s.sectionTitle,s.listHeading,{color:palette.text}]}>{t('supportedLanguages')}</Text>{languages.map(code=><Pressable accessibilityRole="radio" accessibilityState={{checked:a.language===code}} key={code} onPress={()=>{void a.update({language:code});setLanguagesOpen(false)}} style={[s.languageRow,{borderBottomColor:palette.border}]}><Text style={s.flag}>{flags[code]}</Text><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{languageNames[code]}</Text><Muted>{english[code]}</Muted></View><Ionicons name={a.language===code?'radio-button-on':'radio-button-off'} size={22} color={a.language===code?palette.success:palette.muted}/></Pressable>)}</Card>:null}
    {!desktop?<Regional/>:null}
    <Card style={[s.help,{backgroundColor:palette.successSoft}]}><Ionicons name="shield-checkmark-outline" size={23} color={palette.success}/><View style={{flex:1}}><Text style={{fontWeight:'900',color:palette.success}}>Help improve translations</Text><Muted>You can help make CDA Connect better by sharing translation feedback.</Muted></View><Button title="Contact Support" variant="secondary" onPress={()=>router.push('/help')}/></Card>
   </View>
   {desktop?<View style={s.right}><Regional/></View>:null}
  </View>
 </Screen>

 function Regional(){return <><Card><Text style={[s.sectionTitle,{color:palette.text}]}>Regional Format</Text><Muted>Customize how dates, times and numbers appear.</Muted><Picker label="Date Format" value={a.dateFormat==='DMY'?'24 May 2026':a.dateFormat==='MDY'?'May 24, 2026':'2026-05-24'} values={['24 May 2026','May 24, 2026','2026-05-24']} change={v=>a.update({dateFormat:v==='24 May 2026'?'DMY':v==='May 24, 2026'?'MDY':'YMD'})}/><Picker label="Time Format" value={a.timeFormat==='12'?'10:30 AM':'22:30'} values={['10:30 AM','22:30']} change={v=>a.update({timeFormat:v==='10:30 AM'?'12':'24'})}/><Picker label="First Day of Week" value={a.firstDayOfWeek} values={['Monday','Sunday']} change={v=>a.update({firstDayOfWeek:v as typeof a.firstDayOfWeek})}/><Picker label="Numbers" value={a.numberFormat==='comma-dot'?'1,234.56':'1.234,56'} values={['1,234.56','1.234,56']} change={v=>a.update({numberFormat:v==='1,234.56'?'comma-dot':'dot-comma'})}/><View style={[s.preview,{backgroundColor:palette.successSoft}]}><Text style={[s.rowTitle,{color:palette.text}]}>Example Preview</Text><Muted>{a.dateFormat==='DMY'?'24 May 2026':a.dateFormat==='MDY'?'May 24, 2026':'2026-05-24'} · {a.timeFormat==='12'?'10:30 AM':'22:30'} · {a.numberFormat==='comma-dot'?'1,234.56':'1.234,56'}</Muted></View></Card>
  <Card><Text style={[s.sectionTitle,{color:palette.text}]}>Translation Preferences</Text><Muted>Manage how content is translated.</Muted><Toggle title="Auto-translate posts" body="Translate posts to your language" value={a.autoTranslate} onChange={v=>a.update({autoTranslate:v})}/><Toggle title="Translate comments" body="Translate comments to your language" value={a.translateComments} onChange={v=>a.update({translateComments:v})}/><Pressable onPress={()=>{const next:AppLanguage[]=a.preferredContentLanguages.includes('fr')?['es']:['fr','es'];a.update({preferredContentLanguages:next})}} style={[s.picker,{borderBottomColor:palette.border}]}><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>Preferred content languages</Text><Muted>{a.preferredContentLanguages.map(x=>languageNames[x]).join(', ')||'None selected'}</Muted></View><Ionicons name="chevron-forward" size={20} color={palette.muted}/></Pressable></Card></>}
}

function Picker({label,value,values,change}:{label:string;value:string;values:string[];change:(v:string)=>void}){return <ExpandableSelect label={label} value={value} options={values} onChange={change}/>}
function Toggle({title,body,value,onChange}:{title:string;body:string;value:boolean;onChange:(v:boolean)=>void}){const{palette}=useAppTheme();return <View style={[s.toggle,{borderBottomColor:palette.border}]}><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{title}</Text><Muted>{body}</Muted></View><Switch value={value} onValueChange={onChange} trackColor={{false:palette.border,true:palette.success}}/></View>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1380,alignSelf:'center'},heading:{marginBottom:22},title:{fontSize:29,fontWeight:'900',marginBottom:5},layout:{flexDirection:'row',alignItems:'flex-start',gap:16},stack:{flexDirection:'column'},menu:{width:245,padding:12},menuTitle:{fontWeight:'900',margin:8},menuRow:{minHeight:48,borderRadius:10,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:11},main:{flex:1,width:'100%',minWidth:0},right:{width:310},sectionTitle:{fontSize:19,fontWeight:'900',marginBottom:6},current:{minHeight:68,borderWidth:1,borderRadius:12,flexDirection:'row',alignItems:'center',gap:11,paddingHorizontal:14,marginTop:16},flag:{fontSize:26},rowTitle:{fontWeight:'900',marginBottom:2},notice:{borderRadius:12,padding:13,marginTop:13,flexDirection:'row',alignItems:'center',gap:10},list:{padding:0,overflow:'hidden'},listHeading:{padding:16,paddingBottom:8},languageRow:{minHeight:66,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:16},picker:{minHeight:60,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:10},toggle:{minHeight:72,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:12},preview:{borderRadius:12,padding:14,marginTop:14,gap:5},help:{flexDirection:'row',alignItems:'center',gap:12},hero:{alignItems:'center',paddingVertical:8,marginBottom:12},globe:{width:94,height:94,borderRadius:47,alignItems:'center',justifyContent:'center'},heroTitle:{fontSize:20,fontWeight:'900',marginTop:12,marginBottom:5}});
