import {useMemo,useState} from 'react';
import {Alert,Pressable,StyleSheet,Text,View} from 'react-native';
import {router} from 'expo-router';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {Card,EmptyState,Muted,Screen,useAppTheme} from '@/components/UI';

type NavigationData={type?:string;communityId?:string;postId?:string;commentId?:string;conversationId?:string;announcementId?:string;pollId?:string;eventId?:string;listingId?:string;documentId?:string};
type Notification={Id:string;NotificationType:string;Title:string;Body:string;CommunityId:string;CommunityName:string;EntityId?:string;NavigationData:NavigationData;CreatedAt:string;ReadAt?:string;DeliveryStatus:string;IsRead:boolean};

export default function Notifications(){
 const{palette}=useAppTheme(),client=useQueryClient(),[expanded,setExpanded]=useState<Record<string,boolean>>({});
 const q=useQuery<Notification[]>({queryKey:['notifications'],queryFn:async()=>(await api.get('/me/notifications')).data,refetchInterval:30000,refetchOnWindowFocus:true});
 const mark=useMutation({mutationFn:async(ids:string[])=>api.put('/me/notifications/read',{notificationIds:ids}),onSuccess:()=>client.invalidateQueries({queryKey:['notifications']}),onError:()=>Alert.alert('Unable to update','Notification read status could not be synchronised.')});
 const markAll=useMutation({mutationFn:async()=>api.put('/me/notifications/read-all'),onSuccess:()=>client.invalidateQueries({queryKey:['notifications']}),onError:()=>Alert.alert('Unable to update','Notification read status could not be synchronised.')});
 const visible=q.data||[],groups=useMemo(()=>{const map=new Map<string,Notification[]>();for(const item of visible){const key=`${item.NotificationType}:${item.Title}`;map.set(key,[...(map.get(key)||[]),item])}return[...map.entries()]},[visible]);
 const open=(n:Notification)=>{if(n.Body==='This content is no longer available.')return Alert.alert('Unavailable',n.Body);const d=n.NavigationData||{},path=d.type==='CHAT_MESSAGE'&&d.conversationId?`/chat/${d.conversationId}`:d.type==='POLL'&&d.pollId?`/community/${n.CommunityId}/polls/${d.pollId}`:d.type==='EVENT'?`/community/${n.CommunityId}/events`:d.type==='MARKETPLACE'?`/community/${n.CommunityId}/marketplace`:d.type==='ANNOUNCEMENT'?`/community/${n.CommunityId}/announcements`:`/community/${n.CommunityId}/feed${d.postId?`?postId=${d.postId}${d.commentId?`&commentId=${d.commentId}`:''}`:''}`;router.push(path as any)};
 const unread=visible.filter(item=>!item.ReadAt).length;
 return <Screen scroll contentStyle={s.page}>{unread?<Pressable disabled={markAll.isPending} accessibilityRole="button" accessibilityLabel="Mark all notifications as read" onPress={()=>markAll.mutate()} style={[s.markAll,{borderColor:palette.primary}]}><Ionicons name="checkmark-done-outline" size={20} color={palette.primary}/><Text style={{color:palette.primary,fontWeight:'900'}}>Mark all as read</Text></Pressable>:null}{q.isLoading?<Muted>Loading notifications…</Muted>:groups.length?groups.map(([key,items])=>{const stacked=items.length>1,isOpen=!!expanded[key],latest=items[0],groupRead=items.every(item=>!!item.ReadAt);const pressGroup=()=>{mark.mutate(items.map(item=>item.Id));if(stacked)setExpanded(x=>({...x,[key]:!x[key]}));else open(latest)};return <View key={key} style={[s.group,groupRead&&s.read]}>{stacked&&!isOpen?<View style={[s.stackBack,s.stackBackTwo,{backgroundColor:palette.surface,borderColor:palette.border}]}/>:null}{stacked&&!isOpen?<View style={[s.stackBack,s.stackBackOne,{backgroundColor:palette.surface,borderColor:palette.border}]}/>:null}<Pressable accessibilityRole="button" accessibilityState={{expanded:isOpen}} onPress={pressGroup}><NotificationCard item={latest} count={stacked?items.length:0} expanded={isOpen}/></Pressable>{stacked&&isOpen?<View style={[s.children,{borderLeftColor:palette.primary}]}>{items.slice(1).map(item=><Pressable key={item.Id} onPress={()=>{mark.mutate([item.Id]);open(item)}}><NotificationCard item={item}/></Pressable>)}</View>:null}</View>}):<EmptyState icon="notifications-off-outline" title="You're up to date" body="New messages and community activity will appear here."/>}</Screen>;
}

function NotificationCard({item,count=0,expanded=false}:{item:Notification;count?:number;expanded?:boolean}){const{palette}=useAppTheme(),read=!!item.ReadAt,unavailable=item.Body==='This content is no longer available.';return <Card style={s.item}><View style={[s.icon,{backgroundColor:item.NotificationType==='EMERGENCY'?palette.dangerSoft:palette.primarySoft}]}><Ionicons name={unavailable?'alert-circle-outline':item.NotificationType==='EMERGENCY'?'warning':item.NotificationType==='EVENT'?'calendar':item.NotificationType==='CHAT_MESSAGE'?'chatbubble-outline':read?'notifications-outline':'notifications'} size={21} color={item.NotificationType==='EMERGENCY'?palette.danger:palette.primary}/></View><View style={{flex:1}}><View style={s.titleRow}><Text style={[s.title,{color:palette.text}]} numberOfLines={1}>{item.Title}</Text>{count?<View style={[s.count,{backgroundColor:palette.primary}]}><Text style={s.countText}>{count}</Text></View>:null}</View><Muted>{item.CommunityName} · {new Date(item.CreatedAt).toLocaleString()}</Muted><Muted numberOfLines={2}>{item.Body}</Muted></View>{read?<Ionicons name="checkmark-done" size={19} color={palette.primary}/>:<Ionicons name={count?(expanded?'chevron-up':'chevron-down'):'chevron-forward'} size={19} color={palette.muted}/>}</Card>}

const s=StyleSheet.create({page:{paddingTop:16,paddingBottom:28},markAll:{alignSelf:'flex-end',minHeight:42,borderWidth:1,borderRadius:11,paddingHorizontal:13,marginBottom:14,flexDirection:'row',alignItems:'center',gap:7},group:{position:'relative',marginBottom:12},read:{opacity:.68},stackBack:{position:'absolute',left:12,right:12,height:30,borderWidth:1,borderRadius:14},stackBackOne:{bottom:-5},stackBackTwo:{bottom:-10,left:22,right:22},children:{marginTop:8,marginLeft:18,paddingLeft:10,borderLeftWidth:2,gap:8},item:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:0},icon:{width:44,height:44,borderRadius:13,alignItems:'center',justifyContent:'center'},titleRow:{flexDirection:'row',alignItems:'center',gap:7},title:{fontWeight:'900',marginBottom:3,flexShrink:1},count:{minWidth:22,height:22,borderRadius:11,paddingHorizontal:6,alignItems:'center',justifyContent:'center'},countText:{color:'#fff',fontSize:11,fontWeight:'900'}});
