import {useEffect,useState} from 'react';
import {Alert,Platform,Pressable,StyleSheet,Switch,Text,View,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Button,Card,Input,Muted,Screen,useAppTheme} from '@/components/UI';
import {TimeField} from '@/components/TimeField';
import {api} from '@/lib/api';
import {secureGet,secureSet} from '@/lib/storage';

type OnOff='ON'|'OFF';type PostMode=OnOff|'DAILY';
type Preferences={directMessages:OnOff;mentions:OnOff;communityPosts:PostMode;polls:OnOff;events:OnOff;marketplace:OnOff;businessPromotions:OnOff;quietHoursEnabled:boolean;quietStart:string;quietEnd:string};
type Channels={inApp:boolean;email:boolean;sms:boolean;push:boolean};
type Category='Community Updates'|'Events & Reminders'|'Messages'|'Mentions'|'Polls & Surveys'|'Marketplace & Opportunities'|'System & Updates'|'Alerts & Emergency';
const initial:Preferences={directMessages:'ON',mentions:'ON',communityPosts:'DAILY',polls:'ON',events:'ON',marketplace:'OFF',businessPromotions:'OFF',quietHoursEnabled:false,quietStart:'22:00',quietEnd:'07:00'};
const categories:[Category,keyof Preferences,string,keyof typeof Ionicons.glyphMap][]=[['Community Updates','communityPosts','Posts, announcements and community updates','megaphone-outline'],['Events & Reminders','events','Event reminders and RSVP updates','calendar-outline'],['Messages','directMessages','New messages and chat activity','chatbubble-outline'],['Mentions','mentions','When someone mentions you','at-outline'],['Polls & Surveys','polls','New polls and voting reminders','stats-chart-outline'],['Marketplace & Opportunities','marketplace','Listings and local opportunities','briefcase-outline'],['System & Updates','businessPromotions','CDA Connect news and service updates','settings-outline'],['Alerts & Emergency','directMessages','Important safety alerts are always enabled','warning-outline']];
const settingsMenu=[['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;
const top=StyleSheet.create({brandBar:{minHeight:68,flexDirection:'row',alignItems:'center',gap:8},topBack:{width:44,height:44,borderWidth:1,borderRadius:22,alignItems:'center',justifyContent:'center'},logo:{width:48,height:48,resizeMode:'contain'},brandName:{fontSize:17,fontWeight:'900'},tagline:{fontSize:9},topAction:{width:44,height:44,alignItems:'center',justifyContent:'center'}});

export default function NotificationSettings(){
 const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;
 const[p,setP]=useState<Preferences>(initial);const[channels,setChannels]=useState<Channels>({inApp:true,email:true,sms:false,push:true});const[detail,setDetail]=useState<Category|null>(null);const[saving,setSaving]=useState(false);
 useEffect(()=>{api.get('/me/preferences').then(r=>{const n=r.data?.notifications;if(!n)return;setP({directMessages:n.DirectMessages??n.directMessages??initial.directMessages,mentions:n.Mentions??n.mentions??initial.mentions,communityPosts:n.CommunityPosts??n.communityPosts??initial.communityPosts,polls:n.Polls??n.polls??initial.polls,events:n.Events??n.events??initial.events,marketplace:n.Marketplace??n.marketplace??initial.marketplace,businessPromotions:n.BusinessPromotions??n.businessPromotions??initial.businessPromotions,quietHoursEnabled:Boolean(n.QuietHoursEnabled??n.quietHoursEnabled),quietStart:String(n.QuietStart??n.quietStart??'22:00').slice(0,5),quietEnd:String(n.QuietEnd??n.quietEnd??'07:00').slice(0,5)})}).catch(()=>Alert.alert('Notifications','Your saved preferences could not be loaded.'));secureGet('notification-channels').then(v=>v&&setChannels({...channels,...JSON.parse(v)})).catch(()=>{})},[]);
 const toggle=(key:keyof Preferences)=>setP(x=>({...x,[key]:(x[key]==='ON'?'OFF':'ON') as any}));
 const save=async()=>{if(!/^\d\d:\d\d$/.test(p.quietStart)||!/^\d\d:\d\d$/.test(p.quietEnd))return Alert.alert('Check quiet hours','Use 24-hour time, for example 22:00.');setSaving(true);try{await api.put('/me/notification-preferences',{...p,emergencyAlerts:'ALWAYS'});await secureSet('notification-channels',JSON.stringify(channels));Alert.alert('Saved','Your notification preferences have been updated.')}catch(e:any){Alert.alert('Unable to save',e.response?.data?.error||e.message)}finally{setSaving(false)}};
 if(detail)return <CategoryDetail name={detail} p={p} channels={channels} setP={setP} setChannels={setChannels} save={save} saving={saving} back={()=>setDetail(null)}/>;
 return <Screen scroll contentStyle={s.page}><View style={s.heading}><Muted>Choose what you want to be notified about and how.</Muted></View>
  {!desktop?<Card style={[s.hero,{backgroundColor:palette.surface}]}><View style={[s.heroIcon,{backgroundColor:palette.successSoft}]}><Ionicons name="notifications-outline" size={42} color={palette.success}/></View><View style={{flex:1}}><Text style={[s.heroTitle,{color:palette.text}]}>Stay updated, your way</Text><Muted>Manage notification preferences and never miss what matters.</Muted></View><Ionicons name="checkmark-circle" size={30} color={palette.primary}/></Card>:null}
  <View style={[s.layout,!desktop&&s.stack]}>
   {desktop?<Card style={s.menu}><Text style={[s.menuTitle,{color:palette.text}]}>Settings Menu</Text>{settingsMenu.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[s.menuRow,label==='Notifications'&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={label==='Notifications'?palette.success:palette.navy}/><Text style={{fontWeight:'800',color:label==='Notifications'?palette.success:palette.text}}>{label}</Text></Pressable>)}</Card>:null}
   <View style={s.main}>
    {desktop?<Card><Text style={[s.sectionTitle,{color:palette.text}]}>Notification Preferences</Text><Muted>Manage your notification settings and delivery preferences.</Muted><View style={[s.banner,{backgroundColor:palette.successSoft}]}><View><Text style={{fontWeight:'900',color:palette.success}}>Stay informed your way</Text><Muted>Customize each notification category.</Muted></View><Ionicons name="notifications-outline" size={42} color={palette.success}/></View></Card>:null}
    <Text style={[s.groupTitle,{color:palette.text}]}>Notification Status</Text><Card style={s.list}><Channel name="inApp" value={channels.inApp} onChange={v=>setChannels(x=>({...x,inApp:v}))}/></Card>
    <Text style={[s.groupTitle,{color:palette.text}]}>How You Receive Notifications</Text><Card style={[s.channelGrid,!desktop&&s.channelList]}>{(['push','email','sms'] as (keyof Channels)[]).map(key=><Channel key={key} name={key} value={channels[key]} onChange={v=>setChannels(x=>({...x,[key]:v}))}/>)}</Card>
    <View style={s.categoryHead}><View><Text style={[s.groupTitle,{color:palette.text}]}>Notification Categories</Text><Muted>Choose what you want to be notified about.</Muted></View></View>
    <Card style={s.list}>{categories.map(([name,key,help,icon])=><Pressable key={name} onPress={()=>setDetail(name)} style={[s.category,{borderBottomColor:palette.border}]}><View style={[s.categoryIcon,{backgroundColor:name==='Alerts & Emergency'?palette.dangerSoft:palette.successSoft}]}><Ionicons name={icon} size={20} color={name==='Alerts & Emergency'?palette.danger:palette.success}/></View><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{name}</Text><Muted>{help}</Muted></View><Switch value={name==='Alerts & Emergency'||p[key]!=='OFF'} disabled={name==='Alerts & Emergency'} onValueChange={()=>toggle(key)}/><Ionicons name="chevron-forward" size={18} color={palette.muted}/></Pressable>)}</Card>
    {!desktop?<QuietHours p={p} setP={setP}/>:null}<Button title="Save Changes" variant="success" loading={saving} onPress={save}/>
   </View>
   {desktop?<View style={s.right}><QuietHours p={p} setP={setP}/><Card><Text style={[s.sectionTitle,{color:palette.text}]}>Need help?</Text><Muted>Learn more about notifications and how to manage them.</Muted><Button title="View Help Center" variant="secondary" onPress={()=>router.push('/help')}/></Card></View>:null}
  </View>
 </Screen>
}

function CategoryDetail({name,p,channels,setP,setChannels,save,saving,back}:{name:Category;p:Preferences;channels:Channels;setP:(v:any)=>void;setChannels:(v:any)=>void;save:()=>Promise<void>;saving:boolean;back:()=>void}){const{palette}=useAppTheme();const found=categories.find(x=>x[0]===name)!;const key=found[1];const emergency=name==='Alerts & Emergency';const rows=[[found[2],key]] as const;return <Screen scroll contentStyle={s.detail}><Pressable onPress={back} style={s.back}><Ionicons name="chevron-back" size={27} color={palette.text}/><Text style={[s.detailTitle,{color:palette.text}]}>{name}</Text></Pressable><Text style={[s.groupTitle,{color:palette.text}]}>Notification Preferences</Text><Card style={s.list}>{rows.map(([label,k])=><View key={label} style={[s.checkRow,{borderBottomColor:palette.border}]}><Text style={[s.rowTitle,{color:palette.text,flex:1}]}>{label}</Text><Pressable disabled={emergency} onPress={()=>setP((x:Preferences)=>({...x,[k]:x[k]==='OFF'?'ON':'OFF'}))}><Ionicons name={emergency||p[k]!=='OFF'?'checkbox':'square-outline'} size={23} color={emergency||p[k]!=='OFF'?palette.success:palette.muted}/></Pressable></View>)}</Card><Text style={[s.groupTitle,{color:palette.text}]}>How you’ll receive these</Text><Card style={s.list}>{(Object.keys(channels) as (keyof Channels)[]).map(k=><View key={k} style={[s.checkRow,{borderBottomColor:palette.border}]}><Text style={[s.rowTitle,{color:palette.text,flex:1}]}>{channelLabel(k)}</Text><Pressable onPress={()=>setChannels((x:Channels)=>({...x,[k]:!x[k]}))}><Ionicons name={channels[k]?'checkbox':'square-outline'} size={23} color={channels[k]?palette.success:palette.muted}/></Pressable></View>)}</Card><Button title="Save Changes" variant="success" loading={saving} onPress={save}/></Screen>}
function Channel({name,value,onChange}:{name:keyof Channels;value:boolean;onChange:(v:boolean)=>void}){const{palette}=useAppTheme();const icon:Record<keyof Channels,keyof typeof Ionicons.glyphMap>={inApp:'notifications-outline',email:'mail-outline',sms:'chatbox-outline',push:'phone-portrait-outline'};return <View style={[s.channel,{borderColor:palette.border}]}><View style={[s.categoryIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon[name]} size={21} color={palette.success}/></View><View style={{flex:1}}><Text style={[s.rowTitle,{color:palette.text}]}>{channelLabel(name)}</Text><Muted>Receive {name==='sms'?'text messages':name==='email'?'email notifications':name==='push'?'push notifications':'in-app notifications'}</Muted></View><Switch value={value} onValueChange={onChange} trackColor={{false:palette.border,true:palette.success}}/></View>}
function channelLabel(k:keyof Channels){return k==='inApp'?'In-App Notifications':k==='email'?'Email':k==='sms'?'SMS':'Push Notifications'}
function QuietHours({p,setP}:{p:Preferences;setP:(v:any)=>void}){const{palette}=useAppTheme();return <Card><View style={s.quietHead}><Ionicons name="moon-outline" size={22} color={palette.navy}/><View style={{flex:1}}><Text style={[s.sectionTitle,{color:palette.text}]}>Quiet Hours</Text><Muted>Pause non-urgent notifications during this time.</Muted></View><Switch value={p.quietHoursEnabled} onValueChange={v=>setP((x:Preferences)=>({...x,quietHoursEnabled:v}))}/></View>{p.quietHoursEnabled?<View style={s.times}><View style={{flex:1}}><Muted>From</Muted><TimeField value={p.quietStart} onChange={v=>setP((x:Preferences)=>({...x,quietStart:v}))}/></View><View style={{flex:1}}><Muted>To</Muted><TimeField value={p.quietEnd} onChange={v=>setP((x:Preferences)=>({...x,quietEnd:v}))}/></View></View>:null}</Card>}

const s=StyleSheet.create({page:{width:'100%',maxWidth:1380,alignSelf:'center'},heading:{marginBottom:22},title:{fontSize:29,fontWeight:'900',marginBottom:5},layout:{flexDirection:'row',alignItems:'flex-start',gap:16},stack:{flexDirection:'column'},menu:{width:245,padding:12},menuTitle:{fontWeight:'900',margin:8},menuRow:{minHeight:48,borderRadius:10,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:11},main:{flex:1,width:'100%',minWidth:0},right:{width:245},sectionTitle:{fontSize:19,fontWeight:'900',marginBottom:4},banner:{marginTop:16,borderRadius:13,padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},groupTitle:{fontSize:18,fontWeight:'900',marginTop:8,marginBottom:8},channelGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},channelList:{flexDirection:'column',padding:0,overflow:'hidden'},channel:{flexGrow:1,flexBasis:'46%',minHeight:88,borderWidth:1,borderRadius:12,padding:12,flexDirection:'row',alignItems:'center',gap:10},categoryHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},list:{padding:0,overflow:'hidden'},category:{minHeight:68,borderBottomWidth:1,paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:10},categoryIcon:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'},rowTitle:{fontWeight:'900',marginBottom:2},quietHead:{flexDirection:'row',alignItems:'center',gap:10},times:{flexDirection:'row',gap:10,marginTop:14},hero:{alignItems:'center',paddingVertical:8,marginBottom:12},heroIcon:{width:90,height:90,borderRadius:45,alignItems:'center',justifyContent:'center'},heroTitle:{fontSize:19,fontWeight:'900',marginTop:12,marginBottom:5},detail:{width:'100%',maxWidth:720,alignSelf:'center'},back:{minHeight:52,flexDirection:'row',alignItems:'center',gap:9},detailTitle:{fontSize:23,fontWeight:'900'},checkRow:{minHeight:62,borderBottomWidth:1,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:12}});
