import {PolicyPage,PolicySection} from '@/components/PolicyPage';
const sections:PolicySection[]=[
 {heading:'The Future We Want to Support',paragraphs:['We envision communities where members can obtain reliable updates, contribute ideas, organise activities and understand how local decisions are made.','Technology should strengthen real relationships and accountable leadership rather than replace lawful institutions or community processes.']},
 {heading:'Responsible Digital Growth',paragraphs:['Growth should be accompanied by privacy-by-design, security safeguards, accessible interfaces and clear user controls.','New features should be assessed against the Nigeria Data Protection Act 2023, GAID 2025, consumer-protection duties and relevant sector guidance before broad deployment.']},
 {heading:'Transparent Community Governance',paragraphs:['Role permissions, voting tools, attendance and financial records should support traceability, fairness and appropriate oversight.','CDA Connect does not certify the legal validity of a community election, levy or decision; communities remain responsible for their constitutions and applicable law.']},
 {heading:'Safe Innovation',paragraphs:['Automation and future intelligent features should not make significant decisions about a person without an appropriate lawful basis, transparency and human safeguards.','We aim to minimise unnecessary data, limit access and evaluate foreseeable misuse before introducing sensitive capabilities.']},
 {heading:'National and Community Development',paragraphs:['We support Nigeria’s wider goals of safe digital participation, consumer confidence, data protection and inclusive access.','Our vision is measured by practical community benefit, not engagement at the expense of safety, privacy or trust.']},
];
export default function Vision(){return <PolicyPage intro="Our vision is a future in which trusted digital collaboration helps every community become more informed, inclusive and resilient." sections={sections}/>}
