import {PolicyPage,PolicySection} from '@/components/PolicyPage';
const sections:PolicySection[]=[
 {heading:'Connecting Communities Responsibly',paragraphs:['Our mission is to give residents, leaders, organisations and local businesses practical tools for trusted communication, participation and access to resources.','We design features to support—not replace—lawful community constitutions, public authorities, regulated professionals or emergency services.']},
 {heading:'Our Public Commitments',paragraphs:['We aim to provide clear information, fair controls and reasonable support in line with the Federal Competition and Consumer Protection Act 2018.','We respect privacy and data-subject rights under the Nigeria Data Protection Act 2023 and its General Application and Implementation Directive 2025.','We maintain safeguards against cybercrime, fraud, impersonation and unlawful access consistent with Nigeria’s cybercrime framework.']},
 {heading:'Participation and Inclusion',paragraphs:['We seek to make community information and participation available across supported devices, abilities and languages.','Community tools should encourage respectful dialogue, transparent administration and meaningful participation without unlawful discrimination.']},
 {heading:'Safety and Trust',paragraphs:['Our mission includes protecting children and vulnerable users, supporting proportionate moderation and providing reporting routes for unsafe conduct.','We do not promise that every user, listing or statement is accurate; members and administrators must verify important information and act responsibly.']},
 {heading:'Accountability',paragraphs:['Product decisions should consider user safety, privacy, consumer rights, accessibility and foreseeable community impact.','Users may raise concerns through support@cdaconnect.org and retain the right to contact competent Nigerian regulators.']},
];
export default function Mission(){return <PolicyPage intro="CDA Connect exists to strengthen real communities through responsible, inclusive and legally compliant technology." sections={sections}/>}
