import {useEffect,useMemo,useState} from 'react';
import {Alert,Platform,Pressable,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Button,Card,Muted,Screen,ToggleSwitch as Switch,useAppTheme} from '@/components/UI';
import {api} from '@/lib/api';
import {secureGet,secureSet} from '@/lib/storage';

type Access='NOBODY'|'ADMINS'|'MEMBERS';
type PrivacyState={phoneVisibility:Access;emailVisibility:Access;whoCanMessage:Access;whoCanAddToGroups:Access;showOnlineStatus:boolean;showProfilePhoto:boolean;allowCommunityDiscovery:boolean};
type Panel='home'|'profile'|'activity'|'personal'|'location'|'contact'|'tagging'|'blocked'|'report'|'content'|'comments'|'twofactor';
const initial:PrivacyState={phoneVisibility:'ADMINS',emailVisibility:'ADMINS',whoCanMessage:'MEMBERS',whoCanAddToGroups:'ADMINS',showOnlineStatus:true,showProfilePhoto:true,allowCommunityDiscovery:true};
const accessLabel:Record<Access,string>={NOBODY:'Only Me',ADMINS:'Friends & Admins',MEMBERS:'Community Members'};
const menu=[['lock-closed-outline','Privacy & Safety','/privacy'],['notifications-outline','Notifications','/notifications-settings'],['sunny-outline','Appearance','/accessibility'],['language-outline','Language','/language'],['chatbox-outline','Communications','/communications'],['options-outline','Community Preferences','/community-preferences'],['server-outline','Data & Storage','/data-usage'],['shield-checkmark-outline','Security','/security'],['help-circle-outline','Help & Support','/help'],['information-circle-outline','About CDA Connect','/about']] as const;

export default function Privacy(){
 const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;
 const[p,setP]=useState<PrivacyState>(initial);const[expanded,setExpanded]=useState<Panel|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[showLocation,setShowLocation]=useState(false);
 useEffect(()=>{Promise.allSettled([api.get('/me/preferences').then(r=>{if(r.data?.privacy)setP({...initial,...r.data.privacy})}),secureGet('show-community-location').then(v=>setShowLocation(v==='true'))]).then(results=>{if(results[0].status==='rejected')Alert.alert('Privacy settings','Your saved settings could not be loaded.')}).finally(()=>setLoading(false))},[]);
 const profileChoice:Access=useMemo(()=>p.emailVisibility===p.phoneVisibility?p.emailVisibility:'MEMBERS',[p]);
 const save=async(next=p)=>{const previous=p;setP(next);setSaving(true);try{await api.put('/me/privacy-preferences',next)}catch(e:any){setP(previous);Alert.alert('Unable to save',e.response?.data?.error||e.message)}finally{setSaving(false)}};
 const chooseProfile=(value:Access)=>void save({...p,emailVisibility:value,phoneVisibility:value});
 const open=(name:Panel)=>setExpanded(x=>x===name?null:name);
 const toggle=(key:keyof PrivacyState,value:boolean|Access)=>void save({...p,[key]:value});
 const toggleLocation=async(value:boolean)=>{const previous=showLocation;setShowLocation(value);setSaving(true);try{await secureSet('show-community-location',String(value))}catch(e:any){setShowLocation(previous);Alert.alert('Unable to save location preference',e.message||'Please try again.')}finally{setSaving(false)}};
 return <Screen scroll contentStyle={styles.page}>
  <View style={styles.heading}><Muted>Control your privacy, manage safety tools, and choose how you interact on CDA Connect.</Muted></View>
  <View style={[styles.layout,!desktop&&styles.stack]}>
   {desktop?<Card style={styles.menu}><Text style={[styles.menuTitle,{color:palette.text}]}>Settings Menu</Text>{menu.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[styles.menuRow,label==='Privacy & Safety'&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={19} color={label==='Privacy & Safety'?palette.success:palette.navy}/><Text style={{fontWeight:'800',color:label==='Privacy & Safety'?palette.success:palette.text}}>{label}</Text></Pressable>)}</Card>:null}
   <View style={styles.main}>
    {desktop?<Card><Text style={[styles.sectionTitle,{color:palette.text}]}>Privacy &amp; Safety</Text><Muted>Choose who can see your profile and activity.</Muted><View style={styles.choiceGrid}>{(['MEMBERS','ADMINS','NOBODY'] as Access[]).map(v=><Choice key={v} selected={profileChoice===v} icon={v==='MEMBERS'?'people-outline':v==='ADMINS'?'shield-outline':'lock-closed-outline'} title={accessLabel[v]} body={v==='MEMBERS'?'Members of your communities':v==='ADMINS'?'Community administrators':'Only you'} onPress={()=>chooseProfile(v)}/>)}</View></Card>:null}
    <Text style={[styles.groupTitle,{color:palette.text}]}>Profile Privacy</Text>
    <Card style={styles.listCard}>
     {!desktop?<Accordion icon="person-outline" title="Profile Visibility" value={accessLabel[profileChoice]} open={expanded==='profile'} onPress={()=>open('profile')}><Toggle title="Show profile photo" body="Allow permitted members to see your profile picture." value={p.showProfilePhoto} disabled={saving} onChange={v=>toggle('showProfilePhoto',v)}/><Toggle title="Visible to community members" body="Switch off to make your phone and email visible only to you." value={profileChoice!=='NOBODY'} disabled={saving} onChange={v=>void save({...p,emailVisibility:v?'MEMBERS':'NOBODY',phoneVisibility:v?'MEMBERS':'NOBODY'})}/></Accordion>:null}
     <Accordion icon="eye-outline" title="Activity Visibility" value={p.showOnlineStatus?'Community Members':'Only Me'} open={expanded==='activity'} onPress={()=>open('activity')}><Toggle title="Show online status" body="Let permitted members see when you are active." value={p.showOnlineStatus} disabled={saving} onChange={v=>toggle('showOnlineStatus',v)}/></Accordion>
     <Accordion icon="lock-closed-outline" title="Personal Information" value="Manage" open={expanded==='personal'} onPress={()=>open('personal')}><Toggle title="Show phone number" body="Allow community members to see your phone number." value={p.phoneVisibility==='MEMBERS'} disabled={saving} onChange={v=>toggle('phoneVisibility',v?'MEMBERS':'NOBODY')}/><Toggle title="Show email address" body="Allow community members to see your email address." value={p.emailVisibility==='MEMBERS'} disabled={saving} onChange={v=>toggle('emailVisibility',v?'MEMBERS':'NOBODY')}/></Accordion>
     <Accordion icon="location-outline" title="Location" value={showLocation?'LGA & State shown':'Hidden'} open={expanded==='location'} onPress={()=>open('location')}><Toggle title="Show my location" body="Show only your LGA and state while discovering nearby communities." value={showLocation} disabled={saving} onChange={v=>void toggleLocation(v)}/></Accordion>
     <Accordion icon="mail-outline" title="Contact Me" value={accessLabel[p.whoCanMessage]} open={expanded==='contact'} onPress={()=>open('contact')}><Toggle title="Allow member messages" body="Permit members of your communities to contact you." value={p.whoCanMessage==='MEMBERS'} disabled={saving} onChange={v=>toggle('whoCanMessage',v?'MEMBERS':'NOBODY')}/></Accordion>
     <Accordion icon="pricetag-outline" title="Data & Tagging" value="Manage" open={expanded==='tagging'} onPress={()=>open('tagging')}><Toggle title="Allow group invitations" body="Allow community members to add you to groups." value={p.whoCanAddToGroups==='MEMBERS'} disabled={saving} onChange={v=>toggle('whoCanAddToGroups',v?'MEMBERS':'NOBODY')}/></Accordion>
    </Card>
    <Text style={[styles.groupTitle,{color:palette.text}]}>Safety &amp; Protection</Text>
    <Card style={styles.listCard}>
     <ListRow icon="person-remove-outline" title="Blocked Users" value="Manage" tone="red" onPress={()=>router.push('/blocked-users' as any)}/>
     <Accordion icon="shield-outline" title="Content Preferences" value={p.allowCommunityDiscovery?'Discovery on':'Discovery off'} open={expanded==='content'} onPress={()=>open('content')}><Toggle title="Community discovery" body="Use your preferences to recommend relevant communities." value={p.allowCommunityDiscovery} disabled={saving} onChange={v=>toggle('allowCommunityDiscovery',v)}/></Accordion>
     <Accordion icon="chatbubble-ellipses-outline" title="Comment Controls" value={accessLabel[p.whoCanMessage]} open={expanded==='comments'} onPress={()=>open('comments')}><Toggle title="Allow member interactions" body="Allow community members to interact with your posts." value={p.whoCanMessage==='MEMBERS'} disabled={saving} onChange={v=>toggle('whoCanMessage',v?'MEMBERS':'NOBODY')}/></Accordion>
    </Card>
    <Card style={[styles.safetyCard,{backgroundColor:palette.primarySoft,borderColor:palette.primaryLight}]}><Ionicons name="shield-checkmark-outline" size={34} color={palette.primary}/><View style={{flex:1}}><Text style={[styles.safetyTitle,{color:palette.primaryDark}]}>Your safety matters</Text><Muted>Use the report tools whenever content or behaviour violates the community guidelines.</Muted></View><Pressable accessibilityRole="button" onPress={()=>router.push('/about')} style={[styles.guidelines,{borderColor:palette.primary}]}><Text style={{color:palette.primary,fontWeight:'900'}}>Guidelines</Text></Pressable></Card>
    {saving||loading?<Muted style={styles.saving}>{loading?'Loading preferences…':'Saving changes…'}</Muted>:null}
   </View>
   {desktop?<Card style={[styles.info,{backgroundColor:palette.successSoft}]}><Ionicons name="lock-closed-outline" size={27} color={palette.success}/><Text style={[styles.infoTitle,{color:palette.success}]}>Your Privacy Matters</Text><Muted>We are committed to keeping your data safe and giving you full control over your privacy.</Muted><Pressable onPress={()=>router.push('/about')}><Text style={{color:palette.success,fontWeight:'900',marginTop:20}}>Learn more about our Privacy Policy →</Text></Pressable></Card>:null}
  </View>
 </Screen>
}

function Detail({panel,p,setP,save,saving,onBack}:{panel:Panel;p:PrivacyState;setP:(v:any)=>void;save:(v?:PrivacyState)=>Promise<void>;saving:boolean;onBack:()=>void}){
 const{palette}=useAppTheme();const title:Record<Panel,string>={home:'Privacy & Safety',profile:'Profile Visibility',activity:'Activity Visibility',personal:'Personal Information',location:'Location',contact:'Contact Me',tagging:'Data & Tagging',blocked:'Blocked Users',report:'Report & Flag',content:'Content Preferences',comments:'Comment Controls',twofactor:'Two-Factor Authentication'};
 const accessKey=panel==='contact'?'whoCanMessage':panel==='comments'?'whoCanMessage':panel==='tagging'?'whoCanAddToGroups':null;
 const setAccess=(v:Access)=>accessKey?setP((x:PrivacyState)=>({...x,[accessKey]:v})):setP((x:PrivacyState)=>({...x,emailVisibility:v,phoneVisibility:v}));
 const selected:Access=accessKey?p[accessKey]:p.emailVisibility===p.phoneVisibility?p.emailVisibility:'MEMBERS';
 return <Screen scroll contentStyle={styles.detailPage}><Pressable accessibilityLabel="Back" onPress={onBack} style={styles.back}><Ionicons name="chevron-back" size={27} color={palette.text}/><Text style={[styles.detailTitle,{color:palette.text}]}>{title[panel]}</Text></Pressable>
  {panel==='profile'||panel==='contact'||panel==='comments'||panel==='tagging'?<><Card style={[styles.note,{backgroundColor:palette.successSoft}]}><Text style={[styles.noteTitle,{color:palette.success}]}>{panel==='profile'?'Who can see your profile?':panel==='contact'?'Who can contact you?':panel==='comments'?'Who can interact with your posts?':'Who can add you to communities?'}</Text><Muted>Your selection is saved to your CDA Connect account.</Muted></Card><Card style={styles.listCard}>{(['MEMBERS','ADMINS','NOBODY'] as Access[]).map(v=><Radio key={v} title={accessLabel[v]} body={v==='MEMBERS'?'Members of your communities':v==='ADMINS'?'Community administrators':'Only you'} selected={selected===v} onPress={()=>setAccess(v)}/>)}</Card><Button title="Save Changes" loading={saving} variant="success" onPress={()=>save()}/></>:null}
  {panel==='activity'?<><Card><Toggle title="Show online status" body="Let permitted members see when you are active." value={p.showOnlineStatus} onChange={v=>setP((x:PrivacyState)=>({...x,showOnlineStatus:v}))}/><Toggle title="Show profile photo" body="Display your profile image to permitted members." value={p.showProfilePhoto} onChange={v=>setP((x:PrivacyState)=>({...x,showProfilePhoto:v}))}/></Card><Button title="Save Changes" loading={saving} variant="success" onPress={()=>save()}/></>:null}
  {panel==='personal'?<><Card><Text style={[styles.sectionTitle,{color:palette.text}]}>Personal information visibility</Text><Muted>Set phone and email visibility separately.</Muted><AccessRow label="Phone number" value={p.phoneVisibility} onChange={v=>setP((x:PrivacyState)=>({...x,phoneVisibility:v}))}/><AccessRow label="Email address" value={p.emailVisibility} onChange={v=>setP((x:PrivacyState)=>({...x,emailVisibility:v}))}/></Card><Button title="Save Changes" loading={saving} variant="success" onPress={()=>save()}/><Button title="Edit profile information" variant="secondary" onPress={()=>router.push('/profile-edit')}/></>:null}
  {panel==='content'?<><Card><Toggle title="Allow community discovery" body="Use your saved preferences to recommend relevant communities." value={p.allowCommunityDiscovery} onChange={v=>setP((x:PrivacyState)=>({...x,allowCommunityDiscovery:v}))}/></Card><Button title="Save Changes" loading={saving} variant="success" onPress={()=>save()}/></>:null}
  {panel==='blocked'?<Card><Text style={[styles.sectionTitle,{color:palette.text}]}>Blocked users</Text><Muted>Users you block cannot contact you. Open a member’s profile and choose Block to add them here.</Muted><Button title="Go to Communities" variant="secondary" onPress={()=>router.push('/(tabs)/communities')}/></Card>:null}
  {panel==='report'?<Card><Text style={[styles.sectionTitle,{color:palette.text}]}>Report unsafe content</Text><Muted>Open the community, post, or member concerned and use its report menu. For immediate danger, use Emergency.</Muted><Button title="Open Communities" variant="success" onPress={()=>router.push('/(tabs)/communities')}/><Button title="Contact Support" variant="secondary" onPress={()=>router.push('/help')}/></Card>:null}
  {panel==='twofactor'?<Card><Text style={[styles.sectionTitle,{color:palette.text}]}>Protect your account</Text><Muted>Two-factor authentication setup is not yet enabled by this server. You can still strengthen your account by changing your password and reviewing privacy settings.</Muted><Button title="Get Security Help" variant="secondary" onPress={()=>router.push('/help')}/></Card>:null}
 </Screen>
}

function ListRow({icon,title,value,onPress,tone}:{icon:keyof typeof Ionicons.glyphMap;title:string;value:string;onPress:()=>void;tone?:string}){const{palette}=useAppTheme();const fg=tone==='red'?palette.danger:tone==='purple'?palette.purple:palette.success;return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.listRow,{borderBottomColor:palette.border}]}><View style={[styles.rowIcon,{backgroundColor:tone==='red'?palette.dangerSoft:palette.successSoft}]}><Ionicons name={icon} size={21} color={fg}/></View><View style={{flex:1}}><Text style={[styles.rowTitle,{color:palette.text}]}>{title}</Text><Muted>{value}</Muted></View><Ionicons name="chevron-forward" size={20} color={palette.muted}/></Pressable>}
function Choice({selected,icon,title,body,onPress}:{selected:boolean;icon:keyof typeof Ionicons.glyphMap;title:string;body:string;onPress:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={onPress} style={[styles.choice,{borderColor:selected?palette.success:palette.border,backgroundColor:selected?palette.successSoft:palette.surface}]}><Ionicons name={icon} size={24} color={selected?palette.success:palette.navy}/><Text style={[styles.choiceTitle,{color:selected?palette.success:palette.text}]}>{title}</Text><Muted>{body}</Muted></Pressable>}
function Radio({title,body,selected,onPress}:{title:string;body:string;selected:boolean;onPress:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={onPress} style={[styles.radio,{borderBottomColor:palette.border}]}><View style={{flex:1}}><Text style={[styles.rowTitle,{color:selected?palette.success:palette.text}]}>{title}</Text><Muted>{body}</Muted></View><Ionicons name={selected?'radio-button-on':'radio-button-off'} size={23} color={selected?palette.success:palette.muted}/></Pressable>}
function Accordion({icon,title,value,open,onPress,children}:{icon:keyof typeof Ionicons.glyphMap;title:string;value:string;open:boolean;onPress:()=>void;children:any}){const{palette}=useAppTheme();return <View style={{borderBottomColor:palette.border,borderBottomWidth:1}}><Pressable accessibilityRole="button" accessibilityState={{expanded:open}} onPress={onPress} style={styles.listRow}><View style={[styles.rowIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={21} color={palette.success}/></View><View style={{flex:1}}><Text style={[styles.rowTitle,{color:palette.text}]}>{title}</Text><Muted>{value}</Muted></View><Ionicons name={open?'chevron-up':'chevron-down'} size={20} color={palette.muted}/></Pressable>{open?<View style={[styles.dropdown,{borderTopColor:palette.border,backgroundColor:palette.background}]}>{children}</View>:null}</View>}
function Toggle({title,body,value,onChange,disabled=false}:{title:string;body:string;value:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){const{palette}=useAppTheme();return <View style={[styles.toggle,{borderBottomColor:palette.border,opacity:disabled?.65:1}]}><View style={{flex:1}}><Text style={[styles.rowTitle,{color:palette.text}]}>{title}</Text><Muted>{body}</Muted></View><Switch disabled={disabled} value={value} onValueChange={onChange} trackColor={{false:palette.border,true:palette.success}}/></View>}
function AccessRow({label,value,onChange}:{label:string;value:Access;onChange:(v:Access)=>void}){const{palette}=useAppTheme();const values:Access[]=['MEMBERS','ADMINS','NOBODY'];return <Pressable onPress={()=>onChange(values[(values.indexOf(value)+1)%values.length])} style={[styles.toggle,{borderBottomColor:palette.border}]}><Text style={[styles.rowTitle,{color:palette.text,flex:1}]}>{label}</Text><Text style={{color:palette.success,fontWeight:'900'}}>{accessLabel[value]} ▾</Text></Pressable>}

const styles=StyleSheet.create({page:{width:'100%',maxWidth:1320,alignSelf:'center',paddingBottom:18},brandBar:{minHeight:82,flexDirection:'row',alignItems:'center',gap:10},topBack:{width:48,height:48,borderWidth:1,borderRadius:24,alignItems:'center',justifyContent:'center'},logo:{width:58,height:58,resizeMode:'contain'},brandName:{fontSize:18,fontWeight:'900'},tagline:{fontSize:9},topAction:{width:44,height:44,alignItems:'center',justifyContent:'center'},heading:{marginBottom:12},title:{fontSize:29,fontWeight:'900',marginBottom:5},layout:{flexDirection:'row',alignItems:'flex-start',gap:16},stack:{flexDirection:'column'},menu:{width:250,padding:12},menuTitle:{fontWeight:'900',margin:8},menuRow:{minHeight:48,borderRadius:10,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:12},main:{flex:1,width:'100%',minWidth:0},info:{width:245,padding:22},infoTitle:{fontSize:17,fontWeight:'900',marginVertical:14},sectionTitle:{fontSize:20,fontWeight:'900',marginBottom:5},choiceGrid:{flexDirection:'row',gap:12,marginTop:18},choice:{flex:1,minHeight:130,borderWidth:1.5,borderRadius:14,padding:15,gap:8},choiceTitle:{fontWeight:'900'},listCard:{padding:0,overflow:'hidden',marginBottom:4},listRow:{minHeight:72,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:12},rowIcon:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center'},rowTitle:{fontWeight:'900',marginBottom:3},groupTitle:{fontSize:17,fontWeight:'900',marginTop:18,marginBottom:10},safetyCard:{flexDirection:'row',alignItems:'center',gap:12,marginTop:16},safetyTitle:{fontWeight:'900',marginBottom:3},guidelines:{minHeight:42,paddingHorizontal:13,borderWidth:1,borderRadius:9,alignItems:'center',justifyContent:'center'},mobileHero:{alignItems:'center',paddingVertical:10,marginBottom:12},heroIcon:{width:88,height:88,borderRadius:44,alignItems:'center',justifyContent:'center'},heroTitle:{fontSize:19,fontWeight:'900',marginTop:12,marginBottom:5},detailPage:{width:'100%',maxWidth:760,alignSelf:'center',paddingBottom:18},back:{minHeight:52,flexDirection:'row',alignItems:'center',gap:8,marginBottom:12},detailTitle:{fontSize:24,fontWeight:'900'},note:{padding:20},noteTitle:{fontSize:17,fontWeight:'900',marginBottom:6},radio:{minHeight:78,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:16,borderBottomWidth:1},toggle:{minHeight:78,flexDirection:'row',alignItems:'center',gap:14,borderBottomWidth:1,paddingVertical:10},dropdown:{paddingHorizontal:15,paddingBottom:8,borderTopWidth:1},inlineActions:{paddingVertical:12,gap:8},saving:{textAlign:'center',marginTop:12}});
