import {useMemo,useState} from 'react';
import {Alert,FlatList,Platform,Pressable,StyleSheet,Text,TextInput,View,useWindowDimensions} from '@/platform/react-native';
import {SafeAreaView} from '@/platform/safe-area';
import {router} from '@/router';
import {Ionicons} from '@/platform/icons';
import * as ImagePicker from '@/platform/image-picker';
import {City,Country,State,type ICountry,type IState} from 'country-state-city';
import {getLGAsByState,getStateByName} from '@some19ice/nigeria-geo-core';
import {api} from '@/lib/api';
import {useAuth} from '@/store/auth';
import {Avatar,Button,Card,Input,Modal,Muted,Screen,useAppTheme} from '@/components/UI';
import {DateField as AppDateField} from '@/components/DateField';
import {CountryPhoneField} from '@/components/CountryPhoneField';
import {countryUsesPostcode} from '@/lib/postalCodes';
type Option={label:string;value:string};
function usableMediaUrl(url:string){try{const apiBase=new URL(import.meta.env.EXPO_PUBLIC_API_URL||window.location.origin);const media=new URL(url);if(['localhost','127.0.0.1'].includes(media.hostname)){media.protocol=apiBase.protocol;media.hostname=apiBase.hostname;media.port=apiBase.port==='80'||apiBase.port==='443'?'':apiBase.port}return media.toString()}catch{return url}}

export default function ProfileEdit(){
 const{user,accessToken,refreshToken,setSession}=useAuth(),{palette}=useAppTheme(),{width}=useWindowDimensions(),desktop=Platform.OS==='web'&&width>=800;
 const countries=useMemo(()=>Country.getAllCountries(),[]),initialCountry=useMemo(()=>countries.find(x=>x.name===user?.Country)||countries.find(x=>x.isoCode==='NG')!,[countries,user?.Country]);
 const[first,setFirst]=useState(user?.FirstName||''),[last,setLast]=useState(user?.LastName||''),[phone,setPhone]=useState(user?.Phone||''),[profile,setProfile]=useState(user?.ProfileImage||''),[country,setCountry]=useState<ICountry>(initialCountry),[state,setState]=useState<IState|null>(()=>State.getStatesOfCountry(initialCountry.isoCode).find(x=>x.name===user?.State)||null),[lga,setLga]=useState(user?.LGA||''),[postcode,setPostcode]=useState(user?.Postcode||''),[address,setAddress]=useState(user?.Address||''),[dob,setDob]=useState(user?.DateOfBirth?.slice(0,10)||''),[loading,setLoading]=useState(false),[uploading,setUploading]=useState(false);
 const states=useMemo(()=>State.getStatesOfCountry(country.isoCode),[country]),areas=useMemo(()=>{if(!state)return[] as Option[];if(country.isoCode==='NG'){const n=getStateByName(state.name);return n?getLGAsByState(n.id).map(x=>({label:x.name,value:x.name})):[]}return City.getCitiesOfState(country.isoCode,state.isoCode).map(x=>({label:x.name,value:x.name}))},[country,state]);
 const name=`${first} ${last}`.trim()||'Community Member',cancel=()=>router.canGoBack()?router.back():router.replace('/(tabs)/profile');
 async function upload(){try{if(Platform.OS!=='web'){const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return Alert.alert('Photo access required','Allow photo-library access to select an image.')}const pick=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.8});if(pick.canceled)return;setUploading(true);const asset=pick.assets[0];if(asset.fileSize&&asset.fileSize>5*1024*1024)throw new Error('Choose an image no larger than 5MB.');const fd=new FormData(),fileName=asset.fileName||`profile-${Date.now()}.jpg`,mime=asset.mimeType||'image/jpeg';if(Platform.OS==='web'){const blob=await(await fetch(asset.uri)).blob();if(blob.size>5*1024*1024)throw new Error('Choose an image no larger than 5MB.');fd.append('file',blob,fileName)}else fd.append('file',{uri:asset.uri,name:fileName,type:mime} as any);const result=await api.post('/media/upload',fd);const url=usableMediaUrl(result.data.url);setProfile(url);await api.patch('/users/me',{profileImage:url});const updated=(await api.get('/users/me')).data;if(accessToken&&refreshToken)await setSession(updated,accessToken,refreshToken);Alert.alert('Photo uploaded','Your profile photo has been saved.')}catch(e:any){Alert.alert('Upload failed',e.response?.data?.error||e.response?.data?.message||e.message)}finally{setUploading(false)}}
 async function save(){try{setLoading(true);await api.patch('/users/me',{firstName:first.trim(),lastName:last.trim(),phone:phone.trim()||null,profileImage:profile||null,country:country.name,state:state?.name||null,lga:lga||null,postcode:countryUsesPostcode(country.isoCode)?postcode.trim():'',address:address.trim()||null,dateOfBirth:dob||null});const updated=(await api.get('/users/me')).data;if(accessToken&&refreshToken)await setSession(updated,accessToken,refreshToken);Alert.alert('Profile updated','Your profile information and photo have been saved.');router.replace('/(tabs)/profile')}catch(e:any){Alert.alert('Unable to update profile',e.response?.data?.error||e.message)}finally{setLoading(false)}}
 return <Screen scroll contentStyle={s.page}><Muted style={s.subtitle}>Update your information and preferences</Muted>
  <Card style={s.photos}><View style={s.profilePhoto}><Text style={[s.photoTitle,{color:palette.text}]}>Profile Photo</Text><View><Avatar name={name} uri={profile||undefined} size={120}/><Pressable onPress={upload} style={[s.camera,{backgroundColor:palette.surface}]}><Ionicons name="camera-outline" size={22} color={palette.primary}/></Pressable></View><Muted>{uploading?'Uploading…':'JPG, PNG or GIF · Max 5MB'}</Muted></View></Card>
  <Card><Section icon="person-outline" title="Personal Information" palette={palette}/><View style={[s.two,!desktop&&s.stack]}><Field label="First Name"><Input value={first} onChangeText={setFirst}/></Field><Field label="Last Name"><Input value={last} onChangeText={setLast}/></Field></View><View style={[s.two,!desktop&&s.stack]}><Field label="Email Address"><Locked value={user?.Email||''} palette={palette}/></Field><Field label="Date of Birth"><DateSelect value={dob} change={setDob} palette={palette}/></Field></View><Field label="Phone Number"><CountryPhoneField value={phone} onChange={setPhone} defaultCountry={country.isoCode}/></Field></Card>
  <Card><Section icon="location-outline" title="Location" palette={palette}/><View style={[s.two,!desktop&&s.stack]}><Field label="Country"><Select value={country.name} options={countries.map(x=>({label:`${x.flag} ${x.name}`,value:x.isoCode}))} choose={o=>{setCountry(countries.find(x=>x.isoCode===o.value)!);setState(null);setLga('');setPostcode('')}} palette={palette}/></Field><Field label="State"><Select value={state?.name||''} options={states.map(x=>({label:x.name,value:x.isoCode}))} choose={o=>{setState(states.find(x=>x.isoCode===o.value)!);setLga('')}} palette={palette}/></Field></View><View style={[s.two,!desktop&&s.stack]}><Field label="LGA / City"><Select value={lga} options={areas} disabled={!state} choose={o=>setLga(o.label)} palette={palette}/></Field>{countryUsesPostcode(country.isoCode)?<Field label="Postcode"><Input value={postcode} onChangeText={setPostcode}/></Field>:null}</View><Field label="Address"><Input value={address} onChangeText={setAddress} placeholder="Street, estate or community"/></Field></Card>
  <View style={s.actionRow}><View style={s.actionButton}><Button title="Save Changes" loading={loading} disabled={uploading||first.trim().length<2||last.trim().length<2} onPress={save}/></View><View style={s.actionButton}><Button title="Cancel" variant="secondary" onPress={cancel}/></View></View>
 </Screen>}

function Select({value,options,choose,palette,disabled}:{value:string;options:Option[];choose:(o:Option)=>void;palette:any;disabled?:boolean}){const[open,setOpen]=useState(false),[search,setSearch]=useState('');const shown=options.filter(x=>x.label.toLowerCase().includes(search.toLowerCase()));return <><Pressable disabled={disabled} onPress={()=>setOpen(true)} style={[s.select,{borderColor:palette.border,opacity:disabled?.45:1}]}><Text style={{color:value?palette.text:palette.muted}} numberOfLines={1}>{value||'Select from list'}</Text><Ionicons name="chevron-down" size={19} color={palette.text}/></Pressable><Modal visible={open} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setOpen(false)}><SafeAreaView style={[s.modal,{backgroundColor:palette.background}]}><View style={s.modalHead}><Text style={[s.modalTitle,{color:palette.text}]}>Select an option</Text><Pressable onPress={()=>setOpen(false)}><Ionicons name="close" size={28} color={palette.text}/></Pressable></View><TextInput value={search} onChangeText={setSearch} placeholder="Search" placeholderTextColor={palette.muted} style={[s.modalSearch,{borderColor:palette.border,color:palette.text}]}/><FlatList data={shown} keyExtractor={x=>x.value} keyboardShouldPersistTaps="handled" renderItem={({item})=><Pressable onPress={()=>{choose(item);setOpen(false);setSearch('')}} style={[s.option,{borderBottomColor:palette.border}]}><Text style={{color:palette.text,fontSize:16}}>{item.label}</Text>{item.label===value?<Ionicons name="checkmark" size={21} color={palette.primary}/>:null}</Pressable>}/></SafeAreaView></Modal></>}
function DateSelect({value,change}:{value:string;change:(x:string)=>void;palette:any}){
 return <AppDateField value={value} onChange={change} maximumDate={new Date()}/>;
 /* Legacy calendar retained below temporarily for source compatibility.
 const initial=value?new Date(`${value}T00:00:00`):new Date(new Date().getFullYear()-18,0,1),[open,setOpen]=useState(false),[month,setMonth]=useState(new Date(initial.getFullYear(),initial.getMonth(),1)),[selecting,setSelecting]=useState<'month'|'year'|null>(null);
 const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),offset=month.getDay(),cells=[...Array(offset).fill(null),...Array.from({length:days},(_,i)=>i+1)],years=Array.from({length:121},(_,i)=>new Date().getFullYear()-i),months=Array.from({length:12},(_,i)=>new Date(2000,i,1).toLocaleDateString(undefined,{month:'long'}));
 function pick(day:number){const d=new Date(month.getFullYear(),month.getMonth(),day);if(d>new Date())return;const p=(n:number)=>String(n).padStart(2,'0');change(`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`);setOpen(false)}
 // @ts-ignore React Native accepts the mixed year/month list and supplemental style keys below.
 return <><Pressable onPress={()=>setOpen(true)} style={[s.select,{borderColor:palette.border}]}><Text>{value}</Text></Pressable></>; */
}
function Field({label,children}:{label:string;children:any}){const{palette}=useAppTheme();return <View style={{flex:1}}><Text style={[s.label,{color:palette.text}]}>{label}</Text>{children}</View>}
function Locked({value,palette}:{value:string;palette:any}){return <View style={[s.select,{borderColor:palette.border}]}><Text style={{color:palette.muted}}>{value}</Text><Ionicons name="lock-closed" size={16} color={palette.muted}/></View>}
function Section({icon,title,palette}:{icon:any;title:string;palette:any}){return <View style={s.section}><Ionicons name={icon} size={21} color={palette.primary}/><Text style={[s.sectionTitle,{color:palette.text}]}>{title}</Text></View>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:980,alignSelf:'center',paddingBottom:28},brandRow:{minHeight:74,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{flexDirection:'row',alignItems:'center',gap:8},logo:{width:52,height:52,resizeMode:'contain'},brandName:{fontSize:18,fontWeight:'900'},tagline:{fontSize:9},subtitle:{marginVertical:15},photos:{alignItems:'stretch'},stack:{flexDirection:'column'},profilePhoto:{alignItems:'center',gap:9},photoTitle:{fontSize:15,fontWeight:'900'},camera:{position:'absolute',right:-5,bottom:2,width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center',elevation:3},section:{flexDirection:'row',alignItems:'center',gap:9,marginBottom:18},sectionTitle:{fontSize:18,fontWeight:'900'},two:{flexDirection:'row',gap:14},actionRow:{flexDirection:'row',gap:10,alignItems:'stretch'},actionButton:{flex:1,minWidth:0},label:{fontSize:13,fontWeight:'800',marginBottom:7},select:{minHeight:50,borderWidth:1,borderRadius:12,paddingHorizontal:14,marginBottom:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},modal:{flex:1,padding:18},modalHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:15},modalTitle:{fontSize:22,fontWeight:'900'},modalSearch:{minHeight:50,borderWidth:1,borderRadius:12,paddingHorizontal:14,marginBottom:10},option:{minHeight:54,borderBottomWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},backdrop:{flex:1,backgroundColor:'rgba(15,31,68,.4)',alignItems:'center',justifyContent:'center',padding:20},calendar:{width:'100%',maxWidth:390,borderRadius:17,padding:18},calendarHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:15},calendarTitle:{fontSize:17,fontWeight:'900'},grid:{flexDirection:'row',flexWrap:'wrap'},cell:{width:'14.285%',height:40,alignItems:'center',justifyContent:'center'}});
Object.assign(s,{dateList:{maxHeight:360},dateOption:{minHeight:48,borderBottomWidth:1,alignItems:'center',justifyContent:'center'},monthYear:{flexDirection:'row',gap:8},dateMenu:{minHeight:40,borderWidth:1,borderRadius:9,paddingHorizontal:10,flexDirection:'row',alignItems:'center',gap:5}});
