import {useCallback,useEffect,useState} from 'react';
import {Alert,Pressable,StyleSheet,Switch,Text,TextInput,View} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {Button,Card,Muted,Screen,useAppTheme} from '@/components/UI';
import {api} from '@/lib/api';
import {useAuth} from '@/store/auth';

type Method='authenticator'|'sms';type Status={enabled:boolean;method:Method|null;phone?:string;phoneVerified:boolean};
export default function TwoFactor(){const{palette}=useAppTheme(),refreshToken=useAuth(x=>x.refreshToken);const[status,setStatus]=useState<Status|null>(null),[method,setMethod]=useState<Method>('authenticator'),[password,setPassword]=useState(''),[code,setCode]=useState(''),[secret,setSecret]=useState(''),[challengeId,setChallengeId]=useState(''),[stage,setStage]=useState<'idle'|'verify'>('idle'),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{setStatus((await api.get('/auth/two-factor')).data)}catch(e:any){Alert.alert('Unable to load two-factor settings',e.response?.data?.error||e.message)}},[]);useEffect(()=>{void load()},[load]);
 const begin=async()=>{if(!password)return Alert.alert('Password required','Enter your current password to continue.');try{setBusy(true);const r=await api.post('/auth/two-factor/setup',{method,password});setSecret(r.data.secret||'');setChallengeId(r.data.challengeId||'');setCode('');setStage('verify')}catch(e:any){Alert.alert('Unable to start setup',e.response?.data?.error||e.message)}finally{setBusy(false)}};
 const enable=async()=>{if(!/^\d{6}$/.test(code))return Alert.alert('Enter the verification code','Enter the current six-digit code.');try{setBusy(true);await api.post('/auth/two-factor/enable',{method,password,code,secret:secret||undefined,challengeId:challengeId||undefined,refreshToken});await load();setStage('idle');setPassword('');setCode('');setSecret('');setChallengeId('');Alert.alert('Two-factor authentication enabled','Your account now requires a verification code when you sign in.')}catch(e:any){Alert.alert('Unable to enable two-factor authentication',e.response?.data?.error||e.message)}finally{setBusy(false)}};
 const disable=async()=>{if(!password)return Alert.alert('Password required','Enter your current password first.');try{setBusy(true);let id='';if(status?.method==='sms')id=(await api.post('/auth/two-factor/sms-code',{purpose:'disable'})).data.challengeId;setChallengeId(id);setCode('');setStage('verify')}catch(e:any){Alert.alert('Unable to continue',e.response?.data?.error||e.message)}finally{setBusy(false)}};
 const confirmDisable=async()=>{if(!/^\d{6}$/.test(code))return Alert.alert('Enter the verification code','Enter the current six-digit code.');try{setBusy(true);await api.post('/auth/two-factor/disable',{password,code,challengeId:challengeId||undefined,refreshToken});await load();setStage('idle');setPassword('');setCode('');setChallengeId('');Alert.alert('Two-factor authentication disabled','Password-only sign in is active again.')}catch(e:any){Alert.alert('Unable to disable two-factor authentication',e.response?.data?.error||e.message)}finally{setBusy(false)}};
 const enabled=Boolean(status?.enabled);return <Screen scroll contentStyle={s.page}><Pressable onPress={()=>router.canGoBack()?router.back():router.replace('/security')} style={s.back}><Ionicons name="chevron-back" size={28} color={palette.text}/><Text style={[s.backText,{color:palette.text}]}>Security</Text></Pressable><Text style={[s.title,{color:palette.text}]}>Two-Factor Authentication</Text><Muted style={s.subtitle}>Add an extra layer of security to protect your account.</Muted>
  <Card style={[s.hero,{backgroundColor:palette.successSoft}]}><View style={[s.heroIcon,{backgroundColor:palette.success}]}><Ionicons name="shield-checkmark" size={48} color="#fff"/></View><View style={s.grow}><Text style={[s.heroTitle,{color:palette.success}]}>Stronger security for your account</Text><Muted>When enabled, you need a verification code in addition to your password to sign in.</Muted><Text style={[s.status,{color:enabled?palette.success:palette.muted}]}>Status: {enabled?`ON · ${status?.method==='sms'?'SMS':'Authenticator app'}`:'OFF'}</Text></View><Switch value={enabled} onValueChange={value=>{if(value&&!enabled)Alert.alert('Choose a method','Select a method and enter your password below.');else if(!value&&enabled)void disable()}} trackColor={{false:palette.border,true:palette.success}}/></Card>
  <Text style={[s.sectionTitle,{color:palette.text}]}>How it works</Text><Card style={s.steps}>{[['key-outline','Enter your password'],['phone-portrait-outline','Verify it is you'],['shield-checkmark-outline','Access your account']].map(([icon,label],i)=><View key={label} style={s.step}><Text style={[s.number,{backgroundColor:palette.success}]}>{i+1}</Text><Ionicons name={icon as any} size={31} color={palette.success}/><Text style={[s.stepLabel,{color:palette.text}]}>{label}</Text></View>)}</Card>
  {!enabled?<><Text style={[s.sectionTitle,{color:palette.text}]}>Choose your method</Text><Card style={s.methods}><MethodRow active={method==='authenticator'} icon="phone-portrait-outline" title="Authenticator App" body="Use Google Authenticator, Microsoft Authenticator, Authy or another TOTP app." onPress={()=>{setMethod('authenticator');setStage('idle')}}/><MethodRow active={method==='sms'} icon="chatbubble-ellipses-outline" title="SMS Verification" body={status?.phoneVerified?'Receive verification codes on your verified mobile number.':'Verify a mobile number in Edit Profile before using SMS.'} onPress={()=>{setMethod('sms');setStage('idle')}}/></Card></>:null}
  <Text style={[s.label,{color:palette.text}]}>Current Password</Text><TextInput secureTextEntry autoCapitalize="none" value={password} onChangeText={setPassword} placeholder="Enter your current password" placeholderTextColor={palette.muted} style={[s.input,{borderColor:palette.border,color:palette.text,backgroundColor:palette.surface}]}/>
  {stage==='verify'&&secret?<Card style={[s.setup,{backgroundColor:palette.successSoft}]}><Text style={[s.setupTitle,{color:palette.success}]}>Add this account to your authenticator app</Text><Muted>Use the selectable setup key below, then enter the current six-digit code generated by the app.</Muted><View style={[s.secret,{borderColor:palette.success}]}><Text selectable style={[s.secretText,{color:palette.text}]}>{secret}</Text></View></Card>:null}
  {stage==='verify'?<><Text style={[s.label,{color:palette.text}]}>Six-digit verification code</Text><TextInput keyboardType="number-pad" maxLength={6} value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} placeholder="000000" placeholderTextColor={palette.muted} style={[s.input,s.code,{borderColor:palette.border,color:palette.text,backgroundColor:palette.surface}]}/><Button title={enabled?'Disable Two-Factor Authentication':'Verify & Enable'} variant={enabled?'danger':'success'} loading={busy} disabled={code.length!==6} onPress={enabled?confirmDisable:enable}/></>:<Button title={enabled?'Disable Two-Factor Authentication':'Enable Two-Factor Authentication'} variant={enabled?'danger':'success'} loading={busy} disabled={!password||(method==='sms'&&!status?.phoneVerified)} onPress={enabled?disable:begin}/>} 
  <Card style={[s.safe,{backgroundColor:palette.successSoft}]}><Ionicons name="lock-closed-outline" size={31} color={palette.success}/><View style={s.grow}><Text style={[s.setupTitle,{color:palette.success}]}>Keep your account safe</Text><Muted>Two-factor authentication protects your account even if someone learns your password. Never share verification codes.</Muted></View></Card><Button title="Get help setting it up" variant="secondary" onPress={()=>router.push('/help')}/>
 </Screen>}
function MethodRow({active,icon,title,body,onPress}:{active:boolean;icon:keyof typeof Ionicons.glyphMap;title:string;body:string;onPress:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={onPress} style={[s.method,{borderBottomColor:palette.border}]}><View style={[s.methodIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={27} color={palette.success}/></View><View style={s.grow}><Text style={[s.methodTitle,{color:palette.text}]}>{title}</Text><Muted>{body}</Muted></View><Ionicons name={active?'radio-button-on':'radio-button-off'} size={27} color={active?palette.success:palette.muted}/></Pressable>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:800,alignSelf:'center',paddingBottom:115},back:{minHeight:52,alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:5},backText:{fontWeight:'800'},title:{fontSize:31,fontWeight:'900',marginTop:10},subtitle:{fontSize:16,marginTop:6,marginBottom:22},hero:{flexDirection:'row',alignItems:'center',gap:17,flexWrap:'wrap'},heroIcon:{width:91,height:99,borderRadius:28,alignItems:'center',justifyContent:'center'},grow:{flex:1,minWidth:180},heroTitle:{fontSize:18,fontWeight:'900',marginBottom:7},status:{fontWeight:'900',marginTop:10},sectionTitle:{fontSize:18,fontWeight:'900',marginTop:22,marginBottom:10},steps:{flexDirection:'row',paddingVertical:24},step:{flex:1,minWidth:0,alignItems:'center',gap:9,paddingHorizontal:7},number:{color:'#fff',fontWeight:'900',width:25,height:25,borderRadius:13,textAlign:'center',lineHeight:25},stepLabel:{fontSize:13,fontWeight:'900',textAlign:'center'},methods:{paddingVertical:0},method:{minHeight:102,flexDirection:'row',alignItems:'center',gap:14,borderBottomWidth:1},methodIcon:{width:58,height:58,borderRadius:29,alignItems:'center',justifyContent:'center'},methodTitle:{fontSize:16,fontWeight:'900',marginBottom:5},label:{fontSize:16,fontWeight:'900',marginTop:20,marginBottom:8},input:{minHeight:60,borderWidth:1.5,borderRadius:14,paddingHorizontal:16,fontSize:16,marginBottom:14},code:{fontSize:26,fontWeight:'900',letterSpacing:8,textAlign:'center'},setup:{gap:10,marginTop:16},setupTitle:{fontSize:17,fontWeight:'900'},secret:{minHeight:56,borderWidth:1,borderRadius:12,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:8},secretText:{flex:1,fontSize:14,fontWeight:'800',letterSpacing:1},safe:{flexDirection:'row',alignItems:'flex-start',gap:13,marginTop:18}});
