import {useEffect,useState} from 'react';
import {Alert,FlatList,Image,KeyboardAvoidingView,Linking,Platform,Pressable,StyleSheet,Text,View} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import {useQuery} from '@tanstack/react-query';
import {Ionicons} from '@expo/vector-icons';
import {SafeAreaView} from 'react-native-safe-area-context';
import {api} from '@/lib/api';
import {connectSocket,socket} from '@/lib/socket';
import {Avatar,Input,Muted,useAppTheme} from '@/components/UI';
import {InAppAudioCall} from '@/components/InAppAudioCall';
import {useAuth} from '@/store/auth';
import {LinkText} from '@/components/LinkText';
import * as DocumentPicker from 'expo-document-picker';

type Conversation={Id:string;Name:string;Type:'COMMUNITY'|'GROUP'|'DIRECT';CommunityId:string;CommunityName:string;CommunityImage?:string;DirectImage?:string};

export default function ChatRoom(){
 const{id}=useLocalSearchParams<{id:string}>();const me=useAuth(s=>s.user);const{palette}=useAppTheme();const[text,setText]=useState('');const[callOpen,setCallOpen]=useState(false);const[uploading,setUploading]=useState(false);
 const conversation=useQuery<Conversation>({queryKey:['conversation',id],queryFn:async()=>(await api.get(`/conversations/${id}`)).data,enabled:Boolean(id)});
 const{data:initial}=useQuery<any[]>({queryKey:['messages',id],queryFn:async()=>(await api.get(`/conversations/${id}/messages`)).data,enabled:Boolean(id)});const[messages,setMessages]=useState<any[]>([]);
 useEffect(()=>{if(initial)setMessages(initial)},[initial]);
 useEffect(()=>{if(!id)return;connectSocket();socket.emit('conversation:join',{conversationId:id});const onNew=(m:any)=>{if(m.ConversationId===id)setMessages(x=>x.some(y=>y.Id===m.Id)?x:[...x,m])};socket.on('message:new',onNew);return()=>{socket.off('message:new',onNew)}},[id]);
 useEffect(()=>{const incoming=({conversationId}:{conversationId:string})=>{if(conversationId!==id||callOpen)return;Alert.alert('Incoming audio call',`${conversation.data?.Name||'A conversation member'} is calling`,[{text:'Decline',style:'cancel'},{text:'Join',onPress:()=>setCallOpen(true)}])};socket.on('call:incoming',incoming);return()=>{socket.off('call:incoming',incoming)}},[id,callOpen,conversation.data?.Name]);
 const title=conversation.data?.Type==='COMMUNITY'?'General Chat':conversation.data?.Name||'Conversation';
 const avatar=conversation.data?.Type==='COMMUNITY'?conversation.data?.CommunityImage:conversation.data?.Type==='DIRECT'?conversation.data?.DirectImage:undefined;
 function send(){const value=text.trim();if(!value)return;socket.emit('message:send',{conversationId:id,messageText:value},(r:any)=>{if(!r?.ok)Alert.alert('Message not sent',r?.error||'Please try again.')});setText('')}
 async function attach(){try{const picked=await DocumentPicker.getDocumentAsync({type:['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/*'],copyToCacheDirectory:true,multiple:false});if(picked.canceled)return;const file=picked.assets[0];if(file.size&&file.size>25*1024*1024)return Alert.alert('File too large','Choose a document no larger than 25 MB.');setUploading(true);const form=new FormData();if(Platform.OS==='web'){const blob=await(await fetch(file.uri)).blob();form.append('file',blob,file.name)}else form.append('file',{uri:file.uri,name:file.name,type:file.mimeType||'application/octet-stream'} as any);const uploaded=(await api.post('/media/upload',form,{headers:{'Content-Type':'multipart/form-data'}})).data;socket.emit('message:send',{conversationId:id,messageText:uploaded.name||file.name,messageType:'DOCUMENT',mediaUrl:uploaded.url},(result:any)=>{if(!result?.ok)Alert.alert('Attachment not sent',result?.error||'Please try again.')})}catch(error:any){Alert.alert('Attachment failed',error.response?.data?.message||error.message)}finally{setUploading(false)}}
 function startCall(){setCallOpen(true)}
 return <SafeAreaView style={[s.safe,{backgroundColor:palette.background}]} edges={['top','bottom']}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}>
  <View style={[s.header,{backgroundColor:palette.background,borderBottomColor:palette.border}]}><Pressable accessibilityLabel="Back" onPress={()=>(router.canGoBack()?router.back():router.replace('/(tabs)/communities' as any))} style={s.action}><Ionicons name="chevron-back" size={28} color={palette.text}/></Pressable><View style={s.identity}>{avatar?<Image source={{uri:avatar}} style={s.avatar}/>:<Avatar name={title} size={42} backgroundColor={palette.primary}/>}<View style={s.copy}><Text numberOfLines={1} style={[s.title,{color:palette.text}]}>{title}</Text><Text numberOfLines={1} style={[s.subtitle,{color:palette.success}]}>{conversation.data?.CommunityName||'Community conversation'}</Text></View></View><Pressable accessibilityLabel="Start audio call" onPress={startCall} style={s.action}><Ionicons name="call-outline" size={25} color={palette.primary}/></Pressable></View>
  <FlatList style={s.flex} contentContainerStyle={[s.list,{backgroundColor:palette.background}]} data={messages} keyExtractor={m=>m.Id} renderItem={({item})=>{const mine=item.SenderUserId===me?.Id;const name=item.FirstName?`${item.FirstName} ${item.LastName}`:mine?'You':'Member';return <View style={[s.msgRow,mine&&s.mineRow]}>{!mine&&<Avatar name={name} uri={item.ProfileImage} size={30}/>}<View style={[s.bubble,mine?[s.mine,{backgroundColor:palette.primary}]:[s.theirs,{backgroundColor:palette.surface,borderColor:palette.border}]]}>{!mine?<Text style={[s.sender,{color:palette.muted}]}>{name}</Text>:null}{item.MediaUrl?<Pressable accessibilityRole="link" accessibilityLabel={`Open attachment ${item.MessageText||'document'}`} onPress={()=>void Linking.openURL(item.MediaUrl)} style={[s.attachment,{backgroundColor:mine?'rgba(255,255,255,.16)':palette.primarySoft}]}><Ionicons name={String(item.MessageType).includes('IMAGE')?'image-outline':'document-text-outline'} size={25} color={mine?'#fff':palette.primary}/><View style={{flex:1}}><Text numberOfLines={2} style={[s.attachmentName,{color:mine?'#fff':palette.text}]}>{item.MessageText||'Attachment'}</Text><Text style={[s.attachmentHint,{color:mine?'#FFFFFF':palette.muted}]}>Tap to open</Text></View><Ionicons name="open-outline" size={18} color={mine?'#fff':palette.primary}/></Pressable>:item.MessageText?<LinkText style={[s.msg,{color:mine?'#fff':palette.text}]}>{item.MessageText}</LinkText>:null}<Text style={[s.time,{color:mine?'#FFFFFF':palette.muted}]}>{item.CreatedAt?new Date(item.CreatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):''}</Text></View></View>}} ListEmptyComponent={<View style={s.empty}><Muted style={s.emptyText}>No messages yet. Start the conversation.</Muted></View>}/>
  <View style={[s.composer,{backgroundColor:palette.surface,borderTopColor:palette.border}]}><Pressable disabled={uploading} accessibilityLabel="Attach document" onPress={()=>void attach()} style={s.attachButton}><Ionicons name={uploading?"hourglass-outline":"attach"} size={24} color={palette.primary}/></Pressable><Input placeholder="Type a message…" value={text} onChangeText={setText} onSubmitEditing={send} style={s.input}/><Pressable accessibilityLabel="Send message" onPress={send} style={[s.send,{backgroundColor:palette.primary}]}><Ionicons name="send" size={19} color="#fff"/></Pressable></View>
 </KeyboardAvoidingView><InAppAudioCall visible={callOpen} conversationId={String(id)} title={title} onEnd={()=>setCallOpen(false)}/></SafeAreaView>
}
const s=StyleSheet.create({flex:{flex:1},safe:{flex:1},header:{height:66,flexDirection:'row',alignItems:'center',paddingHorizontal:10,borderBottomWidth:1},action:{width:46,height:46,alignItems:'center',justifyContent:'center'},identity:{flex:1,minWidth:0,flexDirection:'row',alignItems:'center',gap:10},avatar:{width:42,height:42,borderRadius:21},copy:{flex:1,minWidth:0},title:{fontSize:17,fontWeight:'900'},subtitle:{fontSize:11,fontWeight:'700',marginTop:2},list:{padding:14,paddingBottom:16,flexGrow:1},msgRow:{flexDirection:'row',alignItems:'flex-end',gap:8,marginVertical:5},mineRow:{justifyContent:'flex-end'},bubble:{maxWidth:'78%',paddingHorizontal:12,paddingVertical:9,borderRadius:16},mine:{borderBottomRightRadius:5},theirs:{borderWidth:1,borderBottomLeftRadius:5},sender:{fontSize:10,fontWeight:'900',marginBottom:3},msg:{fontSize:14,lineHeight:20},time:{fontSize:9,textAlign:'right',marginTop:4},empty:{paddingTop:40},emptyText:{textAlign:'center'},composer:{flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:10,paddingVertical:8,borderTopWidth:1},attachButton:{width:40,height:40,alignItems:'center',justifyContent:'center'},attachment:{minWidth:210,maxWidth:280,minHeight:62,borderRadius:11,padding:10,flexDirection:'row',alignItems:'center',gap:9},attachmentName:{fontSize:13,fontWeight:'900'},attachmentHint:{fontSize:10,marginTop:3},input:{flex:1,marginBottom:0,paddingVertical:10},send:{width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center'}});
