import {useEffect,useMemo,useState} from 'react';
import {Alert,FlatList,Image,KeyboardAvoidingView,Platform,Pressable,StyleSheet,Text,View} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import {useQuery} from '@tanstack/react-query';
import {Ionicons} from '@expo/vector-icons';
import {SafeAreaView} from 'react-native-safe-area-context';
import {api} from '@/lib/api';
import {connectSocket,socket} from '@/lib/socket';
import {Avatar,Input,Muted,useAppTheme} from '@/components/UI';
import {InAppAudioCall} from '@/components/InAppAudioCall';
import {useAuth} from '@/store/auth';

type Conversation={Id:string;Name:string;Type:'COMMUNITY'|'GROUP'|'DIRECT';CommunityId:string;CommunityName:string;CommunityImage?:string;DirectImage?:string};

export default function ChatRoom(){
 const{id}=useLocalSearchParams<{id:string}>();const me=useAuth(s=>s.user);const{palette}=useAppTheme();const[text,setText]=useState('');const[callOpen,setCallOpen]=useState(false);
 const conversation=useQuery<Conversation>({queryKey:['conversation',id],queryFn:async()=>(await api.get(`/conversations/${id}`)).data,enabled:Boolean(id)});
 const{data:initial}=useQuery<any[]>({queryKey:['messages',id],queryFn:async()=>(await api.get(`/conversations/${id}/messages`)).data,enabled:Boolean(id)});const[messages,setMessages]=useState<any[]>([]);
 useEffect(()=>{if(initial)setMessages(initial)},[initial]);
 useEffect(()=>{if(!id)return;connectSocket();socket.emit('conversation:join',{conversationId:id});const onNew=(m:any)=>{if(m.ConversationId===id)setMessages(x=>x.some(y=>y.Id===m.Id)?x:[...x,m])};socket.on('message:new',onNew);return()=>{socket.off('message:new',onNew)}},[id]);
 const title=conversation.data?.Type==='COMMUNITY'?'General Chat':conversation.data?.Name||'Conversation';
 const avatar=conversation.data?.Type==='COMMUNITY'?conversation.data?.CommunityImage:conversation.data?.Type==='DIRECT'?conversation.data?.DirectImage:undefined;
 const callUrl=useMemo(()=>{const room=`CDA-${String(id||'conversation').replace(/[^a-z0-9]/gi,'')}`;const name=encodeURIComponent(me?`${me.FirstName} ${me.LastName}`:'CDA member');return `https://meet.jit.si/${room}#userInfo.displayName=${name}&config.startAudioOnly=true&config.startWithVideoMuted=true&config.prejoinPageEnabled=false&config.disableDeepLinking=true&config.enableWelcomePage=false`},[id,me]);
 function send(){const value=text.trim();if(!value)return;socket.emit('message:send',{conversationId:id,messageText:value},(r:any)=>{if(!r?.ok)Alert.alert('Message not sent',r?.error||'Please try again.')});setText('')}
 function startCall(){setCallOpen(true)}
 return <SafeAreaView style={[s.safe,{backgroundColor:palette.background}]} edges={['top','bottom']}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}>
  <View style={[s.header,{backgroundColor:palette.background,borderBottomColor:palette.border}]}><Pressable accessibilityLabel="Back" onPress={()=>(router.canGoBack()?router.back():router.replace('/(tabs)/communities' as any))} style={s.action}><Ionicons name="chevron-back" size={28} color={palette.text}/></Pressable><View style={s.identity}>{avatar?<Image source={{uri:avatar}} style={s.avatar}/>:<Avatar name={title} size={42} backgroundColor={palette.primary}/>}<View style={s.copy}><Text numberOfLines={1} style={[s.title,{color:palette.text}]}>{title}</Text><Text numberOfLines={1} style={[s.subtitle,{color:palette.success}]}>{conversation.data?.CommunityName||'Community conversation'}</Text></View></View><Pressable accessibilityLabel="Start audio call" onPress={startCall} style={s.action}><Ionicons name="call-outline" size={25} color={palette.primary}/></Pressable></View>
  <FlatList style={s.flex} contentContainerStyle={[s.list,{backgroundColor:palette.background}]} data={messages} keyExtractor={m=>m.Id} renderItem={({item})=>{const mine=item.SenderUserId===me?.Id;const name=item.FirstName?`${item.FirstName} ${item.LastName}`:mine?'You':'Member';return <View style={[s.msgRow,mine&&s.mineRow]}>{!mine&&<Avatar name={name} uri={item.ProfileImage} size={30}/>}<View style={[s.bubble,mine?[s.mine,{backgroundColor:palette.primary}]:[s.theirs,{backgroundColor:palette.surface,borderColor:palette.border}]]}>{!mine?<Text style={[s.sender,{color:palette.muted}]}>{name}</Text>:null}<Text style={[s.msg,{color:mine?'#fff':palette.text}]}>{item.MessageText}</Text><Text style={[s.time,{color:mine?'#DCFCE7':palette.muted}]}>{item.CreatedAt?new Date(item.CreatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):''}</Text></View></View>}} ListEmptyComponent={<View style={s.empty}><Muted style={s.emptyText}>No messages yet. Start the conversation.</Muted></View>}/>
  <View style={[s.composer,{backgroundColor:palette.surface,borderTopColor:palette.border}]}><Input placeholder="Type a message…" value={text} onChangeText={setText} onSubmitEditing={send} style={s.input}/><Pressable accessibilityLabel="Send message" onPress={send} style={[s.send,{backgroundColor:palette.primary}]}><Ionicons name="send" size={19} color="#fff"/></Pressable></View>
 </KeyboardAvoidingView><InAppAudioCall visible={callOpen} url={callUrl} title={title} onEnd={()=>setCallOpen(false)}/></SafeAreaView>
}
const s=StyleSheet.create({flex:{flex:1},safe:{flex:1},header:{height:66,flexDirection:'row',alignItems:'center',paddingHorizontal:10,borderBottomWidth:1},action:{width:46,height:46,alignItems:'center',justifyContent:'center'},identity:{flex:1,minWidth:0,flexDirection:'row',alignItems:'center',gap:10},avatar:{width:42,height:42,borderRadius:21},copy:{flex:1,minWidth:0},title:{fontSize:17,fontWeight:'900'},subtitle:{fontSize:11,fontWeight:'700',marginTop:2},list:{padding:14,paddingBottom:16,flexGrow:1},msgRow:{flexDirection:'row',alignItems:'flex-end',gap:8,marginVertical:5},mineRow:{justifyContent:'flex-end'},bubble:{maxWidth:'78%',paddingHorizontal:12,paddingVertical:9,borderRadius:16},mine:{borderBottomRightRadius:5},theirs:{borderWidth:1,borderBottomLeftRadius:5},sender:{fontSize:10,fontWeight:'900',marginBottom:3},msg:{fontSize:14,lineHeight:20},time:{fontSize:9,textAlign:'right',marginTop:4},empty:{paddingTop:40},emptyText:{textAlign:'center'},composer:{flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:10,paddingVertical:8,borderTopWidth:1},input:{flex:1,marginBottom:0,paddingVertical:10},send:{width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center'}});
