import {decodeActivityCursor,activityAfter,activityPage} from './activityCursor.js';
import {getPool,sql} from '../config/db.js';
export const personalActivitySql=`WITH activity AS (
SELECT 'POST' Kind,p.Id,p.Id TargetId,p.CommunityId,p.CreatedAt,CAST(p.Body AS nvarchar(max)) Body,p.PostType FROM CommunityPosts p WHERE p.CreatedBy=@u AND p.IsDeleted=0
UNION ALL SELECT 'COMMENT',x.Id,p.Id,p.CommunityId,x.CreatedAt,CAST(x.Body AS nvarchar(max)),p.PostType FROM PostComments x JOIN CommunityPosts p ON p.Id=x.PostId WHERE x.UserId=@u AND x.IsDeleted=0 AND p.IsDeleted=0
UNION ALL SELECT 'REACTION',p.Id,p.Id,p.CommunityId,x.CreatedAt,CAST(x.ReactionType AS nvarchar(max)),p.PostType FROM PostReactions x JOIN CommunityPosts p ON p.Id=x.PostId WHERE x.UserId=@u AND p.IsDeleted=0
UNION ALL SELECT 'GROUP',m.Id,m.CommunityId,m.CommunityId,m.JoinedAt,CAST('' AS nvarchar(max)),NULL FROM CommunityMembers m WHERE m.UserId=@u AND m.Status='ACTIVE'
UNION ALL SELECT 'MEETING',m.Id,m.Id,m.CommunityId,a.CheckedInAt,CAST(m.Title AS nvarchar(max)),NULL FROM MeetingAttendance a JOIN Meetings m ON m.Id=a.MeetingId WHERE a.UserId=@u AND a.Status IN('PRESENT','LATE') AND dbo.CanViewMeeting(m.Id,@u)=1
UNION ALL SELECT 'EVENT',e.Id,e.Id,e.CommunityId,a.CheckedInAt,CAST(e.Title AS nvarchar(max)),NULL FROM EventAttendees a JOIN CommunityEvents e ON e.Id=a.EventId WHERE a.UserId=@u AND a.CheckedInAt IS NOT NULL
), visible AS (SELECT a.*,c.Name CommunityName FROM activity a JOIN Communities c ON c.Id=a.CommunityId WHERE EXISTS(SELECT 1 FROM Users viewer WHERE viewer.Id=@u AND viewer.AccountStatus='ACTIVE') AND EXISTS(SELECT 1 FROM CommunityMembers cm WHERE cm.CommunityId=a.CommunityId AND cm.UserId=@u AND cm.Status='ACTIVE'))`;
export async function personalActivity(userId:string,kind:string,cursor?:string){const pool=await getPool(),key=decodeActivityCursor(cursor),request=()=>pool.request().input('u',sql.UniqueIdentifier,userId).input('kind',sql.NVarChar(20),kind).input('at',sql.VarChar(33),key?.at??null).input('cursorKind',sql.NVarChar(20),key?.kind??null).input('cursorId',sql.UniqueIdentifier,key?.id??null);const totals=await request().query(personalActivitySql+` SELECT COUNT(CASE WHEN CreatedAt IS NULL THEN 1 END) Undated,COUNT(CASE WHEN Kind='POST' THEN 1 END) Posts,COUNT(CASE WHEN Kind='COMMENT' THEN 1 END) Comments,COUNT(CASE WHEN Kind='REACTION' THEN 1 END) Reactions,COUNT(CASE WHEN Kind='EVENT' THEN 1 END) EventsAttended,COUNT(CASE WHEN Kind IN('MEETING','EVENT') THEN 1 END) CheckIns,(SELECT COUNT(DISTINCT v.PollId) FROM PollVotes v JOIN Polls p ON p.Id=v.PollId WHERE v.UserId=@u AND EXISTS(SELECT 1 FROM CommunityMembers cm WHERE cm.CommunityId=p.CommunityId AND cm.UserId=@u AND cm.Status='ACTIVE')) Votes FROM visible;`);const page=await request().query(personalActivitySql+` SELECT TOP 21 *,CONVERT(varchar(33),CreatedAt,126) CursorAt FROM visible WHERE CreatedAt IS NOT NULL AND (@kind='ALL' OR Kind=@kind) AND ${activityAfter} ORDER BY CreatedAt DESC,Kind,Id;`);return {stats:totals.recordset[0],...activityPage(page.recordset)}}
