import crypto from 'node:crypto';
import {messageActionsRouter} from './messageActions.js';
import {env} from '../config/env.js';
import {communicationSettings} from '../services/communications.js';
import {requireAudience} from '../services/privacy.js';
import { Router } from 'express'; import { z } from 'zod'; import { getPool,sql } from '../config/db.js'; import { requireAuth } from '../middleware/auth.js'; import { asyncHandler,AppError } from '../utils/errors.js'; import { requireCommunityMember,requirePermission } from '../services/permissions.js';
export const chatRouter=Router();chatRouter.use(requireAuth);chatRouter.use(messageActionsRouter);
chatRouter.get('/calls/ice',asyncHandler(async(_req,res)=>{const schema=z.array(z.object({urls:z.union([z.string().url(),z.array(z.string().url()).min(1)]),username:z.string().optional(),credential:z.string().optional()})).min(1).max(8);let configured:unknown;try{configured=JSON.parse(env.RTC_ICE_SERVERS)}catch{throw new AppError(503,'Call relay configuration is invalid')}res.setHeader('Cache-Control','private, no-store');res.json({iceServers:schema.parse(configured)})}));
chatRouter.get('/communities/:communityId/conversations',asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).query(`INSERT INTO ConversationMembers(ConversationId,UserId) SELECT cv.Id,@u FROM Conversations cv WHERE cv.CommunityId=@c AND cv.Type='COMMUNITY' AND NOT EXISTS(SELECT 1 FROM ConversationMembers x WHERE x.ConversationId=cv.Id AND x.UserId=@u); SELECT cv.Id,cv.Name,cv.Type,cv.CreatedAt,cm.MutedUntil,c.LogoUrl CommunityImage,
(SELECT TOP 1 CONCAT(u2.FirstName,' ',u2.LastName) FROM ConversationMembers cm2 JOIN Users u2 ON u2.Id=cm2.UserId WHERE cm2.ConversationId=cv.Id AND cm2.UserId<>@u AND cm2.IsActive=1) DirectName,
(SELECT TOP 1 m.CreatedAt FROM Messages m WHERE m.ConversationId=cv.Id AND m.IsDeleted=0 AND NOT EXISTS(SELECT 1 FROM MessagePreferences hidden WHERE hidden.MessageId=m.Id AND hidden.UserId=@u AND hidden.IsHidden=1) ORDER BY m.CreatedAt DESC,m.Id DESC) LastMessageAt,
(SELECT TOP 1 CASE WHEN m.SenderUserId=@u THEN 'You' ELSE CONCAT(sender.FirstName,' ',sender.LastName) END FROM Messages m JOIN Users sender ON sender.Id=m.SenderUserId WHERE m.ConversationId=cv.Id AND m.IsDeleted=0 AND NOT EXISTS(SELECT 1 FROM MessagePreferences hidden WHERE hidden.MessageId=m.Id AND hidden.UserId=@u AND hidden.IsHidden=1) ORDER BY m.CreatedAt DESC,m.Id DESC) LastSender,
(SELECT COUNT(*) FROM Messages m WHERE m.ConversationId=cv.Id AND m.IsDeleted=0 AND m.SenderUserId<>@u AND NOT EXISTS(SELECT 1 FROM MessagePreferences p WHERE p.MessageId=m.Id AND p.UserId=@u AND p.IsHidden=1) AND NOT EXISTS(SELECT 1 FROM ConversationReadReceipts rr WHERE rr.ConversationId=cv.Id AND rr.UserId=@u AND rr.LastReadAt>=m.CreatedAt)) UnreadCount,
(SELECT TOP 1 MessageText FROM Messages m WHERE m.ConversationId=cv.Id AND m.IsDeleted=0 AND NOT EXISTS(SELECT 1 FROM MessagePreferences hidden WHERE hidden.MessageId=m.Id AND hidden.UserId=@u AND hidden.IsHidden=1) ORDER BY m.CreatedAt DESC,m.Id DESC) LastMessage,(SELECT TOP 1 u2.ProfileImage FROM ConversationMembers cm2 JOIN Users u2 ON u2.Id=cm2.UserId WHERE cm2.ConversationId=cv.Id AND cm2.UserId<>@u AND cm2.IsActive=1) DirectImage,(SELECT TOP 1 u2.Id FROM ConversationMembers cm2 JOIN Users u2 ON u2.Id=cm2.UserId WHERE cm2.ConversationId=cv.Id AND cm2.UserId<>@u AND cm2.IsActive=1) DirectUserId FROM Conversations cv JOIN ConversationMembers cm ON cm.ConversationId=cv.Id AND cm.IsActive=1 JOIN Communities c ON c.Id=cv.CommunityId WHERE cv.CommunityId=@c AND cm.UserId=@u ORDER BY CASE cv.Type WHEN 'COMMUNITY' THEN 0 WHEN 'GROUP' THEN 1 ELSE 2 END,cv.CreatedAt DESC`);res.json(r.recordset);}));
chatRouter.put('/conversations/:conversationId/mute',asyncHandler(async(req,res)=>{const{muted}=z.object({muted:z.boolean()}).parse(req.body),pool=await getPool();const r=await pool.request().input('cv',sql.UniqueIdentifier,req.params.conversationId).input('u',sql.UniqueIdentifier,req.user!.id).input('until',sql.DateTime2,muted?new Date('9999-12-31T23:59:59.000Z'):null).query(`UPDATE ConversationMembers SET MutedUntil=@until WHERE ConversationId=@cv AND UserId=@u AND IsActive=1;SELECT @@ROWCOUNT Affected`);if(!r.recordset[0]?.Affected)throw new AppError(404,'Active conversation membership not found');res.json({success:true,muted,mutedUntil:muted?'9999-12-31T23:59:59.000Z':null});}));
chatRouter.post('/communities/:communityId/conversations',asyncHandler(async(req,res)=>{
 const communityId=z.string().uuid().parse(req.params.communityId);await requirePermission(req.user!.id,communityId,'CHAT_CREATE');
 const d=z.object({name:z.string().trim().min(2).max(200),type:z.literal('GROUP').default('GROUP'),memberUserIds:z.array(z.string().uuid()).min(1).max(200)}).parse(req.body),pool=await getPool(),tx=new sql.Transaction(pool);await tx.begin();
 try{
  await new sql.Request(tx).input('lock',sql.NVarChar(255),'chat-group:'+req.user!.id).query(`DECLARE @result int;EXEC @result=sys.sp_getapplock @Resource=@lock,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=10000;IF @result<0 THROW 50001,'Group creation is busy, retry',1;`);
  const account=(await new sql.Request(tx).input('u',sql.UniqueIdentifier,req.user!.id).query("SELECT Id FROM Users WHERE Id=@u AND AccountStatus='ACTIVE' AND EmailVerified=1")).recordset[0];if(!account)throw new AppError(403,'Verify your email before creating a group');
  const recent=(await new sql.Request(tx).input('u',sql.UniqueIdentifier,req.user!.id).query("SELECT COUNT(*) Count FROM Conversations WHERE CreatedBy=@u AND Type='GROUP' AND CreatedAt>DATEADD(hour,-24,SYSUTCDATETIME())")).recordset[0];if(Number(recent?.Count)>=5)throw new AppError(429,'You can create up to 5 groups in 24 hours');
  const ids=[...new Set([req.user!.id,...d.memberUserIds].map(x=>x.toLowerCase()))];if(ids.length<2)throw new AppError(400,'Select at least one other active member');
  const eligible=(await new sql.Request(tx).input('c',sql.UniqueIdentifier,communityId).input('ids',sql.NVarChar(sql.MAX),JSON.stringify(ids)).query(`SELECT cm.UserId FROM CommunityMembers cm WITH(UPDLOCK,HOLDLOCK) JOIN Users u ON u.Id=cm.UserId AND u.AccountStatus='ACTIVE' WHERE cm.CommunityId=@c AND cm.Status='ACTIVE' AND cm.UserId IN(SELECT CONVERT(uniqueidentifier,value) FROM OPENJSON(@ids))`)).recordset;
  if(eligible.length!==ids.length)throw new AppError(400,'Every selected person must be an active member of this community');
  const duplicate=(await new sql.Request(tx).input('c',sql.UniqueIdentifier,communityId).input('n',sql.NVarChar(200),d.name).query("SELECT Id FROM Conversations WITH(UPDLOCK,HOLDLOCK) WHERE CommunityId=@c AND Type='GROUP' AND LOWER(LTRIM(RTRIM(Name)))=LOWER(@n)")).recordset[0];if(duplicate)throw new AppError(409,'A group with this name already exists');
  const r=await new sql.Request(tx).input('c',sql.UniqueIdentifier,communityId).input('n',sql.NVarChar(200),d.name).input('u',sql.UniqueIdentifier,req.user!.id).query(`INSERT INTO Conversations(CommunityId,Name,Type,CreatedBy) OUTPUT INSERTED.* VALUES(@c,@n,'GROUP',@u)`),cid=r.recordset[0].Id;
  for(const uid of ids)await new sql.Request(tx).input('cv',sql.UniqueIdentifier,cid).input('u',sql.UniqueIdentifier,uid).query('INSERT INTO ConversationMembers(ConversationId,UserId) VALUES(@cv,@u)');
  await new sql.Request(tx).input('c',sql.UniqueIdentifier,communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('cv',sql.UniqueIdentifier,cid).query("INSERT AuditLogs(CommunityId,UserId,Action,EntityType,EntityId) VALUES(@c,@u,'CHAT_GROUP_CREATED','Conversation',@cv)");
  await tx.commit();for(const targetUserId of ids)if(targetUserId!==req.user!.id.toLowerCase())void import('../queues/index.js').then(({enqueueCommunityNotification})=>enqueueCommunityNotification({communityId,conversationId:cid,actorUserId:req.user!.id,targetUserId,type:'INVITATION',title:'You were added to a group',body:d.name,entityId:cid,data:{conversationId:cid}})).catch(error=>console.error('Group notification failed',error));res.status(201).json(r.recordset[0]);
 }catch(e){await tx.rollback();throw e;}
}));

chatRouter.post('/communities/:communityId/direct-conversations/:otherUserId',asyncHandler(async(req,res)=>{const {listingId,requestKey}=z.object({listingId:z.string().uuid().optional(),requestKey:z.string().uuid().optional()}).parse(req.body||{}),c=req.params.communityId,u=req.user!.id,other=req.params.otherUserId;await requireCommunityMember(u,c);await requireCommunityMember(other,c);if(u===other)throw new AppError(400,'Cannot create a direct chat with yourself');await requireAudience(u,other,'contact');const pool=await getPool(),tx=new sql.Transaction(pool);await tx.begin();try{const lock='direct:'+c+':'+[u,other].sort().join(':');await new sql.Request(tx).input('lock',sql.NVarChar(255),lock).query(`DECLARE @result int;EXEC @result=sys.sp_getapplock @Resource=@lock,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=10000;IF @result<0 THROW 50001,'Conversation is busy, retry',1;`);if(listingId){const listing=await new sql.Request(tx).input('listing',sql.UniqueIdentifier,listingId).input('c',sql.UniqueIdentifier,c).input('seller',sql.UniqueIdentifier,other).query(`SELECT Id FROM MarketplaceListings WHERE Id=@listing AND CommunityId=@c AND SellerUserId=@seller AND Status='ACTIVE' AND ModerationStatus='APPROVED'`);if(!listing.recordset[0])throw new AppError(404,'Listing is unavailable for this seller')}
let conversation=(await new sql.Request(tx).input('c',sql.UniqueIdentifier,c).input('u1',sql.UniqueIdentifier,u).input('u2',sql.UniqueIdentifier,other).query(`SELECT TOP 1 cv.* FROM Conversations cv WHERE cv.CommunityId=@c AND cv.Type='DIRECT' AND (SELECT COUNT(*) FROM ConversationMembers cm WHERE cm.ConversationId=cv.Id AND cm.IsActive=1)=2 AND EXISTS(SELECT 1 FROM ConversationMembers WHERE ConversationId=cv.Id AND UserId=@u1 AND IsActive=1) AND EXISTS(SELECT 1 FROM ConversationMembers WHERE ConversationId=cv.Id AND UserId=@u2 AND IsActive=1) ORDER BY cv.CreatedAt`)).recordset[0];const created=!conversation;if(!conversation){conversation=(await new sql.Request(tx).input('c',sql.UniqueIdentifier,c).input('u',sql.UniqueIdentifier,u).query(`INSERT Conversations(CommunityId,Name,Type,CreatedBy) OUTPUT INSERTED.* VALUES(@c,'Direct message','DIRECT',@u)`)).recordset[0];for(const member of [u,other])await new sql.Request(tx).input('cv',sql.UniqueIdentifier,conversation.Id).input('u',sql.UniqueIdentifier,member).query('INSERT ConversationMembers(ConversationId,UserId) VALUES(@cv,@u)')}
if(listingId){const key=requestKey||crypto.randomUUID(),previous=(await new sql.Request(tx).input('c',sql.UniqueIdentifier,c).input('u',sql.UniqueIdentifier,u).input('key',sql.UniqueIdentifier,key).query('SELECT ConversationId,ListingId FROM ChatReferenceRequests WITH(UPDLOCK,HOLDLOCK) WHERE CommunityId=@c AND UserId=@u AND RequestKey=@key')).recordset[0];if(previous&&(previous.ConversationId!==conversation.Id||previous.ListingId!==listingId))throw new AppError(409,'Request key was already used for a different listing');if(!previous){const text='Marketplace listing\n'+new URL('/community/'+c+'/marketplace?listing='+listingId,env.PUBLIC_BASE_URL).href;await new sql.Request(tx).input('cv',sql.UniqueIdentifier,conversation.Id).input('u',sql.UniqueIdentifier,u).input('text',sql.NVarChar(sql.MAX),text).input('c',sql.UniqueIdentifier,c).input('key',sql.UniqueIdentifier,key).input('listing',sql.UniqueIdentifier,listingId).query(`INSERT Messages(ConversationId,SenderUserId,MessageType,MessageText) VALUES(@cv,@u,'TEXT',@text);INSERT ChatReferenceRequests(CommunityId,UserId,RequestKey,ConversationId,ListingId) VALUES(@c,@u,@key,@cv,@listing)`)} }
await tx.commit();res.status(created?201:200).json(conversation)}catch(e){await tx.rollback();throw e}}));

chatRouter.get('/conversations/:conversationId/messages',asyncHandler(async(req,res)=>{const pool=await getPool();const membership=await pool.request().input('cv',sql.UniqueIdentifier,req.params.conversationId).input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT 1 ok FROM ConversationMembers cm JOIN Conversations c ON c.Id=cm.ConversationId JOIN CommunityMembers member ON member.CommunityId=c.CommunityId AND member.UserId=@u AND member.Status='ACTIVE' WHERE cm.ConversationId=@cv AND cm.UserId=@u AND cm.IsActive=1`);if(!membership.recordset[0])throw new AppError(403,'Not in conversation');const r=await pool.request().input('cv',sql.UniqueIdentifier,req.params.conversationId).input('viewer',sql.UniqueIdentifier,req.user!.id).query(`SELECT TOP 100 m.Id,m.MessageType,m.MessageText,m.MediaUrl,m.ReplyToMessageId,m.ForwardedFromMessageId,m.CreatedAt,COALESCE(pref.IsStarred,0) IsStarred,pref.Note,(SELECT mr.Emoji,COUNT(*) Count FROM MessageReactions mr WHERE mr.MessageId=m.Id GROUP BY mr.Emoji FOR JSON PATH) Reactions,(SELECT Emoji FROM MessageReactions mr WHERE mr.MessageId=m.Id AND mr.UserId=@viewer) MyReaction,(SELECT TOP 1 reply.MessageText FROM Messages reply WHERE reply.Id=m.ReplyToMessageId AND reply.ConversationId=m.ConversationId AND reply.IsDeleted=0) ReplyText,CASE WHEN m.SenderUserId=@viewer THEN (SELECT COUNT(*) FROM ConversationReadReceipts rr LEFT JOIN CommunicationSettings prefs ON prefs.UserId=rr.UserId JOIN ConversationMembers cm ON cm.ConversationId=rr.ConversationId AND cm.UserId=rr.UserId AND cm.IsActive=1 WHERE rr.ConversationId=m.ConversationId AND rr.UserId<>@viewer AND rr.LastReadAt>=m.CreatedAt AND COALESCE(prefs.ReadReceipts,1)=1) ELSE 0 END ReadCount,u.Id SenderUserId,u.FirstName,u.LastName,u.ProfileImage FROM Messages m JOIN Users u ON u.Id=m.SenderUserId LEFT JOIN MessagePreferences pref ON pref.MessageId=m.Id AND pref.UserId=@viewer WHERE m.ConversationId=@cv AND m.IsDeleted=0 AND COALESCE(pref.IsHidden,0)=0 ORDER BY m.CreatedAt DESC,m.Id DESC`);res.json(r.recordset.reverse());}));
chatRouter.get('/conversations/:conversationId',asyncHandler(async(req,res)=>{const pool=await getPool();const r=await pool.request().input('cv',sql.UniqueIdentifier,req.params.conversationId).input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT TOP 1 cv.Id,cv.Name,cv.Type,cv.CommunityId,c.Name CommunityName,c.LogoUrl CommunityImage,(SELECT TOP 1 CONCAT(u2.FirstName,' ',u2.LastName) FROM ConversationMembers cm2 JOIN Users u2 ON u2.Id=cm2.UserId WHERE cm2.ConversationId=cv.Id AND cm2.UserId<>@u AND cm2.IsActive=1) DirectName,(SELECT TOP 1 u2.ProfileImage FROM ConversationMembers cm2 JOIN Users u2 ON u2.Id=cm2.UserId WHERE cm2.ConversationId=cv.Id AND cm2.UserId<>@u) DirectImage FROM Conversations cv JOIN ConversationMembers cm ON cm.ConversationId=cv.Id AND cm.UserId=@u JOIN Communities c ON c.Id=cv.CommunityId JOIN CommunityMembers member ON member.CommunityId=cv.CommunityId AND member.UserId=@u AND member.Status='ACTIVE' WHERE cv.Id=@cv AND cm.IsActive=1`);if(!r.recordset[0])throw new AppError(403,'Not in conversation');res.json(r.recordset[0]);}));

chatRouter.post('/conversations/:conversationId/read',asyncHandler(async(req,res)=>{const id=z.string().uuid().parse(req.params.conversationId),{messageId}=z.object({messageId:z.string().uuid()}).parse(req.body),pool=await getPool();const record=(await pool.request().input('cv',sql.UniqueIdentifier,id).input('u',sql.UniqueIdentifier,req.user!.id).input('m',sql.UniqueIdentifier,messageId).query(`SELECT m.CreatedAt FROM Messages m JOIN ConversationMembers cm ON cm.ConversationId=m.ConversationId AND cm.UserId=@u AND cm.IsActive=1 JOIN Conversations c ON c.Id=m.ConversationId JOIN CommunityMembers member ON member.CommunityId=c.CommunityId AND member.UserId=@u AND member.Status='ACTIVE' WHERE m.Id=@m AND m.ConversationId=@cv AND m.IsDeleted=0`)).recordset[0];if(!record)throw new AppError(403,'Message not available');const prefs=await communicationSettings(req.user!.id);await pool.request().input('cv',sql.UniqueIdentifier,id).input('u',sql.UniqueIdentifier,req.user!.id).input('m',sql.UniqueIdentifier,messageId).query(`MERGE ConversationReadReceipts WITH(HOLDLOCK) t USING(SELECT @cv ConversationId,@u UserId,m.CreatedAt LastReadAt FROM Messages m WHERE m.Id=@m AND m.ConversationId=@cv AND m.IsDeleted=0)s ON t.ConversationId=s.ConversationId AND t.UserId=s.UserId WHEN MATCHED AND t.LastReadAt<s.LastReadAt THEN UPDATE SET LastReadAt=s.LastReadAt WHEN NOT MATCHED THEN INSERT(ConversationId,UserId,LastReadAt) VALUES(s.ConversationId,s.UserId,s.LastReadAt);`);res.json({shared:prefs.ReadReceipts!==false&&prefs.ReadReceipts!==0})}));

