import {Router} from 'express';
import {z} from 'zod';
import {getPool,sql} from '../config/db.js';
import {getRedis} from '../config/redis.js';
import {asyncHandler,AppError} from '../utils/errors.js';
import {normalizePhone} from '../services/sms.js';
export const communicationsRouter=Router();
communicationsRouter.get('/communications',asyncHandler(async(req,res)=>{
 const pool=await getPool();const r=await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT u.Email,u.Phone,u.EmailVerified,u.PhoneVerified,COALESCE(a.EmailUpdates,0) EmailUpdates,COALESCE(s.ReadReceipts,1) ReadReceipts,COALESCE(s.TypingIndicators,1) TypingIndicators,COALESCE(s.SmsUpdates,0) SmsUpdates,COALESCE(s.InAppMessages,1) InAppMessages,COALESCE(s.VoiceCalls,1) VoiceCalls,COALESCE(s.ContactSync,0) ContactSync,s.DoNotDisturbUntil,COALESCE(p.WhoCanMessage,'MEMBERS') WhoCanMessage,COALESCE(app.NotificationPreviewsEnabled,0) MessagePreviews,(SELECT COUNT(*) FROM BlockedUsers b WHERE b.UserId=u.Id) BlockedCount,(SELECT COUNT(*) FROM SyncedContacts c WHERE c.UserId=u.Id) SyncedCount FROM Users u LEFT JOIN AccountSettings a ON a.UserId=u.Id LEFT JOIN CommunicationSettings s ON s.UserId=u.Id LEFT JOIN PrivacyPreferences p ON p.UserId=u.Id LEFT JOIN UserAppPreferences app ON app.UserId=u.Id WHERE u.Id=@u`);res.set('Cache-Control','no-store').json(r.recordset[0]);
}));
communicationsRouter.patch('/communications',asyncHandler(async(req,res)=>{
 const d=z.discriminatedUnion('key',[z.object({key:z.enum(['readReceipts','typingIndicators','smsUpdates','inAppMessages','voiceCalls','messagePreviews','emailUpdates']),value:z.boolean()}),z.object({key:z.literal('whoCanMessage'),value:z.enum(['MEMBERS','ADMINS','NOBODY'])}),z.object({key:z.literal('dndMinutes'),value:z.number().int().min(0).max(10080)})]).parse(req.body),pool=await getPool();
 if(d.key==='smsUpdates'&&d.value){const user=(await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).query('SELECT Phone,PhoneVerified FROM Users WHERE Id=@u')).recordset[0];if(!user?.PhoneVerified||!user.Phone)throw new AppError(400,'Verify your phone number before enabling SMS updates')}
 if(d.key==='emailUpdates'&&d.value){const user=(await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).query('SELECT EmailVerified FROM Users WHERE Id=@u')).recordset[0];if(!user?.EmailVerified)throw new AppError(400,'Verify your email before enabling email updates')}
 const config={readReceipts:['CommunicationSettings','ReadReceipts'],typingIndicators:['CommunicationSettings','TypingIndicators'],smsUpdates:['CommunicationSettings','SmsUpdates'],inAppMessages:['CommunicationSettings','InAppMessages'],voiceCalls:['CommunicationSettings','VoiceCalls'],messagePreviews:['UserAppPreferences','NotificationPreviewsEnabled'],emailUpdates:['AccountSettings','EmailUpdates'],whoCanMessage:['PrivacyPreferences','WhoCanMessage'],dndMinutes:['CommunicationSettings','DoNotDisturbUntil']} as const;
 const [table,column]=config[d.key],value=d.key==='dndMinutes'?(d.value?new Date(Date.now()+d.value*60000):null):d.value;
 await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).input('v',d.key==='dndMinutes'?sql.DateTime2:typeof value==='boolean'?sql.Bit:sql.NVarChar(20),value).query(`MERGE ${table} WITH(HOLDLOCK) t USING(SELECT @u UserId)s ON t.UserId=s.UserId WHEN MATCHED THEN UPDATE SET ${column}=@v,UpdatedAt=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(UserId,${column}) VALUES(@u,@v);`);res.json({success:true});
}));
const contactVisibility=`u.AccountStatus='ACTIVE' AND u.PhoneVerified=1 AND p.PhoneVisibility='MEMBERS' AND EXISTS(SELECT 1 FROM CommunityMembers mine JOIN CommunityMembers theirs ON theirs.CommunityId=mine.CommunityId WHERE mine.UserId=@u AND theirs.UserId=u.Id AND mine.Status='ACTIVE' AND theirs.Status='ACTIVE') AND NOT EXISTS(SELECT 1 FROM BlockedUsers b WHERE (b.UserId=@u AND b.BlockedUserId=u.Id) OR (b.UserId=u.Id AND b.BlockedUserId=@u)) AND NOT EXISTS(SELECT 1 FROM HiddenUsers h WHERE h.UserId=u.Id AND h.HiddenUserId=@u)`;
communicationsRouter.get('/communications/contacts',asyncHandler(async(req,res)=>{const pool=await getPool();res.json((await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT u.Id,u.FirstName,u.LastName FROM SyncedContacts c JOIN Users u ON u.Id=c.ContactUserId JOIN PrivacyPreferences p ON p.UserId=u.Id WHERE c.UserId=@u AND ${contactVisibility}`)).recordset)}));
communicationsRouter.post('/communications/contacts',asyncHandler(async(req,res)=>{
 const {phones}=z.object({phones:z.array(z.string().max(40)).min(1).max(5000)}).parse(req.body),numbers=[...new Set(phones.map(normalizePhone))],redis=getRedis(),key='contact-sync:'+req.user!.id;
 const attempts=await redis.incr(key);if(attempts===1)await redis.expire(key,3600);if(attempts>10)throw new AppError(429,'Please wait before syncing contacts again');
 const pool=await getPool();await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).input('phones',sql.NVarChar(sql.MAX),JSON.stringify(numbers)).query(`SET XACT_ABORT ON;BEGIN TRANSACTION;DELETE FROM SyncedContacts WHERE UserId=@u;INSERT INTO SyncedContacts(UserId,ContactUserId) SELECT DISTINCT @u,u.Id FROM OPENJSON(@phones) ph JOIN Users u ON u.Phone=ph.value JOIN PrivacyPreferences p ON p.UserId=u.Id WHERE u.Id<>@u AND ${contactVisibility};MERGE CommunicationSettings WITH(HOLDLOCK) t USING(SELECT @u UserId)s ON t.UserId=s.UserId WHEN MATCHED THEN UPDATE SET ContactSync=1,UpdatedAt=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(UserId,ContactSync) VALUES(@u,1);COMMIT;`);res.json({success:true});
}));
communicationsRouter.delete('/communications/contacts',asyncHandler(async(req,res)=>{const pool=await getPool();await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).query(`SET XACT_ABORT ON;BEGIN TRANSACTION;DELETE FROM SyncedContacts WHERE UserId=@u;UPDATE CommunicationSettings SET ContactSync=0,UpdatedAt=SYSUTCDATETIME() WHERE UserId=@u;COMMIT;`);res.json({success:true})}));
