import { Router } from 'express';
import multer from 'multer';
import { requireAuth } from '../middleware/auth.js';
import { env } from '../config/env.js';
import { asyncHandler, AppError } from '../utils/errors.js';
import { storeObject,deleteObject,readObject } from '../services/storage.js';
import { getPool, sql } from '../config/db.js';
import sharp from 'sharp';
import path from 'node:path';
import { getRedis } from '../config/redis.js';
import { requirePermission } from '../services/permissions.js';

const fileTypes:Record<string,{mime:string;signature:'pdf'|'jpeg'|'png'|'gif'|'webp'|'mp4'|'mp3'|'wav'|'ole'|'zip'|'text'}>={pdf:{mime:'application/pdf',signature:'pdf'},jpg:{mime:'image/jpeg',signature:'jpeg'},jpeg:{mime:'image/jpeg',signature:'jpeg'},png:{mime:'image/png',signature:'png'},gif:{mime:'image/gif',signature:'gif'},webp:{mime:'image/webp',signature:'webp'},mp4:{mime:'video/mp4',signature:'mp4'},mov:{mime:'video/quicktime',signature:'mp4'},m4a:{mime:'audio/mp4',signature:'mp4'},mp3:{mime:'audio/mpeg',signature:'mp3'},wav:{mime:'audio/wav',signature:'wav'},doc:{mime:'application/msword',signature:'ole'},xls:{mime:'application/vnd.ms-excel',signature:'ole'},ppt:{mime:'application/vnd.ms-powerpoint',signature:'ole'},docx:{mime:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',signature:'zip'},xlsx:{mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',signature:'zip'},pptx:{mime:'application/vnd.openxmlformats-officedocument.presentationml.presentation',signature:'zip'},txt:{mime:'text/plain',signature:'text'},csv:{mime:'text/csv',signature:'text'}};
const cleanName=(value:string)=>path.basename(value).normalize('NFKC').replace(/[^\p{L}\p{N} ._()-]/gu,'_').replace(/\s+/g,' ').slice(0,180)||'document';
function matchesSignature(buffer:Buffer,type:typeof fileTypes[string]['signature']){const ascii=buffer.subarray(0,16).toString('ascii');if(type==='pdf')return ascii.startsWith('%PDF-');if(type==='jpeg')return buffer[0]===0xff&&buffer[1]===0xd8&&buffer[2]===0xff;if(type==='png')return buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));if(type==='gif')return ascii.startsWith('GIF87a')||ascii.startsWith('GIF89a');if(type==='webp')return ascii.startsWith('RIFF')&&ascii.slice(8,12)==='WEBP';if(type==='wav')return ascii.startsWith('RIFF')&&ascii.slice(8,12)==='WAVE';if(type==='mp4')return ascii.slice(4,8)==='ftyp';if(type==='mp3')return ascii.startsWith('ID3')||(buffer[0]===0xff&&(buffer[1]&0xe0)===0xe0);if(type==='ole')return buffer.subarray(0,8).equals(Buffer.from([0xd0,0xcf,0x11,0xe0,0xa1,0xb1,0x1a,0xe1]));if(type==='zip')return ascii.startsWith('PK\x03\x04');if(type==='text')return !buffer.subarray(0,4096).includes(0)&&!buffer.subarray(0,4096).toString('utf8').includes('\uFFFD');return false}
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 25 * 1024 * 1024,files:1 },
  fileFilter: (_r, f, cb) => fileTypes[path.extname(f.originalname).slice(1).toLowerCase()] ? cb(null, true) : cb(new AppError(400, 'Unsupported file extension'))
});

export const mediaRouter = Router();
mediaRouter.get('/media/document-download/:token',asyncHandler(async(req,res)=>{const redis=getRedis(),raw=await redis.get(`document-download:${req.params.token}`);if(!raw)throw new AppError(404,'Download link expired');const claim=JSON.parse(raw),pool=await getPool(),record=(await pool.request().input('u',sql.UniqueIdentifier,claim.userId).input('d',sql.UniqueIdentifier,claim.documentId).input('object',sql.UniqueIdentifier,claim.storedObjectId).query(`SELECT stored.StorageKey,stored.OriginalName,stored.MimeType FROM KnowledgeDocuments documentRow JOIN CommunityMembers member ON member.CommunityId=documentRow.CommunityId AND member.UserId=@u AND member.Status='ACTIVE' JOIN Users viewer ON viewer.Id=@u AND viewer.AccountStatus='ACTIVE' JOIN KnowledgeDocumentVersions versionRow ON versionRow.DocumentId=documentRow.Id AND versionRow.VersionNumber=documentRow.CurrentVersion JOIN StoredObjects stored ON stored.Id=versionRow.StoredObjectId AND stored.Id=@object AND stored.UploadState='AVAILABLE' AND stored.DeletedAt IS NULL WHERE documentRow.Id=@d AND (documentRow.Visibility='MEMBERS' OR EXISTS(SELECT 1 FROM CommunityMemberRoles memberRole JOIN RolePermissions rolePermission ON rolePermission.RoleId=memberRole.RoleId JOIN Permissions permission ON permission.Id=rolePermission.PermissionId WHERE memberRole.CommunityMemberId=member.Id AND permission.Code='DOCUMENT_MANAGE') OR EXISTS(SELECT 1 FROM Communities community WHERE community.Id=documentRow.CommunityId AND community.OwnerUserId=@u)) AND (NOT EXISTS(SELECT 1 FROM KnowledgeDocumentAccess WHERE DocumentId=documentRow.Id) OR EXISTS(SELECT 1 FROM KnowledgeDocumentAccess accessRule JOIN CommunityMemberRoles allowedRole ON allowedRole.CommunityMemberId=member.Id AND allowedRole.RoleId=accessRule.RoleId WHERE accessRule.DocumentId=documentRow.Id AND accessRule.CanView=1))`)).recordset[0];if(!record)throw new AppError(404,'Document not found');const bytes=await readObject(record.StorageKey),filename=cleanName(record.OriginalName).replace(/["\\]/g,'_'),fallback=filename.replace(/[^\x20-\x7E]/g,'_');res.setHeader('Content-Type',record.MimeType);res.setHeader('Content-Disposition',`attachment; filename="${fallback}"; filename*=UTF-8''${encodeURIComponent(filename)}`);res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Security-Policy',"default-src 'none'; sandbox");res.setHeader('Cache-Control','private, no-store, max-age=0');res.send(bytes)}));
mediaRouter.use(requireAuth);
mediaRouter.post('/media/upload', upload.single('file'), asyncHandler(async (req, res) => {
  if (!req.file) throw new AppError(400, 'File required');
  const pollImage=req.query.profile==='poll-option'||req.query.profile==='poll';
  const extension=path.extname(req.file.originalname).slice(1).toLowerCase(),detected=fileTypes[extension];if(!detected||!matchesSignature(req.file.buffer,detected.signature))throw new AppError(400,'File content does not match its extension or is not supported');
  if(pollImage&&!detected.mime.startsWith('image/'))throw new AppError(400,'Poll artwork must be an image');
  const documentUpload=req.query.purpose==='document',communityId=String(req.query.communityId??'');if(documentUpload){if(!/^[0-9a-f-]{36}$/i.test(communityId))throw new AppError(400,'Community is required for document uploads');await requirePermission(req.user!.id,communityId,'DOCUMENT_MANAGE');const redis=getRedis(),rateKey=`upload:document:${req.user!.id}:${Math.floor(Date.now()/60000)}`,attempts=await redis.incr(rateKey);if(attempts===1)await redis.expire(rateKey,60);if(attempts>5)throw new AppError(429,'Upload limit reached. Try again in one minute.');const pool=await getPool(),quota=(await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).input('c',sql.UniqueIdentifier,communityId).query(`SELECT (SELECT COUNT(*) FROM StoredObjects WHERE UploadedBy=@u AND CreatedAt>=DATEADD(day,-1,SYSUTCDATETIME()) AND DeletedAt IS NULL) UserDaily,(SELECT COUNT(*) FROM StoredObjects WHERE CommunityId=@c AND DeletedAt IS NULL) CommunityFiles,(SELECT COALESCE(SUM(SizeBytes),0) FROM StoredObjects WHERE CommunityId=@c AND DeletedAt IS NULL) CommunityBytes`)).recordset[0];if(quota.UserDaily>=20)throw new AppError(429,'Daily upload limit reached');if(quota.CommunityFiles>=250)throw new AppError(409,'Community file-count quota reached');if(Number(quota.CommunityBytes)+req.file.size>1024*1024*1024)throw new AppError(409,'Community storage quota reached')}
  const processed=pollImage?await sharp(req.file.buffer).rotate().resize(512,512,{fit:'cover',position:'centre',withoutEnlargement:true}).webp({quality:78,effort:4}).toBuffer():req.file.buffer;
  const originalName=pollImage?`${cleanName(req.file.originalname).replace(/\.[^.]+$/,'')}.webp`:cleanName(req.file.originalname),mimeType=pollImage?'image/webp':detected.mime;
  const stored = await storeObject({ buffer: processed, originalName, mimeType, prefix:documentUpload?'private-documents':'media',private:documentUpload });
  const pool = await getPool();
  try{const record=await pool.request().input('u', sql.UniqueIdentifier, req.user!.id).input('c',sql.UniqueIdentifier,documentUpload?communityId:null).input('k', sql.NVarChar(1000), stored.key).input('url', sql.NVarChar(1500), stored.url).input('name', sql.NVarChar(500), originalName).input('mime', sql.NVarChar(150), mimeType).input('size', sql.BigInt, processed.length).input('private',sql.Bit,documentUpload).query(`INSERT INTO StoredObjects(UploadedBy,CommunityId,StorageKey,PublicUrl,OriginalName,MimeType,SizeBytes,UploadState,IsPrivate) OUTPUT INSERTED.Id VALUES(@u,@c,@k,@url,@name,@mime,@size,'AVAILABLE',@private)`);res.status(201).json({storedObjectId:record.recordset[0].Id,name:originalName,mimeType,size:processed.length,processed:pollImage})}catch(error){await deleteObject(stored.key);throw error}
}));
mediaRouter.delete('/media/uploads/:storedObjectId',asyncHandler(async(req,res)=>{const pool=await getPool(),record=(await pool.request().input('id',sql.UniqueIdentifier,req.params.storedObjectId).input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT StorageKey FROM StoredObjects WHERE Id=@id AND UploadedBy=@u AND DeletedAt IS NULL AND NOT EXISTS(SELECT 1 FROM KnowledgeDocumentVersions WHERE StoredObjectId=@id)`)).recordset[0];if(!record)throw new AppError(404,'Unused upload not found');await deleteObject(record.StorageKey);await pool.request().input('id',sql.UniqueIdentifier,req.params.storedObjectId).query(`UPDATE StoredObjects SET UploadState='DELETED',DeletedAt=SYSUTCDATETIME() WHERE Id=@id`);res.json({success:true})}));
mediaRouter.post('/media/transcribe', upload.single('file'), asyncHandler(async (req, res) => {
  if (!req.file) throw new AppError(400, 'Audio file required');
  if (!env.LANGUAGE_SERVICE_URL) return res.status(503).json({ message: 'Transcription provider is not configured', transcript: null });
  const fd = new FormData();
  fd.append('task', 'transcribe');
  const audioBytes = Uint8Array.from(req.file.buffer);
  fd.append('file', new Blob([audioBytes], { type: req.file.mimetype }), req.file.originalname);
  const r = await fetch(env.LANGUAGE_SERVICE_URL, { method: 'POST', headers: env.LANGUAGE_SERVICE_API_KEY ? { Authorization: `Bearer ${env.LANGUAGE_SERVICE_API_KEY}` } : {}, body: fd });
  if (!r.ok) throw new AppError(502, 'Transcription provider failed');
  const data: any = await r.json();
  res.json({ transcript: data.transcript ?? data.text ?? '' });
}));
