import {Router} from 'express';
import {z} from 'zod';
import {getPool,sql} from '../config/db.js';
import {requireAuth} from '../middleware/auth.js';
import {asyncHandler,AppError} from '../utils/errors.js';
import {requireConversationContact} from '../services/privacy.js';
import {emitConversationEvent} from '../services/conversationEvents.js';
export const messageActionsRouter=Router();messageActionsRouter.use(requireAuth);
export const reactionSchema=z.enum(['👍','❤️','😂','😮','😢','🙏','🎉','👎','🔥','✅']);
// Every action checks both conversation and community membership, including reads.
async function messageFor(user:string,conversation:string,message:string){
 const row=(await(await getPool()).request().input('u',sql.UniqueIdentifier,user).input('cv',sql.UniqueIdentifier,z.string().uuid().parse(conversation)).input('m',sql.UniqueIdentifier,z.string().uuid().parse(message)).query(`SELECT m.*,c.CommunityId FROM Messages m JOIN Conversations c ON c.Id=m.ConversationId JOIN ConversationMembers cm ON cm.ConversationId=c.Id AND cm.UserId=@u AND cm.IsActive=1 JOIN CommunityMembers member ON member.CommunityId=c.CommunityId AND member.UserId=@u AND member.Status='ACTIVE' WHERE m.Id=@m AND m.ConversationId=@cv AND m.IsDeleted=0 AND NOT EXISTS(SELECT 1 FROM MessagePreferences p WHERE p.MessageId=m.Id AND p.UserId=@u AND p.IsHidden=1)`)).recordset[0];
 if(!row)throw new AppError(404,'Message is unavailable');return row;
}
messageActionsRouter.put('/conversations/:conversationId/messages/:messageId/preferences',asyncHandler(async(req,res)=>{
 const d=z.object({starred:z.boolean().optional(),hidden:z.literal(true).optional(),note:z.string().trim().max(2000).optional()}).strict().refine(v=>Object.keys(v).length>0).parse(req.body);
 await messageFor(req.user!.id,req.params.conversationId,req.params.messageId);
 await(await getPool()).request().input('u',sql.UniqueIdentifier,req.user!.id).input('m',sql.UniqueIdentifier,req.params.messageId).input('star',sql.Bit,d.starred??null).input('hidden',sql.Bit,d.hidden??null).input('note',sql.NVarChar(2000),d.note??null).query(`MERGE MessagePreferences WITH(HOLDLOCK) t USING(SELECT @m MessageId,@u UserId)s ON t.MessageId=s.MessageId AND t.UserId=s.UserId WHEN MATCHED THEN UPDATE SET IsStarred=COALESCE(@star,t.IsStarred),IsHidden=COALESCE(@hidden,t.IsHidden),Note=COALESCE(@note,t.Note) WHEN NOT MATCHED THEN INSERT(MessageId,UserId,IsStarred,IsHidden,Note) VALUES(@m,@u,COALESCE(@star,0),COALESCE(@hidden,0),@note);`);
 res.json({success:true});
}));
messageActionsRouter.put('/conversations/:conversationId/messages/:messageId/reaction',asyncHandler(async(req,res)=>{
 const{emoji}=z.object({emoji:reactionSchema.nullable()}).parse(req.body);await messageFor(req.user!.id,req.params.conversationId,req.params.messageId);
 await(await getPool()).request().input('u',sql.UniqueIdentifier,req.user!.id).input('m',sql.UniqueIdentifier,req.params.messageId).input('emoji',sql.NVarChar(16),emoji).query(`MERGE MessageReactions WITH(HOLDLOCK) t USING(SELECT @m MessageId,@u UserId)s ON t.MessageId=s.MessageId AND t.UserId=s.UserId WHEN MATCHED AND @emoji IS NULL THEN DELETE WHEN MATCHED THEN UPDATE SET Emoji=@emoji WHEN NOT MATCHED AND @emoji IS NOT NULL THEN INSERT(MessageId,UserId,Emoji) VALUES(@m,@u,@emoji);`);
 emitConversationEvent(req.params.conversationId,'message:updated',{ConversationId:req.params.conversationId});res.json({success:true});
}));
messageActionsRouter.delete('/conversations/:conversationId/messages/:messageId',asyncHandler(async(req,res)=>{
 const m=await messageFor(req.user!.id,req.params.conversationId,req.params.messageId);if(String(m.SenderUserId).toLowerCase()!==req.user!.id.toLowerCase())throw new AppError(403,'Only the sender can delete a message for everyone');
 await(await getPool()).request().input('m',sql.UniqueIdentifier,m.Id).input('u',sql.UniqueIdentifier,req.user!.id).query('UPDATE Messages SET IsDeleted=1 WHERE Id=@m AND SenderUserId=@u');emitConversationEvent(req.params.conversationId,'message:updated',{ConversationId:req.params.conversationId});res.json({success:true});
}));
messageActionsRouter.post('/conversations/:conversationId/messages/:messageId/report',asyncHandler(async(req,res)=>{
 const{reason,details}=z.object({reason:z.enum(['Spam','Harassment','Threats','Scam','Inappropriate content','Other']),details:z.string().trim().max(1500).default('')}).parse(req.body);const m=await messageFor(req.user!.id,req.params.conversationId,req.params.messageId);
 const snapshot={reason,details,messageId:m.Id,conversationId:m.ConversationId,senderUserId:m.SenderUserId,text:String(m.MessageText||'').slice(0,1600)};let body=JSON.stringify(snapshot);while(body.length>4000){if(snapshot.text)snapshot.text=snapshot.text.slice(0,Math.max(0,snapshot.text.length-(body.length-4000)));else snapshot.details=snapshot.details.slice(0,Math.max(0,snapshot.details.length-(body.length-4000)));body=JSON.stringify(snapshot)}
 const result=await(await getPool()).request().input('u',sql.UniqueIdentifier,req.user!.id).input('subject',sql.NVarChar(200),'Chat message report: '+m.Id).input('body',sql.NVarChar(4000),body).query(`SET XACT_ABORT ON;BEGIN TRANSACTION;IF NOT EXISTS(SELECT 1 FROM SupportTickets WITH(UPDLOCK,HOLDLOCK) WHERE UserId=@u AND Category='SAFETY' AND Subject=@subject AND Status='OPEN') INSERT INTO SupportTickets(UserId,Category,Subject,Message) VALUES(@u,'SAFETY',@subject,@body);SELECT TOP 1 Id FROM SupportTickets WHERE UserId=@u AND Category='SAFETY' AND Subject=@subject ORDER BY CreatedAt DESC;COMMIT;`);
 res.status(201).json({success:true,ticketId:result.recordset[0]?.Id});
}));
messageActionsRouter.post('/conversations/:conversationId/messages/:messageId/forward',asyncHandler(async(req,res)=>{
 const{targetConversationId,requestKey}=z.object({targetConversationId:z.string().uuid(),requestKey:z.string().uuid()}).parse(req.body);const m=await messageFor(req.user!.id,req.params.conversationId,req.params.messageId);if(targetConversationId.toLowerCase()===req.params.conversationId.toLowerCase())throw new AppError(400,'Choose another conversation');
 const pool=await getPool(),target=(await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).input('cv',sql.UniqueIdentifier,targetConversationId).input('c',sql.UniqueIdentifier,m.CommunityId).query(`SELECT c.Id,c.Name,c.CommunityId FROM Conversations c JOIN ConversationMembers cm ON cm.ConversationId=c.Id AND cm.UserId=@u AND cm.IsActive=1 JOIN CommunityMembers member ON member.CommunityId=c.CommunityId AND member.UserId=@u AND member.Status='ACTIVE' JOIN Communities community ON community.Id=c.CommunityId AND community.PlatformStatus='ACTIVE' WHERE c.Id=@cv AND c.CommunityId=@c`)).recordset[0];if(!target)throw new AppError(403,'Choose an active conversation in this community');await requireConversationContact(req.user!.id,targetConversationId);
 // Forward only a server-authorised source message. Private media remains in this community.
 const result=await pool.request().input('cv',sql.UniqueIdentifier,targetConversationId).input('u',sql.UniqueIdentifier,req.user!.id).input('key',sql.UniqueIdentifier,requestKey).input('m',sql.UniqueIdentifier,m.Id).query(`SET XACT_ABORT ON;BEGIN TRANSACTION;IF EXISTS(SELECT 1 FROM Messages WITH(UPDLOCK,HOLDLOCK) WHERE SenderUserId=@u AND ClientMessageId=@key) SELECT *,CAST(1 AS BIT) Duplicate FROM Messages WHERE SenderUserId=@u AND ClientMessageId=@key;ELSE INSERT Messages(ConversationId,SenderUserId,ClientMessageId,MessageType,MessageText,MediaUrl,ForwardedFromMessageId) OUTPUT INSERTED.*,CAST(0 AS BIT) Duplicate SELECT @cv,@u,@key,MessageType,MessageText,MediaUrl,@m FROM Messages WHERE Id=@m AND IsDeleted=0;COMMIT;`);const sent=result.recordset[0];if(!sent)throw new AppError(404,'Message is unavailable');if(String(sent.ConversationId).toLowerCase()!==targetConversationId.toLowerCase()||String(sent.ForwardedFromMessageId).toLowerCase()!==String(m.Id).toLowerCase())throw new AppError(409,'Forward request was already used');if(!sent.Duplicate){emitConversationEvent(targetConversationId,'message:new',sent);void import('../queues/index.js').then(({enqueueCommunityNotification})=>enqueueCommunityNotification({communityId:target.CommunityId,conversationId:targetConversationId,actorUserId:req.user!.id,type:'CHAT_MESSAGE',title:target.Name,body:'Forwarded a message',entityId:sent.Id,data:{conversationId:targetConversationId,messageId:sent.Id}})).catch(error=>console.error('Forward notification failed',error))}res.status(201).json({success:true});
}));
