import { Router } from 'express';
import crypto from 'node:crypto';
import { z } from 'zod';
import { getPool, sql } from '../config/db.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncHandler, AppError } from '../utils/errors.js';
import { audit } from '../services/audit.js';
import { requireCommunityMember, requirePermission } from '../services/permissions.js';
import { env } from '../config/env.js';

export const platformRouter = Router();
platformRouter.use(requireAuth);

const categories=['CDA / Residents Associations','Sports','Parents','Professional','Youth','Charity','Cultural','Educational','Religious','Social'] as const;

// Discovery preferences use coarse town/postcode only. No member GPS coordinates are exposed.
platformRouter.get('/discovery/preferences', asyncHandler(async(req,res)=>{
  const pool=await getPool();
  const r=await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT DiscoveryEnabled,Town,Postcode,PreferredRadiusKm FROM UserDiscoveryPreferences WHERE UserId=@u`);
  res.json(r.recordset[0]??{DiscoveryEnabled:false,Town:null,Postcode:null,PreferredRadiusKm:25});
}));
platformRouter.put('/discovery/preferences', asyncHandler(async(req,res)=>{
  const d=z.object({discoveryEnabled:z.boolean(),town:z.string().max(120).optional().nullable(),postcode:z.string().max(20).optional().nullable(),preferredRadiusKm:z.number().int().min(1).max(100).default(25)}).parse(req.body);
  const pool=await getPool();
  await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).input('e',sql.Bit,d.discoveryEnabled).input('t',sql.NVarChar(120),d.town??null).input('p',sql.NVarChar(20),d.postcode??null).input('r',sql.Int,d.preferredRadiusKm).query(`MERGE UserDiscoveryPreferences t USING(SELECT @u UserId)s ON t.UserId=s.UserId WHEN MATCHED THEN UPDATE SET DiscoveryEnabled=@e,Town=@t,Postcode=@p,PreferredRadiusKm=@r,UpdatedAt=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(UserId,DiscoveryEnabled,Town,Postcode,PreferredRadiusKm) VALUES(@u,@e,@t,@p,@r);`);
  res.json({success:true});
}));
platformRouter.get('/discover/communities', asyncHandler(async(req,res)=>{
  const q=String(req.query.q??'').trim(); const category=String(req.query.category??'').trim(); const town=String(req.query.town??'').trim(); const postcode=String(req.query.postcode??'').trim(); const near=String(req.query.near??'false')==='true';
  const pool=await getPool();
  let pref:any=null;
  if(near){const pr=await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT * FROM UserDiscoveryPreferences WHERE UserId=@u AND DiscoveryEnabled=1`);pref=pr.recordset[0];}
  const areaTown=town||pref?.Town||''; const areaPostcode=postcode||pref?.Postcode||'';
  const r=await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).input('q',sql.NVarChar(250),`%${q}%`).input('cat',sql.NVarChar(80),category).input('town',sql.NVarChar(120),areaTown).input('pc',sql.NVarChar(20),areaPostcode).query(`
    SELECT TOP 60 c.Id,c.Name,c.Description,c.LogoUrl,c.BannerUrl,c.CommunityType,c.Category,c.Country,c.City,c.Postcode,c.IsPrivate,c.IsVerified,c.VerifiedAt,
      CASE WHEN cm.Status='ACTIVE' THEN 'MEMBER' WHEN jr.Status='PENDING' THEN 'PENDING' ELSE 'AVAILABLE' END JoinStatus,
      (SELECT COUNT(*) FROM CommunityMembers x WHERE x.CommunityId=c.Id AND x.Status='ACTIVE') MemberCount
    FROM Communities c
    LEFT JOIN CommunityMembers cm ON cm.CommunityId=c.Id AND cm.UserId=@u
    LEFT JOIN CommunityJoinRequests jr ON jr.CommunityId=c.Id AND jr.UserId=@u AND jr.Status='PENDING'
    WHERE (@q='%%' OR c.Name LIKE @q OR c.Description LIKE @q OR c.City LIKE @q OR c.Postcode LIKE @q OR c.Category LIKE @q)
      AND (@cat='' OR c.Category=@cat OR c.CommunityType=@cat)
      AND (@town='' OR c.City LIKE '%'+@town+'%')
      AND (@pc='' OR c.Postcode LIKE @pc+'%')
    ORDER BY c.IsVerified DESC, MemberCount DESC, c.Name`);
  res.json({categories,nearEnabled:!!pref,items:r.recordset});
}));


platformRouter.get('/communities/:communityId/capabilities', asyncHandler(async(req,res)=>{
 const pool=await getPool(); const r=await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).input('c',sql.UniqueIdentifier,req.params.communityId).query(`SELECT DISTINCT r.Name RoleName,p.Code PermissionCode FROM CommunityMembers cm LEFT JOIN CommunityMemberRoles cmr ON cmr.CommunityMemberId=cm.Id LEFT JOIN Roles r ON r.Id=cmr.RoleId LEFT JOIN RolePermissions rp ON rp.RoleId=r.Id LEFT JOIN Permissions p ON p.Id=rp.PermissionId WHERE cm.UserId=@u AND cm.CommunityId=@c AND cm.Status='ACTIVE'`); if(!r.recordset.length)throw new AppError(403,'Not a member'); res.json({roles:[...new Set(r.recordset.map(x=>x.RoleName).filter(Boolean))],permissions:[...new Set(r.recordset.map(x=>x.PermissionCode).filter(Boolean))]});
}));
platformRouter.post('/verification/:requestId/review', asyncHandler(async(req,res)=>{
 const reviewers=env.PLATFORM_ADMIN_EMAILS.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean); if(!reviewers.includes(req.user!.email.toLowerCase()))throw new AppError(403,'Platform verification reviewer access required');
 const d=z.object({decision:z.enum(['APPROVE','REJECT']),reviewNotes:z.string().max(2000).optional()}).parse(req.body); const pool=await getPool(); const vr=await pool.request().input('id',sql.UniqueIdentifier,req.params.requestId).query(`SELECT * FROM CommunityVerificationRequests WHERE Id=@id`); const v=vr.recordset[0]; if(!v)throw new AppError(404,'Verification request not found'); const tx=new sql.Transaction(pool);await tx.begin();try{await new sql.Request(tx).input('id',sql.UniqueIdentifier,req.params.requestId).input('u',sql.UniqueIdentifier,req.user!.id).input('s',sql.NVarChar(30),d.decision==='APPROVE'?'APPROVED':'REJECTED').input('n',sql.NVarChar(2000),d.reviewNotes??null).query(`UPDATE CommunityVerificationRequests SET Status=@s,ReviewNotes=@n,ReviewedBy=@u,ReviewedAt=SYSUTCDATETIME() WHERE Id=@id`);if(d.decision==='APPROVE')await new sql.Request(tx).input('c',sql.UniqueIdentifier,v.CommunityId).query(`UPDATE Communities SET IsVerified=1,VerifiedAt=SYSUTCDATETIME() WHERE Id=@c`);await tx.commit();res.json({success:true,status:d.decision});}catch(e){await tx.rollback();throw e;}
}));

// Verification submission. Public verification is only set after a platform review outside this community-admin endpoint.
platformRouter.post('/communities/:communityId/verification', asyncHandler(async(req,res)=>{
  await requirePermission(req.user!.id,req.params.communityId,'VERIFICATION_SUBMIT');
  const d=z.object({organisationName:z.string().min(2).max(200),registrationNumber:z.string().max(120).optional(),evidenceUrl:z.string().url(),notes:z.string().max(2000).optional()}).parse(req.body);
  const pool=await getPool();
  const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('o',sql.NVarChar(200),d.organisationName).input('rn',sql.NVarChar(120),d.registrationNumber??null).input('e',sql.NVarChar(1000),d.evidenceUrl).input('n',sql.NVarChar(2000),d.notes??null).query(`INSERT INTO CommunityVerificationRequests(CommunityId,SubmittedBy,OrganisationName,RegistrationNumber,EvidenceUrl,Notes) OUTPUT INSERTED.* VALUES(@c,@u,@o,@rn,@e,@n)`);
  await audit(req.params.communityId,req.user!.id,'VERIFICATION_SUBMITTED','CommunityVerificationRequest',r.recordset[0].Id); res.status(201).json(r.recordset[0]);
}));
platformRouter.get('/communities/:communityId/verification', asyncHandler(async(req,res)=>{
  await requireCommunityMember(req.user!.id,req.params.communityId); const pool=await getPool();
  const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).query(`SELECT TOP 1 v.*,c.IsVerified,c.VerifiedAt FROM CommunityVerificationRequests v JOIN Communities c ON c.Id=v.CommunityId WHERE v.CommunityId=@c ORDER BY v.CreatedAt DESC`); res.json(r.recordset[0]??null);
}));

// Community issue reporting
platformRouter.get('/communities/:communityId/issues', asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).query(`SELECT i.*,u.FirstName,u.LastName,a.FirstName AssignedFirstName,a.LastName AssignedLastName FROM CommunityIssues i JOIN Users u ON u.Id=i.ReportedBy LEFT JOIN Users a ON a.Id=i.AssignedTo WHERE i.CommunityId=@c ORDER BY CASE i.Status WHEN 'SUBMITTED' THEN 0 WHEN 'ASSIGNED' THEN 1 WHEN 'IN_PROGRESS' THEN 2 ELSE 3 END,i.CreatedAt DESC`);res.json(r.recordset);}));
platformRouter.post('/communities/:communityId/issues', asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const d=z.object({category:z.enum(['Broken streetlight','Pothole','Waste problem','Water issue','Security concern','Noise','Damaged facility','Flooding','Other']),title:z.string().min(2).max(250),description:z.string().min(3).max(4000),photoUrl:z.string().url().optional(),approximateLocation:z.string().max(250).optional()}).parse(req.body);const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('cat',sql.NVarChar(80),d.category).input('t',sql.NVarChar(250),d.title).input('d',sql.NVarChar(4000),d.description).input('p',sql.NVarChar(1000),d.photoUrl??null).input('l',sql.NVarChar(250),d.approximateLocation??null).query(`INSERT INTO CommunityIssues(CommunityId,ReportedBy,Category,Title,Description,PhotoUrl,ApproximateLocation) OUTPUT INSERTED.* VALUES(@c,@u,@cat,@t,@d,@p,@l)`);await audit(req.params.communityId,req.user!.id,'ISSUE_REPORTED','CommunityIssue',r.recordset[0].Id);res.status(201).json(r.recordset[0]);}));
platformRouter.patch('/communities/:communityId/issues/:issueId', asyncHandler(async(req,res)=>{await requirePermission(req.user!.id,req.params.communityId,'ISSUE_MANAGE');const d=z.object({status:z.enum(['SUBMITTED','ASSIGNED','IN_PROGRESS','RESOLVED']),assignedTo:z.string().uuid().optional().nullable(),note:z.string().max(2000).optional(),resolutionNote:z.string().max(3000).optional()}).parse(req.body);const pool=await getPool();await pool.request().input('i',sql.UniqueIdentifier,req.params.issueId).input('c',sql.UniqueIdentifier,req.params.communityId).input('s',sql.NVarChar(30),d.status).input('a',sql.UniqueIdentifier,d.assignedTo??null).input('r',sql.NVarChar(3000),d.resolutionNote??null).query(`UPDATE CommunityIssues SET Status=@s,AssignedTo=@a,ResolutionNote=COALESCE(@r,ResolutionNote),ResolvedAt=CASE WHEN @s='RESOLVED' THEN SYSUTCDATETIME() ELSE NULL END,UpdatedAt=SYSUTCDATETIME() WHERE Id=@i AND CommunityId=@c`);if(d.note)await pool.request().input('i',sql.UniqueIdentifier,req.params.issueId).input('u',sql.UniqueIdentifier,req.user!.id).input('s',sql.NVarChar(30),d.status).input('n',sql.NVarChar(2000),d.note).query(`INSERT INTO CommunityIssueUpdates(IssueId,CreatedBy,Status,Note) VALUES(@i,@u,@s,@n)`);await audit(req.params.communityId,req.user!.id,'ISSUE_UPDATED','CommunityIssue',req.params.issueId,{status:d.status});res.json({success:true});}));

// Trusted local service directory
platformRouter.get('/communities/:communityId/services', asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const category=String(req.query.category??'');const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('cat',sql.NVarChar(100),category).query(`SELECT s.*,CAST(ISNULL((SELECT AVG(CAST(Rating AS FLOAT)) FROM ServiceReviews r WHERE r.ProviderId=s.Id),0) AS DECIMAL(3,1)) Rating,(SELECT COUNT(*) FROM ServiceReviews r WHERE r.ProviderId=s.Id) ReviewCount FROM ServiceProviders s WHERE s.CommunityId=@c AND s.Status='ACTIVE' AND (@cat='' OR s.Category=@cat) ORDER BY s.IsVerified DESC,Rating DESC,s.Name`);res.json(r.recordset);}));
platformRouter.post('/communities/:communityId/services', asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const d=z.object({name:z.string().min(2).max(200),category:z.string().min(2).max(100),description:z.string().max(3000).optional(),phone:z.string().max(40).optional(),email:z.string().email().optional(),website:z.string().url().optional(),area:z.string().max(200).optional(),logoUrl:z.string().url().optional()}).parse(req.body);const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('n',sql.NVarChar(200),d.name).input('cat',sql.NVarChar(100),d.category).input('d',sql.NVarChar(3000),d.description??null).input('p',sql.NVarChar(40),d.phone??null).input('e',sql.NVarChar(255),d.email??null).input('w',sql.NVarChar(500),d.website??null).input('a',sql.NVarChar(200),d.area??null).input('l',sql.NVarChar(1000),d.logoUrl??null).query(`INSERT INTO ServiceProviders(CommunityId,CreatedBy,Name,Category,Description,Phone,Email,Website,Area,LogoUrl) OUTPUT INSERTED.* VALUES(@c,@u,@n,@cat,@d,@p,@e,@w,@a,@l)`);res.status(201).json(r.recordset[0]);}));
platformRouter.patch('/communities/:communityId/services/:providerId/verification', asyncHandler(async(req,res)=>{await requirePermission(req.user!.id,req.params.communityId,'DIRECTORY_MANAGE');const {isVerified}=z.object({isVerified:z.boolean()}).parse(req.body);const pool=await getPool();await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('p',sql.UniqueIdentifier,req.params.providerId).input('v',sql.Bit,isVerified).query(`UPDATE ServiceProviders SET IsVerified=@v WHERE Id=@p AND CommunityId=@c`);await audit(req.params.communityId,req.user!.id,isVerified?'SERVICE_VERIFIED':'SERVICE_UNVERIFIED','ServiceProvider',req.params.providerId);res.json({success:true});}));
platformRouter.post('/services/:providerId/reviews', asyncHandler(async(req,res)=>{const d=z.object({rating:z.number().int().min(1).max(5),comment:z.string().max(2000).optional()}).parse(req.body);const pool=await getPool();const s=await pool.request().input('id',sql.UniqueIdentifier,req.params.providerId).query(`SELECT CommunityId FROM ServiceProviders WHERE Id=@id`);if(!s.recordset[0])throw new AppError(404,'Service not found');await requireCommunityMember(req.user!.id,s.recordset[0].CommunityId);await pool.request().input('p',sql.UniqueIdentifier,req.params.providerId).input('u',sql.UniqueIdentifier,req.user!.id).input('r',sql.TinyInt,d.rating).input('c',sql.NVarChar(2000),d.comment??null).query(`MERGE ServiceReviews t USING(SELECT @p ProviderId,@u UserId)s ON t.ProviderId=s.ProviderId AND t.UserId=s.UserId WHEN MATCHED THEN UPDATE SET Rating=@r,Comment=@c,CreatedAt=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(ProviderId,UserId,Rating,Comment) VALUES(@p,@u,@r,@c);`);res.json({success:true});}));

// Marketplace
platformRouter.get('/communities/:communityId/marketplace', asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const type=String(req.query.type??'');const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('t',sql.NVarChar(30),type).query(`SELECT m.*,u.FirstName,u.LastName,CASE WHEN EXISTS(SELECT 1 FROM CommunityMembers cm JOIN CommunityMemberRoles cmr ON cmr.CommunityMemberId=cm.Id JOIN Roles r ON r.Id=cmr.RoleId WHERE cm.UserId=m.SellerUserId AND cm.CommunityId=m.CommunityId AND r.Name IN('Owner','Admin')) THEN 1 ELSE 0 END SellerVerified FROM MarketplaceListings m JOIN Users u ON u.Id=m.SellerUserId WHERE m.CommunityId=@c AND m.Status='ACTIVE' AND m.ModerationStatus='APPROVED' AND (@t='' OR m.ListingType=@t) ORDER BY m.CreatedAt DESC`);res.json(r.recordset);}));
platformRouter.post('/communities/:communityId/marketplace', asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const d=z.object({listingType:z.enum(['FOR_SALE','FREE','WANTED','SERVICES','RENTALS','JOBS']),title:z.string().min(2).max(220),description:z.string().max(4000).optional(),price:z.number().min(0).optional(),currency:z.string().max(10).default('GBP'),area:z.string().max(200).optional(),imageUrl:z.string().url().optional()}).parse(req.body);const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('lt',sql.NVarChar(30),d.listingType).input('t',sql.NVarChar(220),d.title).input('d',sql.NVarChar(4000),d.description??null).input('p',sql.Decimal(18,2),d.price??null).input('cur',sql.NVarChar(10),d.currency).input('a',sql.NVarChar(200),d.area??null).input('img',sql.NVarChar(1000),d.imageUrl??null).query(`INSERT INTO MarketplaceListings(CommunityId,SellerUserId,ListingType,Title,Description,Price,Currency,Area,ImageUrl) OUTPUT INSERTED.* VALUES(@c,@u,@lt,@t,@d,@p,@cur,@a,@img)`);res.status(201).json(r.recordset[0]);}));
platformRouter.post('/marketplace/:listingId/report', asyncHandler(async(req,res)=>{const d=z.object({reason:z.string().min(2).max(120),details:z.string().max(1000).optional()}).parse(req.body);const pool=await getPool();const x=await pool.request().input('id',sql.UniqueIdentifier,req.params.listingId).query(`SELECT CommunityId FROM MarketplaceListings WHERE Id=@id`);if(!x.recordset[0])throw new AppError(404,'Listing not found');await requireCommunityMember(req.user!.id,x.recordset[0].CommunityId);await pool.request().input('l',sql.UniqueIdentifier,req.params.listingId).input('u',sql.UniqueIdentifier,req.user!.id).input('r',sql.NVarChar(120),d.reason).input('d',sql.NVarChar(1000),d.details??null).query(`INSERT INTO MarketplaceReports(ListingId,ReportedBy,Reason,Details) VALUES(@l,@u,@r,@d)`);res.status(201).json({success:true});}));
platformRouter.delete('/communities/:communityId/marketplace/:listingId', asyncHandler(async(req,res)=>{await requirePermission(req.user!.id,req.params.communityId,'MARKETPLACE_MODERATE');const pool=await getPool();await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('id',sql.UniqueIdentifier,req.params.listingId).query(`UPDATE MarketplaceListings SET Status='REMOVED',UpdatedAt=SYSUTCDATETIME() WHERE Id=@id AND CommunityId=@c`);await audit(req.params.communityId,req.user!.id,'MARKETPLACE_REMOVED','MarketplaceListing',req.params.listingId);res.status(204).end();}));

// Jobs and opportunities
platformRouter.get('/communities/:communityId/opportunities', asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const type=String(req.query.type??'');const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('t',sql.NVarChar(40),type).query(`SELECT o.*,CASE WHEN so.UserId IS NULL THEN 0 ELSE 1 END IsSaved FROM CommunityOpportunities o LEFT JOIN SavedOpportunities so ON so.OpportunityId=o.Id AND so.UserId=@u WHERE o.CommunityId=@c AND o.Status='OPEN' AND (@t='' OR o.OpportunityType=@t) ORDER BY CASE WHEN o.Deadline IS NULL THEN 1 ELSE 0 END,o.Deadline,o.CreatedAt DESC`);res.json(r.recordset);}));
platformRouter.post('/communities/:communityId/opportunities', asyncHandler(async(req,res)=>{await requirePermission(req.user!.id,req.params.communityId,'OPPORTUNITY_MANAGE');const d=z.object({opportunityType:z.enum(['JOB','VOLUNTEERING','TRAINING','SCHOLARSHIP','INTERNSHIP','COMMUNITY']),title:z.string().min(2).max(250),description:z.string().min(3).max(5000),organisation:z.string().max(200).optional(),location:z.string().max(200).optional(),applyUrl:z.string().url().optional(),deadline:z.coerce.date().optional()}).parse(req.body);const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('ot',sql.NVarChar(40),d.opportunityType).input('t',sql.NVarChar(250),d.title).input('d',sql.NVarChar(5000),d.description).input('o',sql.NVarChar(200),d.organisation??null).input('l',sql.NVarChar(200),d.location??null).input('a',sql.NVarChar(1000),d.applyUrl??null).input('dl',sql.DateTime2,d.deadline??null).query(`INSERT INTO CommunityOpportunities(CommunityId,CreatedBy,OpportunityType,Title,Description,Organisation,Location,ApplyUrl,Deadline) OUTPUT INSERTED.* VALUES(@c,@u,@ot,@t,@d,@o,@l,@a,@dl)`);res.status(201).json(r.recordset[0]);}));
platformRouter.post('/opportunities/:opportunityId/save', asyncHandler(async(req,res)=>{const pool=await getPool();const o=await pool.request().input('id',sql.UniqueIdentifier,req.params.opportunityId).query(`SELECT CommunityId FROM CommunityOpportunities WHERE Id=@id`);if(!o.recordset[0])throw new AppError(404,'Opportunity not found');await requireCommunityMember(req.user!.id,o.recordset[0].CommunityId);await pool.request().input('o',sql.UniqueIdentifier,req.params.opportunityId).input('u',sql.UniqueIdentifier,req.user!.id).query(`IF EXISTS(SELECT 1 FROM SavedOpportunities WHERE OpportunityId=@o AND UserId=@u) DELETE FROM SavedOpportunities WHERE OpportunityId=@o AND UserId=@u ELSE INSERT INTO SavedOpportunities(OpportunityId,UserId) VALUES(@o,@u)`);res.json({success:true});}));

// Events
platformRouter.get('/communities/:communityId/events', asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT e.*,ea.Status MyStatus,ea.CheckedInAt,(SELECT COUNT(*) FROM EventAttendees x WHERE x.EventId=e.Id AND x.Status='GOING') GoingCount,(SELECT COUNT(*) FROM EventAttendees x WHERE x.EventId=e.Id AND x.Status='WAITLIST') WaitlistCount,(SELECT COUNT(*) FROM EventPhotos p WHERE p.EventId=e.Id) PhotoCount,(SELECT TOP 1 p.PhotoUrl FROM EventPhotos p WHERE p.EventId=e.Id ORDER BY p.CreatedAt DESC) LastPhotoUrl FROM CommunityEvents e LEFT JOIN EventAttendees ea ON ea.EventId=e.Id AND ea.UserId=@u WHERE e.CommunityId=@c ORDER BY e.StartDateTime`);res.json(r.recordset);}));
platformRouter.post('/communities/:communityId/events', asyncHandler(async(req,res)=>{await requirePermission(req.user!.id,req.params.communityId,'EVENT_CREATE');const d=z.object({title:z.string().min(2).max(250),description:z.string().max(5000).optional(),eventType:z.string().max(80).optional(),location:z.string().max(500).optional(),startDateTime:z.coerce.date(),endDateTime:z.coerce.date(),capacity:z.number().int().positive().optional(),allowWaitlist:z.boolean().default(true),reminderMinutes:z.number().int().min(0).optional(),coverImageUrl:z.string().url().optional()}).parse(req.body);const pool=await getPool();const tx=new sql.Transaction(pool);await tx.begin();try{const cv=await new sql.Request(tx).input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('n',sql.NVarChar(200),d.title).query(`INSERT INTO Conversations(CommunityId,Name,Type,CreatedBy) OUTPUT INSERTED.Id VALUES(@c,@n,'EVENT',@u)`);const r=await new sql.Request(tx).input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('t',sql.NVarChar(250),d.title).input('d',sql.NVarChar(5000),d.description??null).input('et',sql.NVarChar(80),d.eventType??null).input('l',sql.NVarChar(500),d.location??null).input('s',sql.DateTime2,d.startDateTime).input('e',sql.DateTime2,d.endDateTime).input('cap',sql.Int,d.capacity??null).input('w',sql.Bit,d.allowWaitlist).input('rm',sql.Int,d.reminderMinutes??null).input('img',sql.NVarChar(1000),d.coverImageUrl??null).input('cv',sql.UniqueIdentifier,cv.recordset[0].Id).query(`INSERT INTO CommunityEvents(CommunityId,CreatedBy,Title,Description,EventType,Location,StartDateTime,EndDateTime,Capacity,AllowWaitlist,ReminderMinutes,CoverImageUrl,ConversationId) OUTPUT INSERTED.* VALUES(@c,@u,@t,@d,@et,@l,@s,@e,@cap,@w,@rm,@img,@cv)`);await tx.commit();res.status(201).json(r.recordset[0]);}catch(e){await tx.rollback();throw e;}}));
platformRouter.post('/events/:eventId/rsvp', asyncHandler(async(req,res)=>{const d=z.object({status:z.enum(['GOING','NOT_GOING'])}).parse(req.body);const pool=await getPool();const er=await pool.request().input('e',sql.UniqueIdentifier,req.params.eventId).query(`SELECT * FROM CommunityEvents WHERE Id=@e`);const event=er.recordset[0];if(!event)throw new AppError(404,'Event not found');await requireCommunityMember(req.user!.id,event.CommunityId);let status:'GOING'|'NOT_GOING'|'WAITLIST'=d.status;if(status==='GOING'&&event.Capacity){const cr=await pool.request().input('e',sql.UniqueIdentifier,req.params.eventId).query(`SELECT COUNT(*) n FROM EventAttendees WHERE EventId=@e AND Status='GOING'`);if(cr.recordset[0].n>=event.Capacity)status=event.AllowWaitlist?'WAITLIST':'NOT_GOING';}await pool.request().input('e',sql.UniqueIdentifier,req.params.eventId).input('u',sql.UniqueIdentifier,req.user!.id).input('s',sql.NVarChar(30),status).query(`MERGE EventAttendees t USING(SELECT @e EventId,@u UserId)s ON t.EventId=s.EventId AND t.UserId=s.UserId WHEN MATCHED THEN UPDATE SET Status=@s WHEN NOT MATCHED THEN INSERT(EventId,UserId,Status) VALUES(@e,@u,@s); INSERT INTO ConversationMembers(ConversationId,UserId) SELECT ConversationId,@u FROM CommunityEvents WHERE Id=@e AND ConversationId IS NOT NULL AND @s IN ('GOING','WAITLIST') AND NOT EXISTS(SELECT 1 FROM ConversationMembers cm WHERE cm.ConversationId=CommunityEvents.ConversationId AND cm.UserId=@u);`);res.json({success:true,status});}));
platformRouter.post('/events/:eventId/photos', asyncHandler(async(req,res)=>{const {photoUrl}=z.object({photoUrl:z.string().url()}).parse(req.body);const pool=await getPool();const e=await pool.request().input('e',sql.UniqueIdentifier,req.params.eventId).query(`SELECT CommunityId FROM CommunityEvents WHERE Id=@e`);if(!e.recordset[0])throw new AppError(404,'Event not found');await requireCommunityMember(req.user!.id,e.recordset[0].CommunityId);await pool.request().input('e',sql.UniqueIdentifier,req.params.eventId).input('u',sql.UniqueIdentifier,req.user!.id).input('p',sql.NVarChar(1000),photoUrl).query(`INSERT INTO EventPhotos(EventId,UploadedBy,PhotoUrl) VALUES(@e,@u,@p)`);res.status(201).json({success:true});}));

// Digital membership card and QR check-in
platformRouter.get('/communities/:communityId/membership-card', asyncHandler(async(req,res)=>{const membershipId=await requireCommunityMember(req.user!.id,req.params.communityId);const pool=await getPool();let card=(await pool.request().input('m',sql.UniqueIdentifier,membershipId).query(`SELECT * FROM MembershipCards WHERE MembershipId=@m AND IsActive=1`)).recordset[0];if(!card){const cardNumber='CDA-'+crypto.randomBytes(5).toString('hex').toUpperCase();const token=crypto.randomBytes(24).toString('base64url');card=(await pool.request().input('m',sql.UniqueIdentifier,membershipId).input('n',sql.NVarChar(50),cardNumber).input('q',sql.NVarChar(120),token).query(`INSERT INTO MembershipCards(MembershipId,CardNumber,QrToken) OUTPUT INSERTED.* VALUES(@m,@n,@q)`)).recordset[0];}const data=await pool.request().input('m',sql.UniqueIdentifier,membershipId).query(`SELECT cm.JoinedAt,u.FirstName,u.LastName,c.Name CommunityName,STRING_AGG(r.Name,', ') Roles FROM CommunityMembers cm JOIN Users u ON u.Id=cm.UserId JOIN Communities c ON c.Id=cm.CommunityId LEFT JOIN CommunityMemberRoles cmr ON cmr.CommunityMemberId=cm.Id LEFT JOIN Roles r ON r.Id=cmr.RoleId WHERE cm.Id=@m GROUP BY cm.JoinedAt,u.FirstName,u.LastName,c.Name`);res.json({...card,...data.recordset[0],QrPayload:`CDACONNECT:${card.QrToken}`});}));
platformRouter.post('/communities/:communityId/check-in', asyncHandler(async(req,res)=>{await requirePermission(req.user!.id,req.params.communityId,'MEMBERSHIP_SCAN');const d=z.object({qrPayload:z.string().min(10),eventId:z.string().uuid().optional(),meetingId:z.string().uuid().optional()}).parse(req.body);const token=d.qrPayload.replace(/^CDACONNECT:/,'');const pool=await getPool();const r=await pool.request().input('q',sql.NVarChar(120),token).input('c',sql.UniqueIdentifier,req.params.communityId).query(`SELECT mc.Id CardId,cm.UserId,u.FirstName,u.LastName FROM MembershipCards mc JOIN CommunityMembers cm ON cm.Id=mc.MembershipId JOIN Users u ON u.Id=cm.UserId WHERE mc.QrToken=@q AND mc.IsActive=1 AND cm.CommunityId=@c AND cm.Status='ACTIVE'`);if(!r.recordset[0])throw new AppError(404,'Valid membership card not found');if(d.eventId)await pool.request().input('e',sql.UniqueIdentifier,d.eventId).input('u',sql.UniqueIdentifier,r.recordset[0].UserId).query(`MERGE EventAttendees t USING(SELECT @e EventId,@u UserId)s ON t.EventId=s.EventId AND t.UserId=s.UserId WHEN MATCHED THEN UPDATE SET Status='GOING',CheckedInAt=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(EventId,UserId,Status,CheckedInAt) VALUES(@e,@u,'GOING',SYSUTCDATETIME());`);if(d.meetingId)await pool.request().input('m',sql.UniqueIdentifier,d.meetingId).input('u',sql.UniqueIdentifier,r.recordset[0].UserId).query(`MERGE MeetingAttendees t USING(SELECT @m MeetingId,@u UserId)s ON t.MeetingId=s.MeetingId AND t.UserId=s.UserId WHEN MATCHED THEN UPDATE SET Response='GOING',RespondedAt=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(MeetingId,UserId,Response) VALUES(@m,@u,'GOING');`);res.json({success:true,member:r.recordset[0]});}));
