import {sosRouter} from './sos.js';
import { Router } from 'express';
import { z } from 'zod';
import { getPool, sql } from '../config/db.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncHandler, AppError } from '../utils/errors.js';
import { requireCommunityMember, requirePermission } from '../services/permissions.js';
import { audit } from '../services/audit.js';
export const safetyRouter=Router(); safetyRouter.use(requireAuth);

safetyRouter.get('/communities/:communityId/emergency/dashboard',asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const pool=await getPool();const alerts=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT TOP 20 a.*,er.Response MyResponse,(SELECT COUNT(DISTINCT d.UserId) FROM EmergencyNotificationDeliveries d WHERE d.AlertId=a.Id) NotifiedCount,(SELECT COUNT(DISTINCT d.UserId) FROM EmergencyNotificationDeliveries d WHERE d.AlertId=a.Id AND d.Status='SENT') DeliveredCount,(SELECT COUNT(*) FROM EmergencyNotificationDeliveries d WHERE d.AlertId=a.Id AND d.Status IN('PENDING','PROCESSING')) PendingCount,(SELECT COUNT(*) FROM EmergencyNotificationDeliveries d WHERE d.AlertId=a.Id AND d.Status IN('FAILED','UNKNOWN')) FailedCount,(SELECT COUNT(*) FROM EmergencyResponses r WHERE r.AlertId=a.Id AND r.Response='SAFE') SafeCount,(SELECT COUNT(*) FROM EmergencyResponses r WHERE r.AlertId=a.Id AND r.Response='NEED_HELP') NeedHelpCount FROM EmergencyAlerts a LEFT JOIN EmergencyResponses er ON er.AlertId=a.Id AND er.UserId=@u WHERE a.CommunityId=@c ORDER BY a.Active DESC,a.CreatedAt DESC`);const alert=alerts.recordset.find((x:any)=>x.Active)??alerts.recordset[0]??null;if(alert)alert.NoResponseCount=Math.max(0,alert.NotifiedCount-alert.SafeCount-alert.NeedHelpCount);const updates=alert?await pool.request().input('a',sql.UniqueIdentifier,alert.Id).query(`SELECT eu.*,u.FirstName,u.LastName FROM EmergencyIncidentUpdates eu JOIN Users u ON u.Id=eu.CreatedBy WHERE eu.AlertId=@a ORDER BY eu.CreatedAt DESC`):{recordset:[]};const contacts=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).query(`SELECT * FROM CommunityEmergencyContacts WHERE CommunityId=@c ORDER BY IsOfficial DESC,Name`);res.json({alert,alerts:alerts.recordset,updates:updates.recordset,contacts:contacts.recordset});}));
safetyRouter.post('/alerts/:alertId/updates',asyncHandler(async(req,res)=>{const {message}=z.object({message:z.string().min(2).max(3000)}).parse(req.body);const pool=await getPool();const a=await pool.request().input('a',sql.UniqueIdentifier,req.params.alertId).query(`SELECT CommunityId FROM EmergencyAlerts WHERE Id=@a`);if(!a.recordset[0])throw new AppError(404,'Alert not found');await requirePermission(req.user!.id,a.recordset[0].CommunityId,'EMERGENCY_MANAGE');const r=await pool.request().input('a',sql.UniqueIdentifier,req.params.alertId).input('u',sql.UniqueIdentifier,req.user!.id).input('m',sql.NVarChar(3000),message).query(`INSERT INTO EmergencyIncidentUpdates(AlertId,CreatedBy,Message) OUTPUT INSERTED.* VALUES(@a,@u,@m)`);res.status(201).json(r.recordset[0]);}));
safetyRouter.post('/alerts/:alertId/resolve',asyncHandler(async(req,res)=>{const {resolutionNote}=z.object({resolutionNote:z.string().min(2).max(2000)}).parse(req.body),pool=await getPool(),tx=new sql.Transaction(pool);await tx.begin();try{const a=(await new sql.Request(tx).input('a',sql.UniqueIdentifier,req.params.alertId).query('SELECT CommunityId,Active FROM EmergencyAlerts WITH(UPDLOCK,HOLDLOCK) WHERE Id=@a')).recordset[0];if(!a)throw new AppError(404,'Alert not found');await requirePermission(req.user!.id,a.CommunityId,'EMERGENCY_MANAGE');if(!a.Active)throw new AppError(409,'Alert already resolved');await new sql.Request(tx).input('a',sql.UniqueIdentifier,req.params.alertId).input('u',sql.UniqueIdentifier,req.user!.id).input('c',sql.UniqueIdentifier,a.CommunityId).input('n',sql.NVarChar(2000),resolutionNote).query(`UPDATE EmergencyAlerts SET Active=0,ResolvedAt=SYSUTCDATETIME(),ResolvedBy=@u,ResolutionNote=@n WHERE Id=@a AND Active=1;INSERT AuditLogs(CommunityId,UserId,Action,EntityType,EntityId) VALUES(@c,@u,'EMERGENCY_RESOLVED','EmergencyAlert',@a);`);await tx.commit();res.json({success:true})}catch(e){await tx.rollback();throw e}}));
safetyRouter.get('/trusted-contacts',asyncHandler(async(req,res)=>{const pool=await getPool();const r=await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT * FROM TrustedContacts WHERE UserId=@u ORDER BY Name`);res.json(r.recordset);}));
safetyRouter.post('/trusted-contacts',asyncHandler(async(req,res)=>{const d=z.object({name:z.string().min(2).max(160),phone:z.string().min(4).max(40),relationship:z.string().max(100).optional()}).parse(req.body);const pool=await getPool();const r=await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).input('n',sql.NVarChar(160),d.name).input('p',sql.NVarChar(40),d.phone).input('r',sql.NVarChar(100),d.relationship??null).query(`INSERT INTO TrustedContacts(UserId,Name,Phone,Relationship) OUTPUT INSERTED.* VALUES(@u,@n,@p,@r)`);res.status(201).json(r.recordset[0]);}));
safetyRouter.get('/communities/:communityId/emergency-contacts',asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).query(`SELECT * FROM CommunityEmergencyContacts WHERE CommunityId=@c ORDER BY IsOfficial DESC,Name`);res.json(r.recordset);}));
safetyRouter.post('/communities/:communityId/emergency-contacts',asyncHandler(async(req,res)=>{await requirePermission(req.user!.id,req.params.communityId,'EMERGENCY_MANAGE');const d=z.object({name:z.string().min(2).max(160),phone:z.string().min(4).max(40),contactType:z.string().max(80).optional(),isOfficial:z.boolean().default(false)}).parse(req.body);const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('n',sql.NVarChar(160),d.name).input('p',sql.NVarChar(40),d.phone).input('t',sql.NVarChar(80),d.contactType??null).input('o',sql.Bit,d.isOfficial).query(`INSERT INTO CommunityEmergencyContacts(CommunityId,Name,Phone,ContactType,IsOfficial,CreatedBy) OUTPUT INSERTED.* VALUES(@c,@n,@p,@t,@o,@u)`);res.status(201).json(r.recordset[0]);}));

safetyRouter.use(sosRouter);
for(const trusted of [false,true]){
 const route=trusted?'/trusted-contacts/:id':'/communities/:communityId/emergency-contacts/:id';
 safetyRouter.patch(route,asyncHandler(async(req,res)=>{const c=req.params.communityId;if(!trusted)await requirePermission(req.user!.id,c,'EMERGENCY_MANAGE');const d=z.object({name:z.string().trim().min(2).max(160),phone:z.string().regex(/^[+0-9() .-]{4,40}$/),contactType:z.string().max(80).optional(),relationship:z.string().max(100).optional()}).parse(req.body);const pool=await getPool(),r=await pool.request().input('id',sql.UniqueIdentifier,req.params.id).input('owner',sql.UniqueIdentifier,trusted?req.user!.id:c).input('name',sql.NVarChar(160),d.name).input('phone',sql.NVarChar(40),d.phone).input('type',sql.NVarChar(100),trusted?d.relationship||null:d.contactType||null).query(trusted?'UPDATE TrustedContacts SET Name=@name,Phone=@phone,Relationship=@type OUTPUT INSERTED.Id WHERE Id=@id AND UserId=@owner':'UPDATE CommunityEmergencyContacts SET Name=@name,Phone=@phone,ContactType=@type OUTPUT INSERTED.Id WHERE Id=@id AND CommunityId=@owner');if(!r.recordset[0])throw new AppError(404,'Contact not found');res.json({success:true})}));
 safetyRouter.delete(route,asyncHandler(async(req,res)=>{const c=req.params.communityId;if(!trusted)await requirePermission(req.user!.id,c,'EMERGENCY_MANAGE');const pool=await getPool(),r=await pool.request().input('id',sql.UniqueIdentifier,req.params.id).input('owner',sql.UniqueIdentifier,trusted?req.user!.id:c).query(trusted?'DELETE TrustedContacts OUTPUT DELETED.Id WHERE Id=@id AND UserId=@owner':'DELETE CommunityEmergencyContacts OUTPUT DELETED.Id WHERE Id=@id AND CommunityId=@owner');if(!r.recordset[0])throw new AppError(404,'Contact not found');res.json({success:true})}));
}
