import { Router } from 'express';
import { z } from 'zod';
import { getPool, sql } from '../config/db.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncHandler, AppError } from '../utils/errors.js';
import { requireCommunityMember, requirePermission } from '../services/permissions.js';
import { audit } from '../services/audit.js';
export const safetyRouter=Router(); safetyRouter.use(requireAuth);

safetyRouter.get('/communities/:communityId/emergency/dashboard',asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const pool=await getPool();const alerts=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT TOP 20 a.*,er.Response MyResponse,(SELECT COUNT(*) FROM CommunityMembers cm WHERE cm.CommunityId=a.CommunityId AND cm.Status='ACTIVE') NotifiedCount,(SELECT COUNT(*) FROM EmergencyResponses r WHERE r.AlertId=a.Id AND r.Response='SAFE') SafeCount,(SELECT COUNT(*) FROM EmergencyResponses r WHERE r.AlertId=a.Id AND r.Response='NEED_HELP') NeedHelpCount FROM EmergencyAlerts a LEFT JOIN EmergencyResponses er ON er.AlertId=a.Id AND er.UserId=@u WHERE a.CommunityId=@c ORDER BY a.Active DESC,a.CreatedAt DESC`);const alert=alerts.recordset.find((x:any)=>x.Active)??alerts.recordset[0]??null;if(alert)alert.NoResponseCount=Math.max(0,alert.NotifiedCount-alert.SafeCount-alert.NeedHelpCount);const updates=alert?await pool.request().input('a',sql.UniqueIdentifier,alert.Id).query(`SELECT eu.*,u.FirstName,u.LastName FROM EmergencyIncidentUpdates eu JOIN Users u ON u.Id=eu.CreatedBy WHERE eu.AlertId=@a ORDER BY eu.CreatedAt DESC`):{recordset:[]};const contacts=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).query(`SELECT * FROM CommunityEmergencyContacts WHERE CommunityId=@c ORDER BY IsOfficial DESC,Name`);res.json({alert,alerts:alerts.recordset,updates:updates.recordset,contacts:contacts.recordset});}));
safetyRouter.post('/alerts/:alertId/updates',asyncHandler(async(req,res)=>{const {message}=z.object({message:z.string().min(2).max(3000)}).parse(req.body);const pool=await getPool();const a=await pool.request().input('a',sql.UniqueIdentifier,req.params.alertId).query(`SELECT CommunityId FROM EmergencyAlerts WHERE Id=@a`);if(!a.recordset[0])throw new AppError(404,'Alert not found');await requirePermission(req.user!.id,a.recordset[0].CommunityId,'EMERGENCY_MANAGE');const r=await pool.request().input('a',sql.UniqueIdentifier,req.params.alertId).input('u',sql.UniqueIdentifier,req.user!.id).input('m',sql.NVarChar(3000),message).query(`INSERT INTO EmergencyIncidentUpdates(AlertId,CreatedBy,Message) OUTPUT INSERTED.* VALUES(@a,@u,@m)`);res.status(201).json(r.recordset[0]);}));
safetyRouter.post('/alerts/:alertId/resolve',asyncHandler(async(req,res)=>{const {resolutionNote}=z.object({resolutionNote:z.string().min(2).max(2000)}).parse(req.body);const pool=await getPool();const a=await pool.request().input('a',sql.UniqueIdentifier,req.params.alertId).query(`SELECT CommunityId FROM EmergencyAlerts WHERE Id=@a`);if(!a.recordset[0])throw new AppError(404,'Alert not found');await requirePermission(req.user!.id,a.recordset[0].CommunityId,'EMERGENCY_MANAGE');await pool.request().input('a',sql.UniqueIdentifier,req.params.alertId).input('u',sql.UniqueIdentifier,req.user!.id).input('n',sql.NVarChar(2000),resolutionNote).query(`UPDATE EmergencyAlerts SET Active=0,ResolvedAt=SYSUTCDATETIME(),ResolvedBy=@u,ResolutionNote=@n WHERE Id=@a`);await audit(a.recordset[0].CommunityId,req.user!.id,'EMERGENCY_RESOLVED','EmergencyAlert',req.params.alertId);res.json({success:true});}));
safetyRouter.get('/trusted-contacts',asyncHandler(async(req,res)=>{const pool=await getPool();const r=await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).query(`SELECT * FROM TrustedContacts WHERE UserId=@u ORDER BY Name`);res.json(r.recordset);}));
safetyRouter.post('/trusted-contacts',asyncHandler(async(req,res)=>{const d=z.object({name:z.string().min(2).max(160),phone:z.string().min(4).max(40),relationship:z.string().max(100).optional()}).parse(req.body);const pool=await getPool();const r=await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).input('n',sql.NVarChar(160),d.name).input('p',sql.NVarChar(40),d.phone).input('r',sql.NVarChar(100),d.relationship??null).query(`INSERT INTO TrustedContacts(UserId,Name,Phone,Relationship) OUTPUT INSERTED.* VALUES(@u,@n,@p,@r)`);res.status(201).json(r.recordset[0]);}));
safetyRouter.get('/communities/:communityId/emergency-contacts',asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).query(`SELECT * FROM CommunityEmergencyContacts WHERE CommunityId=@c ORDER BY IsOfficial DESC,Name`);res.json(r.recordset);}));
safetyRouter.post('/communities/:communityId/emergency-contacts',asyncHandler(async(req,res)=>{await requirePermission(req.user!.id,req.params.communityId,'EMERGENCY_MANAGE');const d=z.object({name:z.string().min(2).max(160),phone:z.string().min(4).max(40),contactType:z.string().max(80).optional(),isOfficial:z.boolean().default(false)}).parse(req.body);const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('n',sql.NVarChar(160),d.name).input('p',sql.NVarChar(40),d.phone).input('t',sql.NVarChar(80),d.contactType??null).input('o',sql.Bit,d.isOfficial).query(`INSERT INTO CommunityEmergencyContacts(CommunityId,Name,Phone,ContactType,IsOfficial,CreatedBy) OUTPUT INSERTED.* VALUES(@c,@n,@p,@t,@o,@u)`);res.status(201).json(r.recordset[0]);}));
safetyRouter.post('/communities/:communityId/sos',asyncHandler(async(req,res)=>{await requireCommunityMember(req.user!.id,req.params.communityId);const d=z.object({message:z.string().max(1000).optional(),approximateArea:z.string().max(250).optional()}).parse(req.body??{});const pool=await getPool();const r=await pool.request().input('c',sql.UniqueIdentifier,req.params.communityId).input('u',sql.UniqueIdentifier,req.user!.id).input('m',sql.NVarChar(1000),d.message??null).input('a',sql.NVarChar(250),d.approximateArea??null).query(`INSERT INTO SOSRequests(CommunityId,UserId,Message,ApproximateArea) OUTPUT INSERTED.* VALUES(@c,@u,@m,@a)`);await audit(req.params.communityId,req.user!.id,'SOS_REQUESTED','SOSRequest',r.recordset[0].Id);res.status(201).json(r.recordset[0]);}));
