import {Router} from 'express';
import bcrypt from 'bcryptjs';
import {z} from 'zod';
import {getPool,sql} from '../config/db.js';
import {requireAuth} from '../middleware/auth.js';
import {requirePermission,requireSystemAdmin} from '../middleware/systemAdmin.js';
import {AppError,asyncHandler} from '../utils/errors.js';

export const systemAdminRouter=Router();
systemAdminRouter.use(requireAuth,requireSystemAdmin);
const paging=z.object({page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(25),q:z.string().max(100).optional()});
const action=z.object({reason:z.string().trim().min(10).max(1000),password:z.string().min(8).max(200)});
const ip=(req:any)=>String(req.ip||req.socket?.remoteAddress||'').slice(0,80);

async function confirmPassword(userId:string,password:string){const pool=await getPool();const r=await pool.request().input('id',sql.UniqueIdentifier,userId).query('SELECT PasswordHash FROM Users WHERE Id=@id');if(!r.recordset[0]||!await bcrypt.compare(password,r.recordset[0].PasswordHash))throw new AppError(403,'Password confirmation failed')}
async function audit(req:any,code:string,type:string,target:string|null,reason:string,before:any,after:any,tx?:sql.Transaction){const request=tx?new sql.Request(tx):(await getPool()).request();await request.input('actor',sql.UniqueIdentifier,req.user.id).input('code',sql.NVarChar(100),code).input('type',sql.NVarChar(60),type).input('target',sql.NVarChar(100),target).input('reason',sql.NVarChar(1000),reason).input('before',sql.NVarChar(sql.MAX),before?JSON.stringify(before):null).input('after',sql.NVarChar(sql.MAX),after?JSON.stringify(after):null).input('ip',sql.NVarChar(80),ip(req)).input('ua',sql.NVarChar(500),String(req.headers['user-agent']||'').slice(0,500)).query(`INSERT SystemAdminAuditLogs(ActorUserId,ActionCode,TargetType,TargetId,Reason,BeforeJson,AfterJson,IpAddress,UserAgent) VALUES(@actor,@code,@type,@target,@reason,@before,@after,@ip,@ua)`)}

systemAdminRouter.get('/session',asyncHandler(async(req,res)=>res.json({role:req.systemAdmin!.role,permissions:req.systemAdmin!.permissions,isProtected:req.systemAdmin!.protected})));
systemAdminRouter.get('/overview',requirePermission('DASHBOARD_VIEW'),asyncHandler(async(_req,res)=>{const pool=await getPool();const r=await pool.request().query(`SELECT (SELECT COUNT(*) FROM Users) TotalUsers,(SELECT COUNT(*) FROM Users WHERE AccountStatus='ACTIVE') ActiveUsers,(SELECT COUNT(*) FROM Communities) Communities,(SELECT COUNT(*) FROM SystemAdminAuditLogs WHERE CreatedAt>=DATEADD(day,-1,SYSUTCDATETIME())) AdminActions24h`);res.json(r.recordset[0])}));
systemAdminRouter.get('/users',requirePermission('USER_MANAGE'),asyncHandler(async(req,res)=>{const d=paging.parse(req.query),offset=(d.page-1)*d.limit,pool=await getPool(),r=await pool.request().input('q',sql.NVarChar(110),`%${d.q||''}%`).input('offset',sql.Int,offset).input('limit',sql.Int,d.limit).query(`SELECT Id,FirstName,LastName,Email,AccountStatus,SystemRole,IsProtectedAccount,TwoFactorEnabled,CreatedAt,COUNT(*) OVER() TotalCount FROM Users WHERE @q='%%' OR Email LIKE @q OR FirstName LIKE @q OR LastName LIKE @q ORDER BY CreatedAt DESC OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`);res.json({items:r.recordset,total:r.recordset[0]?.TotalCount||0,page:d.page})}));
systemAdminRouter.post('/users/:id/status',requirePermission('USER_MANAGE'),asyncHandler(async(req,res)=>{const body=action.extend({status:z.enum(['ACTIVE','SUSPENDED','BLOCKED','DEACTIVATED'])}).parse(req.body);await confirmPassword(req.user!.id,body.password);const pool=await getPool(),tx=new sql.Transaction(pool);await tx.begin();try{const before=(await new sql.Request(tx).input('id',sql.UniqueIdentifier,req.params.id).query('SELECT Id,Email,AccountStatus,SystemRole,IsProtectedAccount FROM Users WITH(UPDLOCK) WHERE Id=@id')).recordset[0];if(!before)throw new AppError(404,'User not found');if(before.IsProtectedAccount)throw new AppError(409,'Protected Super Admin status cannot be changed');await new sql.Request(tx).input('id',sql.UniqueIdentifier,req.params.id).input('status',sql.NVarChar(30),body.status).query('UPDATE Users SET AccountStatus=@status,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id');if(body.status!=='ACTIVE')await new sql.Request(tx).input('id',sql.UniqueIdentifier,req.params.id).query('DELETE FROM UserSessions WHERE UserId=@id');await audit(req,'USER_STATUS_CHANGE','USER',req.params.id,body.reason,before,{...before,AccountStatus:body.status},tx);await tx.commit();res.json({success:true})}catch(e){await tx.rollback();throw e}}));
systemAdminRouter.post('/users/:id/role',requirePermission('ADMIN_MANAGE'),asyncHandler(async(req,res)=>{const body=action.extend({role:z.enum(['MEMBER','SYSTEM_ADMIN']),permissions:z.array(z.string().regex(/^[A-Z_]+$/)).max(30).default([])}).parse(req.body);await confirmPassword(req.user!.id,body.password);const pool=await getPool(),tx=new sql.Transaction(pool);await tx.begin();try{const before=(await new sql.Request(tx).input('id',sql.UniqueIdentifier,req.params.id).query('SELECT Id,Email,SystemRole,IsProtectedAccount FROM Users WITH(UPDLOCK) WHERE Id=@id')).recordset[0];if(!before)throw new AppError(404,'User not found');if(before.IsProtectedAccount)throw new AppError(409,'Protected Super Admin role cannot be changed');await new sql.Request(tx).input('id',sql.UniqueIdentifier,req.params.id).input('role',sql.NVarChar(30),body.role).query('UPDATE Users SET SystemRole=@role,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id; DELETE FROM SystemAdminPermissions WHERE UserId=@id');if(body.role==='SYSTEM_ADMIN')for(const p of [...new Set(body.permissions)])await new sql.Request(tx).input('id',sql.UniqueIdentifier,req.params.id).input('p',sql.NVarChar(80),p).input('actor',sql.UniqueIdentifier,req.user!.id).query('INSERT SystemAdminPermissions(UserId,PermissionCode,GrantedBy) VALUES(@id,@p,@actor)');await audit(req,'USER_ROLE_CHANGE','USER',req.params.id,body.reason,before,{SystemRole:body.role,permissions:body.permissions},tx);await tx.commit();res.json({success:true})}catch(e){await tx.rollback();throw e}}));
systemAdminRouter.post('/users/:id/revoke-sessions',requirePermission('SECURITY_VIEW'),asyncHandler(async(req,res)=>{const body=action.parse(req.body);await confirmPassword(req.user!.id,body.password);if(req.params.id===req.user!.id)throw new AppError(409,'Use the Security page to revoke your own sessions');const pool=await getPool();const r=await pool.request().input('id',sql.UniqueIdentifier,req.params.id).query('DELETE FROM UserSessions WHERE UserId=@id; SELECT @@ROWCOUNT Removed');await audit(req,'USER_SESSIONS_REVOKED','USER',req.params.id,body.reason,null,{removed:r.recordset[0]?.Removed||0});res.json({success:true,removed:r.recordset[0]?.Removed||0})}));
systemAdminRouter.get('/communities',requirePermission('COMMUNITY_MANAGE'),asyncHandler(async(req,res)=>{const d=paging.parse(req.query),pool=await getPool(),r=await pool.request().input('q',sql.NVarChar(110),`%${d.q||''}%`).input('offset',sql.Int,(d.page-1)*d.limit).input('limit',sql.Int,d.limit).query(`SELECT Id,Name,CommunityType,City,Country,IsVerified,CreatedAt,COUNT(*) OVER() TotalCount FROM Communities WHERE @q='%%' OR Name LIKE @q ORDER BY CreatedAt DESC OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`);res.json({items:r.recordset,total:r.recordset[0]?.TotalCount||0,page:d.page})}));
systemAdminRouter.get('/audit-logs',requirePermission('AUDIT_VIEW'),asyncHandler(async(req,res)=>{const d=paging.parse(req.query),pool=await getPool(),r=await pool.request().input('offset',sql.Int,(d.page-1)*d.limit).input('limit',sql.Int,d.limit).query(`SELECT a.Id,a.ActionCode,a.TargetType,a.TargetId,a.Reason,a.IpAddress,a.CreatedAt,u.Email ActorEmail,COUNT(*) OVER() TotalCount FROM SystemAdminAuditLogs a JOIN Users u ON u.Id=a.ActorUserId ORDER BY a.CreatedAt DESC OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`);res.json({items:r.recordset,total:r.recordset[0]?.TotalCount||0,page:d.page})}));
systemAdminRouter.get('/configuration',requirePermission('CONFIG_VIEW'),asyncHandler(async(_req,res)=>{const pool=await getPool();const r=await pool.request().query(`SELECT CAST(CASE WHEN COL_LENGTH('dbo.Users','SystemRole') IS NOT NULL THEN 1 ELSE 0 END AS bit) SchemaReady,CAST(CASE WHEN OBJECT_ID('dbo.SystemAdminAuditLogs','U') IS NOT NULL THEN 1 ELSE 0 END AS bit) AuditReady,(SELECT COUNT(*) FROM Users WHERE IsProtectedAccount=1 AND SystemRole='SUPER_ADMIN') ProtectedAdminCount`);res.json(r.recordset[0])}));
