import { Router } from 'express';
import { getPool, sql } from '../config/db.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncHandler } from '../utils/errors.js';
import { z } from 'zod';
export const usersRouter=Router(); usersRouter.use(requireAuth);
usersRouter.get('/me',asyncHandler(async(req,res)=>{const pool=await getPool(); const r=await pool.request().input('id',sql.UniqueIdentifier,req.user!.id).query('SELECT Id,FirstName,LastName,Email,Phone,ProfileImage,CoverImage,Country,State,LGA,Postcode,Address,DateOfBirth,CreatedAt FROM Users WHERE Id=@id');res.json(r.recordset[0]);}));
usersRouter.patch('/me',asyncHandler(async(req,res)=>{const d=z.object({firstName:z.string().min(2).max(100).optional(),lastName:z.string().min(2).max(100).optional(),phone:z.string().max(30).nullable().optional(),profileImage:z.string().url().nullable().optional(),coverImage:z.string().url().nullable().optional(),country:z.string().max(100).nullable().optional(),state:z.string().max(100).nullable().optional(),lga:z.string().max(150).nullable().optional(),postcode:z.string().max(30).nullable().optional(),address:z.string().max(500).nullable().optional(),dateOfBirth:z.coerce.date().nullable().optional()}).parse(req.body); const pool=await getPool(); await pool.request().input('id',sql.UniqueIdentifier,req.user!.id).input('f',sql.NVarChar(100),d.firstName??null).input('l',sql.NVarChar(100),d.lastName??null).input('p',sql.NVarChar(30),d.phone??null).input('img',sql.NVarChar(500),d.profileImage??null).input('cover',sql.NVarChar(1000),d.coverImage??null).input('country',sql.NVarChar(100),d.country??null).input('state',sql.NVarChar(100),d.state??null).input('lga',sql.NVarChar(150),d.lga??null).input('postcode',sql.NVarChar(30),d.postcode??null).input('address',sql.NVarChar(500),d.address??null).input('dob',sql.Date,d.dateOfBirth??null).query(`UPDATE Users SET FirstName=COALESCE(@f,FirstName),LastName=COALESCE(@l,LastName),Phone=COALESCE(@p,Phone),ProfileImage=COALESCE(@img,ProfileImage),CoverImage=COALESCE(@cover,CoverImage),Country=COALESCE(@country,Country),State=COALESCE(@state,State),LGA=COALESCE(@lga,LGA),Postcode=COALESCE(@postcode,Postcode),Address=COALESCE(@address,Address),DateOfBirth=COALESCE(@dob,DateOfBirth),UpdatedAt=SYSUTCDATETIME() WHERE Id=@id`);res.json({success:true});}));
usersRouter.post('/devices',asyncHandler(async(req,res)=>{const d=z.object({deviceToken:z.string().min(5),platform:z.enum(['ios','android']),deviceName:z.string().max(200).optional()}).parse(req.body);const pool=await getPool();await pool.request().input('u',sql.UniqueIdentifier,req.user!.id).input('t',sql.NVarChar(500),d.deviceToken).input('p',sql.NVarChar(20),d.platform).input('n',sql.NVarChar(200),d.deviceName??null).query(`MERGE UserDevices AS t USING(SELECT @u UserId,@t DeviceToken)s ON t.UserId=s.UserId AND t.DeviceToken=s.DeviceToken WHEN MATCHED THEN UPDATE SET LastActiveAt=SYSUTCDATETIME(),Platform=@p,DeviceName=@n WHEN NOT MATCHED THEN INSERT(UserId,DeviceToken,Platform,DeviceName,LastActiveAt) VALUES(@u,@t,@p,@n,SYSUTCDATETIME());`);res.status(201).json({success:true});}));
