import {useMemo,useState} from 'react';
import {Alert,Image,Pressable,Share,StyleSheet,Text,View,useWindowDimensions} from '@/platform/react-native';
import {Ionicons} from '@/platform/icons';
import {router,useLocalSearchParams} from '@/router';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Button,Card,EmptyState,Muted,Screen,useAppTheme} from '@/components/UI';
import {api} from '@/lib/api';

type Option={Id:string;OptionText:string;ImageUrl?:string;VoteCount:number;MyVote:boolean};
type Poll={Id:string;Question:string;Description?:string;ImageUrl?:string;IsAnonymous:boolean;AllowMultiple:boolean;AllowChangeVote:boolean;StartAt:string;EndAt?:string;CreatedAt:string;VoterCount:number;MemberCount:number;options:Option[]};

export default function PollDetails(){
  const{id,pollId}=useLocalSearchParams<{id:string;pollId:string}>(),{palette}=useAppTheme(),{width}=useWindowDimensions(),qc=useQueryClient();
  const[selected,setSelected]=useState<string[]>([]);
  const polls=useQuery<Poll[]>({queryKey:['polls',id],queryFn:async()=>(await api.get(`/communities/${id}/polls`)).data});
  const capabilities=useQuery<any>({queryKey:['capabilities',id],queryFn:async()=>(await api.get(`/communities/${id}/capabilities`)).data});
  const poll=useMemo(()=>polls.data?.find(item=>item.Id===pollId),[polls.data,pollId]);
  const vote=useMutation({mutationFn:(optionIds:string[])=>api.post(`/polls/${pollId}/vote`,{optionIds}),onSuccess:async()=>{setSelected([]);await qc.invalidateQueries({queryKey:['polls',id]});Alert.alert('Vote submitted','Your vote has been recorded successfully.')},onError:(e:any)=>Alert.alert('Unable to submit vote',e.response?.data?.error||e.response?.data?.message||e.message)});
  if(polls.isLoading)return <Screen contentStyle={s.page}><Muted>Loading poll details…</Muted></Screen>;
  if(!poll)return <Screen contentStyle={s.page}><EmptyState icon="alert-circle-outline" title="Poll not found" body="This poll is unavailable or has been removed."/><Button title="Back to Polls" variant="secondary" icon="arrow-back" onPress={()=>router.replace(`/community/${id}/polls` as any)}/></Screen>;
  const ended=!!poll.EndAt&&new Date(poll.EndAt).getTime()<=Date.now(),total=poll.options.reduce((n,o)=>n+Number(o.VoteCount||0),0),voters=Number(poll.VoterCount||total),hasVoted=poll.options.some(o=>o.MyVote),canChange=!hasVoted||poll.AllowChangeVote,roles:string[]=capabilities.data?.roles||[],canAnalyze=!!capabilities.data?.isOwner||roles.some(role=>['OWNER','ADMIN','MODERATOR'].includes(String(role).toUpperCase()));
  const days=poll.EndAt?Math.max(0,Math.ceil((new Date(poll.EndAt).getTime()-Date.now())/86400000)):null;
  function choose(optionId:string){if(ended||!canChange)return;if(poll!.AllowMultiple)setSelected(current=>current.includes(optionId)?current.filter(x=>x!==optionId):[...current,optionId]);else setSelected([optionId])}
  async function share(){await Share.share({title:poll!.Question,message:`${poll!.Question}${poll!.Description?`\n\n${poll!.Description}`:''}\n\nOpen CDA Connect to participate.`})}
  return <Screen scroll contentStyle={s.page}>
    <Card style={s.hero}><View style={[s.heroLayout,width<430&&s.heroStack]}><View style={s.heroCopy}><View style={[s.type,{backgroundColor:palette.successSoft}]}><Text style={{color:palette.success,fontWeight:'800'}}>{poll.AllowMultiple?'Multiple-choice Poll':'General Poll'}</Text></View><Text style={[s.question,{color:palette.text}]}>{poll.Question}</Text>{poll.Description?<Muted style={s.description}>{poll.Description}</Muted>:null}</View><View style={[s.ballot,{backgroundColor:palette.successSoft}]}>{poll.ImageUrl?<Image source={{uri:poll.ImageUrl}} resizeMode="cover" style={s.pollImage}/>:<Ionicons name={semanticIcon(poll.Question)} size={43} color={palette.success}/>}</View></View><View style={s.meta}><Meta icon="calendar-outline" text={ended?`Ended ${poll.EndAt?new Date(poll.EndAt).toLocaleDateString():''}`:days===null?'No closing date':`Ends in ${days} day${days===1?'':'s'}`} palette={palette}/><Meta icon="people-outline" text={`${voters} voter${voters===1?'':'s'}`} palette={palette}/><Meta icon="shield-checkmark-outline" text={poll.AllowMultiple?'Multiple selections allowed':'One member, one vote'} palette={palette}/>{canAnalyze?<Pressable accessibilityRole="button" accessibilityLabel="Open poll analysis" onPress={()=>router.push(`/community/${id}/poll/${pollId}/analysis` as any)} style={[s.analysisButton,{borderColor:palette.success}]}><Ionicons name="analytics-outline" size={18} color={palette.success}/><Text style={{color:palette.success,fontSize:13,fontWeight:'900'}}>Poll Analysis</Text></Pressable>:null}</View></Card>
    <View style={s.sectionHead}><Text style={[s.sectionTitle,{color:palette.text}]}>Poll Options</Text><Muted>{poll.AllowMultiple?'Select one or more options':'Select one option'}</Muted></View>
    <Card style={s.options}>{poll.options.map((option,index)=>{const count=Number(option.VoteCount||0),pct=total?Math.round(count/total*100):0,checked=selected.includes(option.Id)||(selected.length===0&&option.MyVote);return <Pressable key={option.Id} accessibilityRole="radio" accessibilityState={{selected:checked,disabled:ended||!canChange}} onPress={()=>choose(option.Id)} style={[s.option,{borderBottomColor:palette.border},index===poll.options.length-1&&{borderBottomWidth:0}]}><View style={[s.optionIcon,{backgroundColor:palette.successSoft}]}>{option.ImageUrl?<Image source={{uri:option.ImageUrl}} resizeMode="cover" style={s.optionImage}/>:<Ionicons name={semanticIcon(option.OptionText)} size={24} color={palette.success}/>}</View><View style={s.optionBody}><Text style={[s.optionTitle,{color:palette.text}]}>{option.OptionText}</Text><View style={[s.track,{backgroundColor:palette.backgroundSoft}]}><View style={[s.fill,{backgroundColor:palette.success,width:`${pct}%`}]}/></View></View><View style={s.count}><Text style={{color:palette.success,fontSize:16,fontWeight:'900'}}>{pct}%</Text><Muted>{count} vote{count===1?'':'s'}</Muted></View><Ionicons name={checked?'checkmark-circle':'ellipse-outline'} size={26} color={checked?palette.success:palette.muted}/></Pressable>})}</Card>
    <View style={[s.note,{backgroundColor:palette.successSoft,borderColor:palette.border}]}><View style={[s.noteIcon,{backgroundColor:palette.success}]}><Ionicons name="shield-checkmark-outline" size={24} color="#fff"/></View><View style={{flex:1}}><Text style={{color:palette.text,fontWeight:'900'}}>Your vote matters!</Text><Muted>{ended?'This poll has ended. The final results are shown above.':hasVoted&&!poll.AllowChangeVote?'Your vote has been recorded and cannot be changed.':'Choose your preferred option, then submit your vote.'}</Muted></View></View>
    <View style={s.actions}>{!ended&&canChange?<View style={s.actionButton}><Button title={hasVoted?'Update Your Vote':'Cast Your Vote'} icon="checkbox-outline" loading={vote.isPending} disabled={!selected.length||vote.isPending} onPress={()=>vote.mutate(selected)}/></View>:null}<View style={s.actionButton}><Button title="Share Poll" icon="share-social-outline" variant="secondary" onPress={()=>void share()}/></View></View>
  </Screen>
}

function Meta({icon,text,palette}:{icon:keyof typeof Ionicons.glyphMap;text:string;palette:any}){return <View style={s.metaItem}><Ionicons name={icon} size={17} color={palette.success}/><Text style={{color:palette.text,flexShrink:1,fontSize:13,lineHeight:18}}>{text}</Text></View>}
function semanticIcon(text:string):keyof typeof Ionicons.glyphMap{const value=text.toLowerCase();if(/wifi|internet|network/.test(value))return'wifi-outline';if(/school|training|education|skill/.test(value))return'school-outline';if(/road|street|transport/.test(value))return'trail-sign-outline';if(/market|shop|business/.test(value))return'storefront-outline';if(/park|tree|garden|environment/.test(value))return'leaf-outline';if(/health|clinic|hospital/.test(value))return'medical-outline';if(/security|safety|police/.test(value))return'shield-checkmark-outline';if(/water|drain|flood/.test(value))return'water-outline';if(/person|mr\.|mrs\.|candidate|leader/.test(value))return'person-outline';if(/date|meeting|event/.test(value))return'calendar-outline';return'options-outline'}
const s=StyleSheet.create({page:{width:'100%',maxWidth:760,alignSelf:'center',paddingTop:2,paddingBottom:112},hero:{padding:13},heroLayout:{flexDirection:'row',alignItems:'center',gap:12},heroStack:{alignItems:'center'},heroCopy:{flex:1,minWidth:0},type:{alignSelf:'flex-start',paddingHorizontal:10,paddingVertical:4,borderRadius:999},question:{fontSize:21,lineHeight:27,fontWeight:'900',marginTop:9},description:{fontSize:14,lineHeight:20,marginTop:6},ballot:{width:82,height:82,borderRadius:41,overflow:'hidden',flexShrink:0,alignItems:'center',justifyContent:'center'},pollImage:{width:'100%',height:'100%'},meta:{flexDirection:'row',flexWrap:'wrap',alignItems:'flex-start',columnGap:10,rowGap:7,marginTop:13},metaItem:{flexGrow:1,flexShrink:1,minWidth:120,flexDirection:'row',alignItems:'flex-start',gap:4},analysisButton:{minHeight:36,borderWidth:1,borderRadius:10,paddingHorizontal:10,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:5,flexGrow:1},sectionHead:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',justifyContent:'space-between',gap:6,marginTop:3,marginBottom:7},sectionTitle:{fontSize:18,fontWeight:'900'},options:{padding:0,overflow:'hidden'},option:{minHeight:82,flexDirection:'row',alignItems:'center',gap:9,paddingHorizontal:11,paddingVertical:9,borderBottomWidth:1},optionIcon:{width:44,height:44,borderRadius:12,alignItems:'center',justifyContent:'center',flexShrink:0,overflow:'hidden'},optionImage:{width:'100%',height:'100%'},optionBody:{flex:1,minWidth:72},optionTitle:{fontSize:15,fontWeight:'900',marginBottom:7},track:{height:7,borderRadius:5,overflow:'hidden'},fill:{height:'100%',borderRadius:5},count:{width:55,alignItems:'center',flexShrink:0},note:{borderWidth:1,borderRadius:13,padding:12,flexDirection:'row',alignItems:'center',gap:10,marginVertical:7},noteIcon:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center'},actions:{flexDirection:'row',alignItems:'stretch',gap:10},actionButton:{flex:1,minWidth:0}});
