import {Alert,Image,Linking,Pressable,Share,StyleSheet,Text,View} from '@/platform/react-native';
import {router,useLocalSearchParams} from '@/router';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Ionicons} from '@/platform/icons';
import {api} from '@/lib/api';
import {Avatar,Badge,Card,EmptyState,Muted,Screen,useAppTheme} from '@/components/UI';
import {LinkText} from '@/components/LinkText';

type MemberProfile={MembershipId:string;UserId:string;FirstName:string;LastName:string;ProfileImage?:string;Email?:string;Phone?:string;Country?:string;State?:string;LGA?:string;Postcode?:string;Address?:string;JoinedAt?:string;MembershipStatus:string;CommunityName:string;Roles?:string};
type Post={Id:string;Body?:string;PostType:string;MediaUrl?:string;MediaType?:string;DocumentName?:string;Caption?:string;CreatedAt:string;FirstName:string;LastName:string;ProfileImage?:string;ReactionCount:number;CommentCount:number;ShareCount:number;MyReaction?:string;MySaved:boolean;IsPinned:boolean;IsAnnouncement:boolean};

export default function MemberProfilePage(){
 const{id,membershipId}=useLocalSearchParams<{id:string;membershipId:string}>();const{palette}=useAppTheme();const qc=useQueryClient();
 const query=useQuery<MemberProfile>({queryKey:['member-profile',id,membershipId],enabled:!!id&&!!membershipId,queryFn:async()=>(await api.get(`/communities/${id}/members/${membershipId}`)).data});
 const posts=useQuery<Post[]>({queryKey:['member-posts',id,membershipId],enabled:!!id&&!!membershipId,queryFn:async()=>(await api.get(`/communities/${id}/members/${membershipId}/posts`)).data});
 const refresh=()=>qc.invalidateQueries({queryKey:['member-posts',id,membershipId]});
 const react=useMutation({mutationFn:({postId,reaction}:{postId:string;reaction:string|null})=>api.post(`/posts/${postId}/reaction`,{reaction}),onSuccess:refresh,onError:()=>Alert.alert('Action failed','The reaction could not be updated.')});
 const save=useMutation({mutationFn:(postId:string)=>api.post(`/posts/${postId}/save`),onSuccess:refresh,onError:()=>Alert.alert('Action failed','The saved status could not be updated.')});
 const share=async(post:Post)=>{try{await api.post(`/posts/${post.Id}/share`);await Share.share({message:`${post.FirstName} ${post.LastName} on CDA Connect:\n\n${post.Body||post.Caption||'Community post'}`});refresh()}catch{Alert.alert('Unable to share','Please try again.')}};
 const member=query.data;if(!member)return <Screen>{query.isError?<EmptyState icon="person-circle-outline" title="Profile unavailable" body="This member profile could not be loaded or is no longer available."/>:<Muted>Loading member profile…</Muted>}</Screen>;
 const name=`${member.FirstName} ${member.LastName}`.trim(),location=[member.LGA,member.State,member.Country].filter(Boolean).join(', '),roles=String(member.Roles||'Member').split(',').map(x=>x.trim()).filter(Boolean);
 return <Screen scroll contentStyle={s.page}>
  <Card style={s.identity}><Avatar name={name} uri={member.ProfileImage} size={82}/><View style={s.identityCopy}><Text style={[s.name,{color:palette.text}]}>{name}</Text><View style={s.badges}>{roles.map(role=><Badge key={role} text={role} tone={/Owner|Admin/.test(role)?'green':role==='Moderator'?'blue':'gray'}/>)}</View><Text style={[s.community,{color:palette.text}]}>{member.CommunityName}</Text>{location?<Muted><Ionicons name="location-outline" size={14}/> {location}</Muted>:null}</View></Card>
  <View style={s.summary}><Summary icon="shield-checkmark-outline" label="Status" value={member.MembershipStatus==='ACTIVE'?'Active member':member.MembershipStatus} palette={palette}/><Summary icon="calendar-outline" label="Member since" value={member.JoinedAt?new Date(member.JoinedAt).toLocaleDateString([], {month:'short',year:'numeric'}):'Not available'} palette={palette}/></View>
  <View style={s.sectionHead}><Text style={[s.sectionTitle,{color:palette.text}]}>Posts</Text>{posts.data?.length?<Muted>{posts.data.length} {posts.data.length===1?'post':'posts'}</Muted>:null}</View>
  {posts.isLoading?<Muted style={s.loading}>Loading posts…</Muted>:posts.isError?<EmptyState icon="newspaper-outline" title="Posts unavailable" body="This member’s posts could not be loaded."/>:posts.data?.length?posts.data.map(post=><Card key={post.Id} style={s.post}><Pressable accessibilityRole="button" accessibilityLabel="Open post" onPress={()=>router.push(`/community/${id}/post/${post.Id}` as any)}><View style={s.postHead}><Avatar name={name} uri={post.ProfileImage} size={42}/><View style={s.postAuthor}><Text style={[s.author,{color:palette.text}]}>{name}</Text><Muted>{new Date(post.CreatedAt).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}</Muted></View>{post.IsPinned?<Ionicons name="pin" size={17} color={palette.primary}/>:null}</View>{post.Body?<LinkText style={[s.postBody,{color:palette.text}]}>{post.Body}</LinkText>:null}{post.MediaUrl&&post.PostType==='PHOTO'?<Image source={{uri:post.MediaUrl}} style={s.media} resizeMode="cover"/>:null}{post.MediaUrl&&post.PostType!=='PHOTO'?<Pressable accessibilityRole="link" accessibilityLabel={`Open ${post.DocumentName||post.PostType.toLowerCase()}`} onPress={()=>Linking.openURL(post.MediaUrl!)} style={[s.attachment,{borderColor:palette.border}]}><Ionicons name="attach-outline" size={20} color={palette.primary}/><Text numberOfLines={1} style={[s.attachmentText,{color:palette.text}]}>{post.DocumentName||post.Caption||`Open ${post.PostType.toLowerCase()}`}</Text></Pressable>:null}</Pressable><View style={[s.postStats,{borderBottomColor:palette.border}]}><Muted>{post.ReactionCount} reactions · {post.CommentCount} comments · {post.ShareCount} shares</Muted></View><View style={s.actions}><PostAction icon={post.MyReaction?'thumbs-up':'thumbs-up-outline'} label="Like" active={!!post.MyReaction} palette={palette} onPress={()=>react.mutate({postId:post.Id,reaction:post.MyReaction?null:'LIKE'})}/><PostAction icon="chatbubble-outline" label="Comment" palette={palette} onPress={()=>router.push(`/community/${id}/post/${post.Id}` as any)}/><PostAction icon="share-social-outline" label="Share" palette={palette} onPress={()=>void share(post)}/><PostAction icon={post.MySaved?'bookmark':'bookmark-outline'} label="Save" active={!!post.MySaved} palette={palette} onPress={()=>save.mutate(post.Id)}/></View></Card>):<EmptyState icon="newspaper-outline" title="No posts yet" body={`${member.FirstName} has not posted in this community yet.`}/>} 
 </Screen>
}

function Summary({icon,label,value,palette}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:string;palette:any}){return <Card style={s.summaryCard}><Ionicons name={icon} size={21} color={palette.primary}/><View style={{flex:1}}><Muted>{label}</Muted><Text style={[s.summaryValue,{color:palette.text}]}>{value}</Text></View></Card>}
function PostAction({icon,label,active,palette,onPress}:{icon:keyof typeof Ionicons.glyphMap;label:string;active?:boolean;palette:any;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={s.action}><Ionicons name={icon} size={19} color={active?palette.primary:palette.muted}/><Text style={{color:active?palette.primary:palette.muted,fontWeight:'700',fontSize:12}}>{label}</Text></Pressable>}

const s=StyleSheet.create({page:{width:'100%',maxWidth:720,alignSelf:'center',paddingBottom:125},identity:{flexDirection:'row',alignItems:'center',paddingVertical:18,gap:15},identityCopy:{flex:1,minWidth:0,gap:5},name:{fontSize:22,fontWeight:'900',lineHeight:27},community:{fontSize:14,fontWeight:'800'},badges:{flexDirection:'row',flexWrap:'wrap',gap:6},summary:{flexDirection:'row',gap:10},summaryCard:{flex:1,minWidth:0,flexDirection:'row',alignItems:'center',gap:9,paddingVertical:13},summaryValue:{fontSize:13,fontWeight:'900',marginTop:2},sectionTitle:{fontSize:18,fontWeight:'900',marginTop:4},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:5},loading:{textAlign:'center',paddingVertical:24},post:{paddingBottom:0,overflow:'hidden'},postHead:{flexDirection:'row',alignItems:'center',gap:10},postAuthor:{flex:1,minWidth:0},author:{fontSize:15,fontWeight:'900'},postBody:{fontSize:15,lineHeight:22,marginTop:13},media:{width:'100%',aspectRatio:1.6,borderRadius:12,marginTop:12},attachment:{minHeight:48,borderWidth:1,borderRadius:11,marginTop:12,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8},attachmentText:{flex:1,fontWeight:'800'},postStats:{paddingVertical:11,borderBottomWidth:1},actions:{flexDirection:'row',marginHorizontal:-8},action:{flex:1,minHeight:47,alignItems:'center',justifyContent:'center',gap:3}});
