import {useEffect,useState} from 'react';
import {Alert,Pressable,Share,StyleSheet,Switch,Text,View} from 'react-native';
import {useQuery} from '@tanstack/react-query';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {useAuth} from '@/store/auth';
import {Avatar,Card,Muted,Screen,useAppTheme} from '@/components/UI';

type Prefs={privateAccount:boolean;showOnline:boolean;allowFollow:boolean;emailUpdates:boolean;personalized:boolean};
const initialPrefs:Prefs={privateAccount:false,showOnline:true,allowFollow:true,emailUpdates:true,personalized:true};

export default function Profile(){
 const{user,logout}=useAuth(),{palette}=useAppTheme();const[prefs,setPrefs]=useState(initialPrefs),[raw,setRaw]=useState<any>({}),[saving,setSaving]=useState('');const communities=useQuery<any[]>({queryKey:['communities'],queryFn:async()=>(await api.get('/communities')).data}),activity=useQuery<any[]>({queryKey:['personal-activity'],queryFn:async()=>(await api.get('/me/activity')).data});
 const groups=communities.data||[],items=activity.data||[],name=`${user?.FirstName||''} ${user?.LastName||''}`.trim()||'Community Member',username=String(user?.Email||'member').split('@')[0],location=[user?.LGA,user?.State,user?.Country].filter(Boolean).join(', ')||'Location not added',since=user?.CreatedAt?new Date(user.CreatedAt).toLocaleDateString(undefined,{month:'short',year:'numeric'}):'Not available',dob=user?.DateOfBirth?new Date(user.DateOfBirth).toLocaleDateString(undefined,{day:'2-digit',month:'long',year:'numeric'}):'Date of birth not added';
 const comments=items.reduce((n,x)=>n+Number(x.CommentCount||0),0),events=items.filter(x=>String(x.ItemType||'').toUpperCase()==='EVENT').length;
 const membership=()=>groups[0]?.Id?router.push(`/community/${groups[0].Id}/membership-card` as any):Alert.alert('Member card unavailable','Join a community before opening your membership QR code.');
 useEffect(()=>{api.get('/me/preferences').then(r=>{const p=r.data||{},privacy=p.privacy||{},notifications=p.notifications||{},app=p.app||{};setRaw(p);setPrefs({privateAccount:privacy.PhoneVisibility==='NOBODY'&&privacy.EmailVisibility==='NOBODY',showOnline:privacy.ShowOnlineStatus??true,allowFollow:privacy.AllowCommunityDiscovery??true,emailUpdates:(notifications.CommunityPosts||'DAILY')!=='OFF',personalized:!(app.DataSaverEnabled??false)})}).catch(()=>{})},[]);
 async function toggle(key:keyof Prefs,value:boolean){const previous=prefs,next={...prefs,[key]:value};setPrefs(next);setSaving(key);try{if(['privateAccount','showOnline','allowFollow'].includes(key)){const p=raw.privacy||{};await api.put('/me/privacy-preferences',{phoneVisibility:next.privateAccount?'NOBODY':p.PhoneVisibility||'ADMINS',emailVisibility:next.privateAccount?'NOBODY':p.EmailVisibility||'ADMINS',whoCanMessage:p.WhoCanMessage||'MEMBERS',whoCanAddToGroups:p.WhoCanAddToGroups||'MEMBERS',showOnlineStatus:next.showOnline,showProfilePhoto:p.ShowProfilePhoto??true,allowCommunityDiscovery:next.allowFollow})}else if(key==='emailUpdates'){const n=raw.notifications||{};await api.put('/me/notification-preferences',{emergencyAlerts:'ALWAYS',directMessages:n.DirectMessages||'ON',mentions:n.Mentions||'ON',communityPosts:value?'DAILY':'OFF',polls:n.Polls||'ON',events:n.Events||'ON',marketplace:n.Marketplace||'OFF',businessPromotions:n.BusinessPromotions||'OFF',quietHoursEnabled:!!n.QuietHoursEnabled,quietStart:n.QuietStart?String(n.QuietStart).slice(0,5):undefined,quietEnd:n.QuietEnd?String(n.QuietEnd).slice(0,5):undefined})}else{const a=raw.app||{};await api.put('/me/app-preferences',{dataSaverEnabled:!value,offlineCacheEnabled:a.OfflineCacheEnabled??true,autoDownloadImages:a.AutoDownloadImages??true,autoDownloadVideos:a.AutoDownloadVideos??false})}const refreshed=(await api.get('/me/preferences')).data;setRaw(refreshed)}catch(e:any){setPrefs(previous);Alert.alert('Unable to save preference',e.response?.data?.error||e.message)}finally{setSaving('')}}
 const confirmLogout=()=>Alert.alert('Log out','Are you sure you want to log out of CDA Connect?',[{text:'Cancel',style:'cancel'},{text:'Log out',style:'destructive',onPress:()=>void logout()}]);
 return <Screen scroll contentStyle={s.page}>
  <View style={s.identity}><View><Avatar name={name} uri={user?.ProfileImage} size={126}/><Pressable onPress={()=>router.push('/profile-edit')} style={[s.camera,{backgroundColor:palette.surface,borderColor:palette.border}]}><Ionicons name="camera-outline" size={20} color={palette.text}/></Pressable></View><Text style={[s.name,{color:palette.text}]}>{name} <Ionicons name="checkmark-circle" size={20} color={palette.primary}/></Text><Muted>@{username}　|　Member since {since}</Muted><View style={[s.active,{backgroundColor:palette.primarySoft}]}><View style={s.dot}/><Text style={{color:palette.primary,fontWeight:'800'}}>Active Member</Text></View></View>
  <Card style={s.actions}><Action icon="person-outline" label="Edit Profile" onPress={()=>router.push('/profile-edit')}/><Action icon="qr-code-outline" label="QR Code" onPress={membership}/><Action icon="share-outline" label="Share Profile" onPress={()=>void Share.share({message:`Connect with ${name} on CDA Connect.`})}/><Action icon="person-add-outline" label="Invite Friends" onPress={()=>void Share.share({message:'Join me on CDA Connect and connect with your local community.'})}/></Card>
  <Card style={s.stats}><Stat icon="people-outline" value={groups.length} label="Groups" color={palette.primary}/><Stat icon="newspaper-outline" value={items.length} label="Posts" color={palette.navy}/><Stat icon="chatbubble-ellipses-outline" value={comments} label="Comments" color={palette.primaryDark}/><Stat icon="calendar-outline" value={events} label="Events" color={palette.primary}/></Card>
  <Card style={s.infoCard}><Info icon="location-outline" text={location}/><Info icon="home-outline" text={user?.Address||'Address not added'}/>{user?.Postcode?<Info icon="navigate-outline" text={user.Postcode}/>:null}<Info icon="calendar-outline" text={dob}/><Info icon="mail-outline" text={user?.Email||'Email not added'}/><Info icon="call-outline" text={user?.Phone||'Phone not added'}/><Info icon="business-outline" text={user?.LGA?`${user.LGA} LGA`:'LGA not added'}/></Card>
  <View style={s.sectionHead}><Text style={[s.sectionTitle,{color:palette.text}]}>My Communities</Text><Pressable onPress={()=>router.push('/(tabs)/communities')}><Text style={s.link}>View all</Text></Pressable></View><View style={s.chips}>{groups.slice(0,6).map(g=><Pressable key={g.Id} onPress={()=>router.push(`/community/${g.Id}/feed` as any)} style={[s.chip,{backgroundColor:palette.primarySoft}]}><Text style={{color:palette.primary,fontWeight:'800'}}>{g.Name}</Text></Pressable>)}</View>
  <SettingsSection label="Account Preferences" palette={palette}><PreferenceToggle icon="shield-checkmark-outline" title="Private Account" body="Only approved members can see your profile information" value={prefs.privateAccount} change={v=>toggle('privateAccount',v)} disabled={saving==='privateAccount'} palette={palette}/><PreferenceToggle icon="eye-outline" title="Show Online Status" body="Let permitted members see when you’re online" value={prefs.showOnline} change={v=>toggle('showOnline',v)} disabled={saving==='showOnline'} palette={palette}/><PreferenceToggle icon="people-outline" title="Allow People to Follow You" body="Let others follow your activities and updates" value={prefs.allowFollow} change={v=>toggle('allowFollow',v)} disabled={saving==='allowFollow'} palette={palette}/><PreferenceToggle icon="mail-outline" title="Email Updates" body="Receive important community updates via email" value={prefs.emailUpdates} change={v=>toggle('emailUpdates',v)} disabled={saving==='emailUpdates'} palette={palette}/><PreferenceToggle icon="stats-chart-outline" title="Personalized Experience" body="Use your preferences to personalize your experience" value={prefs.personalized} change={v=>toggle('personalized',v)} disabled={saving==='personalized'} palette={palette}/></SettingsSection>
  <SettingsSection label="Account Management" palette={palette}><ManagementRow icon="key-outline" title="Change Password" body="Update your password securely" tone={palette.navy} onPress={()=>router.push('/change-password' as any)} palette={palette}/><ManagementRow icon="download-outline" title="Download My Data" body="Download a copy of your account data" tone={palette.primaryDark} onPress={()=>router.push('/data-usage')} palette={palette}/></SettingsSection>
  <Pressable accessibilityRole="button" accessibilityLabel="Log out" onPress={confirmLogout} style={[s.logout,{borderColor:palette.danger,backgroundColor:palette.dangerSoft}]}><Ionicons name="log-out-outline" size={24} color={palette.danger}/><Text style={[s.logoutText,{color:palette.danger}]}>Log out</Text></Pressable>
 </Screen>
}
function Action({icon,label,onPress}:{icon:any;label:string;onPress:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={onPress} style={s.action}><Ionicons name={icon} size={25} color={palette.primary}/><Text style={[s.actionLabel,{color:palette.text}]}>{label}</Text></Pressable>}
function Stat({icon,value,label,color}:{icon:any;value:number;label:string;color:string}){const{palette}=useAppTheme();return <View style={[s.stat,{borderRightColor:palette.border}]}><Ionicons name={icon} size={25} color={color}/><Text style={[s.statValue,{color:palette.text}]}>{value}</Text><Muted>{label}</Muted></View>}
function Info({icon,text}:{icon:any;text:string}){const{palette}=useAppTheme();return <View style={[s.info,{borderBottomColor:palette.border}]}><Ionicons name={icon} size={21} color={palette.primary}/><Text style={[s.infoText,{color:palette.text}]} numberOfLines={1}>{text}</Text></View>}
function SettingsSection({label,children,palette}:{label:string;children:any;palette:any}){return <View><Text style={[s.settingsLabel,{color:palette.text}]}>{label}</Text><View style={[s.settingsSection,{borderColor:palette.border,backgroundColor:palette.surface}]}>{children}</View></View>}
function PreferenceToggle({icon,title,body,value,change,disabled,palette}:{icon:any;title:string;body:string;value:boolean;change:(value:boolean)=>void;disabled:boolean;palette:any}){return <View style={[s.settingsRow,{borderBottomColor:palette.border}]}><View style={[s.settingsIcon,{backgroundColor:palette.primarySoft}]}><Ionicons name={icon} size={24} color={palette.primary}/></View><View style={{flex:1}}><Text style={[s.settingsTitle,{color:palette.text}]}>{title}</Text><Muted>{body}</Muted></View><Switch disabled={disabled} value={value} onValueChange={change} trackColor={{false:palette.border,true:palette.primary}} thumbColor="#fff"/></View>}
function ManagementRow({icon,title,body,onPress,palette,tone}:{icon:any;title:string;body:string;onPress:()=>void;palette:any;tone:string}){return <Pressable onPress={onPress} style={[s.settingsRow,{borderBottomColor:palette.border}]}><View style={[s.settingsIcon,{backgroundColor:`${tone}16`}]}><Ionicons name={icon} size={24} color={tone}/></View><View style={{flex:1}}><Text style={[s.settingsTitle,{color:palette.text}]}>{title}</Text><Muted numberOfLines={1}>{body}</Muted></View><Ionicons name="chevron-forward" size={20} color={palette.text}/></Pressable>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:920,alignSelf:'center',paddingTop:22,paddingBottom:26},header:{minHeight:80,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{flexDirection:'row',alignItems:'center',gap:8},logo:{width:58,height:58,resizeMode:'contain'},brandName:{fontSize:19,fontWeight:'900'},tagline:{fontSize:9},headerRight:{flexDirection:'row',alignItems:'center',gap:15},identity:{alignItems:'center',gap:7},camera:{position:'absolute',right:0,bottom:2,width:38,height:38,borderRadius:19,borderWidth:1,alignItems:'center',justifyContent:'center'},name:{fontSize:27,fontWeight:'900'},active:{marginTop:5,paddingHorizontal:16,paddingVertical:8,borderRadius:20,flexDirection:'row',alignItems:'center',gap:8},dot:{width:8,height:8,borderRadius:4,backgroundColor:'#0F8A43'},actions:{marginTop:14,flexDirection:'row',paddingVertical:12,paddingHorizontal:5},action:{flex:1,alignItems:'center',gap:7},actionLabel:{fontSize:10,fontWeight:'700',textAlign:'center'},stats:{flexDirection:'row',paddingHorizontal:4},stat:{flex:1,alignItems:'center',borderRightWidth:1,gap:4},statValue:{fontSize:20,fontWeight:'900'},sectionTitle:{fontSize:18,fontWeight:'900'},link:{color:'#0F8A43',fontWeight:'900',marginTop:8},infoCard:{paddingVertical:2},info:{minHeight:52,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1},infoText:{flex:1},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:12,marginBottom:9},chips:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:10},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:18},settingsLabel:{fontSize:16,fontWeight:'900',marginTop:24,marginBottom:10,marginLeft:12},settingsSection:{borderWidth:1,borderRadius:14,overflow:'hidden'},settingsRow:{minHeight:78,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:14,borderBottomWidth:1},settingsIcon:{width:48,height:48,borderRadius:24,alignItems:'center',justifyContent:'center'},settingsTitle:{fontSize:15,fontWeight:'900',marginBottom:3},logout:{minHeight:56,borderWidth:1.5,borderRadius:15,marginTop:22,marginBottom:18,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},logoutText:{fontSize:16,fontWeight:'900'}});
