import {Alert,Platform,Pressable,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {useAuth} from '@/store/auth';
import {Avatar,Button,Card,Muted,Screen,useAppTheme} from '@/components/UI';

const options=[
 ['person-outline','Account Settings','Personal information and preferences','/account-settings','green'],
 ['lock-closed-outline','Privacy & Safety','Manage your privacy and safety','/privacy','green'],
 ['notifications-outline','Notifications','Control your notifications','/notifications-settings','blue'],
 ['sunny-outline','Appearance','Theme, display and accessibility','/accessibility','orange'],
 ['language-outline','Language','App language and translations','/language','blue'],
 ['chatbox-outline','Communications','Email, SMS and messaging','/communications','cyan'],
 ['options-outline','Community Preferences','Your community discovery experience','/community-preferences','green'],
 ['server-outline','Data & Storage','Manage offline data and storage','/data-usage','blue'],
 ['shield-checkmark-outline','Security','Password, privacy and account access','/security','green'],
 ['help-circle-outline','Help & Support','Get help and contact support','/help','gray'],
 ['information-circle-outline','About CDA Connect','App version and information','/about','gray'],
] as const;

export default function Settings(){
 const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=900;const{user,logout}=useAuth();const name=`${user?.FirstName||''} ${user?.LastName||''}`.trim()||'Community Member';
 const open=(path:string)=>router.push(path as any);
 const removeAccount=()=>Alert.alert('Delete account?','This submits an irreversible account deletion request. Your account is not removed until the request is processed.',[{text:'Cancel',style:'cancel'},{text:'Request deletion',style:'destructive',onPress:async()=>{try{await api.post('/me/delete-account-request');Alert.alert('Request submitted','Your deletion request has been recorded.')}catch(e:any){Alert.alert('Unable to submit request',e.response?.data?.error||e.message)}}}]);
 return <Screen scroll contentStyle={styles.page}>
  <View style={styles.heading}><Text style={[styles.title,{color:palette.text}]}>Settings</Text><Muted>Manage your account, preferences and community experience.</Muted></View>
  {!desktop?<Card style={styles.mobileProfile}><Avatar name={name} size={66}/><View style={{flex:1}}><Text style={[styles.profileName,{color:palette.text}]}>{name}</Text><Muted>{user?.Email}</Muted><Button title="Edit Profile" variant="secondary" onPress={()=>open('/profile-edit')}/></View></Card>:null}
  <View style={[styles.layout,!desktop&&styles.stack]}>
   {desktop?<Card style={styles.sidebar}>{options.map(([icon,label,,path],index)=><Pressable key={label} onPress={()=>open(path)} style={[styles.sideRow,index===0&&{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={20} color={index===0?palette.success:palette.navy}/><Text style={{color:index===0?palette.success:palette.text,fontWeight:'800'}}>{label}</Text></Pressable>)}</Card>:null}
   <View style={{flex:1,width:'100%'}}>
    {desktop?<Card style={styles.account}><View style={styles.accountHead}><View><Text style={[styles.sectionTitle,{color:palette.text}]}>Account Settings</Text><Muted>Manage your personal information and account preferences.</Muted></View><Button title="Edit Profile" variant="secondary" onPress={()=>open('/profile-edit')}/></View><View style={styles.identity}><Avatar name={name} size={76}/><View style={{flex:1}}><Text style={[styles.profileName,{color:palette.text}]}>{name} <Ionicons name="checkmark-circle" size={17} color={palette.success}/></Text><Muted>{user?.Email}</Muted><Muted>{user?.Phone||'Phone number not added'}</Muted></View></View><Detail label="Full Name" value={name} onPress={()=>open('/profile-edit')}/><Detail label="Email" value={user?.Email||'Not added'} onPress={()=>open('/profile-edit')}/><Detail label="Phone Number" value={user?.Phone||'Not added'} onPress={()=>open('/profile-edit')}/><Detail label="Location" value={[(user as any)?.City,(user as any)?.State,(user as any)?.Country].filter(Boolean).join(', ')||'Not added'} onPress={()=>open('/profile-edit')}/></Card>:<Card style={styles.mobileMenu}>{options.map(([icon,label,help,path,tone])=><Pressable accessibilityRole="button" accessibilityLabel={label} key={label} onPress={()=>open(path)} style={[styles.row,{borderBottomColor:palette.border}]}><View style={[styles.rowIcon,{backgroundColor:tone==='orange'?palette.warningSoft:tone==='blue'?palette.primarySoft:tone==='cyan'?'#E0F7FA':tone==='gray'?palette.background:palette.successSoft}]}><Ionicons name={icon} size={21} color={tone==='orange'?palette.warning:tone==='blue'?palette.primary:tone==='cyan'?palette.cyan:tone==='gray'?palette.muted:palette.success}/></View><View style={{flex:1}}><Text style={[styles.rowLabel,{color:palette.text}]}>{label}</Text><Muted>{help}</Muted></View><Ionicons name="chevron-forward" size={19} color={palette.muted}/></Pressable>)}</Card>}
    <Text style={[styles.quickTitle,{color:palette.text}]}>Quick Settings</Text><View style={[styles.quickGrid,!desktop&&styles.quickStack]}>{options.slice(1,6).map(([icon,label,help,path,tone])=><Pressable key={label} onPress={()=>open(path)} style={[styles.quick,{backgroundColor:palette.surface,borderColor:palette.border}]}><View style={[styles.rowIcon,{backgroundColor:tone==='orange'?palette.warningSoft:palette.successSoft}]}><Ionicons name={icon} size={22} color={tone==='orange'?palette.warning:palette.success}/></View><Text style={[styles.quickLabel,{color:palette.text}]}>{label}</Text><Muted>{help}</Muted></Pressable>)}</View>
    <Card style={[styles.danger,{backgroundColor:palette.dangerSoft,borderColor:palette.danger}]}><View style={{flex:1}}><Text style={[styles.dangerTitle,{color:palette.danger}]}>Danger Zone</Text><Muted>Account deletion requests are reviewed before data is removed.</Muted></View><Button title="Delete Account" variant="danger" onPress={removeAccount}/></Card>
    <Pressable onPress={async()=>{await logout();router.replace('/(auth)/welcome')}} style={[styles.logout,{borderColor:palette.border}]}><Ionicons name="log-out-outline" size={21} color={palette.danger}/><Text style={{color:palette.danger,fontWeight:'900'}}>Log out</Text></Pressable>
   </View>
  </View>
 </Screen>
}

function Detail({label,value,onPress}:{label:string;value:string;onPress:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={onPress} style={[styles.detail,{borderTopColor:palette.border}]}><Text style={[styles.detailLabel,{color:palette.text}]}>{label}</Text><Muted style={{flex:1,textAlign:'right'}}>{value}</Muted><Ionicons name="chevron-forward" size={18} color={palette.muted}/></Pressable>}

const styles=StyleSheet.create({page:{width:'100%',maxWidth:1220,alignSelf:'center'},heading:{marginBottom:20},title:{fontSize:28,fontWeight:'900',marginBottom:5},layout:{flexDirection:'row',gap:18,alignItems:'flex-start'},stack:{flexDirection:'column'},sidebar:{width:270,padding:13},sideRow:{minHeight:52,borderRadius:11,flexDirection:'row',alignItems:'center',gap:11,paddingHorizontal:12},account:{padding:22},accountHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:14,marginBottom:20},sectionTitle:{fontSize:20,fontWeight:'900',marginBottom:4},identity:{flexDirection:'row',alignItems:'center',gap:16,marginBottom:18},profileName:{fontSize:18,fontWeight:'900',marginBottom:4},detail:{minHeight:58,borderTopWidth:1,flexDirection:'row',alignItems:'center',gap:12},detailLabel:{fontWeight:'800',minWidth:120},mobileProfile:{flexDirection:'row',alignItems:'center',gap:14},mobileMenu:{padding:0,overflow:'hidden'},row:{minHeight:72,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:14,borderBottomWidth:1},rowIcon:{width:42,height:42,borderRadius:12,alignItems:'center',justifyContent:'center'},rowLabel:{fontWeight:'900',marginBottom:2},quickTitle:{fontSize:19,fontWeight:'900',marginTop:20,marginBottom:12},quickGrid:{flexDirection:'row',gap:10},quickStack:{flexWrap:'wrap'},quick:{flex:1,minWidth:145,minHeight:140,borderWidth:1,borderRadius:15,padding:14},quickLabel:{fontWeight:'900',marginTop:12,marginBottom:5},danger:{flexDirection:'row',alignItems:'center',gap:16,borderWidth:1,marginTop:20},dangerTitle:{fontSize:17,fontWeight:'900',marginBottom:3},logout:{height:52,borderWidth:1,borderRadius:12,marginTop:12,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8}});
