import { useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, router } from 'expo-router';
import { useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { api } from '@/lib/api';
import { Button, Card, Header, Input, Muted, Screen } from '@/components/UI';
import { colors } from '@/theme';

type Mode='announcement'|'meeting'|'poll'|'alert'|'group';
const tiles:{key:Mode;label:string;icon:keyof typeof Ionicons.glyphMap;tone:string;bg:string}[]=[
 {key:'group',label:'Manage Members',icon:'people',tone:colors.navy,bg:colors.background},
 {key:'group',label:'Join Requests',icon:'person-add',tone:colors.green,bg:colors.successSoft},
 {key:'announcement',label:'Announcements',icon:'megaphone',tone:colors.green,bg:colors.successSoft},
 {key:'meeting',label:'Meetings',icon:'calendar',tone:colors.navy,bg:colors.background},
 {key:'poll',label:'Polls & Voting',icon:'stats-chart',tone:colors.green,bg:colors.successSoft},
 {key:'alert',label:'Emergency Alerts',icon:'notifications',tone:colors.red,bg:colors.dangerSoft},
 {key:'group',label:'Emergency Command',icon:'shield',tone:colors.red,bg:colors.dangerSoft},
 {key:'group',label:'Community Verification',icon:'shield-checkmark',tone:colors.green,bg:colors.successSoft},
 {key:'group',label:'Issue Management',icon:'construct',tone:colors.navy,bg:colors.background},
 {key:'group',label:'Service Directory',icon:'storefront',tone:colors.green,bg:colors.successSoft},
 {key:'group',label:'Marketplace',icon:'bag-handle',tone:colors.navy,bg:colors.background},
 {key:'group',label:'Opportunities',icon:'briefcase',tone:colors.green,bg:colors.successSoft},
 {key:'group',label:'Community Events',icon:'calendar-number',tone:colors.navy,bg:colors.background},
 {key:'group',label:'Scan Member QR',icon:'qr-code',tone:colors.navy,bg:colors.background},
 {key:'group',label:'Governance',icon:'git-branch',tone:colors.green,bg:colors.successSoft},
 {key:'group',label:'Formal Voting',icon:'checkbox',tone:colors.green,bg:colors.successSoft},
 {key:'group',label:'Community Finances',icon:'wallet',tone:colors.green,bg:colors.successSoft},
 {key:'group',label:'Document Centre',icon:'folder-open',tone:colors.navy,bg:colors.background},
 {key:'group',label:'CDA Assistant',icon:'sparkles',tone:colors.navy,bg:colors.background},
 {key:'group',label:'Moderation Queue',icon:'shield-checkmark',tone:colors.navy,bg:colors.background},
 {key:'group',label:'Admin Analytics',icon:'analytics',tone:colors.navy,bg:colors.background},
 {key:'group',label:'Create Chat Group',icon:'chatbubbles',tone:colors.green,bg:colors.successSoft},
];
export default function Manage(){
 const{id}=useLocalSearchParams<{id:string}>(); const qc=useQueryClient(); const[mode,setMode]=useState<Mode|null>(null); const[title,setTitle]=useState(''); const[body,setBody]=useState(''); const[extra,setExtra]=useState(''); const[area,setArea]=useState(''); const[loading,setLoading]=useState(false);
 const reset=()=>{setTitle('');setBody('');setExtra('');setArea('')};
 async function submit(){if(!mode)return;if(!title.trim()){Alert.alert('Title required','Enter a title or poll question.');return}const pollOptions=[...new Set(extra.split(',').map(x=>x.trim()).filter(Boolean))];if(mode==='poll'&&pollOptions.length<2){Alert.alert('Add poll options','Enter at least two different options separated by commas.');return}try{setLoading(true);if(mode==='announcement'){await api.post(`/communities/${id}/announcements`,{title:title.trim(),body,isPinned:false});await qc.invalidateQueries({queryKey:['announcements',id]});}if(mode==='meeting'){const start=new Date(extra||Date.now()+86400000);const end=new Date(start.getTime()+3600000);await api.post(`/communities/${id}/meetings`,{title:title.trim(),description:body,startDateTime:start.toISOString(),endDateTime:end.toISOString(),agenda:[]});await qc.invalidateQueries({queryKey:['meetings',id]});}if(mode==='poll'){await api.post(`/communities/${id}/polls`,{question:title.trim(),description:body,options:pollOptions});await qc.invalidateQueries({queryKey:['polls',id]});}if(mode==='alert'){await api.post(`/communities/${id}/alerts`,{title:title.trim(),message:body,alertType:'COMMUNITY',severity:(extra||'HIGH').toUpperCase(),requiresAcknowledgement:true,affectedArea:area||undefined});await qc.invalidateQueries({queryKey:['alerts',id]});}if(mode==='group'){await api.post(`/communities/${id}/conversations`,{name:title.trim(),type:'GROUP',memberUserIds:[]});await qc.invalidateQueries({queryKey:['conversations',id]});}reset();setMode(null);Alert.alert('Created',`${mode} created successfully.`);}catch(e:any){Alert.alert('Unable to create',e.response?.data?.error??e.message)}finally{setLoading(false)}}
 function choose(key:Mode,label:string){if(label==='Manage Members'){router.push(`/community/${id}/members`);return}if(label==='Join Requests'){router.push(`/community/${id}/requests`);return}if(label==='Emergency Command'){router.push(`/community/${id}/emergency-command`);return}if(label==='Community Verification'){router.push(`/community/${id}/verification`);return}if(label==='Issue Management'){router.push(`/community/${id}/issues`);return}if(label==='Service Directory'){router.push(`/community/${id}/services`);return}if(label==='Marketplace'){router.push(`/community/${id}/marketplace`);return}if(label==='Opportunities'){router.push(`/community/${id}/opportunities`);return}if(label==='Community Events'){router.push(`/community/${id}/events`);return}if(label==='Scan Member QR'){router.push(`/community/${id}/scan-card`);return}if(label==='Governance'){router.push(`/community/${id}/governance` as any);return}if(label==='Formal Voting'){router.push(`/community/${id}/formal-voting` as any);return}if(label==='Community Finances'){router.push(`/community/${id}/finance` as any);return}if(label==='Document Centre'){router.push(`/community/${id}/documents` as any);return}if(label==='CDA Assistant'){router.push(`/community/${id}/assistant` as any);return}if(label==='Moderation Queue'){router.push(`/community/${id}/moderation` as any);return}if(label==='Admin Analytics'){router.push(`/community/${id}/analytics` as any);return}setMode(key);reset()}
 return <Screen scroll><View style={styles.nav}><Pressable onPress={()=>(router.canGoBack()?router.back():router.replace('/'))}><Ionicons name="chevron-back" size={24}/></Pressable><Text style={styles.navTitle}>Admin Panel</Text><View style={{width:24}}/></View><Muted>Manage your community, publish updates and create member activities.</Muted><View style={styles.grid}>{tiles.map((t,i)=><Pressable key={`${t.label}-${i}`} onPress={()=>choose(t.key,t.label)} style={[styles.tile,{backgroundColor:t.bg}]}><View style={[styles.icon,{backgroundColor:t.tone}]}><Ionicons name={t.icon} size={25} color="#fff"/></View><Text style={styles.tileText}>{t.label}</Text></Pressable>)}</View><Text style={styles.section}>Community Controls</Text><Card><Pressable onPress={()=>router.push(`/community/${id}/members`)} style={styles.control}><Ionicons name="shield-checkmark-outline" size={22} color={colors.primary}/><View style={{flex:1}}><Text style={styles.controlTitle}>Roles & Permissions</Text><Muted>Configure administrators, moderators and responsibilities.</Muted></View><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable><Pressable onPress={()=>router.push(`/community/${id}/verification`)} style={styles.control}><Ionicons name="settings-outline" size={22} color={colors.success}/><View style={{flex:1}}><Text style={styles.controlTitle}>Community Settings</Text><Muted>Privacy, membership and communication preferences.</Muted></View><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable><Pressable onPress={()=>router.push(`/community/${id}/analytics` as any)} style={[styles.control,{borderBottomWidth:0}]}><Ionicons name="receipt-outline" size={22} color={colors.purple}/><View style={{flex:1}}><Text style={styles.controlTitle}>Activity Logs</Text><Muted>Review administrative actions and changes.</Muted></View><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable></Card>
 <Modal visible={!!mode} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setMode(null)}><Screen scroll><Header title={mode==='group'?'Create Group':mode==='alert'?'Send Emergency Alert':mode==='poll'?'Create Poll':mode==='meeting'?'Schedule Meeting':'New Announcement'} right={<Pressable onPress={()=>setMode(null)}><Ionicons name="close" size={26}/></Pressable>}/><Muted>The backend will validate your community role and permissions before publishing.</Muted><Text style={styles.label}>{mode==='poll'?'Poll question':mode==='group'?'Group name':'Title'}</Text><Input placeholder={mode==='poll'?'What would you like members to vote on?':mode==='group'?'Enter group name':'Enter title'} value={title} onChangeText={setTitle}/>{mode!=='group'&&<><Text style={styles.label}>{mode==='alert'?'Emergency message':'Description'}</Text><Input placeholder={mode==='alert'?'Describe the emergency and instructions':'Add details'} value={body} onChangeText={setBody} multiline/></>}{mode==='meeting'&&<><Text style={styles.label}>Start date/time</Text><Input placeholder="2026-08-20T19:00:00" value={extra} onChangeText={setExtra}/></>}{mode==='poll'&&<><Text style={styles.label}>Options</Text><Input placeholder="Community Park, Sports Centre, Community Hall" value={extra} onChangeText={setExtra}/><Muted>Separate each option with a comma.</Muted></>}{mode==='alert'&&<><Text style={styles.label}>Affected area</Text><Input placeholder="e.g. Central Estate" value={area} onChangeText={setArea}/><Text style={styles.label}>Severity</Text><Input placeholder="HIGH or CRITICAL" value={extra} onChangeText={setExtra}/></>}<Button title={mode==='alert'?'Send Alert':mode==='meeting'?'Schedule Meeting':mode==='poll'?'Create Poll':mode==='group'?'Create Group':'Publish Announcement'} loading={loading} onPress={submit}/></Screen></Modal>
 </Screen>
}
const styles=StyleSheet.create({nav:{height:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:8},navTitle:{fontSize:18,fontWeight:'900',color:colors.text},grid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:18},tile:{width:'48%',minHeight:132,borderRadius:18,padding:15,justifyContent:'space-between'},icon:{width:44,height:44,borderRadius:13,alignItems:'center',justifyContent:'center'},tileText:{fontSize:14,fontWeight:'900',color:colors.text,maxWidth:120},section:{fontSize:18,fontWeight:'900',color:colors.text,marginTop:24,marginBottom:12},control:{flexDirection:'row',gap:12,alignItems:'center',paddingVertical:14,borderBottomWidth:1,borderBottomColor:colors.border},controlTitle:{fontSize:14,fontWeight:'900',color:colors.text},label:{fontSize:13,fontWeight:'800',color:colors.text,marginTop:18,marginBottom:8}})
