import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, router } from 'expo-router';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { api } from '@/lib/api';
import { Badge, Button, Card, EmptyState, Muted, Screen } from '@/components/UI';
import { colors } from '@/theme';
import type { Meeting } from '@/types';

export default function Meetings(){const{id}=useLocalSearchParams<{id:string}>();const qc=useQueryClient();const{data=[]}=useQuery<Meeting[]>({queryKey:['meetings',id],queryFn:async()=>(await api.get(`/communities/${id}/meetings`)).data});const rsvp=useMutation({mutationFn:async(v:{meetingId:string,response:string})=>api.post(`/meetings/${v.meetingId}/rsvp`,{response:v.response}),onSuccess:()=>qc.invalidateQueries({queryKey:['meetings',id]})});return <Screen scroll><View style={styles.nav}><Pressable onPress={()=>(router.canGoBack()?router.back():router.replace('/'))}><Ionicons name="chevron-back" size={24}/></Pressable><Text style={styles.navTitle}>Meetings</Text><Pressable onPress={()=>router.push(`/community/${id}/manage`)}><Ionicons name="add" size={25} color={colors.primary}/></Pressable></View><View style={styles.segment}><View style={styles.activeSeg}><Text style={styles.activeText}>Upcoming</Text></View><View style={styles.seg}><Text style={styles.segText}>Past</Text></View></View>{data.length?data.map(m=>{const d=new Date(m.StartDateTime);return <Card key={m.Id} style={styles.card}><View style={styles.dateBox}><Text style={styles.month}>{d.toLocaleString('en',{month:'short'}).toUpperCase()}</Text><Text style={styles.day}>{d.getDate()}</Text></View><View style={{flex:1}}><Text style={styles.title}>{m.Title}</Text><Muted>{d.toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}</Muted><Muted>{m.Location||'Location not specified'}</Muted><View style={styles.people}><Badge text={m.MyResponse||'RSVP'} tone={m.MyResponse==='GOING'?'green':'gray'}/></View><View style={styles.actions}><Button title="Going" variant={m.MyResponse==='GOING'?'success':'secondary'} onPress={()=>rsvp.mutate({meetingId:m.Id,response:'GOING'})}/><Button title="Maybe" variant="secondary" onPress={()=>rsvp.mutate({meetingId:m.Id,response:'MAYBE'})}/></View></View></Card>}):<EmptyState icon="calendar-outline" title="No meetings yet" body="Meetings created by your community admins will appear here."/>}</Screen>}
const styles=StyleSheet.create({nav:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',height:52},navTitle:{fontSize:18,fontWeight:'900',color:colors.text},segment:{flexDirection:'row',backgroundColor:'#EEF0F5',borderRadius:13,padding:3,marginVertical:14},activeSeg:{flex:1,backgroundColor:colors.primary,borderRadius:10,paddingVertical:9,alignItems:'center'},seg:{flex:1,paddingVertical:9,alignItems:'center'},activeText:{fontSize:12,fontWeight:'900',color:'#fff'},segText:{fontSize:12,fontWeight:'800',color:colors.muted},card:{flexDirection:'row',gap:12},dateBox:{width:54,height:62,borderRadius:14,backgroundColor:colors.dangerSoft,alignItems:'center',justifyContent:'center'},month:{fontSize:10,fontWeight:'900',color:colors.danger},day:{fontSize:21,fontWeight:'900',color:colors.text},title:{fontSize:15,fontWeight:'900',color:colors.text,marginBottom:3},people:{marginTop:8},actions:{flexDirection:'row',gap:8,marginTop:8}})
