import {PhoneField} from './PhoneField';
import {LocationFields} from './LocationFields';
import {getLocale} from './i18n';
import {Capacitor} from '@capacitor/core';
import {useState} from 'react';
import {Link,Navigate,useLocation,useNavigate,useParams} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {UserRound,AtSign,CalendarDays,Mail,Phone,MapPin,ShieldCheck,Eye,Users,ChartNoAxesColumn,KeyRound,Monitor,Download,Clock,Camera,ChevronRight,ArrowLeft,LockKeyhole,SquarePen,UserPlus} from 'lucide-react';
import {api,session,str,rows,type RecordData} from './api';
import {Field,MutationForm,Loading,ErrorBox,Page,Action} from './ui';
import {VerificationCode} from './VerificationCode';
import './member-activity.css';

const titles:Record<string,string>={name:'Name',username:'Username',birth:'Date of birth',email:'Registered email address',phone:'Phone number',location:'Location',download:'Download my data',deactivate:'Deactivate account',following:'Following'};
const preferenceRows=[['privateAccount','PrivateAccount','Private account','Only members of your communities can view your member profile.',ShieldCheck],['showOnlineStatus','ShowOnlineStatus','Show online status','Let people who can view your profile see when you are online.',Eye],['allowFollowers','AllowFollowers','Allow people to follow you','Let eligible members follow your profile and read your updates.',Users],['emailUpdates','EmailUpdates','Email updates','Receive community updates by email. Security messages stay enabled.',Mail],['personalizedExperience','PersonalizedExperience','Personalized experience','Use your name in your Home greeting.',ChartNoAxesColumn]] as const;
function AccountRow({to,title,value,Icon,locked=false}:{to:string;title:string;value:string;Icon:typeof UserRound;locked?:boolean}){const content=<><span className="settings-row-icon"><Icon size={21}/></span><span className="settings-row-text"><strong>{title}</strong><small>{value||'Not provided'}</small></span>{locked?<LockKeyhole size={18} aria-label="Locked"/>:<ChevronRight size={18}/>}</>;return locked?<div className="settings-row" aria-label={`${title} is locked`}>{content}</div>:<Link className="settings-row" to={to}>{content}</Link>}

export function AccountSettings(){
 const field=useLocation().pathname.split('/')[3]||'',qc=useQueryClient(),[busy,setBusy]=useState(''),[error,setError]=useState<unknown>(),[notice,setNotice]=useState('');
 const q=useQuery({queryKey:['/users/account'],queryFn:({signal})=>api.get<RecordData>('/users/account',signal)});
 if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;
 const u=q.data,name=[u.FirstName,u.LastName].filter(Boolean).join(' '),joined=u.CreatedAt?new Date(str(u.CreatedAt)).toLocaleDateString(getLocale(),{month:'long',year:'numeric'}):'';
 async function toggle(key:string,value:boolean){setBusy(key);setError(undefined);setNotice('');try{await api.send('/users/account/preferences',{key,value},'PATCH');await qc.invalidateQueries();setNotice('Preference saved.')}catch(e){setError(e)}finally{setBusy('')}}
 if(field)return <><Link className="settings-back" to="/profile/account"><ArrowLeft size={17}/>Account settings</Link><h2>{titles[field]||'Account settings'}</h2><AccountEditor key={field} field={field} user={u}/></>;
 return <div className="account-dashboard">

 <section className="settings-group"><h2 className="sr-only">Personal information</h2><div className="settings-list">
 <AccountRow to="/profile/account/name" title="Name" value={name} Icon={UserRound}/><AccountRow to="/profile/account/username" title="Username" value={u.Username?'@'+str(u.Username):'Choose a username'} Icon={AtSign}/><AccountRow to="/profile/account/birth" title="Date of birth" value={u.DateOfBirth?new Date(str(u.DateOfBirth).slice(0,10)+'T12:00:00').toLocaleDateString(getLocale(),{day:'numeric',month:'long',year:'numeric'}):''} Icon={CalendarDays}/><AccountRow to="/profile/account/email" title="Registered email address" value={str(u.Email)} Icon={Mail} locked/><AccountRow to="/profile/account/phone" title="Phone number" value={str(u.Phone)} Icon={Phone}/><AccountRow to="/profile/account/location" title="Location" value={[u.LGA,u.State,u.Country].filter(Boolean).join(', ')} Icon={MapPin}/>
 </div></section>
 <section className="settings-group"><h2>Account preferences</h2><div className="settings-list">{preferenceRows.map(([key,column,title,description,Icon])=><label className="settings-row account-switch-row" key={key}><span className="settings-row-icon"><Icon size={21}/></span><span className="settings-row-text"><strong>{title}</strong><small>{description}</small></span><input aria-label={title} type="checkbox" role="switch" checked={Boolean(u[column])} disabled={Boolean(busy)} onChange={e=>void toggle(key,e.target.checked)}/></label>)}</div><ErrorBox error={error}/>{notice&&<p role="status">{notice}</p>}</section>
 <section className="settings-group"><h2>Account management</h2><div className="settings-list"><AccountRow to="/settings/password" title="Change password" value="Update your password regularly" Icon={KeyRound}/><AccountRow to="/settings/sessions" title="Active sessions" value="View and manage your active sessions" Icon={Monitor}/><AccountRow to="/profile/account/download" title="Download my data" value="Download a copy of your profile and authored content" Icon={Download}/>{!u.IsProtectedAccount&&<AccountRow to="/profile/account/deactivate" title="Deactivate account" value="Temporarily deactivate your account" Icon={Clock}/>}</div></section>
 </div>;
}

function AccountEditor({field,user:u}:{field:string;user:RecordData}){
 const nav=useNavigate(),qc=useQueryClient(),done=()=>nav('/profile/account');
 if(field==='name')return <MutationForm label="Save name" onSuccess={done} onSubmit={async d=>{const result=await api.send('/users/me',d,'PATCH'),current=session.get();if(current)session.set({...current,user:{...current.user,FirstName:d.firstName,LastName:d.lastName}});return result}}><Field name="firstName" label="First name" defaultValue={str(u.FirstName)}/><Field name="lastName" label="Last name" defaultValue={str(u.LastName)}/></MutationForm>;
 if(field==='username')return <><p>Use 3–30 letters, numbers or underscores, starting with a letter. Usernames are unique. Continue signing in with your email address.</p><MutationForm label="Save username" onSuccess={done} onSubmit={d=>api.send('/users/account/username',d,'PUT')}><Field name="username" label="Username" defaultValue={str(u.Username)}/></MutationForm></>;
 if(field==='birth')return <MutationForm label="Save date of birth" onSuccess={done} onSubmit={d=>{if(d.dateOfBirth>new Date().toISOString().slice(0,10))throw Error('Date of birth cannot be in the future.');return api.send('/users/me',d,'PATCH')}}><Field name="dateOfBirth" label="Date of birth" type="date" defaultValue={str(u.DateOfBirth).slice(0,10)}/></MutationForm>;
 if(field==='phone')return <><p>Changing your number clears its previous verification.</p><MutationForm label="Save phone number" onSuccess={done} onSubmit={d=>api.send('/users/me',d,'PATCH')}><PhoneField defaultValue={str(u.Phone)}/></MutationForm></>;
 if(field==='location')return <MutationForm label="Save location" onSuccess={done} onSubmit={d=>api.send('/users/me',d,'PATCH')}>{[['address','Address'],['postcode','Postcode']].map(([key,label])=><Field key={key} name={key} label={label} required={false} defaultValue={str(u[key==='lga'?'LGA':key[0].toUpperCase()+key.slice(1)])}/>)}<LocationFields country={str(u.Country)} state={str(u.State)} lga={str(u.LGA)}/></MutationForm>;
 if(field==='email')return <><p>Your registered email address is locked and cannot be changed.</p><p><strong>{str(u.Email)}</strong></p><Link className="button" to="/profile/account">Back to account settings</Link></>;
 if(field==='download')return <AccountDownload/>;
 if(field==='deactivate')return u.IsProtectedAccount?<Navigate to="/profile/account" replace/>:<><p>Your sign-in and member-profile access will be disabled. Your community records and data are retained. Contact support@cdaconnect.org to request reactivation.</p><MutationForm label="Deactivate my account" onSubmit={d=>api.send('/users/account/deactivate',d)} onSuccess={()=>{session.set(null);qc.clear();nav('/login',{replace:true})}}><Field name="password" label="Current password" type="password"/></MutationForm><Link className="button" to="/profile/account">Keep my account active</Link></>;
 if(field==='following')return <Following/>;
 return <p>Choose an item from Account settings.</p>;
}

export function AccountDownload(){const[busy,setBusy]=useState(false),[message,setMessage]=useState('');return <><p>Download a JSON file containing your profile, preferences, memberships and content you authored. Passwords and other members’ content are excluded.</p><button type="button" disabled={busy} onClick={async()=>{setBusy(true);setMessage('');try{const data=await api.get<RecordData>('/users/account/export');if(Capacitor.isNativePlatform()){const {Filesystem,Directory,Encoding}=await import('@capacitor/filesystem'),{Share}=await import('@capacitor/share');const file=await Filesystem.writeFile({path:'cda-connect-my-data.json',data:JSON.stringify(data,null,2),directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:'CDA Connect account data',files:[file.uri]});setMessage('Your data file is ready. Choose where to save it in the share sheet.');return}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='cda-connect-my-data.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);setMessage('Your data file is ready. Check your downloads.')}catch(e){setMessage(e instanceof Error?e.message:'Download failed')}finally{setBusy(false)}}}>{busy?'Preparing download…':'Download my data'}</button><p role="status">{message}</p></>}
function Following(){const q=useQuery({queryKey:['/users/account/following'],queryFn:()=>api.get<RecordData[]>('/users/account/following')});return q.isPending?<Loading/>:q.error?<ErrorBox error={q.error}/>:q.data.length?<div className="settings-list">{q.data.map(u=><AccountRow key={str(u.Id)} to={'/member/'+u.Id} title={[u.FirstName,u.LastName].filter(Boolean).join(' ')} value="View profile and updates" Icon={UserRound}/>)}</div>:<p>You are not following any available profiles. Members can share their profile link with you.</p>}

export function MemberProfile(){
 const{id}=useParams(),q=useQuery({queryKey:['/users/members/'+id],queryFn:()=>api.get<RecordData>('/users/members/'+id)});
 if(q.isPending)return <Loading/>;if(q.error)return <Page title="Member profile"><ErrorBox error={q.error}/></Page>;
 const p=q.data.profile as RecordData,name=[p.FirstName,p.LastName].filter(Boolean).join(' '),initials=[str(p.FirstName)[0],str(p.LastName)[0]].filter(Boolean).join('').toUpperCase(),posts=rows(q.data.posts),groups=new Map<string,RecordData[]>();
 posts.forEach(post=>{const date=new Date(str(post.CreatedAt)),heading=Number.isFinite(date.getTime())?date.toLocaleDateString(getLocale(),{month:'long',year:'numeric'}):'Date unavailable';groups.set(heading,[...(groups.get(heading)||[]),post])});
 const canFollow=str(p.Id)!==session.get()?.user.Id&&(Boolean(p.AllowFollowers)||Boolean(q.data.following));
 return <Page title="Member profile"><div className="member-public-profile"><section className="member-public-summary" aria-label={`${name} profile`}><div className="member-public-cover"><div className="member-public-avatar">{p.ProfileImage?<img src={api.asset(str(p.ProfileImage))} alt={`${name} profile`}/>:<span>{initials||<UserRound/>}</span>}</div><div className="member-public-identity"><h1>{name}</h1>{!!p.Username&&<p>@{str(p.Username)}</p>}{q.data.online!==null&&<small className={q.data.online?'is-online':''}>{q.data.online?'Online now':'Offline'}</small>}</div></div>{canFollow&&<div className="member-public-actions"><Action run={()=>api.send('/users/members/'+id+'/follow',{following:!q.data.following},'PUT')}><UserPlus size={18}/>{q.data.following?'Unfollow':'Follow'}</Action></div>}</section><section className="member-public-activity" aria-labelledby="member-activity-heading"><h2 id="member-activity-heading">Activity</h2>{posts.length?Array.from(groups,([heading,entries])=><section className="activity-period" key={heading}><h3>{heading}</h3><div className="activity-timeline">{entries.map(post=><article key={str(post.Id)}><span className="activity-marker"><SquarePen size={21}/></span><Link className="activity-entry" to={post.Id?'/post/'+post.Id:'#'}><span className="activity-entry-heading"><strong>{post.IsTagged?'Tagged in a post':'Created a post'}</strong><time dateTime={Number.isFinite(Date.parse(str(post.CreatedAt)))?str(post.CreatedAt):undefined}>{Number.isFinite(Date.parse(str(post.CreatedAt)))?new Date(str(post.CreatedAt)).toLocaleDateString(getLocale(),{day:'numeric',month:'short',year:'numeric'}):'Date unavailable'}</time></span>{!!post.Body&&<p>{str(post.Body)}</p>}{!!post.CommunityName&&<small>in <b>{str(post.CommunityName)}</b></small>}</Link></article>)}</div></section>):<p className="empty">No activity is available to you.</p>}</section></div></Page>
}
