import {useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
const key='cda-analytics-consent';
function current(){try{return localStorage.getItem(key)}catch{return null}}
export function AnalyticsPreferences(){const[choice,setChoice]=useState(current),[open,setOpen]=useState(!current()),location=useLocation();function choose(value:string){try{localStorage.setItem(key,value)}catch{}setChoice(value);setOpen(false);window.dispatchEvent(new Event('cda-analytics-consent'));if(value==='denied')window.location.reload()}
 const publicPage=['/login','/register','/forgot-password','/privacy','/cookies','/terms','/contact','/account-deletion'].includes(location.pathname);
 return <>{open&&<section className="analytics-consent" role="region" aria-label="Cookie preferences"><strong>Cookies</strong><p>Necessary cookies keep CDA Connect secure and signed in. With your permission, analytics cookies help us understand app usage and improve reliability.</p><div><button onClick={()=>choose('denied')}>Reject</button><button onClick={()=>choose('granted')}>Accept</button><Link to="/cookies">Cookie information</Link>{choice&&<button onClick={()=>setOpen(false)}>Close</button>}</div></section>}{publicPage&&<footer className="privacy-footer">{location.pathname==='/cookies'&&<button onClick={()=>setOpen(true)}>Cookie preferences</button>}<Link to="/privacy">Privacy</Link><Link to="/cookies">Cookies</Link><Link to="/terms">Terms</Link></footer>}</>
}
export function CookieNotice(){return <main className="page narrow"><h1>Cookies and analytics</h1><p>Necessary session cookies keep you signed in securely. Local preferences and cached app files support the app. These are separate from optional analytics.</p><p>Google Analytics is disabled by default. If you accept, Google receives usage and page-view information and may store analytics cookies such as _ga for up to two years. Do not include sensitive personal information in page URLs.</p><p>Use Analytics preferences below to reject or withdraw consent. Withdrawal stops future analytics and removes accessible analytics cookies on this device; it does not erase information already received by Google. Your choice applies to this browser or app installation.</p><Link to="/privacy">Privacy statement</Link></main>}
