import {useState} from 'react';
import {createPortal} from 'react-dom';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {Megaphone,ShieldCheck,CalendarDays,TriangleAlert,MessageCircle,Search,SlidersHorizontal,Pin,ArrowLeft,SquarePen} from 'lucide-react';
import {api,rows,str,type RecordData} from './api';
import {Loading,ErrorBox,MutationForm,Field} from './ui';
import {PostMedia} from './PostMedia';
import {getLocale} from './i18n';
import './announcements.css';
type Entry={r:RecordData;kind:string;category:string};
const icons={All:Megaphone,Official:ShieldCheck,Events:CalendarDays,Important:TriangleAlert,General:MessageCircle};
export function Announcements({id,name,permissions}:{id:string;name:string;permissions:string[]}){
 const navigate=useNavigate();
 const base='/communities/'+id,[params,setParams]=useSearchParams(),[search,setSearch]=useState(''),[filters,setFilters]=useState(false),[pinned,setPinned]=useState(false),[oldest,setOldest]=useState(false),[notice,setNotice]=useState(''),[limit,setLimit]=useState(20),creating=params.get('create')==='1';
 const announcements=useQuery({queryKey:[base+'/announcements'],queryFn:()=>api.get<RecordData[]>(base+'/announcements')}),posts=useQuery({queryKey:[base+'/feed'],queryFn:()=>api.get<RecordData[]>(base+'/feed')}),meetings=useQuery({queryKey:[base+'/meetings'],queryFn:()=>api.get<RecordData[]>(base+'/meetings')}),polls=useQuery({queryKey:[base+'/polls'],queryFn:()=>api.get<RecordData[]>(base+'/polls')});
 const community=useQuery({queryKey:[base],queryFn:()=>api.get<RecordData>(base)});
 const entries:Entry[]=[...rows(announcements.data).map(r=>({r,kind:'announcement',category:r.IsPinned?'Important':'Official'})),...rows(posts.data).filter(r=>r.IsAnnouncement).map(r=>({r,kind:'post',category:r.IsPinned?'Important':'General'})),...rows(meetings.data).map(r=>({r,kind:'meeting',category:'Events'})),...rows(polls.data).filter(r=>(r.settings as RecordData)?.announcement).map(r=>({r:{...r,Title:r.Question},kind:'poll',category:'Official'}))];
 const filtered=entries.filter(({r,category:c})=>(!pinned||!!r.IsPinned)&&[r.Title,r.Body,r.Description,r.FirstName,r.LastName].map(str).join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(!!b.r.IsPinned)-Number(!!a.r.IsPinned)||(oldest?1:-1)*((Date.parse(str(a.r.CreatedAt||a.r.StartDateTime))||0)-(Date.parse(str(b.r.CreatedAt||b.r.StartDateTime))||0)));
 const selected=entries.find(e=>str(e.r.Id)===params.get('announcement')&&e.kind===(params.get('kind')||'announcement'));
 const link=(e:Entry)=>e.kind==='meeting'?'/community/'+id+'/meetings?meeting='+e.r.Id:e.kind==='poll'?'/poll/'+id+'/'+e.r.Id:e.kind==='post'?'/post/'+e.r.Id:'/community/'+id+'/announcements?announcement='+e.r.Id;
 const back='/community/'+id+'/announcements';
 const create=permissions.includes('ANNOUNCEMENT_CREATE')?<Link className="topbar-icon announcement-create" aria-label="Create announcement" title="Create announcement" to={back+'?create=1'}><SquarePen size={20}/></Link>:null,target=document.getElementById('page-search-actions');
 if(creating)return <div className="announcements-page"><div className="announcements-content announcement-editor"><Link className="announcement-back" to={back}><ArrowLeft size={18}/>Back to announcements</Link>{permissions.includes('ANNOUNCEMENT_CREATE')?<section className="announcement-form"><h1>Create announcement</h1><MutationForm label="Publish announcement" onSubmit={d=>api.send(base+'/announcements',{title:d.title,body:d.body,isPinned:d.pinned==='yes'})} onSuccess={()=>{setParams({});setNotice('Announcement published.')}}><Field name="title" label="Title"/><Field name="body" label="Announcement" type="textarea"/><label className="announcement-pin-choice"><input type="checkbox" name="pinned" value="yes"/>Pin as important</label></MutationForm></section>:<p role="alert">You do not have permission to create announcements.</p>}</div></div>;
 if(params.has('announcement'))return <div className="announcements-page"><div className="announcements-content announcement-editor"><Link className="announcement-back" to={back}><ArrowLeft size={18}/>Back to announcements</Link><ErrorBox error={announcements.error||posts.error}/>{announcements.isPending||posts.isPending?<Loading/>:selected?<article className="announcement-full-detail"><h1>{str(selected.r.Title)||'Community update'}</h1><p>{str(selected.r.Body||selected.r.Description)}</p><PostMedia post={selected.r}/></article>:<p role="status">This announcement is unavailable.</p>}</div></div>;
 return <div className="announcements-page">{target?createPortal(create,target):create}<div className="announcements-content"><div className="announcement-search"><label><Search size={19}/><input aria-label="Search announcements" placeholder="Search announcements…" value={search} onChange={e=>{setSearch(e.target.value);setLimit(20)}}/></label><button aria-label="Filter announcements" aria-expanded={filters} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={20}/></button></div>{filters&&<div className="announcement-filters"><label><input type="checkbox" checked={pinned} onChange={e=>{setPinned(e.target.checked);setLimit(20)}}/>Pinned only</label><label>Sort<select value={oldest?'oldest':'newest'} onChange={e=>setOldest(e.target.value==='oldest')}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label></div>}<ErrorBox error={announcements.error||posts.error||meetings.error||polls.error}/>{notice&&<p role="status">{notice}</p>}
 {announcements.isPending||posts.isPending||meetings.isPending||polls.isPending?<Loading/>:<div className="announcement-list">{!filtered.length&&<p className="empty">No announcements match your filters.</p>}{filtered.slice(0,limit).map(e=>{const {r,category:c}=e,Icon=icons[c as keyof typeof icons],author=[r.FirstName,r.LastName].filter(Boolean).join(' ')||name;return <article className={'announcement-card category-'+c.toLowerCase()} key={e.kind+str(r.Id)} onClick={event=>{if(!(event.target as HTMLElement).closest('a,button,input,video,audio,summary'))navigate(link(e))}}><div className="announcement-card-top"><span className="announcement-symbol"><Icon/></span><div className="announcement-copy"><div className="announcement-meta"><span className="announcement-category"><Icon size={14}/>{c==='Events'?'Event':c}</span>{!!r.IsPinned&&<span className="announcement-pin"><Pin size={13}/>Pinned</span>}</div><Link className="announcement-title" to={link(e)}>{str(r.Title)||'Community update'}</Link><p className="announcement-excerpt">{str(r.Body||r.Description)}</p><Link className="announcement-author" to={r.FirstName&&r.CreatedBy?'/member/'+r.CreatedBy:'/community/'+id+'/profile'}>{(r.FirstName?r.ProfileImage:community.data?.LogoUrl)?<img src={api.asset(str(r.FirstName?r.ProfileImage:community.data?.LogoUrl))} alt=""/>:<span>{author.slice(0,1)}</span>}<div>By <strong>{author}</strong><small>{r.CreatedAt?new Date(str(r.CreatedAt)).toLocaleDateString(getLocale(),{day:'numeric',month:'short',year:'numeric'}):'Community announcement'}</small></div></Link></div></div><PostMedia post={r}/></article>})}{filtered.length>limit&&<button onClick={()=>setLimit(limit+20)}>Show more announcements</button>}</div>}
</div></div>
}
