import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Link,useSearchParams} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {Megaphone,ShieldCheck,CalendarDays,TriangleAlert,MessageCircle,Search,SlidersHorizontal,Pin,MoreVertical,Share2,X,FileText} from 'lucide-react';
import {api,rows,str,type RecordData} from './api';
import {Loading,ErrorBox,MutationForm,Field} from './ui';
import {PostMedia,SocialActions} from './PostMedia';
import {exportCalendar} from './CommunityEvents';
import {Capacitor} from '@capacitor/core';
import {Share} from '@capacitor/share';
import {getLocale} from './i18n';
import './announcements.css';
type Entry={r:RecordData;kind:string;category:string};
const categories=['All','Official','Events','Important','General'];
const icons={All:Megaphone,Official:ShieldCheck,Events:CalendarDays,Important:TriangleAlert,General:MessageCircle};
export function Announcements({id,name,permissions}:{id:string;name:string;permissions:string[]}){
 const base='/communities/'+id,[params,setParams]=useSearchParams(),[category,setCategory]=useState('All'),[search,setSearch]=useState(''),[filters,setFilters]=useState(false),[pinned,setPinned]=useState(false),[oldest,setOldest]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState<unknown>(),[limit,setLimit]=useState(20),dialog=useRef<HTMLDialogElement>(null),creating=params.get('create')==='1';
 const announcements=useQuery({queryKey:[base+'/announcements'],queryFn:()=>api.get<RecordData[]>(base+'/announcements')}),posts=useQuery({queryKey:[base+'/feed'],queryFn:()=>api.get<RecordData[]>(base+'/feed')}),meetings=useQuery({queryKey:[base+'/meetings'],queryFn:()=>api.get<RecordData[]>(base+'/meetings')}),polls=useQuery({queryKey:[base+'/polls'],queryFn:()=>api.get<RecordData[]>(base+'/polls')});
 const entries:Entry[]=[...rows(announcements.data).map(r=>({r,kind:'announcement',category:r.IsPinned?'Important':'Official'})),...rows(posts.data).filter(r=>r.IsAnnouncement).map(r=>({r,kind:'post',category:r.IsPinned?'Important':'General'})),...rows(meetings.data).map(r=>({r,kind:'meeting',category:'Events'})),...rows(polls.data).filter(r=>(r.settings as RecordData)?.announcement).map(r=>({r:{...r,Title:r.Question},kind:'poll',category:'Official'}))];
 const filtered=entries.filter(({r,category:c})=>(category==='All'||category===c)&&(!pinned||!!r.IsPinned)&&[r.Title,r.Body,r.Description,r.FirstName,r.LastName].map(str).join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(!!b.r.IsPinned)-Number(!!a.r.IsPinned)||(oldest?1:-1)*((Date.parse(str(a.r.CreatedAt||a.r.StartDateTime))||0)-(Date.parse(str(b.r.CreatedAt||b.r.StartDateTime))||0)));
 const selected=entries.find(e=>str(e.r.Id)===params.get('announcement')&&e.kind===(params.get('kind')||'announcement'));
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close()},[selected?.r.Id]);
 const link=(e:Entry)=>e.kind==='meeting'?'/community/'+id+'/meetings?meeting='+e.r.Id:e.kind==='poll'?'/poll/'+id+'/'+e.r.Id:e.kind==='post'?'/post/'+e.r.Id:'/community/'+id+'/announcements?announcement='+e.r.Id;
 async function share(e:Entry){try{const url='https://cdaconnect.org'+link(e);if(Capacitor.isNativePlatform())await Share.share({title:str(e.r.Title),url});else if(navigator.share)await navigator.share({title:str(e.r.Title),url});else{await navigator.clipboard.writeText(url);setNotice('Link copied.')}}catch(e){if((e as Error).name!=='AbortError')setError(e)}}
 const create=permissions.includes('ANNOUNCEMENT_CREATE')?<button className="announcement-create" onClick={()=>setParams({create:'1'})}><Megaphone size={17}/>Create</button>:null,target=document.getElementById('page-search-actions');
 return <div className="announcements-page">{target?createPortal(create,target):create}<header className="announcements-hero"><span><Megaphone/></span><div><h1>Community Announcements</h1><h2>Stay informed. Stay connected.</h2><p>Important updates, news and information from your community leaders.</p></div><em>Stronger<br/>Together</em></header><div className="announcements-content"><nav className="announcement-tabs feed-filter" aria-label="Announcement categories">{categories.map(c=>{const Icon=icons[c as keyof typeof icons];return <button key={c} aria-pressed={category===c} onClick={()=>{setCategory(c);setLimit(20)}}>{c!=='All'&&<Icon size={16}/>} {c}</button>})}</nav><div className="announcement-search"><label><Search size={19}/><input aria-label="Search announcements" placeholder="Search announcements…" value={search} onChange={e=>{setSearch(e.target.value);setLimit(20)}}/></label><button aria-label="Filter announcements" aria-expanded={filters} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={20}/></button></div>{filters&&<div className="announcement-filters"><label><input type="checkbox" checked={pinned} onChange={e=>{setPinned(e.target.checked);setLimit(20)}}/>Pinned only</label><label>Sort<select value={oldest?'oldest':'newest'} onChange={e=>setOldest(e.target.value==='oldest')}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label></div>}<ErrorBox error={error||announcements.error||posts.error||meetings.error||polls.error}/>{notice&&<p role="status">{notice}</p>}{creating&&permissions.includes('ANNOUNCEMENT_CREATE')&&<section className="announcement-form"><header><h2>Create announcement</h2><button aria-label="Cancel announcement" onClick={()=>setParams({})}><X/></button></header><MutationForm label="Publish announcement" onSubmit={d=>api.send(base+'/announcements',{title:d.title,body:d.body,isPinned:d.pinned==='yes'})} onSuccess={()=>{setParams({});setNotice('Announcement published.')}}><Field name="title" label="Title"/><Field name="body" label="Announcement" type="textarea"/><label><input type="checkbox" name="pinned" value="yes"/>Pin as important</label></MutationForm></section>}
 {announcements.isPending||posts.isPending||meetings.isPending||polls.isPending?<Loading/>:<div className="announcement-list">{!filtered.length&&<p className="empty">No announcements match your filters.</p>}{filtered.slice(0,limit).map(e=>{const {r,category:c}=e,Icon=icons[c as keyof typeof icons],author=[r.FirstName,r.LastName].filter(Boolean).join(' ')||name;return <article className={'announcement-card category-'+c.toLowerCase()} key={e.kind+str(r.Id)}><div className="announcement-card-top"><span className="announcement-symbol"><Icon/></span><div className="announcement-copy"><div className="announcement-meta"><span className="announcement-category"><Icon size={14}/>{c==='Events'?'Event':c}</span>{!!r.IsPinned&&<span className="announcement-pin"><Pin size={13}/>Pinned</span>}<details><summary aria-label={'Options for '+str(r.Title||'announcement')}><MoreVertical size={18}/></summary><button onClick={()=>void share(e)}><Share2 size={16}/>Share</button></details></div><Link className="announcement-title" to={link(e)}>{str(r.Title)||'Community update'}</Link><p className="announcement-excerpt">{str(r.Body||r.Description)}</p><Link className="announcement-author" to={r.CreatedBy?'/member/'+r.CreatedBy:'/community/'+id+'/profile'}>{r.ProfileImage?<img src={api.asset(str(r.ProfileImage))} alt=""/>:<span>{author.slice(0,1)}</span>}<div>By <strong>{author}</strong><small>{r.CreatedAt?new Date(str(r.CreatedAt)).toLocaleDateString(getLocale(),{day:'numeric',month:'short',year:'numeric'}):'Community announcement'}</small></div></Link></div></div><PostMedia post={r}/><footer>{e.kind==='post'?<SocialActions post={r}/>:<button aria-label={'Share '+str(r.Title)} onClick={()=>void share(e)}><Share2 size={17}/>Share</button>}<div><Link className="button" to={link(e)}><FileText size={16}/>{e.kind==='meeting'?'View meeting':e.kind==='poll'?'Open poll':'View details'}</Link>{e.kind==='meeting'&&!!r.AllowCalendar&&<button onClick={()=>void exportCalendar(r).catch(setError)}><CalendarDays size={16}/>Add to Calendar</button>}</div></footer></article>})}{filtered.length>limit&&<button onClick={()=>setLimit(limit+20)}>Show more announcements</button>}</div>}
 <dialog ref={dialog} className="announcement-detail" aria-label="Announcement details" onCancel={()=>setParams({})}>{selected&&<><button aria-label="Close announcement details" onClick={()=>setParams({})}><X/></button><h2>{str(selected.r.Title)}</h2><p>{str(selected.r.Body||selected.r.Description)}</p><button onClick={()=>void share(selected)}><Share2 size={17}/>Share</button></>}</dialog></div></div>
}
