import {HeaderSearch} from './HeaderSearch';
import {useState,useRef,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Capacitor} from '@capacitor/core';
import {Filesystem,Directory,Encoding} from '@capacitor/filesystem';
import {Share} from '@capacitor/share';
import {ArrowLeft,CalendarDays,MapPin,ShieldCheck,Users,Lightbulb,Download,Search,SlidersHorizontal,CheckCircle2,Clock,XCircle,ChevronRight} from 'lucide-react';
import {api,rows,str,type RecordData} from './api';
import {ErrorBox,Loading} from './ui';
import {getLocale} from './i18n';
const date=(v:unknown)=>new Date(str(v));
const when=(m:RecordData)=>date(m.StartDateTime).toLocaleString(getLocale(),{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
async function csvExport(meetings:RecordData[]){const cell=(v:unknown)=>'"'+str(v).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const csv='\uFEFF'+[['Meeting','Starts','Ends','My status'],...meetings.map(m=>[m.Title,m.StartDateTime,m.EndDateTime,m.MyStatus||'Not marked'])].map(row=>row.map(cell).join(',')).join('\r\n');const name='attendance-'+new Date().toISOString().slice(0,10)+'.csv';if(Capacitor.isNativePlatform()){const file=await Filesystem.writeFile({path:name,data:csv,directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:'Attendance history',files:[file.uri]});}else{const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
export function Attendance({id}:{id:string}){const base='/communities/'+id+'/attendance',qc=useQueryClient(),q=useQuery({queryKey:[base],queryFn:()=>api.get<RecordData>(base)}),[tab,setTab]=useState('mark'),[code,setCode]=useState(''),[error,setError]=useState<unknown>(),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filters,setFilters]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState(''),[status,setStatus]=useState('all'),[now,setNow]=useState(Date.now);const inputs=useRef<(HTMLInputElement|null)[]>([]),meetings=rows(q.data?.meetings),available=meetings.filter(m=>date(m.EndDateTime).getTime()>now),current=[...available].sort((a,b)=>date(a.StartDateTime).getTime()-date(b.StartDateTime).getTime())[0],visible=meetings.filter(m=>date(m.EndDateTime).getTime()<=now&&(!search||str(m.Title).toLowerCase().includes(search.toLowerCase()))&&(!from||date(m.StartDateTime)>=new Date(from+'T00:00:00'))&&(!to||date(m.StartDateTime)<=new Date(to+'T23:59:59.999'))&&(status==='all'||(status==='attended'?['PRESENT','LATE'].includes(str(m.MyStatus)):m.MyStatus==='ABSENT'))).sort((a,b)=>date(b.StartDateTime).getTime()-date(a.StartDateTime).getTime());const canCheckIn=available.some(m=>date(m.StartDateTime).getTime()<=now);const total=(status:string)=>visible.filter(m=>m.MyStatus===status).length;useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),30000);return()=>window.clearInterval(timer)},[]);
 async function mark(){if(!canCheckIn||busy||!/^\d{6}$/.test(code))return;setBusy(true);setError(undefined);setMessage('');try{const r=await api.send<RecordData>(base+'/mark',{code});const matched=meetings.find(m=>m.Id===r.meetingId);setMessage('Attendance recorded'+(matched?' for '+str(matched.Title):'')+(r.status==='LATE'?' (late).':'.'));setCode('');await qc.invalidateQueries({queryKey:[base]});if(r.meetingId)await qc.invalidateQueries({queryKey:['/meetings/'+str(r.meetingId)+'/attendance']});}catch(e){setError(e)}finally{setBusy(false)}}
 return <div className="attendance-page"><ErrorBox error={q.error||error}/>{message&&<p role="status" className="attendance-success">{message}</p>}{q.isPending?<Loading/>:tab==='mark'?<><h2>Mark Attendance</h2><p>Enter the meeting code to mark your attendance.</p>{current?<article className="attendance-meeting"><CalendarDays/><div><h3>{str(current.Title)}</h3><p><CalendarDays size={16}/>{when(current)} – {date(current.EndDateTime).toLocaleTimeString(getLocale(),{hour:'2-digit',minute:'2-digit'})}</p><p><MapPin size={16}/>{str(current.Location)||'Online meeting'}</p>{Number(current.MyAttendance)>0&&<strong>Your attendance has been recorded.</strong>}</div></article>:<p className="attendance-empty">No upcoming or ongoing meetings are available.</p>}<form className="attendance-code-panel" onSubmit={e=>{e.preventDefault();void mark()}}><ShieldCheck size={36}/><h2>Enter Meeting Code</h2><p>{current&&!canCheckIn?'Check-in opens at the scheduled meeting start time.':'Enter the 6-digit code shown by the organiser.'}</p><div className="attendance-digits">{Array.from({length:6},(_,i)=><input key={i} ref={el=>{inputs.current[i]=el}} aria-label={'Code digit '+(i+1)} type="text" inputMode="numeric" autoComplete={i===0?'one-time-code':'off'} pattern="[0-9]*" maxLength={6} value={(code[i]||'').trim()} disabled={!canCheckIn||busy} onFocus={e=>e.target.select()} onPaste={e=>{e.preventDefault();const digits=e.clipboardData.getData('text').replace(/\D/g,'').slice(0,6);setCode(digits);inputs.current[Math.min(digits.length,5)]?.focus()}} onChange={e=>{const digits=e.target.value.replace(/\D/g,'');if(digits.length>1){setCode(digits.slice(0,6));inputs.current[Math.min(digits.length,5)]?.focus()}else{setCode((code.slice(0,i).padEnd(i,' ')+(digits||' ')+code.slice(i+1)).slice(0,6).trimEnd());if(digits)inputs.current[Math.min(i+1,5)]?.focus()}}} onKeyDown={e=>{if(e.key==='Backspace'&&!code[i]?.trim()&&i>0)inputs.current[i-1]?.focus();if(e.key==='ArrowLeft'&&i>0)inputs.current[i-1]?.focus();if(e.key==='ArrowRight'&&i<5)inputs.current[i+1]?.focus()}}/>)}</div><p><ShieldCheck size={17}/>Your attendance will be securely recorded.</p><button className="primary" disabled={!canCheckIn||busy||!/^\d{6}$/.test(code)}>{busy?'Recording…':'Mark Attendance'}</button></form><aside className="attendance-info"><Users/><div><strong>Only community members can mark attendance</strong><p>Use your registered account and a valid meeting code.</p></div></aside><aside className="attendance-info tip"><Lightbulb/><div><strong>Tip</strong><p>Codes are specific to each meeting and can expire. Ask the organiser for the current code.</p></div></aside></>:<>
 <h2>Attendance History</h2><section className="attendance-panel"><div className="attendance-stats">{([[CalendarDays,'Meetings',visible.length],[CheckCircle2,'Present',total('PRESENT')],[Clock,'Late',total('LATE')],[XCircle,'Absent',total('ABSENT')]] as const).map(([Icon,label,value])=><div key={label}><Icon/><span>{label}</span><strong>{value}</strong></div>)}</div><p className="attendance-caption">Your attendance in completed meetings. Unmarked attendance is not counted as absent.</p></section><div className="attendance-search attendance-search-actions"><HeaderSearch label="Search"><label><Search size={18}/><input aria-label="Search meetings" placeholder="Search meetings…" value={search} onChange={e=>setSearch(e.target.value)}/></label></HeaderSearch><button className="attendance-filter-icon" aria-label="Date & status filters" title="Date & status filters" aria-expanded={filters} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={20}/></button><button aria-label="Export attendance" title="Export attendance" disabled={!visible.length||busy} onClick={async()=>{setBusy(true);try{await csvExport(visible)}catch(e){setError(e)}finally{setBusy(false)}}}><Download size={20}/></button></div>{filters&&<div className="attendance-filter-grid"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label><label>My attendance<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All meetings</option><option value="attended">Attended</option><option value="absent">Recorded absent</option></select></label><button onClick={()=>{setFrom('');setTo('');setStatus('all');setSearch('')}}>Clear filters</button></div>}<section className="attendance-panel attendance-history"><h3>Meetings ({visible.length})</h3>{visible.length?visible.map(m=>{const state=str(m.MyStatus),label=state==='PRESENT'?'Present':state==='LATE'?'Late':state==='ABSENT'?'Absent':'Not marked',Icon=state==='PRESENT'?CheckCircle2:state==='LATE'?Clock:state==='ABSENT'?XCircle:Users;return <article className="attendance-history-row attendance-personal-row" key={str(m.Id)}><span className="attendance-row-icon"><CalendarDays/></span><div className="attendance-history-title"><strong>{str(m.Title)}</strong><small>{when(m)}</small></div><span className={'attendance-personal-status status-'+state.toLowerCase()}><Icon size={17}/>{label}</span></article>}):<p className="attendance-empty">No completed meetings match your filters.</p>}</section></>}</div>
}
