import {LocationFields} from './LocationFields';
import {authDestination,authLink} from './CommunityInvitation';
import {VerificationCode} from './VerificationCode';
import {useState,useSyncExternalStore} from 'react';
import {Link,Navigate,Outlet,useNavigate} from 'react-router-dom';
import {api,session,type Session} from './api';
import {Field,MutationForm} from './ui';
import {PhoneField} from './PhoneField';
export const useSession=()=>useSyncExternalStore(session.subscribe,session.get,()=>null);
export function Protected(){return useSession()?<Outlet/>:<Navigate to={authLink("/login")} replace/>}
export function Welcome(){return <main className="welcome"><section className="welcome-story"><div className="welcome-story-content"><p className="eyebrow">BELONG. PARTICIPATE. MAKE A DIFFERENCE.</p><h1>CDA Connect: a place for your community.</h1><p>Stay informed, connect with neighbours and take part in the decisions that matter.</p><div className="welcome-points"><Link to={authLink("/register")}>Community conversations</Link><Link to={authLink("/register")}>Meetings & decisions</Link><Link to={authLink("/register")}>Resources & support</Link></div></div></section><section className="welcome-entry"><div className="welcome-mobile-visual"><div className="welcome-mobile-brand"><img className="welcome-mobile-logo" src="/brand-logo.png" alt=""/><img className="welcome-mobile-wordmark" src="/brand-wordmark.png" alt="CDA Connect"/><p className="welcome-mobile-tagline">Stronger communities,<br/>better together.</p></div></div><div className="welcome-entry-content"><BrandLink/><p className="eyebrow welcome-desktop-copy">WELCOME TO CDA CONNECT</p><h2 className="welcome-desktop-copy">Your community starts here.</h2><p className="welcome-desktop-copy">One account. All your communities.</p><div className="welcome-actions"><Link className="primary button" to={authLink("/register")}><span className="welcome-mobile-label">Get started</span><span className="welcome-desktop-label">Create an account</span></Link><p>Already have an account? <Link to={authLink("/login")}>Sign in</Link></p></div></div></section></main>}
function BrandLink(){return <Link className="brand desktop-auth-brand" to="/" aria-label="CDA Connect home"><img className="brand-logo" src="/brand-logo.png" alt=""/><img className="brand-wordmark" src="/brand-wordmark.png" alt="CDA Connect"/></Link>}
export function AuthLayout({children,title,variant='default'}:{children:React.ReactNode;title:string;variant?:'default'|'login'}){const login=variant==='login';return <main className={`auth-page${login?' login-page':''}`}><aside className="auth-visual"><div className="auth-visual-content"><p className="eyebrow">BELONG. PARTICIPATE. MAKE A DIFFERENCE.</p><h1>A place for your community.</h1><p>Stay informed, connect with neighbours and take part in the decisions that matter.</p></div></aside><section className="auth-panel">{login&&<div className="login-mobile-hero"><img src="/brand-logo.png" alt="CDA Connect"/></div>}<div className="auth-panel-content"><BrandLink/><Link className="auth-back" to="/">← Welcome</Link><h2>{title}</h2>{login&&!challengeTitle(title)&&<p className="login-intro">Sign in to your CDA Connect account and continue building stronger communities.</p>}{children}</div></section></main>}
function challengeTitle(title:string){return title==='Verify your sign-in'}
export function Login(){const [returnPath]=useState(authDestination);const nav=useNavigate(),[challenge,setChallenge]=useState('');const s=useSession();if(s)return <Navigate to={returnPath} replace/>;return <AuthLayout title={challenge?'Verify your sign-in':'Welcome back'} variant="login"><MutationForm label={challenge?'Verify and sign in':'Log in'} onSubmit={async data=>{const result=await api.send<Session&{requiresTwoFactor?:boolean;challengeToken?:string}>(challenge?'/auth/login/two-factor':'/auth/login',challenge?{challengeToken:challenge,code:data.code}:data);if(result.requiresTwoFactor){setChallenge(result.challengeToken!);return}session.set(result);nav(returnPath,{replace:true})}}>{challenge?<Field name="code" label="Six-digit verification code"/>:<><Field name="email" label="Email address" type="email"/><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><p className="login-forgot"><Link to="/forgot-password">Forgot password?</Link></p></>}</MutationForm>{challenge&&<button type="button" onClick={()=>setChallenge('')}>Use a different account</button>}<p className="login-signup">Don’t have an account? <Link to={authLink("/register")}>Sign up</Link></p></AuthLayout>}
export function Register(){const[method,setMethod]=useState<'sms'|'email'>('sms'),[busy,setBusy]=useState(false);return <AuthLayout title="Create your account"><div className="verification-switch" role="group" aria-label="Verification method"><button type="button" aria-pressed={method==='sms'} disabled={busy} onClick={()=>setMethod('sms')}>SMS</button><button type="button" aria-pressed={method==='email'} disabled={busy} onClick={()=>setMethod('email')}>Email</button></div><RegisterFlow key={method} method={method} setBusy={setBusy}/><p>Already registered? <Link to={authLink("/login")}>Sign in</Link></p></AuthLayout>}
function RegisterFlow({method,setBusy}:{method:'sms'|'email';setBusy:(value:boolean)=>void}){
 const [returnPath]=useState(authDestination);const nav=useNavigate(),[destination,setDestination]=useState(''),[token,setToken]=useState('');const email=method==='email',kind=email?'email':'phone';
 async function run(action:()=>Promise<void>){setBusy(true);try{await action()}finally{setBusy(false)}}
 return !destination?<MutationForm label="Send verification code" onSubmit={d=>run(async()=>{const value=email?d.email.trim().toLowerCase():d.phone;await api.send('/auth/'+kind+'-verification/request',{[kind]:value});setDestination(value)})}>{email?<Field name="email" label="Email address" type="email"/>:<PhoneField/>}<small>We’ll send a six-digit code by {email?'email':'SMS'} to verify your account.</small></MutationForm>:!token?<><p>Enter the code sent to {destination}.{email&&' Check your spam folder if it does not arrive.'}</p><MutationForm label={email?'Verify email':'Verify phone'} onSubmit={d=>run(async()=>{const result=await api.send<{verificationToken:string}>('/auth/'+kind+'-verification/verify',{[kind]:destination,code:d.code});setToken(result.verificationToken)})}><VerificationCode/></MutationForm><button type="button" onClick={()=>setDestination('')}>Change {kind} or request another code</button></>:<MutationForm label="Create account" onSubmit={d=>run(async()=>{if(d.password!==d.confirmPassword)throw Error('Passwords do not match.');const{confirmPassword,...raw}=d;const body=Object.fromEntries(Object.entries(raw).filter(([,value])=>value!==''));const result=await api.send<Session>('/auth/register',{...body,verificationMethod:method,...(email?{email:destination,emailVerificationToken:token}:{phone:destination,phoneVerificationToken:token})});session.set(result);nav(returnPath,{replace:true})})}><p className="success">{email?'Email':'Phone number'} verified: {destination}</p><div className="form-grid"><Field name="firstName" label="First name"/><Field name="lastName" label="Last name"/></div>{!email&&<Field name="email" label="Email" type="email"/>}<LocationFields required/><Field name="postcode" label="Postcode" required={false}/><Field name="address" label="Area or community address"/><Field name="dateOfBirth" label="Date of birth" type="date"/><Field name="password" label="Password (at least 8 characters)" type="password"/><Field name="confirmPassword" label="Confirm password" type="password"/></MutationForm>
}
export function Recovery(){const[token,setToken]=useState(''),[done,setDone]=useState(false);return <AuthLayout title="Reset your password">{done?<><p>Password changed. Sign in with your new password.</p><Link to={authLink("/login")}>Go to sign in</Link></>:<MutationForm label={token?'Reset password':'Send reset code'} onSubmit={async d=>{if(!token){const r=await api.send<{resetToken:string}>('/auth/password-reset/request',{email:d.email.trim().toLowerCase()});setToken(r.resetToken)}else{await api.send('/auth/password-reset/complete',{...d,resetToken:token});setDone(true)}}}>{token?<><Field name="code" label="Verification code"/><Field name="newPassword" label="New password" type="password"/><p className="muted">Use 8 or more characters including uppercase, lowercase, number and symbol.</p></>:<><Field name="email" label="Registered email address" type="email"/><p className="muted">We’ll send a six-digit reset code to your email address. Check your spam folder if it does not arrive.</p></>}</MutationForm>}</AuthLayout>}



