import {LocationFields} from './LocationFields';
import {authDestination,authLink} from './CommunityInvitation';
import {VerificationCode} from './VerificationCode';
import {useCallback,useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {Link,Navigate,Outlet,useLocation,useNavigate} from 'react-router-dom';
import {App as NativeApp} from '@capacitor/app';
import {Capacitor} from '@capacitor/core';
import {Eye,EyeOff,Fingerprint,LogOut} from 'lucide-react';
import {api,session,type Session} from './api';
import {Field,MutationForm} from './ui';
import {disconnectPush} from './push';
import {authenticateBiometric,biometricLock,getBiometricEnabled} from './sessionSecurity';
export const useSession=()=>useSyncExternalStore(session.subscribe,session.get,()=>null);
export function Protected(){
 const current=useSession(),locked=useSyncExternalStore(biometricLock.subscribe,biometricLock.get,()=>false),nav=useNavigate(),ending=useRef(false);
 const endSession=useCallback(async()=>{if(ending.current)return;ending.current=true;const revoke=Promise.allSettled([disconnectPush(),api.send('/auth/logout',{})]);await Promise.race([revoke,new Promise(resolve=>window.setTimeout(resolve,2000))]);session.set(null);nav('/login',{replace:true})},[nav]);
 useEffect(()=>{if(!current||!Capacitor.isNativePlatform())return;let disposed=false,handle:{remove:()=>Promise<void>}|undefined;void NativeApp.addListener('appStateChange',state=>{if(!state.isActive)biometricLock.lock()}).then(value=>{if(disposed)void value.remove();else handle=value});return()=>{disposed=true;void handle?.remove()}},[current]);
 if(!current)return <Navigate to={authLink("/login")} replace/>;
 if(getBiometricEnabled()&&locked)return <BiometricGate onSignOut={()=>endSession()}/>;
 return <Outlet/>;
}
function BiometricGate({onSignOut}:{onSignOut:()=>Promise<void>}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),attempted=useRef(false);
 const unlock=useCallback(async()=>{if(busy)return;setBusy(true);setError('');try{await authenticateBiometric()}catch(e){const message=e instanceof Error?e.message:'';if(!/cancel/i.test(message))setError(message||'Your identity could not be verified. Try again.')}finally{setBusy(false)}},[busy]);
 useEffect(()=>{if(!attempted.current){attempted.current=true;void unlock()}},[unlock]);
 return <main className="session-gate"><div className="session-gate-icon"><Fingerprint size={42}/></div><h1>Unlock CDA Connect</h1><p>Use your phone's Face ID, fingerprint or screen lock to continue.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" type="button" disabled={busy} onClick={()=>void unlock()}>{busy?'Waiting for your phone...':'Unlock'}</button><button className="session-gate-signout" type="button" disabled={busy} onClick={()=>void onSignOut()}><LogOut size={18}/>Sign in with another account</button></main>;
}
export function Welcome(){return <main className="welcome"><section className="welcome-story"><div className="welcome-story-content"><p className="eyebrow">BELONG. PARTICIPATE. MAKE A DIFFERENCE.</p><h1>CDA Connect: a place for your community.</h1><p>Stay informed, connect with neighbours and take part in the decisions that matter.</p><div className="welcome-points"><Link to={authLink("/register")}>Community conversations</Link><Link to={authLink("/register")}>Meetings & decisions</Link><Link to={authLink("/register")}>Resources & support</Link></div></div></section><section className="welcome-entry"><div className="welcome-mobile-visual"><div className="welcome-mobile-brand"><img className="welcome-mobile-logo" src="/brand-logo.webp" width="112" height="101" decoding="async" fetchPriority="high" alt=""/><img className="welcome-mobile-wordmark" src="/brand-wordmark.webp" width="250" height="83" decoding="async" fetchPriority="high" alt="CDA Connect"/><p className="welcome-mobile-tagline">Stronger communities,<br/>better together.</p></div></div><div className="welcome-entry-content"><BrandLink/><p className="eyebrow welcome-desktop-copy">WELCOME TO CDA CONNECT</p><h2 className="welcome-desktop-copy">Your community starts here.</h2><p className="welcome-desktop-copy">One account. All your communities.</p><div className="welcome-actions"><Link className="primary button" to={authLink("/register")}><span className="welcome-mobile-label">Get started</span><span className="welcome-desktop-label">Create an account</span></Link><p>Already have an account? <Link to={authLink("/login")}>Sign in</Link></p></div></div></section></main>}
function BrandLink(){return <Link className="brand desktop-auth-brand" to="/" aria-label="CDA Connect home"><img className="brand-logo" src="/brand-logo.webp" width="52" height="47" decoding="async" alt=""/><img className="brand-wordmark" src="/brand-wordmark.webp" width="230" height="77" decoding="async" alt="CDA Connect"/></Link>}
export function AuthLayout({children,title,variant='default'}:{children:React.ReactNode;title:string;variant?:'default'|'login'}){const login=variant==='login';return <main className={`auth-page${login?' login-page':''}`}><aside className="auth-visual"><div className="auth-visual-content"><p className="eyebrow">BELONG. PARTICIPATE. MAKE A DIFFERENCE.</p><h1>A place for your community.</h1><p>Stay informed, connect with neighbours and take part in the decisions that matter.</p></div></aside><section className="auth-panel">{login&&<div className="login-mobile-hero"><img src="/brand-logo.webp" width="160" height="144" decoding="async" fetchPriority="high" alt="CDA Connect"/></div>}<div className="auth-panel-content"><BrandLink/><Link className="auth-back" to="/">← Welcome</Link><h2>{title}</h2>{login&&!challengeTitle(title)&&<p className="login-intro">Sign in to your CDA Connect account and continue building stronger communities.</p>}{children}</div></section></main>}
function challengeTitle(title:string){return title==='Verify your sign-in'}
export function Login(){const [returnPath]=useState(authDestination);const nav=useNavigate(),location=useLocation(),[challenge,setChallenge]=useState(''),[showPassword,setShowPassword]=useState(false);const s=useSession(),notice=(location.state as {notice?:string}|null)?.notice;if(s)return <Navigate to={returnPath} replace/>;return <AuthLayout title={challenge?'Verify your sign-in':'Welcome back'} variant="login">{notice&&<p className="session-notice" role="status">{notice}</p>}<MutationForm label={challenge?'Verify and sign in':'Log in'} onSubmit={async data=>{const result=await api.send<Session&{requiresTwoFactor?:boolean;challengeToken?:string}>(challenge?'/auth/login/two-factor':'/auth/login',challenge?{challengeToken:challenge,code:data.code}:data);if(result.requiresTwoFactor){setChallenge(result.challengeToken!);return}biometricLock.unlock();session.set(result);nav(returnPath,{replace:true})}}>{challenge?<Field name="code" label="Six-digit verification code"/>:<><Field name="email" label="Email address" type="email"/><div className="login-password-field"><label htmlFor="login-password">Password</label><div className="login-password-input"><input id="login-password" name="password" type={showPassword?'text':'password'} required autoComplete="current-password"/><button className="login-password-toggle" type="button" aria-label={showPassword?'Hide password':'Show password'} aria-pressed={showPassword} onClick={()=>setShowPassword(value=>!value)}>{showPassword?<EyeOff size={21}/>:<Eye size={21}/>}</button></div></div><p className="login-forgot"><Link to="/forgot-password">Forgot password?</Link></p></>}</MutationForm>{challenge&&<button type="button" onClick={()=>setChallenge('')}>Use a different account</button>}<p className="login-signup">Don't have an account? <Link to={authLink("/register")}>Sign up</Link></p></AuthLayout>}
export function Register(){return <AuthLayout title="Create your account"><RegisterFlow/><p>Already registered? <Link to={authLink("/login")}>Sign in</Link></p></AuthLayout>}
function RegisterFlow(){
 const [returnPath]=useState(authDestination);const nav=useNavigate(),[destination,setDestination]=useState(''),[token,setToken]=useState(''),[busy,setBusy]=useState(false);
 async function run(action:()=>Promise<void>){setBusy(true);try{await action()}finally{setBusy(false)}}
 return !destination?<MutationForm label="Send verification code" onSubmit={d=>run(async()=>{const email=d.email.trim().toLowerCase();await api.send('/auth/email-verification/request',{email});setDestination(email)})}><Field name="email" label="Email address" type="email"/><small>We'll send a six-digit code by email to verify your account. Check your spam folder if it does not arrive.</small></MutationForm>:!token?<><p>Enter the code sent to {destination}. Check your spam folder if it does not arrive.</p><div className="registration-verification-actions"><MutationForm label="Verify email" onSubmit={d=>run(async()=>{const result=await api.send<{verificationToken:string}>('/auth/email-verification/verify',{email:destination,code:d.code});setToken(result.verificationToken)})}><VerificationCode/></MutationForm><button type="button" disabled={busy} onClick={()=>setDestination('')}>Change email or request another code</button></div></>:<MutationForm label="Create account" onSubmit={d=>run(async()=>{if(d.password!==d.confirmPassword)throw Error('Passwords do not match.');const{confirmPassword,...raw}=d;const body=Object.fromEntries(Object.entries(raw).filter(([,value])=>value!==''));const result=await api.send<Session>('/auth/register',{...body,email:destination,verificationMethod:'email',emailVerificationToken:token});biometricLock.unlock();session.set(result);nav(returnPath,{replace:true})})}><p className="success">Email verified: {destination}</p><div className="form-grid"><Field name="firstName" label="First name"/><Field name="lastName" label="Last name"/></div><LocationFields required/><Field name="postcode" label="Postcode" required={false}/><Field name="address" label="Area or community address"/><Field name="dateOfBirth" label="Date of birth" type="date"/><Field name="password" label="Password (at least 8 characters)" type="password"/><Field name="confirmPassword" label="Confirm password" type="password"/></MutationForm>
}
export function Recovery(){const[token,setToken]=useState(''),[done,setDone]=useState(false);return <AuthLayout title="Reset your password">{done?<><p>Password changed. Sign in with your new password.</p><Link to={authLink("/login")}>Go to sign in</Link></>:<MutationForm label={token?'Reset password':'Send reset code'} onSubmit={async d=>{if(!token){const r=await api.send<{resetToken:string}>('/auth/password-reset/request',{email:d.email.trim().toLowerCase()});setToken(r.resetToken)}else{await api.send('/auth/password-reset/complete',{...d,resetToken:token});setDone(true)}}}>{token?<><Field name="code" label="Verification code"/><Field name="newPassword" label="New password" type="password"/><p className="muted">Use 8 or more characters including uppercase, lowercase, number and symbol.</p></>:<><Field name="email" label="Registered email address" type="email"/><p className="muted">We’ll send a six-digit reset code to your email address. Check your spam folder if it does not arrive.</p></>}</MutationForm>}</AuthLayout>}



