import {useEffect,useRef,useState} from 'react';
import {useParams} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {io,type Socket} from 'socket.io-client';
import {useSession} from './auth';
import {socketOrigin,api,rows,str,type RecordData} from './api';
import {Page,ErrorBox,Loading} from './ui';
export function Chat(){const{id}=useParams(),s=useSession(),qc=useQueryClient(),socket=useRef<Socket|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false),pending=useRef<{id:string;text:string}|null>(null);const path='/conversations/'+id+'/messages';const q=useQuery({queryKey:[path],queryFn:({signal})=>api.get<unknown>(path,signal)});useEffect(()=>{if(!s)return;const sock=io(socketOrigin(),{auth:{token:s.accessToken},autoConnect:false});socket.current=sock;const join=()=>{setConnected(true);sock.emit('conversation:join',{conversationId:id});void qc.invalidateQueries({queryKey:[path]})};sock.on('connect',join);sock.on('disconnect',()=>setConnected(false));sock.on('connect_error',()=>setError('Chat connection failed. Retry when your connection is available.'));sock.on('message:new',(r:RecordData)=>{if(r.ConversationId===id)void qc.invalidateQueries({queryKey:[path]})});sock.connect();return()=>{sock.emit('conversation:leave',{conversationId:id});sock.disconnect();socket.current=null}},[id,s?.accessToken,qc,path]);function send(){if(!socket.current?.connected||!text.trim()||busy)return;const draft=pending.current?.text===text?pending.current:{id:crypto.randomUUID(),text};pending.current=draft;setBusy(true);setError('');socket.current.timeout(12000).emit('message:send',{conversationId:id,clientMessageId:draft.id,messageText:draft.text},(timeout:Error|null,response?:{ok:boolean;error?:string})=>{setBusy(false);if(timeout||!response?.ok){setError(response?.error||'Delivery not confirmed. Retry without changing the text to reuse its message ID.');return}pending.current=null;setText('');void qc.invalidateQueries({queryKey:[path]});});}return <Page title="Conversation" subtitle={connected?'Connected':'Connecting…'}><div className="chat-thread" aria-live="polite">{q.isPending?<Loading/>:<ErrorBox error={q.error}/ >}{rows(q.data).map(m=><article className={'message '+(m.SenderUserId===s?.user.Id?'mine':'')} key={str(m.Id)}><strong>{str(m.FirstName)} {str(m.LastName)}</strong><p>{str(m.MessageText)}</p><small>{m.CreatedAt?new Date(str(m.CreatedAt)).toLocaleTimeString():''}</small></article>)}</div><form className="composer" onSubmit={e=>{e.preventDefault();send()}}><label className="sr-only" htmlFor="chat-message">Message</label><textarea id="chat-message" value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message" rows={2}/><button className="primary" disabled={!connected||busy||!text.trim()}>{busy?'Sending…':'Send'}</button></form>{error&&<p className="error" role="alert">{error}</p>}</Page>}

