import {useEffect,useRef,useState,type MouseEvent as ReactMouseEvent,type PointerEvent,type ReactNode} from 'react';
import {Copy,Forward,MessageSquareReply,NotebookPen,Star,Trash2,Flag} from 'lucide-react';
import {api,rows,str,type RecordData} from './api';

export function ChatMessageActions({message,conversationId,communityId,mine,children,onReply,onChanged,onStatus}:{message:RecordData;conversationId:string;communityId:string;mine:boolean;children:ReactNode;onReply:(message:RecordData)=>void;onChanged:()=>void;onStatus:(value:string)=>void}){
 const [open,setOpen]=useState(false),[forwarding,setForwarding]=useState(false),[conversations,setConversations]=useState<RecordData[]>([]),[busy,setBusy]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),start=useRef<{x:number;y:number}|undefined>(undefined),suppressClickUntil=useRef(0);
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 function begin(event:PointerEvent){if(open||!event.isPrimary||(event.pointerType==='mouse'&&event.button!==0))return;start.current={x:event.clientX,y:event.clientY};clearTimeout(timer.current);timer.current=setTimeout(()=>{suppressClickUntil.current=Date.now()+750;start.current=undefined;if('vibrate' in navigator)navigator.vibrate(12);setOpen(true)},500)}
 function move(event:PointerEvent){if(start.current&&Math.hypot(event.clientX-start.current.x,event.clientY-start.current.y)>10){clearTimeout(timer.current);start.current=undefined}}
 function cancel(){clearTimeout(timer.current);start.current=undefined}
 function blockHeldClick(event:ReactMouseEvent){if(Date.now()>suppressClickUntil.current)return;event.preventDefault();event.stopPropagation()}
 async function change(path:string,body:unknown,method='PUT'){setBusy(true);try{await api.send(`/conversations/${conversationId}/messages/${str(message.Id)}/${path}`,body,method);setOpen(false);onChanged()}catch(error){onStatus(error instanceof Error?error.message:'Unable to update this message.')}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(str(message.MessageText));onStatus('Message copied.');setOpen(false)}catch{onStatus('Copy is unavailable on this device.')}}
 async function note(){const value=window.prompt('Add a private note for this message',str(message.MyNote));if(value===null)return;await change('note',{note:value})}
 async function report(){const details=window.prompt('Tell us why you are reporting this message. Do not include sensitive information.','');if(details===null)return;if(!details.trim()){onStatus('Enter a reason for the report.');return}await change('report',{reason:'OTHER',details:details.trim()},'POST');onStatus('Message reported for review.')}
 async function remove(){if(!window.confirm('Delete this message?'))return;await change('',{},'DELETE')}
 async function showForward(){setBusy(true);try{setConversations(rows(await api.get(`/communities/${communityId}/conversations`)).filter(item=>str(item.Id)!==conversationId));setForwarding(true)}catch(error){onStatus(error instanceof Error?error.message:'Unable to load conversations.')}finally{setBusy(false)}}
 async function forward(target:string){await change('forward',{targetConversationId:target},'POST');onStatus('Message forwarded.')}
 return <div className="chat-message-action-anchor" onPointerDown={begin} onPointerMove={move} onPointerUp={cancel} onPointerCancel={cancel} onClickCapture={blockHeldClick} onDragStart={event=>event.preventDefault()} onContextMenu={event=>event.preventDefault()}>{children}{open&&<div className="message-action-scrim" role="presentation" onPointerDown={event=>{event.stopPropagation();if(event.target===event.currentTarget)setOpen(false)}}><section className="message-action-menu" role="dialog" aria-modal="true" aria-label="Message options">{forwarding?<div className="message-forward-list"><strong>Forward to</strong>{conversations.length?conversations.map(item=><button key={str(item.Id)} disabled={busy} onClick={()=>void forward(str(item.Id))}>{str(item.Type)==='DIRECT'?str(item.DirectName)||str(item.Name):str(item.Name)}</button>):<p>No other conversations are available.</p>}<button onClick={()=>setForwarding(false)}>Back</button></div>:<div className="message-action-list"><button onClick={()=>{onReply(message);setOpen(false)}}><MessageSquareReply/>Reply</button><button disabled={busy||!str(message.MessageText)} onClick={()=>void showForward()}><Forward/>Forward</button><button disabled={!str(message.MessageText)} onClick={()=>void copy()}><Copy/>Copy</button><button disabled={busy} onClick={()=>void note()}><NotebookPen/>Add text to note</button><button disabled={busy} onClick={()=>void change('star',{starred:!message.MyStarred})}><Star fill={message.MyStarred?'currentColor':'none'}/>{message.MyStarred?'Unstar':'Star'}</button>{mine?<button className="danger" disabled={busy} onClick={()=>void remove()}><Trash2/>Delete</button>:<button className="danger" disabled={busy} onClick={()=>void report()}><Flag/>Report</button>}</div>}</section></div>}</div>
}
