import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {ChevronLeft,ChevronRight} from 'lucide-react';
import {api,rows,str,type RecordData} from './api';
import {ErrorBox,Loading} from './ui';
import {getLocale} from './i18n';
import './community-calendar.css';
const key=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const localDay=(v:unknown)=>{const s=str(v);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:key(new Date(s))};
type Activity={id:string;kind:string;title:string;start:string;end:string;href:string};
const kinds=['Event','Meeting','Poll','Finance'];
export function CommunityCalendar({id,events,search}:{id:string;events:RecordData[];search:string}){
 const base='/communities/'+id,root='/community/'+id;
 const meetings=useQuery({queryKey:[base+'/meetings'],queryFn:()=>api.get<RecordData[]>(base+'/meetings')}),polls=useQuery({queryKey:[base+'/polls'],queryFn:()=>api.get<RecordData[]>(base+'/polls')}),finance=useQuery({queryKey:[base+'/finance/me'],queryFn:()=>api.get<RecordData>(base+'/finance/me')});
 const[today,setToday]=useState(()=>key(new Date())),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[day,setDay]=useState(()=>key(new Date()));
 useEffect(()=>{const refresh=()=>setToday(key(new Date())),timer=setInterval(refresh,60000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh)}},[]);
 const make=(r:RecordData,kind:string,start:unknown,end:unknown,title:unknown,href:string):Activity=>({id:kind+str(r.Id),kind,title:str(title)||kind,start:localDay(start),end:localDay(end||start),href});
 const items=[...events.map(r=>make(r,'Event',r.StartDateTime,r.EndDateTime,r.Title,root+'/events?event='+r.Id)),...rows(meetings.data).map(r=>make(r,'Meeting',r.StartDateTime,r.EndDateTime,r.Title,root+'/meetings?meeting='+r.Id)),...rows(polls.data).map(r=>make(r,'Poll',r.StartAt||r.CreatedAt,r.EndAt,r.Question,'/poll/'+id+'/'+r.Id)),...rows(finance.data?.dues).filter(r=>r.DueDate).map(r=>make(r,'Finance',str(r.DueDate).slice(0,10),null,r.PlanName,root+'/finance?view=pay&ledger='+r.Id))].filter(r=>/^\d{4}-\d{2}-\d{2}$/.test(r.start)&&r.title.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.start.localeCompare(b.start)||a.title.localeCompare(b.title));
 const onDay=(d:string)=>items.filter(r=>r.start<=d&&r.end>=d),offset=(month.getDay()+6)%7,days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),monthStart=key(month),monthEnd=key(new Date(month.getFullYear(),month.getMonth()+1,0)),visible=day?onDay(day):items.filter(r=>r.start<=monthEnd&&r.end>=monthStart);
 function move(n:number){setMonth(new Date(month.getFullYear(),month.getMonth()+n,1));setDay('')}
 return <section className="event-calendar community-calendar"><header><button aria-label="Previous month" onClick={()=>move(-1)}><ChevronLeft size={19}/></button><h2>{month.toLocaleDateString(getLocale(),{month:'long',year:'numeric'})}</h2><button aria-label="Next month" onClick={()=>move(1)}><ChevronRight size={19}/></button></header><div className="calendar-legend"><span className="calendar-today-label">Today</span>{kinds.map(kind=><span key={kind}><i className={'calendar-dot kind-'+kind.toLowerCase()}/>{kind}</span>)}<button onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));setDay(key(now))}}>Today</button></div><ErrorBox error={meetings.error||polls.error||finance.error}/>{(meetings.isPending||polls.isPending||finance.isPending)&&<Loading/>}<div className="event-calendar-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><span key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const d=key(new Date(month.getFullYear(),month.getMonth(),i+1)),entries=onDay(d),types=kinds.filter(k=>entries.some(e=>e.kind===k));return <button key={d} aria-label={d+', '+entries.length+' activities'+(types.length?': '+types.join(', '):'')} aria-current={d===today?'date':undefined} aria-pressed={day===d} onClick={()=>setDay(d)}>{i+1}<span className="calendar-markers" aria-hidden="true">{types.map(k=><i key={k} className={'calendar-dot kind-'+k.toLowerCase()}/>)}</span></button>})}</div><div className="events-section-heading"><h2>{day?'Activities on '+day:'Activities this month'}</h2>{day&&<button onClick={()=>setDay('')}>Whole month</button>}</div><div className="calendar-activities">{visible.map(a=><Link className={'calendar-activity kind-'+a.kind.toLowerCase()} key={a.id} to={a.href}><span>{a.kind}</span><strong>{a.title}</strong><small>{a.start}{a.end!==a.start?' – '+a.end:''}</small></Link>)}</div>{!visible.length&&<p className="events-empty">No activities for this date.</p>}</section>
}
