import {HeaderSearch} from './HeaderSearch';
import './discovery.css';
import {useEffect,useRef,useState} from 'react';
import {useInfiniteQuery,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link,useSearchParams} from 'react-router-dom';
import {Search,SlidersHorizontal,Users,Compass,MapPin,Heart,Bell,MoreHorizontal,Building2,Trophy,Sprout,BriefcaseBusiness,ArrowRight,Plus,ShieldCheck} from 'lucide-react';
import {api,str,type RecordData} from './api';
import {Page,Action,ErrorBox,Loading} from './ui';
import {currentNamedPosition} from './location';
import {isUnreadCommunityActivity} from './communityActivity';
const categories=[['All',Compass],['Residents',Building2],['Sports',Trophy],['Parents',Users],['Youth',Sprout],['Professional',BriefcaseBusiness],['Charity',Heart]] as const;
const profilePath=(c:RecordData,mine=false)=>mine||c.JoinStatus==='MEMBER'?'/community/'+c.Id+'/profile':'/communities?discover=1&preview='+c.Id;
const locationOf=(c:RecordData)=>[c.City||c.LGA,c.State,c.Country].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join(', ');
const count=(n:unknown)=>Number(n||0).toLocaleString();
export function CommunityLogo({community:c}:{community:RecordData}){const[failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[c.LogoUrl]);return <span className="directory-logo">{c.LogoUrl&&!failed?<img src={api.asset(str(c.LogoUrl))} alt="" onError={()=>setFailed(true)}/>:str(c.Name).slice(0,1).toUpperCase()}</span>}
function Card({c,mine=false,hasActivity=false}:{c:RecordData;mine?:boolean;hasActivity?:boolean}){
 const status=str(c.JoinStatus),to=status==='MEMBER'?'/community/'+c.Id+'/feed':mine?'/communities?preview='+c.Id:profilePath(c),qc=useQueryClient(),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
 async function save(){setBusy(true);setError(undefined);try{await api.send('/communities/'+c.Id+'/saved',{saved:!c.IsSaved},'PUT');await qc.invalidateQueries()}catch(e){setError(e)}finally{setBusy(false)}}
 return <article className="directory-card directory-featured directory-direct-card"><Link className="directory-card-link" to={to} aria-label={'Open '+c.Name}><span className="directory-community-mark"><CommunityLogo community={c}/>{hasActivity&&<i className="community-activity-dot" title="New activity" aria-hidden="true"/>}</span><div className="directory-card-content"><strong className="directory-name">{str(c.Name)}</strong>{!!c.IsVerified&&<span className="directory-role"><ShieldCheck size={12}/>Verified</span>}<small className="directory-active">{c.IsPrivate?'Private community':'Public community'}</small><p>{str(c.Description)}</p><small className="directory-location"><MapPin size={13}/>{locationOf(c)}</small><div className="directory-meta"><span><Users size={14}/>{count(c.MemberCount)} members</span>{c.DistanceKm!=null&&<span>{Number(c.DistanceKm).toFixed(1)} km away</span>}</div></div></Link><button className="directory-heart" aria-label={(c.IsSaved?'Unsave ':'Save ')+c.Name} aria-pressed={!!c.IsSaved} title={c.IsSaved?'Unsave community':'Save community'} disabled={busy} onClick={()=>void save()}><Heart size={19} fill={c.IsSaved?'currentColor':'none'}/></button>{status==='PENDING'&&<small className="directory-request-status">Request pending</small>}{status==='REJECTED'&&<small className="directory-request-status">Request declined</small>}{mine&&status==='MEMBER'&&Number(c.PendingRequestCount)>0&&<small className="directory-request-status">{c.PendingRequestCount!=null?<Link to={'/community/'+c.Id+'/members?tab=pending'}>{count(c.PendingRequestCount)} pending {Number(c.PendingRequestCount)===1?'request':'requests'}</Link>:'Member'}</small>}{status==='BANNED'&&<small>Membership restricted</small>}<ErrorBox error={error}/></article>
}

export function Communities(){
 const [params,setParams]=useSearchParams(),discover=params.has('discover'),search=params.get('q')||'',category=params.get('category')||'',preview=params.get('preview');
 const [draft,setDraft]=useState(search),[position,setPosition]=useState<Awaited<ReturnType<typeof currentNamedPosition>>>(),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
 const privacy=useQuery({queryKey:['/users/privacy'],queryFn:()=>api.get<RecordData>('/users/privacy')}),mine=useQuery({queryKey:['/communities/mine/status'],queryFn:()=>api.get<RecordData[]>('/communities/mine/status'),refetchInterval:30000}),notifications=useQuery({queryKey:['/me/notifications'],queryFn:({signal})=>api.get<RecordData[]>('/me/notifications',signal),refetchInterval:()=>document.visibilityState==='visible'&&navigator.onLine?5000:false,refetchOnWindowFocus:true});
 const sharing=!!privacy.data?.ShareLocation,refreshLocation=useRef<()=>void>(()=>{});
 useEffect(()=>setDraft(search),[search]);
 useEffect(()=>{let active=true,inFlight=false;async function refresh(){if(!active||inFlight||!sharing||document.visibilityState==='hidden')return;inFlight=true;setBusy(true);setError(undefined);try{const p=await currentNamedPosition(true);if(active)setPosition(p)}catch(e){if(active){setPosition(undefined);setError(e)}}finally{inFlight=false;if(active)setBusy(false)}}refreshLocation.current=()=>void refresh();if(!sharing){setPosition(undefined);setError(undefined);setBusy(false)}if(discover&&!preview&&sharing)void refresh();const timer=setInterval(()=>{if(discover&&!preview)void refresh()},60000);const onVisible=()=>{if(discover&&!preview)void refresh()};document.addEventListener('visibilitychange',onVisible);return()=>{active=false;clearInterval(timer);document.removeEventListener('visibilitychange',onVisible)}},[discover,preview,sharing]);
 function update(values:Record<string,string>){const next=new URLSearchParams(params);next.delete('area');for(const[k,v]of Object.entries(values))v?next.set(k,v):next.delete(k);setParams(next)}
 const nearby=!!position&&sharing&&!search.trim(),canDiscover=!!search.trim()||nearby;
 const directory=useInfiniteQuery({queryKey:['community-directory',search,category,nearby?position:null],initialPageParam:0,queryFn:({pageParam,signal})=>nearby?api.send<RecordData[]>('/communities/discover/search',{latitude:position!.latitude,longitude:position!.longitude,radius:25,q:'',category,offset:pageParam}):api.get<RecordData[]>('/communities/discover/search?'+new URLSearchParams({q:search,category,offset:String(pageParam)}),signal),getNextPageParam:(last,pages)=>last.length===60?pages.length*60:undefined,enabled:discover&&!preview&&canDiscover});
 const items=discover?(canDiscover?directory.data?.pages.flat()||[]:[]):(mine.data||[]).filter(c=>!search||str(c.Name).toLowerCase().includes(search.toLowerCase()));
 if(preview)return <CommunityPreview id={preview}/>;
 return <Page title="Communities"><div className="directory-page"><nav className="directory-tabs" aria-label="Community views"><button aria-pressed={!discover} onClick={()=>setParams({})}><Users size={18}/>My communities</button><button aria-pressed={discover} onClick={()=>setParams({discover:'1'})}><Compass size={18}/>Discover</button></nav><HeaderSearch label="Search"><form className="directory-search" onSubmit={e=>{e.preventDefault();update({q:draft.trim()})}}><Search size={19}/><input aria-label="Search communities" placeholder="Search by community name…" value={draft} onChange={e=>setDraft(e.target.value)}/><button type="submit">Search</button></form></HeaderSearch>{discover&&<><button className="discovery-city" aria-label="Current city" disabled={busy||privacy.isPending} onClick={()=>{if(sharing)refreshLocation.current()}}><MapPin size={19}/><span>{privacy.isPending?'Checking location preference…':!sharing?'Location is turned off':busy&&!position?'Finding your city…':position?.city||'City unavailable — retry'}</span></button><ErrorBox error={error||privacy.error}/><nav className="directory-categories" aria-label="Community categories">{categories.map(([label,Icon])=><button key={label} aria-pressed={category===(label==='All'?'':label)} onClick={()=>update({category:label==='All'?'':label})}><Icon size={20}/><span>{label}</span></button>)}</nav></>}<section className="directory-section"><header><h2>{discover?(search?'Search results':'Nearby communities'):'My communities'}</h2></header>{discover&&!canDiscover?<p className="directory-empty">{busy?'Finding nearby communities…':sharing?'Your current location is unavailable. Retry using the location icon or search by community name.':'Turn on Share location in Privacy settings to see nearby communities, or search by community name.'}</p>:(discover?directory:mine).isPending?<Loading/>:(discover?directory:mine).error?<ErrorBox error={(discover?directory:mine).error}/>:items.length?<div className="directory-card-grid">{items.map(c=><Card key={str(c.Id)} c={c} mine={!discover} hasActivity={!discover&&(notifications.data||[]).some(item=>isUnreadCommunityActivity(item,str(c.Id)))}/>)}</div>:<p className="directory-empty">{discover&&!search?'No communities with a map position were found within 25 km.':'No communities found.'}</p>}{discover&&canDiscover&&directory.hasNextPage&&<button disabled={directory.isFetchingNextPage} onClick={()=>void directory.fetchNextPage()}>Load more communities</button>}</section></div></Page>
}
function CommunityPreview({id}:{id:string}){
 const qc=useQueryClient(),q=useQuery({queryKey:['/communities/'+id+'/preview'],queryFn:()=>api.get<RecordData>('/communities/'+id+'/preview')}),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
 if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;const c=q.data;
 return <section className="public-community-profile"><div className="public-profile-hero"><div className="public-profile-cover">{c.BannerUrl?<img src={api.asset(str(c.BannerUrl))} alt="Community cover"/>:null}</div><div className="public-profile-intro"><CommunityLogo community={c}/><h1>{str(c.Name)}{!!c.IsVerified&&<span className="public-profile-verified"><ShieldCheck size={14}/>Verified</span>}</h1><p>{str(c.Description)||'Welcome to our community'}</p><p className="public-profile-members"><Users size={16}/>{count(c.MemberCount)} {Number(c.MemberCount)===1?'member':'members'}</p></div></div><dl className="public-profile-facts">{[['Community type',c.CommunityType||c.Category],['Location',[c.SpecificArea,c.LGA||c.City,c.State,c.Country].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join(', ')],['Focus areas',Array.isArray(c.Tags)?c.Tags.join(', '):c.Tags],['Privacy',c.IsPrivate?'Private community':'Public community'],['Established',c.CreatedAt&&Number.isFinite(Date.parse(str(c.CreatedAt)))?new Date(str(c.CreatedAt)).getFullYear():null]].map(([label,value])=><div key={str(label)}><dt>{str(label)}</dt><dd>{str(value)||'Not specified'}</dd></div>)}</dl><section className="public-profile-about"><h2>About our community</h2><p className="prose">{str(c.Description)||'No description added yet.'}</p><h3>Community guidelines</h3><p className="prose">{str(c.Guidelines)||'No community guidelines added yet.'}</p></section><div className="public-profile-join"><ErrorBox error={error}/>{c.JoinStatus==='MEMBER'?<Link className="button primary" to={'/community/'+id+'/profile'}>Open community profile</Link>:c.JoinStatus==='PENDING'?<p role="status">Request pending — an admin, moderator or exco will review it.</p>:c.JoinStatus==='BANNED'?<p>Membership is restricted. Contact the community administrator.</p>:<><p>New members need approval from an admin, moderator or exco.</p><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setError(undefined);try{await api.send('/communities/'+id+'/join-request');await qc.invalidateQueries({queryKey:['/communities/'+id+'/preview']});await qc.invalidateQueries({queryKey:['community-directory']});await qc.invalidateQueries({queryKey:['/communities/mine/status']})}catch(e){setError(e)}finally{setBusy(false)}}}>{busy?'Sending request…':'Request to join'}</button></>}</div></section>
}

