import {HeaderSearch} from './HeaderSearch';
import {refreshInterval,useStoragePreferences,useConnectionType} from './storageDevice';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {Users,UserRound,MessageCirclePlus,Search,MoreHorizontal,BellOff,Bell,LockKeyhole,X} from 'lucide-react';
import {api,str,session,type RecordData} from './api';
import {ErrorBox,Loading,Action} from './ui';
import {getLocale} from './i18n';
const chatName=(c:RecordData)=>str(c.Type==='DIRECT'?c.DirectName||c.Name:c.Name);
const muted=(c:RecordData)=>!!c.MutedUntil&&Date.parse(str(c.MutedUntil))>Date.now();
function Avatar({chat:c}:{chat:RecordData}){const url=c.Type==='DIRECT'?c.DirectImage:c.CommunityImage;return <span className="chat-list-avatar">{url?<img src={api.asset(str(url))} alt=""/>:c.Type==='DIRECT'?<UserRound size={23}/>:<Users size={24}/>}</span>}
function timeLabel(value:unknown){if(!value)return '';const d=new Date(str(value));if(Number.isNaN(d.getTime()))return '';return d.toDateString()===new Date().toDateString()?d.toLocaleTimeString(getLocale(),{hour:'2-digit',minute:'2-digit'}):d.toLocaleDateString(getLocale(),{day:'numeric',month:'short'})}
export function CommunityChats({id,permissions}:{id:string;permissions:string[]}){
 useStoragePreferences();useConnectionType();
 const base='/communities/'+id,nav=useNavigate(),qc=useQueryClient(),searchInput=useRef<HTMLInputElement>(null),editor=useRef<HTMLDivElement>(null);
 const[params,setParams]=useSearchParams(),mode=(params.get('new')==='group'?'group':params.get('new')==='direct'?'direct':undefined),step=params.get('step')==='name'?'name':'members';
 const[searchOpen,setSearchOpen]=useState(false);
 const[tab,setTab]=useState('all'),[search,setSearch]=useState(''),[name,setName]=useState(''),[selected,setSelected]=useState<string[]>([]),[memberSearch,setMemberSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
 const chats=useQuery({queryKey:[base+'/conversations'],queryFn:({signal})=>api.get<RecordData[]>(base+'/conversations',signal),refetchInterval:()=>refreshInterval(15000)}),members=useQuery({queryKey:[base+'/members'],queryFn:({signal})=>api.get<RecordData[]>(base+'/members',signal),refetchInterval:()=>refreshInterval(15000)});
 const canCreate=permissions.includes('CHAT_CREATE'),roster=(members.data||[]).filter(m=>(!m.MembershipStatus||m.MembershipStatus==='ACTIVE')&&str(m.UserId).toLowerCase()!==str(session.get()?.user.Id).toLowerCase()).map(m=>{const existing=(chats.data||[]).find(c=>c.Type==='DIRECT'&&str(c.DirectUserId).toLowerCase()===str(m.UserId).toLowerCase());return {...existing,Id:existing?.Id||'member-'+m.UserId,Type:'DIRECT',DirectUserId:m.UserId,DirectName:[m.FirstName,m.LastName].filter(Boolean).join(' '),DirectImage:m.ProfileImage,IsSelf:str(m.UserId).toLowerCase()===str(session.get()?.user.Id).toLowerCase(),NewDirect:!existing} as RecordData}),all=[...(chats.data||[]).filter(c=>c.Type!=='DIRECT'),...roster],list=all.filter(c=>(tab==='all'||(tab==='direct'?c.Type==='DIRECT':c.Type!=='DIRECT'))&&[chatName(c),c.LastMessage,c.LastSender].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>{const time=(c:RecordData)=>Date.parse(str(c.LastMessageAt||c.CreatedAt))||0;return time(b)-time(a)||chatName(a).localeCompare(chatName(b))});
 useEffect(()=>{
  const menus=()=>Array.from(document.querySelectorAll<HTMLDetailsElement>('.chat-row-menu[open]'));
  const close=()=>menus().forEach(menu=>menu.open=false);
  const pointer=(event:PointerEvent)=>{const active=(event.target as Element).closest<HTMLDetailsElement>('.chat-row-menu');menus().forEach(menu=>{if(menu!==active)menu.open=false})};
  const key=(event:KeyboardEvent)=>{if(event.key==='Escape')close()};document.addEventListener('pointerdown',pointer);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',pointer);document.removeEventListener('keydown',key)};
 },[]);

 function open(kind:'group'|'direct'){setParams({new:kind});setName('');setMemberSearch('');setSelected([]);setError(undefined);setTimeout(()=>{editor.current?.scrollIntoView({behavior:'smooth',block:'start'});editor.current?.querySelector<HTMLInputElement>('input')?.focus()},0)}
 async function create(){if(!mode||busy)return;setBusy(true);setError(undefined);try{const result=await api.send<RecordData>(mode==='group'?base+'/conversations':base+'/direct-conversations/'+selected[0],mode==='group'?{name:name.trim(),type:'GROUP',memberUserIds:selected}:{});if(!result.Id)throw Error('The chat could not be opened. Please try again.');await qc.invalidateQueries({queryKey:[base+'/conversations']});nav('/chat/'+result.Id)}catch(e){setError(e)}finally{setBusy(false)}}
 const target=document.getElementById('community-chat-header-actions');
 return <div className="community-chats">{target&&createPortal(<><button className="topbar-icon" aria-label="Create chat group" title={canCreate?'Create chat group':'Group creation requires permission'} disabled={!canCreate} onClick={()=>open('group')}><MessageCirclePlus size={21}/></button><button className="topbar-icon" aria-label="Search chats" aria-expanded={searchOpen} onClick={()=>setSearchOpen(!searchOpen)}><Search size={21}/></button></>,target)}
 <nav className="chat-list-tabs" aria-label="Chat types">{[['all','All chats'],['groups','Groups'],['direct','Direct']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
 {searchOpen&&document.getElementById('community-chat-header-search')&&createPortal(<div className="chat-header-search"><Search size={18}/><input autoFocus ref={searchInput} aria-label="Search conversations" placeholder="Search chats..." value={search} onChange={e=>setSearch(e.target.value)}/><button aria-label="Close chat search" onClick={()=>{setSearchOpen(false);setSearch('')}}><X size={18}/></button></div>,document.getElementById('community-chat-header-search')!)}
 {mode&&<div className="chat-create-panel chat-create-page" ref={editor}><header><h2>{mode==='direct'?'New direct chat':step==='members'?'Select members':'Name your group'}</h2><button aria-label="Close chat creator" onClick={()=>setParams({})}><X size={18}/></button></header><form onSubmit={e=>{e.preventDefault();if(mode==='group'&&step==='members'){setParams({new:'group',step:'name'});return}void create()}}><fieldset disabled={busy}>{mode==='group'&&step==='name'&&<label>Group name<input required minLength={2} maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label>}{step==='members'&&<><HeaderSearch label="Find a member"><label>Find a member<input value={memberSearch} onChange={e=>setMemberSearch(e.target.value)} placeholder="Search community members"/></label></HeaderSearch>{members.isPending?<Loading/>:members.error?<ErrorBox error={members.error}/>:<div className="chat-member-picker">{(members.data||[]).filter(m=>m.UserId!==session.get()?.user.Id&&[m.FirstName,m.LastName].join(' ').toLowerCase().includes(memberSearch.toLowerCase())).map(m=><label key={str(m.UserId)}><input type={mode==='group'?'checkbox':'radio'} name="chat-member" checked={selected.includes(str(m.UserId))} onChange={e=>setSelected(mode==='direct'?[str(m.UserId)]:e.target.checked?[...selected,str(m.UserId)]:selected.filter(x=>x!==m.UserId))}/><span>{str(m.FirstName)} {str(m.LastName)}</span></label>)}{members.data?.filter(m=>m.UserId!==session.get()?.user.Id).length===0&&<p>No other members are available.</p>}</div>}</>}{step==='name'&&<><p>{selected.length} members selected</p><button type="button" onClick={()=>setParams({new:'group'})}>Back to members</button></>}<button className="primary" disabled={busy||!selected.length||(mode==='group'&&(!canCreate||(step==='name'&&name.trim().length<2)))}>{busy?'Opening...':mode==='group'?(step==='members'?'Next':'Create group'):'Open chat'}</button></fieldset><ErrorBox error={error}/></form></div>}
 <section className="chat-conversation-list" aria-label="Conversations">{chats.isPending||(tab!=='groups'&&members.isPending)?<Loading/>:chats.error?<ErrorBox error={chats.error}/>:list.length?list.map(c=><article className="chat-conversation-row" key={str(c.Id)}><Link to={c.IsSelf?'/member/'+c.DirectUserId+'?community='+id:c.NewDirect?'#':'/chat/'+c.Id} className="chat-conversation-open" onClick={async e=>{if(c.IsSelf||!c.NewDirect)return;e.preventDefault();if(busy)return;setBusy(true);setError(undefined);try{const result=await api.send<RecordData>(base+'/direct-conversations/'+c.DirectUserId,{});await qc.invalidateQueries({queryKey:[base+'/conversations']});if(!result.Id)throw Error('The chat could not be opened. Please try again.');nav('/chat/'+result.Id)}catch(error){setError(error)}finally{setBusy(false)}}}><Avatar chat={c}/><div className="chat-conversation-copy"><strong>{chatName(c)}{c.IsSelf?' (You)':''}{muted(c)&&<BellOff size={14} aria-label="Muted"/>}</strong><p>{c.IsSelf?'Your community profile':c.LastMessage?<>{!!c.LastSender&&<b>{str(c.LastSender)}: </b>}{str(c.LastMessage)}</>:'No messages yet'}</p></div><div className="chat-conversation-meta"><time dateTime={str(c.LastMessageAt)||undefined}>{timeLabel(c.LastMessageAt)}</time>{Number(c.UnreadCount)>0&&<span aria-label={Number(c.UnreadCount)+' unread messages'}>{Number(c.UnreadCount)>99?'99+':Number(c.UnreadCount)}</span>}</div></Link>{!c.NewDirect&&!c.IsSelf&&<details className="chat-row-menu"><summary aria-label={'Options for '+chatName(c)}><MoreHorizontal size={18}/></summary><Action run={()=>api.send('/conversations/'+c.Id+'/mute',{muted:!muted(c)},'PUT')}>{muted(c)?<Bell size={16}/>:<BellOff size={16}/>} {muted(c)?'Unmute':'Mute'}</Action></details>}</article>):<p className="chat-list-empty">{search?'No chats match your filters.':'No conversations in this tab yet.'}</p>}</section>
 <ErrorBox error={error||members.error}/><aside className="chat-privacy-note"><LockKeyhole size={23}/><div><strong>Your conversation settings</strong><p>Manage who can contact you, read receipts and typing indicators.</p></div><Link to="/settings/communications">Manage</Link></aside></div>
}
