import {MobileHeaderActions} from './MobileHeaderActions';
import {CommunityMapPosition} from './CommunityMapPosition';
import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueries,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {Camera,Contact,Users,ShieldCheck,Share2,MessageCircle} from 'lucide-react';
import {Capacitor} from '@capacitor/core';
import {Share} from '@capacitor/share';
import {api,str,rows,type RecordData} from './api';
import {ErrorBox} from './ui';
export function CommunityHero({id,community:c,profile=false}:{id:string;community:RecordData;profile?:boolean}){
 const menuRef=useRef<HTMLDivElement>(null);
 const[logoFailed,setLogoFailed]=useState(false);useEffect(()=>setLogoFailed(false),[c.LogoUrl]);
 const cap=useQuery({queryKey:['/communities/'+id+'/capabilities'],queryFn:()=>api.get<{permissions:string[]}>('/communities/'+id+'/capabilities')}),qc=useQueryClient(),[menu,setMenu]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),input=useRef<HTMLInputElement>(null),kind=useRef<'profile'|'cover'>('profile');
 useEffect(()=>{const workspace=document.querySelector<HTMLElement>('.workspace'),header=workspace?.querySelector<HTMLElement>('.topbar');if(!workspace||!header)return;workspace.classList.add('community-cover-workspace');workspace.style.setProperty('--community-cover-image',c.BannerUrl?'url('+JSON.stringify(api.asset(str(c.BannerUrl)))+')':'linear-gradient(115deg,#073b78,#087240)');const measure=()=>workspace.style.setProperty('--community-header-height',header.offsetHeight+'px');measure();const observer=new ResizeObserver(measure);observer.observe(header);return()=>{observer.disconnect();workspace.classList.remove('community-cover-workspace');workspace.style.removeProperty('--community-cover-image');workspace.style.removeProperty('--community-header-height')}},[c.BannerUrl]);
 useEffect(()=>{if(!menu)return;const close=(event:PointerEvent)=>{if(!menuRef.current?.contains(event.target as Node))setMenu(false)};const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenu(false);menuRef.current?.querySelector<HTMLButtonElement>('button')?.focus()}};document.addEventListener('pointerdown',close,true);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close,true);document.removeEventListener('keydown',key)}},[menu]);
 async function upload(file?:File){if(!file)return;setMenu(false);setError(undefined);setNotice('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError(Error('Choose a JPG, PNG or WebP image up to 5 MB.'));return}setBusy(true);try{const data=new FormData();data.append('file',file);const uploaded=await api.upload<{storedObjectId:string}>('/media/upload',data);await api.send('/communities/'+id+'/image',{kind:kind.current,uploadId:uploaded.storedObjectId},'PATCH');await qc.invalidateQueries();setNotice('Community image updated.')}catch(e){setError(e)}finally{setBusy(false)}}
 return <section className="community-hero"><div className="community-hero-cover">{c.BannerUrl?<img src={api.asset(str(c.BannerUrl))} alt="Community cover"/>:<div className="community-cover-fallback"/>}<MobileHeaderActions><div ref={menuRef} className="community-hero-tools">{cap.data?.permissions.includes('MEMBER_ROLE_CHANGE')&&<><button aria-label="Change community images" aria-expanded={menu} disabled={busy} onClick={()=>setMenu(!menu)}><Camera size={21}/></button>{menu&&<div className="community-image-menu">{(['profile','cover'] as const).map(value=><button key={value} onClick={()=>{kind.current=value;input.current?.click()}}>Change {value}</button>)}</div>}<input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" aria-label="Community image" onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/></>}{!profile&&<Link aria-label="Community profile" title="Community profile" to={'/community/'+id+'/profile'}><Contact size={21}/></Link>}</div></MobileHeaderActions></div><div className="community-hero-info"><div className="community-hero-logo">{c.LogoUrl&&!logoFailed?<img src={api.asset(str(c.LogoUrl))} alt="Community logo" onError={()=>setLogoFailed(true)}/>:str(c.Name).slice(0,1)}</div><h2>{str(c.Name)} {!!c.IsVerified&&<span className="community-verified"><ShieldCheck size={14}/>Verified</span>}</h2><p>{str(c.Description)||'Your community workspace'}</p>{c.MemberCount!==undefined&&<Link className="community-member-count" to={'/community/'+id+'/members'}><Users size={17}/>{Number(c.MemberCount)} {Number(c.MemberCount)===1?'member':'members'}</Link>}<ErrorBox error={error}/>{(busy||notice)&&<p role="status">{busy?'Saving image…':notice}</p>}</div></section>
}
export function CommunityProfile({id,community:c}:{id:string;community:RecordData}){
 const[notice,setNotice]=useState(''),base='/communities/'+id;const sections=['events','announcements','documents','excos'];const queries=useQueries({queries:sections.map(section=>({queryKey:[base+'/'+section],queryFn:()=>api.get<unknown>(base+'/'+section)}))});const mine=useQuery({queryKey:['/communities'],queryFn:()=>api.get<RecordData[]>('/communities')});const membership=mine.data?.find(x=>x.Id===id);const team=rows(queries[3].data).filter(x=>x.Status==='ACTIVE');
 async function invite(){if(!c.JoinCode)return;const url='https://cdaconnect.org/invite/'+encodeURIComponent(str(c.JoinCode));try{if(Capacitor.isNativePlatform())await Share.share({title:str(c.Name),url});else if(navigator.share)await navigator.share({title:str(c.Name),url});else{await navigator.clipboard.writeText(url);setNotice('Invite link copied.')}}catch(e){if((e as Error).name!=='AbortError')setNotice('Sharing failed. Try again.')}}
 return <div className="community-profile-page"><CommunityHero id={id} community={c} profile/><div className="community-profile-content"><CommunityMapPosition id={id} community={c}/><div className="community-profile-actions">{!!c.JoinCode&&<button onClick={()=>void invite()}><Share2 size={17}/>Invite</button>}<Link className="button" to={'/community/'+id+'/conversations'}><MessageCircle size={17}/>Message</Link></div>{notice&&<p role="status">{notice}</p>}<nav className="community-profile-counts" aria-label="Community activity"><Link to={'/community/'+id+'/members'}><strong>{c.MemberCount===undefined?'—':Number(c.MemberCount)}</strong>Members</Link>{sections.slice(0,3).map((key,i)=><Link key={key} to={'/community/'+id+'/'+key}><strong>{queries[i].isPending?'…':queries[i].error?'—':rows(queries[i].data).length}</strong>{key[0].toUpperCase()+key.slice(1)}</Link>)}</nav><section className="card community-profile-team"><div className="section-heading"><h2>Executive team</h2><Link to={'/community/'+id+'/excos'}>View all</Link></div><ErrorBox error={queries[3].error}/>{queries[3].isPending?<p>Loading team…</p>:team.length?<div className="community-team-grid">{team.slice(0,4).map(person=><Link key={str(person.Id)} to={'/member/'+person.UserId}>{person.ProfileImage?<img src={api.asset(str(person.ProfileImage))} alt=""/>:<span>{str(person.FirstName).slice(0,1)}</span>}<strong>{[person.FirstName,person.LastName].filter(Boolean).join(' ')}</strong><small>{str(person.Position)}</small></Link>)}</div>:!queries[3].error&&<p>No active appointments yet.</p>}</section><dl className="community-profile-facts">{[['Community type',c.CommunityType||c.Category],['Location',[c.SpecificArea,c.LGA,c.State,c.Country].filter(Boolean).join(', ')],['Focus areas',Array.isArray(c.Tags)?c.Tags.join(', '):c.Tags],['Privacy',c.IsPrivate?'Private community':'Public community'],['Established',c.CreatedAt?new Date(str(c.CreatedAt)).getFullYear():''],['Joined',membership?.JoinedAt?new Date(str(membership.JoinedAt)).toLocaleDateString():'']].map(([label,value])=><div key={str(label)}><dt>{str(label)}</dt><dd>{str(value)||'Not specified'}</dd></div>)}</dl><section className="card"><h2>About our community</h2><p>{str(c.Description)||'No description added yet.'}</p>{!!c.Guidelines&&<><h3>Community guidelines</h3><p>{str(c.Guidelines)}</p></>}</section></div></div>
}
