import {useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Users,Tag,Filter,EyeOff,Hash,Bell,CalendarDays,Megaphone,ChartNoAxesColumn,MessageCircle,AtSign,UserPlus,ShieldCheck,ChevronRight,ArrowLeft,Settings2} from 'lucide-react';
import {api,str,rows,type RecordData} from './api';
import {Loading,ErrorBox,MutationForm,Field,Action} from './ui';
const topics=[['TEXT','General'],['PHOTO','Photos'],['VIDEO','Videos'],['DOCUMENT','Documents'],['POLL','Polls'],['EVENT','Events'],['OPPORTUNITY','Opportunities'],['LOST_FOUND','Lost & found'],['RECOMMENDATION','Recommendations'],['QUESTION','Questions'],['ALERT','Community alerts'],['LOCAL_NEWS','Local news'],['VOICE','Voice posts'],['INITIATIVE','Initiatives']] as const;
const on=(v:unknown)=>v!==false&&v!==0&&v!=='OFF';
export function CommunityPreferences(){
 const field=useLocation().pathname.split('/')[3]||'',qc=useQueryClient(),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState('');
 const q=useQuery({queryKey:['/users/community-preferences'],queryFn:()=>api.get<RecordData>('/users/community-preferences')}),n=useQuery({queryKey:['/users/notification-settings'],queryFn:()=>api.get<RecordData>('/users/notification-settings')}),privacy=useQuery({queryKey:['/users/privacy'],queryFn:()=>api.get<RecordData>('/users/privacy')});
 async function save(key:string,value:unknown,notification=false){setBusy(true);setError(undefined);setNotice('');try{await api.send(notification?'/users/notification-settings':'/users/community-preferences',{key,value},'PATCH');await qc.invalidateQueries();setNotice('Community preference saved.')}catch(e){setError(e)}finally{setBusy(false)}}
 if(q.isPending||n.isPending||privacy.isPending)return <Loading/>;if(q.error||n.error||privacy.error)return <ErrorBox error={q.error||n.error||privacy.error}/>;
 const p=q.data!,np=n.data!,pr=privacy.data!,array=(key:string)=>(p[key]??[]) as string[];
 const toggle=(key:string,title:string,description:string,checked:boolean,Icon:typeof Users,notification=false)=><label className="settings-row account-switch-row"><span className="settings-row-icon"><Icon size={21}/></span><span className="settings-row-text"><strong>{title}</strong><small>{description}</small></span><input type="checkbox" role="switch" disabled={busy} checked={checked} onChange={e=>void save(key,e.target.checked,notification)}/></label>;
 const link=(to:string,title:string,description:string,value:string,Icon:typeof Users)=><Link className="settings-row" to={to.startsWith('/')?to:'/settings/community/'+to}><span className="settings-row-icon"><Icon size={21}/></span><span className="settings-row-text"><strong>{title}</strong><small>{description}</small></span><span className="privacy-value">{value}</span><ChevronRight size={17}/></Link>;
 const feedback=<>{error!=null&&<ErrorBox error={error}/>}<p className="privacy-status" role="status">{busy?'Saving…':notice}</p></>;
 if(field)return <div className="community-preferences-detail"><Link className="settings-back" to="/settings/community"><ArrowLeft size={17}/>Community Preferences</Link><h2>{field==='interests'?'Content Interests':field==='filter'?'Content Filter':field==='hashtags'?'Hashtag Preferences':field==='join'?'Join Request Settings':'Community Preferences'}</h2>{feedback}
 {(field==='interests'||field==='filter')&&<TopicChoices key={field+JSON.stringify(p)} selected={array(field==='interests'?'Interests':'ContentTypes')} filter={field==='filter'}/>}
 {field==='hashtags'&&<><p>Followed hashtags prioritise matching posts. Muted hashtags hide matching feed posts, even if followed. Enter up to 20 tags per list, separated by commas.</p>{(['FollowedTags','MutedTags'] as const).map((key,i)=><MutationForm key={key+JSON.stringify(p[key])} label={i?'Save muted hashtags':'Save followed hashtags'} onSubmit={d=>api.send('/users/community-preferences',{key:i?'mutedTags':'followedTags',value:d.tags.split(/[,\s]+/).filter(Boolean)},'PATCH')}><Field name="tags" label={i?'Muted hashtags':'Followed hashtags'} required={false} defaultValue={array(key).join(', ')}/></MutationForm>)}</>}
 {field==='join'&&<ManagedCommunities/>}
 </div>;
 const audience=(v:unknown)=>v==='NOBODY'?'Nobody':v==='COMMUNITIES'?'My communities':'Everyone';
 return <div className="privacy-dashboard community-preferences-dashboard"><p>Customize your community experience and content.</p><section className="notification-hero"><span className="notification-hero-bell"><Users size={34}/></span><div><h2>Your community, your way</h2><p>Set your preferences to get the most relevant updates and content.</p></div><Settings2 className="notification-hero-check" size={44}/></section>{feedback}
 <section className="settings-group"><h2>Community Content</h2><div className="settings-list">{link('interests','Content Interests','Choose topics you care about',array('Interests').length+' selected',Tag)}{link('filter','Content Filter','Filter the types of posts in your feed',array('ContentTypes').length?'Custom':'All types',Filter)}{toggle('hideSensitive','Hide Sensitive Content','Hide posts marked as sensitive',!!p.HideSensitive,EyeOff)}{link('hashtags','Hashtag Preferences','Choose hashtags to follow or mute','Manage',Hash)}</div></section>
 <section className="settings-group"><h2>Community Updates</h2><div className="settings-list">{toggle('communityUpdates','Community Announcements','Important updates from your communities',on(np.CommunityUpdates),Bell,true)}{toggle('events','Event Updates','Updates about events and activities',on(np.Events),CalendarDays,true)}{toggle('initiatives','New Initiatives','Notifications about new initiative posts',on(np.Initiatives),Megaphone,true)}{toggle('polls','Polls & Surveys','Notifications about community polls and surveys',on(np.Polls),ChartNoAxesColumn,true)}{toggle('invitations','Community Invitations','Notifications when you are added to a group',on(np.Invitations),Users,true)}</div><p className="privacy-note">These update switches share your Notifications settings. They do not change membership or voting rights.</p></section>
 <section className="settings-group"><h2>Participation Settings</h2><div className="settings-list">{link('/settings/privacy/comments','Comment Preferences','Choose who can comment on your posts and reply to you',audience(pr.CommentAudience),MessageCircle)}{link('/settings/privacy/mentions','Mention Preferences','Choose who can mention you',audience(pr.MentionAudience),AtSign)}{link('join','Join Request Settings','Manage approval for communities you own','Manage',UserPlus)}{link('/settings/privacy/visibility','Community Privacy','Manage who can view your member profile',pr.PrivateAccount?'My communities':'Visible',ShieldCheck)}</div></section>
 <section className="privacy-safety"><ShieldCheck size={34}/><div><strong>You’re in control</strong><p>Reset your content interests, filters and hashtags to their defaults.</p></div><Action run={async()=>{if(!window.confirm('Reset content interests, filters and hashtags, and enable hiding sensitive posts? Your shared notification, privacy and community approval settings will stay as they are.'))return;await api.send('/users/community-preferences/reset');setNotice('Content preferences reset.')}}>Reset to Defaults</Action></section></div>;
}
function TopicChoices({selected,filter}:{selected:string[];filter:boolean}){const [value,setValue]=useState(selected);return <><p>{filter?'Choose the post types to include in your feed. No selections means all types.':'Selected topics are prioritised in your feed. Other topics remain available.'}</p><MutationForm label={filter?'Save content filter':'Save interests'} onSubmit={()=>api.send('/users/community-preferences',{key:filter?'contentTypes':'interests',value},'PATCH')}><div className="community-topic-options">{topics.map(([key,label])=><label className="choice" key={key}><input type="checkbox" checked={value.includes(key)} onChange={e=>setValue(e.target.checked?[...value,key]:value.filter(v=>v!==key))}/>{label}</label>)}</div></MutationForm></>}
function ManagedCommunities(){const q=useQuery({queryKey:['/users/community-preferences/managed'],queryFn:()=>api.get<RecordData[]>('/users/community-preferences/managed')});if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;return <><p>Only community owners can change these settings. Private communities always require approval. Changes apply to future requests; existing requests still need review.</p>{!q.data.length?<p>You do not own a community yet.</p>:q.data.map(c=><section className="card" key={str(c.Id)}><h3>{str(c.Name)}</h3><MutationForm key={str(c.Id)+String(c.RequireMemberApproval)} label="Save approval setting" onSubmit={d=>api.send('/users/community-preferences/managed/'+c.Id,{requireMemberApproval:d.mode==='manual'},'PATCH')}><label>New join requests<select name="mode" defaultValue={c.IsPrivate||c.RequireMemberApproval?'manual':'automatic'}><option value="manual">Approve manually</option>{!c.IsPrivate&&<option value="automatic">Join automatically</option>}</select></label></MutationForm></section>)}</>}
