import {PollInsights,ParticipationRing} from './PollInsights';
import {CreatePoll} from './CreatePoll';
import {HeaderSearch} from './HeaderSearch';
import './polls.css';
import {useEffect,useState} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {BarChart3,Users,Clock,Plus,Search,SlidersHorizontal,MoreVertical,Info,ArrowLeft,ShieldCheck,Vote,CheckSquare,CalendarDays} from 'lucide-react';
import {api,rows,str,type RecordData} from './api';
import {Loading,ErrorBox,MutationForm} from './ui';
import {getLocale} from './i18n';

function state(p:RecordData,now:number){return p.EndAt&&Date.parse(str(p.EndAt))<=now?'completed':p.StartAt&&Date.parse(str(p.StartAt))>now?'scheduled':'active'}
function date(v:unknown){return v?new Date(str(v)).toLocaleString(getLocale(),{dateStyle:'medium',timeStyle:'short'}):'No closing date'}
function useNow(){const [now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);return now}
function usePolls(id:string){return useQuery({queryKey:['/communities/'+id+'/polls'],queryFn:({signal})=>api.get<RecordData[]>('/communities/'+id+'/polls',signal)})}
function Results({poll}:{poll:RecordData}){if(poll.ResultsVisible===false)return <p>Results are not available yet.</p>;const voters=Number(poll.VoterCount)||0;return <div className="poll-results" aria-label="Poll results">{rows(poll.options).map(o=>{const count=Number(o.VoteCount)||0,percent=voters?Math.round(count/voters*100):0;return <div className="poll-result" key={str(o.Id)}><span>{str(o.OptionText)}</span><progress value={count} max={Math.max(voters,count,1)} aria-label={str(o.OptionText)+' votes'}/><small>{percent}% ({count})</small></div>})}{!!poll.AllowMultiple&&<small>Members can choose multiple options. Percentages are based on voters.</small>}</div>}
function PollCard({p,communityId,now,expanded,activeTab}:{p:RecordData;communityId:string;now:number;expanded:boolean;activeTab:boolean}){const status=state(p,now),voters=Number(p.VoterCount)||0,members=Number(p.MemberCount)||0,participation=members?Math.min(100,Math.round(voters/members*100)):0,href='/poll/'+communityId+'/'+p.Id;return <Link to={href} className="poll-history-card poll-card-open"><div className="poll-card-icon"><BarChart3 size={27}/></div><div className="poll-card-body"><span className={'poll-state '+status}>{status==='completed'?'Completed':status==='scheduled'?'Scheduled':'Active'}</span><h2>{str(p.Question)}</h2><p className="poll-date">Created on {date(p.CreatedAt)}</p><div className="poll-meta"><span><Users size={16}/>{voters} {voters===1?'voter':'voters'}</span><span><Clock size={16}/>{status==='completed'?'Ended ':status==='scheduled'?'Starts ':'Ends '}{date(status==='scheduled'?p.StartAt:p.EndAt)}</span></div>{status==='active'&&activeTab&&<div className="poll-participation"><progress value={participation} max={100} aria-label="Participation"/><small>{participation}% participation ({voters} / {members} current members)</small></div>}{status==='completed'&&expanded&&<Results poll={p}/>}<span className="poll-details-link">{status==='completed'?'View results':status==='scheduled'?'View details':rows(p.options).some(o=>o.MyVote)?'View your vote':'Open poll & vote'}</span></div>{status==='active'&&<ParticipationRing value={participation}/>}</Link>}

export function CommunityPolls({id,permissions}:{id:string;permissions:string[]}){const q=usePolls(id),now=useNow(),[params,setParams]=useSearchParams(),tab=['active','completed'].includes(params.get('tab')||'')?params.get('tab')!:'all',[search,setSearch]=useState('');const creating=params.get('view')==='create';function view(value:string){const next=new URLSearchParams(params);if(value)next.set('view',value);else{next.delete('view');next.delete('step')}setParams(next)}
 if(creating&&permissions.includes('POLL_CREATE'))return <CreatePoll id={id} permissions={permissions} onClose={()=>view('')}/>;
 const list=(q.data||[]).filter(p=>(tab==='all'||state(p,now)===tab)&&str(p.Question).toLowerCase().includes(search.toLowerCase().trim())).sort((a,b)=>Date.parse(str(b.CreatedAt))-Date.parse(str(a.CreatedAt)));
 return <section className="polls-page"><div className="polls-heading"><h1>Poll history</h1>{permissions.includes('POLL_CREATE')&&<button className="primary" onClick={()=>view('create')}><Plus size={18}/>Create poll</button>}</div><div className="poll-tabs" role="tablist" aria-label="Poll status">{[['all','All polls'],['active','Active'],['completed','Completed']].map(([value,label])=><button role="tab" aria-selected={tab===value} aria-controls="poll-list" id={'poll-tab-'+value} key={value} onClick={()=>{const next=new URLSearchParams(params);next.set('tab',value);next.delete('view');setParams(next)}}>{label}</button>)}</div><div className="poll-search-row"><HeaderSearch label="Search"><label><Search size={19}/><input aria-label="Search polls" placeholder={tab==='all'?'Search polls…':'Search '+tab+' polls…'} value={search} onChange={e=>setSearch(e.target.value)}/></label></HeaderSearch></div><div id="poll-list" role="tabpanel" aria-labelledby={'poll-tab-'+tab}>{q.isPending?<Loading/>:q.error?<><ErrorBox error={q.error}/><button onClick={()=>void q.refetch()}>Retry</button></>:list.length?list.map(p=><PollCard key={str(p.Id)} p={p} communityId={id} now={now} expanded={tab==='completed'} activeTab={tab==='active'}/>):<div className="poll-empty"><BarChart3 size={30}/><h2>{search?'No polls match your search.':tab==='all'?'No polls yet.':'No '+tab+' polls.'}</h2><p>{tab==='completed'?'Results will appear here when polls end.':'Community polls will appear here when available.'}</p></div>}</div>{tab!=='all'&&<aside className="poll-notice"><Info size={20}/><div><strong>{tab==='active'?'These polls are accepting votes.':'These polls have ended.'}</strong><p>{tab==='active'?'Open a poll to vote, view details or share.':'You can view the results and details of completed polls.'}</p></div></aside>}</section>
}
export function Poll(){const {id='',communityId=''}=useParams(),q=usePolls(communityId),now=useNow(),[params,setParams]=useSearchParams();if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;const p=q.data.find(p=>p.Id===id);if(!p)return <ErrorBox error={Error('Poll not found.')}/>;const view=p.CanAnalyze?(params.get('view')||'vote'):'vote';return <><nav className="poll-view-switch" aria-label="Poll views">{[['vote','Vote'],['analysis','Poll Analysis'],['overview','View Poll']].filter(([key])=>key==='vote'||p.CanAnalyze).map(([key,label])=><button key={key} aria-pressed={view===key} onClick={()=>setParams(key==='vote'?{}:{view:key})}>{label}</button>)}</nav>{view==='analysis'||view==='overview'?<PollInsights key={id} p={p} communityId={communityId} analysis={view==='analysis'} onView={next=>setParams({view:next})}/>:<PollDetail key={id} p={p} communityId={communityId} now={now}/>}</>}
function PollDetail({p,communityId,now}:{p:RecordData;communityId:string;now:number}){
 const qc=useQueryClient(),options=rows(p.options),[otherText,setOtherText]=useState(str(p.MyOtherText)),[selected,setSelected]=useState(()=>options.filter(o=>o.MyVote).map(o=>str(o.Id))),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[message,setMessage]=useState(''),status=state(p,now),hasVoted=options.some(o=>o.MyVote),canVote=p.CanVote!==false&&p.CanVote!==0&&status==='active'&&(!hasVoted||!!p.AllowChangeVote),settings=p.settings as RecordData|undefined,voters=Number(p.VoterCount)||0,visible=p.ResultsVisible!==false&&p.ResultsVisible!==0;
 async function submit(e:React.FormEvent){e.preventDefault();if(!canVote||busy)return;setError(undefined);if(!selected.length){setError(Error('Select an option.'));return}setBusy(true);try{await api.send('/polls/'+p.Id+'/vote',{optionIds:selected,otherText:otherText.trim()||undefined});await qc.invalidateQueries({queryKey:['/communities/'+communityId+'/polls']});setMessage('Your vote has been recorded.')}catch(e){setError(e)}finally{setBusy(false)}}
 return <section className="polls-page poll-detail-page"><section className="poll-detail-summary"><div className="poll-detail-intro"><div><span className="poll-state">{settings?.type==='DECISION'?'Decision Poll':'General Poll'}</span><h1>{str(p.Question)}</h1>{!!p.Description&&<p>{str(p.Description)}</p>}</div><div className="poll-detail-art">{p.ImageUrl?<img src={api.asset(str(p.ImageUrl))} alt="Poll"/>:<Vote size={64}/>}</div></div><div className="poll-meta poll-detail-meta"><span><CalendarDays size={18}/>{status==='completed'?'Ended ':status==='scheduled'?'Starts ':'Ends '}{date(status==='scheduled'?p.StartAt:p.EndAt)}</span><span><Users size={18}/>{voters} {voters===1?'voter':'voters'}</span><span><ShieldCheck size={18}/>{p.AllowMultiple?'Multiple choices allowed':'One member, one choice'}</span></div></section>
 <form onSubmit={submit}><div className="poll-options-heading"><h2>Poll Options</h2><span>{canVote?p.AllowMultiple?'Select one or more options':'Select one option':hasVoted?'Your vote':status==='completed'?'Final results':'Voting unavailable'}</span></div><fieldset className="poll-detail-options" disabled={!canVote||busy}>{options.map(o=>{const count=Number(o.VoteCount)||0,percent=voters?Math.round(count/voters*100):0;return <label className="poll-detail-option" key={str(o.Id)}><span className="poll-option-art">{o.ImageUrl?<img src={api.asset(str(o.ImageUrl))} alt=""/>:<BarChart3 size={26}/>}</span><span className="poll-option-content"><strong>{str(o.OptionText)}</strong>{visible&&<progress value={count} max={Math.max(voters,count,1)} aria-label={str(o.OptionText)+' votes'}/>} {!!o.Description&&<small>{str(o.Description)}</small>}</span>{visible&&<span className="poll-option-count"><strong>{percent}%</strong><small>{count} {count===1?'vote':'votes'}</small></span>}<input aria-label={str(o.OptionText)} type={p.AllowMultiple?'checkbox':'radio'} name="vote" checked={selected.includes(str(o.Id))} onChange={()=>setSelected(p.AllowMultiple?selected.includes(str(o.Id))?selected.filter(x=>x!==o.Id):[...selected,str(o.Id)]:[str(o.Id)])}/></label>})}</fieldset>{!!settings?.other&&options.some(o=>o.OptionText==='Other'&&selected.includes(str(o.Id)))&&<label className="poll-other-answer">Your answer<input maxLength={500} required disabled={!canVote||busy} value={otherText} onChange={e=>setOtherText(e.target.value)}/></label>}
 <aside className="poll-notice poll-vote-notice"><ShieldCheck size={32}/><div><strong>{hasVoted?'Thank you for participating!':'Your vote matters!'}</strong><p>{!visible?settings?.showResults===false?'Results are available to poll managers only.':'Results will be shared once the poll ends.':status==='completed'?'This poll has ended. View the final results above.':p.AllowMultiple?'Percentages are based on voters; each member can choose multiple options.':'Select your preferred option above.'}</p>{status==='scheduled'&&<p>Voting opens {date(p.StartAt)}.</p>}</div></aside><ErrorBox error={error}/>{(message||hasVoted)&&<p role="status" className="success">{message||'Your vote has been recorded.'}</p>}<div className="poll-vote-actions">{canVote&&<button className="primary poll-vote-submit" disabled={busy}><CheckSquare size={21}/>{busy?'Submitting�':hasVoted?'Update Your Vote':'Cast Your Vote'}</button>}</div></form></section>
}
