import {useEffect} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api} from './api';
export type LocationChoice={countryCode:string;stateId:string;localArea:string};
export function CommunityLocation({value,onChange,onReady}:{value:LocationChoice;onChange:(v:LocationChoice)=>void;onReady:(v:boolean)=>void}){
 const countries=useQuery({queryKey:['community-countries'],queryFn:()=>api.get<{id:string;name:string}[]>('/communities/locations'),staleTime:86400000});
 const states=useQuery({queryKey:['community-states',value.countryCode],queryFn:()=>api.get<{id:string;name:string}[]>('/communities/locations?country='+value.countryCode),enabled:!!value.countryCode,staleTime:86400000});
 const areas=useQuery({queryKey:['community-areas',value.countryCode,value.stateId],queryFn:()=>api.get<string[]>('/communities/locations?country='+value.countryCode+'&state='+value.stateId),enabled:!!value.countryCode&&!!value.stateId,staleTime:86400000});
 const ready=!!countries.data?.some(c=>c.id===value.countryCode)&&!!states.data&&(!states.data.length||!!states.data.some(s=>s.id===value.stateId)&&!!areas.data&&(!areas.data.length||areas.data.includes(value.localArea)));
 useEffect(()=>onReady(ready),[ready,onReady]);
 return <><div className="create-location"><label>Country *<select required name="countryCode" value={value.countryCode} onChange={e=>onChange({countryCode:e.target.value,stateId:'',localArea:''})}><option value="">{countries.isPending?'Loading countries…':'Select country'}</option>{countries.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>State / Region{states.data?.length?' *':''}<select name="stateId" required={!!states.data?.length} disabled={!value.countryCode||states.isPending||!states.data?.length} value={value.stateId} onChange={e=>onChange({...value,stateId:e.target.value,localArea:''})}><option value="">{!value.countryCode?'Select country first':states.isError?'Regions unavailable':states.isFetching?'Loading regions…':states.data?.length?'Select state / region':'No region list available'}</option>{states.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>{value.countryCode==='NG'?'LGA':'Local Area / City'}{areas.data?.length?' *':''}<select name="localArea" required={!!areas.data?.length} disabled={!value.stateId||areas.isPending||!areas.data?.length} value={value.localArea} onChange={e=>onChange({...value,localArea:e.target.value})}><option value="">{!value.stateId?'Select region first':areas.isError?'Local areas unavailable':areas.isFetching?'Loading local areas…':areas.data?.length?'Select local area':'No local-area list available'}</option>{areas.data?.map(a=><option key={a} value={a}>{a}</option>)}</select></label><label>Specific area (Optional)<input name="specificArea" maxLength={250} placeholder="e.g. Estate, street or neighbourhood"/></label></div>{(countries.isError||states.isError||areas.isError)&&<div className="location-error" role="alert"><p>Location options could not be loaded. Please try again.</p><button type="button" className="secondary" onClick={()=>{if(countries.isError)void countries.refetch();if(states.isError)void states.refetch();if(areas.isError)void areas.refetch()}}>Retry location options</button></div>}</>;
}



