import {HeaderSearch} from './HeaderSearch';
import {CommunityHero} from './CommunityProfile';
import {useEffect,useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {ArrowLeft,SquarePen,Menu,Users,Newspaper,Megaphone,CalendarDays,MessageCircle,ShieldCheck,Folder,Wallet,Vote,Briefcase,Store,TriangleAlert,ClipboardCheck,Contact,ImagePlus,Video,Share2,ThumbsUp,Bookmark} from 'lucide-react';
import {api,rows,str,type RecordData} from './api';
import {getLocale} from './i18n';
import {Action,ErrorBox,Loading,Empty,MutationForm,Field} from './ui';
import {PostMedia,SocialActions} from './PostMedia';
import {TranslatedText} from './TranslatedText';
import {DomainActions} from './domain';
import {Capacitor} from '@capacitor/core';
import {Share} from '@capacitor/share';
import {communityActivitySection,isUnreadCommunityActivity} from './communityActivity';
const groups=[
 ['Connect',[
  ['feed','Feed',Newspaper],['announcements','Announcements',Megaphone],['conversations','Chat',MessageCircle],['events','Events',CalendarDays],['marketplace','Marketplace',Store],['services','Services',Briefcase]
 ]],
 ['Community life',[
  ['meetings','Meetings',CalendarDays],['issues','Report issue',TriangleAlert],['polls','Polls',Vote],['finance','My finances',Wallet],['membership-card','Membership card',Contact],['documents','Documents',Folder],['members','Members',Users],['alerts','Emergency',ShieldCheck],['excos','Executive team',Users]
 ]]
] as const;
export function CommunityNavigation({id,title,menu=false,compose=false}:{id:string;title:string;menu?:boolean;compose?:boolean}){return <div className="community-section-heading"><Link className="button secondary" aria-label={menu||compose?'Back to feed':'Open community menu'} to={'/community/'+id+(menu||compose?'/feed':'/menu')}>{compose?<ArrowLeft size={21}/>:<Menu size={21}/>}</Link><h1>{title}</h1>{title==='Feed'&&<Link className="button secondary feed-create-button" aria-label="Create post" title="Create post" to={'/community/'+id+'/create-post'}><SquarePen size={21}/></Link>}</div>}
export function CommunityMenu({id,community}:{id:string;community:RecordData}){
 const q=useQuery({queryKey:['/communities/'+id+'/announcements'],queryFn:()=>api.get<RecordData[]>('/communities/'+id+'/announcements')});
 const notifications=useQuery({queryKey:['/me/notifications'],queryFn:({signal})=>api.get<RecordData[]>('/me/notifications',signal),refetchInterval:()=>document.visibilityState==='visible'&&navigator.onLine?5000:false,refetchOnWindowFocus:true});
 const announcements=rows(q.data),latest=announcements[0],activeSections=new Set(rows(notifications.data).filter(item=>isUnreadCommunityActivity(item,id)).map(communityActivitySection));
 return <div className="community-menu"><CommunityHero id={id} community={community}/>{latest&&<Link className="card community-latest" to={'/community/'+id+'/announcements'}><Megaphone/><div><strong>Community announcement</strong><p>{str(latest.Title)}</p><small>View details →</small></div></Link>}{groups.map(([heading,items])=><section key={heading}><h2>{heading}</h2><nav className="community-menu-grid" aria-label={heading}>{items.map(([path,label,Icon])=>{const hasActivity=activeSections.has(path);return <Link key={path} to={'/community/'+id+'/'+path} aria-label={hasActivity?label+', new activity':undefined}><span className="community-menu-icon"><Icon size={23}/>{hasActivity&&<i className="community-activity-dot" title="New activity" aria-hidden="true"/>}</span><strong>{label}</strong></Link>})}</nav></section>)}</div>
}
function date(value:unknown){const d=new Date(str(value));return Number.isNaN(d.getTime())?'':d.toLocaleString(getLocale(),{dateStyle:'medium',timeStyle:'short'})}
export function CommunityFeed({id,name,permissions,announcementsOnly=false}:{id:string;name:string;permissions:string[];announcementsOnly?:boolean}){
 const navigate=useNavigate();const [params,setParams]=useSearchParams(),tab=announcementsOnly?'announcements':params.get('tab')==='announcements'?'announcements':'all',[notice,setNotice]=useState(''),[search,setSearch]=useState('');const base='/communities/'+id;
 const posts=useQuery({queryKey:[base+'/feed'],queryFn:()=>api.get<RecordData[]>(base+'/feed')}),announcements=useQuery({queryKey:[base+'/announcements'],queryFn:()=>api.get<RecordData[]>(base+'/announcements')}),polls=useQuery({queryKey:[base+'/polls'],queryFn:()=>api.get<RecordData[]>(base+'/polls')}),events=useQuery({queryKey:[base+'/meetings'],queryFn:()=>api.get<RecordData[]>(base+'/meetings')});
 const community=useQuery({queryKey:[base],queryFn:()=>api.get<RecordData>(base)});
 const destination=(r:RecordData,kind:string)=>kind==='poll'?'/poll/'+id+'/'+r.Id:kind==='post'?'/post/'+r.Id:kind==='meeting'?'/community/'+id+'/meetings?meeting='+r.Id:'/community/'+id+'/announcements?announcement='+r.Id;
 const all=[...rows(polls.data).filter(r=>!!r.settings&&((r.settings as RecordData).visibility==='FEED'||(r.settings as RecordData).announcement)).map(r=>({r:{...r,Title:r.Question} as RecordData,kind:'poll'})),...rows(posts.data).map(r=>({r,kind:'post'})),...rows(announcements.data).map(r=>({r,kind:'announcement'})),...rows(events.data).map(r=>({r,kind:'meeting'}))].filter(({r,kind})=>(tab==='all'||tab==='announcements'&&(kind==='announcement'||kind==='meeting'||kind==='poll'&&!!(r.settings as RecordData)?.announcement||!!r.IsAnnouncement))&&[r.Title,r.Body,r.Description,r.Location].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(Date.parse(str(b.r.CreatedAt||b.r.StartDateTime))||0)-(Date.parse(str(a.r.CreatedAt||a.r.StartDateTime))||0));
 async function share(r:RecordData,kind:string){const url='https://cdaconnect.org'+destination(r,kind);try{if(Capacitor.isNativePlatform())await Share.share({title:str(r.Title)||name,url});else if(navigator.share)await navigator.share({title:str(r.Title)||name,url});else{await navigator.clipboard.writeText(url);setNotice('Link copied.')}}catch(e){if((e as Error).name!=='AbortError')setNotice('Sharing was unavailable. Please try again.')}}
 return <div className="community-feed"><HeaderSearch label="Search feed"><input aria-label="Search feed posts" placeholder="Search posts and announcements…" value={search} onChange={e=>setSearch(e.target.value)}/></HeaderSearch>{!announcementsOnly&&<nav className="feed-filter" aria-label="Feed filters">{[['all','All posts'],['announcements','Announcements']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setParams(key==='all'?{}:{tab:key})}>{label}</button>)}</nav>}<ErrorBox error={posts.error||announcements.error||events.error||polls.error}/>{posts.isPending||announcements.isPending||events.isPending||polls.isPending?<Loading/>:!all.length?<Empty text="No posts yet."/>:all.map(({r,kind})=><article className={'card feed-post'+(kind!=='post'?' feed-linked-card':'')} key={kind+str(r.Id)} onClick={kind!=='post'?e=>{if(!(e.target as HTMLElement).closest('a,button,input,video,audio,summary'))navigate(destination(r,kind))}:undefined}><header><Link className="feed-author" to={kind==='post'?"/member/"+r.CreatedBy:"/community/"+id+"/menu"}><span className="post-avatar">{(kind==='post'?r.ProfileImage:community.data?.LogoUrl)?<img src={api.asset(str(kind==='post'?r.ProfileImage:community.data?.LogoUrl))} alt=""/>:str(kind==='post'?r.FirstName:name).slice(0,1)}</span><div><strong>{kind==='post'?[r.FirstName,r.LastName].filter(Boolean).join(' ')||name:name}</strong><small>{date(r.CreatedAt)}{kind!=='post'?' · '+(kind==='event'?'Event':'Announcement'):''}</small></div></Link>{kind!=='post'&&<button className="feed-header-share" aria-label={'Share '+str(r.Title||'announcement')} onClick={()=>void share(r,kind)}><Share2 size={18}/><span className="sr-only">Share</span></button>}</header>{!!r.Title&&<h2>{kind==='post'?str(r.Title):<Link className="feed-content-link" to={destination(r,kind)}>{str(r.Title)}</Link>}</h2>}{kind==='post'?<div className="feed-post-body" role="link" tabIndex={0} aria-label="Open post" onClick={e=>{if(!(e.target as HTMLElement).closest('button,a'))navigate('/post/'+r.Id)}} onKeyDown={e=>{if(e.key==='Enter'&&e.target===e.currentTarget)navigate('/post/'+r.Id)}}><TranslatedText type="post" id={str(r.Id)} text={str(r.Body)}/></div>:<p className="prose">{str(r.Body||r.Description)}</p>}<PostMedia post={r}/>{kind==='meeting'&&<p>{date(r.StartDateTime)} · {str(r.Location)}</p>}{kind==='post'&&<SocialActions post={r}/>}</article>)}<p role="status">{notice}</p></div>
}


export function CommunityPostPage({id,name,permissions}:{id:string;name:string;permissions:string[]}){
 const community=useQuery({queryKey:['/communities/'+id],queryFn:()=>api.get<RecordData>('/communities/'+id)});
 const navigate=useNavigate(),[file,setFile]=useState<File>(),[preview,setPreview]=useState(''),[fileError,setFileError]=useState('');const base='/communities/'+id;
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 function selectFile(value:File|undefined,type:string){if(!value)return;if(!value.type.startsWith(type)){setFileError('Choose a supported photo or video.');return}if(value.size>20*1024*1024){setFileError('Choose a file up to 20 MB.');return}setFileError('');setFile(value)}
 return <section className="card community-post-page"><header><span className="post-avatar">{community.data?.LogoUrl?<img src={api.asset(str(community.data.LogoUrl))} alt=""/>:name.slice(0,1)}</span><div><strong>{name}</strong><p>Share with your community</p></div></header><MutationForm label="Publish post" onSuccess={()=>navigate('/community/'+id+'/feed',{replace:true})} onSubmit={async d=>{if(!d.body.trim()&&!file)throw Error('Write a post or attach a photo or video.');let media:RecordData={};if(file){if(file.size>20*1024*1024)throw Error('Choose a file up to 20 MB.');const form=new FormData();form.append('file',file);const uploaded=await api.upload<RecordData>('/media/upload',form);if(!uploaded.url)throw Error('Media upload failed.');media={mediaUrl:api.asset(str(uploaded.url)),mediaType:file.type,postType:file.type.startsWith('video/')?'VIDEO':'PHOTO'}}return api.send(base+'/feed',{body:d.body,postType:d.postType,isSensitive:d.isSensitive==='yes',...media})}}><Field name="body" label="Share with your community" type="textarea" required={false}/><div className="post-media-options"><label><ImagePlus size={18}/>Photo<input aria-label="Attach photo" type="file" accept="image/*" onChange={e=>selectFile(e.target.files?.[0],'image/')} /></label><label><Video size={18}/>Video<input aria-label="Attach video" type="file" accept="video/*" onChange={e=>selectFile(e.target.files?.[0],'video/')} /></label></div>{file&&<div className="post-attachment">{preview&&(file.type.startsWith('video/')?<video src={preview} controls preload="metadata"/>:<img src={preview} alt="Selected attachment"/>)}<p>{file.name}</p><button type="button" onClick={()=>setFile(undefined)}>Remove attachment</button></div>}{fileError&&<p role="alert">{fileError}</p>}<label>Post topic<select name="postType"><option value="TEXT">General</option><option value="LOCAL_NEWS">Local news</option><option value="QUESTION">Question</option><option value="OPPORTUNITY">Opportunity</option><option value="INITIATIVE">New initiative</option></select></label><label className="choice"><input type="checkbox" name="isSensitive" value="yes"/>Mark as sensitive content</label></MutationForm><nav className="post-other-actions" aria-label="Other community updates">{permissions.includes('EVENT_CREATE')&&<Link to={'/community/'+id+'/events'}><CalendarDays size={18}/>Create an event</Link>}<Link to={'/community/'+id+'/polls'}><Vote size={18}/>Create a poll</Link></nav></section>
}
