import {Capacitor} from '@capacitor/core';
import {useState,useRef} from 'react';
import {Link} from 'react-router-dom';
import {useQueryClient} from '@tanstack/react-query';
import {parsePhoneNumberFromString,getCountries,type CountryCode} from 'libphonenumber-js';
import {api,str} from './api';
import {Records,ErrorBox,Action} from './ui';
export function ContactSync({phone,enabled}:{phone:string;enabled:boolean}){
 const[country,setCountry]=useState<CountryCode>(parsePhoneNumberFromString(phone)?.country||'NG'),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),file=useRef<HTMLInputElement>(null),qc=useQueryClient();
 async function upload(numbers:string[]){const phones=[...new Set(numbers.map(v=>parsePhoneNumberFromString(v,country)).filter(v=>v?.isValid()).map(v=>v!.number))];if(!phones.length)throw Error('No valid phone numbers were found. Check the country selection.');if(phones.length>5000)throw Error('Choose a contact list with at most 5,000 phone numbers.');await api.send('/users/communications/contacts',{phones});await qc.invalidateQueries();setNotice('Contacts matched. Only eligible CDA Connect members appear below.');}
 async function sync(){setError(undefined);setNotice('');if(!Capacitor.isNativePlatform()&&!(navigator as Navigator&{contacts?:unknown}).contacts){file.current?.click();return}setBusy(true);try{
  if(Capacitor.isNativePlatform()){const{Contacts}=await import('@capacitor-community/contacts');const permission=await Contacts.requestPermissions();if(!['granted','limited'].includes(permission.contacts))throw Error('Contact permission was not granted. You can try again or import a contacts file.');const data=await Contacts.getContacts({projection:{phones:true}});await upload(data.contacts.flatMap(c=>(c.phones||[]).map(p=>p.number||'')));}
  else{const picker=(navigator as unknown as {contacts:{select:(fields:string[],options:{multiple:boolean})=>Promise<{tel?:string[]}[]>}}).contacts;const selected=await picker.select(['tel'],{multiple:true});await upload(selected.flatMap(c=>c.tel||[]));}
 }catch(e){if((e as Error).name!=='AbortError')setError(e)}finally{setBusy(false)}}
 return <><p>Choose contacts to find members in your communities who share their verified phone number. Only matched member IDs are saved; names and unmatched numbers from your address book are not retained.</p><p>Sync runs when you choose it here. Turning it off removes the saved matches.</p>{error!=null&&<ErrorBox error={error}/>}<section className="card"><label>Country for numbers without a country code<select value={country} onChange={e=>setCountry(e.target.value as CountryCode)}>{getCountries().map(c=><option value={c} key={c}>{new Intl.DisplayNames(['en'],{type:'region'}).of(c)||c}</option>)}</select></label><div className="actions"><button type="button" disabled={busy} onClick={sync}>{busy?'Syncing…':'Choose contacts and sync'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>file.current?.click()}>Import contacts file</button></div><input ref={file} className="sr-only" aria-label="Contacts vCard file" type="file" accept=".vcf,text/vcard,text/x-vcard" onChange={async e=>{const selected=e.target.files?.[0];e.target.value='';if(!selected)return;setBusy(true);setError(undefined);try{if(selected.size>5*1024*1024)throw Error('Choose a contacts file smaller than 5 MB.');const content=(await selected.text()).replace(/\r?\n[ \t]/g,'');const phones=[...content.matchAll(/^TEL(?:;[^:\r\n]*)?:(?:tel:)?([^\r\n]+)/gim)].map(m=>m[1]);await upload(phones)}catch(e){setError(e)}finally{setBusy(false)}}}/><p className="privacy-note">On browsers without contact access, select a .vcf file exported from your contacts app. This also works on desktop.</p></section><p role="status">{notice}</p>{enabled&&<Action danger run={async()=>{await api.send('/users/communications/contacts',{},'DELETE');await qc.invalidateQueries()}}>Turn off sync and remove matches</Action>}<Records endpoint="/users/communications/contacts" render={r=><Link to={'/member/'+r.Id}>{str(r.FirstName)} {str(r.LastName)}</Link>}/></>;
}
