import {currentPosition} from './location';
import {CommunityCreated} from './CommunityInvitation';
import {CommunityLocation,type LocationChoice} from './CommunityLocation';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Link,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Users,UserPlus,GraduationCap,Briefcase,Heart,Landmark,Drama,MoreHorizontal,PersonStanding,Goal,ImagePlus,Save} from 'lucide-react';
import {api,str,type RecordData} from './api';
import {Page,ErrorBox,Loading} from './ui';
const categories=[['CDA / Residents',Users],['Sports',Goal],['Educational',GraduationCap],['Professional',Briefcase],['Youth',PersonStanding],['Charity',Heart],['Religious',Landmark],['Cultural',Drama],['Social',UserPlus],['Other',MoreHorizontal]] as const;
export function CreateCommunity(){
 const {id}=useParams(),editing=!!id,initialized=useRef(false);const [createdCommunity,setCreatedCommunity]=useState<RecordData>();const [mapPosition,setMapPosition]=useState<{latitude:number;longitude:number}>(),[findingPosition,setFindingPosition]=useState(false);
 const [params,setParams]=useSearchParams(),step=params.get('step')==='preferences'?2:1;const [location,setLocation]=useState<LocationChoice>({countryCode:'',stateId:'',localArea:''}),[preferences,setPreferences]=useState({isPrivate:true,requireMemberApproval:true,allowMemberEvents:true,allowMemberDiscussions:true});
 const [locationReady,setLocationReady]=useState(false),[detailsReady,setDetailsReady]=useState(false);useEffect(()=>{if(step===2&&!detailsReady)setParams({},{replace:true})},[step,detailsReady,setParams]);
 const [name,setName]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState('CDA / Residents'),[specificArea,setSpecificArea]=useState(''),[guidelines,setGuidelines]=useState(''),[file,setFile]=useState<File>(),[preview,setPreview]=useState(''),[uploaded,setUploaded]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();const nav=useNavigate(),qc=useQueryClient();
 const eligibility=useQuery({queryKey:['/communities/creation-eligibility'],queryFn:()=>api.get<RecordData>('/communities/creation-eligibility'),enabled:!editing});
 const community=useQuery({queryKey:['/communities/'+id],queryFn:()=>api.get<RecordData>('/communities/'+id),enabled:editing});
 const capabilities=useQuery({queryKey:['/communities/'+id+'/capabilities'],queryFn:()=>api.get<{permissions:string[]}>('/communities/'+id+'/capabilities'),enabled:editing});
 const updateLocation=useCallback((value:LocationChoice)=>{setLocationReady(false);setLocation(value)},[]);
 useEffect(()=>{const c=community.data;if(!editing||!c||initialized.current)return;initialized.current=true;setName(str(c.Name));setDescription(str(c.Description));setCategory(str(c.Category||c.CommunityType)||'CDA / Residents');setSpecificArea(str(c.SpecificArea));setGuidelines(str(c.Guidelines));setPreferences({isPrivate:Boolean(c.IsPrivate),requireMemberApproval:true,allowMemberEvents:c.AllowMemberEvents===undefined?true:Boolean(c.AllowMemberEvents),allowMemberDiscussions:c.AllowMemberDiscussions===undefined?true:Boolean(c.AllowMemberDiscussions)});setDetailsReady(true);if(c.Latitude!==null&&c.Latitude!==undefined&&c.Longitude!==null&&c.Longitude!==undefined)setMapPosition({latitude:Number(c.Latitude),longitude:Number(c.Longitude)})},[community.data,editing]);
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 function choose(f?:File){setError(undefined);if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>5*1024*1024){setError(Error('Choose a PNG, JPG or WebP image up to 5 MB.'));return}setFile(f);setUploaded('')}
 async function uploadImage(){let logoUploadId=uploaded;if(file&&!logoUploadId){const data=new FormData();data.append('file',file);const result=await api.upload<RecordData>('/media/upload',data);logoUploadId=str(result.storedObjectId);if(!logoUploadId)throw Error('The image upload did not return a file ID. Please try again.');setUploaded(logoUploadId)}return logoUploadId}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;if(!name.trim()||!description.trim()||!location.countryCode||!guidelines.trim()){setError(Error('Enter a community name, description, location and community rules.'));return}if(step===1){setDetailsReady(true);setError(undefined);setParams({step:'preferences'});window.scrollTo({top:0});return}setBusy(true);setError(undefined);try{const logoUploadId=await uploadImage();if(editing){const c=community.data!;await api.send('/communities/'+id,{name:name.trim(),description:description.trim(),category,communityType:category,country:str(c.Country),state:str(c.State),lga:str(c.LGA),city:str(c.City),stateId:location.stateId,localArea:location.localArea,specificArea:specificArea.trim(),postcode:str(c.Postcode),...mapPosition,isPrivate:preferences.isPrivate,requireMemberApproval:true,allowMemberEvents:preferences.allowMemberEvents,allowMemberDiscussions:preferences.allowMemberDiscussions,guidelines:guidelines.trim(),tags:Array.isArray(c.Tags)?c.Tags:String(c.Tags||'').split(',').map(value=>value.trim()).filter(Boolean),logoUrl:str(c.LogoUrl),bannerUrl:str(c.BannerUrl)},'PATCH');if(logoUploadId)await api.send('/communities/'+id+'/image',{kind:'profile',uploadId:logoUploadId},'PATCH');await qc.invalidateQueries({queryKey:['/communities/'+id]});await qc.invalidateQueries({queryKey:['/communities']});nav('/community/'+id+'/profile',{replace:true});return}const created=await api.send<RecordData>('/communities',{name:name.trim(),description:description.trim(),category,communityType:category,stateId:location.stateId,localArea:location.localArea,...mapPosition,specificArea:specificArea.trim(),guidelines:guidelines.trim(),logoUploadId:logoUploadId||undefined,...preferences});setCreatedCommunity(created);void qc.invalidateQueries();window.scrollTo({top:0})}catch(caught){setError(caught)}finally{setBusy(false)}}
 if(editing&&(community.isPending||capabilities.isPending))return <Loading/>;
 if(editing&&(community.error||capabilities.error))return <Page title="Edit community"><ErrorBox error={community.error||capabilities.error}/></Page>;
 if(editing&&!capabilities.data?.permissions.includes('MEMBER_ROLE_CHANGE'))return <Page title="Edit community"><section className="card error" role="alert"><h2>You cannot edit this community</h2><p>Only authorized community managers can change these details.</p></section></Page>;
 if(createdCommunity)return <Page title="Create community"><CommunityCreated community={createdCommunity}/></Page>;
 const current=community.data,imagePreview=preview||(editing&&current?.LogoUrl?api.asset(str(current.LogoUrl)):'');
 return <Page title={editing?'Edit community':'Create a community'}><div className="create-community">
 {!editing&&eligibility.data&&!eligibility.data.eligible&&<section className="card error" role="alert"><h2>Community creation is unavailable</h2><p>{str(eligibility.data.reason)}</p>{!!eligibility.data.nextEligibleAt&&<p>You can try again after {new Date(str(eligibility.data.nextEligibleAt)).toLocaleString()}.</p>}</section>}
 <form onSubmit={submit}><fieldset disabled={busy||(!editing&&eligibility.isPending)||eligibility.data?.eligible===false}><div className="create-details-step" hidden={step!==1}>
 <section><h2>1. Basic Information</h2><p>Tell us about your community</p><div className="card create-fields"><label>Community Name *<input name="name" required minLength={2} maxLength={200} value={name} onChange={event=>setName(event.target.value)} placeholder="e.g. Riverside Community"/></label><label>Description *<textarea name="description" required maxLength={500} value={description} onChange={event=>setDescription(event.target.value)} placeholder="Describe your community, its purpose and what members can expect…"/></label><small className="create-counter">{description.length}/500</small></div></section>
 <section><h2>2. Category</h2><p>Choose the category that best fits your community</p><label>Community category<select aria-label="Community category" value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(([categoryName])=><option key={categoryName} value={categoryName}>{categoryName}</option>)}</select></label></section>
 <section><h2>3. Location</h2><p>Help people find your community</p><CommunityLocation value={location} onChange={updateLocation} onReady={setLocationReady} country={editing?str(current?.Country):undefined} initialState={editing?str(current?.State):''} initialArea={editing?str(current?.LGA||current?.City):''} specificArea={specificArea} onSpecificAreaChange={setSpecificArea}/></section>
 <section className="card"><h2>Map position (optional)</h2><p>If you are at the community centre or meeting point, add its position to help nearby members find this community.</p><button type="button" disabled={findingPosition} onClick={async()=>{setFindingPosition(true);setError(undefined);try{setMapPosition(await currentPosition())}catch(caught){setError(caught)}finally{setFindingPosition(false)}}}>{findingPosition?'Finding position…':'Use current position'}</button>{mapPosition&&<><p role="status">Map position added: {mapPosition.latitude.toFixed(4)}, {mapPosition.longitude.toFixed(4)}</p><button type="button" onClick={()=>setMapPosition(undefined)}>Remove map position</button></>}</section>
 <section className="card"><h2>4. Community Image</h2><p>Add a logo or photo to represent your community</p><label className="create-upload">{imagePreview?<img src={imagePreview} alt="Community image preview"/>:<ImagePlus size={30}/>}<strong>{file||editing?'Change image':'Tap to upload an image'}</strong><small>PNG, JPG or WebP (Max 5 MB)</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>{choose(event.target.files?.[0]);event.target.value=''}}/></label>{file&&<button type="button" className="secondary" onClick={()=>{setFile(undefined);setUploaded('')}}>Keep current image</button>}</section>
 <section><h2>5. Community Rules *</h2><p>Set guidelines to keep your community safe and respectful</p><label className="sr-only" htmlFor="create-rules">Community rules</label><textarea id="create-rules" name="guidelines" required maxLength={2000} value={guidelines} onChange={event=>setGuidelines(event.target.value)} placeholder="e.g. Be respectful, no spam, support each other…"/></section>
 </div>{step===2&&<section className="create-preferences"><h2>Community Preferences</h2><p>Choose how people join and participate. You can change these settings later.</p><div className="settings-list">{([['public','Public community','Members can find this community in search and request to join. Invite codes and links also work.'],['private','Private community','Hidden from search. A valid invite code or invite link is required to request to join.']] as const).map(([value,title,preferenceDescription])=><label key={value} className="settings-row account-switch-row"><span className="settings-row-text"><strong>{title}</strong><small>{preferenceDescription}</small></span><input type="checkbox" role="switch" checked={value==='private'?preferences.isPrivate:!preferences.isPrivate} onChange={event=>setPreferences(previous=>({...previous,isPrivate:value==='private'?event.target.checked:!event.target.checked}))}/></label>)}{([['requireMemberApproval','Approve join requests','Review requests before people become members.'],['allowMemberEvents','Allow member events','Members can create community events.'],['allowMemberDiscussions','Allow member discussions','Members can create community discussion groups.']] as const).map(([key,title,preferenceDescription])=><label key={key} className="settings-row account-switch-row"><span className="settings-row-text"><strong>{title}</strong><small>{preferenceDescription}</small></span><input type="checkbox" role="switch" checked={preferences[key]} disabled={key==='requireMemberApproval'} onChange={event=>setPreferences(previous=>({...previous,[key]:event.target.checked}))}/></label>)}</div></section>}<ErrorBox error={error}/><div className="create-footer-actions">{step===2&&<button className="secondary" type="button" onClick={()=>setParams({})}>Back to community details</button>}<button className="primary create-submit" type="submit" disabled={!locationReady||busy}>{editing?<Save size={20}/>:<UserPlus size={20}/>} {busy?(editing?'Saving community…':'Creating community…'):step===1?'Next':editing?'Save changes':'Create Community'}</button></div><p role="status">{busy?(editing?'Saving your community changes.':'Uploading your image, if selected, and creating your community.'):''}</p></fieldset></form><Link className="create-guidelines" to="/settings/privacy/guidelines">Community guidelines and safety information</Link></div></Page>;
}