import {currentPosition} from './location';
import {CommunityCreated} from './CommunityInvitation';
import {CommunityLocation,type LocationChoice} from './CommunityLocation';
import {useState,useEffect,type FormEvent} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {useQueryClient} from '@tanstack/react-query';
import {Users,UserPlus,GraduationCap,Briefcase,Heart,Landmark,Drama,MoreHorizontal,PersonStanding,Goal,ImagePlus,RefreshCw,ShieldCheck,HelpCircle,ArrowLeft} from 'lucide-react';
import {api,str,type RecordData} from './api';
import {Page,ErrorBox} from './ui';
const categories=[['CDA / Residents',Users],['Sports',Goal],['Educational',GraduationCap],['Professional',Briefcase],['Youth',PersonStanding],['Charity',Heart],['Religious',Landmark],['Cultural',Drama],['Social',UserPlus],['Other',MoreHorizontal]] as const;
export function CreateCommunity(){
 const [createdCommunity,setCreatedCommunity]=useState<RecordData>();const [mapPosition,setMapPosition]=useState<{latitude:number;longitude:number}>(),[findingPosition,setFindingPosition]=useState(false);
 const [params,setParams]=useSearchParams(),step=params.get('step')==='preferences'?2:1;const [location,setLocation]=useState<LocationChoice>({countryCode:'',stateId:'',localArea:''}),[preferences,setPreferences]=useState({isPrivate:true,requireMemberApproval:true,allowMemberEvents:true,allowMemberDiscussions:true});
 const [locationReady,setLocationReady]=useState(false),[detailsReady,setDetailsReady]=useState(false);useEffect(()=>{if(step===2&&!detailsReady)setParams({},{replace:true})},[step,detailsReady,setParams]);
 const [description,setDescription]=useState(''),[category,setCategory]=useState('CDA / Residents'),[file,setFile]=useState<File>(),[preview,setPreview]=useState(''),[uploaded,setUploaded]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[help]=useState(false);const nav=useNavigate(),qc=useQueryClient();
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 function choose(f?:File){setError(undefined);if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>5*1024*1024){setError(Error('Choose a PNG, JPG or WebP image up to 5 MB.'));return}setFile(f);setUploaded('')}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const d=Object.fromEntries(new FormData(e.currentTarget));if(!String(d.name).trim()||!description.trim()||!location.countryCode||!String(d.guidelines||'').trim()){setError(Error('Enter a community name, description, location and community rules.'));return}if(step===1){setDetailsReady(true);setError(undefined);setParams({step:'preferences'});window.scrollTo({top:0});return}setBusy(true);setError(undefined);try{let logoUploadId=uploaded;if(file&&!logoUploadId){const data=new FormData();data.append('file',file);const r=await api.upload<RecordData>('/media/upload',data);logoUploadId=str(r.storedObjectId);if(!logoUploadId)throw Error('The image upload did not return a file ID. Please try again.');setUploaded(logoUploadId)}const created=await api.send<RecordData>('/communities',{name:String(d.name).trim(),description:description.trim(),category,communityType:category,stateId:location.stateId,localArea:location.localArea,...mapPosition,specificArea:String(d.specificArea||'').trim(),guidelines:String(d.guidelines||'').trim(),logoUploadId:logoUploadId||undefined,...preferences});setCreatedCommunity(created);void qc.invalidateQueries();window.scrollTo({top:0})}catch(e){setError(e)}finally{setBusy(false)}}
 if(createdCommunity)return <Page title="Create community"><CommunityCreated community={createdCommunity}/></Page>;
 return <Page title="Create a community"><div className="create-community">
 {help&&<section className="card"><h2>Creating your community</h2><p>You become the owner and administrator. Choose privacy and participation options on the next step. Share the invite code with people you want to invite. You can manage community details and membership after creation.</p><p>Choose a clear name and category, add your location and write rules for your members. Image upload is optional.</p><Link to="/settings/support">Contact support</Link></section>}
 <form onSubmit={submit}><fieldset disabled={busy}><div className="create-details-step" hidden={step!==1}>
 <section><h2>1. Basic Information</h2><p>Tell us about your community</p><div className="card create-fields"><label>Community Name *<input name="name" required minLength={2} maxLength={200} placeholder="e.g. Riverside Community"/></label><label>Description *<textarea name="description" required maxLength={500} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe your community, its purpose and what members can expect…"/></label><small className="create-counter">{description.length}/500</small></div></section>
 <section><h2>2. Category</h2><p>Choose the category that best fits your community</p><label>Community category<select aria-label="Community category" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(([name])=><option key={name} value={name}>{name}</option>)}</select></label></section>
 <section><h2>3. Location</h2><p>Help people find your community</p><CommunityLocation value={location} onChange={v=>{setLocationReady(false);setLocation(v)}} onReady={setLocationReady}/></section>
 <section className="card"><h2>Map position (optional)</h2><p>If you are at the community centre or meeting point, add its position to help nearby members find this community.</p><button type="button" disabled={findingPosition} onClick={async()=>{setFindingPosition(true);setError(undefined);try{setMapPosition(await currentPosition())}catch(e){setError(e)}finally{setFindingPosition(false)}}}>{findingPosition?'Finding position…':'Use current position'}</button>{mapPosition&&<><p role="status">Map position added: {mapPosition.latitude.toFixed(4)}, {mapPosition.longitude.toFixed(4)}</p><button type="button" onClick={()=>setMapPosition(undefined)}>Remove map position</button></>}</section><section className="card"><h2>4. Community Image</h2><p>Add a logo or photo to represent your community</p><label className="create-upload">{preview?<img src={preview} alt="Community image preview"/>:<ImagePlus size={30}/>}<strong>{file?'Change image':'Tap to upload an image'}</strong><small>PNG, JPG or WebP (Max 5 MB)</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{choose(e.target.files?.[0]);e.target.value=''}}/></label>{file&&<button type="button" className="secondary" onClick={()=>{setFile(undefined);setUploaded('')}}>Remove image</button>}</section>

 <section><h2>5. Community Rules *</h2><p>Set guidelines to keep your community safe and respectful</p><label className="sr-only" htmlFor="create-rules">Community rules</label><textarea id="create-rules" name="guidelines" required maxLength={2000} placeholder="e.g. Be respectful, no spam, support each other…"/></section>
 </div>{step===2&&<section className="create-preferences"><h2>Community Preferences</h2><p>Choose how people join and participate. You can change these settings later.</p><div className="settings-list">{([['public','Public community','Members can find this community in search and request to join. Invite codes and links also work.'],['private','Private community','Hidden from search. A valid invite code or invite link is required to request to join.']] as const).map(([value,title,description])=><label key={value} className="settings-row account-switch-row"><span className="settings-row-text"><strong>{title}</strong><small>{description}</small></span><input type="checkbox" role="switch" checked={value==='private'?preferences.isPrivate:!preferences.isPrivate} onChange={e=>setPreferences(p=>({...p,isPrivate:value==='private'?e.target.checked:!e.target.checked}))}/></label>)}{([['requireMemberApproval','Approve join requests','Review requests before people become members.'],['allowMemberEvents','Allow member events','Members can create community events.'],['allowMemberDiscussions','Allow member discussions','Members can create community discussion groups.']] as const).map(([key,title,description])=><label key={key} className="settings-row account-switch-row"><span className="settings-row-text"><strong>{title}</strong><small>{description}</small></span><input type="checkbox" role="switch" checked={preferences[key]} disabled={key==='requireMemberApproval'} onChange={e=>setPreferences(p=>({...p,[key]:e.target.checked}))}/></label>)}</div></section>}<ErrorBox error={error}/><div className="create-footer-actions">{step===2&&<button className="secondary" type="button" onClick={()=>setParams({})}>Back to community details</button>}<button className="primary create-submit" type="submit" disabled={!locationReady||busy}><UserPlus size={20}/>{busy?'Creating community…':step===1?'Next':'Create Community'}</button></div><p role="status">{busy?'Uploading your image, if selected, and creating your community.':''}</p></fieldset></form><Link className="create-guidelines" to="/settings/privacy/guidelines">Community guidelines and safety information</Link></div></Page>;
}

