import {Link,useSearchParams} from 'react-router-dom';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {FolderOpen,FileText,Upload,ArrowLeft,Search,MoreVertical,X,Download,History} from 'lucide-react';
import {Capacitor} from '@capacitor/core';
import {api,str,type RecordData} from './api';
import {Loading,ErrorBox} from './ui';
import {getLocale} from './i18n';
import './documents.css';
const categories=['Constitution','Policies','Meeting minutes','Financial reports','Forms','Newsletters','Community rules','Emergency procedures','Archives','Other'];
const size=(n:unknown)=>Number(n)>1048576?(Number(n)/1048576).toFixed(1)+' MB':Math.ceil(Number(n||0)/1024)+' KB';
const format=(d:unknown)=>d?new Date(str(d)).toLocaleDateString(getLocale(),{day:'numeric',month:'short',year:'numeric'}):'Date unavailable';
export function Documents({id,permissions}:{id:string;permissions:string[]}){
 const path='/communities/'+id+'/documents',qc=useQueryClient(),q=useQuery({queryKey:[path],queryFn:({signal})=>api.get<RecordData[]>(path,signal)});
 const [params]=useSearchParams(),folder=params.get('folder')||'',validFolder=categories.includes(folder);
 const [search,setSearch]=useState(''),[sort,setSort]=useState('recent'),[selected,setSelected]=useState<RecordData|null>(null),[version,setVersion]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState('');
 const upload=useRef<HTMLDialogElement>(null),detail=useRef<HTMLDialogElement>(null),input=useRef<HTMLInputElement>(null),canManage=permissions.includes('DOCUMENT_MANAGE');
 const history=useQuery({queryKey:['document-history',selected?.Id],queryFn:({signal})=>api.get<RecordData[]>('/documents/'+selected?.Id+'/history',signal),enabled:!!selected});
 useEffect(()=>{setSearch('');setNotice('');setError(undefined);setSelected(null);detail.current?.close();upload.current?.close()},[folder]);
 const data=Array.isArray(q.data)?q.data:[];
 const visible=data.filter(d=>str(d.Category)===folder&&[d.Title,d.Summary,d.FileName].some(v=>str(v).toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>sort==='name'?str(a.Title).localeCompare(str(b.Title)):new Date(str(b.UpdatedAt)).getTime()-new Date(str(a.UpdatedAt)).getTime());
 function open(d:RecordData){setSelected(d);setError(undefined);detail.current?.showModal()}
 async function download(d:RecordData){setBusy(true);setError(undefined);try{const {url}=await api.send<{url:string}>('/documents/'+d.Id+'/download-url');if(new URL(url).protocol!=='https:')throw Error('Download requires a secure HTTPS link.');if(Capacitor.isNativePlatform()){const {Filesystem,Directory}=await import('@capacitor/filesystem');const {Share}=await import('@capacitor/share');const name=str(d.FileName).replace(/[^a-zA-Z0-9._-]/g,'_')||'document';const result=await Filesystem.downloadFile({url,path:Date.now()+'-'+name,directory:Directory.Cache});if(!result.path)throw Error('Download could not be saved.');await Share.share({title:str(d.Title),files:[result.path]})}else{const a=document.createElement('a');a.href=url;a.download=str(d.FileName);a.rel='noopener';document.body.append(a);a.click();a.remove()}setNotice('Download prepared.')}catch(e){setError(e)}finally{setBusy(false)}}
 function showUpload(newVersion=false){setVersion(newVersion);setError(undefined);detail.current?.close();upload.current?.showModal()}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget,f=new FormData(form),file=f.get('file');if(!(file instanceof File)||!file.size){setError(Error('Choose a document.'));return}if(file.size>25*1024*1024){setError(Error('Choose a file no larger than 25 MB.'));return}setBusy(true);setError(undefined);let objectId='';try{const body=new FormData();body.append('file',file);const uploaded=await api.upload<{storedObjectId:string}>('/media/upload?purpose=document&communityId='+id,body);objectId=uploaded.storedObjectId;if(version&&selected)await api.send('/documents/'+selected.Id+'/versions',{storedObjectId:objectId,changeNotes:String(f.get('changeNotes'))});else await api.send(path,{title:String(f.get('title')).trim(),category:folder,summary:String(f.get('summary')),visibility:String(f.get('visibility')),storedObjectId:objectId});await qc.invalidateQueries({queryKey:[path]});await qc.invalidateQueries({queryKey:['document-history']});upload.current?.close();form.reset();setSelected(null);setNotice(version?'New version uploaded.':'Document uploaded.')}catch(e){setError(e);if(objectId)await api.send('/media/uploads/'+objectId,{},'DELETE').catch(()=>{})}finally{setBusy(false)}}
 return <div className="document-center">{folder&&<header className="doc-heading doc-folder-heading"><div>{folder&&<Link className="doc-back" to={'/community/'+id+'/documents'} aria-label="Back to document folders"><ArrowLeft size={20}/></Link>}<h1>{folder}</h1></div>{validFolder&&canManage&&<button className="doc-header-upload" aria-label="Upload document to this folder" title="Upload document" onClick={()=>showUpload()}><Upload size={20}/></button>}</header>}
 {!folder?<>{q.isPending?<Loading/>:q.error?<ErrorBox error={q.error}/>:<nav className="doc-folder-grid" aria-label="Document folders">{categories.map(name=>{const count=data.filter(d=>str(d.Category)===name).length;return <Link key={name} to={'/community/'+id+'/documents?folder='+encodeURIComponent(name)}><FolderOpen aria-hidden="true"/><strong>{name}</strong><span>{count} {count===1?'document':'documents'}</span></Link>})}</nav>}</>:!validFolder?<div className="doc-empty"><strong>Folder not found</strong><Link to={'/community/'+id+'/documents'}>Return to folders</Link></div>:<section className="doc-panel"><div className="doc-search"><Search size={18}/><input ref={input} aria-label="Search documents" placeholder={'Search '+folder.toLowerCase()+'…'} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Sort documents" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Newest first</option><option value="name">Name A–Z</option></select></div>
 {q.isPending?<Loading/>:q.error?<ErrorBox error={q.error}/>:visible.length?<div className="doc-list">{visible.map(d=>{const ext=str(d.FileName).split('.').pop()?.toUpperCase()||'FILE';return <article key={str(d.Id)}><button className="doc-row" onClick={()=>open(d)}><span className={'doc-file '+(ext==='PDF'?'pdf':ext.startsWith('XLS')?'sheet':ext.startsWith('PPT')?'slides':'word')}><FileText/><small>{ext.slice(0,5)}</small></span><span className="doc-title"><strong>{str(d.Title)}</strong><small>{str(d.Category)} · {ext} · {size(d.SizeBytes)}</small></span><span className="doc-meta"><span>{format(d.UpdatedAt)}</span><small>{[d.UploaderFirstName,d.UploaderLastName].filter(Boolean).join(' ')||'Community'}</small></span></button><button className="doc-more" aria-label={'Actions for '+str(d.Title)} onClick={()=>open(d)}><MoreVertical size={18}/></button></article>})}</div>:<div className="doc-empty"><FolderOpen/><strong>{search?'No matching documents':'This folder is empty'}</strong><p>{search?'Try a different search.':'Documents uploaded to this folder will appear here.'}</p></div>}
 </section>}
 {notice&&<p role="status">{notice}</p>}{!upload.current?.open&&!detail.current?.open&&<ErrorBox error={error}/>}
 <dialog ref={detail} className="doc-dialog"><div className="doc-heading"><h2>{str(selected?.Title)}</h2><button aria-label="Close document" onClick={()=>detail.current?.close()}><X/></button></div><p>{str(selected?.Summary)||'No description provided.'}</p><p>{str(selected?.Category)} · {str(selected?.FileName)} · {size(selected?.SizeBytes)}</p><p>{selected?.Visibility==='ADMINS'?'Managers only':'Community members'} · Version {Number(selected?.CurrentVersion||1)}</p><button disabled={busy||!selected?.FileName} className="primary" onClick={()=>selected&&void download(selected)}><Download size={17}/>{busy?'Preparing…':'Download document'}</button>{canManage&&<button className="secondary" onClick={()=>showUpload(true)}><Upload size={17}/>Upload new version</button>}<ErrorBox error={error}/><h3><History size={17}/>Version history</h3>{history.isPending?<Loading/>:history.error?<ErrorBox error={history.error}/>:history.data?.map(v=><div className="doc-version" key={str(v.Id)}><strong>Version {Number(v.VersionNumber)}</strong><span>{format(v.UploadedAt)}</span><p>{str(v.ChangeNotes)}</p></div>)}</dialog>
 <dialog ref={upload} className="doc-dialog" onCancel={e=>{if(busy)e.preventDefault()}}><div className="doc-heading"><h2>{version?'Upload new version':'Upload Document'}</h2><button disabled={busy} aria-label="Close upload" onClick={()=>upload.current?.close()}><X/></button></div><form onSubmit={submit}><fieldset disabled={busy}>{!version&&<><label>Document title<input name="title" required minLength={2} maxLength={250}/></label><p className="doc-upload-folder">Folder: <strong>{folder}</strong></p><label>Description<textarea name="summary" maxLength={2000}/></label><label>Who can access<select name="visibility"><option value="MEMBERS">Community members</option><option value="ADMINS">Document managers only</option></select></label></>}{version&&<label>What changed?<textarea name="changeNotes" required minLength={2} maxLength={1000}/></label>}<label className="doc-file-input"><Upload/>Choose document<input type="file" name="file" required accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv,.jpg,.jpeg,.png"/><small>PDF, Office, text or images · up to 25 MB</small></label><ErrorBox error={error}/><button className="primary" type="submit">{busy?'Uploading…':'Upload document'}</button></fieldset></form></dialog>
 </div>
}
