import {useEffect,useRef,useState} from 'react';
import type {PDFDocumentProxy,RenderTask} from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?worker&url';
import {api} from './api';
import {ErrorBox,Loading} from './ui';
export function DocumentReader({id,name,sizeBytes=0}:{id:string;name:string;sizeBytes?:number}){
 const[pdf,setPdf]=useState<PDFDocumentProxy>(),[page,setPage]=useState(1),[src,setSrc]=useState(''),[text,setText]=useState(''),[error,setError]=useState<unknown>(),[loading,setLoading]=useState(true),[rendering,setRendering]=useState(true),[width,setWidth]=useState(300),[pageText,setPageText]=useState('');const host=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null);const ext=name.split('.').pop()?.toLowerCase(),supported=['pdf','png','jpg','jpeg','txt','csv'].includes(ext||'');
 useEffect(()=>{if(!host.current)return;const observer=new ResizeObserver(entries=>setWidth(Math.max(100,entries[0].contentRect.width)));observer.observe(host.current);return()=>observer.disconnect()},[]);
 useEffect(()=>{let disposed=false,object='',task:ReturnType<typeof import('pdfjs-dist')['getDocument']>|undefined;const controller=new AbortController();setLoading(true);setError(undefined);setPdf(undefined);setPage(1);setSrc('');setText('');(async()=>{try{if(!supported)return;if(sizeBytes>8*1024*1024)throw Error('This file is too large for an inline preview. Use the download icon to open it safely.');const {url}=await api.send<{url:string}>('/documents/'+id+'/download-url');if(new URL(url).protocol!=='https:')throw Error('Document requires a secure link.');const response=await fetch(url,{signal:controller.signal,cache:'no-store'});if(!response.ok)throw Error('Unable to open document. Please reload to retry.');if(Number(response.headers.get('content-length'))>8*1024*1024)throw Error('Preview limit is 8 MB. Download this file to open it.');const reader=response.body?.getReader();if(!reader)throw Error('Unable to read document');let total=0;const chunks:Uint8Array<ArrayBuffer>[]=[];while(true){const {value,done}=await reader.read();if(done)break;total+=value.byteLength;if(total>8*1024*1024){await reader.cancel();throw Error('Preview limit is 8 MB. Download this file to open it.')}chunks.push(value as Uint8Array<ArrayBuffer>)}const blob=new Blob(chunks,{type:response.headers.get('content-type')||'application/octet-stream'});if(disposed)return;if(ext==='pdf'){const lib=await import('pdfjs-dist');if(disposed)return;lib.GlobalWorkerOptions.workerSrc=workerUrl;task=lib.getDocument({data:new Uint8Array(await blob.arrayBuffer())});const doc=await task.promise;if(!disposed)setPdf(doc)}else if(ext==='txt'||ext==='csv'){const value=await blob.text();if(!disposed)setText(value)}else{object=URL.createObjectURL(blob);setSrc(object)}}catch(e){if(!disposed)setError(e)}finally{if(!disposed)setLoading(false)}})();return()=>{disposed=true;controller.abort();void task?.destroy();if(object)URL.revokeObjectURL(object)}},[id,name,sizeBytes]);
 useEffect(()=>{if(!pdf)return;let cancelled=false,render:RenderTask|undefined;setRendering(true);setPageText('');(async()=>{try{const p=await pdf.getPage(page);if(cancelled||!canvas.current)return;const viewport=p.getViewport({scale:width/p.getViewport({scale:1}).width}),ratio=Math.min(devicePixelRatio||1,2);const c=canvas.current;c.width=Math.ceil(viewport.width*ratio);c.height=Math.ceil(viewport.height*ratio);c.style.width='100%';render=p.render({canvas:c,viewport,transform:[ratio,0,0,ratio,0,0]});await render.promise;if(!cancelled)setRendering(false);const content=await p.getTextContent();if(!cancelled)setPageText(content.items.slice(0,2000).map(i=>'str' in i?i.str:'').join(' ').slice(0,20000))}catch(e){if(!cancelled)setError(e)}})();return()=>{cancelled=true;render?.cancel()}},[pdf,page,width]);
 return <div ref={host} className="document-reader" aria-label="Document contents">{(loading||(!!pdf&&rendering))&&!error&&<p role="status">Opening document…</p>}<ErrorBox error={error}/>{!supported&&<p>This file format cannot be previewed here. Use the download icon below to open it in a compatible app.</p>}{pdf&&<><canvas ref={canvas} style={{visibility:rendering?'hidden':'visible'}} aria-label={'Document page '+page}/>{!rendering&&<><details><summary>Page text</summary><p>{pageText}</p></details><nav aria-label="Document pages"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {pdf.numPages}</span><button disabled={page>=pdf.numPages} onClick={()=>setPage(p=>p+1)}>Next</button></nav></>}</>}{src&&<img src={src} alt={name}/>} {!!text&&<pre>{text}</pre>}</div>
}
