import {getLocale} from './i18n';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api,str,rows,type RecordData} from './api';
import {Action,ErrorBox,Field,MutationForm,Records,Loading} from './ui';
type Schema={permission?:string;fields:{name:string;label:string;type?:string;options?:string[]}[];convert?:(v:Record<string,string>)=>RecordData};
const schemas:Record<string,Schema>={
 events:{permission:'EVENT_CREATE',fields:[{name:'title',label:'Event title'},{name:'description',label:'Description',type:'textarea'},{name:'location',label:'Location'},{name:'startDateTime',label:'Starts',type:'datetime-local'},{name:'endDateTime',label:'Ends',type:'datetime-local'}],convert:d=>{if(new Date(d.endDateTime)<=new Date(d.startDateTime))throw Error('End time must follow the start.');return{...d,startDateTime:new Date(d.startDateTime).toISOString(),endDateTime:new Date(d.endDateTime).toISOString()}}},
 marketplace:{fields:[{name:'title',label:'Item title'},{name:'description',label:'Description',type:'textarea'},{name:'area',label:'Collection area'},{name:'price',label:'Price',type:'number'},{name:'currency',label:'Currency code (e.g. NGN)'},{name:'listingType',label:'Listing type',options:['FOR_SALE','FREE','WANTED','SERVICES','RENTALS','JOBS']}],convert:d=>({...d,price:Number(d.price)})},
 services:{fields:[{name:'name',label:'Service name'},{name:'category',label:'Category'},{name:'description',label:'Description',type:'textarea'},{name:'phone',label:'Contact phone',type:'tel'},{name:'area',label:'Area served'}]},
 issues:{fields:[{name:'title',label:'Issue title'},{name:'description',label:'What happened?',type:'textarea'},{name:'category',label:'Category',options:['Broken streetlight','Pothole','Waste problem','Water issue','Security concern','Noise','Damaged facility','Flooding','Other']},{name:'approximateLocation',label:'Approximate location'}]},
 'governance/proposals':{fields:[{name:'title',label:'Proposal title'},{name:'summary',label:'Summary',type:'textarea'},{name:'body',label:'Full proposal',type:'textarea'}]},
 alerts:{permission:'EMERGENCY_SEND',fields:[{name:'title',label:'Alert title'},{name:'message',label:'Instructions',type:'textarea'},{name:'alertType',label:'Incident type'},{name:'severity',label:'Severity',options:['INFO','NOTICE','WARNING','HIGH','CRITICAL']}]}
};
export function DomainCreate({section,base,permissions}:{section:string;base:string;permissions:string[]}){const[open,setOpen]=useState(false);const schema=schemas[section];if(!schema||schema.permission&&!permissions.includes(schema.permission))return null;return <><button className="primary" onClick={()=>setOpen(!open)}>{open?'Cancel':'Create new'}</button>{open&&<div className="card"><MutationForm label="Submit" onSuccess={()=>setOpen(false)} onSubmit={d=>api.send(base+'/'+section,schema.convert?schema.convert(d):d)}>{schema.fields.map(f=>f.options?<label key={f.name}>{f.label}<select name={f.name}>{f.options.map(o=><option key={o}>{o}</option>)}</select></label>:<Field key={f.name} {...f}/>)}</MutationForm></div>}</>}
export function DomainActions({section,r}:{section:string;r:RecordData}){return <>{section==='events'&&<div className="actions">{['GOING','NOT_GOING'].map(status=><Action key={status} run={()=>api.send('/events/'+r.Id+'/rsvp',{status})}>{status==='GOING'?'Register':'Cancel registration'}</Action>)}</div>}{section==='marketplace'&&<><p>{str(r.Currency)} {str(r.Price)} · {str(r.Area)}</p><Action run={()=>api.send('/marketplace/'+r.Id+'/save')}>Toggle saved</Action></>}{section==='documents'&&<Download id={str(r.Id)}/>}</>}
function Download({id}:{id:string}){const[url,setUrl]=useState('');return <><Action run={async()=>{const data=await api.send<{url:string}>('/documents/'+id+'/download-url');const u=new URL(data.url);if(u.protocol!=='https:'&&import.meta.env.PROD)throw Error('Download link must use HTTPS.');setUrl(data.url)}}>Prepare download</Action>{url&&<a className="button secondary" href={url} target="_blank" rel="noreferrer">Download (expires in five minutes)</a>}</>}
export {Finance} from './LevyFinance';
export {Attendance} from './Attendance';
export function Support(){return <><div className="card narrow"><h2>Contact support</h2><MutationForm label="Submit ticket" onSubmit={d=>api.send('/me/support-tickets',d)}><label>Category<select name="category">{['GENERAL','ACCOUNT','TECHNICAL','SAFETY','PAYMENTS'].map(c=><option key={c}>{c}</option>)}</select></label><Field name="subject" label="Subject"/><Field name="message" label="Message (at least 10 characters)" type="textarea"/></MutationForm></div><Records endpoint="/me/support-tickets" render={r=><><h3>{str(r.Subject)}</h3><p>{str(r.Message)}</p><span className="badge">{str(r.Status)}</span></>}/></>}

