import {useEffect,useState} from 'react';
import {useQueries,useQuery} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {MessageCircle,Megaphone,CalendarDays,ShoppingBag,Vote} from 'lucide-react';
import {api,rows,str,type RecordData} from './api';
import {useSession} from './auth';
import {Page,Loading,ErrorBox} from './ui';
import {HeaderSearch} from './HeaderSearch';
import {getLocale} from './i18n';
import './home-activities.css';
const sources=[['feed','Post',MessageCircle],['announcements','Announcement',Megaphone],['meetings','Meeting',CalendarDays],['events','Event',CalendarDays],['marketplace','Marketplace',ShoppingBag],['polls','Poll',Vote]] as const;
export function activityLink(type:string,community:string,id:string){const base='/community/'+encodeURIComponent(community);switch(type){case 'feed':return '/post/'+encodeURIComponent(id);case 'announcements':return base+'/announcements?announcement='+encodeURIComponent(id);case 'meetings':return base+'/meetings?meeting='+encodeURIComponent(id);case 'events':return base+'/events?event='+encodeURIComponent(id);case 'marketplace':return base+'/marketplace?listing='+encodeURIComponent(id);case 'polls':return '/poll/'+encodeURIComponent(community)+'/'+encodeURIComponent(id);default:return base+'/feed'}}
export function greeting(hour:number){return hour<12?'Good morning':hour<17?'Good afternoon':'Good evening'}
export function Home(){const session=useSession(),[now,setNow]=useState(()=>new Date()),[search,setSearch]=useState(''),[limit,setLimit]=useState(20);useEffect(()=>{const update=()=>setNow(new Date()),timer=setInterval(update,60000);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update)}},[]);
 const home=useQuery({queryKey:['/me/home'],queryFn:({signal})=>api.get<RecordData>('/me/home',signal)}),communities=rows(home.data?.communities),requests=communities.flatMap(c=>sources.map(([type,label,Icon])=>({c,type,label,Icon,path:'/communities/'+c.Id+'/'+type}))),results=useQueries({queries:requests.map(({path})=>({queryKey:[path],queryFn:({signal}:{signal:AbortSignal})=>api.get<RecordData[]>(path,signal),staleTime:30000}))});
 const activities=results.flatMap((q,i)=>rows(q.data).map(r=>({...requests[i],r}))).filter(({r,c})=>[r.Title,r.Question,r.Body,r.Description,c.Name].map(str).join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(Date.parse(str(b.r.CreatedAt))||0)-(Date.parse(str(a.r.CreatedAt))||0)||str(a.r.Id).localeCompare(str(b.r.Id))),loading=results.some(q=>q.isPending),failed=results.filter(q=>q.isError);
 return <Page title={greeting(now.getHours())+(session?.user.FirstName?', '+session.user.FirstName:'')} subtitle="Catch up on what’s happening in your communities."><div className="home-activities"><HeaderSearch label="Search activities"><input aria-label="Search recent activities" placeholder="Search activities and communities…" value={search} onChange={e=>{setSearch(e.target.value);setLimit(20)}}/></HeaderSearch><h2>Recent activities</h2><ErrorBox error={home.error}/>{home.isPending?<Loading/>:<>{failed.length>0&&<div role="alert" className="home-activity-error"><p>Some community activities could not be loaded. Available activities are shown below.</p><button onClick={()=>void Promise.all(results.filter(q=>q.isError).map(q=>q.refetch()))}>Retry</button></div>}{loading&&<Loading/>}{!loading&&!home.error&&!failed.length&&!activities.length&&<div className="empty"><p>{!communities.length?'Join a community to see its recent activities.':search?'No activities match your search.':'No community activities yet.'}</p>{!communities.length&&<Link className="button" to="/communities">Find communities</Link>}</div>}<div className="home-activity-list">{activities.slice(0,limit).map(({r,c,type,label,Icon})=><Link className="home-activity-card" key={str(c.Id)+type+str(r.Id)} to={activityLink(type,str(c.Id),str(r.Id))}><span className="home-activity-icon"><Icon size={21}/></span><div className="home-activity-copy"><div className="home-activity-meta"><span>{str(c.Name)}</span><span>{label}</span></div><h3>{str(r.Title||r.Question)||(type==='feed'?'Community post':label)}</h3>{!!(r.Body||r.Description)&&<p>{str(r.Body||r.Description)}</p>}{!!r.CreatedAt&&Number.isFinite(Date.parse(str(r.CreatedAt)))&&<time dateTime={str(r.CreatedAt)}>{new Date(str(r.CreatedAt)).toLocaleString(getLocale(),{dateStyle:'medium',timeStyle:'short'})}</time>}</div></Link>)}</div>{activities.length>limit&&<button className="home-activity-more" onClick={()=>setLimit(limit+20)}>Load more activities</button>}</>}</div></Page>
}

