import {useSession} from './auth';
import {useEffect,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Globe,Languages,MessageCircle,Download,RotateCcw,ChevronRight,ChevronDown,ArrowLeft} from 'lucide-react';
import {api,session,str,type RecordData} from './api';
import {Loading,ErrorBox,MutationForm,Field,Action} from './ui';
import {applyLanguage} from './i18n';
const languages=[['en-US','EN','English (US)','English'],['en-GB','EN','English (UK)','English'],['fr','FR','Français','French'],['es','ES','Español','Spanish'],['ar','ع','العربية','Arabic'],['ha','HA','Hausa','Hausa'],['yo','YO','Yorùbá','Yoruba'],['ig','IG','Igbo','Igbo'],['pt','PT','Português','Portuguese'],['de','DE','Deutsch','German']] as const;
const languageName=(value:unknown)=>languages.find(l=>l[0]===value)?.[2]||'English (UK)';
export function LanguageSync(){const user=useSession();const q=useQuery({queryKey:['/users/language-preferences'],queryFn:()=>api.get<RecordData>('/users/language-preferences'),enabled:!!user});useEffect(()=>{if(q.data)applyLanguage(str(q.data.AppLanguage))},[q.data?.AppLanguage]);return null}
export function LanguageSettings(){const field=useLocation().pathname.split('/')[3]||'',qc=useQueryClient(),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),[all,setAll]=useState(false);const q=useQuery({queryKey:['/users/language-preferences'],queryFn:()=>api.get<RecordData>('/users/language-preferences')});async function save(key:string,value:string|boolean){setBusy(true);setError(undefined);setNotice('');try{await api.send('/users/language-preferences',{key,value},'PATCH');if(key==='appLanguage')applyLanguage(String(value));await qc.invalidateQueries();setNotice('Language preference saved.')}catch(e){setError(e)}finally{setBusy(false)}}if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;const p=q.data;
 const link=(to:string,title:string,desc:string,Icon:typeof Globe,value?:string)=><Link className="settings-row" to={'/settings/language/'+to}><span className="settings-row-icon"><Icon size={21}/></span><span className="settings-row-text"><strong>{title}</strong><small>{desc}</small></span>{value&&<span className="privacy-value">{value}</span>}<ChevronRight size={17}/></Link>;
 const choices=(translation=false)=><div className="settings-list" role="radiogroup" aria-label={translation?'Translation language':'App language'}>{languages.slice(0,all||field?languages.length:6).map(([code,short,name,desc])=>{const available=translation||code.startsWith('en-');return <label className="settings-row language-choice" key={code}><span className="settings-row-icon">{short}</span><span className="settings-row-text"><strong lang={code}>{name}</strong><small>{available?desc:'Interface pack not available yet'}</small></span><input type="radio" name="language" checked={(translation?p.TranslationLanguage:p.AppLanguage)===code} disabled={busy||!available} onChange={()=>void save(translation?'translationLanguage':'appLanguage',code)}/></label>})}{!field&&<button className="language-all" onClick={()=>setAll(!all)}>{all?'Show fewer languages':'View all languages'}<ChevronDown size={17}/></button>}</div>;
 const feedback=<>{error!=null&&<ErrorBox error={error}/>}<p role="status" className="privacy-status">{busy?'Saving…':notice}</p></>;
 const toggle=(key:string,title:string,desc:string,checked:boolean,Icon:typeof Globe)=><label className="settings-row account-switch-row"><span className="settings-row-icon"><Icon size={21}/></span><span className="settings-row-text"><strong>{title}</strong><small>{desc}</small></span><input type="checkbox" role="switch" disabled={busy||(!p.translationAvailable&&!checked)} checked={checked} onChange={e=>void save(key,e.target.checked)}/></label>;
 if(field)return <div className="language-detail"><Link className="settings-back" to="/settings/language"><ArrowLeft size={17}/>Language</Link><h2>{field==='app'?'App Language':field==='translation'?'Translation Language':field==='packs'?'Included Language Packs':field==='suggest'?'Suggest Language':'Reset to Default'}</h2>{feedback}{field==='app'&&<><p>English regional choices change supported interface spellings and date/time formatting across the app. Other interface translations are not yet available.</p>{choices()}</>}{field==='translation'&&<><p>Choose the language to translate posts and messages into. Automatic translation requires a configured provider that supports your chosen language.</p>{choices(true)}</>}{field==='packs'&&<LanguagePacks/>}{field==='suggest'&&<MutationForm label="Send language suggestion" onSubmit={d=>api.send('/me/support-tickets',{category:'GENERAL',subject:'Language request: '+d.language,message:d.message||('Please support '+d.language)})}><Field name="language" label="Language name"/><Field name="message" label="Details" type="textarea" required={false}/></MutationForm>}{field==='reset'&&<><p>Return to English (UK) and turn off automatic post and message translation. Both English interface packs remain available.</p><Action run={async()=>{await api.send('/users/language-preferences/reset');applyLanguage('en-GB');setNotice('Language settings reset.')}}>Reset language settings</Action></>}</div>;
 return <div className="privacy-dashboard language-dashboard">{feedback}<div className="settings-list">{link('app','App Language','Interface language and regional formatting',Globe,languageName(p.AppLanguage))}</div><section className="settings-group"><h2>Suggested Languages</h2>{choices()}</section><section className="settings-group"><h2>Translation Settings</h2><div className="settings-list">{toggle('translatePosts','Translate Posts','Automatically translate posts into your selected language',!!p.TranslatePosts,Languages)}{toggle('translateMessages','Translate Messages','Automatically translate incoming message text',!!p.TranslateMessages,MessageCircle)}{link('translation','Translation Language','Language to translate content into',Globe,languageName(p.TranslationLanguage))}</div>{!p.translationAvailable&&<p className="privacy-note">No translation provider is configured. Automatic translation is unavailable until the server is connected to one.</p>}</section><section className="settings-group"><h2>Other Options</h2><div className="settings-list">{link('packs','Included Language Packs','English packs included with the app',Download)}{link('reset','Reset to Default','Reset your saved language settings',RotateCcw)}</div></section><section className="privacy-safety"><Globe size={36}/><div><strong>Help make CDA Connect better</strong><p>Can’t find your language? Let us know.</p></div><Link className="button secondary" to="/settings/language/suggest">Suggest Language</Link></section></div>;
}
function LanguagePacks(){return <><p>English (UK) and English (US) are included with CDA Connect and update with the app. No separate download is needed.</p>{['en-GB','en-US'].map(code=><section className="card" key={code}><h3>{languageName(code)}</h3><span className="badge">Included with the app</span></section>)}<Link className="button primary" to="/settings/language/app">Choose app language</Link><p className="privacy-note">These packs provide supported interface wording and regional formatting. They do not translate posts or messages or make private content available offline.</p></>}
