import {OfficialGuidance} from './OfficialGuidance';
import {Link} from 'react-router-dom';
const privacy=[
 ['About this statement','This statement describes how the CDA Connect application handles information when you create an account, join communities and use its features. Privacy enquiries can be sent to support@cdaconnect.org. The operator’s legal identity, address and detailed processing arrangements must be confirmed before this draft is adopted as a final privacy notice.'],
 ['Information you provide','Account information includes your name, username, email address, phone number, date of birth, location and profile images where supplied. Community information includes memberships, posts, comments, messages, uploaded media, event responses, votes, reports, support requests and financial records associated with features you use.'],
 ['How information is used','The app uses information to create and authenticate accounts, verify contact details, manage community access, deliver messages and updates, record participation, apply your preferences and handle support or safety reports. Security and session information helps manage sign-ins and access. Optional features use the information needed for the feature you enable.'],
 ['Visibility and sharing','Community members can see content available to them under membership and privacy controls. Administrators may access member information needed for community administration, including contact details. Service providers supporting hosting, storage, email, SMS or push delivery may process relevant information to deliver those features. Enabling a connected translation or AI feature may send the submitted content to its configured provider. Do not share information you do not have permission to disclose.'],
 ['Your choices and device permissions','Profile → Account settings lets you review personal details and account preferences. Privacy & safety controls profile visibility and contact sharing. Notifications and Communications control available delivery and messaging preferences. Device permissions are requested for features such as notifications or contact selection. Withdrawing a permission may stop the related feature. Necessary account and security processing is separate from optional preferences.'],
 ['Local storage and security','The app stores session and preference information needed to operate, and may cache public app resources on your device. Authentication, access checks and privacy controls restrict application access; no online service can guarantee absolute security. Protect your device and do not share passwords, verification codes or account access.'],
 ['Retention and deleting an account','Records remain while needed to operate the account and community features. Account deletion clears personal profile fields and message text, marks authored posts and comments as deleted, and removes or disables membership and participation records as described on the deletion page. Some community records remain associated with a deleted-member record. Stored uploads, backups and copies held by other people are not automatically erased by that action. A complete retention schedule, including backup and upload disposal, must be confirmed by the operator.'],
 ['Your rights and questions','Depending on the law that applies, you may have rights to access, correct, erase or obtain a copy of your information, restrict or object to processing, and withdraw consent where processing relies on consent. Account settings provides editing and data-export tools. Send other requests or privacy concerns to support@cdaconnect.org. You may also complain to the relevant data protection regulator, including the UK Information Commissioner’s Office or the Nigeria Data Protection Commission where applicable.'],
 ['Information still to be confirmed','Before final publication, the operator must confirm its legal identity and address, the lawful basis for each processing purpose, provider and international-transfer arrangements, retention periods or criteria, and any applicable child-user rules. This draft does not claim government approval or certification.']
];
const terms=[
 ['Using CDA Connect','CDA Connect provides tools for community communication, participation and administration. These draft terms explain the proposed rules for using those tools. The operator’s legal identity and contact address must be added before these terms are finalised. Contact: support@cdaconnect.org.'],
 ['Your account','Provide accurate information, keep your sign-in details secure and use only accounts you are authorised to access. Do not impersonate another person or share verification codes. Report suspected unauthorised access promptly. Some features require verified contact details or additional security checks.'],
 ['Community membership','Access depends on membership, approval requirements and assigned permissions. Community administrators manage requests, roles and community rules. An invitation does not override a private community’s approval requirements. Follow the rules of each community as well as applicable law.'],
 ['Content and acceptable use','Share only content you have the right to share. Do not use the service for harassment, threats, fraud, unlawful discrimination, exploitation, spam or unauthorised disclosure of personal information. Do not try to bypass access controls or disrupt the service. You retain your rights in your content; the service needs permission to store, process and display it for the features and audiences you choose.'],
 ['Moderation and safety','Content and access may be restricted to address rule violations, security concerns or legal requirements. Relevant circumstances should be considered and concerns can be raised through support. Community emergency features are communication tools, not a replacement for local emergency services.'],
 ['Events, listings and payments','Community organisers and members are responsible for the accuracy of their events, listings and shared information. Check arrangements, prices and payment instructions before committing. A community listing does not by itself mean CDA Connect endorses the provider. Any paid service needs clear pricing and applicable payment, cancellation and refund terms before purchase. These terms do not introduce a subscription or fee.'],
 ['Availability and your legal rights','Features may be affected by maintenance, connectivity, device support or service-provider availability. Nothing in these terms removes mandatory consumer or data-protection rights, or excludes liability that cannot lawfully be excluded. No guarantee is made that community content is accurate or that the service will always be uninterrupted.'],
 ['Leaving the service','You can use the account-management tools to deactivate or delete your account. Read the deletion screen and Privacy Policy for the effects and limits of deletion. Community records and copies held by others may remain as described there.'],
 ['Changes and resolving concerns','Material changes to final terms should be communicated clearly before they take effect where required. Contact support@cdaconnect.org with concerns about the service or these terms. Final operator details and any applicable dispute provisions remain to be confirmed; this draft does not restrict rights to complain to regulators or use courts available under applicable law.']
];
export function LegalStatement({kind}:{kind:'privacy'|'terms'}){const items=kind==='privacy'?privacy:terms;return <article className="legal-statement"><OfficialGuidance terms={kind==='terms'}/><div className="legal-intro"><span className="badge">Draft for operator review</span><p>{kind==='privacy'?'How CDA Connect handles your information and the choices available to you.':'Rules for using CDA Connect and participating in its communities.'}</p><small>Prepared 10 September 2026</small></div><nav className="legal-contents" aria-label="On this page">{items.map(([title],i)=><a key={title} href={'#'+kind+'-'+i}>{i+1}. {title}</a>)}</nav>{items.map(([title,body],i)=><section id={kind+'-'+i} key={title}><h3>{i+1}. {title}</h3><p>{body}</p></section>)}{kind==='privacy'&&<Link className="button secondary" to="/settings/privacy">Manage privacy preferences</Link>}</article>}
