import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api} from './api';
export function LocationFields({country='',state='',lga='',required=false,onChange}:{country?:string;state?:string;lga?:string;required?:boolean;onChange?:(area:string)=>void}){
 const[c,setC]=useState(country),[s,setS]=useState(state),[a,setA]=useState(lga);
 const countries=useQuery({queryKey:['community-countries'],queryFn:()=>api.get<{id:string;name:string}[]>('/communities/locations'),staleTime:86400000});
 const code=countries.data?.find(x=>x.name===c||x.id===c)?.id;
 const states=useQuery({queryKey:['community-states',code],queryFn:()=>api.get<{id:string;name:string}[]>('/communities/locations?country='+code),enabled:!!code,staleTime:86400000});
 const sid=states.data?.find(x=>x.name===s||x.id===s)?.id;
 const areas=useQuery({queryKey:['community-areas',code,sid],queryFn:()=>api.get<string[]>('/communities/locations?country='+code+'&state='+sid),enabled:!!code&&!!sid,staleTime:86400000});
 const error=countries.error||states.error||areas.error;
 return <div className="location-selectors"><input type="hidden" name="state" value={s||(required&&states.data?.length===0?c:'')}/><input type="hidden" name="lga" value={a}/><label>Country<select aria-label="Country" required={required} name="country" value={c} onChange={e=>{setC(e.target.value);setS('');setA('');onChange?.(e.target.value)}}><option value="">{countries.isPending?'Loading countries…':'Select country'}</option>{c&&!countries.data?.some(x=>x.name===c)&&<option value={c}>{c} (saved)</option>}{countries.data?.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></label><label>State / Region<select aria-label="State / Region" required={required&&!!states.data?.length} value={s} disabled={!code||states.isPending} onChange={e=>{setS(e.target.value);setA('');onChange?.(e.target.value||c)}}><option value="">{!code?'Select country first':states.isPending?'Loading regions…':states.data?.length?'Select state / region':'No regions available'}</option>{s&&!states.data?.some(x=>x.name===s)&&<option value={s}>{s} (saved)</option>}{states.data?.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></label><label>LGA / Local area<select aria-label="LGA / Local area" value={a} disabled={!sid||areas.isPending} onChange={e=>{setA(e.target.value);onChange?.(e.target.value||s||c)}}><option value="">{!sid?'Select region first':areas.isPending?'Loading local areas…':areas.data?.length?'Select LGA / local area':'No local areas available'}</option>{a&&!areas.data?.includes(a)&&<option value={a}>{a} (saved)</option>}{areas.data?.map(x=><option key={x} value={x}>{x}</option>)}</select></label>{error&&<div role="alert">Location choices could not load. <button type="button" onClick={()=>{void countries.refetch();if(code)void states.refetch();if(sid)void areas.refetch()}}>Retry</button></div>}</div>
}
