import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,CalendarDays,Clock,MapPin,Users,FileText,Folder,ChevronDown,ChevronRight,Download,CheckCircle2,HelpCircle,XCircle,Video} from 'lucide-react';
import {api,str,rows,type RecordData} from './api';
import {ErrorBox,Loading} from './ui';
import {MeetingParticipation} from './MeetingParticipation';
import {getLocale} from './i18n';
function MeetingDocument({document:d}:{document:RecordData}){const[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();return <article className="meeting-document"><FileText/><div><strong>{str(d.title)}</strong><small>Meeting document</small>{url&&<a href={url} target="_blank" rel="noreferrer">Open download · valid for 5 minutes</a>}<ErrorBox error={error}/></div><button disabled={busy} aria-label={'Download '+str(d.title)} title="Prepare secure download" onClick={async()=>{setBusy(true);try{const r=await api.send<{url:string}>('/documents/'+str(d.id)+'/download-url');if(new URL(r.url).protocol!=='https:')throw Error('A secure download URL is required.');setUrl(r.url)}catch(e){setError(e)}finally{setBusy(false)}}}><Download size={20}/></button></article>}
export function MeetingDetails({id,communityId,close}:{id:string;communityId:string;close:()=>void}){
 const qc=useQueryClient(),q=useQuery({queryKey:['/meetings/'+id],queryFn:({signal})=>api.get<RecordData>('/meetings/'+id,signal)}),community=useQuery({queryKey:['/communities/'+communityId],queryFn:()=>api.get<RecordData>('/communities/'+communityId)});
 const[error,setError]=useState<unknown>(),[message,setMessage]=useState(''),[about,setAbout]=useState(false),[fullAgenda,setFullAgenda]=useState(false),[attendeesOpen,setAttendeesOpen]=useState(false),[documentsOpen,setDocumentsOpen]=useState(false),[busy,setBusy]=useState(false),[contributions,setContributions]=useState(false);
 const m=q.data;if(q.isPending)return <Loading/>;if(q.error||!m)return <div className="published-meeting"><button onClick={close}>Back to meetings</button><ErrorBox error={q.error}/></div>;
 const settings=(m.settings as RecordData)||{},start=new Date(str(m.StartDateTime)),end=new Date(str(m.EndDateTime)),ended=end.getTime()<Date.now(),status=ended?'Past':start.getTime()<=Date.now()?'In progress':'Upcoming',timeZone=str(settings.timeZone)||undefined,time=(date:Date)=>date.toLocaleTimeString(getLocale(),{hour:'2-digit',minute:'2-digit',timeZone}),agenda=rows(m.agenda),attendees=rows(m.attendees),documents=rows(settings.documents),description=str(m.Description),going=Number(m.GoingCount||0),restricted=settings.attendance==='ORGANISERS',communityName=str(m.CommunityName)||str(community.data?.Name),logo=str(community.data?.LogoUrl),host=str(settings.organizer)||str(m.HostedBy)||'Community organiser';
 async function rsvp(response:string){if(busy)return;setBusy(true);setError(undefined);try{await api.send('/meetings/'+id+'/rsvp',{response});await qc.invalidateQueries({queryKey:['/meetings/'+id]});await qc.invalidateQueries({queryKey:['/communities/'+communityId+'/meetings']});setMessage('Your response has been saved.')}catch(e){setError(e)}finally{setBusy(false)}}
 return <div className="published-meeting"><ErrorBox error={error}/>{message&&<p role="status" className="meeting-feedback">{message}</p>}
 <section className="published-hero"><div><span className="meeting-status"><CalendarDays size={15}/>{status}</span><h2>{str(m.Title)}</h2><p>Your voice. Your community.</p></div><div className="meeting-emblem">{logo?<img src={api.asset(logo)} alt={communityName} onError={e=>{e.currentTarget.style.display='none'}}/>:<Users size={48}/>}<strong>{communityName}</strong></div></section>
 <section className="meeting-facts" aria-label="Meeting information"><div><CalendarDays/><span>Date</span><strong>{start.toLocaleDateString(getLocale(),{weekday:'short',day:'numeric',month:'short',year:'numeric',timeZone})}</strong><small>{status}</small></div><div><Clock/><span>Time</span><strong>{time(start)} – {time(end)}</strong><small>{Math.round((end.getTime()-start.getTime())/60000)} minutes{timeZone?' · '+timeZone:''}</small></div><div><MapPin/><span>Location</span><strong>{str(m.Location)||'Online meeting'}</strong>{/^https:\/\//i.test(str(m.OnlineMeetingUrl))&&<a href={str(m.OnlineMeetingUrl)} target="_blank" rel="noreferrer"><Video size={14}/>Join online</a>}</div><div><Users/><span>Hosted By</span><strong>{host}</strong><small>{restricted?'Organisers only':'Community members'}</small></div></section>
 <section className="meeting-section"><h2>About the Meeting</h2><p className="meeting-description">{description?(about||description.length<=240?description:description.slice(0,240)+'…'):'No description has been added.'}</p>{description.length>240&&<button className="section-link" aria-expanded={about} onClick={()=>setAbout(!about)}>{about?'See less':'See more'}<ChevronDown size={17}/></button>}</section>
 <section className="meeting-section"><header><h2><FileText/>Agenda</h2>{agenda.length>0&&<button className="section-link" aria-expanded={fullAgenda} onClick={()=>setFullAgenda(!fullAgenda)}>{fullAgenda?'Show summary':'View Full Agenda'}<ChevronRight size={17}/></button>}</header>{agenda.length?<ol className="published-agenda">{(fullAgenda?agenda:agenda.slice(0,6)).map((a,i)=>{const offset=agenda.slice(0,i).reduce((n,x)=>n+Number(x.DurationMinutes||0),0);return <li key={str(a.Id)}><b>{i+1}</b><div><strong>{str(a.Title)}</strong>{fullAgenda&&<><p>{str(a.Description)||'No additional details.'}</p>{!!a.DurationMinutes&&<small>{Number(a.DurationMinutes)} minutes</small>}</>}</div><time>{i===0||agenda.slice(0,i).every(x=>Number(x.DurationMinutes)>0)?time(new Date(start.getTime()+offset*60000)):'—'}</time></li>})}</ol>:<p>No agenda has been added.</p>}</section>
 <section className="meeting-section"><header><h2><Users/>Who’s Attending</h2><strong className="going-count">{going} Going</strong></header><div className="attending-preview"><div className="meeting-avatar-row">{attendees.slice(0,5).map(a=><span className="meeting-avatar" key={str(a.UserId)} title={str(a.FirstName)+' '+str(a.LastName)}>{a.ProfileImage?<img src={api.asset(str(a.ProfileImage))} alt={str(a.FirstName)} onError={e=>{e.currentTarget.style.display='none'}}/>:str(a.FirstName).slice(0,1)+str(a.LastName).slice(0,1)}</span>)}{going>5&&<span className="meeting-avatar">+{going-5}</span>}{going===0&&<p>No confirmed attendees yet.</p>}</div>{attendees.length>0&&<button aria-expanded={attendeesOpen} onClick={()=>setAttendeesOpen(!attendeesOpen)}>{attendeesOpen?'Hide attendees':'See Attendees'}</button>}</div>{attendeesOpen&&<><ul className="published-attendees">{attendees.map(a=><li key={str(a.UserId)}>{str(a.FirstName)} {str(a.LastName)}</li>)}</ul>{going>attendees.length&&<p>Showing the first {attendees.length} confirmed attendees.</p>}</>}</section>
 <section className="meeting-section"><header><h2><Folder/>Meeting Documents</h2>{documents.length>2&&<button className="section-link" aria-expanded={documentsOpen} onClick={()=>setDocumentsOpen(!documentsOpen)}>{documentsOpen?'Show fewer':'View All'}<ChevronRight size={17}/></button>}</header>{documents.length?<div className="meeting-document-grid">{(documentsOpen?documents:documents.slice(0,2)).map(d=><MeetingDocument key={str(d.id)} document={d}/>)}</div>:<p>No documents have been attached.</p>}</section>
 {!ended&&!!m.AllowRegistration?<section className="published-rsvp" aria-label="Your meeting response">{([['GOING','I’m Attending',CheckCircle2],['MAYBE','Maybe',HelpCircle],['NOT_GOING','Can’t Attend',XCircle]] as const).map(([response,label,Icon])=><button key={response} className={m.MyResponse===response?'selected':''} aria-pressed={m.MyResponse===response} disabled={busy} onClick={()=>void rsvp(response)}><Icon size={19}/>{label}</button>)}</section>:<p className="meeting-feedback">{ended?'RSVPs are closed for this meeting.':'Registration is disabled for this meeting.'}</p>}
 {(!!settings.allowQuestions||!!settings.allowNotes||!!settings.enableVoting)&&<section className="meeting-section"><button className="section-link" aria-expanded={contributions} onClick={()=>setContributions(!contributions)}>{contributions?'Hide':'Open'} questions, notes & votes<ChevronDown size={18}/></button>{contributions&&<MeetingParticipation id={id} settings={{...settings,documents:[]}}/>}</section>}</div>
}
