import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useInfiniteQuery} from '@tanstack/react-query';
import {Activity,Users,SquarePen,MessageCircle,Heart,CalendarDays,RefreshCw} from 'lucide-react';
import {api,str,type RecordData} from './api';
import {Loading,ErrorBox} from './ui';
import {getLocale} from './i18n';
import './member-activity.css';
type Result={stats:RecordData;items:RecordData[];nextCursor:string|null};
const kinds=[['ALL','All activity'],['POST','Posts'],['COMMENT','Comments'],['REACTION','Reactions'],['GROUP','Groups'],['MEETING','Meetings'],['EVENT','Events']];
const labels:Record<string,string>={POST:'You created a post',COMMENT:'You commented on a post',REACTION:'You reacted to a post',GROUP:'You joined a community',MEETING:'You attended a meeting',EVENT:'You attended an event'};
const icons:Record<string,typeof Activity>={POST:SquarePen,COMMENT:MessageCircle,REACTION:Heart,GROUP:Users,MEETING:CalendarDays,EVENT:CalendarDays};
function target(r:RecordData){const base='/community/'+r.CommunityId;return ['POST','COMMENT','REACTION'].includes(str(r.Kind))?'/post/'+r.TargetId+(r.Kind==='COMMENT'?'#comments':''):r.Kind==='GROUP'?base+'/feed':r.Kind==='MEETING'?base+'/meetings?meeting='+r.TargetId:base+'/events?event='+r.TargetId}
function group(value:unknown){const d=new Date(str(value)),now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),week=new Date(today);if(!value||!Number.isFinite(d.getTime()))return 'Date unavailable';week.setDate(week.getDate()-((week.getDay()+6)%7));if(d>=today)return 'Today';if(d>=week)return 'This week';if(d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear())return 'Earlier this month';return d.toLocaleDateString(getLocale(),{month:'long',year:'numeric'})}
export function MemberActivity(){const [kind,setKind]=useState('ALL'),q=useInfiniteQuery({queryKey:['personal-activity',kind],initialPageParam:'',queryFn:({pageParam,signal})=>api.get<Result>('/me/personal-activity?kind='+kind+'&cursor='+encodeURIComponent(pageParam),signal),getNextPageParam:last=>last.nextCursor??undefined});const items=q.data?.pages.flatMap(p=>p.items)||[],groups=new Map<string,RecordData[]>();items.forEach(r=>{const key=group(r.CreatedAt);groups.set(key,[...(groups.get(key)||[]),r])});return <div className="member-activity"><div className="member-activity-content"><div className="activity-filter"><select aria-label="Activity type" value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>{Number(q.data?.pages[0]?.stats.Undated||0)>0&&<p role="status">{Number(q.data?.pages[0]?.stats.Undated)} activities have no recorded date and cannot be placed in the timeline.</p>}<ErrorBox error={q.error}/>{q.isPending?<Loading/>:!items.length&&!q.error?<p className="empty">No {kind==='ALL'?'activity':kinds.find(k=>k[0]===kind)?.[1].toLowerCase()} recorded yet.</p>:Array.from(groups,([heading,entries])=><section className="activity-period" key={heading}><h2>{heading}</h2><div className="activity-timeline">{entries.map(r=>{const Icon=icons[str(r.Kind)]||Activity;return <article key={str(r.Kind)+str(r.Id)}><span className={'activity-marker kind-'+str(r.Kind).toLowerCase()}><Icon size={21}/></span><Link className="activity-entry" to={target(r)}><span className="activity-entry-heading"><strong>{r.Kind==='POST'&&r.PostType==='PHOTO'?'You shared a photo':labels[str(r.Kind)]}</strong><time dateTime={Number.isFinite(Date.parse(str(r.CreatedAt)))?str(r.CreatedAt):undefined}>{!r.CreatedAt||!Number.isFinite(Date.parse(str(r.CreatedAt)))?'Date unavailable':new Date(str(r.CreatedAt)).toLocaleString(getLocale(),heading==='Today'?{hour:'2-digit',minute:'2-digit'}:{day:'numeric',month:'short',year:'numeric'})}</time></span>{!!r.Body&&<p>{str(r.Body)}</p>}<small>in <b>{str(r.CommunityName)}</b></small></Link></article>})}</div></section>)}{q.hasNextPage&&!q.isFetchNextPageError&&<button className="activity-load" disabled={q.isFetchingNextPage} onClick={()=>void q.fetchNextPage()}><RefreshCw size={17}/>{q.isFetchingNextPage?'Loading…':'Load more activity'}</button>}{q.isFetchNextPageError?<div role="alert"><p>Could not load more activity. Your loaded activity is still available.</p><button onClick={()=>void q.fetchNextPage()}>Retry loading more</button></div>:q.error&&<button onClick={()=>void q.refetch()}>Retry</button>}</div></div>}
