import {useEffect,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {createPortal} from 'react-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Reply,Forward,Copy,NotebookPen,Star,Trash2,Flag,X} from 'lucide-react';
import {api,str,type RecordData} from './api';
import {ErrorBox} from './ui';
export function useMessagePress(open:(message:RecordData)=>void){
 const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),start=useRef<{x:number;y:number}|undefined>(undefined);
 function cancel(){clearTimeout(timer.current);timer.current=undefined;start.current=undefined}
 useEffect(()=>cancel,[]);
 return (message:RecordData)=>({onPointerDown:(event:ReactPointerEvent)=>{if(event.button!==0||event.isPrimary===false)return;cancel();start.current={x:event.clientX,y:event.clientY};timer.current=setTimeout(()=>{start.current=undefined;open(message)},2000)},onPointerMove:(event:ReactPointerEvent)=>{if(start.current&&Math.hypot(event.clientX-start.current.x,event.clientY-start.current.y)>10)cancel()},onPointerUp:cancel,onPointerCancel:cancel,onPointerLeave:cancel,onContextMenu:(event:React.MouseEvent)=>{event.preventDefault();cancel();open(message)}});
}
const emojis=['👍','❤️','😂','😮','😢','🙏','🎉','👎','🔥','✅'];
export function MessageActions({message,conversationId,communityId,mine,onClose,onReply}:{message:RecordData;conversationId:string;communityId:string;mine:boolean;onClose:()=>void;onReply:(m:RecordData)=>void}){
 const qc=useQueryClient(),dialog=useRef<HTMLDialogElement>(null),[panel,setPanel]=useState('menu'),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[status,setStatus]=useState(''),[note,setNote]=useState(str(message.Note)),[reason,setReason]=useState('Spam'),[details,setDetails]=useState(''),[target,setTarget]=useState(''),[moreEmoji,setMoreEmoji]=useState(false),forwardKey=useRef(crypto.randomUUID());
 const path='/conversations/'+conversationId+'/messages/'+str(message.Id),chats=useQuery({queryKey:['/communities/'+communityId+'/conversations'],queryFn:()=>api.get<RecordData[]>('/communities/'+communityId+'/conversations'),enabled:panel==='forward'&&!!communityId});
 useEffect(()=>{const el=dialog.current;el?.showModal();return()=>el?.close()},[]);
 async function run(action:()=>Promise<unknown>,close=true){if(busy)return;setBusy(true);setError(undefined);try{await action();await qc.invalidateQueries({queryKey:['/conversations/'+conversationId+'/messages']});await qc.invalidateQueries({queryKey:['/communities/'+communityId+'/conversations']});if(close)onClose()}catch(e){setError(e)}finally{setBusy(false)}}
 return createPortal(<dialog ref={dialog} className="message-actions-dialog" aria-label="Message actions" onCancel={e=>{e.preventDefault();if(!busy)onClose()}} onClick={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><div className="message-actions-content"><header><strong>{panel==='menu'?'Message options':panel==='forward'?'Forward message':panel==='note'?'Private note':panel==='report'?'Report message':'Delete message'}</strong><button aria-label="Close message options" disabled={busy} onClick={onClose}><X size={20}/></button></header><blockquote>{str(message.MessageText)||'Attachment'}</blockquote><ErrorBox error={error}/>{status&&<p role="status">{status}</p>}
 {panel==='menu'?<><div className="message-reactions" aria-label="React to message">{emojis.slice(0,moreEmoji?emojis.length:7).map(emoji=><button key={emoji} aria-label={'React '+emoji} aria-pressed={message.MyReaction===emoji} disabled={busy} onClick={()=>void run(()=>api.send(path+'/reaction',{emoji:message.MyReaction===emoji?null:emoji},'PUT'))}>{emoji}</button>)}<button aria-label="More reactions" onClick={()=>setMoreEmoji(!moreEmoji)}>+</button></div><nav aria-label="Message options"><button onClick={()=>{onReply(message);onClose()}}><Reply size={19}/>Reply</button><button onClick={()=>setPanel('forward')}><Forward size={19}/>Forward</button>{!!message.MessageText&&<button onClick={()=>void run(async()=>{await navigator.clipboard.writeText(str(message.MessageText));setStatus('Message copied')},false)}><Copy size={19}/>Copy</button>}{!!message.MessageText&&<button onClick={()=>setPanel('note')}><NotebookPen size={19}/>Add text to note</button>}<button disabled={busy} onClick={()=>void run(()=>api.send(path+'/preferences',{starred:!message.IsStarred},'PUT'))}><Star size={19}/>{message.IsStarred?'Unstar':'Star'}</button><button className="message-danger" onClick={()=>setPanel('delete')}><Trash2 size={19}/>Delete</button><button onClick={()=>setPanel('report')}><Flag size={19}/>Report</button></nav></>:
 panel==='forward'?<form onSubmit={e=>{e.preventDefault();void run(()=>api.send(path+'/forward',{targetConversationId:target,requestKey:forwardKey.current}))}}><label>Conversation<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose a conversation</option>{(chats.data||[]).filter(c=>str(c.Id).toLowerCase()!==conversationId.toLowerCase()).map(c=><option key={str(c.Id)} value={str(c.Id)}>{str(c.Type==='DIRECT'?c.DirectName||c.Name:c.Name)}</option>)}</select></label><p>Forward to another conversation in this community.</p><ErrorBox error={chats.error}/><button className="primary" disabled={busy||!target||chats.isPending}>Forward</button></form>:
 panel==='note'?<form onSubmit={e=>{e.preventDefault();void run(()=>api.send(path+'/preferences',{note},'PUT'))}}><p>This note is visible only to you. Find it in Saved messages.</p><label>Note<textarea maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder={str(message.MessageText)} /></label><button type="button" onClick={()=>setNote(str(message.MessageText).slice(0,2000))}>Use message text</button><button className="primary" disabled={busy}>Save note</button></form>:
 panel==='report'?<form onSubmit={e=>{e.preventDefault();void run(()=>api.send(path+'/report',{reason,details}).then(()=>{setStatus('Report sent to the safety support team');setPanel('menu')}),false)}}><p>The safety support team receives the reported message and your explanation.</p><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}>{['Spam','Harassment','Threats','Scam','Inappropriate content','Other'].map(r=><option key={r}>{r}</option>)}</select></label><label>Details (optional)<textarea maxLength={1500} value={details} onChange={e=>setDetails(e.target.value)}/></label><button className="primary" disabled={busy}>Send report</button></form>:
 <div><p>Delete for me hides this message from your view.</p><button disabled={busy} onClick={()=>void run(()=>api.send(path+'/preferences',{hidden:true},'PUT'))}>Delete for me</button>{mine&&<><p>Delete for everyone removes your message from the conversation.</p><button className="message-danger" disabled={busy} onClick={()=>void run(()=>api.send(path,{},'DELETE'))}>Delete for everyone</button></>}</div>}
 {panel!=='menu'&&<button disabled={busy} onClick={()=>setPanel('menu')}>Back to options</button>}</div></dialog>,document.body);
}
export function MessageReactions({message}:{message:RecordData}){let reactions:{Emoji:string;Count:number}[]=[];try{reactions=JSON.parse(str(message.Reactions)||'[]')}catch{}return <>{!!message.IsStarred&&<span className="message-star" aria-label="Starred message">★</span>}{reactions.length>0&&<div className="message-reaction-counts">{reactions.map(r=><span key={r.Emoji}>{r.Emoji} {r.Count}</span>)}</div>}</>}
