import {useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Bell,Mail,MessageCircle,Megaphone,FilePenLine,AtSign,CalendarDays,Users,ChartNoAxesColumn,TriangleAlert,Moon,ChevronRight,ArrowLeft,Smartphone,ShieldCheck} from 'lucide-react';
import {api,str,type RecordData} from './api';
import {Loading,ErrorBox,MutationForm,Field} from './ui';
import {PushSettings} from './push';
const fields=[['communityUpdates','CommunityUpdates','Community Updates','News, announcements and important updates',Megaphone],['newPosts','CommunityPosts','New Posts','New posts in your communities',FilePenLine],['comments','Comments','Comments','Comments on your posts and replies',MessageCircle],['mentions','Mentions','Mentions','When someone mentions you in a post or comment',AtSign],['events','Events','Event Reminders','Reminders and updates about events',CalendarDays],['invitations','Invitations','Invitations','When you are added to a community group',Users],['polls','Polls','Polls & Surveys','New community polls and surveys',ChartNoAxesColumn],['emergency','EmergencyEnabled','Emergency Alerts','Important alerts and safety notifications',TriangleAlert]] as const;
const isOn=(v:unknown,defaultValue=true)=>v==null?defaultValue:v!==false&&v!==0&&v!=='OFF';
export function NotificationSettings(){
 const field=useLocation().pathname.split('/')[3]||'',qc=useQueryClient(),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState('');
 const q=useQuery({queryKey:['/users/notification-settings'],queryFn:({signal})=>api.get<RecordData>('/users/notification-settings',signal)}),c=useQuery({queryKey:['/users/communications'],queryFn:({signal})=>api.get<RecordData>('/users/communications',signal)});
 async function save(key:string,value:boolean,communication=false){setBusy(true);setError(undefined);setNotice('');try{await api.send(communication?'/users/communications':'/users/notification-settings',{key,value},'PATCH');await qc.invalidateQueries();setNotice('Notification preference saved.')}catch(e){setError(e)}finally{setBusy(false)}}
 if(q.isPending||c.isPending)return <Loading/>;if(q.error||c.error)return <ErrorBox error={q.error||c.error}/>;
 const p=q.data!,comm=c.data!,enabled=isOn(p.Enabled),start=str(p.QuietStart)||'22:00',end=str(p.QuietEnd)||'07:00';
 const toggle=(key:string,title:string,description:string,checked:boolean,Icon:typeof Bell,communication=false)=><label className="settings-row account-switch-row"><span className="settings-row-icon"><Icon size={21}/></span><span className="settings-row-text"><strong>{title}</strong><small>{description}</small></span><input type="checkbox" role="switch" checked={checked} disabled={busy} onChange={e=>void save(key,e.target.checked,communication)}/></label>;
 const link=(to:string,title:string,description:string,Icon:typeof Bell,value?:string)=><Link className="settings-row" to={'/settings/notifications/'+to}><span className="settings-row-icon"><Icon size={21}/></span><span className="settings-row-text"><strong>{title}</strong><small>{description}</small></span>{value&&<span className="privacy-value">{value}</span>}<ChevronRight size={17}/></Link>;
 const feedback=<>{error!=null&&<ErrorBox error={error}/>}<p className="privacy-status" role="status" aria-live="polite">{busy?'Saving…':notice}</p></>;
 if(field)return <div className="notifications-detail"><Link className="settings-back" to="/settings/notifications"><ArrowLeft size={17}/>Notifications</Link><h2>{field==='messages'?'Messages':field==='quiet-hours'?'Quiet Hours':'Notifications'}</h2>{feedback}
 {field==='messages'?<><div className="settings-list">{toggle('messages','Message Notifications','Notify me about new messages and chat activity',isOn(p.DirectMessages),MessageCircle)}{toggle('messagePreviews','Message Previews','Show message text in supported notifications',!!comm.MessagePreviews,Smartphone,true)}</div><Link className="button secondary" to="/settings/communications/messages">Manage in-app messaging</Link><p className="privacy-note">Turning off notifications does not prevent people from sending messages.</p></>:field==='quiet-hours'?<><p>Pause non-essential delivery during these hours. Emergency alerts you have enabled can still arrive.</p><MutationForm key={String(p.QuietHoursEnabled)+start+end+str(p.TimeZone)} label="Save quiet hours" onSubmit={d=>api.send('/users/notification-settings/quiet-hours',{enabled:d.enabled==='yes',start:d.start,end:d.end,timeZone:d.timeZone},'PUT')}><label>Quiet hours<select name="enabled" defaultValue={p.QuietHoursEnabled?'yes':'no'}><option value="no">Off</option><option value="yes">On</option></select></label><div className="form-grid"><Field name="start" label="Start time" type="time" defaultValue={start}/><Field name="end" label="End time" type="time" defaultValue={end}/></div><Field name="timeZone" label="Time zone" defaultValue={str(p.TimeZone)||Intl.DateTimeFormat().resolvedOptions().timeZone}/></MutationForm><p className="privacy-note">Your inbox keeps new updates. Email and SMS alerts during quiet hours are silenced; push queued before quiet hours ends may arrive afterwards. Verification and account-security messages are unaffected.</p><Link className="button secondary" to="/settings/communications/dnd">Manage Do Not Disturb</Link></>:<Link to="/settings/notifications">Back to notification settings</Link>}</div>;
 return <div className="privacy-dashboard notifications-dashboard"><section className="notification-hero"><span className="notification-hero-bell"><Bell size={37}/></span><div><h2>Stay updated, your way</h2><p>Manage your notification preferences and never miss what matters.</p></div><ShieldCheck className="notification-hero-check" size={44}/></section>{feedback}
 <section className="settings-group"><h2>Notification Status</h2><div className="settings-list">{toggle('enabled','Enable Notifications','Receive notifications across the app',enabled,Bell)}</div>{!enabled&&<p className="privacy-note">Notifications are paused, including emergency delivery. Your choices below are retained. Verification and account-security messages still arrive.</p>}</section>
 <section className="settings-group"><h2>How You Receive Notifications</h2><div className="settings-list"><PushSettings compact/>{toggle('emailUpdates','Email Notifications','Receive notifications via email',!!comm.EmailUpdates,Mail,true)}{toggle('smsUpdates','SMS Notifications','Receive important alerts via SMS',!!comm.SmsUpdates,MessageCircle,true)}</div>{!comm.EmailVerified&&<Link className="notification-help" to="/settings/communications/email">Verify your email to enable email notifications</Link>}{!comm.PhoneVerified&&<Link className="notification-help" to="/settings/communications/sms">Verify your phone to enable SMS notifications</Link>}<p className="privacy-note">Routine SMS is limited to one update per hour. Emergency broadcasts currently use push and email.</p></section>
 <section className="settings-group"><h2>What You Want to Be Notified About</h2><div className="settings-list">{fields.map(([key,col,title,description,Icon],i)=><div key={key}>{i===4&&link('messages','Messages','New messages and chat activity',Mail)}{toggle(key,title,description,isOn(p[col]),Icon)}</div>)}</div></section>
 <section className="settings-group"><h2>Quiet Hours</h2><div className="settings-list">{link('quiet-hours','Quiet Hours','Pause non-essential notifications at night',Moon,p.QuietHoursEnabled?start+' – '+end:'Off')}</div></section>
 </div>;
}
