import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link,useNavigate} from 'react-router-dom';
import {api,rows,str,session,type RecordData} from './api';
import {Loading,ErrorBox} from './ui';
function Evidence({base,url}:{base:string;url:string}){const[src,setSrc]=useState(''),[mime,setMime]=useState(''),[error,setError]=useState<unknown>();useEffect(()=>{const controller=new AbortController();let object='';setSrc('');setError(undefined);(async()=>{try{if(!url.startsWith('levy-evidence:'))throw Error('Evidence is unavailable');const r=await fetch(api.url(base+'/evidence/'+url.slice(14)),{credentials:'include',headers:{Authorization:'Bearer '+session.get()?.accessToken},signal:controller.signal});if(!r.ok)throw Error('Evidence could not be loaded. Reopen the payment to retry.');const blob=await r.blob();if(controller.signal.aborted)return;object=URL.createObjectURL(blob);setMime(blob.type);setSrc(object)}catch(e){if(!controller.signal.aborted)setError(e)}})();return()=>{controller.abort();if(object)URL.revokeObjectURL(object)}},[base,url]);return <section className="levy-review-evidence"><h3>Payment evidence</h3><ErrorBox error={error}/>{!src&&!error&&<Loading/>}{src&&(mime.startsWith('image/')?<img src={src} alt="Payment evidence"/>:mime==='application/pdf'?<><iframe title="Payment evidence PDF" src={src}/><a href={src} target="_blank" rel="noreferrer">Open PDF evidence</a></>:<p>Unsupported evidence format.</p>)}</section>}
export function PaymentReviews({base,onReviewed,ledgerId,submissionId}:{base:string;onReviewed:()=>Promise<void>;ledgerId?:string;submissionId?:string}){
 const navigate=useNavigate();
 const q=useQuery({queryKey:[base+'/payment-submissions'],queryFn:()=>api.get<RecordData[]>(base+'/payment-submissions')}),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();const all=rows(q.data).filter(r=>r.Status==='PENDING'||r.Status==='APPROVED').sort((a,b)=>Number(b.Status==='PENDING')-Number(a.Status==='PENDING')),item=submissionId?rows(q.data).find(r=>r.Id===submissionId):ledgerId?all.find(r=>r.LedgerId===ledgerId&&r.Status==='PENDING')||all.find(r=>r.LedgerId===ledgerId):undefined;
 async function review(action:string){if(!item||busy)return;setBusy(true);setError(undefined);try{await api.send(base+'/payment-submissions/'+item.Id,{action,reviewNote:note},'PATCH');await q.refetch();await onReviewed();setNote('')}catch(e){setError(e)}finally{setBusy(false)}}
 if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;
 if((submissionId||ledgerId)&&!item)return <ErrorBox error={Error('Payment not found or no longer available.')}/>;
 return <section className="levy-reviews">{submissionId||ledgerId?<h1>Payment details</h1>:<><h2>Payment confirmations and paid members</h2><p>Open a submitted payment to check its evidence and approve or decline it.</p></>}{item?<article className="levy-panel"><Link className="levy-review-member" to={'/member/'+item.UserId}>{!!item.ProfileImage&&<img src={api.asset(str(item.ProfileImage))} alt="Member profile"/>}<strong>{str(item.FirstName)} {str(item.LastName)}</strong></Link><h3>{str(item.PlanName)}</h3><dl><dt>Amount submitted</dt><dd>{new Intl.NumberFormat('en-GB',{style:'currency',currency:str(item.CurrencyCode)||'NGN'}).format(Number(item.Amount))}</dd><dt>Payment method</dt><dd>{str(item.PaymentMethod).replaceAll('_',' ')}</dd><dt>Reference</dt><dd>{str(item.Reference)}</dd><dt>Submitted</dt><dd>{new Date(str(item.SubmittedAt)).toLocaleString()}</dd><dt>Status</dt><dd>{str(item.Status)}</dd></dl>{!!item.Note&&<p>{str(item.Note)}</p>}<Evidence base={base} url={str(item.EvidenceUrl)}/><ErrorBox error={error}/>{item.Status==='PENDING'?<><label>Review note<textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label><div className="levy-review-actions"><button className="primary" disabled={busy} onClick={()=>void review('APPROVE')}>Approve</button><button disabled={busy} onClick={()=>void review('REJECT')}>Decline</button></div></>:<p>{str(item.ReviewNote)||'Payment review completed.'}</p>}</article>:all.length?all.map(r=><button className="levy-card" key={str(r.Id)} onClick={()=>{navigate('?view=payment-detail&submission='+encodeURIComponent(str(r.Id)));document.getElementById('main')?.scrollTo({top:0});window.scrollTo({top:0})}}><div><strong>{str(r.FirstName)} {str(r.LastName)}</strong><p>{str(r.PlanName)} · {r.Status==='PENDING'?'Awaiting confirmation':'Paid'}</p></div></button>):<p>No payment submissions yet.</p>}</section>
}
