import {Filesystem,Directory,Encoding} from '@capacitor/filesystem';
import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {BarChart3,Users,Clock,Vote,Download,FileText,Copy} from 'lucide-react';
import {Capacitor} from '@capacitor/core';
import {Share} from '@capacitor/share';
import {api,rows,str,type RecordData} from './api';
import {Loading,ErrorBox} from './ui';
import './poll-insights.css';
const colours=['#009447','#1764d8','#8758ca','#e99b19','#0a969c'];
const num=(v:unknown)=>Number(v)||0;
const fmt=(v:unknown)=>v?new Date(str(v)).toLocaleDateString():'Not set';
export function ParticipationRing({value}:{value:number}){const v=Math.max(0,Math.min(100,value));return <div className="poll-ring-wrap"><svg className="poll-ring" viewBox="0 0 100 100" role="img" aria-label={v+'% participation'}><circle cx="50" cy="50" r="42" fill="none" stroke="#e9edf1" strokeWidth="5"/><circle cx="50" cy="50" r="42" fill="none" stroke="var(--cda-green-dark)" strokeWidth="5" pathLength="100" strokeDasharray={`${v} 100`} transform="rotate(-90 50 50)"/><text x="50" y="56" textAnchor="middle">{v}%</text></svg><small>participation</small></div>}
function Donut({items,total,label}:{items:RecordData[];total:number;label:string}){const sum=items.reduce((n,x)=>n+num(x.Value),0);let offset=0;return <svg viewBox="0 0 200 200" className="poll-donut" role="img" aria-label={label+': '+total+'. '+items.map(x=>str(x.Label)+' '+num(x.Value)).join(', ')}><circle cx="100" cy="100" r="76" fill="none" stroke="#e9edf1" strokeWidth="28"/>{items.map((x,i)=>{const length=sum?num(x.Value)/sum*100:0,start=offset;offset+=length;return <circle key={i} cx="100" cy="100" r="76" fill="none" stroke={colours[i%colours.length]} strokeWidth="28" pathLength="100" strokeDasharray={`${length} ${100-length}`} strokeDashoffset={-start} transform="rotate(-90 100 100)"><title>{str(x.Label)}: {num(x.Value)}</title></circle>})}<text x="100" y="99" textAnchor="middle" className="donut-total">{total}</text><text x="100" y="120" textAnchor="middle" className="donut-label">{label}</text></svg>}
function Bars({items,total}:{items:RecordData[];total:number}){return <div className="insight-bars">{items.map((x,i)=><div key={i}><span className="insight-dot" style={{background:colours[i%colours.length]}}/><span>{str(x.Label)}</span><progress style={{accentColor:colours[i%colours.length],'--bar-colour':colours[i%colours.length]} as React.CSSProperties} value={num(x.Value)} max={Math.max(total,num(x.Value),1)} aria-label={str(x.Label)}/><small>{total?Math.round(num(x.Value)/total*100):0}%</small><small>{num(x.Value)}</small></div>)}</div>}
function Timeline({data}:{data:RecordData[]}){const[mode,setMode]=useState('CumulativeVotes'),max=Math.max(1,...data.map(x=>num(x[mode]))),points=data.map((x,i)=>`${45+(data.length===1?0:i/(data.length-1)*620)},${195-num(x[mode])/max*165}`).join(' ');return <section className="insight-card"><header><h2>Votes Over Time</h2><select aria-label="Timeline display" value={mode} onChange={e=>setMode(e.target.value)}><option value="CumulativeVotes">Cumulative</option><option value="Votes">Daily</option></select></header>{data.length?<svg viewBox="0 0 700 240" className="poll-timeline" role="img" aria-label="Votes over time">{[0,.25,.5,.75,1].map(f=><g key={f}><line x1="45" x2="665" y1={195-f*165} y2={195-f*165} stroke="#e2e7ee" strokeDasharray="4 3"/><text x="35" y={199-f*165} textAnchor="end">{Math.round(max*f)}</text></g>)}<polygon points={`45,195 ${points} ${data.length===1?45:665},195`} fill="#e5f4e8"/><polyline points={points} fill="none" stroke="#00863c" strokeWidth="3"/>{data.map((x,i)=><g key={i}><circle tabIndex={0} cx={45+(data.length===1?0:i/(data.length-1)*620)} cy={195-num(x[mode])/max*165} r="5" fill="#00863c"><title>{fmt(x.VoteDate)}: {num(x[mode])} voters</title></circle>{(i===0||i===data.length-1||data.length<6)&&<text x={45+(data.length===1?0:i/(data.length-1)*620)} y="224" textAnchor="middle">{fmt(x.VoteDate)}</text>}</g>)}</svg>:<p>No votes recorded yet.</p>}</section>}
export function PollInsights({p,communityId,analysis,onView}:{p:RecordData;communityId:string;analysis:boolean;onView:(view:string)=>void}){
 const qc=useQueryClient(),[tab,setTab]=useState('overview'),[body,setBody]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState<unknown>();
 const q=useQuery({queryKey:['/polls/'+p.Id+'/analysis'],queryFn:({signal})=>api.get<RecordData>('/polls/'+p.Id+'/analysis',signal),enabled:!!p.CanAnalyze}),comments=useQuery({queryKey:['/polls/'+p.Id+'/comments'],queryFn:({signal})=>api.get<RecordData[]>('/polls/'+p.Id+'/comments',signal),enabled:!analysis&&tab==='comments'});
 const d=q.data||{},summary=(d.summary||{}) as RecordData,details=(d.poll||{}) as RecordData,visible=p.ResultsVisible!==false&&p.ResultsVisible!==0,options=rows(d.options||p.options),items=options.map(o=>({Label:o.OptionText,Value:o.VoteCount})),voters=num(summary.totalVoters??p.VoterCount),eligible=num(details.EligibleMembers??p.MemberCount),turnout=eligible?Math.round(voters/eligible*1000)/10:0,selections=items.reduce((n,o)=>n+num(o.Value),0),ended=!!p.EndAt&&new Date(str(p.EndAt)).getTime()<=Date.now(),max=Math.max(0,...items.map(x=>num(x.Value))),leaders=items.filter(x=>num(x.Value)===max),minutes=summary.avgMinutesToVote,result=max?(leaders.length>1?'The leading options are tied.':`${ended?'Most selected option':'Currently leading'}: ${str(leaders[0]?.Label)}.`):'No votes have been recorded yet.';
 async function exportResults(){try{const cell=(v:unknown)=>'"'+str(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"',csv=['Option,Votes,Percent of voters',...items.map(x=>[cell(x.Label),num(x.Value),voters?Math.round(num(x.Value)/voters*100):0].join(','))].join('\r\n');if(Capacitor.isNativePlatform()){const file=await Filesystem.writeFile({path:'poll-results.csv',data:csv,directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:'Poll results',files:[file.uri]});return}const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='poll-results.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Results exported.');}catch(e){setError(e)}}
 async function report(){if(!Capacitor.isNativePlatform()){window.print();return}try{const data=[str(p.Question),str(p.Description),'Voters: '+voters,'Eligible: '+eligible,'Turnout: '+turnout+'%',...items.map(x=>str(x.Label)+': '+num(x.Value)),result].join('\n');const file=await Filesystem.writeFile({path:'poll-report.txt',data,directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:'Poll report',files:[file.uri]})}catch(e){setError(e)}}
 const metrics=<div className="poll-metrics">{[[Users,'Total Voters',voters,'Unique members'],[BarChart3,'Voter Turnout',turnout+'%',voters+' of '+eligible+' currently eligible'],[Clock,'Avg. Time to Vote',minutes==null?'—':Math.floor(num(minutes)/60)+'h '+num(minutes)%60+'m','From poll creation'],[Vote,'Total Selections',selections,p.AllowMultiple?'Multiple choices allowed':'One choice per voter']].map(([Icon,label,value,help])=>{const I=Icon as typeof Users;return <div key={str(label)}><I size={24}/><span>{str(label)}</span><strong>{str(value)}</strong><small>{str(help)}</small></div>})}</div>;
 const results=<section className="insight-card"><h2>Results Overview</h2>{visible?<><div className="poll-results-overview">{analysis&&<Donut items={items} total={selections} label="Selections"/>}<Bars items={items} total={voters}/></div><aside className="poll-notice"><Vote size={28}/><div><strong>{ended?'Result':'Live result'}</strong><p>{result}</p>{!!p.AllowMultiple&&<p>The circle shows shares of selections. Bars show percentages of voters.</p>}</div></aside></>:<p>Results are not available to you yet.</p>}</section>;
 if(!p.CanAnalyze)return <ErrorBox error={Error('Poll analysis is available to poll managers.')}/>;
 if(p.CanAnalyze&&q.isPending)return <Loading/>;
 if(p.CanAnalyze&&q.error)return <><ErrorBox error={q.error}/><button onClick={()=>void q.refetch()}>Retry analysis</button></>;
 return <section className="polls-page poll-insights"><section className="insight-card insight-poll-summary"><div className="poll-detail-art">{p.ImageUrl?<img src={api.asset(str(p.ImageUrl))} alt=""/>:<Vote size={48}/>}</div><div><span className="poll-state">{ended?'Completed':'Active'}</span><h2>{str(p.Question)}</h2>{!!details.CreatedByName&&<p>Created by {str(details.CreatedByName)}</p>}<p>{fmt(p.CreatedAt)} – {fmt(p.EndAt)} · {voters} voters</p></div></section>
 {!analysis&&<nav className="poll-view-tabs" aria-label="Poll information">{['overview','voters','comments','details'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</nav>}
 {analysis?<>{metrics}{results}<Timeline data={rows(d.timeline)}/><div className="insight-columns"><section className="insight-card"><h2>Demographics</h2>{rows(d.ageGroups).length?<><Donut items={rows(d.ageGroups)} total={voters} label="Voters"/><Bars items={rows(d.ageGroups)} total={voters}/></>:<p>No demographic data available.</p>}</section><section className="insight-card"><h2>Votes by Membership Type</h2><Bars items={rows(d.memberGroups)} total={voters}/>{!rows(d.memberGroups).length&&<p>No votes yet.</p>}</section></div><aside className="poll-notice"><div><strong>Key Insights</strong><p>{result} Current turnout is {turnout}%.</p><small>Eligibility and membership groups reflect current membership. Voting times reflect stored ballots, including any changes.</small></div><button onClick={()=>void report()}><FileText size={18}/>View Full Report</button></aside></>:tab==='overview'?<>{results}{visible&&<section className="insight-card"><h2>Poll Summary</h2>{metrics}</section>}<section className="insight-card"><h2>Description</h2><p>{str(p.Description)||'No description provided.'}</p><span className="poll-state">{str((p.settings as RecordData)?.category)||'General'}</span></section></>:tab==='voters'?<section className="insight-card"><h2>Voters</h2>{!p.CanAnalyze?<p>Voter details are available to poll managers only.</p>:p.IsAnonymous?<p>This poll is anonymous. Voter identities are hidden.</p>:rows(d.voters).length?rows(d.voters).map(v=><div className="insight-voter" key={str(v.UserId)}><Link to={'/member/'+v.UserId+'?community='+communityId}>{str(v.FirstName)} {str(v.LastName)}</Link><span>{str(v.Vote)}</span><small>{fmt(v.VotedAt)}</small></div>):<p>No votes yet.</p>}</section>:tab==='comments'?<section className="insight-card"><h2>Comments</h2>{comments.isPending?<Loading/>:comments.error?<ErrorBox error={comments.error}/>:comments.data?.length?comments.data.map(c=><article className="insight-comment" key={str(c.Id)}><strong>{str(c.Author)}</strong><small>{fmt(c.CreatedAt)}</small><p>{str(c.Body)}</p></article>):<p>No comments yet.</p>}<form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError(undefined);try{await api.send('/polls/'+p.Id+'/comments',{body});setBody('');await qc.invalidateQueries({queryKey:['/polls/'+p.Id+'/comments']})}catch(e){setError(e)}finally{setBusy(false)}}}><label>Add a comment<textarea required maxLength={2000} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Posting…':'Post comment'}</button></form></section>:<section className="insight-card"><h2>Details</h2><dl>{[['Created',fmt(p.CreatedAt)],['Closing date',fmt(p.EndAt)],['Type',str((p.settings as RecordData)?.type)||'General'],['Voting',p.AllowMultiple?'Multiple choices':'Single choice'],['Anonymous',p.IsAnonymous?'Yes':'No'],['Vote changes',p.AllowChangeVote?'Allowed':'Not allowed']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section>}
 <ErrorBox error={error}/>{notice&&<p role="status">{notice}</p>}<div className="insight-actions">{visible&&<button onClick={()=>void exportResults()}><Download size={18}/>Export Results</button>}<button onClick={()=>void report()}><FileText size={18}/>View Report</button>{!!p.CanCreate&&<Link className="button" to={'/community/'+communityId+'/polls?view=create&copy='+p.Id}><Copy size={18}/>Create Similar Poll</Link>}</div></section>
}
