import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {Play,Pause,Volume2,VolumeX,RotateCcw,RotateCw,ArrowLeft,Maximize2,MoreHorizontal,ThumbsUp,MessageCircle,Share2,Bookmark} from 'lucide-react';
import {Capacitor} from '@capacitor/core';
import {Share} from '@capacitor/share';
import {api,session,str,type RecordData} from './api';
import {Action} from './ui';
import {CommentComposer} from './SocialComments';
export async function sharePost(post:RecordData){const url='https://cdaconnect.org/post/'+post.Id;if(Capacitor.isNativePlatform())await Share.share({title:'Community post',url});else if(navigator.share)await navigator.share({title:'Community post',url});else await navigator.clipboard.writeText(url)}
export function SocialActions({post}:{post:RecordData}){const[notice,setNotice]=useState('');return <><div className="social-actions"><Action run={()=>api.send('/posts/'+post.Id+'/reaction',{reaction:post.MyReaction==='LIKE'?null:'LIKE'})}><ThumbsUp size={18}/><span className="sr-only">{post.MyReaction==='LIKE'?'Unlike':'Like'}</span><small>{Number(post.ReactionCount||0)}</small></Action><Link to={'/post/'+post.Id+'#comments'}><MessageCircle size={18}/><span className="sr-only">Comment</span><small>{Number(post.CommentCount||0)}</small></Link><button onClick={async()=>{try{await sharePost(post);setNotice(typeof navigator.share==='function'||Capacitor.isNativePlatform()?'':'Link copied.')}catch(e){if((e as Error).name!=='AbortError')setNotice('Sharing failed. Please try again.')}}}><Share2 size={18}/><span className="sr-only">Share</span></button><Action run={()=>api.send('/posts/'+post.Id+'/save')}><Bookmark size={18}/><span className="sr-only">{post.MySaved?'Unsave':'Save'}</span></Action></div>{notice&&<p role="status">{notice}</p>}</>}
export function PostMedia({post}:{post:RecordData}){
 const mediaSection=useRef<HTMLDivElement>(null);
 const[open,setOpen]=useState(false),[failed,setFailed]=useState(false);const url=api.asset(str(post.MediaUrl)),type=str(post.MediaType),photo=type.startsWith('image/')||post.PostType==='PHOTO',video=type.startsWith('video/')||post.PostType==='VIDEO';
 useEffect(()=>setFailed(false),[url]);
 useEffect(()=>{
  const section=mediaSection.current,media=section?.querySelector<HTMLMediaElement>('video,audio');
  if(!section||!media)return;
  let visible=true;
  const pause=()=>{if(!media.paused)media.pause()};
  const onPlay=()=>{const rect=media.getBoundingClientRect();if(!visible||document.hidden||open||rect.bottom<=0||rect.top>=window.innerHeight)pause()};
  const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting&&entry.intersectionRatio>0;if(!visible)pause()},{threshold:0});
  observer.observe(media);
  const onVisibility=()=>{if(document.hidden)pause()};
  media.addEventListener('play',onPlay);document.addEventListener('visibilitychange',onVisibility);
  if(open)pause();
  return()=>{observer.disconnect();media.removeEventListener('play',onPlay);document.removeEventListener('visibilitychange',onVisibility);pause()};
 },[url,failed,open]);
 if(!post.MediaUrl)return null;
 return <div ref={mediaSection} className="post-media">{failed?<p role="status">Media is unavailable.</p>:photo?<button className="media-open" aria-label="Open photo" onClick={()=>setOpen(true)}><img src={url} loading="lazy" alt={str(post.Caption)||'Community photo'} onError={()=>setFailed(true)}/></button>:video?<div className="inline-video"><video src={url} controls playsInline preload="metadata" controlsList="nodownload" onClick={e=>{e.currentTarget.pause();setOpen(true)}} onError={()=>setFailed(true)}/><button className="media-expand" aria-label="Open video" onClick={()=>setOpen(true)}><Maximize2 size={20}/></button></div>:type.startsWith('audio/')?<audio src={url} controls preload="metadata" controlsList="nodownload"/>:<a href={url} target="_blank" rel="noreferrer">{str(post.DocumentName)||'Open attachment'}</a>}{open&&createPortal(<MediaViewer post={post} photo={photo} close={()=>setOpen(false)}/>,document.body)}</div>
}
function MediaViewer({post,photo,close}:{post:RecordData;photo:boolean;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[zoom,setZoom]=useState(false),[paused,setPaused]=useState(false),[muted,setMuted]=useState(true),[duration,setDuration]=useState(0),[time,setTime]=useState(0),[playError,setPlayError]=useState(''),videoRef=useRef<HTMLVideoElement>(null);const member=useQuery({queryKey:['/users/members/'+post.CreatedBy],queryFn:()=>api.get<RecordData>('/users/members/'+post.CreatedBy),enabled:!!post.CreatedBy&&post.CreatedBy!==session.get()?.user.Id});const profile=member.data?.profile as RecordData|undefined;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialog.current?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;previous?.focus()}},[]);
 return <dialog ref={dialog} className={"media-viewer "+(photo?"photo-viewer":"video-viewer")} aria-label="Community media viewer" onCancel={e=>{e.preventDefault();close()}}><header><button aria-label="Close media viewer" onClick={close}><ArrowLeft/></button><div>{photo&&<button aria-label={zoom?'Fit photo':'Zoom photo'} onClick={()=>setZoom(!zoom)}><Maximize2/></button>}<details><summary aria-label="More media options"><MoreHorizontal/></summary><nav><Link to={'/post/'+post.Id} onClick={close}>Open post</Link>{!!post.CreatedBy&&<Link to={'/member/'+post.CreatedBy} onClick={close}>View member profile</Link>}</nav></details></div></header><div className={'viewer-stage'+(zoom?' zoomed':'')}>{photo?<img src={api.asset(str(post.MediaUrl))} alt={str(post.Caption)||'Community photo'}/>:<video ref={videoRef} src={api.asset(str(post.MediaUrl))} autoPlay muted={muted} playsInline onPlay={()=>setPaused(false)} onPause={()=>setPaused(true)} onLoadedMetadata={e=>setDuration(e.currentTarget.duration)} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onError={()=>setPlayError('Video is unavailable.')}/>}</div><footer>{!photo&&<><input className="viewer-progress" type="range" aria-label="Video position" min={0} max={Number.isFinite(duration)?duration:0} step={0.1} value={time} onChange={e=>{if(videoRef.current)videoRef.current.currentTime=Number(e.target.value)}}/><div className="viewer-playback"><button aria-label={muted?'Unmute video':'Mute video'} onClick={()=>setMuted(!muted)}>{muted?<VolumeX/>:<Volume2/>}</button><div><button aria-label="Rewind 10 seconds" onClick={()=>{if(videoRef.current)videoRef.current.currentTime=Math.max(0,time-10)}}><RotateCcw/></button><button aria-label={paused?'Play video':'Pause video'} onClick={()=>{const v=videoRef.current;if(v){if(v.paused)void v.play().catch(()=>setPlayError('Playback could not start. Try again.'));else v.pause()}}}>{paused?<Play/>:<Pause/>}</button><button aria-label="Forward 10 seconds" onClick={()=>{if(videoRef.current&&Number.isFinite(duration))videoRef.current.currentTime=Math.min(duration,time+10)}}><RotateCw/></button></div></div>{playError&&<p className="viewer-play-error" role="alert">{playError}</p>}</>}<div className="viewer-author"><Link to={'/member/'+post.CreatedBy} onClick={close}>{!!post.ProfileImage&&<img src={api.asset(str(post.ProfileImage))} alt=""/>}<strong>{[post.FirstName,post.LastName].filter(Boolean).join(' ')||'Community member'}</strong></Link>{profile&&Boolean(profile.AllowFollowers||member.data?.following)&&<Action run={()=>api.send('/users/members/'+post.CreatedBy+'/follow',{following:!member.data?.following},'PUT')}>{member.data?.following?'Unfollow':'Follow'}</Action>}</div><p>{str(post.Body)}</p><div onClick={e=>{if((e.target as HTMLElement).closest('a'))close()}}><SocialActions post={post}/></div><CommentComposer postId={str(post.Id)}/></footer></dialog>
}
