import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {Send,Smile,X,ThumbsUp,ThumbsDown} from 'lucide-react';
import {api,str,session,type RecordData} from './api';
import {Action,Loading,ErrorBox} from './ui';
export type ReplyTarget={id:string;name:string};
export function CommentComposer({postId,reply,onCancelReply}:{postId:string;reply?:ReplyTarget;onCancelReply?:()=>void}){
 const[body,setBody]=useState(''),[busy,setBusy]=useState(false),[emoji,setEmoji]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),input=useRef<HTMLTextAreaElement>(null),qc=useQueryClient();
 useEffect(()=>{if(reply)input.current?.focus()},[reply]);
 async function send(e:FormEvent){e.preventDefault();if(!body.trim()||busy)return;setBusy(true);setError(undefined);setNotice('');try{await api.send('/posts/'+postId+'/comments',{body:body.trim(),...(reply?{parentCommentId:reply.id}:{})});setBody('');setEmoji(false);onCancelReply?.();await qc.invalidateQueries();setNotice('Comment posted.')}catch(e){setError(e)}finally{setBusy(false)}}
 return <div className="comment-composer"><ErrorBox error={error}/><span className="sr-only" role="status">{notice}</span>{reply&&<div className="reply-notice">Replying to {reply.name}<button type="button" aria-label="Cancel reply" onClick={onCancelReply}><X size={16}/></button></div>}{emoji&&<div className="comment-emojis" aria-label="Choose an emoji">{['😀','❤️','👏','🎉','👍','🙏','😂','😊'].map(value=><button type="button" key={value} aria-label={'Insert '+value} onClick={()=>{setBody(b=>b.length<1498?b+value:b);input.current?.focus()}}>{value}</button>)}</div>}<form onSubmit={send}><textarea ref={input} aria-label="Your comment" placeholder={'Comment as '+(session.get()?.user.FirstName||'a member')} value={body} maxLength={1500} rows={1} disabled={busy} onChange={e=>setBody(e.target.value)}/><button type="button" aria-label="Choose emoji" aria-expanded={emoji} onClick={()=>setEmoji(!emoji)} disabled={busy}><Smile size={22}/></button><button type="submit" aria-label="Post comment" disabled={busy||!body.trim()}><Send size={21}/></button></form></div>
}
export function CommentThread({postId,onReply}:{postId:string;onReply:(reply:ReplyTarget)=>void}){
 const[sort,setSort]=useState('relevant'),q=useQuery({queryKey:['/posts/'+postId+'/comments'],queryFn:({signal})=>api.get<RecordData[]>('/posts/'+postId+'/comments',signal)});
 if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;const comments=q.data||[],compare=(a:RecordData,b:RecordData)=>sort==='relevant'?Number(b.LikeCount||0)-Number(a.LikeCount||0):sort==='newest'?Date.parse(str(b.CreatedAt))-Date.parse(str(a.CreatedAt)):Date.parse(str(a.CreatedAt))-Date.parse(str(b.CreatedAt));
 const roots=comments.filter(c=>!c.ParentCommentId||!comments.some(p=>p.Id===c.ParentCommentId)).sort(compare);
 function render(c:RecordData,depth=0):React.ReactNode{return <div className={'social-comment'+(depth?' comment-reply':'')} key={str(c.Id)}><Link className="comment-avatar" to={'/member/'+c.UserId}>{c.ProfileImage?<img src={api.asset(str(c.ProfileImage))} alt=""/>:str(c.FirstName).slice(0,1)}</Link><div className="comment-content"><div><Link to={'/member/'+c.UserId}><strong>{[c.FirstName,c.LastName].filter(Boolean).join(' ')}</strong></Link><time>{new Date(str(c.CreatedAt)).toLocaleDateString()}</time></div><p>{str(c.Body)}</p><div className="comment-actions"><button onClick={()=>onReply({id:str(c.Id),name:[c.FirstName,c.LastName].filter(Boolean).join(' ')})}>Reply</button><Action run={()=>api.send('/comments/'+c.Id+'/reaction',{reaction:c.MyReaction==='LIKE'?null:'LIKE'})}><ThumbsUp size={16}/><span className="sr-only">Like comment</span>{Number(c.LikeCount||0)||''}</Action><Action run={()=>api.send('/comments/'+c.Id+'/reaction',{reaction:c.MyReaction==='DISLIKE'?null:'DISLIKE'})}><ThumbsDown size={16}/><span className="sr-only">Dislike comment</span>{Number(c.DislikeCount||0)||''}</Action></div>{depth<20&&comments.filter(r=>r.ParentCommentId===c.Id).sort(compare).map(r=>render(r,depth+1))}</div></div>}
 return <section className="comment-thread" id="comments" aria-label="Comments"><label className="comment-sort"><span className="sr-only">Sort comments</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="relevant">Most relevant</option><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label>{comments.length?roots.map(c=>render(c)):<p className="comments-empty">No comments yet. Be the first to join the conversation.</p>}</section>
}
