import {useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {ChartNoAxesColumn,Wifi,Image,Video,FileText,Headphones,Trash2,HardDrive,CloudUpload,RefreshCw,ShieldCheck,ChevronRight,ArrowLeft} from 'lucide-react';
import {useStoragePreferences,saveStoragePreferences,bytes,useConnectionType,type StoragePreferences} from './storageDevice';
import {storageDefaults,type MediaPolicy} from './storagePolicy';
import {localStorageItems,removeLocalItem,clearPublicCache,publicCacheBytes} from './storageLocal';
import {AccountDownload} from './account';
import {Action,ErrorBox,Loading,MutationForm} from './ui';
import {applyLanguage,getLocale} from './i18n';
const policies={WIFI:'Wi-Fi Only',ALWAYS:'Wi-Fi and Mobile',NEVER:'Never'};
const media=[['photos','Photos',Image],['videos','Videos',Video],['documents','Documents',FileText],['audio','Audio',Headphones]] as const;
export function StorageSettings(){const field=useLocation().pathname.split('/')[3]||'',p=useStoragePreferences(),network=useConnectionType(),qc=useQueryClient(),[error,setError]=useState<unknown>(),[notice,setNotice]=useState('');const q=useQuery({queryKey:['device-storage'],queryFn:async()=>({estimate:await navigator.storage?.estimate?.()??{},cache:await publicCacheBytes(),items:await localStorageItems()}),refetchOnWindowFocus:true});function save(value:Partial<StoragePreferences>){try{saveStoragePreferences(value);setError(undefined);setNotice('Device preference saved.')}catch(e){setError(e)}}
 const link=(to:string,title:string,description:string,Icon:typeof Wifi,value?:string)=><Link className="settings-row" to={'/settings/data/'+to}><span className="settings-row-icon"><Icon size={21}/></span><span className="settings-row-text"><strong>{title}</strong><small>{description}</small></span>{value&&<span className="privacy-value">{value}</span>}<ChevronRight size={17}/></Link>;
 const toggle=(key:'dataSaver'|'syncMobile',title:string,description:string,Icon:typeof Wifi)=><label className="settings-row account-switch-row"><span className="settings-row-icon"><Icon size={21}/></span><span className="settings-row-text"><strong>{title}</strong><small>{description}</small></span><input type="checkbox" role="switch" checked={p[key]} onChange={e=>save({[key]:e.target.checked})}/></label>;
 const feedback=<>{error!=null&&<ErrorBox error={error}/>}<p className="privacy-status" role="status">{notice}</p></>;
 const usage=q.data?.estimate.usage,quota=q.data?.estimate.quota,percent=usage!=null&&quota?Math.min(100,Math.round(usage/quota*100)):undefined,localSize=q.data?.items.reduce((sum,x)=>sum+x.size,0);
 let measured:{bytes:number;reported:number;unreported:number}|undefined;try{measured=JSON.parse(localStorage.getItem('cda-network-usage-'+new Date().toISOString().slice(0,7))||'null')}catch{}
 if(field)return <div className="storage-detail"><Link className="settings-back" to="/settings/data"><ArrowLeft size={17}/>Data & Storage</Link><h2>{media.find(x=>x[0]===field)?.[1]||({storage:'Manage Storage',usage:'Data Usage Summary',cache:'Clear Cache',local:'Manage Local Data',backup:'Back Up Data',learn:'Your Data'} as Record<string,string>)[field]||'Data & Storage'}</h2>{feedback}
 {media.some(x=>x[0]===field)&&<><p>Choose when this media may load automatically. Saving to Downloads or another app still requires your action.</p><MutationForm key={field} label="Save media preference" onSubmit={async d=>{saveStoragePreferences({[field]:d.policy as MediaPolicy});setNotice('Media preference saved.')}}><label>Automatic loading<select name="policy" defaultValue={p[field as keyof StoragePreferences] as string}>{Object.entries(policies).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></MutationForm><p className="privacy-note">Wi-Fi Only waits for a confirmed Wi-Fi or Ethernet connection. If this device cannot report its network type, use Load or Download manually. Data Saver pauses automatic media loading. Document preloading requires download permission and a reported file size up to 10 MB.</p></>}
 {field==='usage'&&<section className="card"><h3>Reported transfers this month</h3><strong>{measured?.reported?bytes(measured.bytes):'Not reported yet'}</strong><p>Measured on this device since this feature was installed. These browser-reported transfers exclude unreported or cached resources and may exclude uploads. They are not your mobile provider’s billing total.</p><p>{measured?.reported||0} resources reported a transfer size; {measured?.unreported||0} did not.</p></section>}
 {field==='storage'&&<><section className="card"><h3>Web app storage estimate</h3><p>Used: {bytes(usage)}</p><p>Browser allocation: {bytes(quota)}</p><p>This is browser-managed storage, not your account’s cloud allowance or all files on your device.</p></section>{link('cache','Clear Cache','Remove CDA Connect’s public offline cache',Trash2,bytes(q.data?.cache))}{link('local','Manage Local Data','Review app-managed files and language packs',HardDrive,bytes(localSize))}</>}
 {field==='cache'&&<><p>Clear temporary public offline-page data ({bytes(q.data?.cache)}). Your sign-in session, preferences, messages and server files remain intact. The offline fallback returns after the service worker installs again.</p><Action run={async()=>{await clearPublicCache();await qc.invalidateQueries({queryKey:['device-storage']});setNotice('Public cache cleared.')}}>Clear public cache</Action></>}
 {field==='local'&&<>{q.isPending?<Loading/>:q.error?<ErrorBox error={q.error}/>:!q.data?.items.length?<p>No removable app-managed files or language packs were found.</p>:q.data.items.map(item=><section className="card" key={item.key}><h3>{item.key.replace('cda-language-pack-','Language pack: ')}</h3><p>{bytes(item.size)}</p><Action run={async()=>{if(!window.confirm('Remove this local app file? Copies saved outside CDA Connect are not affected.'))return;await removeLocalItem(item);applyLanguage(getLocale());await qc.invalidateQueries({queryKey:['device-storage']});setNotice('Local app file removed.')}}>Remove local file</Action></section>)}<p className="privacy-note">Files saved to your browser Downloads folder, Photos or other apps must be managed there. Removing a temporary copy does not delete your server content.</p></>}
 {field==='backup'&&<><p>Your submitted account information is already stored on the server. Download a personal JSON copy below. This is an export, not an automatic cloud backup or a restore service.</p><AccountDownload/></>}
 {field==='learn'&&<><p>Device preferences stay on this device. Content you submit is stored on the app server. Clearing local data does not delete your account or its server records.</p><p>Wi-Fi detection is unavailable on some browsers and native web views. Wi-Fi-only background refreshes and media loading pause when the network type is unknown. Manual actions and live chat remain available.</p><p>Voice and video bitrate controls are not currently exposed by this app, so the call-data switch cannot be enabled.</p><Link className="button secondary" to="/settings/privacy">Privacy & Safety</Link><Link className="button secondary" to="/settings/support">Contact Support</Link></>}
 </div>;
 return <div className="privacy-dashboard storage-dashboard"><p>Manage your data usage, storage and download preferences.</p>{feedback}{q.error&&<ErrorBox error={q.error}/>}<section className="storage-hero"><div className="storage-ring" style={{background:percent==null?'#e3e9ed':`conic-gradient(#008540 ${percent}%,#e3e9ed 0)`}}><span><strong>{percent==null?'—':percent+'%'}</strong><small>Used</small></span></div><div><small>Web App Storage Used</small><h2>{q.isPending?'Checking…':bytes(usage)}</h2><p>of {bytes(quota)} browser allocation</p><Link to="/settings/data/storage">Manage Storage →</Link></div></section>
 <section className="settings-group"><h2>Data Usage</h2><div className="settings-list">{toggle('dataSaver','Data Saver','Pause automatic media loading and reduce background refreshes',ChartNoAxesColumn)}<label className="settings-row account-switch-row"><span className="settings-row-icon"><Wifi size={21}/></span><span className="settings-row-text"><strong>Use Less Data for Calls</strong><small>Call quality controls are not available in this build</small></span><input type="checkbox" role="switch" disabled checked={false} readOnly/></label>{link('usage','Data Usage Summary','View transfers reported by this device',ChartNoAxesColumn,measured?.reported?bytes(measured.bytes):'Not reported')}</div></section>
 <section className="settings-group"><h2>Media Auto-Download</h2><div className="settings-list">{media.map(([key,title,Icon])=><div key={key}>{link(key,title,'Automatic media loading',Icon,policies[p[key]])}</div>)}<button className="language-all" onClick={()=>save({photos:storageDefaults.photos,videos:storageDefaults.videos,documents:storageDefaults.documents,audio:storageDefaults.audio})}>Reset Auto-Download Settings</button></div><p className="privacy-note">Network: {network==='unknown'?'not reported by this device':network}. Wi-Fi-only media remains manual when network detection is unavailable.</p></section>
 <section className="settings-group"><h2>Cache</h2><div className="settings-list">{link('cache','Clear Cache','Free space used by temporary public data',Trash2,bytes(q.data?.cache))}{link('local','Manage Local Data','Review app files and downloaded interface packs',HardDrive,bytes(localSize))}</div></section>
 <section className="settings-group"><h2>Other Settings</h2><div className="settings-list">{link('backup','Back Up Data','Export a personal copy of your account data',CloudUpload)}{toggle('syncMobile','Sync Over Mobile Data','Allow background refreshes on mobile or unknown networks',RefreshCw)}</div></section><section className="privacy-safety"><ShieldCheck size={36}/><div><strong>Manage your data</strong><p>Understand what is stored locally and on your account.</p></div><Link className="button secondary" to="/settings/data/learn">Learn More</Link></section></div>;
}
