import {useEffect,useMemo,useState,type ReactNode} from 'react';
import {Link,NavLink,Navigate,Outlet,useLocation,useNavigate,useParams} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {Activity,AlertTriangle,BarChart3,Bell,Building2,ChevronLeft,CircleDollarSign,ClipboardCheck,FileClock,HeartPulse,Home,LifeBuoy,LockKeyhole,Menu,MessageSquareWarning,Network,Plug,Settings,Shield,ShieldCheck,SlidersHorizontal,UserCog,Users,X} from 'lucide-react';
import {api,rows,session,str,type RecordData,type Session} from './api';
import {useSession} from './auth';
import {Action,Empty,ErrorBox,Field,Loading,MutationForm} from './ui';import {VerificationCode} from './VerificationCode';
export {AdminDetail} from './SuperAdminDetail';

type Item={to:string;label:string;icon:typeof Home};
const groups:{label:string;items:Item[]}[]=[
 {label:'',items:[{to:'/super-admin',label:'Overview',icon:Home}]},
 {label:'Management',items:[{to:'/super-admin/users',label:'Users',icon:Users},{to:'/super-admin/communities',label:'Communities',icon:Building2},{to:'/super-admin/verifications',label:'Verifications',icon:ClipboardCheck},{to:'/super-admin/moderation',label:'Moderation',icon:MessageSquareWarning},{to:'/super-admin/finance',label:'Finance',icon:CircleDollarSign},{to:'/super-admin/emergencies',label:'Emergencies',icon:AlertTriangle},{to:'/super-admin/support',label:'Support',icon:LifeBuoy}]},
 {label:'Operations',items:[{to:'/super-admin/notifications',label:'Notifications',icon:Bell},{to:'/super-admin/queues',label:'Queues',icon:Network},{to:'/super-admin/system-health',label:'System Health',icon:HeartPulse},{to:'/super-admin/analytics',label:'Analytics',icon:BarChart3}]},
 {label:'Security',items:[{to:'/super-admin/audit-logs',label:'Audit Logs',icon:FileClock},{to:'/super-admin/security',label:'Security Centre',icon:ShieldCheck},{to:'/super-admin/administrators',label:'Administrators',icon:UserCog},{to:'/super-admin/roles',label:'Roles & Permissions',icon:LockKeyhole},{to:'/super-admin/privacy',label:'Data & Privacy',icon:Shield}]},
 {label:'Configuration',items:[{to:'/super-admin/settings',label:'Platform Settings',icon:Settings},{to:'/super-admin/integrations',label:'Integrations',icon:Plug},{to:'/super-admin/account',label:'My Account',icon:SlidersHorizontal}]},
];
const labels=Object.fromEntries(groups.flatMap(group=>group.items.map(item=>[item.to,item.label])));
const display=(value:unknown)=>value===null||value===undefined||value===''?'—':typeof value==='boolean'?(value?'Yes':'No'):typeof value==='object'?JSON.stringify(value):String(value);
const friendly=(key:string)=>key.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/Id$/,' ID');

function MfaGate({children}:{children:ReactNode}){
 const status=useQuery({queryKey:['/super-admin/mfa/status'],queryFn:({signal})=>api.get<RecordData>('/super-admin/mfa/status',signal),retry:false});
 const[verified,setVerified]=useState(false);useEffect(()=>{if(status.data?.verified)setVerified(true)},[status.data]);
 if(status.isPending)return <main className="admin-gate"><Loading/></main>;
 if(status.error)return <main className="admin-gate"><ErrorBox error={status.error}/></main>;
 if(!status.data?.enabled||status.data.method!=='authenticator')return <main className="admin-gate"><Shield size={38}/><h1>Authenticator protection required</h1><p>Super Admin access requires authenticator-app 2FA. Set it up before opening this protected workspace.</p><Link className="button primary" to="/settings/two-factor">Set up authenticator</Link></main>;
 if(!verified)return <main className="admin-gate"><LockKeyhole size={38}/><h1>Verify Super Admin access</h1><p>Enter the current six-digit code from your authenticator app.</p><MutationForm label="Open protected dashboard" onSuccess={()=>setVerified(true)} onSubmit={data=>api.send('/super-admin/mfa/verify',{code:data.code})}><VerificationCode label="Authenticator code"/></MutationForm></main>;
 return <>{children}</>;
}

export function SuperAdminShell(){
 const current=useSession(),location=useLocation(),nav=useNavigate(),[open,setOpen]=useState(false);useEffect(()=>setOpen(false),[location.pathname]);
 if(!current?.user.IsSuperAdmin)return <Navigate to="/home" replace/>;
 const base=location.pathname.match(/^\/super-admin\/users\/[^/]+/)?.[0]||location.pathname.match(/^\/super-admin\/communities\/[^/]+/)?.[0]||location.pathname;
 const title=base.startsWith('/super-admin/users/')?'User details':base.startsWith('/super-admin/communities/')?'Community details':labels[base]||'Super Admin';
 return <MfaGate><div className="admin-shell"><button className="admin-scrim" aria-label="Close navigation" onClick={()=>setOpen(false)} data-open={open}/><aside className="admin-sidebar" data-open={open}><div className="admin-brand"><span>🌐</span><strong>CDA<span>Connect</span></strong><button aria-label="Close navigation" onClick={()=>setOpen(false)}><X/></button></div><nav>{groups.map(group=><section key={group.label||'overview'}>{group.label&&<h2>{group.label}</h2>}{group.items.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/super-admin'}><Icon/>{label}</NavLink>)}</section>)}</nav><div className="admin-person"><strong>{current.user.FirstName} {current.user.LastName}</strong><small>Protected Super Admin</small><button onClick={()=>nav('/home')}><ChevronLeft/> Community app</button></div></aside><div className="admin-workspace"><header className="admin-topbar"><button className="admin-menu" aria-label="Open navigation" onClick={()=>setOpen(true)}><Menu/></button><div><small>Protected workspace</small><h1>{title}</h1></div><Link aria-label="Security centre" to="/super-admin/security"><ShieldCheck/></Link></header><main className="admin-content"><Outlet/></main><nav className="admin-mobile-nav">{[groups[0].items[0],groups[1].items[0],groups[1].items[1],groups[2].items[2],groups[4].items[2]].map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/super-admin'}><Icon/><span>{label}</span></NavLink>)}</nav></div></div></MfaGate>;
}

export function SuperAdminLogin(){
 const current=useSession(),nav=useNavigate(),[challenge,setChallenge]=useState('');if(current?.user.IsSuperAdmin)return <Navigate to="/super-admin" replace/>;
 return <main className="admin-login"><section><div className="admin-login-brand">🌐 <strong>CDAConnect</strong></div><ShieldCheck size={42}/><h1>Super Admin sign in</h1><p>This protected workspace requires your password and authenticator app.</p><MutationForm label={challenge?'Verify and continue':'Continue'} onSubmit={async data=>{const result=await api.send<Session&{requiresTwoFactor?:boolean;challengeToken?:string}>(challenge?'/auth/login/two-factor':'/auth/login',challenge?{challengeToken:challenge,code:data.code}:{email:data.email,password:data.password});if(result.requiresTwoFactor){setChallenge(result.challengeToken!);return}if(!result.user.IsSuperAdmin)throw Error('This account does not have Super Admin access.');session.set(result);nav('/super-admin',{replace:true})}}>{challenge?<VerificationCode label="Authenticator code"/>:<><Field name="email" label="Email address" type="email"/><Field name="password" label="Password" type="password"/></>}</MutationForm>{challenge&&<button onClick={()=>setChallenge('')}>Use another account</button>}<p className="muted">Do not trust shared or public devices. Protected-account recovery is handled through the audited security process.</p></section></main>;
}

export function AdminOverview(){const q=useQuery({queryKey:['/super-admin/overview'],queryFn:({signal})=>api.get<RecordData>('/super-admin/overview',signal)});if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;const summary=q.data.summary as RecordData,activity=rows(q.data.activity);return <><section className="admin-hero"><div><p>Platform overview</p><h2>Monitor CDA Connect safely</h2><span>Community finance and private evidence remain hidden unless separately authorised.</span></div><Activity/></section><div className="admin-metrics">{Object.entries(summary||{}).map(([key,value])=><article key={key}><small>{friendly(key)}</small><strong>{display(value)}</strong></article>)}</div><section className="admin-panel"><header><div><h2>Recent security activity</h2><p>Latest audited actions across the platform.</p></div><Link to="/super-admin/audit-logs">View all</Link></header><AdminTable data={activity}/></section></>}

const endpointFor:Record<string,string>={verifications:'verifications',moderation:'moderation',finance:'finance',emergencies:'emergencies',notifications:'notifications',queues:'queues','system-health':'system-health',support:'support','audit-logs':'audit-logs',security:'security',administrators:'administrators',roles:'roles',privacy:'privacy',analytics:'analytics',settings:'settings',integrations:'integrations'};
export function AdminSection(){const {section='',paymentId}=useParams(),path=paymentId?`finance/payments/${paymentId}`:endpointFor[section]||section,q=useQuery({queryKey:['/super-admin/'+path],queryFn:({signal})=>api.get<unknown>('/super-admin/'+path,signal)});if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;if(section==='analytics'&&q.data&&typeof q.data==='object'){const metrics=q.data as RecordData;return <><section className="admin-panel"><h2>Application activity</h2><p>Daily totals for the last 30 days, recorded by the application. These totals do not depend on optional analytics cookies. Messages and posts exclude deleted records.</p></section>{Object.entries(metrics).map(([name,values])=><section key={name} className="admin-panel"><h2>{friendly(name)}</h2><AdminTable data={rows(values)}/></section>)}</>}const data=Array.isArray(q.data)?q.data:objectRows(q.data);return <section className="admin-panel"><header><div><h2>{paymentId?'Payment investigation':labels['/super-admin/'+section]||'Platform records'}</h2><p>Live operational data. Sensitive values and provider secrets are masked by the API.</p></div></header><AdminTable data={data}/></section>}
function objectRows(value:unknown){if(!value||typeof value!=='object')return[];const object=value as RecordData;const list=rows(value);if(list.length)return list;return Object.entries(object).map(([Name,Value])=>({Name,Value}))}
function AdminTable({data}:{data:RecordData[]}){if(!data.length)return <Empty text="No records found"/>;const keys=Array.from(new Set(data.flatMap(item=>Object.keys(item)))).filter(key=>!['Id','InternalId','CommunityId','UserId','Details'].includes(key)).slice(0,6);return <div className="admin-table-wrap"><table><thead><tr>{keys.map(key=><th key={key}>{friendly(key)}</th>)}</tr></thead><tbody>{data.map((item,index)=><tr key={str(item.Id||item.InternalId)||index}>{keys.map(key=><td key={key}>{display(item[key])}</td>)}</tr>)}</tbody></table></div>}


export function AdminUsers(){const[search,setSearch]=useState(''),[status,setStatus]=useState('ALL'),endpoint=useMemo(()=>`/super-admin/users?search=${encodeURIComponent(search)}&status=${status}`,[search,status]),q=useQuery({queryKey:[endpoint],queryFn:({signal})=>api.get<RecordData[]>(endpoint,signal)});return <section className="admin-panel"><header><div><h2>Users</h2><p>Search accounts, review verification and open a complete audit profile.</p></div></header><div className="admin-filters"><input aria-label="Search users" placeholder="Search name or email" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Account status" value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option><option>ACTIVE</option><option>SUSPENDED</option><option>DEACTIVATED</option></select></div>{q.isPending?<Loading/>:q.error?<ErrorBox error={q.error}/>:q.data?.length?<div className="admin-card-list">{q.data.map(user=><Link to={'/super-admin/users/'+user.Id} key={str(user.Id)}><div><strong>{str(user.FirstName)} {str(user.LastName)}</strong><small>{str(user.Email)} · #{str(user.AuditId)}</small></div><span>{str(user.AccountStatus)}</span></Link>)}</div>:<Empty/>}</section>}
export function AdminCommunities(){const q=useQuery({queryKey:['/super-admin/communities'],queryFn:({signal})=>api.get<RecordData[]>('/super-admin/communities',signal)});if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;return <section className="admin-panel"><header><div><h2>Communities</h2><p>Platform directory, verification state and membership totals.</p></div></header><div className="admin-card-list">{q.data?.map(item=><Link to={'/super-admin/communities/'+item.Id} key={str(item.Id)}><div><strong>{str(item.Name)}</strong><small>{str(item.City)}, {str(item.Country)} · #{str(item.AuditId)}</small></div><span>{str(item.MemberCount)} members</span></Link>)}</div></section>}
export function AdminAccount(){const q=useQuery({queryKey:['/super-admin/account'],queryFn:({signal})=>api.get<RecordData>('/super-admin/account',signal)});if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;const user=q.data.user as RecordData;return <><section className="admin-panel"><h2>{str(user.FirstName)} {str(user.LastName)}</h2><p>Protected Super Admin · authenticator MFA {user.TwoFactorEnabled?'enabled':'required'}</p><AdminTable data={[user]}/></section><section className="admin-panel"><h2>Confirm password</h2><p>Confirmation opens a ten-minute window for password changes and session revocation.</p><MutationForm label="Confirm password" onSubmit={data=>api.send('/super-admin/password/confirm',{password:data.password})}><Field name="password" label="Current password" type="password"/></MutationForm></section><section className="admin-panel"><h2>Change protected password</h2><p>Requires recent authenticator and password confirmation. Other sessions are revoked and the change is written to the security audit.</p><MutationForm label="Change password" onSubmit={data=>{if(data.password!==data.confirmPassword)throw Error('Passwords do not match.');return api.send('/super-admin/account/password',{password:data.password},'PUT')}}><Field name="password" label="New password" type="password"/><Field name="confirmPassword" label="Confirm new password" type="password"/></MutationForm></section><section className="admin-panel"><h2>Active sessions</h2><Action danger run={()=>api.send('/super-admin/account/sessions',{},'DELETE')}>Revoke all other sessions</Action><AdminTable data={rows(q.data.sessions)}/></section><section className="admin-panel"><h2>Security activity</h2><AdminTable data={rows(q.data.activity)}/></section></>}

