import {HeaderSearch} from './HeaderSearch';
import {useState,useEffect,useRef} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,CalendarDays,MapPin,Clock,QrCode,Search,History,Download,Square,CheckCircle2,Users,HelpCircle,X,XCircle,ChevronDown} from 'lucide-react';
import {Capacitor} from '@capacitor/core';
import {Filesystem,Directory,Encoding} from '@capacitor/filesystem';
import {Share} from '@capacitor/share';
import {api,str,rows,type RecordData} from './api';
import {ErrorBox,Loading} from './ui';
import {getLocale} from './i18n';
import {AttendanceScanner} from './AttendanceScanner';
function MemberAvatar({person}:{person:RecordData}){const[failed,setFailed]=useState(false);return <span className="take-avatar" aria-hidden="true">{person.ProfileImage&&!failed?<img src={api.asset(str(person.ProfileImage))} alt="" onError={()=>setFailed(true)}/>:str(person.FirstName).slice(0,1)+str(person.LastName).slice(0,1)}</span>}
const time=(v:unknown)=>new Date(str(v)).toLocaleTimeString(getLocale(),{hour:'2-digit',minute:'2-digit'});
export async function exportAttendance(m:RecordData,people:RecordData[]){const cell=(v:unknown)=>'"'+str(v).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"',csv='\uFEFF'+[['Meeting','Name','Member ID','Status','Recorded at','Method'],...people.map(p=>[m.Title,str(p.FirstName)+' '+str(p.LastName),p.CardNumber,p.Status||'ABSENT',p.CheckedInAt,p.CheckInMethod])].map(row=>row.map(cell).join(',')).join('\r\n'),name='meeting-attendance.csv';if(Capacitor.isNativePlatform()){const file=await Filesystem.writeFile({path:name,data:csv,directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:'Attendance',files:[file.uri]})}else{const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
export function TakeAttendance({id,allowed,close}:{id:string;allowed:boolean;close:()=>void}){const[chosen,setChosen]=useState(''),[finished,setFinished]=useState<string[]>([]),[now,setNow]=useState(Date.now);useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);const q=useQuery({queryKey:['/communities/'+id+'/attendance/manage'],queryFn:()=>api.get<RecordData>('/communities/'+id+'/attendance/manage'),enabled:allowed,refetchInterval:10000});const meetings=rows(q.data?.meetings).filter(m=>Date.parse(str(m.EndDateTime))>now&&m.IsActive!==false&&m.IsActive!==0&&!finished.includes(str(m.Id))),selected=meetings.find(m=>m.Id===chosen)||meetings[0];return <div className="take-attendance">{!allowed?<p>This page is available to active community members.</p>:q.isPending?<Loading/>:q.error?<ErrorBox error={q.error}/>:<>{meetings.length>1&&<label className="take-meeting-picker">Meeting<select value={str(selected?.Id)} onChange={e=>setChosen(e.target.value)}>{meetings.map(m=><option key={str(m.Id)} value={str(m.Id)}>{str(m.Title)} · {new Date(str(m.StartDateTime)).toLocaleDateString(getLocale())}</option>)}</select></label>}{selected?<AttendanceSession key={str(selected.Id)} id={str(selected.Id)} communityId={id} onClosed={()=>setFinished(ids=>[...ids,str(selected.Id)])}/>:<p>Ready for the next meeting. No open or upcoming attendance sessions are available.</p>}</>}</div>}
function AttendanceSession({id,communityId,onClosed}:{id:string;communityId:string;onClosed:()=>void}){const base='/meetings/'+id+'/attendance',qc=useQueryClient(),[tab,setTab]=useState('scan'),[search,setSearch]=useState(''),[limit,setLimit]=useState(8),[recentMinutes,setRecentMinutes]=useState(0),[error,setError]=useState<unknown>(),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[help,setHelp]=useState(false),[now,setNow]=useState(Date.now),clockOffset=useRef(0),[endConfirm,setEndConfirm]=useState(false),operation=useRef(false);
 const q=useQuery({queryKey:[base,'manage'],queryFn:async()=>{await api.send(base+'/open');const result=await api.get<RecordData>(base);if(result.serverNow){clockOffset.current=Date.parse(str(result.serverNow))-Date.now();setNow(Date.now()+clockOffset.current)}return result},refetchInterval:10000,retry:false});useEffect(()=>{const update=()=>setNow(Date.now()+clockOffset.current),tick=setInterval(update,1000);window.addEventListener('focus',update);document.addEventListener('visibilitychange',update);return()=>{clearInterval(tick);window.removeEventListener('focus',update);document.removeEventListener('visibilitychange',update)}},[]);
 const m=(q.data?.meeting as RecordData)||{},people=rows(q.data?.participants),start=Date.parse(str(m.StartDateTime)),end=Date.parse(str(m.EndDateTime)),remaining=Math.max(0,Math.ceil((end-now)/1000)),beforeStart=now<start,closed=!m.IsActive||!Number.isFinite(remaining)||remaining<=0,canCheckIn=!closed&&!beforeStart,staff=!!q.data?.canManage;
 const present=(p:RecordData)=>['PRESENT','LATE'].includes(str(p.Status)),checked=people.filter(present),card=checked.filter(p=>p.CheckInMethod==='CARD'),recent=checked.filter(p=>(!recentMinutes||Date.parse(str(p.CheckedInAt))>=now-recentMinutes*60000)).sort((a,b)=>Date.parse(str(b.CheckedInAt))-Date.parse(str(a.CheckedInAt))),absent=people.filter(p=>!present(p)),list=(tab==='absent'?absent:tab==='recent'?recent:card).filter(p=>[p.FirstName,p.LastName,p.CardNumber,p.Phone,p.Email].map(str).join(' ').toLowerCase().includes(search.toLowerCase()));
 async function refresh(){await qc.invalidateQueries({queryKey:[base]});await qc.invalidateQueries({queryKey:['/communities/'+communityId+'/attendance']})}
 async function act(path:string,body:unknown={},success='Attendance updated.'){if(operation.current)return;operation.current=true;setBusy(true);setError(undefined);try{const result=await api.send(path,body);setMessage(result.alreadyCheckedIn?'This member is already checked in.':success);await refresh()}catch(e){setError(e)}finally{operation.current=false;setBusy(false)}}
 async function scan(payload:string){if(!canCheckIn||busy)return;await act('/communities/'+communityId+'/check-in',{meetingId:id,qrPayload:payload},'Membership card checked in.');}
 useEffect(()=>{if(q.data&&closed)onClosed()},[q.data,closed]);
 if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;if(!staff)return <p>You do not have access to take attendance.</p>;if(closed)return null;
 return <><div className="take-subheading"><h2>{str(m.Title)}</h2><button aria-expanded={help} onClick={()=>setHelp(!help)}><HelpCircle size={18}/>Help</button></div>{help&&<p className="take-help">Attendance opens at the scheduled start time. Scan QR Code lists membership-card scans; Recent Check-ins lists all recorded attendees, including meeting-code, QR and manual entries. Absent lists eligible members who have not checked in. Attendance closes at the scheduled end time or when you choose End Attendance.</p>}<ErrorBox error={error}/>{message&&<p role="status" className="take-message">{message}</p>}<section className="take-summary"><div className="take-schedule"><CalendarDays/><div><strong>{new Date(str(m.StartDateTime)).toLocaleDateString(getLocale(),{weekday:'short',day:'numeric',month:'short',year:'numeric'})} · {time(m.StartDateTime)} – {time(m.EndDateTime)}</strong><p><MapPin size={16}/>{str(m.Location)||'Online meeting'}</p></div></div><div className="take-code"><strong>{closed?'Attendance closed':'Meeting Code'}</strong>{closed?<p>The meeting code is no longer valid.</p>:<><div className="take-code-line"><div className="take-code-digits" aria-label={'Meeting code '+str(m.AttendanceCode)}>{str(m.AttendanceCode).split('').map((digit,i)=><b key={i}>{digit}</b>)}</div><span className="take-countdown"><Clock size={18}/>{beforeStart?'Opens at':'Closes in'}<strong>{beforeStart?time(m.StartDateTime):<>{Math.floor(remaining/3600)>0?String(Math.floor(remaining/3600))+':':''}{String(Math.floor(remaining/60)%60).padStart(2,'0')}:{String(remaining%60).padStart(2,'0')}</>}</strong></span></div><p>{beforeStart?'Check-in and the countdown begin when the meeting starts.':'Members enter this code to mark their attendance.'}</p></>}</div><div className="take-overview"><div className="take-list-heading"><h3>Recent Check-ins</h3><select aria-label="Check-in time range" value={recentMinutes} onChange={e=>{setRecentMinutes(Number(e.target.value));setLimit(8)}}><option value="0">All time</option><option value="15">Last 15 minutes</option><option value="60">Last hour</option></select></div><p className="take-recent-description">All recorded attendees, including meeting-code, QR and manual check-ins.</p><div className="take-stats">{([['Total check-ins',recent.filter(p=>p.Status!=='ABSENT').length,Users],['Present',recent.filter(p=>p.Status==='PRESENT').length,CheckCircle2],['Late',recent.filter(p=>p.Status==='LATE').length,Clock]] as const).map(([label,count,Icon])=><div key={label}><Icon size={23}/><strong>{count}</strong><span>{label}</span></div>)}</div></div></section><nav className="take-tabs" aria-label="Take attendance tools">{([['scan','Scan QR Code'],['recent','Recent Check-ins'],['absent','Absent']] as const).map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>{setTab(key);setLimit(8);setSearch('')}}>{label}</button>)}</nav>

{tab==='scan'&&canCheckIn&&!busy&&<AttendanceScanner onScan={scan}/>}{tab==='scan'&&closed&&<p className="take-help" role="status">Attendance has ended. You can review and export the records below.</p>}
{<HeaderSearch label="Search"><div className="take-search"><Search size={18}/><input aria-label="Search members" placeholder="Search name, member ID, phone or email" value={search} onChange={e=>{setSearch(e.target.value);setLimit(8)}}/>{search&&<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={18}/></button>}</div></HeaderSearch>}

{tab==='absent'&&<p className="take-recent-description">{beforeStart?'The meeting has not started. These members have not checked in yet.':'Eligible members with no present or late attendance record for this meeting.'}</p>}
<section className="take-members"><div className="take-list-heading"><h3>{tab==='absent'?'Absent':tab==='recent'?'Recent Check-ins':'Membership-card Scans'} ({list.length})</h3></div>
{list.slice(0,limit).map(p=><div className="take-member" key={str(p.UserId)}><MemberAvatar person={p}/><div className="take-member-info"><strong>{str(p.FirstName)} {str(p.LastName)}</strong><span>{str(p.CardNumber)||'Community member'}</span>{tab==='absent'&&!!(p.Email||p.Phone)&&<small>{[p.Email,p.Phone].filter(Boolean).map(str).join(' · ')}</small>}{!!p.CheckedInAt&&<small>{p.Status==='ABSENT'?'Recorded':'Checked in'} {time(p.CheckedInAt)} · {p.CheckInMethod==='CARD'?'QR code':p.CheckInMethod==='CODE'?'Meeting code':'Manual'}</small>}</div><div className="take-member-actions"><span className={'take-status '+str(p.Status).toLowerCase()}>{p.Status==='LATE'?'Late':p.Status==='PRESENT'?'Present':p.Status==='ABSENT'?'Absent':'Absent'}</span></div></div>)}
{!list.length&&<p className="take-empty">{search?'No members match your search.':'No attendance records to show.'}</p>}{tab==='recent'&&(recentMinutes>0||list.length>limit)&&<button className="take-load" onClick={()=>{setRecentMinutes(0);setLimit(people.length)}}>View all check-in history</button>}{tab!=='recent'&&list.length>limit&&<button className="take-load" onClick={()=>setLimit(limit+16)}>Load more {tab==='absent'?'members':'check-ins'}<ChevronDown size={16}/></button>}</section>
<footer className="take-footer"><button disabled={busy} onClick={()=>void exportAttendance(m,people).catch(setError)}><Download size={18}/>Export attendance</button><button className="primary" disabled={!canCheckIn||busy} onClick={()=>setEndConfirm(true)}><Square size={16}/>{closed?'Attendance closed':'End attendance'}</button></footer>{endConfirm&&canCheckIn&&<div className="take-confirm" role="alert"><p>End attendance now? The meeting code will stop working and attendance cannot be reopened.</p><button disabled={busy} onClick={()=>{setEndConfirm(false);void act(base+'/end',{},'Attendance closed. The meeting code is no longer valid.')}}>End attendance now</button><button disabled={busy} onClick={()=>setEndConfirm(false)}>Cancel</button></div>}</>;
}
