import {useState,useRef,useEffect} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {ShieldCheck,LockKeyhole,Smartphone,MessageCircle,HelpCircle,LifeBuoy,ChevronRight,ArrowLeft} from 'lucide-react';
import {api,session,str,type RecordData} from './api';
import {Action,Field,MutationForm,ErrorBox,Loading} from './ui';
import {VerificationCode} from './VerificationCode';

export function TwoFactorSettings(){
 const q=useQuery({queryKey:['/auth/two-factor'],queryFn:()=>api.get<RecordData>('/auth/two-factor')});
 const [method,setMethod]=useState('authenticator'),[flow,setFlow]=useState(''),[setup,setSetup]=useState<RecordData|null>(null),[challenge,setChallenge]=useState(''),[notice,setNotice]=useState('');
 const form=useRef<HTMLElement>(null),learn=useLocation().pathname==='/settings/two-factor/learn';
 useEffect(()=>{if(flow){form.current?.scrollIntoView({behavior:'smooth',block:'start'});form.current?.querySelector<HTMLInputElement>('input')?.focus({preventScroll:true})}},[flow]);
 function cancel(){setFlow('');setSetup(null);setChallenge('')}
 if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;
 const enabled=!!q.data.enabled,activeMethod=str(q.data.method),selected=enabled?activeMethod:method;
 function start(){setNotice('');setSetup(null);setChallenge('');setFlow(enabled?'disable':'setup')}
 if(learn)return <div className="two-factor-detail"><Link className="settings-back" to="/settings/two-factor"><ArrowLeft size={17}/>Two-Factor Authentication</Link><h2>How two-factor authentication works</h2><p>Sign in with your password, then enter a six-digit code from your selected method.</p><section className="card"><h3>Authenticator app</h3><p>Add the setup key to an authenticator using a time-based account. Enter its current code to finish setup. Keep your device’s date and time automatic, and keep the setup key private.</p></section><section className="card"><h3>SMS verification</h3><p>A verified phone number is required. CDA Connect sends a code when you sign in. If delivery fails, wait before requesting another code and check that your number is correct.</p><Link to="/settings/security/recovery">Manage recovery phone</Link></section><section className="card"><h3>Changing methods or losing access</h3><p>To change methods, verify your password and current code to turn off protection, then set up the other method. Recovery codes are not available in this build. Contact support if you lose access; support cannot display your password or authenticator secret.</p><Link className="button secondary" to="/settings/support">Get setup help</Link></section></div>;
 return <div className="privacy-dashboard two-factor-dashboard"><p>Add an extra layer of security to protect your account.</p><p className="privacy-status" role="status">{notice}</p>
 <section className="two-factor-hero"><ShieldCheck size={56}/><div><h2>Stronger security for your account</h2><p>When enabled, you’ll need a verification code in addition to your password to sign in.</p><span className="two-factor-badge">Status: {enabled?'ON':'OFF'}</span></div><label className="account-switch-row two-factor-switch"><span className="sr-only">Two-factor authentication</span><input type="checkbox" role="switch" checked={enabled} disabled={!!flow} onChange={start}/></label></section>
 <section className="settings-group"><h2>How it works</h2><div className="two-factor-steps">{[[LockKeyhole,'Enter your password','Use your usual password to sign in.'],[Smartphone,'Verify it’s you','Enter a code from your authenticator app or SMS.'],[ShieldCheck,'Access your account','Continue after your code is verified.']].map(([Icon,title,text],i)=>{const Symbol=Icon as typeof LockKeyhole;return <div key={i}><span className="two-factor-number">{i+1}</span><Symbol size={32}/><strong>{title as string}</strong><p>{text as string}</p></div>})}</div></section>
 <section className="settings-group"><h2>Choose your method</h2><div className="settings-list">{[['authenticator','Authenticator App','Use a time-based authenticator app to generate verification codes.',Smartphone],['sms','SMS Verification','Receive verification codes on your verified mobile number.',MessageCircle]].map(([value,title,text,Icon])=>{const Symbol=Icon as typeof Smartphone;return <label className="settings-row two-factor-choice" key={value as string}><span className="settings-row-icon"><Symbol size={24}/></span><span className="settings-row-text"><strong>{title as string}</strong><small>{text as string}</small>{value==='sms'&&!q.data.phoneVerified&&<small>Verify your phone before choosing SMS.</small>}</span><input type="radio" name="twoFactorMethod" value={value as string} checked={selected===value} disabled={enabled||!!flow||(value==='sms'&&!q.data.phoneVerified)} onChange={()=>setMethod(value as string)}/></label>})}</div>{!q.data.phoneVerified&&<Link className="notification-help" to="/settings/security/recovery">Verify your phone number</Link>}{enabled&&<p className="privacy-note">To change methods, turn off protection using your current code, then set up your new method.</p>}</section>
 {!!flow&&<section ref={form} className="card two-factor-setup" aria-label={flow==='setup'?'Set up two-factor authentication':'Turn off two-factor authentication'}><h2>{flow==='setup'?'Verify to enable protection':'Verify to turn off protection'}</h2><p>Your status stays {enabled?'ON':'OFF'} until verification succeeds.</p>
 {flow==='setup'&&!setup&&<MutationForm label="Continue setup" onSubmit={async d=>setSetup(await api.send<RecordData>('/auth/two-factor/setup',{...d,method}))}><Field name="password" label="Current password" type="password"/></MutationForm>}
 {flow==='setup'&&setup&&<><p>{setup.method==='sms'?'Enter the code sent to '+str(setup.maskedPhone)+'.':'Add this private setup key to your authenticator as a time-based account, then enter its current six-digit code.'}</p>{!!setup.secret&&<code className="settings-secret">{str(setup.secret)}</code>}<MutationForm label="Verify and enable" onSuccess={()=>{cancel();setNotice('Two-factor authentication enabled.')}} onSubmit={d=>api.send('/auth/two-factor/enable',{...d,method:setup.method,secret:setup.secret,challengeId:setup.challengeId})}><Field name="password" label="Confirm current password" type="password"/><VerificationCode/></MutationForm></>}
 {flow==='disable'&&(activeMethod==='sms'&&!challenge?<Action run={async()=>{const r=await api.send<RecordData>('/auth/two-factor/sms-code',{purpose:'disable'});setChallenge(str(r.challengeId))}}>Send verification code</Action>:<MutationForm label="Verify and disable" onSuccess={()=>{cancel();setNotice('Two-factor authentication disabled.')}} onSubmit={d=>api.send('/auth/two-factor/disable',{...d,challengeId:challenge||undefined})}><Field name="password" label="Current password" type="password"/><VerificationCode/></MutationForm>)}
 <button className="secondary" type="button" onClick={cancel}>Cancel</button><p className="privacy-note">Changing protection revokes other refresh sessions. Existing access tokens remain valid until expiry.</p></section>}
 <section className="privacy-safety"><ShieldCheck size={36}/><div><strong>Keep your account safe</strong><p>Two-factor authentication adds another verification step, even if someone knows your password.</p></div></section>
 <section className="settings-group"><h2>Need help?</h2><div className="settings-list"><Link className="settings-row" to="/settings/two-factor/learn"><HelpCircle size={22}/><span className="settings-row-text">Learn more about two-factor authentication</span><ChevronRight size={17}/></Link><Link className="settings-row" to="/settings/support"><LifeBuoy size={22}/><span className="settings-row-text">Get help setting it up</span><ChevronRight size={17}/></Link></div></section>
 {!flow&&<button className={enabled?'secondary':'primary'} onClick={start}><LockKeyhole size={18}/>{enabled?'Turn Off Two-Factor Authentication':'Enable Two-Factor Authentication'}</button>}</div>;
}
