import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { api } from '@/lib/api';
import { useCommunity } from '@/store/community';
import { Badge, Card, EmptyState, Header, Muted, Screen } from '@/components/UI';
import { colors } from '@/theme';
import type { Meeting } from '@/types';

export default function Calendar(){const c=useCommunity(s=>s.current);const{data=[]}=useQuery<Meeting[]>({queryKey:['meetings',c?.Id],enabled:!!c,queryFn:async()=>(await api.get(`/communities/${c!.Id}/meetings`)).data});const now=new Date();const[cursor,setCursor]=useState(new Date(now.getFullYear(),now.getMonth(),1));const days=['M','T','W','T','F','S','S'];return <Screen scroll><Header title="Calendar" subtitle={c?.Name||'Select a community'} right={c?<Pressable onPress={()=>router.push(`/community/${c.Id}/manage`)} style={styles.add}><Ionicons name="add" size={23} color="#fff"/></Pressable>:undefined}/><Card><View style={styles.monthHeader}><Text style={styles.month}>{cursor.toLocaleString('en',{month:'long',year:'numeric'})}</Text><View style={styles.arrows}><Pressable onPress={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><Ionicons name="chevron-back" size={20} color={colors.muted}/></Pressable><Pressable onPress={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><Ionicons name="chevron-forward" size={20} color={colors.muted}/></Pressable></View></View><View style={styles.grid}>{days.map((d,i)=><Text key={i} style={styles.weekday}>{d}</Text>)}{Array.from({length:42},(_,i)=>{const offset=(new Date(cursor.getFullYear(),cursor.getMonth(),1).getDay()+6)%7;const d=i-offset+1;const max=new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate();const active=d===now.getDate()&&cursor.getMonth()===now.getMonth()&&cursor.getFullYear()===now.getFullYear();return <View key={i} style={[styles.date,active&&styles.activeDate]}><Text style={[styles.dateText,active&&{color:'#fff'}]}>{d>0&&d<=max?d:''}</Text></View>})}</View></Card><Text style={styles.upcoming}>Upcoming</Text>{!c?<EmptyState icon="calendar-outline" title="No community selected" body="Select a community to see its meetings."/>:data.length?data.map(m=><Card key={m.Id} style={styles.meeting}><View style={styles.marker}/><View style={{flex:1}}><Text style={styles.title}>{m.Title}</Text><Muted>{new Date(m.StartDateTime).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}</Muted><Muted>{m.Location||'Location not specified'}</Muted></View>{m.MyResponse&&<Badge text={m.MyResponse.replace('_',' ')} tone={m.MyResponse==='GOING'?'green':'gray'}/>}</Card>):<EmptyState icon="calendar-clear-outline" title="Nothing scheduled" body="Upcoming meetings and community events will appear here."/>}</Screen>}
const styles=StyleSheet.create({add:{width:38,height:38,borderRadius:19,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},monthHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:14},month:{fontSize:18,fontWeight:'900',color:colors.text},arrows:{flexDirection:'row',gap:14},grid:{flexDirection:'row',flexWrap:'wrap'},weekday:{width:'14.28%',textAlign:'center',fontSize:11,fontWeight:'800',color:colors.muted,paddingVertical:6},date:{width:'14.28%',height:38,alignItems:'center',justifyContent:'center'},activeDate:{backgroundColor:colors.primary,borderRadius:12},dateText:{fontSize:13,color:colors.text,fontWeight:'700'},upcoming:{fontSize:18,fontWeight:'900',color:colors.text,marginBottom:12,marginTop:6},meeting:{flexDirection:'row',gap:12,alignItems:'flex-start'},marker:{width:4,height:'100%',minHeight:52,borderRadius:4,backgroundColor:colors.primary},title:{fontSize:15,fontWeight:'900',color:colors.text}})
