import {useMemo,useState} from 'react';
import {Alert,Platform,Pressable,Share,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {useQuery} from '@tanstack/react-query';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import * as Location from 'expo-location';
import {api} from '@/lib/api';
import {useAuth} from '@/store/auth';
import {Avatar,Badge,Button,Card,EmptyState,Muted,Screen,useAppTheme} from '@/components/UI';

const tabs=['Overview','Activity','Groups','Posts','Saved','Settings'] as const;
type Tab=typeof tabs[number];

export default function Profile(){
 const{user,logout}=useAuth();const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=980;const[tab,setTab]=useState<Tab>('Overview');const[deviceLocation,setDeviceLocation]=useState('');const[locating,setLocating]=useState(false);
 const communities=useQuery<any[]>({queryKey:['communities'],queryFn:async()=>(await api.get('/communities')).data});
 const activity=useQuery<any[]>({queryKey:['personal-activity'],queryFn:async()=>(await api.get('/me/activity')).data});
 const name=`${user?.FirstName||''} ${user?.LastName||''}`.trim()||'Community Member';const location=deviceLocation||(user as any)?.City||(user as any)?.State||(user as any)?.Country||'Location not added';const items=activity.data||[];const groups=communities.data||[];
 const stats=useMemo(()=>[{label:'Groups',value:groups.length,icon:'people',route:'/(tabs)/communities'},{label:'Posts',value:items.filter(x=>x.ItemType==='POST'||x.Type==='POST').length,icon:'newspaper',route:'/notifications'},{label:'Activity',value:items.length,icon:'chatbubbles',route:'/notifications'}],[groups,items]);
 async function updateLocation(){setLocating(true);try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted'){Alert.alert('Location permission','Allow location access to update your profile location.');return}const position=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});const place=(await Location.reverseGeocodeAsync(position.coords))[0];setDeviceLocation([place?.city||place?.district,place?.region,place?.country].filter(Boolean).join(', ')||`${position.coords.latitude.toFixed(4)}, ${position.coords.longitude.toFixed(4)}`)}catch{Alert.alert('Location unavailable','CDA Connect could not determine your location.')}finally{setLocating(false)}}
 const share=()=>Share.share({title:`${name} on CDA Connect`,message:`Connect with ${name} on CDA Connect.`});
 const openCard=()=>groups[0]?.Id?router.push(`/community/${groups[0].Id}/membership-card` as any):Alert.alert('Membership card','Join a community to create your membership card.');
 return <Screen scroll contentStyle={desktop?s.desktop:undefined}>
  <View style={[s.hero,{backgroundColor:palette.navy}]}><View style={s.heroPattern}/></View>
  <View style={[s.identity,!desktop&&s.identityMobile]}><View><Avatar name={name} size={desktop?116:92}/><Pressable accessibilityLabel="Change profile photo" onPress={()=>router.push('/profile-edit')} style={[s.camera,{backgroundColor:palette.surface,borderColor:palette.border}]}><Ionicons name="camera" size={16} color={palette.navy}/></Pressable></View><View style={s.identityText}><View style={s.nameRow}><Text style={[s.name,{color:palette.text}]}>{name}</Text><Ionicons name="checkmark-circle" size={20} color={palette.success}/></View><Muted>{user?.Email||'CDA Connect member'}</Muted><View style={s.meta}><Badge text="Active Member" tone="green"/><Pressable onPress={updateLocation} style={s.metaItem}><Ionicons name="location" size={15} color={palette.success}/><Muted>{locating?'Finding location…':location}</Muted></Pressable></View></View><View style={s.profileActions}><Button title="Edit Profile" icon="create-outline" variant="secondary" onPress={()=>router.push('/profile-edit')}/><Pressable accessibilityLabel="More profile options" onPress={()=>setTab('Settings')} style={[s.more,{borderColor:palette.border}]}><Ionicons name="ellipsis-horizontal" size={22} color={palette.text}/></Pressable></View></View>
  {!desktop?<View style={s.mobileActions}><Action icon="create-outline" label="Edit Profile" onPress={()=>router.push('/profile-edit')}/><Action icon="qr-code-outline" label="QR Card" onPress={openCard}/><Action icon="share-outline" label="Share Profile" onPress={share}/><Action icon="ellipsis-horizontal" label="More" onPress={()=>setTab('Settings')}/></View>:null}
  <View style={[s.tabs,{borderBottomColor:palette.border}]}>{tabs.map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&{borderBottomColor:palette.success}]}><Text style={{color:tab===x?palette.success:palette.muted,fontWeight:'800'}}>{x}</Text></Pressable>)}</View>
  {tab==='Overview'?<Overview desktop={desktop} user={user as any} name={name} location={location} stats={stats} groups={groups} activity={items} palette={palette}/>:tab==='Groups'?<Groups groups={groups} palette={palette}/>:tab==='Activity'||tab==='Posts'||tab==='Saved'?<Activity items={items} mode={tab} palette={palette}/>:<Settings logout={logout} palette={palette}/>} 
 </Screen>
}

function Overview({desktop,user,name,location,stats,groups,activity,palette}:{desktop:boolean;user:any;name:string;location:string;stats:any[];groups:any[];activity:any[];palette:any}){return <View style={[s.columns,!desktop&&s.stack]}><View style={{flex:1}}><Card><Text style={[s.heading,{color:palette.text}]}>About Me</Text><Text style={[s.body,{color:palette.text}]}>{user?.Bio||'Community member helping to build safer, stronger and more connected neighbourhoods.'}</Text><Info icon="mail" text={user?.Email||'Email not added'}/><Info icon="call" text={user?.Phone||'Phone number not added'}/><Info icon="location" text={location}/></Card><Card><View style={s.sectionHead}><Text style={[s.heading,{color:palette.text}]}>My Groups</Text><Pressable onPress={()=>router.push('/(tabs)/communities')}><Text style={[s.link,{color:palette.success}]}>View all</Text></Pressable></View>{groups.slice(0,4).map(g=><Pressable key={g.Id} onPress={()=>router.push(`/community/${g.Id}` as any)} style={s.groupRow}><Avatar name={g.Name} size={38}/><Text style={[s.groupName,{color:palette.text}]}>{g.Name}</Text><Badge text={g.UserRole||'Member'} tone={g.UserRole==='Admin'?'green':'gray'}/><Ionicons name="chevron-forward" size={18} color={palette.muted}/></Pressable>)}{!groups.length?<Muted>No communities joined yet.</Muted>:null}</Card></View><View style={{flex:1}}><Card><Text style={[s.heading,{color:palette.text}]}>Community Stats</Text><View style={s.stats}>{stats.map(x=><Pressable key={x.label} onPress={()=>router.push(x.route as any)} style={s.stat}><View style={[s.statIcon,{backgroundColor:palette.primarySoft}]}><Ionicons name={x.icon} size={22} color={palette.primary}/></View><Text style={[s.statValue,{color:palette.text}]}>{x.value}</Text><Muted>{x.label}</Muted></Pressable>)}</View></Card><Card><View style={s.sectionHead}><Text style={[s.heading,{color:palette.text}]}>Recent Activity</Text><Pressable onPress={()=>router.push('/notifications' as any)}><Text style={[s.link,{color:palette.success}]}>View all</Text></Pressable></View>{activity.slice(0,4).map((x,i)=><Pressable key={x.Id||i} onPress={()=>x.CommunityId&&router.push(`/community/${x.CommunityId}/feed` as any)} style={s.activityRow}><View style={[s.activityIcon,{backgroundColor:palette.successSoft}]}><Ionicons name="sparkles" size={18} color={palette.success}/></View><View style={{flex:1}}><Text style={[s.activityTitle,{color:palette.text}]}>{x.Title||x.Body||'Community activity'}</Text><Muted>{x.CommunityName||'CDA Connect'}{x.CreatedAt?` · ${new Date(x.CreatedAt).toLocaleDateString()}`:''}</Muted></View><Ionicons name="chevron-forward" size={18} color={palette.muted}/></Pressable>)}{!activity.length?<Muted>No recent activity.</Muted>:null}</Card></View></View>}
function Groups({groups,palette}:{groups:any[];palette:any}){return <View>{groups.length?groups.map(g=><Pressable key={g.Id} onPress={()=>router.push(`/community/${g.Id}` as any)}><Card style={s.listCard}><Avatar name={g.Name}/><View style={{flex:1}}><Text style={[s.groupName,{color:palette.text}]}>{g.Name}</Text><Muted>{[g.City,g.Country].filter(Boolean).join(', ')||'Community workspace'}</Muted></View><Badge text={g.UserRole||'Member'} tone="green"/><Ionicons name="chevron-forward" size={20} color={palette.muted}/></Card></Pressable>):<EmptyState icon="people-outline" title="No groups" body="Communities you join will appear here."/>}</View>}
function Activity({items,mode,palette}:{items:any[];mode:Tab;palette:any}){const data=mode==='Posts'?items.filter(x=>x.ItemType==='POST'||x.Type==='POST'):items;return <View>{data.length?data.map((x,i)=><Pressable key={x.Id||i} onPress={()=>x.CommunityId&&router.push(`/community/${x.CommunityId}/feed` as any)}><Card><Text style={[s.activityTitle,{color:palette.text}]}>{x.Title||x.Body||`${mode} item`}</Text><Muted>{x.CommunityName||'CDA Connect'}{x.CreatedAt?` · ${new Date(x.CreatedAt).toLocaleString()}`:''}</Muted></Card></Pressable>):<EmptyState icon={mode==='Saved'?'bookmark-outline':'newspaper-outline'} title={`No ${mode.toLowerCase()} yet`} body={`${mode} will appear here as you use CDA Connect.`}/>}</View>}
function Settings({logout,palette}:{logout:()=>Promise<void>;palette:any}){const rows=[['settings-outline','App Settings','/(tabs)/settings'],['notifications-outline','Notification Settings','/notifications-settings'],['lock-closed-outline','Privacy Centre','/privacy'],['accessibility-outline','Accessibility & Language','/accessibility']];return <Card>{rows.map(([icon,label,path])=><Pressable key={label} onPress={()=>router.push(path as any)} style={[s.setting,{borderBottomColor:palette.border}]}><Ionicons name={icon as any} size={22} color={palette.primary}/><Text style={[s.settingText,{color:palette.text}]}>{label}</Text><Ionicons name="chevron-forward" size={19} color={palette.muted}/></Pressable>)}<Pressable onPress={async()=>{await logout();router.replace('/(auth)/welcome')}} style={s.setting}><Ionicons name="log-out-outline" size={22} color={palette.danger}/><Text style={[s.settingText,{color:palette.danger}]}>Log out</Text></Pressable></Card>}
function Action({icon,label,onPress}:{icon:keyof typeof Ionicons.glyphMap;label:string;onPress:()=>void}){const{palette}=useAppTheme();return <Pressable onPress={onPress} style={s.action}><View style={[s.actionIcon,{borderColor:palette.border}]}><Ionicons name={icon} size={21} color={palette.navy}/></View><Text style={[s.actionText,{color:palette.text}]}>{label}</Text></Pressable>}
function Info({icon,text}:{icon:keyof typeof Ionicons.glyphMap;text:string}){const{palette}=useAppTheme();return <View style={s.info}><Ionicons name={icon} size={17} color={palette.success}/><Muted style={{flex:1}}>{text}</Muted></View>}

const s=StyleSheet.create({desktop:{paddingTop:0},hero:{height:150,marginHorizontal:-24,marginTop:-8,borderBottomLeftRadius:18,borderBottomRightRadius:18,overflow:'hidden'},heroPattern:{position:'absolute',left:'30%',right:'10%',bottom:-70,height:150,borderRadius:100,backgroundColor:'rgba(21,128,61,.35)'},identity:{marginTop:-54,flexDirection:'row',alignItems:'flex-end',gap:20,paddingHorizontal:24,marginBottom:22},identityMobile:{flexDirection:'column',alignItems:'center',marginTop:-45,paddingHorizontal:0,gap:10},camera:{position:'absolute',right:0,bottom:4,width:34,height:34,borderRadius:17,borderWidth:2,alignItems:'center',justifyContent:'center'},identityText:{flex:1},nameRow:{flexDirection:'row',alignItems:'center',gap:7},name:{fontSize:25,fontWeight:'900'},meta:{flexDirection:'row',alignItems:'center',gap:12,flexWrap:'wrap',marginTop:10},metaItem:{flexDirection:'row',alignItems:'center',gap:4},profileActions:{flexDirection:'row',alignItems:'center',gap:9},more:{width:46,height:46,borderWidth:1,borderRadius:11,alignItems:'center',justifyContent:'center'},mobileActions:{flexDirection:'row',justifyContent:'space-around',marginVertical:12},action:{alignItems:'center',width:78,gap:5},actionIcon:{width:48,height:48,borderRadius:24,borderWidth:1,alignItems:'center',justifyContent:'center'},actionText:{fontSize:10,fontWeight:'800',textAlign:'center'},tabs:{flexDirection:'row',borderBottomWidth:1,marginBottom:18,overflow:'scroll'},tab:{paddingHorizontal:15,paddingVertical:14,borderBottomWidth:3,borderBottomColor:'transparent'},columns:{flexDirection:'row',gap:16,alignItems:'flex-start'},stack:{flexDirection:'column'},heading:{fontSize:18,fontWeight:'900',marginBottom:12},body:{fontSize:14,lineHeight:22,marginBottom:12},info:{flexDirection:'row',alignItems:'center',gap:9,marginTop:10},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:8},link:{fontWeight:'900'},stats:{flexDirection:'row',gap:8},stat:{flex:1,alignItems:'center',gap:5},statIcon:{width:46,height:46,borderRadius:13,alignItems:'center',justifyContent:'center'},statValue:{fontSize:20,fontWeight:'900'},groupRow:{minHeight:58,flexDirection:'row',alignItems:'center',gap:10},groupName:{fontWeight:'900',flex:1},activityRow:{minHeight:64,flexDirection:'row',alignItems:'center',gap:10},activityIcon:{width:38,height:38,borderRadius:12,alignItems:'center',justifyContent:'center'},activityTitle:{fontWeight:'900',marginBottom:4},listCard:{flexDirection:'row',alignItems:'center',gap:12},setting:{minHeight:62,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1},settingText:{flex:1,fontWeight:'800'}});
