import {Image,Pressable,Share,StyleSheet,Text,View,useWindowDimensions} from '@/platform/react-native';
import {router,useLocalSearchParams} from '@/router';
import {Ionicons} from '@/platform/icons';
import {useQuery} from '@tanstack/react-query';
import Svg,{Circle,Polyline} from '@/platform/svg';
import {api} from '@/lib/api';
import {Card,EmptyState,Muted,Screen,useAppTheme} from '@/components/UI';

type Item={Label:string;Value:number};type Option={Id:string;OptionText:string;ImageUrl?:string;VoteCount:number};
type Analysis={poll:{Id:string;Question:string;Description?:string;ImageUrl?:string;CreatedAt:string;StartAt:string;EndAt?:string;CommunityName:string;EligibleMembers:number;CreatedByName:string;IsAnonymous:boolean;AllowMultiple:boolean;AllowChangeVote:boolean};summary:{totalVoters:number;totalSelections:number;avgMinutesToVote:number|null;turnout:number};options:Option[];timeline:{VoteDate:string;Votes:number;CumulativeVotes:number}[];ageGroups:Item[];memberGroups:Item[];voters:{UserId:string;FirstName:string;LastName:string;ProfileImage?:string;Vote:string;VotedAt:string}[]};
const colors=['#0F8A43','#2563EB','#7C3AED','#F59E0B','#0891B2','#DC2626'];

export default function PollAnalysis(){const{id,pollId}=useLocalSearchParams<{id:string;pollId:string}>(),{palette}=useAppTheme(),{width}=useWindowDimensions();const query=useQuery<Analysis>({queryKey:['poll-analysis',pollId],queryFn:async()=>(await api.get(`/polls/${pollId}/analysis`)).data});
 if(query.isLoading)return <Screen contentStyle={s.page}><Muted>Loading poll analysis…</Muted></Screen>;
 if(query.isError||!query.data)return <Screen contentStyle={s.page}><EmptyState icon="lock-closed-outline" title="Analysis unavailable" body="Poll analysis is available only to community administrators and moderators."/></Screen>;
 const d=query.data,totalSelections=d.options.reduce((sum,x)=>sum+x.VoteCount,0),winner=[...d.options].sort((a,b)=>b.VoteCount-a.VoteCount)[0],ended=!!d.poll.EndAt&&new Date(d.poll.EndAt)<=new Date(),chartWidth=Math.max(250,Math.min(width-58,760));
 const average=d.summary.avgMinutesToVote==null?'No votes':formatDuration(d.summary.avgMinutesToVote);async function share(){await Share.share({title:`${d.poll.Question} analysis`,message:`${d.poll.Question}\n${d.summary.totalVoters} voters · ${d.summary.turnout}% turnout${winner?`\nLeading option: ${winner.OptionText} (${winner.VoteCount})`:''}`})}
 return <Screen scroll contentStyle={s.page}><View style={s.titleRow}><View style={{flex:1}}><Text style={[s.title,{color:palette.text}]}>Poll Analysis</Text><Muted>Live metrics and insights from recorded votes</Muted></View><Pressable accessibilityLabel="Share poll analysis" onPress={()=>void share()} style={[s.share,{borderColor:palette.border}]}><Ionicons name="share-outline" size={22} color={palette.text}/></Pressable></View>
 <Card style={s.hero}><View style={s.heroRow}>{d.poll.ImageUrl?<Image source={{uri:d.poll.ImageUrl}} style={s.heroImage}/>:<View style={[s.heroImage,s.placeholder,{backgroundColor:palette.successSoft}]}><Ionicons name="analytics" size={36} color={palette.success}/></View>}<View style={s.heroCopy}><Text style={[s.status,{color:palette.success,backgroundColor:palette.successSoft}]}>{ended?'Completed':'Active'}</Text><Text style={[s.question,{color:palette.text}]}>{d.poll.Question}</Text><Muted>{new Date(d.poll.CreatedAt).toLocaleDateString()} {d.poll.EndAt?`– ${new Date(d.poll.EndAt).toLocaleDateString()}`:''}</Muted></View></View><Pressable onPress={()=>router.push(`/community/${id}/poll/${pollId}/view` as any)} style={s.viewPoll}><Text style={{color:palette.success,fontWeight:'900'}}>View Poll</Text><Ionicons name="chevron-forward" size={18} color={palette.success}/></Pressable></Card>
 <View style={s.metrics}><Metric icon="people" label="Total Voters" value={String(d.summary.totalVoters)} note={`of ${d.poll.EligibleMembers} eligible`} palette={palette}/><Metric icon="pie-chart" label="Voter Turnout" value={`${d.summary.turnout}%`} note="eligible members" palette={palette}/><Metric icon="time" label="Avg. Time to Vote" value={average} note="from poll creation" palette={palette}/><Metric icon="checkbox" label="Selections" value={String(d.summary.totalSelections)} note="recorded choices" palette={palette}/></View>
 <Card><Text style={[s.sectionTitle,{color:palette.text}]}>Results Overview</Text>{totalSelections?<><View style={s.donutWrap}><Donut values={d.options.map(x=>x.VoteCount)} total={totalSelections}/><View><Text style={[s.donutTotal,{color:palette.text}]}>{totalSelections}</Text><Muted>Total selections</Muted></View></View>{d.options.map((x,i)=><Bar key={x.Id} label={x.OptionText} value={x.VoteCount} total={totalSelections} color={colors[i%colors.length]} palette={palette}/>)}</>:<Muted>No votes have been recorded yet.</Muted>}{winner&&winner.VoteCount>0?<View style={[s.insight,{backgroundColor:palette.successSoft}]}><Ionicons name="trophy-outline" size={24} color={palette.success}/><Text style={{color:palette.text,flex:1}}><Text style={{fontWeight:'900'}}>Leading result: </Text>{winner.OptionText} with {winner.VoteCount} selection{winner.VoteCount===1?'':'s'}.</Text></View>:null}</Card>
 <Card><Text style={[s.sectionTitle,{color:palette.text}]}>Votes Over Time</Text>{d.timeline.length?<LineChart data={d.timeline} width={chartWidth} color={palette.success} muted={palette.muted}/>:<Muted>The timeline will appear after the first vote.</Muted>}</Card>
 <View style={s.split}><GroupCard title="Voter Age Ranges" items={d.ageGroups} palette={palette}/><GroupCard title="Votes by Membership Group" items={d.memberGroups} palette={palette}/></View>
 <View style={[s.verified,{borderColor:palette.border}]}><Ionicons name="shield-checkmark-outline" size={18} color={palette.success}/><Muted>All figures are calculated from current verified database records.</Muted></View></Screen>}

function Metric({icon,label,value,note,palette}:any){return <Card style={s.metric}><View style={[s.metricIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={17} color={palette.success}/></View><Muted numberOfLines={2} style={s.metricLabel}>{label}</Muted><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.65} style={[s.metricValue,{color:palette.text}]}>{value}</Text><Muted numberOfLines={2} style={s.metricNote}>{note}</Muted></Card>}
function Bar({label,value,total,color,palette}:{label:string;value:number;total:number;color:string;palette:any}){const pct=total?Math.round(value/total*100):0;return <View style={s.barRow}><View style={s.barTop}><Text style={[s.barLabel,{color:palette.text}]}>{label}</Text><Text style={{color:palette.text,fontWeight:'800'}}>{pct}% ({value})</Text></View><View style={[s.track,{backgroundColor:palette.backgroundSoft}]}><View style={[s.fill,{backgroundColor:color,width:`${pct}%`}]}/></View></View>}
function Donut({values,total}:{values:number[];total:number}){const size=108,center=54,r=42,c=2*Math.PI*r;let offset=0;return <Svg width={size} height={size}><Circle cx={center} cy={center} r={r} fill="none" stroke="#E8EEF5" strokeWidth={10}/>{values.map((value,i)=>{const length=value/total*c,node=<Circle key={i} cx={center} cy={center} r={r} fill="none" stroke={colors[i%colors.length]} strokeWidth={10} strokeDasharray={`${length} ${c-length}`} strokeDashoffset={-offset} rotation="-90" origin={`${center},${center}`}/>;offset+=length;return node})}</Svg>}
function LineChart({data,width,color,muted}:{data:Analysis['timeline'];width:number;color:string;muted:string}){const h=190,p=24,max=Math.max(...data.map(x=>x.CumulativeVotes),1),usable=width-p*2,step=data.length>1?usable/(data.length-1):0,points=data.map((x,i)=>`${p+i*step},${h-p-x.CumulativeVotes/max*(h-p*2)}`).join(' ');return <View><Svg width={width} height={h}><Polyline points={`${p},${h-p} ${width-p},${h-p}`} stroke={muted} strokeWidth="1"/><Polyline points={points} fill="none" stroke={color} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>{data.map((x,i)=><Circle key={i} cx={p+i*step} cy={h-p-x.CumulativeVotes/max*(h-p*2)} r="4" fill={color}/>)}</Svg><View style={s.axis}>{data.map((x,i)=><Muted key={i} style={s.axisLabel}>{new Date(x.VoteDate).toLocaleDateString([],{month:'short',day:'numeric'})}</Muted>)}</View></View>}
function GroupCard({title,items,palette}:{title:string;items:Item[];palette:any}){const total=items.reduce((n,x)=>n+x.Value,0);return <Card style={s.group}><Text style={[s.sectionTitle,{color:palette.text}]}>{title}</Text>{items.length?items.map((x,i)=><Bar key={x.Label} label={x.Label} value={x.Value} total={total} color={colors[i%colors.length]} palette={palette}/>):<Muted>No data is available yet.</Muted>}</Card>}
function formatDuration(minutes:number){if(minutes<60)return`${minutes}m`;const hours=Math.floor(minutes/60),mins=minutes%60;return`${hours}h${mins?` ${mins}m`:''}`}
const s=StyleSheet.create({page:{width:'100%',maxWidth:900,alignSelf:'center',paddingBottom:125},titleRow:{flexDirection:'row',alignItems:'center',marginBottom:12},title:{fontSize:22,fontWeight:'900'},share:{width:40,height:40,borderWidth:1,borderRadius:13,alignItems:'center',justifyContent:'center'},hero:{gap:10},heroRow:{flexDirection:'row',alignItems:'center',gap:13},heroImage:{width:68,height:68,borderRadius:34},placeholder:{alignItems:'center',justifyContent:'center'},heroCopy:{flex:1,minWidth:0},status:{alignSelf:'flex-start',paddingHorizontal:9,paddingVertical:4,borderRadius:8,fontWeight:'800'},question:{fontSize:18,lineHeight:24,fontWeight:'900',marginVertical:6},viewPoll:{alignSelf:'flex-end',minHeight:40,flexDirection:'row',alignItems:'center'},metrics:{flexDirection:'row',flexWrap:'nowrap',gap:6},metric:{flex:1,minWidth:0,minHeight:122,padding:8},metricIcon:{width:32,height:32,borderRadius:10,alignItems:'center',justifyContent:'center',marginBottom:9},metricLabel:{fontSize:10,lineHeight:13},metricValue:{fontSize:18,fontWeight:'900',marginVertical:5},metricNote:{fontSize:9,lineHeight:12},sectionTitle:{fontSize:18,fontWeight:'900',marginBottom:14},donutWrap:{height:112,alignItems:'center',justifyContent:'center',marginBottom:10},donutTotal:{position:'absolute',alignSelf:'center',textAlign:'center',fontSize:18,fontWeight:'900',marginTop:-70},barRow:{gap:5,marginBottom:12},barTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},barLabel:{flex:1,fontSize:13},track:{height:8,borderRadius:6,overflow:'hidden'},fill:{height:'100%',borderRadius:6},insight:{marginTop:8,padding:12,borderRadius:12,flexDirection:'row',alignItems:'center',gap:9},axis:{flexDirection:'row',justifyContent:'space-between'},axisLabel:{fontSize:10,textAlign:'center',flex:1},split:{flexDirection:'row',flexWrap:'wrap',gap:10},group:{flex:1,minWidth:280},verified:{minHeight:50,borderWidth:1,borderRadius:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,padding:10}});
