import {useState} from 'react';
import {Image,Pressable,Share,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {useQuery} from '@tanstack/react-query';
import {api} from '@/lib/api';
import {Avatar,Card,EmptyState,Muted,Screen,useAppTheme} from '@/components/UI';

type Tab='overview'|'voters'|'details';type Option={Id:string;OptionText:string;ImageUrl?:string;VoteCount:number};type Voter={UserId:string;FirstName:string;LastName:string;ProfileImage?:string;Vote:string;VotedAt:string};
type Analysis={poll:{Id:string;Question:string;Description?:string;ImageUrl?:string;CreatedAt:string;StartAt:string;EndAt?:string;CommunityName:string;EligibleMembers:number;CreatedByName:string;IsAnonymous:boolean;AllowMultiple:boolean;AllowChangeVote:boolean};summary:{totalVoters:number;totalSelections:number;avgMinutesToVote:number|null;turnout:number};options:Option[];voters:Voter[]};
const colors=['#16A34A','#2563EB','#7C3AED','#F59E0B','#0891B2','#DC2626'];

export default function ViewPoll(){const{id,pollId}=useLocalSearchParams<{id:string;pollId:string}>(),{palette}=useAppTheme(),{width}=useWindowDimensions();const[tab,setTab]=useState<Tab>('overview');const query=useQuery<Analysis>({queryKey:['poll-analysis',pollId],queryFn:async()=>(await api.get(`/polls/${pollId}/analysis`)).data});
 if(query.isLoading)return <Screen contentStyle={s.page}><Muted>Loading poll…</Muted></Screen>;if(query.isError||!query.data)return <Screen contentStyle={s.page}><EmptyState icon="lock-closed-outline" title="Poll viewer unavailable" body="This page is available only to administrators and moderators."/></Screen>;const d=query.data,ended=!!d.poll.EndAt&&new Date(d.poll.EndAt)<=new Date();async function share(){await Share.share({title:d.poll.Question,message:`${d.poll.Question}\n${d.summary.totalVoters} voter${d.summary.totalVoters===1?'':'s'} · ${d.summary.turnout}% turnout`})}
 return <Screen scroll contentStyle={s.page}><View style={s.heading}><View style={{flex:1}}><Text style={[s.title,{color:palette.text}]}>View Poll</Text><Muted>{d.poll.CommunityName}</Muted></View><Pressable accessibilityLabel="Share poll" onPress={()=>void share()} style={[s.iconButton,{borderColor:palette.border}]}><Ionicons name="share-outline" size={21} color={palette.text}/></Pressable></View>
 <Card style={s.hero}><View style={s.heroRow}>{d.poll.ImageUrl?<Image source={{uri:d.poll.ImageUrl}} style={s.heroImage}/>:<View style={[s.heroImage,s.placeholder,{backgroundColor:palette.successSoft}]}><Ionicons name="stats-chart" size={30} color={palette.success}/></View>}<View style={s.heroCopy}><Text style={[s.status,{color:palette.success,backgroundColor:palette.successSoft}]}>{ended?'Completed':'Active'}</Text><Text style={[s.question,{color:palette.text}]}>{d.poll.Question}</Text><Muted>Created by {d.poll.CreatedByName} · {new Date(d.poll.CreatedAt).toLocaleDateString()}</Muted></View></View><View style={s.heroMeta}><Meta icon="calendar-outline" text={`${new Date(d.poll.StartAt).toLocaleDateString()}${d.poll.EndAt?` – ${new Date(d.poll.EndAt).toLocaleDateString()}`:''}`} palette={palette}/><Meta icon="people-outline" text={`${d.summary.totalVoters} voter${d.summary.totalVoters===1?'':'s'}`} palette={palette}/><Pressable onPress={()=>router.replace(`/community/${id}/poll/${pollId}/analysis` as any)} style={s.analysis}><Ionicons name="analytics" size={17} color={palette.success}/><Text style={{color:palette.success,fontWeight:'900'}}>View Analysis</Text></Pressable></View></Card>
 <View style={[s.tabs,{borderBottomColor:palette.border}]}>{([{key:'overview',label:'Overview',icon:'bar-chart-outline'},{key:'voters',label:'Voters',icon:'people-outline'},{key:'details',label:'Details',icon:'information-circle-outline'}] as const).map(x=><Pressable key={x.key} onPress={()=>setTab(x.key)} style={[s.tab,tab===x.key&&{borderBottomColor:palette.success}]}><Ionicons name={x.icon} size={18} color={tab===x.key?palette.success:palette.muted}/><Text style={{color:tab===x.key?palette.success:palette.muted,fontWeight:tab===x.key?'900':'700'}}>{x.label}</Text></Pressable>)}</View>
 {tab==='overview'?<Overview data={d} palette={palette} width={width}/>:tab==='voters'?<Voters data={d} palette={palette}/>:<Details data={d} palette={palette}/>}</Screen>}

function Overview({data,palette}:any){const total=data.options.reduce((n:number,x:Option)=>n+x.VoteCount,0),winner=[...data.options].sort((a:Option,b:Option)=>b.VoteCount-a.VoteCount)[0];return <><Card><View style={s.sectionHead}><Text style={[s.sectionTitle,{color:palette.text}]}>Poll Results</Text><Text style={[s.totalBadge,{color:palette.success,backgroundColor:palette.successSoft}]}>{total} total selection{total===1?'':'s'}</Text></View>{data.options.map((x:Option,i:number)=>{const pct=total?Math.round(x.VoteCount/total*100):0;return <View key={x.Id} style={s.result}><View style={s.resultTop}><View style={[s.dot,{backgroundColor:colors[i%colors.length]}]}/><Text style={{color:palette.text,flex:1}}>{x.OptionText}</Text><Text style={{color:palette.text,fontWeight:'900'}}>{pct}% ({x.VoteCount})</Text></View><View style={[s.track,{backgroundColor:palette.backgroundSoft}]}><View style={[s.fill,{backgroundColor:colors[i%colors.length],width:`${pct}%`}]}/></View></View>})}{winner?.VoteCount?<View style={[s.insight,{backgroundColor:palette.successSoft}]}><Ionicons name="trophy-outline" size={21} color={palette.success}/><Text style={{color:palette.text,flex:1}}><Text style={{fontWeight:'900'}}>Leading result: </Text>{winner.OptionText}</Text></View>:null}</Card><View style={s.summary}><Summary value={data.summary.totalVoters} label="Total Voters" palette={palette}/><Summary value={`${data.summary.turnout}%`} label="Turnout" palette={palette}/><Summary value={data.summary.avgMinutesToVote==null?'—':duration(data.summary.avgMinutesToVote)} label="Avg. Time" palette={palette}/></View>{data.poll.Description?<Card><Text style={[s.sectionTitle,{color:palette.text}]}>Description</Text><Muted>{data.poll.Description}</Muted></Card>:null}</>}
function Voters({data,palette}:{data:Analysis;palette:any}){if(data.poll.IsAnonymous)return <EmptyState icon="eye-off-outline" title="Anonymous poll" body="Voter identities are protected for this poll. Aggregate results remain available in Overview and Poll Analysis."/>;return <Card style={s.voterCard}>{data.voters.length?data.voters.map((v,index)=><View key={v.UserId} style={[s.voter,{borderBottomColor:palette.border},index===data.voters.length-1&&{borderBottomWidth:0}]}><Avatar name={`${v.FirstName} ${v.LastName}`} uri={v.ProfileImage} size={45}/><View style={s.voterName}><Text style={{color:palette.text,fontWeight:'900'}}>{v.FirstName} {v.LastName}</Text><Muted numberOfLines={2}>{v.Vote}</Muted></View><Muted style={s.votedAt}>{new Date(v.VotedAt).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}</Muted></View>):<EmptyState icon="people-outline" title="No voters yet" body="Members who vote will appear here unless anonymous voting is enabled."/>}</Card>}
function Details({data,palette}:{data:Analysis;palette:any}){const p=data.poll,ended=!!p.EndAt&&new Date(p.EndAt)<=new Date();return <><Card><Text style={[s.sectionTitle,{color:palette.text}]}>Poll Information</Text><Detail icon="list-outline" label="Poll type" value={p.AllowMultiple?'Multiple choice':'Single choice'} palette={palette}/><Detail icon="person-outline" label="Created by" value={p.CreatedByName} palette={palette}/><Detail icon="calendar-outline" label="Created on" value={new Date(p.CreatedAt).toLocaleString()} palette={palette}/><Detail icon="play-outline" label="Start date" value={new Date(p.StartAt).toLocaleString()} palette={palette}/><Detail icon="stop-circle-outline" label="End date" value={p.EndAt?new Date(p.EndAt).toLocaleString():'No closing date'} palette={palette}/><Detail icon="checkmark-circle-outline" label="Status" value={ended?'Completed':'Active'} palette={palette}/>{p.Description?<Detail icon="document-text-outline" label="Description" value={p.Description} palette={palette}/>:null}</Card><Card><Text style={[s.sectionTitle,{color:palette.text}]}>Voting Settings</Text><Detail icon="checkbox-outline" label="Multiple choices" value={p.AllowMultiple?'Yes':'No'} palette={palette}/><Detail icon="eye-off-outline" label="Anonymous voting" value={p.IsAnonymous?'Yes':'No'} palette={palette}/><Detail icon="refresh-outline" label="Vote changes" value={p.AllowChangeVote?'Allowed':'Not allowed'} palette={palette}/><Detail icon="people-outline" label="Eligible members" value={String(p.EligibleMembers)} palette={palette}/></Card></>}
function Meta({icon,text,palette}:any){return <View style={s.meta}><Ionicons name={icon} size={17} color={palette.success}/><Muted>{text}</Muted></View>}function Summary({value,label,palette}:any){return <Card style={s.summaryCard}><Text numberOfLines={1} adjustsFontSizeToFit style={[s.summaryValue,{color:palette.text}]}>{value}</Text><Muted numberOfLines={2}>{label}</Muted></Card>}function Detail({icon,label,value,palette}:any){return <View style={[s.detail,{borderBottomColor:palette.border}]}><View style={[s.detailIcon,{backgroundColor:palette.successSoft}]}><Ionicons name={icon} size={18} color={palette.success}/></View><Text style={{color:palette.text,flex:1}}>{label}</Text><Text style={[s.detailValue,{color:palette.muted}]}>{value}</Text></View>}function duration(minutes:number){return minutes<60?`${minutes}m`:`${Math.floor(minutes/60)}h ${minutes%60}m`}
const s=StyleSheet.create({page:{width:'100%',maxWidth:850,alignSelf:'center',paddingBottom:125},heading:{flexDirection:'row',alignItems:'center',marginBottom:12},title:{fontSize:23,fontWeight:'900'},iconButton:{width:42,height:42,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center'},hero:{gap:12},heroRow:{flexDirection:'row',alignItems:'center',gap:12},heroImage:{width:68,height:68,borderRadius:34},placeholder:{alignItems:'center',justifyContent:'center'},heroCopy:{flex:1,minWidth:0},status:{alignSelf:'flex-start',paddingHorizontal:8,paddingVertical:3,borderRadius:7,fontWeight:'800'},question:{fontSize:18,lineHeight:23,fontWeight:'900',marginVertical:5},heroMeta:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:12},meta:{flexDirection:'row',alignItems:'center',gap:5},analysis:{marginLeft:'auto',minHeight:38,flexDirection:'row',alignItems:'center',gap:5},tabs:{flexDirection:'row',borderBottomWidth:1,marginVertical:10},tab:{flex:1,minHeight:49,borderBottomWidth:3,borderBottomColor:'transparent',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:5},sectionHead:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',justifyContent:'space-between',gap:8},sectionTitle:{fontSize:18,fontWeight:'900',marginBottom:12},totalBadge:{paddingHorizontal:9,paddingVertical:5,borderRadius:8,fontWeight:'800'},result:{gap:6,marginBottom:14},resultTop:{flexDirection:'row',alignItems:'center',gap:8},dot:{width:11,height:11,borderRadius:6},track:{height:8,borderRadius:6,overflow:'hidden'},fill:{height:'100%',borderRadius:6},insight:{padding:12,borderRadius:12,flexDirection:'row',alignItems:'center',gap:8},summary:{flexDirection:'row',gap:8},summaryCard:{flex:1,minWidth:0,alignItems:'center',padding:10},summaryValue:{fontSize:20,fontWeight:'900',marginBottom:4},voterCard:{paddingVertical:0,overflow:'hidden'},voter:{minHeight:76,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1},voterName:{flex:1,minWidth:0},votedAt:{width:105,textAlign:'right',fontSize:11},detail:{minHeight:58,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:9},detailIcon:{width:34,height:34,borderRadius:10,alignItems:'center',justifyContent:'center'},detailValue:{maxWidth:'52%',textAlign:'right',fontSize:12,lineHeight:17}});
