import {Image,Platform,Pressable,Share,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {useLocalSearchParams,router} from 'expo-router';
import {useQuery} from '@tanstack/react-query';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {useCommunity} from '@/store/community';
import {Avatar,Badge,Card,IconTile,Muted,Screen,useAppTheme} from '@/components/UI';
import type {Announcement,Alert,Conversation,Meeting} from '@/types';

type Action={label:string;icon:keyof typeof Ionicons.glyphMap;route:string;tone?:'blue'|'red'|'green'|'orange'|'purple';description:string};

export default function CommunityScreen(){
 const{id}=useLocalSearchParams<{id:string}>();const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=980;const current=useCommunity(s=>s.current);
 const details=useQuery<any>({queryKey:['community',id],queryFn:async()=>(await api.get(`/communities/${id}`)).data});const c=details.data||current;
 const announcements=useQuery<Announcement[]>({queryKey:['announcements',id],queryFn:async()=>(await api.get(`/communities/${id}/announcements`)).data});
 const meetings=useQuery<Meeting[]>({queryKey:['meetings',id],queryFn:async()=>(await api.get(`/communities/${id}/meetings`)).data});
 const alerts=useQuery<Alert[]>({queryKey:['alerts',id],queryFn:async()=>(await api.get(`/communities/${id}/alerts`)).data});
 const conversations=useQuery<Conversation[]>({queryKey:['conversations',id],queryFn:async()=>(await api.get(`/communities/${id}/conversations`)).data});
 const activeAlert=alerts.data?.find((a:any)=>a.Active!==false);const members=Number(c?.MemberCount||1);const isAdmin=['Admin','Owner'].includes(c?.UserRole);
 const chatRoute=conversations.data?.[0]?`/chat/${conversations.data[0].Id}`:'/(tabs)/chat';
 const connect:Action[]=[{label:'Feed',icon:'newspaper-outline',route:`/community/${id}/feed`,description:'Posts and announcements'},{label:'Members',icon:'people-outline',route:`/community/${id}/members`,description:'Community directory'},{label:'Chat',icon:'chatbubble-ellipses-outline',route:chatRoute,description:'Community conversations'},{label:'Events',icon:'calendar-number-outline',route:`/community/${id}/events`,description:'Meetings and activities'}];
 const life:Action[]=[{label:'Report Issue',icon:'construct-outline',route:`/community/${id}/issues`,tone:'orange',description:'Report community problems'},{label:'Services',icon:'storefront-outline',route:`/community/${id}/services`,tone:'green',description:'Community service directory'},{label:'Marketplace',icon:'bag-handle-outline',route:`/community/${id}/marketplace`,tone:'purple',description:'Buy, sell and trade locally'},{label:'Opportunities',icon:'briefcase-outline',route:`/community/${id}/opportunities`,description:'Jobs, grants and volunteering'}];
 const govern:Action[]=[{label:'Governance',icon:'git-branch-outline',route:`/community/${id}/governance`,description:'Rules, proposals and policies'},{label:'Formal Vote',icon:'checkbox-outline',route:`/community/${id}/formal-voting`,tone:'purple',description:'Participate in formal votes'},{label:'Emergency',icon:'shield-outline',route:`/community/${id}/emergency-command`,tone:'red',description:'Alerts and emergency contacts'},{label:'Member Card',icon:'card-outline',route:`/community/${id}/membership-card`,tone:'green',description:'Your digital member card'}];
 const knowledge:Action[]=[{label:'Documents',icon:'folder-open-outline',route:`/community/${id}/documents`,description:'Files and community records'},{label:'Finances',icon:'wallet-outline',route:`/community/${id}/finance`,tone:'green',description:'Community finance and reports'},{label:'CDA Assistant',icon:'sparkles-outline',route:`/community/${id}/assistant`,tone:'purple',description:'Ask the community assistant'},{label:'Summary',icon:'reader-outline',route:`/community/${id}/smart-summary`,description:'Community overview and insights'}];
 async function shareCommunity(){const message=`Join ${c?.Name||'our community'} on CDA Connect${c?.JoinCode?` using code ${c.JoinCode}`:''}.`;await Share.share({title:c?.Name||'CDA Connect community',message})}
 return <Screen scroll contentStyle={s.flush}>
  <View style={[s.topbar,{backgroundColor:palette.surface,borderBottomColor:palette.border}]}><Pressable accessibilityLabel="Go back" onPress={()=>(router.canGoBack()?router.back():router.replace('/'))} style={s.touch}><Ionicons name="chevron-back" size={24} color={palette.text}/></Pressable><Text numberOfLines={1} style={[s.topTitle,{color:palette.text}]}>{c?.Name||'Community'}</Text><Pressable accessibilityLabel="Community settings" onPress={()=>router.push(`/community/${id}/manage`)} style={s.touch}><Ionicons name="settings-outline" size={23} color={palette.text}/></Pressable></View>
  <View style={[s.banner,{backgroundColor:palette.primaryDark}]}>{c?.BannerUrl?<Image source={{uri:c.BannerUrl}} style={StyleSheet.absoluteFillObject} resizeMode="cover"/>:<View style={s.bannerPattern}><Ionicons name="home-outline" size={84} color="rgba(255,255,255,.22)"/></View>}</View>
  <View style={[s.identity,desktop&&s.identityDesktop]}><View style={[s.avatarRing,{borderColor:palette.surface}]}>{c?.LogoUrl?<Image source={{uri:c.LogoUrl}} style={s.logo}/>:<Avatar name={c?.Name||'Community'} size={desktop?104:76}/>}</View><View style={[s.identityText,desktop&&{alignItems:'flex-start'}]}><View style={s.nameRow}><Text style={[s.name,{color:palette.text}]}>{c?.Name||'Community'}</Text>{c?.IsVerified?<Ionicons name="checkmark-circle" size={21} color={palette.success}/>:null}</View><Muted>Community workspace</Muted><View style={s.meta}><View style={[s.dot,{backgroundColor:palette.success}]}/><Text style={[s.metaText,{color:palette.success}]}>Active</Text><Text style={[s.metaText,{color:palette.muted}]}>•</Text><Ionicons name="people-outline" size={15} color={palette.muted}/><Text style={[s.metaText,{color:palette.muted}]}>{members.toLocaleString()} Members</Text></View></View><View style={s.heroActions}><Pressable onPress={()=>router.push(`/community/${id}/members`)} style={[s.outlineButton,{borderColor:palette.success}]}><Ionicons name="checkmark" size={18} color={palette.success}/><Text style={{color:palette.success,fontWeight:'800'}}>Joined</Text></Pressable><Pressable onPress={shareCommunity} style={[s.outlineButton,{borderColor:palette.border}]}><Ionicons name="share-social-outline" size={18} color={palette.text}/><Text style={{color:palette.text,fontWeight:'800'}}>Share</Text></Pressable>{isAdmin?<Pressable accessibilityLabel="Manage community" onPress={()=>router.push(`/community/${id}/manage`)} style={[s.more,{borderColor:palette.border}]}><Ionicons name="ellipsis-vertical" size={20} color={palette.text}/></Pressable>:null}</View></View>
  <View style={s.content}>
   {activeAlert?<Pressable onPress={()=>router.push(`/community/${id}/emergency-command`)} style={[s.alert,{backgroundColor:palette.dangerSoft,borderColor:palette.danger}]}><Ionicons name="warning" size={22} color={palette.danger}/><View style={{flex:1}}><Text style={{color:palette.danger,fontWeight:'900'}}>{activeAlert.Title}</Text><Muted numberOfLines={1}>{activeAlert.Message}</Muted></View><Ionicons name="chevron-forward" size={19} color={palette.danger}/></Pressable>:null}
   <Card style={s.connectCard}><ActionGrid actions={connect} palette={palette} compact={!desktop}/></Card>
   <View style={desktop?s.desktopColumns:undefined}><View style={{flex:1}}><View style={desktop?s.threeColumns:undefined}><ActionSection title="Community Life" actions={life} palette={palette} desktop={desktop}/><ActionSection title="Govern & Protect" actions={govern} palette={palette} desktop={desktop}/><ActionSection title="Knowledge & Support" actions={knowledge} palette={palette} desktop={desktop}/></View><Upcoming meeting={meetings.data?.[0]} id={id!} palette={palette}/></View>{desktop?<View style={s.aside}><About community={c} members={members} palette={palette}/><Activity announcements={announcements.data||[]} meeting={meetings.data?.[0]} id={id!} palette={palette}/></View>:null}</View>
   {!desktop?<Activity announcements={announcements.data||[]} meeting={meetings.data?.[0]} id={id!} palette={palette}/>:null}
  </View>
 </Screen>
}

function ActionGrid({actions,palette,compact}:{actions:Action[];palette:any;compact:boolean}){return <View style={s.actionGrid}>{actions.map(a=><IconTile key={a.label} icon={a.icon} label={a.label} tone={a.tone} onPress={()=>router.push(a.route as any)}/>)}</View>}
function ActionSection({title,actions,palette,desktop}:{title:string;actions:Action[];palette:any;desktop:boolean}){return <Card style={[s.actionSection,desktop&&{flex:1}]}><View style={s.sectionHead}><Text style={[s.sectionTitle,{color:palette.text}]}>{title}</Text><Pressable onPress={()=>router.push(actions[0].route as any)}><Text style={{color:palette.primary,fontWeight:'800'}}>See all</Text></Pressable></View>{desktop?actions.map(a=><Pressable key={a.label} onPress={()=>router.push(a.route as any)} style={s.actionRow}><View style={[s.smallIcon,{backgroundColor:palette.primarySoft}]}><Ionicons name={a.icon} size={19} color={a.tone==='red'?palette.danger:a.tone==='green'?palette.success:a.tone==='orange'?palette.warning:palette.primary}/></View><View style={{flex:1}}><Text style={{color:palette.text,fontWeight:'800'}}>{a.label}</Text><Muted>{a.description}</Muted></View></Pressable>):<ActionGrid actions={actions} palette={palette} compact/>}</Card>}
function About({community,members,palette}:{community:any;members:number;palette:any}){return <Card><Text style={[s.sectionTitle,{color:palette.text}]}>About {community?.Name||'Community'}</Text><Text style={[s.aboutText,{color:palette.text}]}>{community?.Description||'Connect with residents, share resources and work together for a stronger community.'}</Text><Info icon="calendar-outline" text={`Created ${new Date(community?.CreatedAt||Date.now()).toLocaleDateString()}`} palette={palette}/><Info icon="location-outline" text={[community?.SpecificArea,community?.City,community?.State,community?.Country].filter(Boolean).join(', ')||'Location not provided'} palette={palette}/><Info icon={community?.IsPrivate?'lock-closed-outline':'globe-outline'} text={community?.IsPrivate?'Private Community':'Public Community'} palette={palette}/><Info icon="people-outline" text={`${members.toLocaleString()} active member${members===1?'':'s'}`} palette={palette}/></Card>}
function Info({icon,text,palette}:{icon:keyof typeof Ionicons.glyphMap;text:string;palette:any}){return <View style={s.info}><Ionicons name={icon} size={17} color={palette.muted}/><Muted style={{flex:1}}>{text}</Muted></View>}
function Upcoming({meeting,id,palette}:{meeting?:Meeting;id:string;palette:any}){return <Card><View style={s.sectionHead}><Text style={[s.sectionTitle,{color:palette.text}]}>Upcoming Events</Text><Pressable onPress={()=>router.push(`/community/${id}/events`)}><Text style={{color:palette.primary,fontWeight:'800'}}>See all</Text></Pressable></View>{meeting?<Pressable onPress={()=>router.push(`/community/${id}/events`)} style={s.event}><View style={[s.dateBox,{borderColor:palette.success}]}><Text style={{color:palette.success,fontWeight:'900'}}>{new Date(meeting.StartDateTime).toLocaleString('en',{month:'short'}).toUpperCase()}</Text><Text style={[s.dateNumber,{color:palette.text}]}>{new Date(meeting.StartDateTime).getDate()}</Text></View><View style={{flex:1}}><Text style={{color:palette.text,fontWeight:'900'}}>{meeting.Title}</Text><Muted>{new Date(meeting.StartDateTime).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}</Muted><Muted>{meeting.Location||'Location to be confirmed'}</Muted></View><Ionicons name="chevron-forward" size={20} color={palette.muted}/></Pressable>:<Pressable onPress={()=>router.push(`/community/${id}/events`)} style={s.emptyAction}><Ionicons name="calendar-outline" size={25} color={palette.primary}/><Muted>No upcoming event. Open Events to create or view activities.</Muted></Pressable>}</Card>}
function Activity({announcements,meeting,id,palette}:{announcements:Announcement[];meeting?:Meeting;id:string;palette:any}){const items=[...announcements.slice(0,2).map(a=>({key:a.Id,title:a.Title,body:a.Body,icon:'megaphone-outline' as const,route:`/community/${id}/feed`})),...(meeting?[{key:meeting.Id,title:'Event reminder',body:meeting.Title,icon:'calendar-outline' as const,route:`/community/${id}/events`}]:[])];return <Card><View style={s.sectionHead}><Text style={[s.sectionTitle,{color:palette.text}]}>Recent Activity</Text><Pressable onPress={()=>router.push(`/community/${id}/feed`)}><Text style={{color:palette.primary,fontWeight:'800'}}>See all</Text></Pressable></View>{items.length?items.map(item=><Pressable key={item.key} onPress={()=>router.push(item.route as any)} style={[s.activity,{borderBottomColor:palette.border}]}><View style={[s.smallIcon,{backgroundColor:palette.primarySoft}]}><Ionicons name={item.icon} size={18} color={palette.primary}/></View><View style={{flex:1}}><Text style={{color:palette.text,fontWeight:'800'}}>{item.title}</Text><Muted numberOfLines={2}>{item.body}</Muted></View><Ionicons name="chevron-forward" size={17} color={palette.muted}/></Pressable>):<Muted>New posts, members and event updates will appear here.</Muted>}</Card>}

const s=StyleSheet.create({flush:{paddingHorizontal:0,paddingTop:0,maxWidth:1180},topbar:{height:62,borderBottomWidth:1,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},touch:{width:44,height:44,alignItems:'center',justifyContent:'center'},topTitle:{fontSize:17,fontWeight:'900',maxWidth:'70%'},banner:{height:170,overflow:'hidden',alignItems:'center',justifyContent:'center'},bannerPattern:{alignItems:'center',justifyContent:'center'},identity:{alignItems:'center',paddingHorizontal:18,paddingBottom:18,marginTop:-38},identityDesktop:{flexDirection:'row',alignItems:'flex-end',marginTop:-50,paddingHorizontal:40},avatarRing:{borderWidth:5,borderRadius:60},logo:{width:104,height:104,borderRadius:52},identityText:{alignItems:'center',flex:1,marginTop:8,marginLeft:16},nameRow:{flexDirection:'row',alignItems:'center',gap:7},name:{fontSize:25,fontWeight:'900'},meta:{flexDirection:'row',alignItems:'center',gap:7,marginTop:8},dot:{width:8,height:8,borderRadius:4},metaText:{fontSize:12,fontWeight:'700'},heroActions:{flexDirection:'row',gap:9,marginTop:15},outlineButton:{minHeight:42,minWidth:105,borderWidth:1,borderRadius:10,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,paddingHorizontal:13},more:{width:42,height:42,borderWidth:1,borderRadius:10,alignItems:'center',justifyContent:'center'},content:{paddingHorizontal:18,paddingBottom:24},alert:{borderWidth:1,borderRadius:14,padding:13,marginBottom:12,flexDirection:'row',alignItems:'center',gap:10},connectCard:{paddingVertical:10},actionGrid:{flexDirection:'row',alignItems:'stretch'},desktopColumns:{flexDirection:'row',gap:14,alignItems:'flex-start'},threeColumns:{flexDirection:'row',gap:12},actionSection:{padding:14},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:12},sectionTitle:{fontSize:16,fontWeight:'900'},actionRow:{flexDirection:'row',alignItems:'center',gap:10,minHeight:64},smallIcon:{width:38,height:38,borderRadius:11,alignItems:'center',justifyContent:'center'},aside:{width:285},aboutText:{fontSize:14,lineHeight:21,marginVertical:12},info:{flexDirection:'row',gap:9,alignItems:'center',marginTop:10},event:{flexDirection:'row',alignItems:'center',gap:12},dateBox:{width:58,height:68,borderWidth:1,borderRadius:10,alignItems:'center',justifyContent:'center'},dateNumber:{fontSize:24,fontWeight:'900'},emptyAction:{flexDirection:'row',alignItems:'center',gap:10,minHeight:60},activity:{flexDirection:'row',alignItems:'center',gap:10,minHeight:68,borderBottomWidth:1}});
