import {Alert,Image,Platform,Pressable,Share,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {useLocalSearchParams,router} from 'expo-router';
import {useQuery} from '@tanstack/react-query';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {useCommunity} from '@/store/community';
import {useAuth} from '@/store/auth';
import {Avatar,Card,Muted,Screen,useAppTheme} from '@/components/UI';
import type {Alert as CommunityAlert} from '@/types';

type Action={label:string;icon:keyof typeof Ionicons.glyphMap;route:string;tone?:'blue'|'red'|'green'|'orange'|'purple';description:string};

export default function CommunityScreen(){
 const{id}=useLocalSearchParams<{id:string}>();const{palette}=useAppTheme();const{width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=980;const current=useCommunity(s=>s.current);const user=useAuth(s=>s.user);
 const details=useQuery<any>({queryKey:['community',id],queryFn:async()=>(await api.get(`/communities/${id}`)).data});const c=details.data||current;
 const alerts=useQuery<CommunityAlert[]>({queryKey:['alerts',id],queryFn:async()=>(await api.get(`/communities/${id}/alerts`)).data});
 const capabilities=useQuery<any>({queryKey:['capabilities',id],queryFn:async()=>(await api.get(`/communities/${id}/capabilities`)).data});
 const activeAlert=alerts.data?.find((a:any)=>a.Active!==false);const members=Number(c?.MemberCount||1);const capabilityRoles:string[]=capabilities.data?.roles||[];const communityRole=[c?.UserRole,c?.Role,c?.Roles,...capabilityRoles].filter(Boolean).join(',').toUpperCase();const isOwner=!!c?.OwnerUserId&&String(c.OwnerUserId).toLowerCase()===String(user?.Id||'').toLowerCase();const isAdmin=isOwner||capabilities.data?.isOwner||capabilities.data?.canManageCommunity||communityRole.includes('ADMIN')||communityRole.includes('OWNER');
 const chatRoute=`/community/${id}/chat`;
 const connect:Action[]=[{label:'Feed',icon:'newspaper-outline',route:`/community/${id}/feed`,description:'Posts and announcements'},{label:'Members',icon:'people-outline',route:`/community/${id}/members`,description:'Community directory'},{label:'Chat',icon:'chatbubble-ellipses-outline',route:chatRoute,description:'Community conversations'},{label:'Events',icon:'calendar-number-outline',route:`/community/${id}/events`,description:'Meetings and activities'}];
 const canTakeAttendance=capabilities.data?.permissions?.includes('ATTENDANCE_MANAGE');
 const canManageFinance=capabilities.data?.permissions?.includes('FINANCE_MANAGE');
 const platform:Action[]=[{label:'Meetings',icon:'people-circle-outline',route:`/community/${id}/meetings`,tone:'green',description:'Upcoming and past community meetings'},{label:'Excos',icon:'ribbon-outline',route:`/community/${id}/excos`,tone:'green',description:'Executive committee appointments'},...(canTakeAttendance?[{label:'Take Attendance',icon:'qr-code-outline' as const,route:`/community/${id}/take-attendance`,tone:'green' as const,description:'Scan cards or mark members present'}]:[]),{label:'Mark Attendance',icon:'checkmark-done-circle-outline',route:`/community/${id}/mark-attendance`,tone:'green',description:'Check in using the meeting code'},{label:'Attendance History',icon:'time-outline',route:`/community/${id}/attendance-history`,tone:'green',description:'Past meetings and participants'},...(canManageFinance?[{label:'Financial Record',icon:'wallet-outline' as const,route:`/community/${id}/financial-record`,tone:'green' as const,description:'Create levies and approve payments'}]:[]),{label:'My Financial Record',icon:'receipt-outline',route:`/community/${id}/my-financial-record`,tone:'green',description:'View and pay your assigned levies'}];
 const life:Action[]=[{label:'Report Issue',icon:'construct-outline',route:`/community/${id}/issues`,tone:'orange',description:'Report community problems'},{label:'Services',icon:'storefront-outline',route:`/community/${id}/services`,tone:'green',description:'Community service directory'},{label:'Marketplace',icon:'bag-handle-outline',route:`/community/${id}/marketplace`,tone:'purple',description:'Buy, sell and trade locally'},{label:'Calendar',icon:'calendar-outline',route:'/(tabs)/calendar',tone:'green',description:'Community events and schedules'}];
 const canManageCommunity=isAdmin||capabilities.data?.permissions?.includes('COMMUNITY_EDIT')||capabilities.data?.permissions?.includes('MEMBER_ROLE_CHANGE');
 const canManageEmergency=capabilities.data?.permissions?.includes('EMERGENCY_MANAGE');const canScanMembers=capabilities.data?.permissions?.includes('MEMBERSHIP_SCAN')||canTakeAttendance;const govern:Action[]=[{label:'Governance',icon:'git-branch-outline',route:`/community/${id}/governance`,description:'Rules, proposals and policies'},{label:'Alerts',icon:'shield-outline',route:`/community/${id}/alerts`,tone:'red',description:'Emergency alerts for this community'},{label:'Member Card',icon:'card-outline',route:`/community/${id}/membership-card`,tone:'green',description:'Your digital member card'},{label:'Polls',icon:'stats-chart-outline',route:`/community/${id}/polls`,tone:'purple',description:'Community polls and voting'},{label:'Document Centre',icon:'folder-open-outline',route:`/community/${id}/documents`,description:'Community files and records'},...(canManageEmergency?[{label:'Emergency Command',icon:'warning-outline' as const,route:`/community/${id}/emergency-command`,tone:'red' as const,description:'Create and manage emergency alerts'}]:[]),...(canScanMembers?[{label:'Scan Member QR',icon:'qr-code-outline' as const,route:`/community/${id}/scan-card`,description:'Verify member credentials'}]:[]),...(canManageCommunity?[{label:'Verification',icon:'shield-checkmark-outline' as const,route:`/community/${id}/verification`,tone:'green' as const,description:'Official community verification'},{label:'Admin Analytics',icon:'analytics-outline' as const,route:`/community/${id}/analytics`,description:'Community activity and insights'}]:[])];
 const remainingAdminActions:Action[]=canManageCommunity?[{label:'Community Profile',icon:'business-outline',route:`/community/${id}/community-profile`,tone:'green',description:'Edit the created community and its public identity'}]:[];
 function inviteUrl(){const code=encodeURIComponent(c?.JoinCode||'');if(Platform.OS==='web'&&typeof window!=='undefined')return `${window.location.origin}/join-community?code=${code}`;const configured=process.env.EXPO_PUBLIC_APP_URL;if(configured)return `${configured.replace(/\/$/,'')}/join-community?code=${code}`;try{const apiUrl=new URL(process.env.EXPO_PUBLIC_API_URL||'');return `${apiUrl.protocol}//${apiUrl.hostname}/join-community?code=${code}`}catch{return `https://www.cdaconnect.org/join-community?code=${code}`}}
 async function copyInviteCode(){const code=c?.JoinCode;if(!code)return Alert.alert('Invite code unavailable','Please refresh this community and try again.');if(Platform.OS==='web'&&typeof navigator!=='undefined'&&navigator.clipboard){await navigator.clipboard.writeText(code);Alert.alert('Invite code copied',code);return}await Share.share({title:'Community invite code',message:code});Alert.alert('Invite code copied',code)}
 async function shareCommunity(){const url=inviteUrl();const message=`Join ${c?.Name||'our community'} on CDA Connect. Invite code: ${c?.JoinCode}. ${url}`;await Share.share({title:c?.Name||'CDA Connect community',message,url})}
 const profileLocation=[c?.SpecificArea||c?.City,c?.State].filter(Boolean).join(', ');const establishedYear=c?.CreatedAt?new Date(c.CreatedAt).getFullYear():null;
 return <Screen scroll contentStyle={s.flush}>
  <View style={[s.banner,{backgroundColor:palette.primaryDark}]}>{c?.BannerUrl?<Image source={{uri:c.BannerUrl}} style={StyleSheet.absoluteFill} resizeMode="cover"/>:<View style={s.bannerPattern}><Ionicons name="home-outline" size={84} color="rgba(255,255,255,.22)"/></View>}</View>
  <View style={[s.identity,desktop&&s.identityDesktop]}><View style={[s.avatarRing,{borderColor:palette.surface,backgroundColor:palette.surface}]}>{c?.LogoUrl?<Image source={{uri:c.LogoUrl}} style={s.logo}/>:<Avatar name={c?.Name||'Community'} size={desktop?104:96}/>}</View>{!desktop?<View style={[s.profileActions,{borderColor:palette.border,backgroundColor:palette.surface}]}><Pressable accessibilityRole="button" accessibilityLabel="Open community profile" onPress={()=>router.push(`/community/${id}/community-profile` as any)} style={s.profileAction}><Ionicons name="business-outline" size={22} color="#000000"/></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Copy community invite code" onPress={()=>void copyInviteCode()} style={s.profileAction}><Ionicons name="key-outline" size={22} color="#000000"/></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Share community" onPress={()=>void shareCommunity()} style={s.profileAction}><Ionicons name="share-social-outline" size={22} color="#000000"/></Pressable></View>:null}<View style={s.identityText}><View style={s.nameRow}><Text style={[s.name,{color:palette.text}]}>{c?.Name||'Community'}</Text>{c?.IsVerified?<Ionicons name="checkmark-circle" size={21} color={palette.success}/>:null}</View><Muted>Community workspace</Muted><View style={s.meta}><Ionicons name="people-outline" size={15} color={palette.muted}/><Text style={[s.metaText,{color:palette.muted}]}>{members.toLocaleString()} Members</Text>{profileLocation?<><Text style={[s.metaText,{color:palette.muted}]}>•</Text><Ionicons name="location-outline" size={15} color={palette.muted}/><Text numberOfLines={1} style={[s.metaText,{color:palette.muted}]}>{profileLocation}</Text></>:null}{establishedYear?<><Text style={[s.metaText,{color:palette.muted}]}>•</Text><Text style={[s.metaText,{color:palette.muted}]}>Est. {establishedYear}</Text></>:null}</View></View></View>
  <View style={s.content}>
   {activeAlert?<Pressable onPress={()=>router.push(`/community/${id}/emergency-command`)} style={[s.alert,{backgroundColor:palette.dangerSoft,borderColor:palette.danger}]}><Ionicons name="warning" size={22} color={palette.danger}/><View style={{flex:1}}><Text style={{color:palette.danger,fontWeight:'900'}}>{activeAlert.Title}</Text><Muted numberOfLines={1}>{activeAlert.Message}</Muted></View><Ionicons name="chevron-forward" size={19} color={palette.danger}/></Pressable>:null}
   <Card style={s.connectCard}><ActionGrid actions={connect} palette={palette} columns={4}/></Card>
   <View style={desktop?s.desktopColumns:undefined}><View style={{flex:1}}><ActionSection title="CDA Platform" actions={platform} palette={palette} desktop={desktop}/><View style={desktop?s.threeColumns:undefined}><ActionSection title="Community Life" actions={life} palette={palette} desktop={desktop}/><ActionSection title="Govern & Protect" actions={[...govern,...remainingAdminActions]} palette={palette} desktop={desktop}/></View></View>{desktop?<View style={s.aside}><About community={c} members={members} palette={palette}/></View>:null}</View>
  </View>
 </Screen>
}

function actionColor(action:Action,palette:any){return action.tone==='red'?palette.danger:action.tone==='orange'?palette.warning:action.tone==='purple'?palette.primary:palette.success}
function ActionGrid({actions,palette,columns}:{actions:Action[];palette:any;columns:3|4}){return <View style={s.actionGrid}>{actions.map(a=><View key={a.label} style={[s.actionItem,{width:columns===4?'25%':'33.333%'}]}><Pressable accessibilityRole="button" accessibilityLabel={a.label} onPress={()=>router.push(a.route as any)} style={({pressed})=>[s.gridAction,pressed&&s.actionPressed]}><Ionicons name={a.icon} size={columns===4?30:32} color={actionColor(a,palette)}/><Text numberOfLines={2} style={[s.gridLabel,{color:palette.text}]}>{a.label}</Text></Pressable></View>)}</View>}
function ActionSection({title,actions,palette,desktop}:{title:string;actions:Action[];palette:any;desktop:boolean}){return <Card style={[s.actionSection,desktop&&{flex:1}]}><View style={s.sectionHead}><Text style={[s.sectionTitle,{color:palette.text}]}>{title}</Text></View>{desktop?actions.map(a=><Pressable key={a.label} onPress={()=>router.push(a.route as any)} style={s.actionRow}><View style={s.smallIcon}><Ionicons name={a.icon} size={27} color={actionColor(a,palette)}/></View><View style={{flex:1}}><Text style={{color:palette.text,fontWeight:'800'}}>{a.label}</Text><Muted>{a.description}</Muted></View></Pressable>):<ActionGrid actions={actions} palette={palette} columns={4}/>}</Card>}
function About({community,members,palette}:{community:any;members:number;palette:any}){return <Card><Text style={[s.sectionTitle,{color:palette.text}]}>About {community?.Name||'Community'}</Text><Text style={[s.aboutText,{color:palette.text}]}>{community?.Description||'Connect with residents, share resources and work together for a stronger community.'}</Text><Info icon="calendar-outline" text={`Created ${new Date(community?.CreatedAt||Date.now()).toLocaleDateString()}`} palette={palette}/><Info icon="location-outline" text={[community?.SpecificArea,community?.City,community?.State,community?.Country].filter(Boolean).join(', ')||'Location not provided'} palette={palette}/><Info icon={community?.IsPrivate?'lock-closed-outline':'globe-outline'} text={community?.IsPrivate?'Private Community':'Public Community'} palette={palette}/><Info icon="people-outline" text={`${members.toLocaleString()} active member${members===1?'':'s'}`} palette={palette}/></Card>}
function Info({icon,text,palette}:{icon:keyof typeof Ionicons.glyphMap;text:string;palette:any}){return <View style={s.info}><Ionicons name={icon} size={17} color={palette.muted}/><Muted style={{flex:1}}>{text}</Muted></View>}

const s=StyleSheet.create({flush:{paddingHorizontal:0,paddingTop:0,maxWidth:1180},banner:{height:170,overflow:'hidden',alignItems:'center',justifyContent:'center'},bannerPattern:{alignItems:'center',justifyContent:'center'},identity:{position:'relative',alignItems:'flex-start',paddingHorizontal:18,paddingBottom:16,marginTop:-38},identityDesktop:{flexDirection:'row',alignItems:'flex-end',marginTop:-50,paddingHorizontal:40},avatarRing:{borderWidth:5,borderRadius:60,overflow:'hidden'},logo:{width:104,height:104,borderRadius:52},profileActions:{position:'absolute',right:18,top:47,height:46,borderRadius:13,borderWidth:1,flexDirection:'row',alignItems:'center',paddingHorizontal:3},profileAction:{width:42,height:42,alignItems:'center',justifyContent:'center'},identityText:{alignItems:'flex-start',flex:1,marginTop:8},nameRow:{flexDirection:'row',alignItems:'center',gap:7},name:{fontSize:25,fontWeight:'900'},meta:{maxWidth:'100%',flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:6,marginTop:8},dot:{width:8,height:8,borderRadius:4},metaText:{fontSize:12,fontWeight:'700',flexShrink:1},more:{width:42,height:42,borderWidth:1,borderRadius:10,alignItems:'center',justifyContent:'center'},content:{paddingHorizontal:18,paddingBottom:24},alert:{borderWidth:1,borderRadius:14,padding:13,marginBottom:12,flexDirection:'row',alignItems:'center',gap:10},connectCard:{paddingVertical:8,paddingHorizontal:6},actionGrid:{flexDirection:'row',flexWrap:'wrap',alignItems:'stretch'},actionItem:{alignItems:'stretch',paddingHorizontal:0},gridAction:{minHeight:82,alignItems:'center',justifyContent:'center',gap:9,paddingHorizontal:0},gridLabel:{fontSize:12,fontWeight:'800',lineHeight:16,textAlign:'center'},actionPressed:{opacity:.65,transform:[{scale:.97}]},desktopColumns:{flexDirection:'row',gap:14,alignItems:'flex-start'},threeColumns:{flexDirection:'row',gap:12},actionSection:{paddingHorizontal:8,paddingVertical:12},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:8,paddingHorizontal:4},sectionTitle:{fontSize:16,fontWeight:'900'},actionRow:{flexDirection:'row',alignItems:'center',gap:10,minHeight:64},smallIcon:{width:40,height:40,alignItems:'center',justifyContent:'center'},aside:{width:285},aboutText:{fontSize:14,lineHeight:21,marginVertical:12},info:{flexDirection:'row',gap:9,alignItems:'center',marginTop:10},event:{flexDirection:'row',alignItems:'center',gap:12},dateBox:{width:58,height:68,borderWidth:1,borderRadius:10,alignItems:'center',justifyContent:'center'},dateNumber:{fontSize:24,fontWeight:'900'},emptyAction:{flexDirection:'row',alignItems:'center',gap:10,minHeight:60},activity:{flexDirection:'row',alignItems:'center',gap:10,minHeight:68,borderBottomWidth:1}});
