import {Alert,Linking,Platform,StyleSheet,Text,View,useWindowDimensions} from '@/platform/react-native';
import {useLocalSearchParams} from '@/router';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Ionicons} from '@/platform/icons';
import {api} from '@/lib/api';
import {Avatar,Badge,Button,Card,EmptyState,Muted,Screen,useAppTheme} from '@/components/UI';

type AgendaItem={Id:string;Title:string;Description?:string;Position:number;DurationMinutes?:number};
type Attendee={UserId:string;FirstName:string;LastName:string;ProfileImage?:string};
type MeetingDetail={Id:string;CommunityId:string;CommunityName:string;Title:string;Description?:string;Location?:string;OnlineMeetingUrl?:string;StartDateTime:string;EndDateTime:string;MeetingType?:string;AllowRegistration:boolean;AllowCalendar:boolean;HostedBy:string;MyResponse?:'GOING'|'MAYBE'|'NOT_GOING';GoingCount:number;agenda:AgendaItem[];attendees:Attendee[]};

export default function MeetingDetails(){
 const{id,meetingId}=useLocalSearchParams<{id:string;meetingId:string}>();const{palette}=useAppTheme();const{width}=useWindowDimensions();const narrow=width<480;const tiny=width<370;const qc=useQueryClient();
 const query=useQuery<MeetingDetail>({queryKey:['meeting',meetingId],queryFn:async()=>(await api.get(`/meetings/${meetingId}`)).data,enabled:!!meetingId});
 const rsvp=useMutation({mutationFn:async(response:'GOING'|'MAYBE'|'NOT_GOING')=>api.post(`/meetings/${meetingId}/rsvp`,{response}),onSuccess:()=>{qc.invalidateQueries({queryKey:['meeting',meetingId]});qc.invalidateQueries({queryKey:['meetings',id]})},onError:(e:any)=>Alert.alert('Unable to update RSVP',e.response?.data?.message||e.message)});
 if(query.isLoading)return <Screen><Muted>Loading meeting…</Muted></Screen>;if(!query.data)return <Screen><EmptyState icon="calendar-outline" title="Meeting unavailable" body="This meeting could not be found or you no longer have access."/></Screen>;const meeting=query.data;
 const start=new Date(meeting.StartDateTime),end=new Date(meeting.EndDateTime),past=end.getTime()<Date.now(),duration=Math.max(1,Math.round((end.getTime()-start.getTime())/60000));
 async function addCalendar(){try{if(Platform.OS==='web'){const clean=(v:string)=>new Date(v).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nSUMMARY:${meeting.Title}\nDTSTART:${clean(meeting.StartDateTime)}\nDTEND:${clean(meeting.EndDateTime)}\nLOCATION:${meeting.Location||''}\nDESCRIPTION:${(meeting.Description||'').replace(/\n/g,' ')}\nEND:VEVENT\nEND:VCALENDAR`;const url=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download=`${meeting.Title.replace(/[^a-z0-9]+/gi,'-')}.ics`;a.click();URL.revokeObjectURL(url);return}const Calendar=await import('@/platform/calendar');const permission=await Calendar.requestCalendarPermissionsAsync();if(permission.status==='granted')await Calendar.createEventInCalendarAsync({title:meeting.Title,startDate:start,endDate:end,location:meeting.Location,notes:meeting.Description})}catch{Alert.alert('Calendar unavailable','The meeting could not be added to your device calendar.')}}
 return <Screen scroll contentStyle={s.page}>
  <View style={[s.hero,narrow&&s.heroNarrow,tiny&&s.heroTiny,{backgroundColor:palette.primaryDark}]}><Badge text={past?'PAST MEETING':'UPCOMING'} tone={past?'gray':'green'}/><Text style={[s.heroTitle,narrow&&s.heroTitleNarrow,tiny&&s.heroTitleTiny]}>{meeting.Title}</Text><Text style={[s.heroText,tiny&&s.heroTextTiny]}>Your voice. Your community.</Text></View>
  <Card style={[s.facts,narrow&&s.factsNarrow]}><Fact compact={narrow} icon="calendar-outline" label="Date" value={start.toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short',year:'numeric'})} palette={palette}/><Fact compact={narrow} icon="time-outline" label="Time" value={`${start.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} – ${end.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}\n${duration<60?`${duration} minutes`:`${Math.round(duration/60*10)/10} hours`}`} palette={palette}/><Fact compact={narrow} icon={meeting.OnlineMeetingUrl?'videocam-outline':'location-outline'} label="Location" value={meeting.OnlineMeetingUrl?'Online meeting':meeting.Location||'To be confirmed'} palette={palette}/><Fact compact={narrow} icon="people-outline" label="Hosted By" value={`${meeting.HostedBy}\n${meeting.MeetingType||'Community meeting'}`} palette={palette}/></Card>
  {!past?<Card style={[s.notice,narrow&&s.noticeNarrow,{backgroundColor:palette.successSoft}]}><View style={s.noticeCopy}><Ionicons name="megaphone-outline" size={29} color={palette.success}/><View style={{flex:1,minWidth:0}}><Text style={{color:palette.success,fontWeight:'900'}}>All members are encouraged to attend</Text><Muted>Stay informed and take part in community decisions.</Muted></View></View>{meeting.AllowCalendar?<View style={narrow?s.noticeButton:undefined}><Button title="Add to Calendar" icon="calendar-outline" variant="secondary" onPress={addCalendar}/></View>:null}</Card>:null}
  <Card><Text style={[s.sectionTitle,{color:palette.text}]}>About the Meeting</Text><Text style={[s.body,{color:palette.text}]}>{meeting.Description||'No meeting description has been provided.'}</Text>{!past&&meeting.OnlineMeetingUrl?<Button title="Join online meeting" icon="videocam-outline" onPress={()=>Linking.openURL(meeting.OnlineMeetingUrl!)}/>:null}</Card>
  <Card><View style={s.sectionHead}><View style={s.headingRow}><Ionicons name="document-text-outline" size={22} color={palette.primary}/><Text style={[s.sectionTitle,{color:palette.text}]}>Agenda</Text></View><Muted>{meeting.agenda.length} item{meeting.agenda.length===1?'':'s'}</Muted></View>{meeting.agenda.length?meeting.agenda.map((item,index)=><View key={item.Id} style={[s.agendaRow,{borderBottomColor:palette.border}]}><View style={[s.number,{backgroundColor:palette.primary}]}><Text style={s.numberText}>{index+1}</Text></View><View style={{flex:1}}><Text style={{color:palette.text,fontWeight:'800'}}>{item.Title}</Text>{item.Description?<Muted>{item.Description}</Muted>:null}</View>{item.DurationMinutes?<Muted>{item.DurationMinutes} min</Muted>:null}</View>):<Muted>No agenda has been published for this meeting.</Muted>}</Card>
  <Card><View style={s.sectionHead}><View style={s.headingRow}><Ionicons name="people-outline" size={22} color={palette.primary}/><Text style={[s.sectionTitle,{color:palette.text}]}>Who’s Attending</Text></View><Text style={{color:palette.primary,fontWeight:'900'}}>{meeting.GoingCount||0} Going</Text></View>{meeting.attendees.length?<View style={s.avatars}>{meeting.attendees.slice(0,12).map(person=><Avatar key={person.UserId} name={`${person.FirstName} ${person.LastName}`} uri={person.ProfileImage} size={48}/>)}</View>:<Muted>No members have confirmed attendance yet.</Muted>}</Card>
  {!past&&meeting.AllowRegistration?<View style={s.rsvp}><View style={s.rsvpButton}><Button accessibilityLabel="I’m Attending" title="Going" icon="checkmark-circle" variant={meeting.MyResponse==='GOING'?'success':'secondary'} loading={rsvp.isPending} onPress={()=>rsvp.mutate('GOING')}/></View><View style={s.rsvpButton}><Button title="Maybe" icon="help-circle-outline" variant={meeting.MyResponse==='MAYBE'?'success':'secondary'} disabled={rsvp.isPending} onPress={()=>rsvp.mutate('MAYBE')}/></View><View style={s.rsvpButton}><Button title="Can’t attend" icon="close-circle-outline" variant={meeting.MyResponse==='NOT_GOING'?'success':'secondary'} disabled={rsvp.isPending} onPress={()=>rsvp.mutate('NOT_GOING')}/></View></View>:<Card style={[s.completed,{backgroundColor:palette.backgroundSoft}]}><Ionicons name="checkmark-done-circle-outline" size={25} color={palette.muted}/><Muted>{past?'This meeting has ended. Attendance responses are now closed.':'Registration is disabled for this meeting.'}</Muted></Card>}
 </Screen>
}

function Fact({icon,label,value,palette,compact}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:string;palette:any;compact:boolean}){return <View style={[s.fact,compact&&s.factCompact,{borderColor:palette.border}]}><Ionicons name={icon} size={25} color={palette.primary}/><Muted>{label}</Muted><Text style={{color:palette.text,fontWeight:'800',textAlign:'center',fontSize:12,lineHeight:18}}>{value}</Text></View>}
const s=StyleSheet.create({page:{width:'100%',maxWidth:920,alignSelf:'center',paddingBottom:150},hero:{minHeight:190,borderRadius:22,padding:28,justifyContent:'center',overflow:'hidden'},heroNarrow:{minHeight:175,padding:20},heroTiny:{minHeight:160,padding:17},heroTitle:{color:'#fff',fontSize:33,fontWeight:'900',maxWidth:'100%',marginTop:17},heroTitleNarrow:{fontSize:27,lineHeight:33,marginTop:14},heroTitleTiny:{fontSize:23,lineHeight:28},heroText:{color:'#fff',fontSize:16,fontWeight:'700',marginTop:13,maxWidth:'100%'},heroTextTiny:{fontSize:13},facts:{flexDirection:'row',paddingVertical:14},factsNarrow:{flexWrap:'wrap',paddingVertical:4},fact:{flex:1,minHeight:115,alignItems:'center',justifyContent:'center',gap:6,borderRightWidth:1,paddingHorizontal:6},factCompact:{flexGrow:0,flexBasis:'50%',minHeight:108,borderBottomWidth:1},notice:{flexDirection:'row',alignItems:'center',gap:13},noticeNarrow:{alignItems:'stretch',flexDirection:'column',gap:8},noticeCopy:{flex:1,minWidth:0,flexDirection:'row',alignItems:'center',gap:12},noticeButton:{width:'100%'},sectionTitle:{fontSize:17,fontWeight:'900'},body:{fontSize:14,lineHeight:22,marginTop:9,marginBottom:10},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:10},headingRow:{flexDirection:'row',alignItems:'center',gap:9,minWidth:0},agendaRow:{minHeight:58,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1},number:{width:25,height:25,borderRadius:13,alignItems:'center',justifyContent:'center'},numberText:{color:'#fff',fontWeight:'900'},avatars:{flexDirection:'row',gap:9,flexWrap:'wrap'},rsvp:{width:'100%',flexDirection:'row',gap:6,alignItems:'stretch'},rsvpButton:{flex:1,minWidth:0},completed:{flexDirection:'row',alignItems:'center',gap:10}});
